### ISSUE TITLE
[Mentions] Provision for different Replacement Text

### ISSUE THREAD

**Issue by sirajulm** [draft-js-plugins/draft-js-plugins#1001]
Hi, 
First of all thanks for all the great work behind in maintaining such a feature rich plugins for DraftJS editor.

I've a clarification about the mention plugin. Could you help me know the complete structure of the mentions JSON. I'm not able to understand how it works exactly. 

## Use-case/Problem
My use case is like, I'd need one label to be shown for the suggestions dropdown and once a suggestion is selected. the editor text that come up to be another value.

Eg: 
```
{
    label: 'Page title', 
    value: '{{page-title}}'
}
```
Using the above sample I'd need to show the text "Page title" in the dropdown. and the once that is selected the editor will be recieving the value "{{page-title}}"

Would be good if someone could provide an insight on how it can be done with draftjs-mention-plugin

Thanks.

**Comment by tumetus** [comment]
Hi @sirajulm !

I don't have working code example of this but as far as I have understood the workings of the mention plugin, you can use mentionComponent and entryComponent props to achieve this.

createMentionPlugin() accepts the **mentionComponent** prop. _If provided the passed component is used to render a Mention. It receives the following props: entityKey, mention, className & decoratedText_
MentionSuggestions accepts the **entryComponent** prop. _Component to be used as the template for each of the suggestions entry._
(https://www.draft-js-plugins.com/plugin/mention)

So with these components you can determine that you use the "label" for the suggestion dropdown (=entryComponent) and the "value" for the editor text (=mentionComponent).

Hope this helps 🙂

**Comment by sirajulm** [comment]
@tumetus Thanks a lot for the response. It works with using the Entry component :)

**Comment by juliankrispel** [comment]
Thanks @tumetus for tackling this 🙌

**Comment by Alizeh-Asim** [comment]
@sirajulm could you please explain how you achieved that?
