### ISSUE TITLE
Mention - Suggestion popup doesn't show when using rich text utills

### ISSUE THREAD

**Issue by moleynik** [draft-js-plugins/draft-js-plugins#1007]
## Version
"draft-js": "^0.10.4"
"draft-js-export-html": "^1.2.0"
"draft-js-linkify-plugin": "^2.0.1"
"draft-js-mention-plugin": "^2.0.1"
"draft-js-plugins-editor": "^2.0.3"
"draft-js-static-toolbar-plugin": "^2.0.1"
## Steps

1. start typing text
2. typing space [\s]
3. pushing button [B] or [Ctrl+B] [Cmd+B]
4. typing [@]
## Result
The mention suggestion popup doesn't appear.
<img width="1014" alt="withboldstyle" src="https://user-images.githubusercontent.com/1118829/34517972-d905d12c-f085-11e7-90a3-5600d30cc7e8.png">
And
<img width="1012" alt="withboldstyle2" src="https://user-images.githubusercontent.com/1118829/34517993-f713dbbe-f085-11e7-9341-f6a7a632ff85.png">
## Correct work
If without any style, then the mention suggestion is working correct.
<img width="1015" alt="withoutanystyle" src="https://user-images.githubusercontent.com/1118829/34518034-246c4d44-f086-11e7-9ac7-afdea1867e1b.png">

## Question
What could be reason for this behavior?

**Comment by dem** [comment]
@moleynik  It is highly probable, that this problem is fixed by this pull request 
https://github.com/draft-js-plugins/draft-js-plugins/pull/1003/files

Could you please check it this fix works for you?

**Comment by moleynik** [comment]
@dem Yes, this fix solves my problem. Thank you.

**Comment by moleynik** [comment]
Fixed in: https://github.com/draft-js-plugins/draft-js-plugins/pull/1003/files
