### ISSUE TITLE
Multiple instances of MentionSuggestions, onSearchChange only called for last one

### ISSUE THREAD

**Issue by LarsLiden** [draft-js-plugins/draft-js-plugins#1009]
Having issues with multiple instances on the same parent component, specifically, onSearchChange is only called for the last one I create.  Followed example in #298 (i.e. create plugin in constructor) but problem still exists.

My parent component, creates multiple instances like this:

 {...somecode...}.map(slot =>
 {
        return (
         <MyChildComponent
              editorState={this.state.editorStates[slot.key] || EditorState.createEmpty()}
               key={slot.key}
               placeholder={''}
               onChange={eState => this.onChangeMentionEditor(eState, slot.key)}
             >
         )
 })
My MyChildComponent is:

constructor(p: Props) {
    super(p);
 
    this.mentionPlugin = createMentionPlugin({
        entityMutability: 'IMMUTABLE',
        mentionPrefix: mentionTrigger,
        mentionTrigger,
    })
  }

render() {
   const { MentionSuggestions } = this.mentionPlugin;
   const plugins = [this.mentionPlugin];

    return (
      <div>
          <Editor
            placeholder={this.props.placeholder}
            editorState={this.props.editorState}
            onChange={this.onChange}
            plugins={plugins}
            ref={this.setDomEditorRef}
            onFocus={this.onFocus}
            onBlur={this.onBlur}
            readOnly={this.props.disabled}
          />
          <MentionSuggestions
            onSearchChange={this.onSearchChange}
            suggestions={this.state.suggestions}
            entryComponent={CustomEntryComponent}
          />
        </div>
    )
  }

**Comment by juliankrispel** [comment]
Hi @larsliden - please provide a codepen or a codesandbox example that reproduces this bug - until then I’ll close this issue - apologies for the late reply :/

**Comment by dimitar-nikovski** [comment]
@LarsLiden I wonder whether you found a way?
