### ISSUE TITLE
Make entity and block type configurable

### ISSUE THREAD

**Issue by simsim0709** [draft-js-plugins/draft-js-plugins#1014]
## Use-case/Problem

Currently, it's not possible to change entity and block type, because it's hardcoded.
For example, the entity type of `draft-js-image-plugin` is 'image'. But, I want it to be 'IMAGE' or 'AVATAR_IMAGE' or something else. Not only that, other plugins that handle entity or block type such as `draft-js-emoji-plugin`, `draft-js-video-plugin` are same situation, as described above.

So, my suggestion is because every draft-js-plugins accept config parameter,  add entityType or blockType property to make users customize entity or block type.

For example, `draft-js-image-plugin` index.js

```javascript
export default (config = **{ entityType = 'image' }**) => {
  const theme = config.theme ? config.theme : defaultTheme;
  let Image = config.imageComponent || ImageComponent;
  if (config.decorator) {
    Image = config.decorator(Image);
  }
  const ThemedImage = decorateComponentWithProps(Image, { theme });
  return {
    blockRendererFn: (block, { getEditorState }) => {
      if (block.getType() === 'atomic') {
        const contentState = getEditorState().getCurrentContent();
        const entity = block.getEntityAt(0);
        if (!entity) return null;
        const type = contentState.getEntity(entity).getType();
        **if (type === entityType) {**
          return {
            component: ThemedImage,
            editable: false,
          };
        }
        return null;
      }

      return null;
    },
    addImage,
  };
};
```

If it's acceptable, I can make a PR.

Thank you.

**Comment by juliankrispel** [comment]
That’d be acceptable - if you feel like implementing this please go ahead I‘d be happy to help!
