### ISSUE TITLE
how can i get the value to be submitted to backend from the editor

### ISSUE THREAD

**Issue by abhilisten** [draft-js-plugins/draft-js-plugins#1017]
i am not able to get the value to be submitted to backend from editor. How and where can i get?

**Comment by tumetus** [comment]
Hi @abhilisten !

I am not quite sure if this is what you mean but you can get the content of the editor as raw JS structure and store that to your backend. Use draft-js convertToRaw-method for this.
```javascript
import { convertToRaw } from 'draft-js';
const content = editorState.getCurrentContent();
const dataToSaveBackend = convertToRaw(content);
```
You can read about it from the draft-js docs: https://draftjs.org/docs/api-reference-data-conversion.html#content
Here is a good blog post on how to save draft-js data to server: https://reactrocket.com/post/draft-js-persisting-content/

**Comment by juliankrispel** [comment]
Hey @tumetus - thanks for answering this! Would you be interesting in joining me maintaining this project? Hit me up on slack/twitter/email) would love to team up!
