### ISSUE TITLE
linkify plugin susceptible to punycode phishing attack

### ISSUE THREAD

**Issue by comatory** [draft-js-plugins/draft-js-plugins#1019]
I am able  to use UTF-8 characters as input of the editor. However I can use sequences such as `ɡοοɡle` which is not actually `google` and append `.com` which will convert it to link. The problem is the domain actually points to `http://xn--le-igba36oa.com/`

This can be used to potentially lead user to bad website, execute script etc. It would be cool if the link would be assembled by detecting user agent's encoding.

**Comment by juliankrispel** [comment]
interesting, fancy opening a pr for this @comatory ?

**Comment by comatory** [comment]
Yeah sure, when I have the time I'll look into it.

**Comment by cawabunga** [comment]
I don't think linkify plugin should concern about it. Because there are tons of potential harmful links and you definitely don't want to show unsanitized html to user. The best option is to preprocess your html before giving it to user, for example with [DOMPurify](https://github.com/cure53/DOMPurify ) or any custom DOM parser and replace bad links.

**Comment by comatory** [comment]
> I don't think linkify plugin should concern about it. Because there are tons of potential harmful links and you definitely don't want to show unsanitized html to user. The best option is to preprocess your html before giving it to user, for example with [DOMPurify](https://github.com/cure53/DOMPurify) or any custom DOM parser and replace bad links.

User can still type those directly into the editor. So I think it can still be issue. 

I agree that there should be a discussion if it should be the library's concern or author's. I guess there could be a callback that would receive the link and author could check the validity there and decide what to do with the input (just throwing ideas around). But I guess I could already do that with `draft-js` directly.

I shouldn't complain though since I never opened that PR 😞
