### ISSUE TITLE
Character Count Plugin

### ISSUE THREAD

**Issue by neuling** [draft-js-plugins/draft-js-plugins#102]
Shows a simple character counter (optional: conditional styling if counter exceeds configurable char limits?)

**Comment by nikgraf** [comment]
Love it!

**Comment by adrianmc** [comment]
I'll take this up just to get familiar with creating plugins. Can I get assigned?

**Comment by mxstbr** [comment]
Can't assign people that aren't collaborators, so your comment will have to suffice :+1: Looking forward to it!

**Comment by nikgraf** [comment]
@adrianmc I added you as a collaborator. you now can work from a branch instead of a fork :)

**Comment by adrianmc** [comment]
@nikgraf Awesome! thanks a lot :+1:

**Comment by adrianmc** [comment]
As promised, here is my first attempt in making something useful. Check out the `counter-plugin` branch here: https://github.com/draft-js-plugins/draft-js-plugins/tree/counter-plugin

You can see it in action by:

1. `git clone https://github.com/draft-js-plugins/draft-js-plugins.git`
2. `cd draft-js-plugins/`
3. `git pull origin counter-plugin`
4. `npm install`
5. `cd docs`
6. `npm install`
7. `npm run start`

Go to [`http://localhost:3000/plugin/counter`](http://localhost:3000/plugin/counter) in your browser and check it out!

😄 

Or... you can watch this gif I made:

![counter plugin being shown off](http://i.imgur.com/txYAnHA.gif)

**Comment by nikgraf** [comment]
@adrianmc really appreciate your effort & the good execution here!
