### ISSUE TITLE
Image resizing bugs in Firefox

### ISSUE THREAD

**Issue by Kathleen-Francis** [draft-js-plugins/draft-js-plugins#1020]
## Use-case/Problem

The draft-js-resizeable-plugin seems to have some bugs in Firefox. You can see the bugs on the examples in the documentation ("Alignment + Resize + Focus + Drag'n'Drop + Drag'n'Drop Upload Example" at https://www.draft-js-plugins.com/plugin/image).

When you try to resize the image, you can hover your mouse on the edge of the image and the cursor turns into the resize cursor, but when you click and drag, it drags and drops instead of resizing, sometimes adding extra blank lines after the image, sometimes copying and pasting the image.

**Comment by vikeen** [comment]
I can comment that this is an issue with recent versions of Firefox. Just download the latest and the bug is present.

**Comment by GabrielDuarteM** [comment]
Can you check if this is related to #1021? Does this happens with `draft-js@0.10.4`?

**Comment by Kathleen-Francis** [comment]
I took this package out of my project so I can't easily check if changing the draft version changes anything. but I just looked at the examples in #1021 and the bugs happening in the 0.10.5 demo seem to be the same things that were happening for me.

**Comment by freedomlang** [comment]
Looks like refs error!

**Comment by juliankrispel** [comment]
@freedomlang sry not related
