### ISSUE TITLE
Image resizing stop working since draft.js 0.10.5

### ISSUE THREAD

**Issue by Hongbo-Miao** [draft-js-plugins/draft-js-plugins#1021]
The two live demos below are exactly same and use draft-js-plugins demo code.
The only difference is one using draft.js 0.10.4 and another one using draft.js 0.10.5

[Live demo using draft.js 0.10.4](https://stackblitz.com/edit/react-gxcpfp), can resize image, 
[Live demo using draft.js 0.10.5](https://stackblitz.com/edit/react-qoswxb), failed to resize image

**Comment by JohnMaguir** [comment]
Having this issue too.
I've set draft-js to use version 0.10.4 until it's fixed.

**Comment by rauleite** [comment]
I also had to downgrade to 0.10.4

**Comment by keithhalterman** [comment]
Same problem, also had to downgrade to 0.10.4.

**Comment by juliankrispel** [comment]
hey folks - Just tested this on plugins-editor 2.0.4 and it works fine - please upgrade

**Comment by juliankrispel** [comment]
@Hongbo-Miao fixed - please try the latest version of the plugin (`2.0.2`)

**Comment by Hongbo-Miao** [comment]
Works perfect, thanks for fixing!
