### ISSUE TITLE
SideToolbarPlugin doesn't work inside ShadowDOM

### ISSUE THREAD

**Issue by alubchuk** [draft-js-plugins/draft-js-plugins#1023]
## Use-case/Problem
I'm rendering my application inside ShadowDOM, everything works fine except `draft-js-side-toolbar-plugin`. When I do focus in editor, this line...

![image](https://user-images.githubusercontent.com/2202797/35466834-4fab8c62-0310-11e8-8cca-f70272670fc7.png)

...throws the following error because of the ShadowDOM boundaries:

![image](https://user-images.githubusercontent.com/2202797/35466763-97a7ceaa-030f-11e8-979f-daab5db58ffa.png)

That would be awesome, if we could pass down some additional prop, let's say `contextNode` or `context` here:

![image](https://user-images.githubusercontent.com/2202797/35466803-ef29ae6e-030f-11e8-9395-0e9eec950dec.png)

It could allow to get rid of direct dependency on `document` node and use whatever user wants.

**Comment by juliankrispel** [comment]
This seems like a small compromise for a cool feature - if you feel like implementing tgis please go ahead I‘d be happy to help!

**Comment by juliankrispel** [comment]
@alubchuk please try version `2.0.2` of the sidetoolbar plugin - it should work now

**Comment by alubchuk** [comment]
@juliankrispel coolio, thanks! Will try!
