### ISSUE TITLE
Placeholder does not work as such.

### ISSUE THREAD

**Issue by falcoagustin** [draft-js-plugins/draft-js-plugins#1025]
Greetings !

I found a bug with the placeholder, it kinda works as a text that is being removed, but I cant write on top of it. Maybe a video will demonstrate better what I mean,

Thanks in advance, keep up the good work ! 😄 
![placholder-behavoir](https://user-images.githubusercontent.com/15353019/35572098-a49c976c-05b2-11e8-9188-31fd362b4872.gif)

**Comment by tiggem1993** [comment]
Same issue, solution required.

**Comment by freedomlang** [comment]
Will you please offer a jsfiddle ?

**Comment by bit-dragon** [comment]
@falcoagustin I did a workaround that maybe helps you.

```js
...

state = {
  placeholder: null,
}

setPlaceholder() {
  const { placeholder } = this.props;
  placeholder && this.setState({ placeholder })
}

componentDidMount() {
  this.setPlaceholder();
}

handleOnClick() {
  this.editorRef.focus();
  this.setState({ placeholder: null });
}

handleOnBlur() {
  this.editorRef.blur();
  this.setPlaceholder();
}

render() {
  return (
    <div 
      onClick={this.handleOnClick} 
      onBlur={this.handleOnBlur}>

      <Editor placeholder={this.state.placeholder} 
        ...
      />

    </div>
  );
}
```

The idea is to listen the onClick event on element that wraps the `Editor` component in order to replace the placeholder (remove it) and trigger the focus event on the editor. That helps to have a better user experience.

**Comment by falcoagustin** [comment]
Thanks @bit-dragon ! But Indecided not to use the library due to lck of maintainability.

**Comment by juliankrispel** [comment]
The placeholder is something that's dealt with inside draft-js and we don't really do anything special to it. In order to place the placeholder at the same position as the editor you need to use css to position it

**Comment by nabeelnazirvf** [comment]
@bit-dragon your solution helped me out. Thank you :)

**Comment by chrise86** [comment]
My solution is to style it:

```
.editor .public-DraftEditorPlaceholder-root {
  color: #999;
  position: absolute;
}
```

**Comment by abheist** [comment]
Just import `Draft.css` from `draft-js` module.

```javascript
import 'draft-js/dist/Draft.css';
```

Good luck ✌️

**Comment by ajaytech002** [comment]
> ```js
> import 'draft-js/dist/Draft.css';
> ```

This fixed it. Thanks
