### ISSUE TITLE
Z-Index Issue with the @-mentions

### ISSUE THREAD

**Issue by johannesnagl** [draft-js-plugins/draft-js-plugins#103]
![screen shot 2016-03-23 at 10 16 28](https://cloud.githubusercontent.com/assets/610811/13980735/592b746c-f0e0-11e5-86c1-31892ae0396c.png)

Steps to repro:

1. Open up https://www.draft-js-plugins.com/
2. within the demo, enter a @ after "smiley below."
3. Mentions-Suggestions pop up, but are not correctly z-indexed in front of the other text

**Comment by nikgraf** [comment]
Interesting, will fix this today! Thx for reporting

**Comment by nikgraf** [comment]
@johannesnagl fixed, thx again
