### ISSUE TITLE
blockStyleFn warning triggered by Image with Draft-js 0.10.5

### ISSUE THREAD

**Issue by HenrikBechmann** [draft-js-plugins/draft-js-plugins#1032]
Adding this to the Image/index.js transpiled code suppresses the warning
```
          blockStyleFn = otherProps.blockStyleFn, // changed by Henrik
          elementProps = _objectWithoutProperties(otherProps, ['blockProps', 'customStyleMap', 'customStyleFn', 'decorator', 'forceSelection', 'offsetKey', 'selection', 'tree', 'contentState','blockStyleFn']); // blockStyleFn added by Henrik
```
iow `blockStyleFn` needs to be added to the list of suppressed props at Image/index.cs at L13 of https://github.com/draft-js-plugins/draft-js-plugins/blob/master/draft-js-image-plugin/src/Image/index.js

Thanks to `@JohnM` in the draft-js-plugins slack channel for the solution

**Comment by freedomlang** [comment]
fixed !
