### ISSUE TITLE
draft-js-resizeable-plugin's error cause by refs

### ISSUE THREAD

**Issue by freedomlang** [draft-js-plugins/draft-js-plugins#1039]
[should be `.editor`](https://github.com/draft-js-plugins/draft-js-plugins/blob/656079cf2bbda71930022013f6c3e521b12667d8/draft-js-resizeable-plugin/src/createDecorator.js#L91)

and i think [this one](https://github.com/draft-js-plugins/draft-js-plugins/blob/2d66829b275076d5fb11f605ab43ea1fb8d32441/draft-js-side-toolbar-plugin/src/components/Toolbar/index.js#L40) in draft-js-side-toolbar-plugin will cause error too

I'm will to mak a pull request to fix this

**Comment by freedomlang** [comment]
Duplicate of #1024

**Comment by arturchyzy** [comment]
Any chance this will be added soon ? It's preventing resizeable plugin to work at all !!!

**Comment by tommypater** [comment]
And side toolbox plugin :)

**Comment by juliankrispel** [comment]
this is now finally finally fixed - please try version `2.0.2` for both the side toolbar plugin as well as the resizable plugin

Cheers folks
