### ISSUE TITLE
Linkify not working when using http(s)://

### ISSUE THREAD

**Issue by johannesnagl** [draft-js-plugins/draft-js-plugins#104]
![screen shot 2016-03-23 at 10 21 19](https://cloud.githubusercontent.com/assets/610811/13980837/fd228f42-f0e0-11e5-8ffe-806b0610370c.png)

Steps to reproduce:

1. Open up https://www.draft-js-plugins.com/
2. Enter "https://orf.at/" or "http://orf.at/" or "http://www.orf.at/" into the demo textbox. No auto linking is happening

**Comment by okonet** [comment]
Also:

* Typing `http://go` breaks the link and the content.
* Selection is gone after that

![2016-03-23 at 11 08](https://cloud.githubusercontent.com/assets/11071/13981995/b80913fc-f0e7-11e5-96bc-af1e119bdf14.gif)

It works after the clean page refresh but not if I go to other plugin page and then navigate to this one again.

**Comment by nikgraf** [comment]
Thx @johannesnagl & @okonet - will look into this …

**Comment by adrianmc** [comment]
I've looked into this a bit and it seems that the Emoji plugin might be tripping things up. More specifically, it is the colon character (`:`) that is splitting up the text. This causes the Linkify plugin strategy to have issues parsing the correct text.

For example, if I type in something like this:

```
http://google.com
```

What ends up happening in the block is:

```html
<div data-offset-key="8besc-0-0" class="public-DraftStyleDefault-block public-DraftStyleDefault-ltr">
  <span data-offset-key="8besc-0-0">
    <span data-text="true">http</span>
  </span>
  <span class="autocomplete___1hrQh" spellcheck="false">
    <span data-offset-key="8besc-1-0">
      <span data-text="true">:</span>
    </span>
  </span>
  <span data-offset-key="8besc-2-0">
    <span data-text="true">//google.com</span>
  </span>
</div>
```

Note how the colon is splitting up the entire URL. I've even looked at this with the React Chrome Dev Tools and it confirms my Emoji conflict theory:

![React Dev Tools Screenshot](http://i.imgur.com/hFj80tS.png)

I haven't looked into how the Emoji plugin works yet though, so I don't have a solution for this yet. But my conclusion still stands:

**The Emoji plugin is interfering with the Linkify plugin**

**Comment by nikgraf** [comment]
wow, just wow - really good find @adrianmc 

just improved the regex for emoji & mention to require a space before so it doesn't match texts like links or emails. https://github.com/draft-js-plugins/draft-js-plugins/pull/181
