### ISSUE TITLE
Focus plugin bug: ArrowUp/ArrowDown from multi-line unstyled block goes directly to atomic block

### ISSUE THREAD

**Issue by efjacobson** [draft-js-plugins/draft-js-plugins#1044]
Basically what the title says, but in more words: when using the focus plugin, if the cursor is in a multi-line unstyled block (say, on the first line) before an atomic block and you press down, the focus jumps to the atomic block. Same situation for if the unstyled block is below the atomic block and you press up.

recording: http://recordit.co/7Z8DR9Pye6

As you can see, this is on the focus plugin's [demo page](https://www.draft-js-plugins.com/plugin/focus), but I also made a [codesandbox](https://codesandbox.io/s/n0k2kk390m).

In the recording you can see that the cursor starts at the first position, which is the first of five lines. Pressing down once skips the other four lines and goes directly to the colored rectangle. Then, pressing down proceeds as expected, line by line, through the second text block. Then you can see the same situation in reverse.

Presumably, the expected behavior here is that the cursor would always proceed line by line until right before the atomic block, instead of jumping.

I'll be working on my own solution, will post any findings as I come across them.

Thanks for all your hard work - the plugins are great!

**Comment by freedomlang** [comment]
I've tried focus plugin's [demo page](https://www.draft-js-plugins.com/plugin/focus) and It looks like all lines before colored rectangle will go to directly to the colored rectangle ! Is that a feature ?

![2018-03-02 09 05 48](https://user-images.githubusercontent.com/11409069/36878303-40ffac80-1df9-11e8-9538-57163eb789e2.gif)

**Comment by efjacobson** [comment]
@freedomlang yeah, this is exactly why I created this issue. I personally would consider it a bug (not a feature), but maybe we'll get some clarification if a maintainer responds. As I said, I'll be working on a fix and will post my findings as I come across them.

**Comment by efjacobson** [comment]
@freedomlang and others:

I've come up with an mvp fix for this, see [this gist](https://gist.github.com/efjacobson/f2a34413d26ad5adb1fbfab6ac82630a)

This is an altered version of the focus plugin's `index.js`. As you'll see, there is a new function `getLines` that returns the lines in the current text block. Then, there is logic in `onDownArrow` and `onUpArrow` to determine if the plugin's behavior should kick in.

In order to use it, you will need to pass a class name in when you create the focus plugin, like so:

```
this.focusPlugin = createFocusPlugin({
  testClass: 'line-length-tester',
});
```

You will need to create that class such that it is styled exactly the same way your text blocks are styled. `getLines` will then create a span element with said style and add words to it until the line breaks, allowing the lines to be split up and returned as they would in the editor.

Here it is in action:

![focus-plugin-fix](https://user-images.githubusercontent.com/6315388/37116755-0ab47570-2204-11e8-8f79-2424f147388a.gif)

There are some clear optimizations that could happen here - a cache could be implemented to only get the lines when necessary, and the whole process could be skipped if a class was not supplied, or if some other flag was set in config. Also - it is not perfect: on up arrow, if the cursor is at the final position of the first line, it will skip the block. Not sure how to address that yet as the alternative is that if it is at the first position of the second line, it will skip the block. The current implementation seemed better and suits my needs for the time being.

I'd be happy to discuss improvements, and move forward with a PR, if a maintainer is interested. For the time being, however, I'm just doing this locally. If no one seems interested I may end up publishing my own fork of the focus plugin.

Standing by.

**Comment by juliankrispel** [comment]
Thanks first of all for opening the issue, your contribution is much appreciated!!! ♥️ 

I was about to write a rant about the DOM and how there's no reliable way to find out something like the computed line-height but apparently things are getting better 🙌 

- Have a look at [the `getComputedStyle` api](https://developer.mozilla.org/en-US/docs/Web/API/Window/getComputedStyle)
- It seems to [have fairly decent support](https://caniuse.com/#feat=getcomputedstyle)

What I would do is not create elements and use the above instead. That'd be much cleaner :)

and then you could figure out if your cursor is on the last line without much code...

WHOOP!
