### ISSUE TITLE
[draft-js-mention-plugin] Extract mentions from editor

### ISSUE THREAD

**Issue by C1one-38** [draft-js-plugins/draft-js-plugins#1045]
Hi guys! You put an amazing job!

But I need a bit of your help:
In my case I have an editor where user can type in any text with mentions. Then I need to store user input in a db, and display that message outside of the draft-js editor.

So I need a way to extract mentions and their positions from the editor. What is the best way to do it?
Are there any API for that?

**Comment by dem** [comment]
Hi @C1one-38 

I think there is no special API for this. I use for this purposes to convert state into HTML (and vise versa)
https://github.com/HubSpot/draft-convert
Example in coffeecript
```
  entityToHTML: (entity, originalText) ->
    switch entity.type
        span
          className: 'mention'
          originalText
```
end convert back to editor state:
```
  htmlToEntity: (nodeName, node, createEntity) ->
    switch nodeName
      when 'span' 
        if node.className is 'mention'
          name = node?.innerText || ''
          if name[0] == '@'
            name = name.substr(1)
          createEntity(
            'mention',
            'IMMUTABLE',
            mention: fromJS
              name: name
          )
```

**Comment by tumetus** [comment]
Ahoy!

@C1one-38 do you mean something like editor.getContent().getMentions() and it would return the mention data + positions for the mentions?

If so, I could prolly work on a PR if this kind of functionality is needed.

**Comment by C1one-38** [comment]
@dem Thanks for provided example! It is similar to what we use now

@tumetus Yeah, it is exactly what I need! And it would be great if it worked in opposit way too - restore mentions in the editor by that extracted data

**Comment by tumetus** [comment]
@C1one-38 ok cool! Unfortunately I don't have time to work on it right away, but once I do I'll be sure to give it a try if anyone else hasn't already started doing it :)

**Comment by juliankrispel** [comment]
Thanks for jumping in here @dem 🙌🙌🙌🙌 - great that it’s been resolved
