### ISSUE TITLE
[draft-js-mention-plugin] Mention text matching suggestion should render on SPACE

### ISSUE THREAD

**Issue by WilliamHolmes** [draft-js-plugins/draft-js-plugins#1048]
## Use-case/Problem

Is it possible to have the `@Mention` text in the editor be converted to the Selection Mention markup when the text is the same the mention, and the user presses SPACE rather than ENTER?

### Currently
@JoeBlogs\<ENTER> would result in Mention Markup 
![image](https://user-images.githubusercontent.com/5538260/37291788-503f276e-2607-11e8-96a1-2f529664e8b7.png)

@JoeBlogs\<SPACE> would result in `@JoeBlogs` text.

**Comment by juliankrispel** [comment]
We could make the key configurable - fancy opening a pr ? It’d be pretty simple

**Comment by juliankrispel** [comment]
@dem any luck?
