### ISSUE TITLE
getEditorState is not a function - when editors are unmounted/remounted

### ISSUE THREAD

**Issue by francisrod01** [draft-js-plugins/draft-js-plugins#1052]
## Use-case/Problem

I'm navigating in my pages that contain the editor as readonly and then I'll update the content again and I receive this bug in console.

![image](https://user-images.githubusercontent.com/4691768/37536032-322d123a-2928-11e8-8daa-bd4075301a1e.png)

And this is when I try to apply more styles using inline toolbar.

![image](https://user-images.githubusercontent.com/4691768/37537837-7acd930c-292d-11e8-8821-5b21755d0e0a.png)

## Environments

`react` 16.2.0
`draft-js-plugins-editor`2.0.4
`draft-js-static-toolbar-plugin` 2.0.1

I'm using `redux`, `redux-saga` redesigned.

My editor component receive props from another components. See as below:

```jsx
import React, { Component } from 'react'
import { actions } from 'mirrorx'

import Editor from 'draft-js-plugins-editor'
import createToolbarPlugin from 'draft-js-static-toolbar-plugin'
import 'draft-js-static-toolbar-plugin/lib/plugin.css'

import {
    EditorState,
    convertFromRaw,
    convertToRaw,
} from 'draft-js'

import styles from '../config/editor-styles'


const staticToolbarPlugin = createToolbarPlugin()
const { Toolbar } = staticToolbarPlugin
let plugins = [staticToolbarPlugin]


const handleChangeContent = (content) => {
    const contentState = content.getCurrentContent()
    const rawContent = convertToRaw(contentState)
    const currentContent = JSON.stringify(rawContent)

    actions.editor.setState(currentContent)
}


class MyEditor extends Component {
    constructor(props) {
        super(props)

        const { content, isReadOnly } = props
        
        if (isReadOnly) {
            plugins = []
        }
        
        const editorState = this._mountEditorState(content)

        this.state = {
            editorState,
        }

        this.onFocus = () => this.refs.editor.focus()

        this.onChange = (editorState) => {
            this.setState({ editorState })
            
            handleChangeContent(editorState)
        }
    }
    componentWillReceiveProps(nextProps) {
        const { content, isReadOnly } = nextProps
        if (content && isReadOnly) {
            const editorState = this._mountEditorState(content)

            this.setState({ editorState })
        }
    }
    _mountEditorState(content) {
        let editorState

        try {
            const rawContent = convertFromRaw(JSON.parse(content))
            editorState = EditorState.createWithContent(rawContent)
        } catch (err) {
            editorState = EditorState.createEmpty()
        }

        return editorState
    }
    render() {
        const { isReadOnly } = this.props
        const { editorState } = this.state

        return (
            <div style={styles.root}>

                { !editorState && <div>Loading content...</div> }

                <div style={styles.editor} onClick={this.onFocus}>
                    <Editor
                        readOnly={isReadOnly}
                        editorState={editorState}
                        onChange={this.onChange}
                        ref='editor'
                        spellCheck={true}
                        plugins={plugins}
                    />
                    { !isReadOnly && <Toolbar /> }
                </div>
            </div>
        )
    }
}


export default MyEditor
```

### References:

https://github.com/facebook/draft-js/issues/473#issuecomment-373791338

**Comment by francisrod01** [comment]
For now I'm pass to use https://github.com/brijeshb42/medium-draft/

**Comment by freedomlang** [comment]
@francisrod01 use `ref={(element) => { this.editor = element; }}` instead of `ref='editor'`; Hope this solves your problem

**Comment by francisrod01** [comment]
It works sometimes but both of this errors above still appears.

**Comment by juliankrispel** [comment]
@francisrod01 so the knack here is that you need to render the `Editor` component before any other components that plugins provide - the `Editor` component needs to actually render first to populate the state.

**Comment by juliankrispel** [comment]
yea we need to fix this - thanks for reporting it. If someone could make a story for this case that'd be sweet

**Comment by katz12** [comment]
This error seems to occur because the render() function of the Toolbar is invoked before the plugin is initialized. If you use a `ref` on the Editor component as @freedomlang [suggested](https://github.com/draft-js-plugins/draft-js-plugins/issues/1052#issuecomment-375147171) and then gate the rendering of Toolbar on the existence of `this.editor` it should get rid of the error.

**Comment by francisrod01** [comment]
Sorry to respond too late.
I'm using `draft-js` combined with `medium-draft`.

**Comment by francisrod01** [comment]
@katz12 I'll try it with `draft-js-static-toolbar-plugin` too.

**Comment by francisrod01** [comment]
@katz12 I'll try it with draft-js-static-toolbar-plugin in few days.

**Comment by sahilpaudel** [comment]
@francisrod01 how did it go, I am facing the same issue.

**Comment by francisrod01** [comment]
Hi @sahilpaudel, sorry for the lag of my answer.
I'll get it to you as soon as possible, once I've learnt more about React since last year. ;)

**Comment by MSameet** [comment]
how we resolve this issue in function component?

**Comment by katz12** [comment]
@MSameet 

something like this
```
const [ref, setRef] = useRef()

return 
  <div>
    <Editor ref={setRef} />
    {ref && <Toolbar />}
  </div>
```

**Comment by tomi1368** [comment]
@katz12 

const [ref, setRef] = useRef(). Throw an error
