### ISSUE TITLE
How to install most recent versions (2.0.2)?

### ISSUE THREAD

**Issue by jrock17** [draft-js-plugins/draft-js-plugins#1054]
I want to update my image and emoji plugins with some of the recent bug fixes that have been merged. But the latest NPM versions are 2.0.1 despite the versions being bumped to 2.0.2 here. 

Can we get the latest pushed to NPM?

Thanks!

**Comment by freedomlang** [comment]
npm install --save gitRepo

import Editor from 'draft-js-plugins/draft-js-plugins-editor'

I don't know if it can do the magic

**Comment by juliankrispel** [comment]
@jrock17 https://www.npmjs.com/package/draft-js-emoji-plugin it's on npm

to specify a version you can do `npm install draft-js-empji-plugin@2.0.2` best first to check if the module exists on npm though
