### ISSUE TITLE
Mention component display only 5 suggestions

### ISSUE THREAD

**Issue by reemtariqq** [draft-js-plugins/draft-js-plugins#1055]
when click @ to display suggestions and choose among them , it only displays 5 and i would like to show all suggestions

**Comment by tumetus** [comment]
Hey @reemtariqq !

If you are using the [defaultSuggestionsFilter](https://github.com/draft-js-plugins/draft-js-plugins/blob/master/draft-js-mention-plugin/src/utils/defaultSuggestionsFilter.js) that comes with draft-js-mention-plugin, it limits the results to max 5. If you want to change the limit of how many suggestions to display or would like to remove the limit all together, you can write your own filter function. 

Here a quick example of what a filter function that limits the suggestions to 10 would look like:
```javascript
 customSuggestionsFilter = (searchValue, suggestions) => {
    const size = (list) => (list.constructor.name === 'List'
        ? list.size
        : list.length);

    const get = (obj, attr) => (obj.get
        ? obj.get(attr)
        : obj[attr]);

    const value = searchValue.toLowerCase();
    const filteredSuggestions = suggestions.filter((suggestion) => (
      !value || get(suggestion, 'name').toLowerCase().indexOf(value) > -1
    ));
    const length = size(filteredSuggestions) < 10 ? size(filteredSuggestions) : 10;
    return filteredSuggestions.slice(0, length);
  };
```

Then your onSearchChange method would look something like this:
```javascript
onSearchChange = ({ value }) => {
    this.setState({
      suggestions: this.customSuggestionsFilter(value, mentions),
    });
  };
```

This way you can also define which attributes are used for filtering suggestions e.g. if you have email-field in your suggestions, you can change the search to filter based on that.

Hope this helps!
