### ISSUE TITLE
[draft-js-mention-plugin] Click on mention to re-open suggestions

### ISSUE THREAD

**Issue by gangleton** [draft-js-plugins/draft-js-plugins#1059]
## Use-case/Problem

After someone has added a mention, there's no way to reopen the suggestion list except by deleting it and then typing in the trigger character (at least as far as I can tell). Is there a way to trigger the suggestion list again by clicking on the mention?

**Comment by simsim0709** [comment]
I'm not sure I understand what you said.
Do you mean you want to change added mentions by clicking it?

For example, when you want to change "gangleton" to "sim", you want to click "gangleton"
then mention list shows up, so that you can change name to "sim".

Is this what you are asking?

**Comment by simsim0709** [comment]
@gangleton. Let me first ask @juliankrispel , if it's doable feature!

If it does I would like to try out.

@juliankrispel Can you check this feature request?

**Comment by simsim0709** [comment]
#1006 is also related regarding click interaction.
