### ISSUE TITLE
Demo code does not work or instructions insufficient.

### ISSUE THREAD

**Issue by semiromid** [draft-js-plugins/draft-js-plugins#1061]
Demo code does not work or instructions insufficient.

Why?

**Comment by freedomlang** [comment]
Which Demo ?

**Comment by tsm91** [comment]
I had similar problems. @semiromid do you focus the Editor in your code (`this.editorRef.current.focus()`)? If so it breaks all the plugins.

As a workaround do:

```js
focus = () => {
  // https://github.com/draft-js-plugins/draft-js-plugins/issues/357
  setTimeout(() => {
    this.editorRef.current && this.editorRef.current.focus()
  }, 0)
}
```

**Comment by mishelashala** [comment]
@semiromid I wasn't able to make run any image-related demo.

**Comment by freedomlang** [comment]
@mishelashala a codesandbox would be help for us to narrow down or solve this issue

**Comment by juliankrispel** [comment]
we need more info to reproduce this - please stick to the issue template I'm afraid we'll have to close this for now.

@tsm91 not sure if your issue is related to this, have you created an issue for your problem yet?

**Comment by tsm91** [comment]
@juliankrispel my issue got resolved already, was just trying to help out here

btw if you check the [code example](https://github.com/draft-js-plugins/draft-js-plugins/issues/1061#issuecomment-379576615) it has a comment with the related issue: https://github.com/draft-js-plugins/draft-js-plugins/issues/357
