### ISSUE TITLE
Allow onAddMention to pre-process editorState

### ISSUE THREAD

**Issue by ericls** [draft-js-plugins/draft-js-plugins#1062]
The `onAddMention` is great but it doesn't allow you to pre-process editorState before adding mention to text.

**Comment by juliankrispel** [comment]
@ericls what do you mean @ericls ?

**Comment by ericls** [comment]
@juliankrispel sorry about the confusion. What I meant was to add `editorState` as an second argument to `onAddMention` and expect it to return a new `EditorState` which will be used as the first argument when calling `addMention`

**Comment by freedomlang** [comment]
@ericls can't figure why you need to preprocess ? a user story may help !

**Comment by juliankrispel** [comment]
@ericls we'd like to help but - why would you want this?

**Comment by ericls** [comment]
Sorry about the delay.

But the use case for me is when @ mention someone, I need to also toggle to `data` field. And I think the cleanest way of doing it is by adding a hook in `onAddMention`

**Comment by juliankrispel** [comment]
@ericls can you be more specific about what you need in data?

**Comment by ericls** [comment]
Sorry about the delay. What I wanted to do was that when @ mention someone, we assign a task to that person.

**Comment by juliankrispel** [comment]
@ericls oh I see. So to me that sounds like you can do that with `onAddMention` as it is implemented right now.

If you disagree please provide an explanation of why that is not the case. Happy to consider API changes if they enable a usecase like this 👍

**Comment by sibelius** [comment]
reopen if needed
