### ISSUE TITLE
Does Resizeable Plugin mutate the editorState?

### ISSUE THREAD

**Issue by jpvalenciag** [draft-js-plugins/draft-js-plugins#1082]
I have my Editor working with the Image Plugin. Now I want to implement the Resizeable Plugin but I'm running into an issue. My onChange function is as follows:

```
onChange(editorState) {
    const currentContent = this.state.description.getCurrentContent();
    const newContent = editorState.getCurrentContent();

    this.setState({ description: editorState });    

    if (currentContent !== newContent) {
        // Save to DB 
    }
}
```
The saving is not being fired. So I inspected both states (before calling `this.setState({ description: editorState })`) to see why the condition wasn't being met:
```
console.log(convertToRaw(currentContent));
console.log(convertToRaw(newContent));
```
And both give the same output. Notice that this is happening before I call `setState`. It's also worth mentioning that if, for example, I type some text in the editor, the first `console.log` shows the empty content, and the second one shows the text I just typed (just as I would expect).

 So my question is, is the Resizeable Plugin mutating the state of the editor? Is this expected behavior? 

Thanks a lot!

**Comment by juliankrispel** [comment]
![image](https://user-images.githubusercontent.com/1188186/39277882-fd2721c2-48e7-11e8-882b-e19268f84e50.png)

@jpvalenciag hey there, so yes the contentState actually changes. I think what happens is that changing entity data doesn't actually create a new immutable structure. This is a bug in draft-js and probably unlikely to be fixed soon 😢 

however, if you look at the screenshot above you can see that the entities metadata contains a different value for the  `width` attribute

**Comment by jpvalenciag** [comment]
I see... :confused:

Well, thanks a lot anyway!

**Comment by jpvalenciag** [comment]
Hey @juliankrispel sorry to bother again with this issue. I want to know if maybe there is a way to save to the database similar to the one I posted. 

Because if I don't put the `if`, clicks or selections on the editor will also save to the database and I would like to avoid that. But if I leave it, resizing or aligning images will not save to the database.

Thanks in advance!
