### ISSUE TITLE
Issue with Image Plugin and convertFromHTML

### ISSUE THREAD

**Issue by jpvalenciag** [draft-js-plugins/draft-js-plugins#1083]
Suppose I have some HTML like this:
```
<div>
    <p>Hello</p>
    <figure><img src="myImage"/></figure>
</div>
```

I can do:
```
const blocksFromHTML = convertFromHTML(value);
const contentState = ContentState.createFromBlockArray(
    blocksFromHTML.contentBlocks,
    blocksFromHTML.entityMap
);
this.setState({ description: EditorState.createWithContent(contentState) });
```

However, the image will not appear, and the camera icon (📷) will appear instead. I inspected the state like this: 
```
console.log(JSON.stringify(convertToRaw(contentState)));
```

And the only notable difference found I comparing it to the raw states of [these examples](https://www.draft-js-plugins.com/plugin/image), is that in my case it appears like this:
```
"entityMap": {
        "0": {
            "type": "IMAGE",
...
```
And in the examples it appears like this:
```
"entityMap": {
        "0": {
            "type": "image",
...
```
Then I copy-pasted my JSON into a variable, changed `IMAGE` to `image`, and tried to do `EditorState.createWithContent(convertFromRaw(initialState))`, and everything worked.

So my guess is that somewhere you are expecting something to equal `image`, but `convertFromHTML` produces `IMAGE`. Maybe it's in [this line.
](https://github.com/draft-js-plugins/draft-js-plugins/blob/master/draft-js-image-plugin/src/index.js#L24)

**Comment by juliankrispel** [comment]
@jpvalenciag release coming up!

**Comment by juliankrispel** [comment]
@jpvalenciag https://www.npmjs.com/package/draft-js-image-plugin

**Comment by jpvalenciag** [comment]
Awesome! Thanks a lot! :smiley:
