### ISSUE TITLE
find-with-regex 1.1.3 version is not available

### ISSUE THREAD

**Issue by mgolcha** [draft-js-plugins/draft-js-plugins#1086]
@juliankrispel  last published version of find-with-regex is 1.1.2 but in draft-js-plugins package.json 1.1.3 is used. Please fix.

**Comment by mgolcha** [comment]
https://travis-ci.org/draft-js-plugins/draft-js-plugins/builds/371310649?utm_source=github_status&utm_medium=notification 

build not completed due to this error. I am getting same error

<img width="998" alt="screen shot 2018-04-26 at 11 08 19 am" src="https://user-images.githubusercontent.com/21233845/39287612-2bc60480-4942-11e8-8e26-0d8fc6f4dcd8.png">

**Comment by juliankrispel** [comment]
sry about that lads - please try again - it's updated now @mgolcha @focus7eleven
