### ISSUE TITLE
how can I clean the editor

### ISSUE THREAD

**Issue by lingjieee** [draft-js-plugins/draft-js-plugins#1088]
I want to clean the editor, this is my code:
`clean = () => {
    const editorState = EditorState.push(this.state.editorState, ContentState.createFromText(''));
    this.setState({editorState: editorState});
  };`
but it doesn't work

**Comment by jpvalenciag** [comment]
You can try `this.setState({ editorState: EditorState.createEmpty() });` 

This is a Draft question though, not a plugins question.

**Comment by simsim0709** [comment]
Thanks @jpvalenciag 👍 

I will close this.
