### ISSUE TITLE
[draft-js-mention-plugin] How to check mentionRegExp default and accurately specify custom regex?

### ISSUE THREAD

**Issue by MarkoDoncic** [draft-js-plugins/draft-js-plugins#1093]
I am attempting to allow a single space when trying to search for a user

example: "@**Tiffany Haddish** _thispartisnotselected_" - as you can see the, "Tiffany Haddish" should be selected while the rest isn't.

However, I am not sure how to accurately use this prop, I believe I am entering valid regex to check after the mentionRegExp ([https://regexr.com/3one9](https://regexr.com/3one9), but I leave out the "@" when I use mentionRegExp prop). I also was not sure if a string or regex is supposed to be used- docs were unclear.

Any way to accomplish this?

**Comment by juliankrispel** [comment]
@MarkoDoncic yea I'm working on an update for the docs currently, they're not that great right now.

There are two configurable parameters for matching mentions:

1 - `mentionTrigger` - the character that triggers the dropdown
2 - `mentionRegExp` - which the regex used for to match the string (this is a string right now which gets turned into a regexp - I know massively confusing :/)

Let me know if that helps.

**Comment by 17bcs1837** [comment]
hey @juliankrispel ,
I want the suggestion box to only show up when a character or number has been entered after the trigger. I don't want the suggestion box to open as soon as the trigger is entered.

I am not able to come up with the value for mentionRegExp for the above task. Can you help me out?
