### ISSUE TITLE
[draft-js-resizeable-plugin] Resize not working when image has width: auto

### ISSUE THREAD

**Issue by NeoHub** [draft-js-plugins/draft-js-plugins#1094]
Hey guys,

I noticed that the plugin is always setting the `width` of the images as `40%` by default. So I tried to set the `horizontal` or `vertical` parameters as `auto`, so the image I insert gets a `width: auto` and the original size is maintained. But I can't do a resize after that. The cursor changes when hovering on the limits of the image, but the drag action with the mouse doesn't work. 
I checked the code and it could be because of these lines in the `doDrag` function:

```
      const newState = {};
      if ((isLeft || isRight) && horizontal === 'relative') {
        newState.width = resizeSteps ? round(widthPerc, resizeSteps) : widthPerc;
      } else if ((isLeft || isRight) && horizontal === 'absolute') {
        newState.width = resizeSteps ? round(width, resizeSteps) : width;
      }
```
The dragging seems to be made only when `horizontal` or `vertical` have different values than `auto`.

Is there a way we can easily say to the plugin that maintain the original size of the image when it is inserted initially, and also have the possibility to resize it?

**Comment by freedomlang** [comment]
@NeoHub looks like we still have no configuration item for the original size, may be in the next version.
