### ISSUE TITLE
[draft-js-mention-plugin] How to render saved mentions with styles?

### ISSUE THREAD

**Issue by yeezysallonyoursofa** [draft-js-plugins/draft-js-plugins#1095]
After saving editorState from a mentions-enabled editor with inline CSS, and then loading it, the styles are gone. How do I render the editor state with CSS? I have seen this mentioned multiple places and 
am following the same advice for saving and loading serialized editorstate, but still not sure how to load.

1. [[Hashtags] Everything is unstyled when I convertToRaw?](https://github.com/draft-js-plugins/draft-js-plugins/issues/670)
2. [Load saved mentions in editor?](https://github.com/draft-js-plugins/draft-js-plugins/issues/622)

**Comment by yeezysallonyoursofa** [comment]
I found the correct solution to doing this, see this issue:

[How to render these plugins from raw content state in "readOnly" mode](https://github.com/draft-js-plugins/draft-js-plugins/issues/530)

> it may sounds silly, but draftjs-plugin editor is using onchange to mount the decorators to editorState. so I think even your editor is on readOnly you still need to pass onchange ={ (editorState) => this.setState({editorState}}

**Comment by yeezysallonyoursofa** [comment]
I also needed to include the following code snippet that was removed in this FAQ

[Why are mentions broken after using `convertFromRaw` and throwing an error](https://github.com/draft-js-plugins/draft-js-plugins/commit/5f437ceab3d6fe8daa20429f7f779c71779dd2ef#diff-e6f81a9d8df4fb4d787121a242ea6bf1)

**Comment by mchaledg19** [comment]
I this already solve?

**Comment by mchaledg19** [comment]
How did you manage this issue?
`<Editor
                  editorState={EditorState.createWithContent(
                    convertFromRaw(
                      JSON.parse(decodeURI(message.message_details.content))
                    )
                  )}
                 readOnly={true}
                  plugins={plugins}
                  ref={element => {
                    this.editor = element;
                  }}
                  onChange={() => {}}
                />`

**Comment by bebeun** [comment]
I have the same problem. How can I restore the style for mentions ?

**Comment by rizalrhmn** [comment]
The key is we need to create include decorator when we create content from raw. Just follow this answer : https://github.com/draft-js-plugins/draft-js-plugins/issues/530#issuecomment-642036963

From before : 
```
setEditorState(EditorState.createWithContent(
    convertFromRaw(JSON.parse(message.content))
    ));
```

become : 
```
setEditorState(EditorState.createWithContent(
    convertFromRaw(JSON.parse(message.content))
    , decorator));
```
Don't forget to import lodash for using flattenDeep and import CompositeDecorator from draft-js plugin. 

```
import _ from 'lodash'
import { EditorState, convertFromRaw, convertToRaw, ContentState, CompositeDecorator } from 'draft-js';
```
here's my full code :

```
import _ from 'lodash'
import { EditorState, convertFromRaw, convertToRaw, ContentState, CompositeDecorator } from 'draft-js';

 const decorators = _.flattenDeep(plugins.map((plugin) => plugin.decorators));
    const decorator = new CompositeDecorator( decorators.filter((decorator, index) => index !== 1) );

    setEditorState(EditorState.createWithContent(
    convertFromRaw(JSON.parse(message.content))
    , decorator));
```

**Comment by s16417** [comment]
> The key is we need to create include decorator when we create content from raw. Just follow this answer : [#530 (comment)](https://github.com/draft-js-plugins/draft-js-plugins/issues/530#issuecomment-642036963)
> 
> From before :
> 
> ```
> setEditorState(EditorState.createWithContent(
>     convertFromRaw(JSON.parse(message.content))
>     ));
> ```
> 
> become :
> 
> ```
> setEditorState(EditorState.createWithContent(
>     convertFromRaw(JSON.parse(message.content))
>     , decorator));
> ```
> 
> Don't forget to import lodash for using flattenDeep and import CompositeDecorator from draft-js plugin.
> 
> ```
> import _ from 'lodash'
> import { EditorState, convertFromRaw, convertToRaw, ContentState, CompositeDecorator } from 'draft-js';
> ```
> 
> And also we need to include plugins & onChange (even this is read only Editor) : [#530 (comment)](https://github.com/draft-js-plugins/draft-js-plugins/issues/530#issuecomment-258736772)
> 
> Here's my full code :
> 
> ```
> import _ from 'lodash'
> import { EditorState, convertFromRaw, convertToRaw, ContentState, CompositeDecorator } from 'draft-js';
> 
> const myApp = ({plugins}) => {
> const [editorState, setEditorState] = useState(EditorState.createEmpty())
>  const decorators = _.flattenDeep(plugins.map((plugin) => plugin.decorators));
>     const decorator = new CompositeDecorator( decorators.filter((decorator, index) => index !== 1) );
> 
>     setEditorState(EditorState.createWithContent(
>     convertFromRaw(JSON.parse(message.content))
>     , decorator));
> 
> return (
> <Editor
>                 readOnly
>                 plugins={plugins}
>                 editorState={editorState}
>                 onChange={editorState => setEditorState(editorState)}
>               />
> )
> 
> }
> ```

Thank you!

**Comment by s16417** [comment]
rizalrhmn Thank you!

**Comment by conor909** [comment]
Thanks!
