### ISSUE TITLE
Improve hashtag regex

### ISSUE THREAD

**Issue by nikgraf** [draft-js-plugins/draft-js-plugins#11]
Nik: what’s wrong with this regex?
Isacc: It's a weak regex for i18n hashtag handling, IIRC

Let's check how to improve it

**Comment by mxstbr** [comment]
Doesn't even work with german characters: https://regex101.com/r/hO7rO4/1

**Comment by nikgraf** [comment]
interesting, somewhere in there twitters solution is hidden: https://github.com/twitter/twitter-text/blob/master/js/twitter-text.js

**Comment by mxstbr** [comment]
They match the hashtag itself [on line 54](https://github.com/twitter/twitter-text/blob/master/js/twitter-text.js#L54), and the regex they use is

```JS
/#\{(\w+)\}/g
```

But they do some more complicated stuff [further down](https://github.com/twitter/twitter-text/blob/master/js/twitter-text.js#L137-L143), that I'm not sure we need for a first version. There's probably a reason for the complexity though:

```JS
  twttr.txt.regexen.hashSigns = /[#＃]/;
  twttr.txt.regexen.hashtagAlpha = new RegExp("[" + unicodeLettersAndMarks + "]");
  twttr.txt.regexen.hashtagAlphaNumeric = new RegExp("[" + unicodeLettersAndMarks + unicodeNumbers + hashtagSpecialChars + "]");
  twttr.txt.regexen.endHashtagMatch = regexSupplant(/^(?:#{hashSigns}|:\/\/)/);
  twttr.txt.regexen.hashtagBoundary = new RegExp("(?:^|$|[^&" + unicodeLettersAndMarks + unicodeNumbers + hashtagSpecialChars + "])");
  twttr.txt.regexen.validHashtag = regexSupplant(/(#{hashtagBoundary})(#{hashSigns})(?!\ufe0f|\u20e3)(#{hashtagAlphaNumeric}*#{hashtagAlpha}#{hashtagAlphaNumeric}*)/gi);
```

**Comment by nikgraf** [comment]
I close this as we have the other issue now.
