### ISSUE TITLE
Selection state out of sync after #968

### ISSUE THREAD

**Issue by taion** [draft-js-plugins/draft-js-plugins#1100]
From https://github.com/draft-js-plugins/draft-js-plugins/pull/968#issuecomment-386090252

cc @mxstbr @juliankrispel 

#968 caused a weird regression for us. We're using the mentions plugin.

After I reset my editor with:

```js
    this.setState({
      // XXX https://github.com/facebook/draft-js/issues/73#issuecomment-191394559
      editorState: EditorState.moveFocusToEnd(EditorState.createEmpty()),
    });
```

Everything looks fine, but typing is screwed up. If I type `hey @J`, I end up with `Jey @h`, the sequence of characters looking something like:
- `h`
- `eh`
- `eyh`
- `ey h`
- `ey @h`
- `Jey @h`

(Same thing happens if I don't call `EditorState.moveFocusToEnd`.)

This doesn't happen against v2.0.4 of draft-js-plugins-editor, and it's not the aria-expanded fix either, nor is it any of the dependency bumps.

I don't really understand the decorator code here, so I can't comment on cause, but it looks like this introduced some state management glitch, perhaps with the added `moveSelectionToEnd` call.

**Comment by juliankrispel** [comment]
this will be fixed in #1078 btw
