### ISSUE TITLE
Migrate to Docusaurus

### ISSUE THREAD

**Issue by simsim0709** [draft-js-plugins/draft-js-plugins#1106]
We already had a discussion about documentation last week.

However, I would like to suggest we migrate to [Docusaurus](https://docusaurus.io/en/).
Many projects has already migrated to Docusarurs(jest, react,...) and [draft-js](https://github.com/facebook/draft-js/pull/1607) is working on as well, due to ease of use with react and markdown and many nice features. 

@juliankrispel. Do you think is it worth migrating? If so, I would love to try out.

**Comment by freedomlang** [comment]
sounds good

**Comment by juliankrispel** [comment]
That sounds like a great idea!

My only requirement is:

- [ ] that you can use codesandbox embeds
- [ ] that we can redirect all pages
- [ ] that we work on a branch on the repository itself rather than a fork
so that we can collaborate

As soon as you have the basic setup done please open a pr.

I’d say put the new docs into a separate folder from docs/ so that we can
have both sites in parallel for now

**Comment by simsim0709** [comment]
I got it! I will try.

Could you elaborate a little bit on what you mean by "that we can redirect all pages"?

And with this "work on a branch on the repository itself rather than a fork",
you mean I should make a pr to new branch(not master) something like "docs-v2.0"?

**Comment by juliankrispel** [comment]
@simsim0709 
- [ ] yes create a branch on the repo yep.
- [ ] I mean we should be able to redirect the old doc pages so that we don't get SEO penalties so `https://www.draft-js-plugins.com/plugin/mention` should redirect to the new mention docs

**Comment by renatoselenica** [comment]
Hey this looks like a great idea.
Happy to help however I can. 
Since Docusaurus is shouldn't it be easy enough to embed codesandboxes?

**Comment by juliankrispel** [comment]
@renatoselenica should be!

The more the merrier!! Would love some help on this!!!!!!!  🚀

**Comment by simsim0709** [comment]
I will make an initial pr as soon as possible!

Thanks guys!

**Comment by juliankrispel** [comment]
👍
