### ISSUE TITLE
Manually call the click handler of Anchor plugin

### ISSUE THREAD

**Issue by jpvalenciag** [draft-js-plugins/draft-js-plugins#1107]
I'm implementing some key bindings in the editor to do things like bold with CTRL+B, etc.

I would like to know if I can manually trigger the click handler of the LinkButton in the Anchor plugin, so that when CTRL+K (for example) is pressed, I can call that handler and show this:

![anchor](https://user-images.githubusercontent.com/35038836/39761259-4359ba74-529d-11e8-9607-ed005b28a2e6.jpg)

Thanks!

**Comment by juliankrispel** [comment]
This functionality doesn't exist right now but it'd be a great addition. Anyone fancy opening a pr?

**Comment by tourbillonlabs** [comment]
@jpvalenciag Hello, I realise this is ridiculously stale, but did you end up resolving this?
