### ISSUE TITLE
Design idea: All plugin components should be controlled 

### ISSUE THREAD

**Issue by juliankrispel** [draft-js-plugins/draft-js-plugins#1115]
## Use-case/Problem

Our Internal state (we have our own pub-sub mechanism :/) is in my opinion a design flaw. Immediate problems I can think of are:
 
- plugin components can only be placed "after" the editor
- it complicates the orchestration of plugins
- it adds a big maintenance burden to the draft-js-plugins team

## Suggestion

Leave state in user land

**Comment by MyOde** [comment]
Yes, for example - the Toolbar plugin keeps its state as a singleton,
which makes it impossible to use multiple instances of a component wrapping the toolbar, without invoking ancient magic.
