### ISSUE TITLE
keyBindingFn not composing across plugins

### ISSUE THREAD

**Issue by NAlexPear** [draft-js-plugins/draft-js-plugins#1117]
## Problem:

I'm not sure if this is an error on my part or if this is a larger bug, but my expectation would be that multiple custom plugins could include a `keyBindingFn` and that each `keyBindingFn` would be composed with every other `keyBindingFn` across all plugins. Currently, only the first `keyBindingFn` in the `plugins` Array will ever take effect e.g.:

```javascript
import { getDefaultKeyBinding } from 'draft-js';

const firstPlugin = {
    keyBindingFn(event) {
        if (event.keyCode === 27){
            return 'escape';
        }
        return getDefaultKeyBinding(event);
    }
};

const secondPlugin = {
    keyBindingFn(event) {
        console.log('I will never fire');

        if (event.keyCode === 69){
            return 'eject';
        }
        return getDefaultKeyBinding(event);
    }
};
```
There's a world in which one could handle the default commands in subsequent plugins after the first plugin's `keyBindingFn` is applied, but, as it exists now, that second plugin's `keyBindingFn` will never fire at all.

My current solution is to pluck out all of the `keyBindingFn`s manually and compose them into a single function. Something like:

```javascript
import { getDefaultKeyBinding } from 'draft-js';

const firstPlugin = {
    keyBindingFn(event) {
        if (event.keyCode === 27){
            return 'escape';
        }
        return event;
    }
};

const secondPlugin = {
    keyBindingFn(event) {
        if (event.keyCode === 69){
            return 'eject';
        }
        return event;
    }
};

// these next two function show how I would expect draft-js-plugins to treat the two embeds above,
// given some event on keypress

const handleDefaults = event => typeof event === "string"
    ? event
    : getDefaultKeyBinding(event)

handleDefaults(secondPlugin.keyBindingFn(firstPlugin.keyBindingFn(event)))

```
This :point_up: is a simplified version of how I'm solving the issue, but this only works because of the delegation of the default case to the `handleDefaults` function. [The example given in the Draft JS documentiation](https://draftjs.org/docs/advanced-topics-key-bindings.html#example) uses `getDefaultKeyBinding` as a part of the keyBindingFn itself, but that would prevent the composition of these `keyBindingFn`s. And when used in something like the focus plugin, [`keyBindingFn` sets editor state directly](https://github.com/draft-js-plugins/draft-js-plugins/blob/4af97bddc8e12b622cab5f6ca126b80207b83dbe/draft-js-focus-plugin/src/index.js#L76), which is also not ideal (as I'd rather handle that in a container-level `handleKeyCommand` function).

## Proposed Solution

It would be wonderful if the `draft-js-plugins-editor` could support `return`-ing `event`s from plugin `keyBindingFn`s, and, in that case, compose those `keyBindingFn`s together.

**Comment by lukesmurray** [comment]
Found the solution. 

https://github.com/draft-js-plugins/draft-js-plugins/blob/040436205cdf59236267c4dca40c80d41b8b8f9c/draft-js-plugins-editor/src/Editor/index.js#L212-L216


If you look at the code here the plugin functions are run until a function returns something other than 'undefined'. So just make your functions return undefined if they don't get hit.

```js
const firstPlugin = {
    keyBindingFn(event) {
        if (event.keyCode === 27){
            return 'escape';
        }
        return undefined;
    }
};

const secondPlugin = {
    keyBindingFn(event) {
        console.log('I will never fire');

        if (event.keyCode === 69){
            return 'eject';
        }
        return undefined;
    }
};
```

The default keybinding behavior is used automatically by the plugin editor. You can turn off default keybinding behavior by passing the prop `defaultKeyBindings: false` to the editor.
