### ISSUE TITLE
When mentions are more than 5 , key down and key up doesn't scroll the mention list

### ISSUE THREAD

**Issue by reemtariqq** [draft-js-plugins/draft-js-plugins#1119]
The issue is keydown/keyup aren't working when mention list popup has scroll , i can scroll using mouse but keyup/keydown aren't making the scroll move to the right position

**Comment by freedomlang** [comment]
@reemtariqq do you mean the keydown do not scroll if the selection is out of the list popup? btw, a codesandbox would help us to reproduce your issue.

**Comment by magichim** [comment]
this issue is still not working? @freedomlang

**Comment by magichim** [comment]
```
<MentionSuggestions
       style={{margin: 0, padding: 0, height: `200px`, overflowY: `auto`}}
       onSearchChange={this.onSearchChange}
       suggestions={this.state.suggestions}
       entryComponent={Entry}
/>
```
I inject style overflow property in MentionSuggestions, but Scroll is working but Keydown and KeyUp not follow scroll direction. just fixed scroll position.

**Comment by hashina** [comment]
@reemtariqq  any solutions on this ? thanks a lot

**Comment by vinod2001** [comment]
is this issue still open? any solution for this?

**Comment by Pardeep94** [comment]
anyone find the solution for this?
