### ISSUE TITLE
Cannot change the available mentions and invalidate all searches

### ISSUE THREAD

**Issue by novitchis** [draft-js-plugins/draft-js-plugins#1120]
## Cannot change the available mentions and invalidate all searches. 
Sample - https://codesandbox.io/s/0yql8pq2wn

Steps to reproduce:
1. Write a mention search: '@'. Notice 6 results.
2. Click out to close the drop-down without selecting anything.
3. Click "Filter Mention" (now the suggestions list should contain 3 items)
   - **1 issue** the popup is open even though the editor is not focused.
   - **2 issue** the suggestions list still has 6 result.
4. Press backspace to remove the '@' character and then write '@' again.
   - The same 6 results are displayed.
5. Press [space] and write 'contact @'.
   - Notice the 3 results are correctly displayed.

A solution would be to update the suggestions when the filter is changed but in this case the popup is opened even though the editor has no focus. 

_It would be OK if the search would trigger after the deletion of '@' text and writing again the '@' but it doesn't._

Appreciate the help.

**Comment by freedomlang** [comment]
Don't quite understand for what you mentioned above ! Do you mean the mention list shoul not popup if the editor has no focus ?

**Comment by novitchis** [comment]
I have updated the repro steps using the codesandbox sample and issues clarification.
