### ISSUE TITLE
video-plugin exhibits same crash behaviour fixed in image plugin

### ISSUE THREAD

**Issue by MattyBalaam** [draft-js-plugins/draft-js-plugins#1122]
I seem to get the same `Unknown DraftEntity key: null.` issue that has been fixed in the image plugin.

https://github.com/draft-js-plugins/draft-js-plugins/issues/778

**Comment by jrock17** [comment]
I have seen this as well

**Comment by freedomlang** [comment]
@MattyBalaam When did the error occur ? I'm willing to solve this bug and a codesandbox would be help to reproduce it !

**Comment by MattyBalaam** [comment]
@freedomlang Thanks for replying. I have stripped down my code to remove any other plugins and have created a reproducible example here: https://codesandbox.io/s/yj34mrkqmz

To reproduce, add the video, then click to the left of the video in the editor and hit enter.

**Comment by MattyBalaam** [comment]
I have been able to throw an error looking at the add video example on: https://www.draft-js-plugins.com/plugin/video

It does not happen when the iframe is set to 100%, but changing the css in devtools to give space to click to the left throws an error in the console, which then stops any further input updating the editor

![screen shot 2018-06-11 at 12 09 34](https://user-images.githubusercontent.com/1246923/41228458-551ca2f6-6d70-11e8-9904-cfb64f20ae2b.png)

Following the pattern used in other plugins such as draft-js-image-plugin, it is possible to check if `block.getEntityAt(0)` is null and then return null in blockRendererFn.

I will create a pull request based around this pattern - although perhaps this is masking a deeper problem elsewhere in draft-js-plugin-editor or even draft.js?
