### ISSUE TITLE
Mentions plugin: Microsoft Edge dom node `NotFoundError` and editor unresponsive after deleting content with a mention

### ISSUE THREAD

**Issue by afercia** [draft-js-plugins/draft-js-plugins#1124]
While developing a simple app using the Mentions plugin, together with my colleagues we faced a bug which seems to happen only with Microsoft Edge and we were able to reproduce it on the online demo too: https://www.draft-js-plugins.com/plugin/mention

To reproduce:
- use Microsoft Edge (tested on version Microsoft Edge 40.15063.674.0 - Microsoft EdgeHTML 15.15063) on Windows 10
- open the Edge dev tools > Console
- use the mentions "Simple Example"
- type some text and trigger a mention, for example:

![screenshot 28](https://user-images.githubusercontent.com/1682452/41231305-f1d61052-6d82-11e8-86c4-f9c12a8a79f5.png)

- select all the content with Ctrl + A
- **with the content still selected, type any character**
- `NotFoundError` in `DOMChildrenOperations.js` sorry for the cryptic message, that's what Edge reports 😞and seems related to the inability to find a DOM node

![screenshot 27](https://user-images.githubusercontent.com/1682452/41231429-58b37fbc-6d83-11e8-9259-ea16ff6a5d96.png)

Additionally:
- type something and type an `@` sign to trigger the mention suggestions
- no suggestions are shown, the caret gets placed at the beginning
- an additional error is shown `Unable to get property getHostNode`, probably related to the missing node above
- at this point it's even impossible to add any other content in the editor: pressing any key does nothing

![screenshot 29](https://user-images.githubusercontent.com/1682452/41231662-22a285fc-6d84-11e8-8b5a-3c1211ba5f7b.png)

Sorry we can't help more. we weren't able to figure out what's happening exactly. Thanks!

**Comment by juliankrispel** [comment]
hmmm :/ - that's an error originating from the react.js repo O_o

**Comment by juliankrispel** [comment]
https://github.com/facebook/react/issues/9134

**Comment by atimmer** [comment]
Related: https://github.com/facebook/draft-js/issues/1320 and https://github.com/facebook/draft-js/issues/1301.

There is a fix there for these issues: https://github.com/facebook/draft-js/pull/1760. @afercia can you check if this fixes the issue for us in edge?

**Comment by juliankrispel** [comment]
Thx for the pr will look at this shortly :)

**Comment by afercia** [comment]
Worth noting after I've successfully (and painfully) updated Windows, my Edge version is now:
Microsoft Edge 42.17134.1.0
Microsoft EdgeHTML 17.17134

and I can't reproduce the error any longer. When I "type over" the selection, everything works fine, the console is clean.
