### ISSUE TITLE
Support for typescript

### ISSUE THREAD

**Issue by ghost** [draft-js-plugins/draft-js-plugins#1126]
## Use-case/Problem
d.ts not available with plugins. I am using TypeScript and could not import plugins

- If you think a feature should be added to draft-js-plugins please provide a description of the use-case.
Add declarations so that these can be used with TypeScript

- If you found a bug please reproduce it within a [codesandbox](codesandbox.io), this'll make it easier for us to help you. Here's an [example that uses the mentions plugin](https://codesandbox.io/s/MjG72jX2R) - this will help get you started

Please note: The draft js plugins core team is very small and there's not that much time on our hands. If you can help fix this issue, please do, there's usually someone available in the draft-js-plugins channel [on slack](https://draftjs.herokuapp.com/) for pairing.

**Comment by simsim0709** [comment]
Sorry, but typescript is not supported...

**Comment by sandtemp01** [comment]
Hi simsim0709,
thanks for reply. From not supported, do you mean that I will not be able to use the plugin by even tweaking? Or you are not planning to release some workaround to support ts?
If I can tweak and use then I would pay effort on my end, else would just leave this plugin. Please confirm

**Comment by simsim0709** [comment]
Sorry @sandtemp01 
"do you mean that I will not be able to use the plugin by even tweaking? "
-> Sorry, I don't have any typescript knowledge. I can't answer it.

you are not planning to release some workaround to support ts?
-> We are planning to add flowtype plugin by plugin, but I'm not sure for typescript.
I think it's better to ask @juliankrispel how he plans and thinks.

**Comment by juliankrispel** [comment]
We're working on flow support right now, from there - typescript support is not far off. I've labeled this issue and will keep it open for now. If someone would like to contribute that'd help a lot!

**Comment by gwillz** [comment]
FWIW, this is what I've got so far in one of my projects.
https://gist.github.com/gwillz/1e23b573af3db71aad268d41a988d3d6

There's a lot of 'any' in there, but it's a start - and it works.

**Comment by mcMickJuice** [comment]
Agree with @ollydixon . The writing is on the wall that Typescript is the overwhelming favorite for static type checking in javascript land.  There'd be a bigger ROI on defining typescript typings than Flow IMO.

**Comment by meds** [comment]
The lack of typescript support is making me reconsider using this library, I've been spoiled by typings and losing all of my typings for emojis is just not worth it :P

**Comment by rebyul** [comment]
This is one of the reasons, for me using Slate JS (even though their typings are incomplete or inaccurate). Typescript is a big reason that is considered when using a library (for our project) and the lack of typings for plugins in draft-js-plugins was the main reason for going with Slate. Would really appreciate it if this was prioritized over flow!

**Comment by juliankrispel** [comment]
I absolutely agree with you. And flow is deprioritised. If anyone would
like to help pick up typescript types please reach out to me

**Comment by dobesv** [comment]
If we create typings should we submit to this repository or to `DefinitelyTyped` ?  e.g. would you accept PRs with typings files?

**Comment by juliankrispel** [comment]
@dobesv I would absolutely accept typings yes and I'd make sure they get published as part of the npm packages

**Comment by dobesv** [comment]
I have created a PR with the typings I have done so far, please everyone who is interested in the TypeScript typings please take a look: https://github.com/draft-js-plugins/draft-js-plugins/pull/1290

**Comment by jkhaui** [comment]
Interested in helping with this, please let me know if and what I can do to contribute

**Comment by gencer** [comment]
`id` and `editorState` is missing in typescript. Is this an expected behavior? If so, any docs?

**Comment by pereznieto** [comment]
Hey, I've written `.d.ts` files for a couple of plugins (linkify, static-toolbar, mention) so I could use them in a TypeScript project that I'm working on.

@juliankrispel, are you happy for me to raise a PR with the files, if that's useful to people?

**Comment by juliankrispel** [comment]
Yes please!

**Comment by VTulupov** [comment]
@pereznieto How can we get your  `.d.ts` file?

**Comment by sibelius** [comment]
We are going to migrate to TypeScript https://github.com/draft-js-plugins/draft-js-plugins/issues/1474

Let us know if you wanna help with this task

**Comment by fxOne** [comment]
TypeScript is added with version 4.0.0 and release under new names: https://www.npmjs.com/org/draft-js-plugins
