### ISSUE TITLE
Unable to override separator styles in the inline toolbar plugin 

### ISSUE THREAD

**Issue by mattgreenfield** [draft-js-plugins/draft-js-plugins#1128]
Using the inline toolbar plugin, I'm able to provide my own custom CSS files and override the toolbar and button styles. This is working correctly.

However, if I use the same method to override the separator styles, it does not work. I'm wondering if there is an oversight in the code?

Here's what I have
```js
import toolbarStyles from './toolbarStyles.module.css';
import buttonStyles from './buttonStyles.module.css';
import separatorStyles from './separatorStyles.module.css';

const inlineToolbarPlugin = createInlineToolbarPlugin({
	structure: [EditorButtonItalic, EditorButtonBold, Separator, EditorButtonStrikethrough],
	theme: {
		toolbarStyles, // Works fine
		buttonStyles, // Works fine
		separatorStyles, // Does not work
	},
});
```

Thanks for your help,

**Comment by freedomlang** [comment]
@mattgreenfield I've check the code and found that changing theme for separator is currently unavailable as you mentioned above. I'll take this issue in the next few days if i do have some time. BTW, You can also open a pr to take this issue.

**Comment by mattgreenfield** [comment]
Thanks @freedomlang, I'd be happy to open a PR if you could point me in the direction of what needs changing please?

**Comment by mattgreenfield** [comment]
Thanks @freedomlang, I've worked around it by putting the styles inside the `toolbarStyles` stylesheet .

**Comment by thirdman** [comment]
Another temporary solution is to use a 'begins with' css selector:

```
div[class^="draftJsToolbar__separator"]{
  border-right: 1px solid red;
}
```

**Comment by artzhookov** [comment]
Separator is very simple component, so you can also implement your own separator with desired styles and don't use separator defined in plugin.
