### ISSUE TITLE
[EmojiSelect] Remove default button and add open prop

### ISSUE THREAD

**Issue by udanpe** [draft-js-plugins/draft-js-plugins#1129]
```jsx
<EmojiSelect isOpen ={true|false} / >
```

**Comment by udanpe** [comment]
But better solution is add two components EmojiButton and EmojiSelect
https://github.com/draft-js-plugins/draft-js-plugins/pull/1133
```jsx
<EmojiSelect isOpen={true|false} / >
```

**Comment by freedomlang** [comment]
@udanpe not sure i understand what you mean, is there a user story ?

**Comment by udanpe** [comment]
@freedomlang mobile app (viber whatsapp) button in one place select in other place
