### ISSUE TITLE
Problem with Emoji

### ISSUE THREAD

**Issue by udanpe** [draft-js-plugins/draft-js-plugins#1131]
<img width="96" alt="screen shot 2018-06-24 at 05 22 20" src="https://user-images.githubusercontent.com/7540232/41815286-d20a13ea-776e-11e8-9073-402bcd701e02.png">
<img width="187" alt="screen shot 2018-06-24 at 05 30 41" src="https://user-images.githubusercontent.com/7540232/41815323-d218b660-776f-11e8-8848-2d4869f8ceea.png">
<img width="112" alt="screen shot 2018-06-24 at 05 34 29" src="https://user-images.githubusercontent.com/7540232/41815334-5415a006-7770-11e8-98f0-6cfeb6928aca.png">

```html
<span title=":relaxed:">
  <span data-offset-key="fblhb-4-0">
    <span data-text="true">☺️</span>
  </span>
</span>
```

**Comment by freedomlang** [comment]
@udanpe can not figure out the problem you described above ! Is that an issue about position ?

**Comment by udanpe** [comment]
@freedomlang Problem with : relaxed : emoji. 2 first screen (Editor and EmojiSuggestions)

**Comment by freedomlang** [comment]
@udanpe relaxed not matching the right emoji ？Is that what you mean ?
