### ISSUE TITLE
Question: error when restoring from rawContent

### ISSUE THREAD

**Issue by ktjd123** [draft-js-plugins/draft-js-plugins#1138]
When I save contents to DB I do
![2018-07-05 6 05 20](https://user-images.githubusercontent.com/15044488/42313549-00e84f0c-807e-11e8-919a-cfb15be71277.png)

I tried to show this with draft-js-plugins-editor readOnly with hashtag, mentions plugin.

When writing works great.

but problem comes when restoring it

I restore using

![2018-07-05 6 02 58](https://user-images.githubusercontent.com/15044488/42313613-23dc4ac2-807e-11e8-831e-f278c088aa69.png)

This code

then I pass it to Editor Component

![2018-07-05 6 03 02](https://user-images.githubusercontent.com/15044488/42313643-32e1734e-807e-11e8-9a62-c9be4c9438e9.png)

I separated editor component. code is

![2018-07-05 6 02 49](https://user-images.githubusercontent.com/15044488/42313703-4e23d1d8-807e-11e8-944e-0c3812dd0b48.png)

It doesn't have any difference even when not separated component.

The problem is It seems like it doesn't recognize mentions, hashtags when rendering ( restoring to writing editor works fine)

Thank you for reading

![2018-07-05 6 09 27](https://user-images.githubusercontent.com/15044488/42313811-941710ce-807e-11e8-86c0-d58b06a56027.png)

![2018-07-05 6 09 29](https://user-images.githubusercontent.com/15044488/42313821-98a927bc-807e-11e8-91e8-c8477c572b18.png)

**Comment by freedomlang** [comment]
@ktjd123 Have you imported this style file of metionPlugin and hashtagPlugin ? BTW, a `codesandbox` would be help for us to narrow down this issue !

**Comment by ktjd123** [comment]
https://codesandbox.io/s/wwv9o0q0l5

it's the codesandbox!! (in sandbox there is new error in mentions suggestion you can't change text to mentions state)

Thank you!

@freedomlang

**Comment by ktjd123** [comment]
do you know this issue exists?? @nikgraf 

Thank you and I always appreciate your work!

**Comment by fran-cadenas** [comment]
Hello, I'm having the same issue. When ever I restore the state from raw the styling of my mentions and its functionality is lost.
