### ISSUE TITLE
Undo & Redo not working when plug them with Editor in the same container

### ISSUE THREAD

**Issue by Drogbi** [draft-js-plugins/draft-js-plugins#1139]
When place undo redo buttons with Editor in the same container they become unclickable. Some screenshots below:

![screenshot_5](https://user-images.githubusercontent.com/19656571/42318021-7e620004-8056-11e8-85c4-59b50cd00cc7.png)

![screenshot_4](https://user-images.githubusercontent.com/19656571/42318028-809843b0-8056-11e8-9c63-e8471598db5e.png)

But when I paced them in the above container they works fine:
![screenshot_1](https://user-images.githubusercontent.com/19656571/42318085-ae0027c8-8056-11e8-95f8-3687feafd90a.png)

![screenshot_3](https://user-images.githubusercontent.com/19656571/42318089-afdde850-8056-11e8-8e29-6e7e693388d0.png)

I found the issue in onClick handler. When I change onClick to onMouseDown problem solved!

**Comment by freedomlang** [comment]
@Drogbi can not reproduce the clickable issue you mentioned above !

**Comment by Drogbi** [comment]
@freedomlang sure: https://codesandbox.io/s/1y551v1pr7
Also that problem reproduce in Static Toolbox plugin. In this case this button very important(

**Comment by Drogbi** [comment]
@freedomlang I can make pull request to solve this problem

**Comment by freedomlang** [comment]
@Drogbi i just take a closer look and that problem was cause by `Event Bubbling`(trigger undo and focus). If you still have time, please feel free to open a pr to fix this. BTW, i do it my self if there is no any progress in this weekend

**Comment by freedomlang** [comment]
@Drogbi fixed! Try draft-js-undo-plugin@2.0.2
