### ISSUE TITLE
editor state cannot be converted to HTML when containing Image

### ISSUE THREAD

**Issue by firashamila33** [draft-js-plugins/draft-js-plugins#1148]
Hello ,
I am using the draft-js-image-plugin, 
The editor is working fine with all the plugins ,, but when it comes to the image-plugin , the image is uploaded to the editor but an error occurs  when trying to convert the editorState to HTML .

Converting the editorState to HTML : 
`convertToHTML(this.state.editorState.getCurrentContent())`

Console Error : 
`TypeError: getBlockHTML(...) is undefined`

**Comment by freedomlang** [comment]
@firashamila33 do you mean `draft-js-image-plugin` ?

**Comment by firashamila33** [comment]
@freedomlang  , sorry ,, yeas I mean  draft-js-image-plugin

**Comment by firashamila33** [comment]
Solved  !!!
I used [draft-js-export-html]([url](https://www.npmjs.com/package/draft-js-export-html))
converting to from stateContent html :
` stateToHTML(this.state.editorState.getCurrentContent());`
converting from Raw to HTML : 
`stateToHTML(convertFromRaw(rowexporteFromStateHere));`
