### ISSUE TITLE
Names filtering for the mention plugin is not working on mobile devices.

### ISSUE THREAD

**Issue by shehab-elhariry** [draft-js-plugins/draft-js-plugins#1149]
I added the draft js mention plugin to a project and the onSearchChange hook is triggering each time I write a letter after the @ on web. On Mobile, it's only trigerring the first time when I write @ and after that any letter I write doesn't filter the list that populate the dropdown list.

**Comment by freedomlang** [comment]
@shehab-elhariry can not reproduce the problem you mentioned above (ios 11.4, safari, default input method). btw, a `codesandbox` would be help for us to take a closer look

**Comment by shehab-elhariry** [comment]
Thanks for replying. I think the problem exists only with Android devices. I have tested it with Samsung J7 pro and Hwawei P9 lite both are Android version 7. @freedomlang

**Comment by freedomlang** [comment]
@shehab-elhariry Ah, Maybe it's not actually related to draft-js-plugins, but draft-js which draft-js-plugin depends on. You can check the draft-js's [FAQ](https://github.com/facebook/draft-js/wiki/Manual-Testing#faq) and find some related issues [here](https://github.com/facebook/draft-js/issues?utf8=%E2%9C%93&q=is%3Aissue+mobile)

**Comment by himadrinath** [comment]
@freedomlang 
![mentions](https://user-images.githubusercontent.com/12247490/51081959-c0a6e200-1722-11e9-8c22-040e816f01d2.gif)

**Comment by Rechdan** [comment]
Can confirm here that the mention is not working on Android phones. As I debugged why this was not working, I realized that it has to do with the auto correct from Android, sinc it only applies the text after the user has inserted a space or clicked in a suggestion of the correct word he wants to put in.
