### ISSUE TITLE
[draft-js-plugins-editor] Issues with flow

### ISSUE THREAD

**Issue by rprzebieglec** [draft-js-plugins/draft-js-plugins#1150]
Hi, I'm getting a lot of flow errors when running flow on simple mentions example.

It's actually 494 errors if I added actual flow support to example code. Most of them are contained in 
`node_modules/draft-js-plugins-editor/lib/Editor/index.js.flow`

Am I doing something wrong? I'm using flow v0.66

First few errors: 

Error ┈┈┈┈┈┈┈┈┈┈┈┈┈┈ node_modules/draft-js-plugins-editor/lib/Editor/index.js.flow:11:26

Cannot resolve module shallowequal.

      8│   Editor,
      9│   DefaultDraftBlockRenderMap,
     10│ } from 'draft-js';
     11│ import shallowEqual from 'shallowequal';
     12│
     13│ import { type DraftBlockRenderMap } from 'draft-js/lib/DraftBlockRenderMap';
     14│ import { Map } from 'immutable';

Error ┈┈┈┈┈┈┈┈┈┈┈┈ node_modules/draft-js-plugins-editor/lib/Editor/index.js.flow:240:103

Cannot resolve name DraftInlineStyle.

     237│         return styles;
     238│       }, []).join(' ')
     239│
     240│   createCustomStyleFn = (plugins: Array<Plugin|EditorProps>, pluginMethods: PluginMethods) => (style: DraftInlineStyle, block: BlockNodeRecord) => plugins.reduce((styles, plugin) => {
     241│     if (plugin.customStyleFn == null) {
     242│       return styles;
     243│     }

Error ┈┈┈┈┈┈┈┈┈┈┈┈┈ node_modules/draft-js-plugins-editor/lib/Editor/index.js.flow:350:22

Cannot call styles.merge because property merge is missing in Plugin [1].

     node_modules/draft-js-plugins-editor/lib/Editor/index.js.flow
     347│       map = plugins
     348│         .reduce((styles, plug) => (
     349│           plug.blockRenderMap != null
     350│             ? styles.merge(plug.blockRenderMap)
     351│             : styles), map);
     352│     }
     353│

     node_modules/draft-js-plugins-editor/lib/index.js.flow
 [1]  50│   plugins?: Array<Plugin>,

Error ┈┈┈┈┈┈┈┈┈┈┈┈┈ node_modules/draft-js-plugins-editor/lib/Editor/index.js.flow:355:17

Cannot call map.merge because property merge is missing in Plugin [1].

     node_modules/draft-js-plugins-editor/lib/Editor/index.js.flow
     352│     }
     353│
     354│     if (blockRenderMap != null) {
     355│       map = map.merge(blockRenderMap);
     356│     }
     357│
     358│     return map;

     node_modules/draft-js-plugins-editor/lib/index.js.flow
 [1]  50│   plugins?: Array<Plugin>,

Error ┈┈┈┈┈┈┈┈┈┈┈┈┈┈ node_modules/draft-js-plugins-editor/lib/Editor/index.js.flow:398:8

Cannot create Editor element because:
 • function [1] is incompatible with string [2] in property ariaActiveDescendantID.
 • function [3] is incompatible with string [2] in property ariaActiveDescendantID.
 • function [4] is incompatible with string [2] in property ariaActiveDescendantID.
 • function [5] is incompatible with string [2] in property ariaActiveDescendantID.
 • function [6] is incompatible with string [2] in property ariaActiveDescendantID.
 • function [7] is incompatible with string [2] in property ariaActiveDescendantID.
 • function [1] is incompatible with string [8] in property ariaAutoComplete.
 • function [3] is incompatible with string [8] in property ariaAutoComplete.

**Comment by rprzebieglec** [comment]
And if I add those lines to `.flowconfig`, it returns only errors from `draft-js-plugins-editor/lib/Editor/index.js.flow`

`
<PROJECT_ROOT>.*/node_modules/draft-js/lib/BlockNode.js.flow
<PROJECT_ROOT>.*/node_modules/draft-js/lib/DraftEditorDragHandler.js.flow
<PROJECT_ROOT>.*/node_modules/draft-js/lib/DraftEditorLeaf.react.js.flow
<PROJECT_ROOT>.*/node_modules/draft-js/lib/DraftEditor.react.js.flow
`

Error ┈┈┈┈┈┈┈┈┈┈┈┈┈┈ node_modules/draft-js-plugins-editor/lib/Editor/index.js.flow:11:26

Cannot resolve module shallowequal.

      8│   Editor,
      9│   DefaultDraftBlockRenderMap,
     10│ } from 'draft-js';
     11│ import shallowEqual from 'shallowequal';
     12│
     13│ import { type DraftBlockRenderMap } from 'draft-js/lib/DraftBlockRenderMap';
     14│ import { Map } from 'immutable';


Error ┈┈┈┈┈┈┈┈┈┈┈┈ node_modules/draft-js-plugins-editor/lib/Editor/index.js.flow:240:103

Cannot resolve name DraftInlineStyle.

     237│         return styles;
     238│       }, []).join(' ')
     239│
     240│   createCustomStyleFn = (plugins: Array<Plugin|EditorProps>, pluginMethods: PluginMethods) => (style: DraftInlineStyle, block: BlockNodeRecord) => plugins.reduce((styles, plugin) => {
     241│     if (plugin.customStyleFn == null) {
     242│       return styles;
     243│     }


Error ┈┈┈┈┈┈┈┈┈┈┈┈┈ node_modules/draft-js-plugins-editor/lib/Editor/index.js.flow:350:22

Cannot call styles.merge because property merge is missing in Plugin [1].

     node_modules/draft-js-plugins-editor/lib/Editor/index.js.flow
     347│       map = plugins
     348│         .reduce((styles, plug) => (
     349│           plug.blockRenderMap != null
     350│             ? styles.merge(plug.blockRenderMap)
     351│             : styles), map);
     352│     }
     353│

     node_modules/draft-js-plugins-editor/lib/index.js.flow
 [1]  50│   plugins?: Array<Plugin>,


Error ┈┈┈┈┈┈┈┈┈┈┈┈┈ node_modules/draft-js-plugins-editor/lib/Editor/index.js.flow:355:17

Cannot call map.merge because property merge is missing in Plugin [1].

     node_modules/draft-js-plugins-editor/lib/Editor/index.js.flow
     352│     }
     353│
     354│     if (blockRenderMap != null) {
     355│       map = map.merge(blockRenderMap);
     356│     }
     357│
     358│     return map;

     node_modules/draft-js-plugins-editor/lib/index.js.flow
 [1]  50│   plugins?: Array<Plugin>,


Error ┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈ node_modules/draft-js-plugins-editor/lib/index.js.flow:79:27

Cannot resolve name DraftInlineStyle.

     76│   blockRenderMap?: DraftBlockRenderMap,
     77│   customStyleMap?: Object,
     78│   initialize?: (PluginMethods) => void,
     79│   customStyleFn?: (style: DraftInlineStyle, block: BlockNodeRecord, PluginMethods) => ?Object,
     80│   decorators?: Array<DraftDecoratorType>,
     81│   autoCapitalize?: string,
     82│   autoComplete?: string,

**Comment by jpmazza** [comment]
+1

**Comment by sibelius** [comment]
we are going to move to typescript
