### ISSUE TITLE
image alignement plugin not working

### ISSUE THREAD

**Issue by firashamila33** [draft-js-plugins/draft-js-plugins#1151]
Hello I implemented the image plugins in the Editor as illustrated in the documentation 
```
const focusPlugin = createFocusPlugin();
const resizeablePlugin = createResizeablePlugin();
const blockDndPlugin = createBlockDndPlugin();
const alignmentPlugin = createAlignmentPlugin();
const { AlignmentTool } = alignmentPlugin;

const decorator = composeDecorators(
  resizeablePlugin.decorator,
  alignmentPlugin.decorator,
  focusPlugin.decorator,
  blockDndPlugin.decorator
);
const imagePlugin = createImagePlugin({ decorator });
const plugins = [
  toolbarPlugin,
  emojiPlugin,
  linkifyPlugin,
  blockDndPlugin,
  focusPlugin,
  alignmentPlugin,
  resizeablePlugin,
  imagePlugin
  ];

render() {
      return (
        <div>
          <div style={editorStyles.editor} onClick={this.focus}>
            <Editor
              editorState={this.state.editorState}
              onChange={this.onChange}
              plugins={plugins}
              ref={(element) => { this.editor = element; }}
            />
            <AlignmentTool />
           </div>        
        </div>
      );
    }

```
but I get the image alignementTools in thee butom of the editor and separated from the image ,, and once I click on the image the alignment tool disappear and I get this error : 

`createBlockAlignmentButton.js:45 
Uncaught TypeError: _this.props.setAlignment is not a function
    at BlockAlignmentButton._this.activate (createBlockAlignmentButton.js:45)
    at HTMLUnknownElement.callCallback (react-dom.development.js:100)
    at Object.invokeGuardedCallbackDev (react-dom.development.js:138)
    at Object.invokeGuardedCallback (react-dom.development.js:187)
    at Object.invokeGuardedCallbackAndCatchFirstError (react-dom.development.js:201)
    at executeDispatch (react-dom.development.js:461)
    at executeDispatchesInOrder (react-dom.development.js:480)
    at executeDispatchesAndRelease (react-dom.development.js:581)
    at executeDispatchesAndReleaseTopLevel (react-dom.development.js:592)
    at forEachAccumulated (react-dom.development.js:562)`

**Comment by freedomlang** [comment]
@firashamila33 Can't find out the difference between doc's example and your code, it's too weird, i'm willing to take a closer look if there is a `codesandbox` for that error you mentioned above!

**Comment by firashamila33** [comment]
Hello @freedomlang 
here and example on codesandbox  : [problem illustration here](https://codesandbox.io/s/oq8zxjp7zq),
Once I click an alignement button this error occurs ,,, same example in my project , but in my project I am uploading photos successfully ,,,  with that error when allignement buttons clicked 
Error :  `_this.props.setAlignment is not a function`

**Comment by freedomlang** [comment]
@firashamila33 sry for my late reply, just Importing the default styles for alignment plugin and it will [work](https://codesandbox.io/s/j24vl50pz3). btw, documentation maybe a little oversight, will find a way to improve it

```javascript
import 'draft-js-alignment-plugin/lib/plugin.css';
```

**Comment by firashamila33** [comment]
Thank you @freedomlang  it worked well ,, 
yeah the documentation is good but sometimes missing somethings ,,

**Comment by lucahuy** [comment]
@freedomlang Why doesn't `draft-js-resizeable-plugin` work with video? The embedded video is tiny, cannot resize it.
