### ISSUE TITLE
Video resizing is not working 

### ISSUE THREAD

**Issue by firashamila33** [draft-js-plugins/draft-js-plugins#1154]
Hello ,
I implemented draft-js-video-plugin successfully , alignment and and focus is working but Resizing is not working , I followed the Documentation ,and I figured out that also the videos in the second demo cannot be resized in [Advanced Video Example](https://www.draft-js-plugins.com/plugin/video) ,
Here a [codesandbox](https://codesandbox.io/s/04ww30225n) implementation that illustrates the problem

**Comment by freedomlang** [comment]
@firashamila33 Sorry for my late reply, I will take a closer look in the next few days.

**Comment by firashamila33** [comment]
no prob , I am still stuck in this issue ,,,, Thank you @freedomlang  ,, hope it gets solved

**Comment by firashamila33** [comment]
so ? still no solution ?

**Comment by freedomlang** [comment]
@firashamila33 sorry for my late reply, i'm actually too busy in these days. Just found a way to get the resizing work again, will open a pr to fix it if i do have time in this weekend. 😅

**Comment by PetrVasilev** [comment]
It does not work yet

**Comment by mohitkumarCLS** [comment]
I am also facing same issue, @firashamila33  can you please tell me the way to resolve this.

**Comment by pratulsharma** [comment]
Is anyone able solve this issue?

**Comment by dfyz011** [comment]
Still not working

**Comment by arun-mi** [comment]
Still not working

**Comment by firashamila33** [comment]
seems that this repo doesn't get the needed support anymore
