### ISSUE TITLE
Pattern for explicitly merging

### ISSUE THREAD

**Issue by juliankrispel** [draft-js-plugins/draft-js-plugins#116]
Idea: Let's stick to not merging themes with the default I think that's a good restriction. But I think if a user wants this feature, they should be able to do so easily.

This is how I imagine that working:

``` js
import createPlugin, { theme } from 'draft-js-plugin';

const myTheme = theme.merge(myStyles);

const myPlugin = createPlugin({theme: myTheme});
```

**Comment by nikgraf** [comment]
I really like this suggestions. Let's do that. You want to pick it up?
