### ISSUE TITLE
draft-js-mention-plugins: Up & down arrows misbehave

### ISSUE THREAD

**Issue by glenn-allen** [draft-js-plugins/draft-js-plugins#1161]
Similar to #1026 when there's a mention within a text block the up and down arrows won't work correctly.

This can be easily replicated on the example page: [mentions plugin](https://www.draft-js-plugins.com/plugin/mention)
Simply add multiple lines and on one of those lines add a mention then try navigating through the text using the up and down keys.

1026 relates to the plugin's `onUpArrow` and `onDownArrow` event handlers incorrectly intercepting the events.
I did not find that to be the case in my situation and instead found that it was caused by `display: inline-block;` of the `.mention` class in the default styles.

This seems to cause the browser to get confused when updating the cursor position which prevents Draft from propagating the correct change into its selection state.

So the solution I've found is to remove the `display: inline-block;` style.

I'm raising this issue in the hope it helps others who encounter it & potentially get some feedback on why this style is required in the first place.

**Comment by freedomlang** [comment]
@glenn-allen Thanks for reporting this! I've reproduced that problem you mentioned above, and surprisingly there is some different: the down key works as expected but the up key won't. Looks like  the navigation will be wrong when the  `display: inline-block` style and `mention` in a line. Will do a closer look in the next few days

**Comment by glenn-allen** [comment]
FWIW, I think I know why the `display: inline-block` style was used in the first place:  It prevents mentions with spaces from wrapping unless absolutely necessary.

I instead use `white-space: nowrap`.  This will always prevent word wrap, even when necessary, but in my case it's an acceptable workaround that doesn't result in strange arrow key behaviour.
