### ISSUE TITLE
[resizeable-plugin] When setting the options horizontal and vertical to "absolute", the initial size of the image is not respected

### ISSUE THREAD

**Issue by GabrielDuarteM** [draft-js-plugins/draft-js-plugins#1166]
## Use-case/Problem

I'm using draft-js-plugins in an e-mail editor, so the and i'm using the following packages
* `"draft-js": "0.10.4"`
* `"draft-js-focus-plugin": "^2.0.1"`
* `"draft-js-image-plugin": "^2.0.1"`
* `"draft-js-plugins-editor": "^2.0.4"`
* `"draft-js-resizeable-plugin": "^2.0.6""`

I need the image to always have the same size defined by the user (when he resizes), so I have to configure the plugin like the following:
```js
const resizeablePlugin = createResizeablePlugin({
  horizontal: "absolute",
  vertical: "absolute",
});
```

The thing is, when you do this, the image always get the default size of 40x40, which in my opinion makes no sense, because the image gets too small and you can't use the default size of the image.
Investigating the code, looks like the line causing this is [this one](https://github.com/draft-js-plugins/draft-js-plugins/blob/master/draft-js-resizeable-plugin/src/createDecorator.js#L161)

For now, I made a fork which fixes this for my needs, but I'm not sure if it addresses all use cases of the plugin, as I'm not familiar with the codebase. At least all tests passed :) You can check it [here](https://github.com/exactsales/draft-js-plugins/blob/draft-js-resizeable-plugin-v2.0.6/src/createDecorator.js#L182). Unfortunately, I commited some things not related to the fix without knowing, like prettier's formatting and some fixes to be able to run the npm scripts on windows (there are some unix specific stuff on it), so to make a PR (given that you guys agree with my solution) I would have to make re-fork it.

To demonstrate the issue, here's a [codesandbox example](https://codesandbox.io/s/yjx096rw1x). You can see that by default the image gets unreadable, with 40x40, when the original is 300x125

This may be related to #1094

**Comment by freedomlang** [comment]
@GabrielDuarteM do you mean that the height always have the same increasing(decrease) size with the width?
> the image to always have the same size defined by the user (when he resizes)

**Comment by GabrielDuarteM** [comment]
@freedomlang I meant that the image size can't be defined by a percentage of the parent element (because it can vary from email client). It has to be an absolute size, measured in pixels, so it stays consistent in all email clients

**Comment by freedomlang** [comment]
@GabrielDuarteM A config for resize unit may solve the use-case? btw, pr is welcome

**Comment by GabrielDuarteM** [comment]
Actually, what i did on the fork was instead of using a default, if a size is not found, i just leave it unsetted, so that the image would get it's default size. 

I've created a codesandbox containing my fork of the lib and the default, for you to compare. It is available [here](https://codesandbox.io/s/35vrwpy1). On the `Editor.js` file, there are those imports:

```js
import createResizeablePlugin from "../lib"
// import createResizeablePlugin from "draft-js-resizeable-plugin"
```

the first one contains my fork, and the second is the original, just switch between them to compare the results

**Comment by freedomlang** [comment]
@GabrielDuarteM Sorry for my late reply! The code on codesandbox wasn't source code, can you provide your fork address? source code is easier to read! :smile:

**Comment by GabrielDuarteM** [comment]
Of course, the package is not actually published on npm, but the source code is available at https://github.com/exactsales/draft-js-plugins/tree/draft-js-resizeable-plugin-v2.0.6

More info about the repo is available on the first post of this issue 😄

**Comment by freedomlang** [comment]
@GabrielDuarteM I've check the code and codesandbox. Finally i think i got what You mean 😢  : While using `resize-plugin`, It doesn't provide a config to set the initial size. Currently it was 40.

I think a config for the initial size would be more flexible.

**Comment by GabrielDuarteM** [comment]
@freedomlang Working on it!

When working on the PR, one thing got me thinking, would it be a problem if we removed the default value, and made it an option, instead of always defaulting to 40? That way, the image size initially will always be the image's actual size, and then the user would resize it to be the size he want's it to be. If the default option is supplied, then the image size will initially use that, instead of the images default size.

What do you think?

**Comment by thomasmikava** [comment]
Is there any news?

**Comment by sibelius** [comment]
fixed here https://github.com/draft-js-plugins/draft-js-plugins/pull/1403/files
