### ISSUE TITLE
Mention Plugin: overriding entity creation / editor state manipulation

### ISSUE THREAD

**Issue by dan-weaver** [draft-js-plugins/draft-js-plugins#1170]
## Use-case/Problem

Is there a way to override how mentions get built into entities and how they're added to `EditorState`?   This issue looks somewhat related but I wasn't sure https://github.com/draft-js-plugins/draft-js-plugins/issues/346 and it doesn't seem to have reached a conclusion.

more specifically: say an application already has a custom way of annotating mentions and you'd like to maintain that method and just use this plugin for it's autocomplete feature.  Likewise, it doesn't look like there is currently support for the creation of a mention outside of selecting it in the suggestions component (simply typing the mention to completion results in plain text, I'd like if it could create a mention using already existing functionality in the application).

Is this a feature you'd welcome in a PR?

**Comment by ramisalem** [comment]
https://gist.github.com/nicubarbaros/8a35a16dd45065891803bbfa3e451d15
