### ISSUE TITLE
[draft-js-image-plugin] Entity type not backwards compatible

### ISSUE THREAD

**Issue by dobesv** [draft-js-plugins/draft-js-plugins#1171]
## Use-case/Problem

In https://github.com/draft-js-plugins/draft-js-plugins/commit/0c98f97537dc937e1dc4bce15d26386f52e9b008#diff-7c6e0b8e32c6156fadff3f0170a0a420 the plugin was changed to emit and expect an all-caps entity type `IMAGE` instead of `image`.  However, we were using this plugin before and storing the text in the old format.  This change is not backwards-compatible so those old image no longer show up.

**Comment by freedomlang** [comment]
fixed!
