### ISSUE TITLE
draft-js-alignment-plugin - creating multiple plugins still results in the store's events being shared between instances

### ISSUE THREAD

**Issue by jonrossmacmillan** [draft-js-plugins/draft-js-plugins#1176]
## Use-case/Problem

We're needing to use multiple draft-js instances on the same page with the image and alignment plugins. While testing I found that when I clicked on a picture in one editor and scrolled the page I would see another alignment toolbar floating. I took care to make sure that every instance of our editor would get fresh instances of the plugin. I tract it down to the store creation being at the module level and not as part of the creation of the plugin. Once I moved it inside I found the problem was fixed.. 

Other side effects were that the other editor was receiving focus after I clicked on the tool bar. 
## example bug
![image](https://user-images.githubusercontent.com/42475861/44492834-7b76fc00-a62b-11e8-885a-63584d2ffdc1.png)

**Comment by freedomlang** [comment]
Merged ❤️
