### ISSUE TITLE
Image upload plugin

### ISSUE THREAD

**Issue by VladShcherbin** [draft-js-plugins/draft-js-plugins#118]
Would be awesome to see an easy plug-in/out image upload plugin.

**Comment by okonet** [comment]
I could try integrating it with https://github.com/okonet/react-dropzone

**Comment by VladShcherbin** [comment]
An integration would be great, I used this dropzone package before, had no problems. It would be a nice addition to the existing plugins.

**Comment by oyeanuj** [comment]
@VladShcherbin @okonet A great place to start could actually be @bkniffler's https://github.com/bkniffler/draft-wysiwyg. It had some very good support for image drag and drop, uploading very early on itself.  I know that he was planning to plugin-ify some of his functionality from the editor, so take a look! 

@bkniffler thoughts?

**Comment by bkniffler** [comment]
Hey, I've started to work on it now, I expect to submit it in the next few hours.

**Comment by bkniffler** [comment]
I submitted a PR (https://github.com/draft-js-plugins/draft-js-plugins/pull/145), so I think we can close this for now.
