### ISSUE TITLE
Breaking Change: Bug: Mention Plugin: Support for whitespace in mentions

### ISSUE THREAD

**Issue by JustCodin** [draft-js-plugins/draft-js-plugins#1182]
## Problem
 I reproduced the issue in a [codesandbox here](https://codesandbox.io/s/71p5q3l0jj).

**Support for whitespace in mentions (#1158)** merged 3 days ago introduces a **breaking change** when mentionTrigger is set to an empty string upon mention plugin creation as shown below:

```
    this.mentionPlugin = createMentionPlugin({
      mentionTrigger: ""
    });
```
The result is that the 'value' field of the argument for the 'onSearchChange' function passed to the 'MentionSuggestions' component is initially an empty string instead of the entered value, and all following updates are ignored (i.e., 'onSearchChange' not called) as shown below:

```
  onSearchChange({ value }) {
    console.log(`value: ${value}`);
    this.setState({
      suggestions: defaultSuggestionsFilter(value, mentions)
    });
  }
```

```
	<MentionSuggestions
		onSearchChange={this.onSearchChange}
		suggestions={this.state.suggestions}
		onAddMention={this.onAddMention}
	/>
```

This occurs without setting 

`supportWhitespace: true`

so it's a breaking change, but the **_goal is to be able to use the new 'supportWhitespace' feature with an empty string for 'mentionTrigger'_**.

## Impact
Breaks editors that use the mention plugin with an empty string as the 'mentionTrigger', i.e. _mentions without an explicit trigger_. Examples: 1.) An editor for entering email addresses, 2.) facebook style mention in a comment.  

## Personal Note
@justinneff @juliankrispel Sincere thanks to both of you for working to add this new feature. Is there any chance one of you might be able to quickly iterate on this with a fix given your recent familiarity with the required parts of the code?

**Comment by JustCodin** [comment]
@juliankrispel @freedomlang #1193 fixed the breaking change (now allows empty triggers), but now when used in combination with supportWhitespace (as described as the intended goal), it **breaks everything** by making the entire tab unresponsive.  I updated the [code sandbox](https://codesandbox.io/s/71p5q3l0jj) to use the following configuration with the most recent mention version 3.1.2

```
    this.mentionPlugin = createMentionPlugin({
      mentionTrigger: "",
      supportWhitespace: true
    });
```

Should we re-open this issue, or create a new one?

**Comment by juliankrispel** [comment]
oh noes. Not good. WIll look into this asap
