### ISSUE TITLE
Image 2.0.6 not published on npm

### ISSUE THREAD

**Issue by nperichSYKES** [draft-js-plugins/draft-js-plugins#1184]
Thanks for adding backwards compatibility with `IMAGE`! 

Looks like it hasn't been updated with npm yet.
https://www.npmjs.com/package/draft-js-image-plugin

**Comment by freedomlang** [comment]
@nperichSYKES Thanks for reporting this! that may be an oversight, we'll release it asap. @juliankrispel

**Comment by freedomlang** [comment]
@nperichSYKES published! ❤️
