### ISSUE TITLE
Emoji's auto complete is buggy on Android

### ISSUE THREAD

**Issue by Aleksion** [draft-js-plugins/draft-js-plugins#119]
Just decided to test the plugins on my Galaxy S7 (Chrome). Mentions seem to be working just fine - and so does the draftjs editor. However, the emoji plugin is acting weird when I use it. The dropdown pops up as expected when I enter a ':'. However, it doesn't update when I type, and the whole editor seems to "misbehave" afterwards:
- it randomly inserts emoji
- Stops accepting input
- Jumps to random locations in the editor. 

If none of you are on Android, I'd try to film or capture the behaviour. And if I get to it before you I'll start rooting out the error

**Comment by nikgraf** [comment]
Will look into this early next week @Aleksion - thx for reporting it!

**Comment by juliankrispel** [comment]
@Aleksion is this still an issue btw? I don't have an android phone I'm afraid.

**Comment by juliankrispel** [comment]
Closing for issue cleanup - If you need this issue and think it should remain open please let us know why, thank you

**Comment by Aleksion** [comment]
Just tested this again. It works as it should now. Good work guys!
