### ISSUE TITLE
Publish issue about divider-plugin

### ISSUE THREAD

**Issue by freedomlang** [draft-js-plugins/draft-js-plugins#1190]
## Use-case/Problem

`draft-js-divider-plugin` on [NPM](https://www.npmjs.com/package/draft-js-divider-plugin) is still `0.2.1`, and its version in repo is `1.0.0`.

mentioned in [this](https://github.com/draft-js-plugins/draft-js-plugins/pull/1069#issuecomment-405789908)

**Comment by juliankrispel** [comment]
all good
