### ISSUE TITLE
[draft-js-mention-plugin] Dropped support for special characters

### ISSUE THREAD

**Issue by rprzebieglec** [draft-js-plugins/draft-js-plugins#1192]
## Use-case/Problem

Special characters won't trigger mentions search anymore (starting version 3.1.0). This has probably something to do with unused `regExp` parameter in `mentionSuggestionsStrategy` and it was working before.

**Comment by soosap** [comment]
yes I can confirm that mention plugin only works for latin alphabet. Tried to use it with unicode characters, but the search would not kick in.

**Comment by SunilRudragada** [comment]
is there any way to support special characters in mentions
