### ISSUE TITLE
Doesn't work with browserify?

### ISSUE THREAD

**Issue by contra** [draft-js-plugins/draft-js-plugins#120]
```
Cannot find module './ReactDefaultPerf' from '/Users/contra/Projects/project-name/node_modules/draft-js-hashtag-plugin/lib'
```

It looks like the output being published to npm is specifically meant to only work with webpack, because browserify hits these require statements and blows up.

**Comment by contra** [comment]
Ah, I identified the root cause - webpack replaces `require()` calls everywhere except for places with dead code apparently. Browserify sees these and tries to resolve them, then blows up. Solution is to use dead code elimination before publishing to npm, although webpack should probably be smarter about this.

Here is an example case:

![image](https://cloud.githubusercontent.com/assets/425716/14024817/7758923a-f1c1-11e5-9a61-e521613f210d.png)

Better yet, publish code that wasn't bundled with webpack? Each plugin is bundling all of react and ends up being huge.

**Comment by nikgraf** [comment]
Hey @contra, totally agreed! To be honest I was kind of rushing doing this webpack setup after I figured simply converting it to ES5 does not do job since we have used CSS modules.

Let's fix this and just convert ES2015 to ES5. I make this my priority Nr1.

I would like to keep the generation of the default CSS classes automated. Can you recommend anything here?

**Comment by nikgraf** [comment]
Update: found this & will give it a try: https://github.com/istarkov/babel-plugin-webpack-loaders

**Comment by nikgraf** [comment]
@contra I just published a new version of every package. Do you have more suggestions for improvement?

**Comment by varun-raj** [comment]
Can we now use it with browserify ? @nikgraf

**Comment by nikgraf** [comment]
@varun-raj yes, we replace the webpack compilation and just used babel for JS compilation

**Comment by varun-raj** [comment]
Any example available for it ? I'm using browserify-rails

**Comment by nikgraf** [comment]
@varun-raj sorry, I don't know anyone using browserify 😕

**Comment by varun-raj** [comment]
@nikgraf Sure, I'd do that ! 👍
