### ISSUE TITLE
[draft-js-mention-plugin] Editor not working on Android

### ISSUE THREAD

**Issue by hashwin** [draft-js-plugins/draft-js-plugins#1203]
Please see attached video from the Simple Example from the docs.
Anytime I press '@' or Space, the entire text box just clears.
Using HTC U11 on Android Oreo 8.0

![](https://j.gifs.com/l5rR9J.gif)

**Comment by hashwin** [comment]
Seems to be a draftjs issue: https://github.com/facebook/draft-js/issues/1077

**Comment by simsim0709** [comment]
It's related to draft-js, so I close it.
