### ISSUE TITLE
draft-js-hashtag-plugin #11111 not work

### ISSUE THREAD

**Issue by janjon** [draft-js-plugins/draft-js-plugins#1205]
#11111 
The use of simple numbers is not effective. If you add letters, you can

#11111a

**Comment by freedomlang** [comment]
@janjon Currently, hashtag-plugin follow the Twitter's strategy. So it doesn’t work with pure number.

**Comment by janjon** [comment]
Stories tried to change draft-js-hashtag-plugin to Lib instead of working.

```javascript
resolve: {
    alias: {
      'draft-js-plugins-editor': path.join(__dirname, '..', 'draft-js-plugins-editor', 'src'),
      'draft-js-hashtag-plugin': path.join(__dirname, '..', 'draft-js-hashtag-plugin', 'lib'),
```
I used the problem I found in the project, and then tried to run in stories to see if there was the same problem.

**Comment by janjon** [comment]
In my project, trying to break points in ```hashtagStrategy```. JS is not accessible, just as ```decorators``` are not included.

**Comment by freedomlang** [comment]
@janjon 不好意思这么晚才回复。你的意思是你想断点`hashtagStrategy` 来调试，但是失败了？
