### ISSUE TITLE
[draft-js-mention-plugin] Trigger open suggestions programmatically

### ISSUE THREAD

**Issue by JoseOrtiz** [draft-js-plugins/draft-js-plugins#1207]
## Use-case
I have an external button, as a shortcut, to mention users.
There is not possible to open the suggestion module, when you have a trigger character, without adding that trigger.
Can you add a way to open the suggestions with a function?

**Comment by mohamedfasil** [comment]
Hi I found a way to do this, 
Basically you have to update editorstate with your mentiontrigger appended to the text and bring focus to the editor, so on your onclick you'll need to execute something like this.

```JS
const { editorState } = this.state;
const text = editorState.getCurrentContent().getPlainText();
const contentState = ContentState.createFromText(`${text} @`);
this.setState({
  editorState: EditorState.createWithContent(contentState)
}, () => {
  setTimeout(() => {
    this.editor.current.focus();
  }, 200);
})
```

**Comment by pederjohnsen** [comment]
I've worked on some changes to allow something similar for a project in work, my changes are here: https://github.com/pederjohnsen/draft-js-plugins/commit/02abe73a3316fb50afc083c6b822fe11dc076f0c

This allows you to do something like this:
```
import addMention from 'draft-js-mention-plugin/lib/modifiers/addMention';

const = mentionPluginProps = {
  entityMutability: 'IMMUTABLE',
  mentionPrefix: '@',
  mentionTrigger: '@',
};

...
  onMentionSelect(mention) {
    const newEditorState = addMention(
      this.editor.current.getEditorState(),
      mention,
      this.mentionPluginProps.mentionPrefix,
      this.mentionPluginProps.mentionTrigger,
      this.mentionPluginProps.entityMutability,
    );

    this.editor.current.onChange(newEditorState);
  }
...
```

This would require onMentionSelect to be triggered by a selection from a custom suggestions box.

I'd be happy to create a PR if this is something wanted for the library.

(I've also been working on adding support for emoji mart for the emoji plugin but currently using a fork of emoji mart, so until I either get any changes I required from my fork pushed back into the main lib or find a way without using my fork I won't be creating a PR for that)

**Comment by bebeun** [comment]
Hi,

I am desperately trying to insert a very basic mention from a button aside the editor. Is there a basic way to call a function which can add a mention at the cursor position just as if it were selected in the mentionsSugestion list ?

Regards

**Comment by xuan9230** [comment]
> Hi,
> 
> I am desperately trying to insert a very basic mention from a button aside the editor. Is there a basic way to call a function which can add a mention at the cursor position just as if it were selected in the mentionsSugestion list ?
> 
> Regards

Check the solution provided by @mohamedfasil. Works perfect for me

**Comment by xuan9230** [comment]
There's a problem with mohamedfasil's solution - it will convert all previous content into plain text, losing other information. So here's a improved version:

```
const newContentState = Modifier.insertText(
      editorState.getCurrentContent(),
      editorState.getSelection(),
      '@',
    );
    const newEditorState = EditorState.push(
      editorState,
      newContentState,
      'insert-fragment',
    );
    setEditorState(newEditorState);
    setTimeout(() => {
      inputRef.current && inputRef.current.focus();
    }, 200);
```

**Comment by sibelius** [comment]
What slack does is to add a `@` when clicking on the mention button

should we add this do the docs?

**Comment by agrawal-rohit** [comment]
> There's a problem with mohamedfasil's solution - it will convert all previous content into plain text, losing other information. So here's an improved version:
> 
> ```
>     const newContentState = Modifier.insertText(
>       editorState.getCurrentContent(),
>       editorState.getSelection(),
>       '$',
>     );
> 
>     const newEditorState = EditorState.push(
>       editorState,
>       newContentState,
>       'insert-fragment',
>     );
> 
>     setEditorState(newEditorState);
> 
>     setTimeout(() => {
>       inputRef.current && inputRef.current.focus();
>     }, 200);
> ```

This worked perfectly! Thanks @xuan9230

**Comment by dungict1510** [comment]
You can reference at this link . 
https://codesandbox.io/s/still-sun-ktc3k?file=/src/App.js
