### ISSUE TITLE
Factor in scrollTop of editor / optional ref when positioning toolbars

### ISSUE THREAD

**Issue by G-Rath** [draft-js-plugins/draft-js-plugins#1211]
Currently the toolbars (SideToolbar & InlineToolbar - I've not actually used StaticToolbar) calculate their position via `node.offsetTop + editorRoot.offsetTop`.

This doesn't take into account the scrolling of the editor, or the parents of the editor.

The simplest fix would be to adjust the positioning math to be `node.offsetTop + editorRoot.offsetTop - editorRoot.scrollTop`. The downside is that this results the scrolling to be happening on the editor itself, but it'd at least be a start.

Ideally, I'd like to be able to pass a `ref`(/`element`) who's `scrollTop` is used in place of `editorRoot`s.

I'm happy to give a go at making a PR for this, but am a little rushed right now, and are not familiar with the practices of this repo (so not sure if it's considered 'ok' to just add a prop to the toolbars) - am happy to expand on this issue via discussion 😄

I have this feature working locally without any apparent issues; My proposal is that the toolbars take a ref prop `scrollOffsetRef`, like so:

```
<SideToolbar scrollOffsetRef={this.props.scrollOffsetRef} />
```

**Comment by ashishkumar-compro** [comment]
Hi,

I am having the same problem with both SideToolbar and Inline Toolbar.

Please find the below screenshot for reference:

![image](https://user-images.githubusercontent.com/54092895/67092008-cbb80280-f1cb-11e9-8ec0-88ca5833142d.png)

I found the below line in Inline Toolbar Plugin but did not find a way to set this variable:

https://github.com/draft-js-plugins/draft-js-plugins/blob/040436205cdf59236267c4dca40c80d41b8b8f9c/draft-js-inline-toolbar-plugin/src/components/Toolbar/index.js#L86

Maybe if we can set this variable from outside then we can send the scrollTop of the container or maybe we can send in the reference of the container.

The same implementation can then be applied to SideToolbar :
https://github.com/draft-js-plugins/draft-js-plugins/blob/040436205cdf59236267c4dca40c80d41b8b8f9c/draft-js-side-toolbar-plugin/src/components/Toolbar/index.js#L84
