### ISSUE TITLE
Inline toolbar sometimes doesn't appear upon selection

### ISSUE THREAD

**Issue by sidewayskumara** [draft-js-plugins/draft-js-plugins#1212]
I am having an issue where under certain circumstances, like refreshing the page, selecting text doesn't prompt the inline toolbar to be visible as expected (shown in images). Then after clicking outside the draft editor, and then trying again, it works. The draft editor component is within a react-grid-layout component. I've been scratching my head on this for a few days now and was wondering if this has been encountered by anyone else. Thanks in advance.

<img width="545" alt="screenshot 2018-10-20 11 52 07" src="https://user-images.githubusercontent.com/26181282/47250604-e3e12e80-d45e-11e8-852f-1377a5540fc1.png">
<img width="363" alt="screenshot 2018-10-20 11 52 27" src="https://user-images.githubusercontent.com/26181282/47250600-e04da780-d45e-11e8-84ff-9baebc46f5e5.png">

**Comment by freedomlang** [comment]
@sidewayskumara Do you mean the inline-toolbar doesn't work after refresh? 

What versions do you use(editor and plugins)?

Btw, a codesandbox would be nice!

**Comment by sidewayskumara** [comment]
I wasn't able to reproduce it in sandbox, I'm still not sure what the problem was but moving forward with development it seems to not be an issue anymore.
