### ISSUE TITLE
[draft-js-static-toolbar-plugin] custom buttons

### ISSUE THREAD

**Issue by kamiky** [draft-js-plugins/draft-js-plugins#1214]
It seems that passing a ``structure`` array doesn't work anymore to customize the toolbar buttons, i've seen the last commit where you deleted it.

https://github.com/draft-js-plugins/draft-js-plugins/commit/9b8b12ffdc4552d13ba5dfcfa1a1be4a21956cea

Would be nice to update the documentation (https://www.draft-js-plugins.com/plugin/static-toolbar), i'm still trying to figure out what you expect as Toolbar Children

**Comment by tanotify** [comment]
+1
Is there any way to solve it?

**Comment by kamiky** [comment]
ok i managed to make it work, but it's kinda dirty, i'm not sure this module version should remain.
Toolbar children prop expect a function, so i copied this function (https://github.com/draft-js-plugins/draft-js-plugins/blob/9975f41d7f0533843882e5bf4e483081c17f7d12/draft-js-static-toolbar-plugin/src/components/Toolbar/index.js#L38)

```
export default class ToolbarEditor extends PureComponent {
...
renderButtons = (externalProps) => (
    <div>
      <ItalicButton {...externalProps} />
      <BoldButton {...externalProps} />
      <UnderlineButton {...externalProps} />
      <CodeButton {...externalProps} />
    </div>
  )

...

render() {
    return (
      <div>
        <div className='editor' onClick={this.focus}>
          <Editor
            editorState={this.state.editorState}
            onChange={this.onChange}
            plugins={plugins}
            ref={(element) => { this.editor = element; }}
          />
          <Toolbar chilren={this.renderButtons}></Toolbar>
        </div>
      </div>
    );
  }
}
```

you can then customize which button you want to return

**Comment by freedomlang** [comment]
@kamiky Thanks for reporting this, we'll update it asap. ❤️

**Comment by freedomlang** [comment]
@kamiky The docs just updated! 🎉
