### ISSUE TITLE
Custom button icons

### ISSUE THREAD

**Issue by toropanov** [draft-js-plugins/draft-js-plugins#1216]
Could you please explain is there any way to change icons of such Draft JS Buttons as UnorderedListButton, BoldButton and etc to my custom svg icons

**Comment by freedomlang** [comment]
@tanotify Use `createBlockStyleButton` or `createInlineStyleButton` exported by `draft-js-buttons`.

```javascript
const BoldButton = createInlineStyleButton({
  style: 'BOLD',
  children: (custom_svg_here),
});
```
