### ISSUE TITLE
[draftjs-mention-plugin] popoverComponent throwing TypeError: Cannot set property 'transform' of undefined

### ISSUE THREAD

**Issue by Mangaraju-Velpula** [draft-js-plugins/draft-js-plugins#1218]
Hi guys,

I am getting following error while passing popoverComponent to MentionSuggestions.

![error1](https://user-images.githubusercontent.com/13298665/47793357-18e55f00-dd44-11e8-8ba6-8d03c8008c55.PNG).

While going through the MentionSuggestions code, I found following line causing this issue in componentDidUpdate. If i pass popoverComponent  as div or span it is working fine because div or span have attribute styles but if i pass component it is causing issue(Due to absence of style attribute on component).

`Object.keys(newStyles).forEach((key) => {
        this.popover.style[key] = newStyles[key];
  });`

Please refer above code in below link:
https://github.com/draft-js-plugins/draft-js-plugins/blob/9975f41d7f0533843882e5bf4e483081c17f7d12/draft-js-mention-plugin/src/MentionSuggestions/index.js#L70

Code:
**PopoverComponent** :

```
class PopoverComponent extends React.Component { 

	render() {
		console.log("PopOverComponent ", this.props)
		return (
			<div className={"chat-area-new-des "+this.props.className} role={this.props.role} {...this.props}>
				<div className="chat-text">
					<div className>
						<div className=" ">
							<ul className="drop-up" role="menu">
								<span className="chat-area-chatslashmenu-title">User matching “@Rozina”
									<span className="pull-right chat-area-navigation" />
								</span>
							</ul>
							{this.props.children}
						</div>
					</div>
				</div>
			</div>);
	}
}
```

**MentionSuggestions:** 
```
class Suggestions extends React.Component {
	constructor(props, context) {
		super(props, context);
		this.state = {
			suggestions: mentions,
		};
	}
	onSearchChange = ({ value }) => {
		this.setState({
			suggestions: mentions,
		});
	}
	onAddMention = (mentionEntity) => {
		console.log('Here is add mentions ', mentionEntity);
	}
	render() {
		return (
			<MentionSuggestions
				onSearchChange={this.onSearchChange}
				suggestions={this.state.suggestions}
				onAddMention={this.onAddMention}
				popoverComponent={<PopoverComponent {...this.props}/>}
			/>
		);
	}
}
```

Please help me on this one.

Thanks in advance.

**Comment by G-Rath** [comment]
Sorry for the "+1" style comment, but I'm having this same issue.

I suspect this is just incorrect behaviour, as you've hit the nail on the head: if `popoverComponent` is of type `HTMLAttribute`, it works fine since it has style attributes, but components won't have this, making this prop pretty much unusable. (or at least, in contradiction to the documentation, which states that you should be able to pass a component).

I'm working on a userland work around/fix as we speak, and will let you know what I come up with.

But regardless, this is a bug - either the code or documentation needs updating.

**Comment by G-Rath** [comment]
@Mangaraju-Velpula you can prevent this crash by overriding the `positionSuggestions` function/prop, and having it return an empty object.

This however creates the problem of having to find a way to recalculate position, and pass that to the custom component.

**Comment by Mangaraju-V** [comment]
Thank you @G-Rath
