### ISSUE TITLE
[draftjs-mention-plugin] MentionSuggestions popover is not triggering immediately after mentionTrigger until some text is added.

### ISSUE THREAD

**Issue by Mangaraju-Velpula** [draft-js-plugins/draft-js-plugins#1220]
Hi Guys, 

I am getting an issue with MentionSuggestions Popover. For the first time MentionSuggestions popover open immediately after mentionTrigger but for the next time mentionTrigger is not triggering the MentionSuggestions popover until you need to type some text.

Here is my plugin config:
 ```
createMentionPlugin({
		positionSuggestions,
		mentionPrefix: '@',
		mentionTrigger: '@',
		supportWhitespace: true,
		entityMutability: 'IMMUTABLE',
	})
```
**Please refer gif below**
![untitled4](https://user-images.githubusercontent.com/13298665/48257022-57aba100-e437-11e8-8ddc-3346cf8e7f08.gif)

Can someone please help me on this.

Thanks in advance.

**Comment by johnsenpeder** [comment]
Looks like this happens when one sets `supportWhitespace` to true :thinking: 
Did you find a solution in the end @Mangaraju-Velpula?

**Comment by YoonjiJang** [comment]
https://github.com/draft-js-plugins/draft-js-plugins/blob/master/draft-js-mention-plugin/src/MentionSuggestions/index.js#L133

changing the `>` to `>=` seems to do the trick for me but I don't have a good understanding of the codebase so I can't be certain that this won't cause other issues. 🤔

**Comment by m1n0s** [comment]
@YoonjiJang I think this sign may differ based on `supportWhitespace` prop.
Anyway, that's a great idea I'd say. Please make a PR and core team will say if it's proper way. 
I also need this functionality ASAP. 
If you haven't enough time please let me know I'll do the PR. Just don't want to steal your solution :)

**Comment by YoonjiJang** [comment]
@m1n0s You can go ahead and make a PR 😄

**Comment by jack-arms** [comment]
This is still an issue in the latest version, @m1n0s @YoonjiJang did either of you make a PR based on your discussion?

**Comment by YoonjiJang** [comment]
@jack-arms I'm super busy at the moment :( anyone's more than welcomed to make a PR

**Comment by liamjohnston** [comment]
@m1n0s Any update on this? I really need this functionality too :( 

It seems a bit buggy also. Sometimes the popover does show instantly, sometimes it doesn't. 

See video:
[bug.mov.zip](https://github.com/draft-js-plugins/draft-js-plugins/files/3748831/bug.mov.zip)

It seems like adding a mention will stop it working with only the symbol, and clearing the field will make it work again?? But no idea what's really going on.

**Comment by dav-sap** [comment]
any updates on this? :)

**Comment by Vannevelj** [comment]
Just adding my voice to this that I've got the same issue. @YoonjiJang the LoC your link points to is off since it's not linking to a commit directly -- do you happen to recall which one you were thinking off?

**Comment by SamuelTSO** [comment]
any updates on this? :)

**Comment by YoonjiJang** [comment]
@Vannevelj Apologies for the late response. I believe I was linking to this line. https://github.com/draft-js-plugins/draft-js-plugins/blame/65d5e57de6f35dfa533c4e58fea4096a2edf23cf/draft-js-mention-plugin/src/MentionSuggestions/index.js#L133

**Comment by worc** [comment]
was a PR for this bug ever made?

**Comment by ashercoren** [comment]
This bug still exists; why was it closed?

**Comment by ashercoren** [comment]
Thank you @artursvonda for re-opening.
Is there a plan to fix this soon? If not, can you tell if what @YoonjiJang suggested (changing the > to >=) is a good fix?

**Comment by artursvonda** [comment]
Hey! Not sure about the solution. Would need to look into it. But feel free to create a PR.

**Comment by fxOne** [comment]
@Vannevelj does this error still occurs? I tried it with the latest version where it worked for me.

**Comment by Vannevelj** [comment]
@fxOne If it does, that's wonderful news. I haven't tested a recent version yet but I'll see if I can give that a go. I do notice that I can't reproduce the issue in the "_Custom Themed Mention Example_" so that would certainly support what you've seen.
