### ISSUE TITLE
There isn't whitespace before trigger for supportWhitespace mode.

### ISSUE THREAD

**Issue by souljja** [draft-js-plugins/draft-js-plugins#1222]
When i type some text and in the middle of the word write @ then appear mention popover, but when `supportWhitespace` mode is disabled, everything is OK. 
I saw that when `supportWhitespace` disabled, in regexp used `(\\s|^)`.
Please add it and for enabled `supportWhitespace` mode.

**Comment by evp3103** [comment]
I have same issue

**Comment by kramarmm** [comment]
So have I.
Is there any progress on it?
