### ISSUE TITLE
Miss match in entityRanges with emoji as presiding text to mentions

### ISSUE THREAD

**Issue by SureshSc** [draft-js-plugins/draft-js-plugins#1226]
Hi 

i am using mentions plugin it works awesome as expected without emojis/unicode. 

My situations

ex: "😀 dude **Suresh Chandrababu**" is my text in editor. Suresh Chandrababu is mention.

I need to extract the mention offset position, length and send to my API, problem here is when emojis/unicode added before the mentions, offset returned by Draft editor was wrong.

Expected o/p: entityRange - offset:3, length: 18
Actual o/p: entityRange - offset:2, length: 18

Emoji's length is 2, but entityRange consider it as 1.

How to handle this situation.

o/p:
<img width="510" alt="screen shot 2018-11-20 at 1 17 48 pm" src="https://user-images.githubusercontent.com/5052940/48758628-b3431d80-ecc6-11e8-8caf-d151909df95d.png">

Thanks in advance

**Comment by johnsenpeder** [comment]
We also have this problem, anyone has any ideas?

**Comment by erlindsalla** [comment]
Any update on this?

**Comment by kalemi19** [comment]
Same problem here.
