### ISSUE TITLE
Problem with positioning of Mention menu

### ISSUE THREAD

**Issue by souljja** [draft-js-plugins/draft-js-plugins#1227]
## Mention Suggestions list has wrong position when supportWhitespace enabled

![mention](https://user-images.githubusercontent.com/24767181/49014829-7083b880-f192-11e8-8f09-c354b99a5636.png)

When i added mention in the middle of text block, mention list has wrong position.

![wrong position](https://user-images.githubusercontent.com/24767181/49014939-b6d91780-f192-11e8-98a2-7234a68d38e1.png)

**Comment by freedomlang** [comment]
@souljja Thanks for reporting this.  Can you provide a `codesandbox` to reproduce it?

**Comment by souljja** [comment]
@freedomlang link to `codesandbox` https://codesandbox.io/s/4xo3qx2kr4

Also I made screenshot.

![mention](https://user-images.githubusercontent.com/24767181/49245174-a4750d00-f422-11e8-88a2-520f286fe34a.png)

Steps to reproduce: 
Just type a lot of long text like on the screenshot and then try to type some mention in the middle of this text.
