### ISSUE TITLE
draft-js-emoji-plugin TypeError: this.props.getEditorState is not a function when trying to render " :" in Editor

### ISSUE THREAD

**Issue by taylorcjohnson** [draft-js-plugins/draft-js-plugins#1234]
## Problem

When using the draft-js-emoji-plugin, an error is created when attempting to render a readOnly Editor component if the message includes a colon preceded by a space (e.g., "hello : world"). I'm not sure if this is a bug, or if I somehow incorrectly configured the draft-js plugins. 

## Reproduction
Here is an [example using the draft-js-emoji-plugin](https://codesandbox.io/s/k2w4lv0vmv?module=%2Fsrc%2FMyEditor.js) - with one single hard-coded text value. I am able to replicate the same error - "TypeError this.props.getEditorState is not a function".

## Description
The error is caused from within the componentWillMount lifecycle method of the EmojiSuggestionPortal component. I believe that when I try to pass editorState to Editor (using EditorState.createWithContent), the plugin gets to the " :" and tries to invoke the EmojiSuggestions component which creates the EmojiSuggestionPortal - even though this is a readOnly Editor. However, it is looking for getEditorState() on this.props - it isn't there, but *is* on this.props.store. Update: @ermanolca pointed out below that it doesn't matter if the Editor is readOnly.

## Solution?
To test locally, I added a check to see if getEditorState exists on this.props - if it does, *then* perform the trigger to re-render so EmojiSuggestions becomes active. This check allows both " :" and actually emojis to display properly.

Please let me know if I can provide any additional information. Thank you in advance (I'm new to draft-js and the plugins so I apologize if this was just a simple oversight on my part).

**Comment by sohansarma** [comment]
Any solution for the same?

**Comment by hjpunzalan** [comment]
just dont use it lol. It seemss like there no choice but to edit the plugin package itself

**Comment by ermanolca** [comment]
It is not just about readOnly attribute. When remove readOnly, same error remains.

**Comment by FilipMessa** [comment]
Hi guys, currently I am trying to solve the same issue but with the mentions plugin, did you find some solution for that?

**Comment by irtefa** [comment]
Having the same problem with mentions plugin like @FilipMessa

**Comment by ButlerBorst** [comment]
Having the same issue..

**Comment by minhdang241** [comment]
Having the same issue :(

**Comment by dieterwalckiers** [comment]
I have the same issue.
For me it's solved when I change
`this.props.setEditorState(this.props.getEditorState());`
to
`this.props.store.setEditorState(this.props.store.getEditorState());`

because as @taylorcjohnson mentioned, the functions are there in the store.
And it looks like they are reliably there, when I look at this initialize function in index.js:
```
initialize: ({ getEditorState, setEditorState }) => {
      store.getEditorState = getEditorState;
      store.setEditorState = setEditorState;
    },
```

Moreover, the exact same is done in other places (EmojiSuggestions component).

Could I open a PR that takes the set/getEditorState from store?

Thanks
Dieter

**Comment by albertodarblade** [comment]
@dieterwalckiers  the same issue is happening in the mentions plugins Could you fixed too, it seems the fix you did for Emoji work great!.

**Comment by dieterwalckiers** [comment]
@albertodarblade 
I opened a PR.

**Comment by sohaibqasem** [comment]
If any one still have this issue.

In preview mode.
you need to make sure that you pass the **Plugin & the Decorators** from the same instance of the **creatementionplugin** function. something like this :

```js
const { FriendsSuggestions, FriendsPlugin, FriendsDecorators } = React.useMemo(() => {
        const FriendsPlugin = createMentionPlugin(...);
        const FriendsSuggestions = FriendsPlugin.MentionSuggestions;
        const FriendsDecorators = FriendsPlugin.decorators;
        return { FriendsPlugin, FriendsSuggestions, FriendsDecorators };
    }, []);
```
and then pass them to the editorState.

this error could happen in edit mode when there is already a content you want to edit, Just make sure that the editorState is not empity when you render the editor.  something like this :
```js
export const isEditorEmpty = (state: EditorState) => {
    return (!state.getCurrentContent().hasText() || state.getCurrentContent().getPlainText().trim().length === 0)
}
```

I will try to write a codeSandbox for this bug

**Comment by sridharAINQA** [comment]
@sohaibqasem I am having this issue in Edit mode. When I tried your solution,
```
export const isEditorEmpty = (state: EditorState) => {
    return (!state.getCurrentContent().hasText() || state.getCurrentContent().getPlainText().trim().length === 0)
}
```
It throws the following error,
```
_this.props.onOpenChange is not a function
    at MentionSuggestions._this.openDropdown (index.esm.js:696)
    at Object.MentionSuggestions._this.onEditorStateChange [as onChange] (index.esm.js:554)
```

It would be better if you provider a codesandbox. Thanks

**Comment by GodAlmighty990** [comment]
SOLUTION FOR this.props.store.getEditorState is not a function.  IF YOU ARE USING SUGGESTIONS AND EMOJI // <--- notice my error is this.props.store.getEditorState is not a function. NOT this.props.getEditorState is not a function which is the title of this thread.

Hello Everyone, I am using draft-js along with draft-js-plugins/mention AND draft-js-plugins/emoji.  When you follow draft-js by the docs, If you use suggestions it will have you using a useMemo like this below


` 
   const emojiPlugin = createEmojiPlugin();

   const { EmojiSuggestions, EmojiSelect } = emojiPlugin;



 const { MentionSuggestions, plugins } = useMemo(() => {
    const mentionPlugin = createMentionPlugin();
    // eslint-disable-next-line no-shadow
    const { MentionSuggestions } = mentionPlugin;
    // eslint-disable-next-line no-shadow
    const plugins = [mentionPlugin];
    return { plugins, MentionSuggestions };
  }, []);
`

I was declaring my emoji plugin and { emojiSuggestions, EmojiSelect } = emojiPlugin OUTSIDE of the useMEMO and this was giving the error of this.props.store.getEditorState is not a function // was showing undefined when logging out this.props.store in actual index.esm.js 

My solution when using BOTH suggestions and emoji was the change the useMemo this below

`
  const { MentionSuggestions, EmojiSuggestions, EmojiSelect, plugins } = useMemo(() => {
    const mentionPlugin = createMentionPlugin({
      entityMutability: 'IMMUTABLE',
      theme: mentionsStyles,
      //mentionPrefix: '@',
      supportWhitespace: true,
    });
    const emojiPlugin = createEmojiPlugin();

    const { EmojiSuggestions, EmojiSelect } = emojiPlugin;
    // eslint-disable-next-line no-shadow
    const { MentionSuggestions } = mentionPlugin;
    // eslint-disable-next-line no-shadow
    const plugins = [mentionPlugin, emojiPlugin];
    return { plugins, MentionSuggestions, EmojiSuggestions, EmojiSelect };
  }, []);

`

Short story THINK ABOUT YOUR USEMEMO IF YOUR FOLLOWING THEIR DOCS THEY SHOULD HAVE THIS IN THE DOCS!!!!!!  ;))

**Comment by MamorukunBE** [comment]
Hi guys! In fact, AFAIK, all plugins having this very problem uses a undocumented function called... initialize. In case of this Emoji plugin, here is it signature:

```ts
    initialize: function initialize(_ref) {
      var getEditorState = _ref.getEditorState,
          setEditorState = _ref.setEditorState;
      store.getEditorState = getEditorState;
      store.setEditorState = setEditorState;
    }
```

So, to solve the problem, just call it and give it the corresponding callbacks:

```ts
    const emojiPlugin = createEmojiPlugin();
    emojiPlugin.initialize({
        getEditorState: whateverFunctionReturningEditorState,
        setEditorState: whateverFunctionUpdatingEditorState
    });
```

Hope this helps :)

**Comment by burakguneli** [comment]
@MamorukunBE this solved the issue for me. thanks!!!

**Comment by GodAlmighty990** [comment]
@wilfredonoyola 

not sure if this helps but here is my useMemo for emoji plugins, suggestions plugins, and linkify with draft.js


`const { MentionSuggestions, EmojiSuggestions, EmojiSelect, plugins } = useMemo(() => {
  const mentionPlugin = createMentionPlugin({
    entityMutability: 'IMMUTABLE',
    theme: mentionsStyles,
    //mentionPrefix: '@',
    supportWhitespace: true,
  });
  const emojiPlugin = createEmojiPlugin({
    selectButtonContent: <FontAwesomeIcon
    icon={['far', 'laugh-beam']}
    transform="shrink-4"
    onClick={() => setPreviewEmoji(!previewEmoji)}
  />,
    theme: defaultTheme,
    useNativeArt: true
  });
  const linkifyPlugin = createLinkifyPlugin()

  const { EmojiSuggestions, EmojiSelect } = emojiPlugin;
  // eslint-disable-next-line no-shadow
  const { MentionSuggestions } = mentionPlugin;
  // eslint-disable-next-line no-shadow
  const plugins = [mentionPlugin, emojiPlugin, linkifyPlugin];
  return { plugins, MentionSuggestions, EmojiSuggestions, EmojiSelect };
}, []);


Here is the useEffect in a component using those plugins

//-------------------------------When first in createBulk trigger this to check for contentState in bulkMessageReducer-------------------------------------------------------------------------------------------------------------------------------------------

// when redux state changes, trigger this useEffect
useEffect(() => {

  if(bulkMessageReducer.contentState && !compose[0]?.composeTemplate) {
      const { contentState } = bulkMessageReducer
      if(!contentState.entityMap) {
        contentState = { entityMap: {},
        blocks: contentState.blocks}
        const decorators = plugins.reduce((acc, p) => [...acc, ...p.decorators], []);
        const decorator = new CompositeDecorator(decorators);
        setEditorState(EditorState.createWithContent(convertFromRaw(contentState)))
      } else { 
        const decorators = plugins.reduce((acc, p) => [...acc, ...p.decorators], []);
        const decorator = new CompositeDecorator(decorators);
        setEditorState(EditorState.createWithContent(
        convertFromRaw(contentState), decorator)) }
  }

}, [])



And here is my Editor with emojiSuggestions

      <div 
              style={{minHeight: "7em", maxHeight: "10em", overflow: "auto"}}
              className={`border border-2x border-300 bg-light rounded-soft fs-1 ${editorStyles.editor}` }
              onClick={() => { messageFieldRef.current.focus(); }}
            >
            <Editor
              editorKey={'editor'}
              currentContent={ContentState}
              editorState={editorState}
              onChange={setEditorState}
              plugins={plugins}
              ref={messageFieldRef}
            />
            <EmojiSuggestions />
            <MentionSuggestions
              open={open}
              onOpenChange={onOpenChange}
              suggestions={suggestions}
              onSearchChange={onSearchChange}
              onAddMention={(e) => {// get the mention object selected
              }}
              entryComponent={Entry}
              />
            </div>
            <div>
                <EmojiSelect closeOnEmojiSelect />
              <span color="light" className="px-3 py-1 bg-soft-info rounded-capsule shadow-none fs--1 ml-3" >
                <FontAwesomeIcon icon="tags" transform="left-3"/>
                 Type <strong>@</strong> for custom fields
              </span>
            </div>
