### ISSUE TITLE
EditorState.moveFocusToEnd(EditorState.createEmpty()) working incorrectly with version ^2.1.1

### ISSUE THREAD

**Issue by phananhnhat** [draft-js-plugins/draft-js-plugins#1238]
I need reset editorState of Comment Editor after press Enter. I use 

```
resetAddComment = () => {
        this.setState({
            editorState: EditorState.moveFocusToEnd(EditorState.createEmpty()),
        });
    };
```

In Chrome, selectionState will return to 0 when I press the first character. In Firefox,that fail and my app stop because error. 
It works incorrectly with version ^2.1.1 but exactly with "2.0.0-rc2"

**Comment by guljarpd** [comment]
You have to use push to reset your existing editor.
```
resetAddComment= () => {
    const editorState = EditorState.push(
      this.state.editorState,
      ContentState.createFromText('')
    );
    this.setState({ editorState });
}; 
```

**Comment by phananhnhat** [comment]
> You have to use push to reset your existing editor.
> 
> ```
> resetAddComment= () => {
>     const editorState = EditorState.push(
>       this.state.editorState,
>       ContentState.createFromText('')
>     );
>     this.setState({ editorState });
> }; 
> ```



> You have to use push to reset your existing editor.
> 
> ```
> resetAddComment= () => {
>     const editorState = EditorState.push(
>       this.state.editorState,
>       ContentState.createFromText('')
>     );
>     this.setState({ editorState });
> }; 
> ```

I want reset comment with empty EditorState. Your solution exits undoStack in EditorState
