### ISSUE TITLE
CSS not being applied 

### ISSUE THREAD

**Issue by rajaraodv** [draft-js-plugins/draft-js-plugins#124]
Hi there,
Great job! I am trying out the plugins and followed all the steps but when I try to use mention plugin or linkyfy plugin, I see that neither one of them are actually using the CSS. 
I guess I am not sure how the` import styles from './styles.css';` actually work. I am under the impression that the plugins we install already come w/ styles and should work out of the box.

**Comment by alexkuz** [comment]
If you're using webpack, use `style-loader` and `css-loader` and add this to your webpack config:
```js
module: {
  loaders: [{
    test: /\.css$/,
    loaders: [
      'style', 'css'
    ]
  }]
}
```
then you can import default styles:
```js
import 'draft-js-mention-plugin/lib/plugin.css';
```

**Comment by nikgraf** [comment]
thanks for helping out here @alexkuz! really appreciated. I added a guide on how to do it with webpack to all the plugin pages.

**Comment by tafelito** [comment]
HI, I know this is an old issue, but I just created a new react app with create-react-app, added draft-js-pluigns and draft-js-inline-toolbar-plugin but the plugin.css seems not to be loading. I know the cra already has the css loader (I actually verified it by ejecting the project) but the styles are still not loading. Im using the latest release, 2.0.0-beta 10. This is what I see when I run the app

![image](https://cloud.githubusercontent.com/assets/5973652/25298479/3292e154-26c3-11e7-85e2-d7d0eb878bfa.png)

Any ideas what might be the issue?

**Comment by nikgraf** [comment]
@tafelito you need to manually import it, I guess that doesn't help, but I'm confident it's there.

**Comment by arthurkushman** [comment]
Hi all, I've been manually imported as instructed here - https://www.draft-js-plugins.com/plugin/static-toolbar
from this directory - `node_modules/draft-js-inline-toolbar-plugin/lib/plugin.css`
And for sure installed all the webpack loaders/dependencies long time ago and updated - there are no errors, but the styles applied only for `<div>` element, but not for `draftJsToolbar`. 
I don't see any `:global` keyword in plugin.css, so how they could be loaded? 
What should I do then?

**Comment by arthurkushman** [comment]
This is my code with which I'm experimenting:
```js
import React, {Component} from 'react';
import '../../../../node_modules/draft-js-mention-plugin/lib/plugin.css';
import  '../../../../node_modules/draft-js-inline-toolbar-plugin/lib/plugin.css';
import '../../../../node_modules/draft-js-image-plugin/lib/plugin.css';
import '../../../../node_modules/draft-js/dist/Draft.css';
import editorStyles from '../../../css/editor.css';

import Editor, {createEditorStateWithText} from 'draft-js-plugins-editor';
import createToolbarPlugin, {Separator} from 'draft-js-static-toolbar-plugin';
import {
    ItalicButton,
    BoldButton,
    UnderlineButton,
    CodeButton,
    HeadlineOneButton,
    HeadlineTwoButton,
    HeadlineThreeButton,
    UnorderedListButton,
    OrderedListButton,
    BlockquoteButton,
    CodeBlockButton,
} from 'draft-js-buttons';


class HeadlinesPicker extends Component {
    componentDidMount() {
        setTimeout(() => {
            window.addEventListener('click', this.onWindowClick);
        });
    }

    componentWillUnmount() {
        window.removeEventListener('click', this.onWindowClick);
    }

    onWindowClick = () =>
        // Call `onOverrideContent` again with `undefined`
        // so the toolbar can show its regular content again.
        this.props.onOverrideContent(undefined);

    render() {
        const buttons = [HeadlineOneButton, HeadlineTwoButton, HeadlineThreeButton];
        return (
            <div>
                {buttons.map((Button, i) => // eslint-disable-next-line
                    <Button key={i} {...this.props} />
                )}
            </div>
        );
    }
}

class HeadlinesButton extends Component {
    onClick = () =>
        // A button can call `onOverrideContent` to replace the content
        // of the toolbar. This can be useful for displaying sub
        // menus or requesting additional information from the user.
        this.props.onOverrideContent(HeadlinesPicker);

    render() {
        return (
            <div className={editorStyles.headlineButtonWrapper}>
                <button onClick={this.onClick} className={editorStyles.headlineButton}>
                    H
                </button>
            </div>
        );
    }
}

const toolbarPlugin = createToolbarPlugin({
    structure: [
        BoldButton,
        ItalicButton,
        UnderlineButton,
        CodeButton,
        Separator,
        HeadlinesButton,
        UnorderedListButton,
        OrderedListButton,
        BlockquoteButton,
        CodeBlockButton
    ]
});
const {Toolbar} = toolbarPlugin;
const plugins = [toolbarPlugin];
const text = 'In this editor a toolbar shows up once you select part of the text …';

export default class CustomToolbarEditor extends Component {

    state = {
        editorState: createEditorStateWithText(text),
    };

    onChange = (editorState) => {
        this.setState({
            editorState,
        });
    };

    focus = () => {
        this.editor.focus();
    };

    render() {
        return (
            <div>
                <div className={editorStyles.editor} onClick={this.focus}>
                    <Editor
                        editorState={this.state.editorState}
                        onChange={this.onChange}
                        plugins={plugins}
                        ref={(element) => {
                            this.editor = element;
                        }}
                    />
                    <Toolbar />
                </div>
            </div>
        );
    }
}
```

**Comment by damnx** [comment]
34243 @ @ #

**Comment by GrandVizierOlaf** [comment]
I had the same issue with Webpack 4 and fixed it with this (for inline-toolbar-plugin):

`import '!style-loader!css-loader!draft-js-inline-toolbar-plugin/lib/plugin.css';`

I did not add anything to my webpack config directly.

**Comment by florianmartens** [comment]
Was there any success in solving this issue @tafelito . I am struggling with the same and currently looking into rebuilding all the plugins which is quite the heavy task ...

I have created a CodingSandbox. Maybe someone who solved this can show in there how to get the styles working:

https://codesandbox.io/s/distracted-gates-w2g7e 

I also created a related Issue #1375
