### ISSUE TITLE
Mentions Not Triggering with Second Instance of Plugin

### ISSUE THREAD

**Issue by mankee10200** [draft-js-plugins/draft-js-plugins#1242]
## Use-case/Problem

I am using the CustomMentionsEditor defined here https://www.draft-js-plugins.com/plugin/mention. My site has an instance of the CustomMentionsEditor which loads when the site loads, allowing users to post new comments and mention other users. However, the same CustomMentionsEditor is loaded again later when someone presses "Reply" on somebody else's comment. This second CustomMentionsEditor does not trigger the MentionsSuggestions. I am also using the StaticToolbar plugin, and this works fine in both editors. I've followed suggestions about updating the EditorState using 

`EditorState.push(this.state.editorState, ContentState.createFromText('')) `

however, this doesn't fix the issue. I've also looked at the FAQ which says you must define separate instances of the plugin if you want to reuse them in the same component, however this is not my use case as I am only using one instance of the plugin in the component, it's just that the component itself has two instances on the site.

**Comment by simplicitylab** [comment]
I have the same problem. Multiple tabs with a component encapsulating the draftjs editor using the mention plugin (not custom) The first tab with the editor works fine, switching to another tab and the on the second editor it does not work, go back to the first tab and it also stopped working. 

StaticToolbar and Emoiji has no problems.

**Comment by jianfenkezhan** [comment]
you should check your cursor, there is some problem, try this:
```js
<div ref={element => {this.editorBox = element}} onClick={this.focus} >
        <Editor
          editorState={editorState}
          onChange={this.onChange}
           .........
          placeholder={intl.get('2f0wb6mobk4').d('请输入消息')}
          ref={element => {
            this.editor = element;
          }}
        />
</div>
```
this.setState({editorState}, () => {this.editorBox.click()})

**Comment by hero-guo** [comment]
I have the same problem.

**Comment by tiwariAtkoolkanya** [comment]
Any solution for this ?
@hero-guo 
@jianfenkezhan 
@simplicitylab

**Comment by mac-deviget** [comment]
I am having the same problem, can't see the mentions box

**Comment by hrolick-git** [comment]
I have the same problem.

**Comment by Rykuno** [comment]
I found a solution for this issue. Basically for each editor rendered you must make a new instance of the plugins.

` const [{ plugins, InlineToolbar, CustomCounter }] = useState(() => {
    const inlineToolbarPlugin = createInlineToolbarPlugin();
    const counterPlugin = createCounterPlugin();

    const { CustomCounter } = counterPlugin;
    const { InlineToolbar } = inlineToolbarPlugin;

    const plugins = [inlineToolbarPlugin, counterPlugin];
    return {
      plugins,
      InlineToolbar,
      CustomCounter
    };
  });`
