### ISSUE TITLE
Multiple draftjs editors cannot be used on the same page using plugins

### ISSUE THREAD

**Issue by tariqporter** [draft-js-plugins/draft-js-plugins#1244]
Multiple draftjs editors cannot be used on the same page using plugins. All interactions are sent to the last instance on the page.

Clone the repo, install dependencies and change line 77 in `/stories/index.js`

from

`  .add('CustomToolbarEditor', () => <CustomToolbarEditor />)`

to

`  .add('CustomToolbarEditor', () => <div><CustomToolbarEditor /><CustomToolbarEditor /></div>)`

Now run `yarn storybook` and open the correct example

![image](https://user-images.githubusercontent.com/8306435/53268525-546db580-36b4-11e9-8ffe-5da54ce7f9e4.png)

Test functionality of both editors and you will see the controls misbehave and target the last editor.

![screenrecording20190222at3](https://user-images.githubusercontent.com/8306435/53268935-7ae02080-36b5-11e9-9783-0b04b954ee39.gif)

A similar issue is https://github.com/draft-js-plugins/draft-js-plugins/issues/548

**Comment by MartinSeeler** [comment]
This is really an issue for me. Any suggestions or workarounds?

**Comment by tariqporter** [comment]
@MartinSeeler 

Taking from the comments, in the example at 

https://github.com/draft-js-plugins/draft-js-plugins/blob/master/stories/static-toolbar/src/App.js

I have changed the code to look like the following to resolve this. Multiple plugins will work with this method

```
import React, { Component } from 'react';
import Editor, { createEditorStateWithText } from 'draft-js-plugins-editor';
import createToolbarPlugin from 'draft-js-static-toolbar-plugin';
import editorStyles from './editorStyles.css';

export default class SimpleInlineToolbarEditor extends Component {
  constructor(props) {
    super(props);
    const text = 'The toolbar above the editor can be used for formatting text, as in conventional static editors  …';
    const inlineToolbarPlugin = createToolbarPlugin();
    this.Plugins = {
      Toolbar: inlineToolbarPlugin.Toolbar
    };
    this.plugins = [inlineToolbarPlugin];
    this.state = {
      editorState: createEditorStateWithText(text)
    };
  }

  onChange = (editorState) => {
    this.setState({
      editorState,
    });
  };

  focus = () => {
    this.editor.focus();
  };

  render() {
    const { Toolbar } = this.Plugins;
    return (
      <div>
        <div className={editorStyles.editor} onClick={this.focus}>
          <Editor
            editorState={this.state.editorState}
            onChange={this.onChange}
            plugins={this.plugins}
            ref={(element) => { this.editor = element; }}
          />
          <Toolbar />
        </div>
      </div>
    );
  }
}
```

**Comment by MartinSeeler** [comment]
Thank you, I have converted it to something similar with `useState`. With this, each editor get's its own plugins.

```jsx
const CustomEditor = () => {
  const [editorState, setEditorState] = useState(() => EditorState.createEmpty());

  const [{ plugins, Toolbar }] = useState(() => {
    const toolbarPlugin = createToolbarPlugin();
    const { Toolbar } = toolbarPlugin;
    const plugins = [toolbarPlugin];
    return {
      plugins,
      Toolbar
    };
  });

  const editorRef = useRef(null);

  return (
    <div>
      <div
        className="editor"
        onClick={() => editorRef.current && editorRef.current.focus()}
      >
        <Editor
          editorState={editorState}
          onChange={(newEditorState: EditorState) => setEditorState(newEditorState)}
          plugins={plugins}
          ref={(editor: any) => (editorRef.current = editor)}
        />
        <Toolbar>
          {// may be use React.Fragment instead of div to improve perfomance after React 16
          (externalProps: any) => (
            <div>
              <BoldButton {...externalProps} />
              <ItalicButton {...externalProps} />
              <UnderlineButton {...externalProps} />
              <CodeButton {...externalProps} />
              <Separator {...externalProps} />
              <UnorderedListButton {...externalProps} />
              <OrderedListButton {...externalProps} />
            </div>
          )}
        </Toolbar>
      </div>
    </div>
  );
};
```

**Comment by ZRCU** [comment]
Helllo everyone!

@MartinSeeler thank you very much for your solution. I had the same issue and it works. But when I do the same with InlineToolbar instead of StaticToolbar, then I keep getting an error `store.getItem(...) is not a function`.

My main idea is that InlineToolbar needs something extra from the Editor and can't get it before mount, but I'm not sure how exactly InlineToolbar works. 

Do you have any ideas of how I may try to fix this?

Thank you in advance!

**Comment by vegardalvsaker** [comment]
@ZRCU Did you solve this issue?

**Comment by pcabreus** [comment]
> Thank you, I have converted it to something similar with `useState`. With this, each editor get's its own plugins.
> 
> ```js-jsx
> const CustomEditor = () => {
>   const [editorState, setEditorState] = useState(() => EditorState.createEmpty());
> 
>   const [{ plugins, Toolbar }] = useState(() => {
>     const toolbarPlugin = createToolbarPlugin();
>     const { Toolbar } = toolbarPlugin;
>     const plugins = [toolbarPlugin];
>     return {
>       plugins,
>       Toolbar
>     };
>   });
> 
>   const editorRef = useRef(null);
> 
>   return (
>     <div>
>       <div
>         className="editor"
>         onClick={() => editorRef.current && editorRef.current.focus()}
>       >
>         <Editor
>           editorState={editorState}
>           onChange={(newEditorState: EditorState) => setEditorState(newEditorState)}
>           plugins={plugins}
>           ref={(editor: any) => (editorRef.current = editor)}
>         />
>         <Toolbar>
>           {// may be use React.Fragment instead of div to improve perfomance after React 16
>           (externalProps: any) => (
>             <div>
>               <BoldButton {...externalProps} />
>               <ItalicButton {...externalProps} />
>               <UnderlineButton {...externalProps} />
>               <CodeButton {...externalProps} />
>               <Separator {...externalProps} />
>               <UnorderedListButton {...externalProps} />
>               <OrderedListButton {...externalProps} />
>             </div>
>           )}
>         </Toolbar>
>       </div>
>     </div>
>   );
> };
> ```

Document this some how, thanks a lot

**Comment by theindiansoftwarecompany** [comment]
> Helllo everyone!
> 
> @MartinSeeler thank you very much for your solution. I had the same issue and it works. But when I do the same with InlineToolbar instead of StaticToolbar, then I keep getting an error `store.getItem(...) is not a function`.
> 
> My main idea is that InlineToolbar needs something extra from the Editor and can't get it before mount, but I'm not sure how exactly InlineToolbar works.
> 
> Do you have any ideas of how I may try to fix this?
> 
> Thank you in advance!

Hey, did you solve this for InlineToolbarPlugin?

**Comment by Alejopdp** [comment]
> Thank you, I have converted it to something similar with `useState`. With this, each editor get's its own plugins.
> 
> ```js-jsx
> const CustomEditor = () => {
>   const [editorState, setEditorState] = useState(() => EditorState.createEmpty());
> 
>   const [{ plugins, Toolbar }] = useState(() => {
>     const toolbarPlugin = createToolbarPlugin();
>     const { Toolbar } = toolbarPlugin;
>     const plugins = [toolbarPlugin];
>     return {
>       plugins,
>       Toolbar
>     };
>   });
> 
>   const editorRef = useRef(null);
> 
>   return (
>     <div>
>       <div
>         className="editor"
>         onClick={() => editorRef.current && editorRef.current.focus()}
>       >
>         <Editor
>           editorState={editorState}
>           onChange={(newEditorState: EditorState) => setEditorState(newEditorState)}
>           plugins={plugins}
>           ref={(editor: any) => (editorRef.current = editor)}
>         />
>         <Toolbar>
>           {// may be use React.Fragment instead of div to improve perfomance after React 16
>           (externalProps: any) => (
>             <div>
>               <BoldButton {...externalProps} />
>               <ItalicButton {...externalProps} />
>               <UnderlineButton {...externalProps} />
>               <CodeButton {...externalProps} />
>               <Separator {...externalProps} />
>               <UnorderedListButton {...externalProps} />
>               <OrderedListButton {...externalProps} />
>             </div>
>           )}
>         </Toolbar>
>       </div>
>     </div>
>   );
> };
> ```

Man, thanks a lot, been struggling a couple of days with this issue. In my case i'm using the Mentions Plugin. With this solution some styles are getting broken, do u have any idea of what it could be?

![Examples](https://user-images.githubusercontent.com/32003170/89113165-c7fd2000-d46d-11ea-8f73-f5e52f4a4539.png)

Anyways, i moved on a lot with your solution.

Thanks again!

**Comment by MartinSeeler** [comment]
@Alejopdp I'm not sure if this is related to the provided solution or just because you're using the editor in different places, where CSS is evaluated differently based on parent rules etc. I'd guess that the functionality does not impact the CSS rules. Try to analyze it in dev tools and which styles are getting applied.

**Comment by sibelius** [comment]
try to create plugins on render

`const plugins = useMemo(() => mentionPlugin, []);`

**Comment by majuric** [comment]
> Helllo everyone!
> 
> @MartinSeeler thank you very much for your solution. I had the same issue and it works. But when I do the same with InlineToolbar instead of StaticToolbar, then I keep getting an error `store.getItem(...) is not a function`.
> 
> My main idea is that InlineToolbar needs something extra from the Editor and can't get it before mount, but I'm not sure how exactly InlineToolbar works.
> 
> Do you have any ideas of how I may try to fix this?
> 
> Thank you in advance!

If this is still a problem for someone, I had the same issue, and the order of adding components matters for InlineToolbar. It needs to be added `below` the Editor component.

```
...
<Editor {...all editor props}}/>
<InlineToolbar/>
...
```

The order for StaticToolbar does not matter.

**Comment by sr-webcode** [comment]
> > Thank you, I have converted it to something similar with `useState`. With this, each editor get's its own plugins.
> > ```
> > const CustomEditor = () => {
> >   const [editorState, setEditorState] = useState(() => EditorState.createEmpty());
> > 
> >   const [{ plugins, Toolbar }] = useState(() => {
> >     const toolbarPlugin = createToolbarPlugin();
> >     const { Toolbar } = toolbarPlugin;
> >     const plugins = [toolbarPlugin];
> >     return {
> >       plugins,
> >       Toolbar
> >     };
> >   });
> > 
> >   const editorRef = useRef(null);
> > 
> >   return (
> >     <div>
> >       <div
> >         className="editor"
> >         onClick={() => editorRef.current && editorRef.current.focus()}
> >       >
> >         <Editor
> >           editorState={editorState}
> >           onChange={(newEditorState: EditorState) => setEditorState(newEditorState)}
> >           plugins={plugins}
> >           ref={(editor: any) => (editorRef.current = editor)}
> >         />
> >         <Toolbar>
> >           {// may be use React.Fragment instead of div to improve perfomance after React 16
> >           (externalProps: any) => (
> >             <div>
> >               <BoldButton {...externalProps} />
> >               <ItalicButton {...externalProps} />
> >               <UnderlineButton {...externalProps} />
> >               <CodeButton {...externalProps} />
> >               <Separator {...externalProps} />
> >               <UnorderedListButton {...externalProps} />
> >               <OrderedListButton {...externalProps} />
> >             </div>
> >           )}
> >         </Toolbar>
> >       </div>
> >     </div>
> >   );
> > };
> > ```
> 
> Document this some how, thanks a lot

this is Godsend! thanks! @MartinSeeler

**Comment by mty-tidjani** [comment]
@MartinSeeler solution is great, thanks.
I did mine with **useMemo** and got the same effect.

```
const plugins = ['mensions', 'linkify', 'hashtags']

const { selectedPlugins, MentionSuggestions } = useMemo(() => {
	return initSelectedPlugins({
		plugins
	})
}, [])
```

**initSelectedPlugins** is just a utility function to add plugins from an array of string since I use Editor differently for many purpose.

Thanks again.

**Comment by timuster** [comment]
> 

This did not work for me. While it does "work", every hot reload (on code change during development) leads to the crash with the `store.getItem(...) is not a function` error.

**Comment by timuster** [comment]
> > Helllo everyone!
> > @MartinSeeler thank you very much for your solution. I had the same issue and it works. But when I do the same with InlineToolbar instead of StaticToolbar, then I keep getting an error `store.getItem(...) is not a function`.
> > My main idea is that InlineToolbar needs something extra from the Editor and can't get it before mount, but I'm not sure how exactly InlineToolbar works.
> > Do you have any ideas of how I may try to fix this?
> > Thank you in advance!
> 
> If this is still a problem for someone, I had the same issue, and the order of adding components matters for InlineToolbar. It needs to be added `below` the Editor component.
> 
> ```
> ...
> <Editor {...all editor props}}/>
> <InlineToolbar/>
> ...
> ```
> 
> The order for StaticToolbar does not matter.

This did not work for me. While it does "work", every hot reload (on code change during development) leads to the crash with the store.getItem(...) is not a function error.

**Comment by arbiasgj** [comment]
> > > Helllo everyone!
> > > @MartinSeeler thank you very much for your solution. I had the same issue and it works. But when I do the same with InlineToolbar instead of StaticToolbar, then I keep getting an error `store.getItem(...) is not a function`.
> > > My main idea is that InlineToolbar needs something extra from the Editor and can't get it before mount, but I'm not sure how exactly InlineToolbar works.
> > > Do you have any ideas of how I may try to fix this?
> > > Thank you in advance!
> > 
> > 
> > If this is still a problem for someone, I had the same issue, and the order of adding components matters for InlineToolbar. It needs to be added `below` the Editor component.
> > ```
> > ...
> > <Editor {...all editor props}}/>
> > <InlineToolbar/>
> > ...
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > The order for StaticToolbar does not matter.
> 
> This did not work for me. While it does "work", every hot reload (on code change during development) leads to the crash with the store.getItem(...) is not a function error.

Same for me as well. Can't get it to work with the InlineToolbar feature. Been trying to debugg and find the reason behind it via devTools but so far no luck!

**Comment by fxOne** [comment]
The [example](https://www.draft-js-plugins.com/plugin/inline-toolbar) has multiple editors on one page. Maybe you can provide an full https://codesandbox.io/ example so that I can reproduce the issue?

**Comment by Bizzle-Dapp** [comment]
> Thank you, I have converted it to something similar with `useState`. With this, each editor get's its own plugins.
> 
> ```js
> const CustomEditor = () => {
>   const [editorState, setEditorState] = useState(() => EditorState.createEmpty());
> 
>   const [{ plugins, Toolbar }] = useState(() => {
>     const toolbarPlugin = createToolbarPlugin();
>     const { Toolbar } = toolbarPlugin;
>     const plugins = [toolbarPlugin];
>     return {
>       plugins,
>       Toolbar
>     };
>   });
> 
>   const editorRef = useRef(null);
> 
>   return (
>     <div>
>       <div
>         className="editor"
>         onClick={() => editorRef.current && editorRef.current.focus()}
>       >
>         <Editor
>           editorState={editorState}
>           onChange={(newEditorState: EditorState) => setEditorState(newEditorState)}
>           plugins={plugins}
>           ref={(editor: any) => (editorRef.current = editor)}
>         />
>         <Toolbar>
>           {// may be use React.Fragment instead of div to improve perfomance after React 16
>           (externalProps: any) => (
>             <div>
>               <BoldButton {...externalProps} />
>               <ItalicButton {...externalProps} />
>               <UnderlineButton {...externalProps} />
>               <CodeButton {...externalProps} />
>               <Separator {...externalProps} />
>               <UnorderedListButton {...externalProps} />
>               <OrderedListButton {...externalProps} />
>             </div>
>           )}
>         </Toolbar>
>       </div>
>     </div>
>   );
> };
> ```

For functional component solution, this is the correct way to go about it. Cheers!
