### ISSUE TITLE
Anchor Plugin - Should have option to normalize with https instead of http

### ISSUE THREAD

**Issue by scottanglr** [draft-js-plugins/draft-js-plugins#1245]
With http sites now marked as"Not Secure" by default in Google Chrome, it would be better to normalise urls with https by default instead of http. If not that, because it could be a breaking change to some, an extra parameter "https: true" could be passed in the config.

**Comment by randolf** [comment]
Unfortunately, there are many web sites that have broken TLS/SSL hosting so I support this being a configurable option.  I do think that within 5 years "https" should be the default though.
