### ISSUE TITLE
Can't use both Static Toolbar and Inline Toolbar

### ISSUE THREAD

**Issue by OriR** [draft-js-plugins/draft-js-plugins#1246]
## Using both Static Toolbar & Inline Toolbar plugins on the same editor doesn't work.
This problem is mainly due to class name clashing.
That's weird because it uses css modules but unfortunately, that's the case 😕 
See the attached image, both plugins for got the same initial hash for the class name of the toolbar.

![image](https://user-images.githubusercontent.com/2384068/53871061-22d5e200-4004-11e9-8d0c-c535227b542d.png)

**Comment by antoniojps** [comment]
Yep, can confirm. Same happens here.

**Comment by CedricVanhaverbeke** [comment]
Any update on this?

**Comment by Alejopdp** [comment]
Hi, does anybody found a fix for this issue?

**Comment by Alejopdp** [comment]
If it helps, i changed the name of the classes and updated the style-linking under the node_modules\draft-js-inline-toolbar-plugin\lib\index.js file with them. Also you'll want to modify the /components/separator/index.js in case you want to use it.

Don't think this is the best approach tho...

**Comment by sr-webcode** [comment]
If it helps, I used Styled Components on this scenario, I copied the native css properties for both the Inline & Static toolbar, then I placed them in their own Styled Component. In that way the styles won't collide if you plan to re-use them.

![image](https://user-images.githubusercontent.com/49327821/99871749-f159db80-2c17-11eb-9739-8f8a34c875a0.png)

If you want ,you can  create a universal toolbar styled container then configure the styles to accept props then conditionally apply the right properties. [Using Props](https://styled-components.com/docs/basics#adapting-based-on-props)
