### ISSUE TITLE
How to display saved mentions with style?

### ISSUE THREAD

**Issue by gkhan205** [draft-js-plugins/draft-js-plugins#1248]
Hello All,

I have saved mentions with my comment to DB and after retrieving it styles are not getting rendered for mentions only. rest all stylings are working fine. 

```
const rawData = JSON.parse(comment);
    const parsedState = convertFromRaw(rawData);
    const commentContext = EditorState.createWithContent(parsedState);
    this.setState({
      editorState: commentContext,
      suggestions: this.fetchMention(rawData.entityMap)
    });
```
This is the display of my comments list
![comments-mentios](https://user-images.githubusercontent.com/24544854/54264105-52eb2b00-4598-11e9-81c2-83d4d0b736eb.png)

I want my mentions to be styled like in my editor which is below:
![comment-editor](https://user-images.githubusercontent.com/24544854/54264194-8928aa80-4598-11e9-8914-0eea2bcbd795.png)

Can anyone help me achieve this?

**Comment by danhtran94** [comment]
Because mention can be customized without using @. you should parse it back to entities base on your pattern.
in my case, my mention pattern is {{ .XYZ }}
below is sample parser.

`
const parseMentions: (
  contentState: Draft.ContentState
) => Draft.ContentState = state => {
  let contentState = state;
  contentState.getBlockMap().forEach(block => {
    if (block) {
      const mentionPattern = /{{ ?((\.\w+)+) ?}}/gm;

      let matched;
      while ((matched = mentionPattern.exec(block.getText()))) {
        const mention = matched[0];
        const anchor = matched.index;
        const focus = anchor + mention.length;

        const blockKey = block.getKey();

        const selection = new SelectionState({
          anchorKey: blockKey,
          anchorOffset: anchor,
          focusKey: blockKey,
          focusOffset: focus
        });

        contentState.createEntity("{{mention", "IMMUTABLE", {
          mention: { name: mention }
        });

        const entityKey = contentState.getLastCreatedEntityKey();

        contentState = Modifier.applyEntity(contentState, selection, entityKey);
      }
    }
  });

  return contentState;
};`

**Comment by timuster** [comment]
@danhtran94  Can you please share the complete example?
