### ISSUE TITLE
Add an option to not hide the mention suggestions dropdown

### ISSUE THREAD

**Issue by Andkoo** [draft-js-plugins/draft-js-plugins#1250]
## Use-case/Problem

- Use case: My chat input includes 2 icons and draft.js editor. The suggestions dropdown should be placed above the chat input, spanning even the area above the icons, otherwise it looks weird.
- Problem: I can't figure out a way to make the dropdown wider than the editor to span even the area above the icons. I can't inspect the dropdown element to play with its styles, because as soon as I try to click on it in my inspector, the editor loses focus and the dropdown gets removed from the DOM. The docs are as uninformative as it gets and even when I copied the code from the docs and tried to run it, it wasn't working as expected on my end. Maybe it would also be fine to update the docs with a detailed API documentation instead of terms like `must implement the same interface` (how does it look like?) or `Additional properties are passed` (which ones?).

**Comment by Pardeep94** [comment]
@Andkoo Did you find any way to solve the problem?

**Comment by worc** [comment]
ran into the same issue today. i'm trying to debug a styling issue with the popover, but the moment the editor loses focus the popover is removed from the DOM
