### ISSUE TITLE
Wrong displaying of mention in editor

### ISSUE THREAD

**Issue by souljja** [draft-js-plugins/draft-js-plugins#1252]
**Steps to reproduce:**
1) Open page with text editor.
2) Write @ sign.
3) Select symbol @ by mouse (it's important).
4) Write @@mat
5) Press enter.

**As a result we have**
![image](https://user-images.githubusercontent.com/24767181/55400607-fd7eba00-5556-11e9-9238-65643c9928a1.png)

You can reproduce it here: https://codesandbox.io/s/4xo3qx2kr4

**Comment by kramarmm** [comment]
I've faced the same issue

**Comment by Dremuchev** [comment]
Are there any updates for this ticket? We have this problem too!

**Comment by fxOne** [comment]
I just tried it in the latest version but the MentionSuggestion closes when you enter the 2nd @. The enter results then in a new line.

**Comment by Dremuchev** [comment]
Tried in the last version

![screen](https://user-images.githubusercontent.com/34788837/110130242-d9c6ed00-7dd9-11eb-9dd1-5b2e2b47220f.gif)

**Comment by fxOne** [comment]
What browser are you using and can you share the source code?

**Comment by Dremuchev** [comment]
Google chrome@last. Source code is above [code from author](https://codesandbox.io/s/4xo3qx2kr4)

**Comment by fxOne** [comment]
Yes, but the code from the author is using the deprecated packages `draft-js-plugins-editor` and `draft-js-mention-plugin` which are no longer supported. So do you have a reproducible demo which uses the latest version of  `@draft-js-plugins/editor` and `@draft-js-plugins/mention`?

**Comment by Dremuchev** [comment]
yep ) this is good for us. Fixed problem by updating next dependencies. Thanks a lot to @fxOne for the tip 🙏🙏🙏💪

- draft-js-mention-plugin@3.1.5
- draft-js-plugins-editor@3.0.0
- draft-js@0.11.7
