### ISSUE TITLE
Nextjs inline toolbar isn't working

### ISSUE THREAD

**Issue by markolofsen** [draft-js-plugins/draft-js-plugins#1258]
Could you implement Inline Toolbar for nextjs? I did it, but toolbar isn't working.
![pro](https://user-images.githubusercontent.com/13606299/56807764-0306b180-6830-11e9-8122-2c3b1c73e6aa.png)

**Comment by luisfilipegoncalves** [comment]
@markolofsen can you share what you have done so far ? I was not able to get that far using nextjs. 

Thanks

**Comment by fxOne** [comment]
There is an issue with SSR and draft-js which can be found here with a solution: https://github.com/facebook/draft-js/issues/2332#issuecomment-761573306
