### ISSUE TITLE
getEditorState from Plugin

### ISSUE THREAD

**Issue by HaNdTriX** [draft-js-plugins/draft-js-plugins#126]
Hey @nikgraf 

First of all thanks for this cool project!
I was playing around with it and asking myself how to get the editor state from a plugin without passing it in via a component.

E.g: When I want to add a plugin, that handles keyCommands, I would use the `handleKeyCommand` callback, but I have no access to the editorState.

Of course I could add a `<KeyCommandComponent editorState={this.state.editorState}>` explicitly, but then I need to register the Plugin in two places.

What am I missing?

**Comment by nikgraf** [comment]
I'm glad you like it :smile:

So far I haven't had the use-case where `getEditorState` was required to passed to `handleKeyCommand `. Nevertheless if you have a use-case I'm happy merge a PR where `getEditorState` & `updateEditorState` are passed as 2nd & 3rd argument to `handleKeyCommand`.

That's the line that you would need to extend: https://github.com/draft-js-plugins/draft-js-plugins/blob/master/draft-js-plugins-editor/src/Editor/index.js#L126

I'm curious what your use-case is :smiley:

**Comment by HaNdTriX** [comment]
I am not sure if I am on right track. 
But one use case could be to create a plugin that handles the basic key commands.

    export default createBasicKeyBindingsPlugin = () => {
      return {
        pluginProps: {
          handleKeyCommand: (command, getEditorState, updateEditorState) => ()=> {
            const editorState = getEditorState();
            const newState = RichUtils.handleKeyCommand(editorState, command);
            if (newState) {
              updateEditorState(newState);
              return true;
            }
            return false;
          }
        }
      };
    };

or:

    export default createBasicKeyBindingsPlugin = () => {
      let onChange, getEditorState;
      return {
        pluginProps: {
          getEditorState,
          onChange,
          handleKeyCommand: (command) => ()=> {
            const editorState = getEditorState();
            const newState = RichUtils.handleKeyCommand(editorState, command);
            if (newState) {
              onChange(newState);
              return true;
            }
            return false;
          }
        }
      };
    };

Changing the plugin api is a pretty big change, that could be difficult to revoke in the future.
Wich approach do you prefer?

**Comment by nikgraf** [comment]
It should be the first one as this is a patter than we already use all over :+1:

**Comment by HaNdTriX** [comment]
Sure? I thought the second one is the pattern we already use all over ;)
