### ISSUE TITLE
Is this repo still maintained?

### ISSUE THREAD

**Issue by thaoms** [draft-js-plugins/draft-js-plugins#1262]
I haven't seen much responses on issues, and haven't seen a lot of commits lately.

**Comment by r3verser** [comment]
same question

**Comment by grant-davidson** [comment]
Such a good library, a pity it seems to be dying.

**Comment by a-x-** [comment]
There is 600 forks, 
but github does not provide convenient tool to select better one

**Comment by a-x-** [comment]
looks https://github.com/pederjohnsen/draft-js-plugins is last fork was be alive, but death too now
