### ISSUE TITLE
[draft-js-emoji-plugin] crash after I wrote specific emoji

### ISSUE THREAD

**Issue by martin-badin** [draft-js-plugins/draft-js-plugins#1267]
Hello, when I write from mobile emoji as an example the number 7 ![Snímka obrazovky 2019-05-31 o 9 19 49](https://user-images.githubusercontent.com/5845264/58688633-4ef3cb80-8385-11e9-8e3b-a561f97c3579.png) then draftjs editor crash with this error. I use the native ios keyboard and native emojis.

`TypeError: undefined is not an object (evaluating 'l.default.emojioneList[m].unicode')`

**Comment by Sauloxd** [comment]
This is a known issue, there is another opened issue here: https://github.com/facebook/draft-js/issues/1636

A possible workaround (not a good one though, but it avoids the crashing) is to set `{ useNativeArt: true }`!
