### ISSUE TITLE
[draft-js-anchor-plugin] Cannot get theming to work properly

### ISSUE THREAD

**Issue by ynotdraw** [draft-js-plugins/draft-js-plugins#1274]
Hello.  First off, thanks so much for all of these plugins - they are great!

I'm having a hard time getting the theming to work as outlined by the docs at https://www.draft-js-plugins.com/plugin/anchor in our app.  To eliminate some added complexity, I went ahead and created a codesandbox example as well, copying directly from the docs page.  That can be found at https://codesandbox.io/s/draft-js-inline-link-issue-eic9y.  I'm probably just missing something really dumb here!

**Comment by mrfambo** [comment]
Hey @ynotdraw , I forked your sandbox and updated it to help you. You had passed the css file itself. But you had to create the object with Specified key values mentioned in the Documentation. Here is the Sandbox for you.

https://codesandbox.io/s/draft-js-inline-link-issue-vbsig?fontsize=14

By the way, i was here on the Repository to learn it :D and i saw your question, luckily i got a hit and made it work :D I don't know more about draft-js-plugins

**Comment by ynotdraw** [comment]
Doh! After reading the docs, I see I missed this bit 😭.  Thanks so much @mrfambo that works great!  I appreciate you taking the time to check into this issue and hope it helped you as well 😂
