### ISSUE TITLE
How to get whole html mentionComponent from createMentionPlugin?

### ISSUE THREAD

**Issue by mchaledg19** [draft-js-plugins/draft-js-plugins#1276]
`export default class CorrespondencePresenter extends Component {
  constructor(props) {
    super(props);
    this.state = {
      editorState: EditorState.createEmpty(),
      suggestions: getProjectMembers(this.props.project.members),
      commentList: []
    };

    this.mentionPlugin = createMentionPlugin({
      mentions: this.state.suggestions,
      **mentionComponent: mentionProps => {
        return (
          <>
            <span
              id={`key-${mentionProps.entityKey}`}
              className={mentionProps.className}
              // eslint-disable-next-line no-alert
              // onClick={() => alert('Clicked on the Mention!')}
            >
              {mentionProps.children}
            </span>
            <UncontrolledPopover
              trigger="legacy"
              placement="bottom"
              target={`key-${mentionProps.entityKey}`}>
              <PopoverHeader>{mentionProps.entityKey}</PopoverHeader>
              <PopoverBody>User data here / Project related / etc</PopoverBody>
            </UncontrolledPopover>
          </>
        );
      }**
    });
  }

// ADDITIONAL CODES BELOW.................................
`

After I mentioned someone I want to send/save it to the database and my problem was I am only saving the "Mike DG" as string. I want to save the whole [mentionComponent] (the html format) so that I can do something on it like clicking then showing popover from reactstrap. 

Please help... thanks

![Capture](https://user-images.githubusercontent.com/46014163/60096583-eb8e6b00-9783-11e9-926c-ff631bce7bbf.PNG)

**Comment by mchaledg19** [comment]
I got it

**Comment by ganeshcse2991** [comment]
@mchaledg19 How did you do it. I am facing the same issue . Please help

**Comment by mchaledg19** [comment]
You can do it by using convertToRaw when saving and convertFromRaw when fetching
