### ISSUE TITLE
How to retrieve and save mentions in the backend and display it in the front end again

### ISSUE THREAD

**Issue by ganeshcse2991** [draft-js-plugins/draft-js-plugins#1278]
## Finding it difficult to get the comment value with mentions from the Editor (this.state.editorState).

I want to get the value from the editorState and save it in the backend and display it in the frontend as such. 

For Example:

I have type my message in the Editor with three mentions. I am not sure how to save it in the backed so that i can display it as such while displaying the comment in a div with mentions. Please help. 

Thanks in Advance.

**Comment by gauravsoti1** [comment]
I have the same task.

**Comment by ganeshcse2991** [comment]
I have written an article about it. Please check it and let me know if you still have problems with this.

[https://medium.com/upshotly/implementing-using-react-mentions-from-react-to-database-and-vice-versa-657c936cfc42](Check the medium article here)

**Comment by gauravsoti1** [comment]
I didn't like react-mention because it doesn't give me flexibility to do more as I have a lot functionality: mention, hashtag. Therefore I opted for draft js. Also, I don't want to save html in my db, that way it becomes platform dependent. I need to come up with a solution acceptable for any platform.

**Comment by Pardeep94** [comment]
Anyone find any solution?

**Comment by gauravsoti1** [comment]
@Pardeep94 convert editorState into stringified rawState like this:
`const stringifiedRawState = JSON.stringify(convertToRaw(editorState.getCurrentContent()));`
And save this to database.

**Comment by Pardeep94** [comment]
@gauravsoti1 How to convert it back to editor state??

**Comment by gauravsoti1** [comment]
@Pardeep94 to convert it back to editor state:
`const rawState = JSON.parse(stringifiedRawState);
const contentState= convertFromRaw(rawState);
const editorState=EditorState.createWithContent(contentState)
`

**Comment by Pardeep94** [comment]
**For future reader**

we need to pass onChange funtion `(onChange={ (editorState) => this.setState({editorState})})` even if we access the editor in read only mode.
