### ISSUE TITLE
"setEditorState is not a function"  when remove image [bug]

### ISSUE THREAD

**Issue by sessionboy** [draft-js-plugins/draft-js-plugins#1297]
I tried to run [this example](https://github.com/draft-js-plugins/draft-js-plugins/tree/master/stories/adding-images), but got an error when I deleted the image

<img width="818" alt="WX20190730-124423@2x" src="https://user-images.githubusercontent.com/17827693/62101379-d4352700-b2c7-11e9-9f17-612fd7871688.png">

**Comment by sessionboy** [comment]
Now I know why.
I installed the latest version of draft-js, which caused this problem. Now I reinstall the version of draft-js to 0.10.5, it work.
But this is still a potential problem, I hope it can be fixed.

**Comment by cmoad** [comment]
The dependency to draft-js should be `"draft-js": "~0.10.5",` instead of `"draft-js": "^0.10.5",`. The new `0.11.0` release breaks this package.
