### ISSUE TITLE
Plugin stops working when setting to ref.current [mentions]

### ISSUE THREAD

**Issue by pscohn** [draft-js-plugins/draft-js-plugins#1298]
## Use-case/Problem

I'm using `ref = React.useRef(createMentionPlugin())` to hold a mention plugin in a functional component, and this works fine. 

But as soon as I try to set `ref.current = createMentionPlugin()`, the plugin stops working.

The reason I want to do this is that I'm custom rendering mentions based on some prop, so the mention component needs to be updated whenever some props change. My aim was to use `useEffect` and re-create the plugin whenever the prop changes.

I'm not entirely sure if this is an issue with draft-js-plugins or if I'm misunderstanding how refs work, but I don't see a reason why it shouldn't work.

Simple example: https://codesandbox.io/s/quirky-minsky-46bum

Just try typing `@foo`, then comment the line setting `ref.current`

**Comment by DavidM-Dev** [comment]
Also happens for emoji plugin, hashtag plugin and linkify plugin. I can figure out a workaround by creating a custom plugin for whenever I want to access the ref, but it's not ideal.
