### ISSUE TITLE
[draft-js-mentions-plugin] Cannot prevent mouse from focusing/selecting mentions in popover

### ISSUE THREAD

**Issue by jack-arms** [draft-js-plugins/draft-js-plugins#1299]
## Use-case/Problem

The `Entry` component provides its own `onMouseDown`, `onMouseEnter`, `onMouseUp` to manage focus of entries of the popover with the mouse, however there is no way to override this behavior (e.g. select an entry when `onClick` fires), only to ignore it by not using these props if you pass in your own `EntryComponent`.

The use case is I want a popover where the arrow keys can highlight entries of the popover but entries will not be highlighted when the mouse is over them. This is not as simple as changing the styling if the mouse is over an entry because I also have custom logic that scrolls an entry of the popover into view if it's selected, which makes sense if using the arrow keys to move up/down but if the mouse is also triggering selecting entries then it interferes with this behavior.

I think in https://github.com/draft-js-plugins/draft-js-plugins/blob/master/draft-js-mention-plugin/src/MentionSuggestions/Entry/index.js the `onMentionSelect` function should be provided to the `EntryComponent` so that custom logic for selecting a mention is possible.

**Comment by sibelius** [comment]
I'm gonna accept a PR to make this component customisable
