### ISSUE TITLE
Can't use useState hook for Editor onChange handler

### ISSUE THREAD

**Issue by ruoshui-git** [draft-js-plugins/draft-js-plugins#1309]
## Use-case/Problem

I'm getting this error:
Warning: State updates from the useState() and useReducer() Hooks don't support the second callback argument. To execute a side effect after rendering, declare it in the component body with useEffect().

I think the problem is, for the onChange handler, I'm using the setStateAction() function returned from useState(). However the plugins-editor passes a callback function to it, assuming that it's setState(). This isn't the case here. Preferably the editor can be updated to use hooks, but in case it can't, please use a workaround to passing callback. This way the editor can be used with the newest techniques in React.

The code that causes error:
```
function ChatInput() {
    const [editorState, setEditorState] = React.useState(
        EditorState.createEmpty()
    );
    const [hasFocus, setFocus] = React.useState(true);

    const handleKeyCommand = (command, editorState) => {
        const newState = RichUtils.handleKeyCommand(editorState, command);
        if (newState) {
            setEditorState(newState);
            return 'handled';
        }
        return 'not-handled';
    };

    const editor = React.useRef(null);

    const focusEditor = () => {
        editor.current.focus();
        setFocus(true);
    };

    React.useEffect(() => {
        focusEditor();
    }, []);

    return (
            <div className={`editor-container ${hasFocus?'editor_focused':''}`} onClick={focusEditor}>
                <Editor
                    ref={editor}
                    editorState={editorState}
                    onChange={setEditorState}
                    handleKeyCommand={handleKeyCommand}
                    onBlur={() => setFocus(false)}
                    onFocus={() => setFocus(true)}
                    plugins={plugins}
                    placeholder='say something...'
                />
            </div>
    );
}
```

The Editor here is the draft-js-plugins-editor.

**Comment by TrySound** [comment]
The second argument here is used to be consistent with all callbacks in plugins editor. Plugins instance can be useful to get additional information. If you want to avoid that warning try this
```
                <Editor
                    editorState={editorState}
                    onChange={newEditorState => setEditorState(newEditorState)}
                />
```
