### ISSUE TITLE
Emoji plugin interferes w/ @mention (show double menus)

### ISSUE THREAD

**Issue by rajaraodv** [draft-js-plugins/draft-js-plugins#132]
I tried to add bunch of plugins to a single editor and then I started seeing odd behaviors like multiple menus!
For example,  In my demo app, I have the following plugins:

`const mentionPlugin = createMentionPlugin({ mentions });
const linkifyPlugin = createLinkifyPlugin();
const stickerPlugin = createStickerPlugin({ stickers });
const StickerSelect = stickerPlugin.StickerSelect;
const emojiPlugin = createEmojiPlugin();

const plugins = [mentionPlugin, linkifyPlugin, stickerPlugin, emojiPlugin];`

But when I type **"@"**, I see the picture below: 

<img width="799" alt="screen shot 2016-03-26 at 12 36 32 am" src="https://cloud.githubusercontent.com/assets/626337/14058852/26f706a2-f2eb-11e5-81ff-18d95de74b40.png">

**Comment by nikgraf** [comment]
I looks like this is an issie with the emoji plugin as the mentions behave correct (at least in this screen)

**Comment by nikgraf** [comment]
I identified the issue & going to provide a fix later today …

**Comment by nikgraf** [comment]
@rajaraodv this should be fixed by this PR: https://github.com/draft-js-plugins/draft-js-plugins/pull/149

can you verify it and close the issue if it works?

**Comment by nikgraf** [comment]
@rajaraodv I hope you don't mind. I will close this as nobody reported this or a similar issue for a few days.
