### ISSUE TITLE
When I click on the first line, the onChange is triggered twice but with two different keys.

### ISSUE THREAD

**Issue by lvdang** [draft-js-plugins/draft-js-plugins#1327]
e.g.

When I click on the first line, the onChange is triggered twice, the first renders gives wrong key but the 2nd render display the correct key. Is this a bug? Below I have example using DraftJS without draft-js-plugin the key matches the cursor  focus.

```
  const onChange = editorState => {
    const focusKey = editorState.getSelection().getFocusKey();
    console.log('onChange called here focusKey', focusKey);
    const contentState = editorState.getCurrentContent();
    const key = editorState.getSelection().getStartKey();
    const keyBlock = contentState.getBlockForKey(key);

    setEditorChange(editorState);
  }
```

![Large GIF (640x335)](https://user-images.githubusercontent.com/7051557/63891277-abbd4d00-c999-11e9-8765-8a6cf0eda7e6.gif)

**Comment by TrySound** [comment]
Could you provide codesandbox please?

**Comment by lvdang** [comment]
@TrySound  - Sorry, I uploaded top git hub

https://github.com/lvdang/learningdraft

**Comment by lvdang** [comment]
Here is the draftjs version without draft-js-plugin. Notice the key comes back properly even though renders twice.

Access code here: https://codepen.io/lvdang/pen/PoYjzQv

![Large GIF (640x321)](https://user-images.githubusercontent.com/7051557/63895860-38213d00-c9a5-11e9-959b-68c16c76971b.gif)
