### ISSUE TITLE
Linkify completely crashes editor when typing certain links

### ISSUE THREAD

**Issue by bdbull** [draft-js-plugins/draft-js-plugins#1328]
## Typing certain links causes the editor to completely break

Using the Linkify plugin and attempting to type certain links causes the editor to completely break.  A link that will cause the issue is www.google.com.  Simply type that into the editor to see the issue.  The editor bombs out when you get to the "L" in typing the link.  Not all links cause this isssue.

I see this error in the console when the problem occurs
![image](https://user-images.githubusercontent.com/1843618/64029788-45f4d080-cb13-11e9-8dd2-95828d699653.png)

The issue can be reproduced in the following codesandbox. 
 Simply try to type www.google.com into the editor.
https://codesandbox.io/embed/blissful-dhawan-norre

**Comment by angithub13** [comment]
Hello. Have you fixed this issue? I'm having the same trouble here :)

**Comment by bdbull** [comment]
We did not fix it in our application.  We ended up just disabling the linkify plugin so we could move forward.

**Comment by cusxio** [comment]
Related to https://github.com/facebook/draft-js/issues/2143

**Comment by thaoms** [comment]
This is also blocking for us.

**Comment by bdbull** [comment]
It appears this issue is fixed by updating to draftjs 0.11.3.  We just did this for our app and are no longer having this problem.
