### ISSUE TITLE
cannot find draft-js-drag-n-drop-upload-plugin

### ISSUE THREAD

**Issue by arahansen** [draft-js-plugins/draft-js-plugins#1331]
I am trying to follow this example: https://www.draft-js-plugins.com/plugin/image

when trying to install `draft-js-drag-n-drop-upload-plugin` with `yarn add draft-js-drag-n-drop-upload-plugin` I'm getting the following error:

```
error No valid versions found for "draft-js-drag-n-drop-upload-plugin". The package may be unpublished.
```

Is this plugin hosted somewhere else?

**Comment by fnduister** [comment]
same here

**Comment by adamth** [comment]
I found it here `@mikeljames/draft-js-drag-n-drop-upload-plugin` but I'm not certain it is the same as the packed listed in the docs example.

**Comment by markymc** [comment]
I just found this missing when attempting to `npm i draft-js-drag-n-drop-upload-plugin` too. Any idea why it's not available?

**Comment by negati-ve** [comment]
This is not a feature that works currently

**Comment by lamnguyencse17** [comment]
I have come up with a small snippet of codes that could do the job (compatible with all image plugin)

Use Editor's handleDroppedFiles event to manually do the work. 

Plugins still have all the image plugin you want except the  `@mikeljames/draft-js-drag-n-drop-upload-plugin`

`
<Editor editorState onChange handleDroppedFiles={this.handleDrop} plugins={plugins} ref/>
`

I am currently using the `url` returned from uploaded image to display but you can display it raw with `base64`.

Except for the first line handling upload process. Others are just copied from orginal `imagePlugin` using to add image element

    handleDrop = async (selection, files) => {

    `const url = await yourFunctionToHandleUpload(files); 

    const urlType = "IMAGE";

    const contentState = this.state.editorState.getCurrentContent();

    const contentStateWithEntity = contentState.createEntity(
      urlType,
      "IMMUTABLE",
      { src: url }
    );

    const entityKey = contentStateWithEntity.getLastCreatedEntityKey();

    const newEditorState = AtomicBlockUtils.insertAtomicBlock(
      this.state.editorState,
      entityKey,
      " "
    );

    this.onChange(newEditorState);

    return "handled";

     };
