### ISSUE TITLE
Merge draft-wysiwyg features into draft-js-plugins

### ISSUE THREAD

**Issue by bkniffler** [draft-js-plugins/draft-js-plugins#134]
Hey all, 
I want to migrate https://github.com/bkniffler/draft-wysiwyg to https://github.com/draft-js-plugins/draft-js-plugins, so everyone can build their own rich-text/wysiwyg/medium editors more easily.

This issue serves to keep track of the process.
## Plugins
- [x] **draft-js-dnd-plugin** - Drag&Drop functionality (move blocks, drop new blocks, upload images)
  ![marz 31 2016 02 28](https://cloud.githubusercontent.com/assets/4349324/14179930/409739ae-f761-11e5-8db0-91431bcc4476.gif)
- [x] **draft-js-toolbar-plugin** - Medium-like text toolbar, easy toolbars with actions for blocks (WIP https://github.com/draft-js-plugins/draft-js-plugins/tree/toolbar-plugin)
  ![marz 31 2016 16 53](https://cloud.githubusercontent.com/assets/4349324/14179943/467ef0f0-f761-11e5-9571-c5101792d552.gif)
- [x] **draft-js-focus-plugin** - Manage active/selected block
- [x] **draft-js-resizeable-plugin** - Make a block resizeable by dragging its borders
- [x] **draft-js-alignment-plugin** - Allow to align a block to left/center/right, currently part of dnd-plugin, needs to find a different place to live in
- [x] **draft-js-table-plugin** - Add a nested editor to your block that plays nicely with the parent and inherits blockRendererFn and other props

**Comment by juliankrispel** [comment]
OMG OMG OMG @bkniffler this is so amazing!

**Comment by bkniffler** [comment]
I've started working on the toolbar, check the gif in the first post for a preview and a link to the branch.

**Comment by juliankrispel** [comment]
So badass

Julian Krispel-Samsel
rainforestqa.com
goodafternoon.co

**Comment by nikgraf** [comment]
hehe, email reply's in Github are funny :smiley:

**Comment by tommoor** [comment]
Excited for this, are you still planning on moving the toolbar functionality over?

**Comment by nikgraf** [comment]
@tommoor for sure, I was quite busy with the [Carte Blanche](https://github.com/carteb/carte-blanche) launch, but looking forward to spend more time in the next 2-3 weeks on this …

**Comment by bkniffler** [comment]
Hey everyone, please keep track of https://github.com/draft-js-plugins/draft-js-plugins/pull/243 for further progress on the PR. Everything works by now, you can see a working example of draft-js-plugins with the wysiwyg plugins at http://draft-wysiwyg.herokuapp.com/. I'm sure there are some bugs here and there, so feel free to try it out, report any suspicious behavior and/or submit a PR.

I think we can close this one for now, it is a bit outdated.

**Comment by oyeanuj** [comment]
@bkniffler This looks great, thanks so much! The only other thing to report is a bug, (which also might not have anything to do with your changes) but it seems that pasting behavior is weird on the wysiwyg editor. 
- Pasting a bolded/h1 block somewhere else loses that formatting. 
- Pasting an image file from the desktop just pastes the file name.

**Comment by yanivtal** [comment]
Where's the god emoji? You rock @bkniffler 🙌

**Comment by Xurma2** [comment]
What about counter?

**Comment by nikgraf** [comment]
@Xurma2 which counter?

closing the issue for now since this is already merged …
