### ISSUE TITLE
How to make plugins work with hooks? (State updates from the useState() and useReducer() Hooks don't support the second callback argument)

### ISSUE THREAD

**Issue by angithub13** [draft-js-plugins/draft-js-plugins#1341]
I created editorState and setEditorState hooks, then I passed them to Editor component that I had required from draft-js-plugins-editor:
editorState={editorState}
 onChange={setEditorState}

**And I get a warning in the console that says:** "_State updates from the useState() and useReducer() Hooks don't support the second callback argument. To execute a side effect after rendering, declare it in the component body with useEffect()._"

**I also get a warning:** "_componentWillReceiveProps has been renamed, and is not recommended for use. See https://fb.me/react-async-component-lifecycle-hooks for details.

* Move data fetching code or side effects to componentDidUpdate.
* If you're updating state whenever props change, refactor your code to use memoization techniques or move it to static getDerivedStateFromProps. Learn more at: https://fb.me/react-derived-state
* Rename componentWillReceiveProps to UNSAFE_componentWillReceiveProps to suppress this warning in non-strict mode. In React 17.x, only the UNSAFE_ name will work. To rename all deprecated lifecycles to their new names, you can run `npx react-codemod rename-unsafe-lifecycles` in your project source folder.

Please update the following components: PluginEditor_"

What should I do? If someone can help as soon as possible, I'll be very grateful - the work must be done soon, so I'm in, kind of, panic mode :)

**Comment by TrySound** [comment]
Was already asked before. Warning is pretty clear: don't pass the second argument to setState.
https://github.com/draft-js-plugins/draft-js-plugins/issues/1309#issuecomment-523768688

**Comment by angithub13** [comment]
> Was already asked before. Warning is pretty clear: don't pass the second argument to setState.
> [#1309 (comment)](https://github.com/draft-js-plugins/draft-js-plugins/issues/1309#issuecomment-523768688)

Thank you!
