### ISSUE TITLE
[Mention plugin] - Resolving decorators on componentWillReceiveProps

### ISSUE THREAD

**Issue by thaoms** [draft-js-plugins/draft-js-plugins#1343]
Since https://github.com/draft-js-plugins/draft-js-plugins/pull/960,
we resolve plugin decorators on mount (componentDidMount).

But our component receives often a new editorState, and loses its decorators.
Is it an option to also resolve it in componentWillReceiveProps? 

I would think you always want to resolve decorators again? Specially for plugins?

**Comment by thaoms** [comment]
I wrote a fix for it, but can't seem to commit due to some eslint errors. Can I send my change to someone?

**Comment by sibelius** [comment]
I think migrating to hooks and useEffect we can keep this in sync
