### ISSUE TITLE
Warning about improper hooks usage

### ISSUE THREAD

**Issue by stevensacks** [draft-js-plugins/draft-js-plugins#1344]
> Warning: State updates from the useState() and useReducer() Hooks don't support the second callback argument. To execute a side effect after rendering, declare it in the component body with useEffect().
>     in PluginEditor

Vanilla install. Not even using any plugins, yet.

**Comment by stevensacks** [comment]
It happens on every single change of the editor state.

**Comment by stevensacks** [comment]
Further, none of the plugins work.

I'm using the latest version of React. 16.9.0.

**Comment by TrySound** [comment]
@stevensacks This was already asked a few times. This is incorrect usage. Everything is quite clear in message.
https://github.com/draft-js-plugins/draft-js-plugins/issues/1309#issuecomment-523768688
