### ISSUE TITLE
Homepage - UX

### ISSUE THREAD

**Issue by juliankrispel** [draft-js-plugins/draft-js-plugins#135]
Right now I think the homepage isn't doing what it could e do for the project. I think it's useful to think about the job that the homepage is hired to do.

Imho the job is twofold
- It should show off the plugins
- It should enable the user to use plugins or make their own.

**Comment by juliankrispel** [comment]
I'd be happy to put together some basic wireframes for a start, how does that sound @nikgraf

**Comment by nikgraf** [comment]
ohhhhh yes please, I had some ideas we didn't execute on yet in this issue https://github.com/draft-js-plugins/draft-js-plugins/issues/63, but no hard feelings on any of them. It definitely needs better navigation. The whole plugins at the top thingy was a rushed hack :smiley:

**Comment by juliankrispel** [comment]
Homepage:
![image](https://cloud.githubusercontent.com/assets/1188186/14071765/dfbe296c-f4b8-11e5-8300-da6cccabc4cd.png)

Plugin Page:
![image](https://cloud.githubusercontent.com/assets/1188186/14071767/e5c6bee6-f4b8-11e5-92b9-0c386af6b82b.png)

**Comment by juliankrispel** [comment]
pretty simples

**Comment by juliankrispel** [comment]
The argument for a left-side-nav is that our plugins will grow in count!

**Comment by nikgraf** [comment]
makes sense @juliankrispel with the left sidebar

Some thoughts:

- make the sidebar expandable/collapsable & slack like (which is important for mobile)
- the sidebar is only by default expanded on screen sizes bigger than x
- since each plugin page already has multiple chapters we could expand those in the sidebar as well and make them clickable + their active state changes based on scroll as well

What do you think?

**Comment by juliankrispel** [comment]
@nikgraf all agreed to. Much like [gitbook/redux style docs](redux.js.org)

**Comment by bkniffler** [comment]
I like it, I agree everything said so far. I'd also suggest adding an `Examples` section that would show combinations of plugins (or all plugins at once), which could sometimes be more impressive than showing each plugin separately. I got the plugins I'm about to migrate in mind, as it makes sense to split them in different plugins, but demo them in a bundle (a wysiwyg editor), or to replicate popular editors (github comments / slack chat).

**Comment by juliankrispel** [comment]
@bkniffler even better, how about allowing the user to configure which plugins to use.

**Comment by juliankrispel** [comment]
Like a multi-select thingy

**Comment by juliankrispel** [comment]
or just checkboxes

**Comment by bkniffler** [comment]
That would definitely be a great addition, do you think it's something you can implement? Though I'm not 100% sure if its better than carefully handpicking whatever combinations we'd like to present and let the users combine/play around with them in their own projects (or on a sandbox project we provide).

The 'replicate popular editors'-thing I threw in would need more than just combining different plugins, we would need to add specific styling and markup for these kind of demos.

**Comment by juliankrispel** [comment]
@bkniffler I think it's pretty doable. But one thing after another. I'll do the smaller changes first :)

**Comment by juliankrispel** [comment]
Never got around to doing this :) I'll leave this open in case I have the time soon

**Comment by juliankrispel** [comment]
So I'm starting to redo the docs with gitbook.

![image](https://user-images.githubusercontent.com/1188186/30244646-37b5b998-95ba-11e7-9734-24c75b08cd9a.png)

The target:
- Improve the UX of reading the docs in general
- Improve the UX of updating docs (When I write docs I don't really want to think about using react components, let me write markdown all the way).

That's pretty much the most important stuff.

Code examples I'd move to [codesandbox](codesandbox.io). Which is nice because people can straight away play around with the code...

I'm continuing speccing this idea in a [paper doc](https://paper.dropbox.com/doc/Gitbook-docs-for-draft-js-plugins-HfT30NQ9MMP7XgrRCxRej), anyone with that link can see/comment on the doc :+1:

**Comment by juliankrispel** [comment]
I'm closing this issue since it's not really an issue (and continuing thought-process in the paper doc)
