### ISSUE TITLE
Hashtag plugin not adds any ranges to state

### ISSUE THREAD

**Issue by f4810** [draft-js-plugins/draft-js-plugins#1352]
Exporting the current state of draft plugin not contains information of any hashtag.
This is what I get:
`{
            "key": "4bp7p",
            "text": "#iamme",
            "type": "unstyled",
            "depth": 0,
            "inlineStyleRanges": [],
            "entityRanges": [],
            "data": {}
}`
So the state I save in db is inconsistent and differ from the actual data shown in the editor.

Instead,  it shouldn't be something like  that?
`{
            "key": "4bp7p",
            "text": "#iamme",
            "type": "unstyled",
            "depth": 0,
            "inlineStyleRanges": [
               {
                    "offset": 0,
                    "length": 6,
                    "style": "HASHTAG"
                }
             ],
            "entityRanges": [],
            "data": {}
}` 
Otherwise, there is a workaround to achieve this?

**Comment by vinceprofeta** [comment]
@f4810 Did you find a solution?

**Comment by f4810** [comment]
Not. The only solution I found is to use editor even to show the contents (a readonly instance of the editor...). But is not so satisfying...
