### ISSUE TITLE
Errors when running docs server locally

### ISSUE THREAD

**Issue by bradbumbalough** [draft-js-plugins/draft-js-plugins#1356]
Hello,

I'm trying to work on a plugin locally and am having issues running the docs server locally (per the contribution instructions).

I added the `babel-preset-react` and `babel-preset-env` presets in attempt to resolve the errors, but am still unable to get the server running. 

Here's one...
```js
Module build failed: SyntaxError: Unexpected token (17:8)

  15 | export default class App extends Component {
  16 |
> 17 |   state = {
     |         ^
  18 |     logoClassName: styles.hiddenLogo,
  19 |   };
  20 |
```

Before adding the react preset this was the error I was getting when running `npm start`:
```js
SyntaxError: /Users/brad/Code/Forks/draft-js-plugins/docs/server.js: Unexpected token (27:41)
  25 |  */
  26 | const renderDocumentToString = (props) =>
> 27 |   `<!doctype html>${renderToStaticMarkup(<Html {...props} />)}`;
     |                                          ^
  28 |
  29 | const app = express();
  30 | const compiler = webpack(config);
```
Running node@8.12.0, npm@6.4.1, yarn@1.19.1 on MacOS@10.14.6

This is the command I'm running to start the server:
```sh
npx babel-node ./server.js --presets=env,react
```

I also updated webpack.config.base.js to use this loader for the js tests:
```js
  use: [
        {
          loader: 'babel-loader',
          options: {
            presets: ['es2015', 'react'],
          },
        },
      ],
```

Any help would be appreciated! 🙇

**Comment by prncvrm** [comment]
did you have any success?

**Comment by reachtokish** [comment]
Any luck on this issue?
