### ISSUE TITLE
Hashtag plugin not mapping to entity map

### ISSUE THREAD

**Issue by t0sic** [draft-js-plugins/draft-js-plugins#1365]
Don't know if this is a bug or not but hashtag does not map to entity map meanwhile the mention plugin does. This is a issue for me as my parser doesn't understand that there is a entity type.

**Comment by gauravsoti1** [comment]
Are you sure that the entity doesn't get mapped? Or is that just the styles are not visible, hence you are not able to see the difference?

**Comment by vinceprofeta** [comment]
@gauravsoti1 I am able to reproduce this.

**Comment by webdeb** [comment]
also facing this, and like OP I would like to be able to have it as an entity so I don't need to parse it separately, see the output from `convertToRaw` 

draft-js-plugins/editor@4.0.0-beta3
draft-js-plugins/hashtag@4.0.0-beta2

```
{
  "blocks": [
    {
      "key": "e546j",
      "text": "No #tag entity",
      "type": "unstyled",
      "depth": 0,
      "inlineStyleRanges": [],
      "entityRanges": [],
      "data": {}
    }
  ],
  "entityMap": {}
}
```

**Comment by hanihusam** [comment]
> also facing this, and like OP I would like to be able to have it as an entity so I don't need to parse it separately, see the output from `convertToRaw`
> 
> draft-js-plugins/editor@4.0.0-beta3 draft-js-plugins/hashtag@4.0.0-beta2
> 
> ```
> {
>   "blocks": [
>     {
>       "key": "e546j",
>       "text": "No #tag entity",
>       "type": "unstyled",
>       "depth": 0,
>       "inlineStyleRanges": [],
>       "entityRanges": [],
>       "data": {}
>     }
>   ],
>   "entityMap": {}
> }
> ```

Do you already have the solution for this? I have the same issue. @webdeb
