### ISSUE TITLE
Add an explanation on why the Toolbar should be included after Editor (and not before)

### ISSUE THREAD

**Issue by julesbou** [draft-js-plugins/draft-js-plugins#1369]
In [the readme](https://github.com/draft-js-plugins/draft-js-plugins/tree/master/draft-js-buttons), it's written:

> Important: Include after the Editor
For the toolbar to work correctly, you must include the <Toolbar> component after the editor component:

Indeed, if I include the Toolbar before, there's a delay appearing when pressing button, so the button doesn't become active immediately, which is a bit annoying.

Is there a specific reason why Toolbar had to be included after? Does this problem has a possible fix?

**Comment by julesbou** [comment]
I found a quickfix to allow having the toolbar before the editor.


I add a ref on the toolbar container:

```
          <this.staticToolbarPlugin.Toolbar>
            {(externalProps) => (
              <div ref={toolbar => this.toolbarRef = toolbar}>
                <BoldButton {...externalProps} />
                <ItalicButton {...externalProps} />
              </div>
            )}
          </this.staticToolbarPlugin.Toolbar>
```

Then I force re-rendering the editor when clicking a button:

```

  componentDidMount() {
    this.toolbarRef.addEventListener('click', () => {
      setTimeout(() => {
        this.setState({
          editorState: EditorState.forceSelection(
            this.state.editorState,
            this.state.editorState.getSelection()
          )
        })
      }, 0)
    })
  }
```

**Comment by devned** [comment]
I encountered this issue as well.

This worked for me:
```
<div style={{ display: "flex", flexDirection: "column-reverse" }}>
    <Editor />
    <Toolbar />
</div>
```
