### ISSUE TITLE
How can we create a new link plugin for static toolbar?

### ISSUE THREAD

**Issue by pmehta18** [draft-js-plugins/draft-js-plugins#1373]
I am using static-toolbar plugin. How can I use anchor plugin for static toolbar? Also I need to add behavior to modify the url for existing link?

**Comment by pmehta18** [comment]
@philohelp I created a plugin in my codebase similar to the structure given in the library, added custom UI which I wanted for modifying already created links or for creating new links. It works fine for me!

**Comment by philohelp** [comment]
Thanks, I did that too.
