### ISSUE TITLE
Mention and Emoji Plugins Issue

### ISSUE THREAD

**Issue by scottshuffler** [draft-js-plugins/draft-js-plugins#1376]
## Mention and Emoji plugins do not function correctly with multiple editors

- Emoji and mentions plugin only work for the last component created  
- Link to [codesandbox](https://codesandbox.io/s/prod-sea-by6vf?fontsize=14&hidenavigation=1&theme=dark)

![](https://im6.ezgif.com/tmp/ezgif-6-7c67502ad761.gif)

**Comment by scottshuffler** [comment]
Found a solution in #298 but I'm not sure if the solution from tedlin182 is what I should be using

**Comment by zcapin** [comment]
Yeah you should reinitialize plugins for every editor, just as you did in the constructor, i also have this issue, not sure about functional component: https://github.com/draft-js-plugins/draft-js-plugins/issues/298

**Comment by scottshuffler** [comment]
@zcapin Nice, I would like to move to hooks soon

I wonder if the docs should show plugin creation like we described

Could lead to less confusion around multiple editors

**Comment by zcapin** [comment]
I think PR was created to put examples showing this, you can see it in the issue https://github.com/draft-js-plugins/draft-js-plugins/issues/298

**Comment by scottshuffler** [comment]
@zcapin You're right. I'm just now realizing I built everything off the toolbar example so I backed myself into an issue that's no longer an issue.
