### ISSUE TITLE
Resolve `customStyleFn` from Multiple Plugins?

### ISSUE THREAD

**Issue by joncursi** [draft-js-plugins/draft-js-plugins#1383]
I have 2 plugins that use `customStyleFn` to set display styles. It would be great if this library supported merging of `customStyleFn` from multiple plugins into a single `customStyleFn`, similar to how `customStyleMap` is resolved and merged.

**Comment by rmakovyak** [comment]
I have exact same issue. Did you manage to resolve it @joncursi ?

**Comment by joncursi** [comment]
> I have exact same issue. Did you manage to resolve it @joncursi ?

Unfortunately I did not. I ended up breaking the pattern and merging what should have been 2 distinct plugins into 1, such that I was only loading a single `customStyleFn` into the Editor. :/

**Comment by Pumpkin-SweetPotato** [comment]
I think actually [draft-js-custom-styles](https://github.com/webdeveloperpr/draft-js-custom-styles/blob/master/src/index.js#L179) use multiple custom style functions

when you want to use font size style and color style then you can use like this 
`const { customStyleFn } = createStyles(['font-size', 'color'], 'CUSTOM_')`
