### ISSUE TITLE
Divider only shows while inside the editor but after publishing it's just a simple white space

### ISSUE THREAD

**Issue by Tsabary** [draft-js-plugins/draft-js-plugins#1386]
I am using it just like in the code provided, and while in the editor it shows just fine, but after posting it is only a <br/> inside a paragraph.
How do I actually have the divider itself appear in the final html like it appears in the Editor?

I can't seem to find any exmple anywhere

**Comment by freedomlang** [comment]
@Tsabary Do you mean convert content to plain HTML?

**Comment by Tsabary** [comment]
Mmm yes I think that explains what I'm taking about. It just doesn't make any difference in the text as far as I can see after posting, as opposed to how it looks like in editing mode

**Comment by freedomlang** [comment]
@Tsabary Did you already import the css for divider?
