### ISSUE TITLE
Different repositories for plugins?

### ISSUE THREAD

**Issue by juliankrispel** [draft-js-plugins/draft-js-plugins#139]
Would kinda make sense right?

**Comment by juliankrispel** [comment]
Because it would make sense to scope issues/tests/release per plugin

**Comment by mxstbr** [comment]
:+1:

**Comment by nikgraf** [comment]
yep, definitely on the roadmap, but I don't feel ready yet to do it. Simply because there is more urgent stuff & still structural changes which are more work with more repos … maybe in 2-3 weeks? makes sense?

**Comment by juliankrispel** [comment]
kk

**Comment by juliankrispel** [comment]
@nikgraf would be nice to prioritise what work we have, it's hard to do that with gh issues

**Comment by okonet** [comment]
I think this might be useful https://github.com/FormidableLabs/builder

**Comment by juliankrispel** [comment]
@okonet ooooh I wasn't aware awesome thanks <3

**Comment by nikgraf** [comment]
I will close this for now.
