### ISSUE TITLE
Struggling to use draft-js-plugins in functional React components ==> _this.props.getEditorState is not a function

### ISSUE THREAD

**Issue by brygge** [draft-js-plugins/draft-js-plugins#1391]
The problem occurs when I try to connect a plugin like the toolbar to the editor. 
Any suggestions?

Example: 
import createToolbarPlugin from 'draft-js-static-toolbar-plugin'

const news = () => {
  const [content, setContent] = useState(EditorState.createEmpty());
  const deToolbarPlugin = createToolbarPlugin();
  const { Toolbar } = deToolbarPlugin;
  const plugins = [deToolbarPlugin];
  return (
    <div className={editorStyles.editor}>
            <Editor editorState={content} 
                         onChange={setContent} 
                         plugins={plugins} 
            />  
            <Toolbar /> 
    </div>
  )

}
export default news;

**Comment by forlayo** [comment]
I am having same issue; any workaround ?
