### ISSUE TITLE
Editor mount causing react warning "Warning: Cannot update a component from inside the function body of a different component."

### ISSUE THREAD

**Issue by sspread** [draft-js-plugins/draft-js-plugins#1393]
Likely due to more recent version of react throwing the warning. As discussed here, (https://github.com/facebook/react/issues/18178) the warning is new and will eventually be a hard exception. I believe the problem comes from this line https://github.com/draft-js-plugins/draft-js-plugins/blob/master/draft-js-plugins-editor/src/Editor/index.js#L74 when `onChange` callback results in a `setState` call, resulting in attempt to render the Editor component within its own onMount hook. I suspect this line didn't work as intended and now the warning brings it to light.

**Comment by abheist** [comment]
Same issue;

**Comment by lciii** [comment]
I've updated to React 16.13.1 as suggested in [this thread](https://github.com/facebook/react/issues/18178) and I'm still getting the same warning.

**Comment by sspread** [comment]
@lciii Yes its not a react issue. It just surfaced more recently since react started warning about the issue that already existed. I've outlined the specific problem in my original post.

**Comment by abheist** [comment]
Instead of passing `setState` and updating the component's state from the parent, I'm updating the state from the same component, and it solved the problem for me.

But you might be calling `setState` on every react rendering, try to put `console.log` below `setState` and check how many times it's updating on any change. 

You can put the `setState` under any condition or under `useEffect`, this might solve your issue.
It's not from the Draft but is a restriction from `react`.

This might help:
https://reactjs.org/blog/2020/02/26/react-v16.13.0.html#warnings-for-some-updates-during-render

**Comment by sspread** [comment]
@abheist Putting `setState` in `useEffect` will solve it, the same way using `setState` in a `setTimeout` will solve it. But the issue is still in this plugin, as following the simple implementation example on this github home page will cause the warning.

**Comment by abheist** [comment]
@sspread Yeah, totally, I was facing many issues while using this plugin library, so kinda move to the pure draft.js. Still, this need a major upgrade I think.

**Comment by gnoesiboe** [comment]
The problem I think is that `componentWillMount` is considered part of the rendering process. However if [the same line](https://github.com/draft-js-plugins/draft-js-plugins/blob/master/draft-js-plugins-editor/src/Editor/index.js#L74) is to be moved to the `componentDidMount`, it appears not to be. I've been playing around with this locally and no longer got a warning on mount. Is this something that might be considered a solution? If it is, let me know and I will file a PR.

**Comment by sspread** [comment]
@gnoesiboe Yes that is the problem. I think your solution would fix the issue. I also think you could make a case for removing that line altogether and leaving it up to developer to call it if/when they want. That could potentially be a breaking change however.

**Comment by gnoesiboe** [comment]
I expect this issue to be fixed with https://github.com/draft-js-plugins/draft-js-plugins/pull/1445

**Comment by dathacky** [comment]
Still error :((
