### ISSUE TITLE
Mention can only get triggered once each line

### ISSUE THREAD

**Issue by fridaystreet** [draft-js-plugins/draft-js-plugins#1406]
this was an issue that was raised in #895 which has been closed as fixed.

I'm still seeing the issue, unable to add a second mention on the same line. It's also apparent in the current live demo for the custom mention example. The simple mention seems to work, but the custom one doesn't. 

I've tried going back to a simple mention in my code, but even in the simple mode I still have to go to a new line before the suggestion box will appear again.

I'm still trying to debug this issue inside the plugin code, I thought at first maybe it was a regex issue because it won't fire if there is any text in front of the @. It has to be at the start of the line. But further debugging revealed it is matching the mention trigger after text (or a second mention trigger) in the regex, but something is failing after that.

I'll keep trying to debug it, but any insight would be greatly appreciated. How was it fixed before in #895 

I'm running the current master branch

Cheers

**Comment by fridaystreet** [comment]
Bit further testing and I've narrowed it down to the use of supportWhitespace: true.

turning this on breaks it and no longer allows multiple suggestions on same line. This kinda brings me back to thinking that it is actually a regex issue. Will try and debug the whitespace regex a bit

**Comment by fridaystreet** [comment]
fixed with change to the regex for supportWhiteSpace

line 42 of mentionSuggestionsStrategy.js change the reg expression from 

`? new RegExp(`(\\s|^)${escapeRegExp(trigger)}(${regExp}|\\s){0,}`, 'g')`

to include the check for space at front as per below:

` ? new RegExp(`(\\s|^)${escapeRegExp(trigger)}(${regExp}|\\s){0,}`, 'g')`

**Comment by dav-sap** [comment]
i'm guessing this code was not merged to the master here. how did u change it in your code base?

**Comment by fridaystreet** [comment]
@dav-sap I just changed the regex on line 42 of mentionSugestionsStrategy.js as I mentioned above. We're actually using this as a base and have forked our own version because we wanted to change the popup and a few other things which needed us to move away from the original code a fair bit in terms of how it's rendered. 

When I get some time I'll see if I can do a PR for this fix in this original codebase
