### ISSUE TITLE
componentWillReceiveProps has been renamed, and is not recommended for use

### ISSUE THREAD

**Issue by anatolzak** [draft-js-plugins/draft-js-plugins#1413]
## Use-case/Problem
Problem

When using the Plugin Editor, I get this error from React:

Warning: componentWillReceiveProps has been renamed, and is not recommended for use. See https://fb.me/react-unsafe-component-lifecycles for details.

* Move data fetching code or side effects to componentDidUpdate.
* If you're updating state whenever props change, refactor your code to use memoization techniques or move it to static getDerivedStateFromProps. Learn more at: https://fb.me/react-derived-state
* Rename componentWillReceiveProps to UNSAFE_componentWillReceiveProps to suppress this warning in non-strict mode. In React 17.x, only the UNSAFE_ name will work. To rename all deprecated lifecycles to their new names, you can run `npx react-codemod rename-unsafe-lifecycles` in your project source folder.

Please update the following components: PluginEditor

**Comment by sibelius** [comment]
anybody working on a fix for this?

**Comment by badazzdev** [comment]
Same issue here. Is there a fix?

**Comment by sibelius** [comment]
The fix is to use hooks

**Comment by badazzdev** [comment]
> The fix is to use hooks

Yeah i see, this is strange because i use hooks.

**Comment by sibelius** [comment]
the problem is that the draft-js plugin code does not use hooks yet
