### ISSUE TITLE
Types for draft-js-inline-toolbar-plugin and draft-js-buttons not compatible

### ISSUE THREAD

**Issue by katz12** [draft-js-plugins/draft-js-plugins#1423]
## Use-case/Problem

I wasn't able to get codesandbox to show me the error, but I reproduced this in the typescript playground: https://www.typescriptlang.org/play/?jsx=2#code/JYWwDg9gTgLgBAJQKYEMDGMA0cDecDCE4EAdkiTACoCeYScAvnAGZRFwDkUqGHAUHwD0AKmF84wuDToBnOGghhgSACYs2IOCqgpmMALQArGfuAkANmaT6YECOYBGKKOMkBlIvRi0kckBBVgZmU1WzhufwA3elBIWBlXQT4kAA84+DMYJChmdHoASQsrSjtHZwAFcwBXAHMzSgALJBB6HHE4ByqYWxI3b3NfAH4ALlx2uA6unoB1HTA6KBG4GRgoMxqAbnHJ7tIllbWSTe30GGBo-dX1rYmGG7hbeycoPuoBmSW2iYnHssXRg7Xdp3doyJBgZwoWwvfpDUZfb5giE6aGXQ7HW5bBgCVLpOCZbK5NAFIpkEpPCrVOokQgkYI1MY-JotUaFSxk0rPSq1erMpBYgSCQTLGBVBxwCBdOAAUUC0L6UKQfG8dBlcugCqycAAvHAUCRqDi0tAMhRCXkpJznPgGsBzNpyOU2GA5AiYHzWaSkOS-tzqY1mkgANoAIk6u16sJkIYAuvcakgYLLgPKYIrRgAKACUOoAfGqUxq01l7mCk+qYem4BnVIXK1lRsnU4qc9r85EIMAVPdSAB5aJQNYqJC0rIUTMKM3jghESBkCjSJAAHh9zxtdodJCdihkudb7c73b42OSxtg+LNOQtq4qztd7TQtvt3BINZSWSgJBQ5m3LtGN6gddn0dO8s1GfVqAFU88RVEl2W9UoACFKR5EgdUZOA2WKK0oFGQhiHnKgfBXHDf13LEtj4Yc0HMZx6EnFZ5G4RUsI5CkoD9MxMwfUh6SWViEPYziaV44Aaj4fdMK9H1kI4qkzEo3ETS0JBciqcx4DQZisgEgDhMokQxAkKQfDkBQlFUdR2G0XQDGMfRwx6BJjI8FoHlMuB-ECYJLLCCIIGifFiHiRJoOUgkr2JOAABEdD0AApGREKmUgAzchEhQINw3HkWiZDBOQwhQeZzENCZTnOJAASuI57kc0hqvROqUpIWZioWRqgRPJTzwiol6Fi2zEuSiMyIw91AyWQaEqSlq0v5Y8jTxPqLWmmBhvMCA0AAawAQUsGoSBaCgRp6MbUjHFQ5DW4aWrGhFvzEo7yBgTraoECYy32p7jpgDNHsO363pqMC4A7LsoNgmK4vWpLNp277AZe07Up8dD8LnF7FyXdobrhra9oO56Truu8+FzRSz1ND9+uhoaZFeAYUa3O84Au8grrpmbmfu0FEybItFRrCtNSqvUDVB8Gj3aBNyzrUXs3Ag1IbRvHGaQZnF3R2dSCx4i1dhHm7wpwVRFcRBwTYeQAiVCQkj4Faor0+TWrmBYMLMeDndQ0ZkFFT9sdgiBmCY1AdOk0iXdzUFViqDAqm4f9SLvIMOEfDcXw4GNFr4Bj4EQ+wVGZ0YDbeDW5rR3UMzAUC8zgJdAkiQRo9z0hGK0sOkGEtr5mydDFctISXZ79222rBEJk97Ch590OWIjmfqWzTBtgOOP-bFmudzrjNtm+evG+j-fj++JcC-tZncAAOhvreXSYZu99PwRD+2LNjyzIA

The issue seems to be that in `draft-js-buttons` we define `DraftJsButtonTheme` as:
```
export interface DraftJsButtonTheme {
  // CSS classes to apply
  active: string;
  button: string;
  buttonWrapper: string;
}
```

but in `draft-js-inline-toolbar` the theme is defined as:
```
export interface InlineToolbarPluginTheme {
  buttonStyles?: {
    buttonWrapper?: string;
    button?: string;
    active?: string;
  };
  toolbarStyles?: {
    toolbar?: string;
  };
  separatorStyles?: {
    separator?: string;
  };
}
```

I'm not sure whether optional or non-optional properties is the correct way to go on this, but I am happy to dig in and make the change.

**Comment by sibelius** [comment]
fixed here https://github.com/draft-js-plugins/draft-js-plugins/pull/1425
