### ISSUE TITLE
Custom Draftjs

### ISSUE THREAD

**Issue by farmer911** [draft-js-plugins/draft-js-plugins#1427]
hi i'm new guy in react Js and i see draft-Js it's really cool, but i have a question.

1. when press # hashtag list is appear, and how can i color the text it not including dropdown list it's look like twitter.

Sorry for my poor english. i have asked so many forum but have no answer

**Comment by sibelius** [comment]
use hashtag plugin https://www.draft-js-plugins.com/plugin/hashtag
