### ISSUE TITLE
Styling Suggestions in Mention plugin

### ISSUE THREAD

**Issue by Seoudi** [draft-js-plugins/draft-js-plugins#1430]
Hey I created an editor with the mention plugin and it's working perfectly the only problem is with the styling I followed the tutorials but as attached the image and text are not aligned 
![image](https://user-images.githubusercontent.com/17534974/85240482-a6555580-b438-11ea-8ebd-ff01200085c5.png)
I took the code in [sandbox](https://codesandbox.io/s/test-mention-plugin-mtsyv?file=/src/ChatInput.jsx) and it works fine so it seems like the code is overwritten by some styling and I can't know which css class because the suggestion list disappears if I lost focus and tried to inspect 
this element disappear 
![image](https://user-images.githubusercontent.com/17534974/85240609-05b36580-b439-11ea-8bcb-8a8c98fe4286.png)
any suggestions ?

**Comment by worc** [comment]
there doesn't seem to be a way to keep the popover open, this issue was opened last year and there hasn't been any updates: https://github.com/draft-js-plugins/draft-js-plugins/issues/1250
