### ISSUE TITLE
Persisting mentions to DB and reloading not working

### ISSUE THREAD

**Issue by vdevired** [draft-js-plugins/draft-js-plugins#1437]
So I am using the DraftJS package with React along with the mentions plugin. When a post is created, I store the raw JS in my PostreSQL JSONField:

`convertToRaw(postEditorState.getCurrentContent())
`

When I edit the post, I set the editor state as follows:

```
let newEditorState = EditorState.createWithContent(convertFromRaw(post.richtext_content));
setEditorState(newEditorState);
```

The text gets set correctly, but none of the mentions are highlighted AND I can't add new mentions. Does anyone know how to fix this?

I am using the mention plugin: https://www.draft-js-plugins.com/plugin/mention

**Comment by stevan-borus** [comment]
Is there a solution to this?

**Comment by fxOne** [comment]
You should not override the editor state as it will remove the decorators. You can read more about that in the FAQ: https://github.com/draft-js-plugins/draft-js-plugins/blob/master/FAQ.md#draft-js-plugin-decorators-are-removed-after-creating-a-new-editorstate

**Comment by stevan-borus** [comment]
If I comment out the last line then the mention won't show, if I don't mention is going to show but when I type @ in the editor nothing is going to happen

```
const stateWithEntity = contentState.createEntity('mention', 'IMMUTABLE', {
        mention: {
          avatar: '',
          name: member.username,
        },
      });

      const entityKey = stateWithEntity.getLastCreatedEntityKey();
      const newContentStateWithAddedColon = Modifier.insertText(
        stateWithEntity,
        selectionState,
        mentionText,
        undefined,
        entityKey,
      );

const newEditorState = EditorState.moveFocusToEnd(
        EditorState.push(editorState, newContentStateWithAddedColon, 'insert-characters'),
);

setEditorState(newEditorState);
```
