### ISSUE TITLE
support other handlers

### ISSUE THREAD

**Issue by ianstormtaylor** [draft-js-plugins/draft-js-plugins#144]
Looks like the unsupported ones are:

- [ ] [`handleBeforeInput`](https://facebook.github.io/draft-js/docs/api-reference-editor.html#handlebeforeinput)
- [ ] [`handlePastedText`](https://facebook.github.io/draft-js/docs/api-reference-editor.html#handlepastedtext)
- [ ] [`handlePastedFiles`](https://facebook.github.io/draft-js/docs/api-reference-editor.html#handlepastedfiles)
- [ ] [`handleDroppedFiles`](https://facebook.github.io/draft-js/docs/api-reference-editor.html#handledroppedfiles)
- [ ] [`handleDrop`](https://facebook.github.io/draft-js/docs/api-reference-editor.html#handledrop)

**Comment by nikgraf** [comment]
Happy to add them :+1: …

I know @bkniffler added some of them while working on Drag & Drop plugin here: https://github.com/draft-js-plugins/draft-js-plugins/issues/134

@ianstormtaylor @bkniffler any of you up for a PR? I'm going to be busy until Wednesday tracking down bugs.

**Comment by juliankrispel** [comment]
@nikgraf @ianstormtaylor there's a ton of `onSomething` and `handleSomething` handlers that aren't supported yet and it'd probably be more efficient to dynamically mount them on the draftjs editor rather than doing this explicitly, I'll make a pr

**Comment by juliankrispel** [comment]
This will also save us work when updates occur

**Comment by nikgraf** [comment]
sound like a good idea, keep in mind onSomething has to be handled differently then handleSomething …

**Comment by juliankrispel** [comment]
thx @nikgraf

**Comment by ianstormtaylor** [comment]
For what it's worth, since we're talking about structural changes, I wrote up a quick example of a potential structure that I think makes the code a bit more manageable, and cleans up a few things:

https://gist.github.com/ianstormtaylor/f28bdb94b0bf6593e45c

Some of it is probably broken, since it was a quick writeup, but I think some of it would be useful. Specifically it covers a few things:

- The [`handlers`](https://gist.github.com/ianstormtaylor/f28bdb94b0bf6593e45c#file-editor-js-L30-L44) can be automatically generated from a list. And I _think_ that the `handle*`, the `on*` and the `*Fn` handlers can actually all use the same [handling code](https://gist.github.com/ianstormtaylor/f28bdb94b0bf6593e45c#file-editor-js-L153-L164). Right now we're missing a few of these, hence this issue.
- By using [`for of`](https://gist.github.com/ianstormtaylor/f28bdb94b0bf6593e45c#file-editor-js-L161) we get early returns, which was marked as a `TODO` in the current source.
- The [handler `props`](https://gist.github.com/ianstormtaylor/f28bdb94b0bf6593e45c#file-editor-js-L123-L130) can be automatically generated from the same list.
- The [`proxies`](https://gist.github.com/ianstormtaylor/f28bdb94b0bf6593e45c#file-editor-js-L10-L24) can be generated in the same way, so that it's easy to stay up to date. Right now it looks like just `focus()` is supported, so this would increase support.
- By resolving [`plugins`](https://gist.github.com/ianstormtaylor/f28bdb94b0bf6593e45c#file-editor-js-L83-L87) in a stateless manner, we can actually easily treat the defaults [as plugins themselves](https://gist.github.com/ianstormtaylor/f28bdb94b0bf6593e45c#file-default-key-binding-plugin-js-L1-L13) which is nice for the system's simplicity. We could add another plugin in the same way for the [`cmd-left/right`](https://github.com/draft-js-plugins/draft-js-plugins/issues/146) bindings. And this makes them easy to disable for the developer if they want to.
- Using [`propTypes`](https://gist.github.com/ianstormtaylor/f28bdb94b0bf6593e45c#file-editor-js-L52-L57) we can get rid of a defensive checks.
- By [mixing in `...props` last](https://gist.github.com/ianstormtaylor/f28bdb94b0bf6593e45c#file-editor-js-L103-L105), I think that gives the developer the ability to override any of the automatically generated handler properties, which was marked as a `TODO` in the current source for some. (I think overriding completely is best to not create confusion.)

I didn't mockup some of the current functionality (and some could be moved in to plugins instead), but hopefully the idea is still clear. Let me know if you guys have any questions!

**Comment by nikgraf** [comment]
This suggestions/discussions make me happy :heart_eyes: 

- I believe plugins in a stateless manner make a lot of sense if you build for yourself. I expect most people to change at least the theming option of some of the plugins in real world applications. Coming from Redux I got multiple times confused that some middlewares need to instantiated, while others can be used in this stateless manner. The goal here was to create consistent experience. Does this make sense?

- :+1: on propTypes. I would love to see Flowtypes + [babel-plugin-flow-react-proptypes](https://github.com/brigand/babel-plugin-flow-react-proptypes), but therefore it would be really handy if the DraftJS flowtypes would be exported. Maybe we can pull this off with a PR next weekend … propTypes sound good until then.

- mixin props last: by having them as last it would completely overwrite the plugins behaviour. I imagined people use 2 plugins + have a custom handleKeyCommand function attached their editor. This [implementation](https://github.com/draft-js-plugins/draft-js-plugins/blob/master/draft-js-plugins-editor/src/Editor/index.js#L115) allows to have both while the attached handleKeyCommand has priority over the plugins. My thinking here was: Make sure the Plugins Editor still behaves exactly the same as the default Editor (+ it takes plugins). With mixin props last we would force people to write plugins. hmm maybe not a bad thing after all …

- I totally agree with all the other points.

**Comment by ianstormtaylor** [comment]
Good points.

- By "stateless" there I meant in the React sense actually. Since it keeps plugins on `props` and mixes in the defaults whenever it needs to, it doesn't need to store them in a stateful way on `this.plugins`.
- For mixin props, I agree with your final point, that it's better for people to write their own plugins to add functionality. If they really want to override the functionality, I think that's what the editor-level prop should be for, as an all-or-nothing option to handle the logic however they want.
