### ISSUE TITLE
UI/UX problem in Mention-documentation

### ISSUE THREAD

**Issue by RAYDENFilipp** [draft-js-plugins/draft-js-plugins#1443]
## Use-case/Problem
 The problem with the documentation is as in the screenshot:

![image](https://user-images.githubusercontent.com/24476415/87545836-48233780-c6b1-11ea-81df-1142ae54e16c.png)

**Comment by sibelius** [comment]
fixed here https://github.com/draft-js-plugins/draft-js-plugins/pull/1444
