### ISSUE TITLE
TypeError: Cannot read property 'offsetTop' of undefined

### ISSUE THREAD

**Issue by julianfrancodev** [draft-js-plugins/draft-js-plugins#1456]
### Hi all, i have the next bug,  Using next js
![nextjs](https://user-images.githubusercontent.com/27922676/90576233-3129a680-e183-11ea-97d2-ff1af4cfff19.png)
  
## and here is my code

`import React from 'react';
import Layout from '../components/Layout'
import { EditorState } from "draft-js";
import createInlineToolbarPlugin from "draft-js-inline-toolbar-plugin";
import createSideToolbarPlugin from "draft-js-side-toolbar-plugin";

import Editor from "draft-js-plugins-editor";

const inlineToolbarPlugin = createInlineToolbarPlugin();
const { InlineToolbar } = inlineToolbarPlugin;
const sideToolbarPlugin = createSideToolbarPlugin();
const { SideToolbar } = sideToolbarPlugin;
const plugins = [inlineToolbarPlugin, sideToolbarPlugin]

export default function CreatePost() {
    const editor = React.useRef(null);

    const [editorState, setEditorState] = React.useState(
        EditorState.createEmpty()
    );

    return (
        <>
            <Layout>
                    <Editor
                        editorState={editorState}
                        onChange={editorState => setEditorState(editorState)}
                        plugins={plugins}
                        ref={editor}
                    />
                    <InlineToolbar />
                    <SideToolbar />
            </Layout>
        </>
    )
}`

## Thanks for ur help.

**Comment by KunleMichaels** [comment]
I have this issue too. as soon as i resize my browser

**Comment by odyseeus** [comment]
I have the issue as well. 

Maybe it has something to do with SSR.... Next.js is known to have problems with reading window properties as it can only access the window object on the client and not on the server 

https://medium.com/frontend-digest/why-is-window-not-defined-in-nextjs-44daf7b4604e
