### ISSUE TITLE
The Mentions plugin stop working when user switch between items

### ISSUE THREAD

**Issue by FilipMessa** [draft-js-plugins/draft-js-plugins#1457]
## Use-case/Problem

I am tried to use mention plugin for multiple Items and would like to keep
the state of the editor of every Item when a user is a switch between them. Because of that, every item has its own editor state.

However, I stuck with the issue when the plugin has been stopped working when the user is switching bettwen items.

It works only for the first time when the user writes `@` and then when switching to another item and go back, the dropdown stops open.

link to a simple example: 
https://codesandbox.io/s/smoosh-architecture-2g006?file=/src/Item.js

Step to reproduce:

1. Click on Item 1
2. write "@" into the editor
3. switch to another item
4. switch back to Item 1
5. Mention plugin stop working for Item 1

Thanks all of you for any Idea or whatever.

https://giphy.com/gifs/ihknyIR3gVCp0JzD9f

**Comment by FilipMessa** [comment]
I was able to solve this issue with this workaround https://github.com/draft-js-plugins/draft-js-plugins/issues/1242

**Comment by brutalimp** [comment]
> I was able to solve this issue with this workaround #1242

@FilipMessa i can't solve this using this workaround,  have work on this issue for like threes days, please help update you code sample if you solve this.
