### ISSUE TITLE
what are the cmd-left and cmd-right bindings for?

### ISSUE THREAD

**Issue by ianstormtaylor** [draft-js-plugins/draft-js-plugins#146]
Was looking through the code and noticed that the `keyBindingFn` [automatically binds to `cmd-left` and `cmd-right`](https://github.com/draft-js-plugins/draft-js-plugins/blob/master/draft-js-plugins-editor/src/Editor/index.js#L181-L187) to implement moving to the start/end of a block. Why's that in there? Wouldn't that be handled by the OS automatically?

**Comment by nikgraf** [comment]
The issue I encountered was that once you have a tag a block that has `contenteditable={ false}` the default OS behaviour doesn't work anymore.

These two solutions came to my mind:
- avoid having inline-blocks at all (move the mentions, emoji search outside the editor)
- fix the behaviour manually

I picked the second one, but I'm open to better ideas :smile:

**Comment by nikgraf** [comment]
I already removed them in the latest version. Let's avoid `contenteditable="false"`. I will refactor the mentions & emoji plugin soon.
