### ISSUE TITLE
Don't mount pluginProps on Editor

### ISSUE THREAD

**Issue by juliankrispel** [draft-js-plugins/draft-js-plugins#147]
We are currently mounting the {pluginProps} [directly on the editor](https://github.com/draft-js-plugins/draft-js-plugins/blob/master/draft-js-plugins-editor/src/Editor/index.js#L235).

I think this is pretty misleading because since you can have multiple plugins, the last plugin will win (even if we merge the props objects, we'll have naming collisions).

The only use-case for mounting pluginProps on the editor that I can think of right now are aria tags (for example the mention plugin and the emoji plugin). I think it makes sense if we leave it up to users to mount those explicitly, we could even expose a default set of recommended editor props. Something like.

```js
import plugin, {ariaProps} from 'draft-js-plugin';

const plugins = [plugin()];

... <Editor plugins={plugins} {...ariaProps} />
```

any thoughts?

**Comment by nikgraf** [comment]
hmmm, these are so specific use-cases. We could avoid merging all props and do some special stuff for aria. That might make more sense …

**Comment by juliankrispel** [comment]
@nikgraf here's what I think we should do:

1 - If the prop is a function (mostly callbacks) we compose it (like we already do).
2 - If the prop is not a function, the user must mount the prop on the Editor itself.

I think that'll help the user clearly differentiate between `editor-level` props or `plugin-level` props

**Comment by nikgraf** [comment]
@juliankrispel how can the user mount it on the editor itself? btw there are tricky edgecases like ariatags. If all of them are the string "false" we should take the string "false". If only one has string "true" we should make it true. Maybe we kick it out & just write some special code for the aria-tags? What do you think?

**Comment by juliankrispel** [comment]
I'm closing this issue since it's super confusing, will write another one that makes the point clearer.
