### ISSUE TITLE
pasted text does not adjust rich text editor sizing

### ISSUE THREAD

**Issue by math0guy009** [draft-js-plugins/draft-js-plugins#1489]
pasted text does not adjust the rich text editor box...

			<div className="textEditorBox">
				<div className="editRow">
					<div className="buttonContainer">
						<button className="editButton" onClick={onBoldClick}>
							B
						</button>
						<button className="editButton" onClick={onItalicClick}>
							I
						</button>
						<button className="editButton" onClick={onUnderlineClick}>
							U
						</button>
						<button className="editButton code" onClick={onCodeClick}>
							{codeSymbol}
						</button>
						<button className="editButton" onClick={onBulletPointClick}>
							<MdFormatListBulleted size={20} />
						</button>
					</div>
				</div>
				<Editor
					handlePastedText={()=>'not-handled'}
					blockStyleFn={() => {
						return 'block';
					}}
					editorState={editorState}
					placeholder={props.placeholder}
					handleKeyCommand={handleKeyCommand}
					onChange={(edits: EditorState) => onRichTextEditChange(edits)}
				/>
			</div>
![image](https://user-images.githubusercontent.com/26983906/92530816-53df3600-f1ea-11ea-8f15-370b056f41da.png)

**Comment by sibelius** [comment]
I think you need to style you're editor using overflow y
