### ISSUE TITLE
[draftjs-mention-plugin] Cumbersome creation of custom mentionSuggestionsComponent

### ISSUE THREAD

**Issue by kizivat** [draft-js-plugins/draft-js-plugins#1501]
## Use-case/Problem

I'm trying to implement a custom editor with "mentions-like" functionality, but I want the user to be able to create new "mention" entity when the search value is not that of any other suggestions. I want to add smthng like `➕ Add new mention "abcd"` option as the last option in suggestions.

I'm not sure what the best approach would be. Right now I'm trying to provide custom `mentionSuggestionsComponent` to the plugin config, but it seems like I need to re-implement all the default functionality of `MentionSuggestions` in the custom one (like up/down arrow movement etc.) just to add the one option.

Another approach I'm considering is to extend `MentionSuggestions` class component and only re-inplement the `render()` method but I'd like to avoid that, preferable in favor of composition (e.g. render prop?).

Is there other recommended way to achieve this in the current version of the plugin?

**Comment by agjs** [comment]
@kizivat Did you ever manage to solve this, and if so, could you please share how?

Thanks in advance.
