### ISSUE TITLE
Feature request Twemoji with draft-js-emoji-plugin

### ISSUE THREAD

**Issue by qalqi** [draft-js-plugins/draft-js-plugins#1503]
Please provide option to add Twemoji in draft-js-emoji-plugin https://twemoji.twitter.com/

As Twemoji is 
Completely free. (Yes, you read that correctly.)
Multiple image formats: SVG, PNG
Supports the latest Unicode version
Simple licensing for commercial & non-commercial use

**Comment by qalqi** [comment]
Twitter’s open source emoji has you covered for all your project's emoji needs. With support for the latest Unicode emoji specification, featuring 3,245 emojis, and all for free.

**Comment by fxOne** [comment]
With this [PR](https://github.com/draft-js-plugins/draft-js-plugins/pull/1622) you should be able to use Twemoji. Just use the options `emojiImage` and `emojiInlineText` to implement you own logic. Can you please tell me if there is anything missing?

**Comment by swkeever** [comment]
@fxOne Thanks for the PR and suggestion! 

Would it be possible to expose the Unicode for each emoji as a prop to `emojiImage`? Currently, only the decorated text is exposed via the `emoji` prop. 

I believe having the Unicode would make it easier to utilize other emoji libraries - unless I've overlooked something.

**Comment by fxOne** [comment]
@swkeever can you open a new feature request for it?

**Comment by swkeever** [comment]
@fxOne Yes, I opened #1877 for this feature request. Thank you.
