### ISSUE TITLE
Can't add links to images

### ISSUE THREAD

**Issue by smddzcy** [draft-js-plugins/draft-js-plugins#1508]
First of all, thanks a lot for maintaining these awesome draft-js plugins. Really appreciate the hard work!

Currently we're using `draft-js-anchor-plugin` and `draft-js-image-plugin` in one of our projects. They're working great separately, but we noticed that we cannot add links to images. Reproduction steps:

- Set up a draft-js editor using image and anchor plugins

```
const anchorPlugin = createAnchorPlugin({
  linkTarget: '_blank',
  placeholder: 'https://…',
});
const inlineToolbarPlugin = createInlineToolbarPlugin();
const imagePlugin = createImagePlugin();
const plugins = [
  imagePlugin,
  anchorPlugin,
  inlineToolbarPlugin,
];
// ...
<Editor
  plugins={plugins}
  // ...
/>
```

- Add an image to the editor and select the image
- Click the anchor button on the inline toolbar that shows up
- Add any link and the image will disappear

I think the issue is with the `RichUtils.toggleLink` function that's used [here](https://github.com/draft-js-plugins/draft-js-plugins/blob/master/draft-js-anchor-plugin/src/utils/EditorUtils.js#L9) (not 100% sure though). Is there anything that we can do to fix this?

**Comment by Strat1987** [comment]
I'm having the exact same requirement where I'd have to combine the anchor and image plugin.
(a link should be able to be authored on an image in the WYSIWYG view).

The expected functionality on the actual image would be to be redirected to the configured URL when the image gets clicked.

**Comment by sibelius** [comment]
can you add a story of your use case on storybook? I think this would be the first step to find a fix
