### ISSUE TITLE
Inline Toolbar should adjust the positioning and placements based on window size

### ISSUE THREAD

**Issue by ashvin777** [draft-js-plugins/draft-js-plugins#1512]
## Use-case/Problem
I am trying to build an electronjs app using DraftJS plugin, I am facing this issue when using the inline toolbar, I can hardly click on those tools.

![image](https://user-images.githubusercontent.com/8143154/96745382-b3cd1d00-13e3-11eb-9ad4-217d7f712285.png)

**Comment by vdesdoigts** [comment]
Hello 👋 Did you find a solution?

**Comment by ashvin777** [comment]
Not me

**Comment by Hazantip** [comment]
Somebody solved this issue? i have the same...
