### ISSUE TITLE
Warning: The <IconBase /> component appears to be a function component that returns a class instance.

### ISSUE THREAD

**Issue by kuzyo** [draft-js-plugins/draft-js-plugins#1514]
Getting that warning when using ` "draft-js-emoji-plugin": "^2.1.3",`. When commenting out - `<EmojiSelect/>`, warning disappears. Could someone suggest any way to fix that issue ? Thanks.

![Screenshot from 2020-10-27 14-14-18](https://user-images.githubusercontent.com/3974101/97302290-86f48c00-1861-11eb-90ac-e3bbb98f5883.png)

I saw that sometimes similar warning can appear because of react-hot-loader, but after removing react-hot-loader - warning is still present.

**Comment by fxOne** [comment]
There shouldn't be a `<IconBase />` Component in `draft-js-emoji-plugin`. It looks like the error comes from `FaSmile0`.

**Comment by kuzyo** [comment]
Interesting we don't have `FaSmile0` in our codebase.

**Comment by kuzyo** [comment]
I'm seeing that <EmojiSelect/> is using FaSmileO icon from react-icons in list of default selectGroups.
https://github.com/draft-js-plugins/draft-js-plugins/blob/master/draft-js-emoji-plugin/src/constants/defaultEmojiGroups.js#L2
https://github.com/draft-js-plugins/draft-js-plugins/blob/master/draft-js-emoji-plugin/src/components/EmojiSelect/index.js#L36

**Comment by fxOne** [comment]
Hmm, didn't see that yesterday. Currently the [demo version](https://www.draft-js-plugins.com/plugin/emoji) which does not throw an error uses `react-icons@2.2.7`. I converted yesterday the emoji plugin to TypeScript and tested it also successful. Can you please check if you maybe use a differente version of `react-icons` which cause the error?

**Comment by kuzyo** [comment]
Thanks for checking. We don't using react-icons in codebase, but we are using fontawesome, not sure it can be related.
```
    "@fortawesome/fontawesome-svg-core": "^1.2.21",
    "@fortawesome/pro-light-svg-icons": "^5.10.1",
    "@fortawesome/pro-regular-svg-icons": "^5.10.1",
    "@fortawesome/pro-solid-svg-icons": "^5.10.1",
    "@fortawesome/react-fontawesome": "0.1.6",
```
Will try to setup selectGroup on our end - will see if that warning goes away.

**Comment by kuzyo** [comment]
After passing custom list to selectGroups - error is gone. Will go with that solution. Thanks.
```
  {
    title: "People",
    icon: <FontAwesomeIcon icon={faSmile} />,
    categories: ["people"],
  },
```

**Comment by fxOne** [comment]
@kuzyo can you please check if it works with latest release of `@draft-js-plugins/emoji@4.0.0-beta6`?
