### ISSUE TITLE
Backspace blocked after single :

### ISSUE THREAD

**Issue by lorensr** [draft-js-plugins/draft-js-plugins#153]
To reproduce:

1. type `:`
2. hit backspace key

Latest Mac Chrome

Related: #110

**Comment by nikgraf** [comment]
@lorensr oh, thx for reporting. will work on a fix later today!

**Comment by nikgraf** [comment]
Fixed it here: https://github.com/draft-js-plugins/draft-js-plugins/pull/180

thx again for reporting
