### ISSUE TITLE
how do I update my mentions on runtime? like pulling from a server?

### ISSUE THREAD

**Issue by nadimtuhin** [draft-js-plugins/draft-js-plugins#155]
say I want my mentions work like facebook. the database is very large so can not preload it. how do I update the list from api calls?

thanks for the awesome plugin.

**Comment by nikgraf** [comment]
@nadimtuhin that's not there yet, but something I would like to implement tomorrow :smile:

**Comment by cavneb** [comment]
Hi @nikgraf have you started on this yet? I'm also needing this functionality if available

**Comment by nikgraf** [comment]
hey @cavneb, yet I didn't get to it. Hopefully tomorrow …

**Comment by nikgraf** [comment]
Right now the mentions plugin manages the autocompletion list by itself.

In MentionsSearch/index.js you can find the method `getMentionsForFilter`. This works well if people provide an initial list upfront, but it is not ideal for

- Flux like architectures
- Remote calls to update the list based on the the search string

What I think what would be best is if let developers manage the list completely by themselves. To make it still easy to get up & running we can provide utility functions that we ship with the plugin.

Usage:

```js
import React, { Component } from 'react';
import { EditorState } from 'draft-js';
import Editor from 'draft-js-plugins-editor';
import createMentionPlugin, {} from 'draft-js-mention-plugin';
import mentions from '../mentions';

const mentionPlugin = createMentionPlugin();

// the MentionSearch becomes a component that lies outside of the Editor,
// but will be positioned correctly by using a portal approach.
// filterMentions is just a utility function and not needed depending on how
// the developers want to update the suggestions
const { MentionSearch, filterMentions } = mentionPlugin;
const plugins = [mentionPlugin];

export default class SimpleMentionEditor extends Component {

  state = {
    editorState: EditorState.createEmpty(),
    mentionSuggestions: [],
  };

  onChange = (editorState) => {
    this.setState({
      editorState,
      mentions,
    });
  };

  onSearchChange = (event) => {
    this.setState({
      mentionSuggestions: filterMentions(mentions, event.value),
    });

    // Note: instead using the provided filterMentions utility someone could
    // use their own logic to retrieve & update the mentions here e.g.
    // myAsyncLib.fetch(`/search?q=${event.value}`)
    //   .then((result) => {
    //     this.setState({
    //       mentionSuggestions: filterMentions(mentions, event.value),
    //     });
    //   });
  };

  render() {
    return (
      <div>
        <Editor
          editorState={ this.state.editorState }
          onChange={this.onChange}
          plugins={plugins}
          ref="editor"
        />
      <MentionSearch
        mentionSuggestions={ mentionSuggestions }
        onSearchChange={ this.onSearchChange }
      />
      </div>
    );
  }
}
```

**Comment by andbet39** [comment]
Just implemented this.
It's working but need some improvement about the fetching url. 

`getMentionsForFilter = () => {
    const selection = this.props.getEditorState().getSelection();
    const { word } = getSearchText(this.props.getEditorState(), selection);
    const mentionValue = word.substring(1, word.length).toLowerCase();
    let mentions = List([]);

    if( this.props.mentions.fetchUrl){
          var request = new XMLHttpRequest();
            request.open('GET', this.props.mentions.fetchUrl, false); 
            request.send(null);
            if (request.status === 200) {
              const js  = JSON.parse(request.responseText);
              mentions =  fromJS(js);
            }
    }else{
             mentions = this.props.mentions ? this.props.mentions : List([]);
    }

    const filteredValues = mentions.filter((mention) => (
      !mentionValue || mention.get('name').toLowerCase().indexOf(mentionValue) > -1
    ));
    const size = filteredValues.size < 5 ? filteredValues.size : 5;
    return filteredValues.setSize(size);
  };`

**Comment by cavneb** [comment]
@andbet39 would you mind hopping on the #draft-js-plugins slack channel for draftjs? I'd like to work with you on this. https://draftjs.herokuapp.com/

**Comment by nikgraf** [comment]
This is not possible. You may want to check out 1.0.0-beta-1 and above 😄

**Comment by AlvaroIHS** [comment]
Sorry, but what is not possible?. When do you think update npm's version? Thanks!

**Comment by nikgraf** [comment]
Sorry, that was a type. Now pulling the mention suggestions from a server is possible 🙌

**Comment by AlvaroIHS** [comment]
Thanks @nikgraf :smile:

**Comment by AlvaroIHS** [comment]
Hi @nikgraf, I tried this feature, but I have some problems. I copied your example of "Remote Data Mention Example" that appear in website. 

My problem is:

- filterMentions is not a function. If I remove it, and I pass one list of mentions, returns a TypeError: cannot read property 'isEmpty' of undefined. This is because SearchSuggestions component expected a property named "suggestions" not "mentionSuggestions". I changed it, but I have new TypeError: cannot read property 'textContent' of null.

**Comment by AlvaroIHS** [comment]
Hi @nikgraf, about my last comment. Do you know something? I don't know if I explained well. Thanks!

**Comment by nikgraf** [comment]
This is possible since the 1.0.0 release. This [page](https://www.draft-js-plugins.com/plugin/mention) contains a "Remote Data Mention Example" demonstrating the functionality. Thanks for all the feedback 🙌  It really helped to make a better implementation than I had in mind initially.
