### ISSUE TITLE
Inline toolbar and anchor not working

### ISSUE THREAD

**Issue by vcarrasc** [draft-js-plugins/draft-js-plugins#1555]
I'm trying to implement this example on my local machine https://github.com/draft-js-plugins/draft-js-plugins/blob/master/stories/inline-toolbar-with-anchor-plugin/src/AnchorSimpleLinkPluginEditor.tsx

If I run the storybook, the example works. If I do it on my local project it doesn't.

The plugin versions are 

- "draft-js": "^0.11.7",
- "draft-js-anchor-plugin": "^2.0.3",
- "draft-js-focus-plugin": "^3.0.1",
- "draft-js-inline-toolbar-plugin": "^3.0.1",
- "draft-js-plugins-editor": "2.1.1",
-  "react": "^17.0.1",
- "react-dom": "^17.0.1",  

Also, it seems like the line below requires some kind of initialization.

```
const linkPlugin = createLinkPlugin();
```

**Comment by owenhoskins** [comment]
@vcarrasc I've got this example working with these versions:
```
"@draft-js-plugins/anchor": "^4.0.0-beta2",
"@draft-js-plugins/editor": "^4.0.0-beta4",
"@draft-js-plugins/inline-toolbar": "^4.0.0-beta2",
"@draft-js-plugins/side-toolbar": "^4.0.0-beta2",
"@draft-js-plugins/undo": "^4.0.0-beta2",
"react": "16.13.1",
"react-dom": "16.13.1",
"draft-js": "^0.11.7",
```
And intergrating the link plugin like this: 
```
<InlineToolbar>
  {
    (externalProps) => (
      <React.Fragment>
        <BoldButton {...externalProps} />
        <ItalicButton {...externalProps} />
        <UnderlineButton {...externalProps} />
        <linkPlugin.LinkButton {...externalProps} />
      </React.Fragment>
    )
  }
</InlineToolbar>
```
I had first tried the method in the Getting Started docs and that **didn't work** as you described:
```
// Pass the `linkPlugin.LinkButton` into the structure of the inline toolbar.
const inlineToolbarPlugin = createInlineToolbarPlugin({
  structure: [
    BoldButton,
    ItalicButton,
    UnderlineButton,
    linkPlugin.LinkButton
  ]
});
```

**Comment by jfar41** [comment]
Hey owenhoskins,
I am currently looking to implement anchor and inline toolbar as well but even after following your steps I haven't made much luck. Can you perhaps most the git JS file in where you used this?

**Comment by alxAgu** [comment]
I myself struggled with this for a couple of hours until I realised I had my `<InlineToolbar />` as a child of `<Editor />` - it is NOT supposed to -.

Leaving this here in case it helps someone.

**Comment by fxOne** [comment]
As far as I can see [this example](https://github.com/draft-js-plugins/draft-js-plugins/blob/master/stories/inline-toolbar-custom-buttons/src/CustomInlineToolbarEditor.tsx) works as expected. Are there any open questions and some examples wrong?
