### ISSUE TITLE
Image/Drag&Drop Plugin Improvements

### ISSUE THREAD

**Issue by nikgraf** [draft-js-plugins/draft-js-plugins#156]
- [ ] Update Readme for dnd
- [ ] Fill the simple editor already with image content so people see something right away
- [ ] Improve the styling of buttons to move the image (Left/Center/Right)
- [ ] Release the plugin on NPM & make sure Ben & Nik can release it
- [ ] Is dnd the best name? I expected to drag&drop images.
- [ ] see if we need the event emitter and if callbacks might be enough …
- [x] change (e) to (event)
- [ ] make it optional to have image file upload via dropping, make image drag&drop optional
- [x] replace (C) with (WrapperComponent)
- [ ] deprecate injectBlockProps 
- [ ] investigate if handleDroppedFiles & handleDrop can be simplified together with the listeners

**Comment by nikgraf** [comment]
@bkniffler do you see a way to avoid using injectBlockProps? I would like to keep it simple and this concept is a bit harder to understand …

**Comment by bkniffler** [comment]
These are the todos I currently see need to be done, based on your list

- [ ] Check eventEmitter, maybe replace by simple callbacks
- [ ] Update Readme for dnd
- [ ] Update example with API documentation
- [ ] Make example image component more simple, remove alignment feature
- [ ] Create a more complex example with a custom image that uses the toolbar-plugin and alignment
- [ ] Allow for custom upload placeholder (no placeholder, gray box with spinning loader, or a preview of the file)
- [ ] Release the plugin on NPM & make sure Ben & Nik can release it
- [ ] Enable/disable drag&drop of images/blocks (manually and on readOnly=true)

Is the name still an issue for you?

**Comment by nikgraf** [comment]
@bkniffler my thougths on name: dnd doesn't necessarily have to mean image drag & drop. I could video or audio or even text that is dragged around. To me it seems like this almost is a image plugin with 3 parts:

- upload
- image management
- image drag & drop support

What do you think?

**Comment by bkniffler** [comment]
I agree, DnD doesn't mean image drag&drop. The plugin should provide all the handlers to make drag&drop possible in general, wether it is video, audio or images, wether they are dropped from the desktop, they are blocks within the editor itself or blocks in a toolbar dropped on the editor. The only thing that really is image specific is the image component, which is rather simple (if you strip out the alignment stuff that should not really be part of this plugin anyways).

Okay, there are some more image specific things here and there, but I'm currently refactoring the lib, stripping these out and working on the other todos we talked about. Then we can add a draft-js-image-plugin that does the image handling stuff.

**Comment by nikgraf** [comment]
sounds like the right way to go … image plugin + dnd plugin and then we can add all sorts of plugins like video, youtube or audio :smiley:
this is going to be sooo cool!

**Comment by bkniffler** [comment]
Okay, I just committed some code.

#### This shows drag&drop of images and text files
![apr 04 2016 13 21](https://cloud.githubusercontent.com/assets/4349324/14246540/31fd9956-fa68-11e5-99f4-258244fcab17.gif)

#### This is how the dnd config looks like
```javascript
createDndPlugin({
  allowDrop: true,
  handleUpload: (data, success, failed, progress) =>
    mockUpload(data, success, failed, progress),
  handlePreview: (state, selection, data) => {
    const { type } = data;
    if (type.indexOf('image/') === 0) {
      return addBlock(state, state.getSelection(), 'block-image', data);
    } else if (type.indexOf('text/') === 0 || type === 'application/json') {
      return addBlock(state, state.getSelection(), 'preview-github', data);
    } return state;
  }, handleBlock: (state, selection, data) => {
    const { type } = data;
    if (type.indexOf('image/') === 0) {
      return addBlock(state, state.getSelection(), 'block-image', data);
    } else if (type.indexOf('text/') === 0 || type === 'application/json') {
      return addBlock(state, state.getSelection(), 'block-text', data);
    } return state;
  },
})
```

#### This is how a custom preview component looks like
```jsx
import React, { Component } from 'react';

class PreviewGithub extends Component {
  render() {
    const { blockProps, block } = this.props;

    return (
        <span contentEditable={false} data-offset-key={ `${block.get('key')}-0-0` }>
          ![Uploading {blockProps.name}...]({blockProps.progress})
        </span>
    );
  }
}

export default PreviewGithub;
```

There is still a lot to do when it comes to cleaning up the example, outsourcing the image to its own plugin and some refactoring.

Also I need to figure out how to replace the eventEmitter I got rid of now. Maybe we could allow custom events in the plugin-editor. A plugin could define and call an event like onUploadProgress, that other plugins may handle just like draft-js handlers/events get handled (onChange, onDropFile, blockRendererFn). What do you think @nikgraf ? Does that make sense to you?

**Comment by nikgraf** [comment]
@bkniffler sorry, just saw this now. This is really cool. I'm a bit tired now, but it looks like a way nicer API + solution.

The one thing that bugs me a bit is that all other plugins that want to support dnd would need to require the dnd plugin to use `Draggable`. Did I understand this correct? I don't know a better solution, but having one without the wrapper would be nice …

**Comment by bkniffler** [comment]
Sure, with something like this:
```jsx
export default function DndPlugin = (options) => {
	return {
		blockRendererFn: (contentBlock) => {
			return {
				wrappers: [Draggable],
				blockProps: {
					allowDrag: options.allowDag !== false
				}
			}
		}
	}
}
```
No type is returned, as the plugin doesn't have any opinion on the types, but it needs to apply the decorator after all plugins blockRendererFn were run and a type has been set. Also, it will define specific blockProps, that need to be merged with those of other blockRendererFn's.

I've talked about similar stuff already, but I'm not sure if I was able to verbalize the necessity of this within a plugin architecture. Plugins need the ability to modify the original return of blockRendererFn. What you are asking for is only one application example, there is plenty of more scenarios.

**Comment by nikgraf** [comment]
That makes a lot more sense to me now. Thanks for the detailed explanation. Let's do the `decorators` thing.

**Comment by juliankrispel** [comment]
@nikgraf I'm going to add some tests for this today or tomorrow :+1:

**Comment by tarjei** [comment]
Hi, what is the status of the DnD plugin? Is it usable?

**Comment by bkniffler** [comment]
It is usable, sorry for not keeping up here. You can try it live here: http://draft-wysiwyg.herokuapp.com/
The code for initializing the dnd part https://github.com/bkniffler/draft-wysiwyg/blob/master/src/create-plugins.js, just look at everything that contains 'dnd'. We will hopefully be able to provide docs soon. 

There is a thread here https://github.com/draft-js-plugins/draft-js-plugins/issues/134 that you can use for further discussions (my post is a bit outdated, but I'd like to keep the discussions there). The PR is at https://github.com/draft-js-plugins/draft-js-plugins/issues/134.

I will close this for now, we will need to revisit each plugin at some point and most of the todos here are not valid any more.
