### ISSUE TITLE
[draftjs-mention-plugin] using supportWhitespace breaks suggestions menu trigger

### ISSUE THREAD

**Issue by shiranZe** [draft-js-plugins/draft-js-plugins#1563]
Hey,
I'm trying to implemet the mentionPlugin with `supportWhitespace: true` ,
because i need to support a whitespace while typing a search option, and also to enable deleting the whole mention and not just last word
(e.g. when mentioning `@bla1 bla2` and clicking backspace key, I want the whole mention to be deleted
and just not `bla2` 
(if there is another way to do so, it will be very helpfull)

The problem is that once i enabled supportWhitespace , when typing the second mention, the trigger for the suggestions menu isn't working anymore, unless clicking on the space bar key after the trigger key (in my case: '@').

here's an exemple from the draftjs-mention-plugin docs: [()](https://www.draft-js-plugins.com/plugin/mention)
![captured (3)](https://user-images.githubusercontent.com/40235967/98709300-e1760800-238a-11eb-9128-85aedd8a0a6d.gif)

**Thanks again for your help.**

**Comment by fxOne** [comment]
Please look at this ticket: https://github.com/draft-js-plugins/draft-js-plugins/issues/1550

**Comment by shiranZe** [comment]
@fxOne Thank you!
did #1550 solved the deletion problem? or just the need to add space after the second @?

**Comment by fxOne** [comment]
The space after the second @. I would guess that the part deletion is a "feature" of `supportWhitespace: false` even if i don't know the use case.
