### ISSUE TITLE
Up/Down Arrow Keys Not Working on mention-plugin after altering key bindings.

### ISSUE THREAD

**Issue by sr-webcode** [draft-js-plugins/draft-js-plugins#1578]
Hi all, I'm quite new to Draft JS /Draft JS Plugins and been trying to figure out what's causing this. Originally what I wanted to happen is to alter the key-bindings of the editor to make the "Enter" key return a custom "submit-comment" event  then assign Shift+Enter key to return a 'split-block' of which creates a new line or block. I was able to pull through with this code: 

```
const handkekeyBindings = (e: SyntheticKeyboardEvent) => {
    if (e.key === "Enter") {
      if (e.nativeEvent.shiftKey) {
        return "split-block";
      } else {
        return "submit-comment";
      }
    }
    return getDefaultKeyBinding(e);
  };
```

I applied the key-bindings handler to my Editor Component:

```
<Editor
   editorState={editorState}
   onChange={handleEditorStateChange}
    keyBindingFn={handkekeyBindings}
    handleKeyCommand={handleKeyEvent}
    plugins={plugins}
 />

```

However, after altering the key-bindings of the editor , I can't seem to use  the UP/DOWN Arrow keys anymore  to select any of the suggestions that would pop-out on the mentions.

![image](https://user-images.githubusercontent.com/49327821/99405267-89f61000-2927-11eb-95b3-9f586d5e6e9d.png)

Any Ideas on this one? I may perhaps messed up on something. Thanks!

**Comment by Vodzo** [comment]
Found a workaround for this exact issue I was having. The idea is to remove bindings while the suggestions popup is open and apply it again when closed.

```js
const keyBinding = () => (e: React.KeyboardEvent): string | null => {
  if (e.key === "Enter") {
    if (e.nativeEvent.shiftKey) {
      return "split-block";
    } else {
      return "submit-comment";
    }
  }
  return getDefaultKeyBinding(e);
};

const SomeComponent = () => {
  /* default keyBinding */
  const [stateKeyBingding, setStateKeyBingding] = useState(keyBinding);

  const removeBinding = () => {
    setStateKeyBingding(undefined);
  };

  const applyBinding = () => {
    setStateKeyBingding(keyBinding);
  };

  return (
    <>
    <Editor 
      /* other props */
      keyBindingFn={stateKeyBingding}
    />
    <MentionSuggestions
      /* other props */
      onOpen={removeBinding}
      onClose={applyBinding}
    />
    </>
  )
}
```

Hope this helps your use case too!

**Comment by sr-webcode** [comment]
@Vodzo woooh,, your lifesaver , thanks !

**Comment by sr-webcode** [comment]
@Vodzo woooh,, you're lifesaver , thanks !

**Comment by upworker00852** [comment]
Hello. @Vodzo .
I have just used your code. It is working well.
But I have a question.
I didn't open mention by "@" and typing generally string but Why does onOpen function?
Would you please explain about this? Thanks

**Comment by fxOne** [comment]
@upworker00852 You can find the correct solution in the [FAQ](https://github.com/draft-js-plugins/draft-js-plugins/blob/master/FAQ.md#keybindings-added-by-a-plugin-stop-working-when-using-custom-keybindingfn-function).

**Comment by upworker00852** [comment]
@fxOne I have just checked the FAQ and I found the solution at there. Thanks :)))

**Comment by upworker00852** [comment]
Hello.
I need to popup a modal when clicking a selected mention.
Would you please help me? Thanks

**Comment by duhaime** [comment]
Where is `getDefaultKeyBinding` defined?
