### ISSUE TITLE
CMD-Z after inserting sticker makes the editor bug

### ISSUE THREAD

**Issue by antoinerey** [draft-js-plugins/draft-js-plugins#158]
I was playing on your [demonstration website](https://www.draft-js-plugins.com/plugin/sticker) and found a bug.

**Here are the step to reproduce :**
1. Insert a sticker
2. CMD-Z to cancel  
   > The cursor should be on the top right side now
3. Type some text  
   > The editor is now broken ! :boom: 

PS: I'm using Chrome Version 49.0.2623.110 (64-bit)

**Comment by nikgraf** [comment]
I could reproduce it my environment as well and will try to fix in the coming days … thanks for reporting

**Comment by juliankrispel** [comment]
can't reproduce this anymore
