### ISSUE TITLE
Can 'draft-js-emoji-plugin' has onOpen, onClose callback for EmojiSelect Plugin ?

### ISSUE THREAD

**Issue by Wayne0902** [draft-js-plugins/draft-js-plugins#1580]
Can 'draft-js-emoji-plugin' has onOpen, onClose callback for EmojiSelect Plugin ?

**Comment by murattishkul** [comment]
I'd like to know too

**Comment by fxOne** [comment]
If you can provide a PR I would love to merge it

**Comment by murattishkul** [comment]
@fxOne I see that changes has been introduced by https://github.com/draft-js-plugins/draft-js-plugins/pull/279/ but they seem to not work

**Comment by murattishkul** [comment]
@fxOne I'd like to make a pr, is there any guidlines for making a pr, or I just create a pr to master?

**Comment by murattishkul** [comment]
@fxOne please look at my pr https://github.com/draft-js-plugins/draft-js-plugins/pull/1753
