### ISSUE TITLE
Support click event for 'Hashtag' plugin

### ISSUE THREAD

**Issue by DevAngsy** [draft-js-plugins/draft-js-plugins#1592]
## Use-case
I think hashtag is designed to be clicked, like twitter, as it makes sense.

OR

Render 'a' tag.

**Comment by fxOne** [comment]
Love the idea!

We should make it possible to pass a custom component for rendering the hashtag like it is already possible for mentions (`mentionComponent`).

**Comment by webdeb** [comment]
Maybe reusing the mention plugin is the solution?

**Comment by DevAngsy** [comment]
reopen
