### ISSUE TITLE
no toolbar appears on Anchor plugin

### ISSUE THREAD

**Issue by TLeobons** [draft-js-plugins/draft-js-plugins#1595]
"Try selecting a part of this text and click on the link button in the toolbar that appears …"

renders on the browser but selecting a part of the text won't make a toolbar appears, like it does in the example on https://www.draft-js-plugins.com/plugin/anchor

**Comment by fxOne** [comment]
Can you please share some more information about where the toolbar does not appear, like browser, page, sourcecode etc. as the example on the sample page works for me.

**Comment by TLeobons** [comment]
My bad! I didn't remove the standard index.css import from the CRA index.js and it was the culprit.
