### ISSUE TITLE
Image Plugin not working

### ISSUE THREAD

**Issue by rkamta** [draft-js-plugins/draft-js-plugins#1597]
## Environment

- draft-js-plugins-editor: "^3.0.0"
- draft-js-image-plugin: "^2.0.7"

## Description
The editor gets error after uploading image.
--- ** ---
Warning: React does not recognize the `preventScroll` prop on a DOM element. If you intentionally want it to appear in the DOM as a custom attribute, spell it as lowercase `preventscroll` instead. If you accidentally passed it from a parent component, remove it from the DOM element.
--- ** ---
## Reproducible Demo

![Screenshot_8](https://user-images.githubusercontent.com/37015885/100202800-c1267b80-2f3c-11eb-993a-a097438a5270.png)

**Comment by fxOne** [comment]
This warning should be resolve in the latest beta version, can you please try out [`@draft-js-plugins/image@4.0.0-beta2`](https://www.npmjs.com/package/@draft-js-plugins/image)?

**Comment by rkamta** [comment]
Awesome!

**Comment by rkamta** [comment]
But after changing dependencies, it is getting the other error.

![image](https://user-images.githubusercontent.com/37015885/100296624-b06f1780-2fc7-11eb-81e8-bf078015a13a.png)

--dependencies:
    "@draft-js-plugins/alignment": "^4.0.0-beta2",
    "@draft-js-plugins/drag-n-drop": "^4.0.0-beta2",
    "@draft-js-plugins/editor": "^4.0.0-beta3",
    "@draft-js-plugins/focus": "^4.0.0-beta2",
    "@draft-js-plugins/image": "^4.0.0-beta2",
    "@draft-js-plugins/linkify": "^4.0.0-beta2",
    "@draft-js-plugins/resizeable": "^4.0.0-beta2",

**Comment by rkamta** [comment]
There is not good compatibility between packages.
