### ISSUE TITLE
Warning: Function components cannot be given refs. Attempts to access this ref will fail. Did you mean to use React.forwardRef()?

### ISSUE THREAD

**Issue by rkamta** [draft-js-plugins/draft-js-plugins#1599]
## Environment

- @draft-js-plugins/editor version:
  "@draft-js-plugins/editor": "^4.0.0-beta3",
- plugin name and version:
  "@draft-js-plugins/image": "^4.0.0-beta2",
  "@draft-js-plugins/focus": "^4.0.0-beta2",

## Description

`import React from 'react';
import { EditorState, Modifier, RichUtils, convertFromRaw } from 'draft-js';
import { FormatBold, FormatItalic, FormatUnderlined, FormatListBulleted, FormatListNumbered, FormatQuote, Code, FormatClear } from '@material-ui/icons';
import InlineStyleControls from './InlineStyleControls';
import BlockStyleControls from './BlockStyleControls';
import MediaStyleControls from './MediaStyleControls';
import { Link, findLinkEntities } from './controls/Link';
import Editor, { composeDecorators } from '@draft-js-plugins/editor';
import createImagePlugin from "@draft-js-plugins/image";
import createFocusPlugin from '@draft-js-plugins/focus';
import createResizeablePlugin from '@draft-js-plugins/resizeable';
import 'draft-js/dist/Draft.css';
import 'antd/dist/antd.css';
import 'draft-js-image-plugin/lib/plugin.css';
import { Button } from 'antd';

const focusPlugin = createFocusPlugin();
const resizeablePlugin = createResizeablePlugin();

const decorator = composeDecorators(
    resizeablePlugin.decorator,
    focusPlugin.decorator
);

const imagePlugin = createImagePlugin({ decorator });
const plugins = [
    imagePlugin,
    focusPlugin,
    resizeablePlugin,
];
const decorators = [
    {
        strategy: findLinkEntities,
        component: Link
    }
];

const initialState = {
    "entityMap": {
        "0": {
            "type": "IMAGE",
            "mutability": "IMMUTABLE",
            "data": {
                "src": "https://www.web-payment-software.com/mc_images/category/26/donation-payment-page-sample.jpg"
            }
        }
    },
    "blocks": [{
        "key": "9gm3s",
        "text": "You can have images in your text field. This is a very rudimentary example, but you can enhance the image plugin with resizing, focus or alignment plugins.",
        "type": "unstyled",
        "depth": 0,
        "inlineStyleRanges": [],
        "entityRanges": [],
        "data": {}
    }, {
        "key": "ov7r",
        "text": " ",
        "type": "atomic",
        "depth": 0,
        "inlineStyleRanges": [],
        "entityRanges": [{
            "offset": 0,
            "length": 1,
            "key": 0
        }],
        "data": {}
    }, {
        "key": "e23a8",
        "text": "See advanced examples further down …",
        "type": "unstyled",
        "depth": 0,
        "inlineStyleRanges": [],
        "entityRanges": [],
        "data": {}
    }]
};

class DraftEditor extends React.Component {
    constructor(props) {
        super(props);
        this.state = {
            editorState: EditorState.createWithContent(convertFromRaw(initialState)),
        };

        this.handleKeyCommand = this.handleKeyCommand.bind(this);
        this.onChange = this.onChange.bind(this);
    }

    onChange = (editorState) => {
        this.setState({ editorState });
    }

    handleKeyCommand = (command, editorState) => {
        const newState = RichUtils.handleKeyCommand(editorState, command);

        if (newState) {
            this.onChange(newState);
            return 'handled';
        }

        return 'not-handled';
    }

    _toggleBlockType = (blockType) => {
        this.onChange(
            RichUtils.toggleBlockType(
                this.state.editorState,
                blockType
            )
        );
    }

    _toggleInlineStyle = (inlineStyle) => {
        this.onChange(
            RichUtils.toggleInlineStyle(
                this.state.editorState,
                inlineStyle
            )
        );
    }

    _onTab = (e) => {
        const maxDepth = 4;
        this.onChange(RichUtils.onTab(e, this.state.editorState, maxDepth));
    }

    _clear = () => {
        const { editorState } = this.state
        const selection = editorState.getSelection()
        const contentState = editorState.getCurrentContent()
        const styles = editorState.getCurrentInlineStyle()

        const removeStyles = styles.reduce((state, style) => {
            return Modifier.removeInlineStyle(state, selection, style)
        }, contentState)

        const removeBlock = Modifier.setBlockType(removeStyles, selection, 'unstyled')

        this.setState({
            editorState: EditorState.push(
                editorState,
                removeBlock
            )
        })
    }

    getBlockStyle = (block) => {
        switch (block.getType()) {
            case 'blockquote': return 'RichEditor-blockquote';
            default: return null;
        }
    }

    handleEditorStateUpdate = (newState) => {
        this.setState({
            editorState: newState
        });
    }

    render() {
        const inlineIcoins = [
            { label: 'Bold', style: 'BOLD', icon: <FormatBold /> },
            { label: 'Italic', style: 'ITALIC', icon: <FormatItalic /> },
            { label: 'Underline', style: 'UNDERLINE', icon: <FormatUnderlined /> },
        ];
        const orderIcons = [
            { label: 'UL', style: 'unordered-list-item', icon: <FormatListBulleted /> },
            { label: 'OL', style: 'ordered-list-item', icon: <FormatListNumbered /> }
        ];
        const quoteIcons = [
            { label: 'Blockquote', style: 'blockquote', icon: <FormatQuote /> },
            { label: 'Code Block', style: 'code-block', icon: <Code /> }
        ];

        return (
            <div>
                <h1 className="text-center mb-3">Draft Editor</h1>
                <div className="border p-3">
                    <div className="toolbar ">
                        <div className="clearfix">
                            <div className="toolbar-group">
                                <InlineStyleControls
                                    editorState={this.state.editorState}
                                    icons={inlineIcoins}
                                    onToggle={this._toggleInlineStyle.bind(this)}
                                />
                            </div>
                            <div className="toolbar-group">
                                <BlockStyleControls
                                    editorState={this.state.editorState}
                                    icons={orderIcons}
                                    onToggle={this._toggleBlockType.bind(this)}
                                />
                            </div>
                            <div className="toolbar-group">
                                <BlockStyleControls
                                    editorState={this.state.editorState}
                                    icons={quoteIcons}
                                    onToggle={this._toggleBlockType.bind(this)}
                                />
                            </div>
                            <div className="toolbar-group">
                                <Button type="default" size="middle" onClick={this._clear.bind(this)}>
                                    <FormatClear />
                                </Button>
                            </div>
                        </div>
                        <div className="clearfix">
                            <div className="toolbar-group">
                                <MediaStyleControls
                                    editorState={this.state.editorState}
                                    handleEditorStateUpdate={this.handleEditorStateUpdate.bind(this)}
                                />
                            </div>
                        </div>
                    </div>
                    <hr />
                    <Editor
                        blockStyleFn={this.getBlockStyle}
                        editorState={this.state.editorState}
                        onChange={this.onChange}
                        handleKeyCommand={this.handleKeyCommand}
                        plugins={plugins}
                        decorators={decorators}
                        ref={element => {
                            this.editor = element
                        }}
                    />
                </div>
            </div>
        );
    }

}

export default DraftEditor;`

**Comment by Apporix** [comment]
Hello, 
I stumbled across the same error and I wondered if you found a fix for this error?
It seems that the resizeable plugin causes this error by trying to use a undefined reference. 
I am also using React Hooks, so its new implementation of references might be a problem too.

**Comment by hasakilol** [comment]
why is this issure closed?

**Comment by fxOne** [comment]
@hasakilol can you provide a [codesandbox](codesandbox.io) example with the issue?
