### ISSUE TITLE
Clicking placeholder should focus editor

### ISSUE THREAD

**Issue by felippepuhle** [draft-js-plugins/draft-js-plugins#1600]
## Description

On old versions, if I click on the editor placeholder, it'd focus the editor. I think we can fix this by just adding `pointer-events: none`

## Reproducible Demo

https://codesandbox.io/s/draft-js-pluginseditor-placeholder-zvg7y

**Comment by felippepuhle** [comment]
In fact, I just tested other versions and it seems to have the same behavior... Should we handle it or close this ticket?

**Comment by fxOne** [comment]
The sample on the [draft-js page](https://draftjs.org/) page handles it by its own css: https://github.com/facebook/draft-js/blob/0411ea2f24275ed9cdadf2ae68af97a160d828fa/website/src/components/DraftEditorExample/css/draft.css#L10

`.public-DraftEditorPlaceholder-root{color:#9197a3;position:absolute;z-index:1}`

So I guess you forget to imported the draft-js css?

**Comment by felippepuhle** [comment]
You're right, I didn't import draft-js CSS on the code sandbox... 🤦‍♂️  I'm so sorry, I'm closing this issue.
