### ISSUE TITLE
Image conversation from HTML with editor on the draft-js-plugins-editor not working

### ISSUE THREAD

**Issue by malavshah9** [draft-js-plugins/draft-js-plugins#1602]
## Environment

- @draft-js-plugins/editor version: 3.0.0
- plugin name and version: draft-js-plugins-editor: 3.0.0

## Description

When composite decorators from draft-js used with the Editor from draft-js-plugins-editor converts the IMAGE entity to the camera icon.
This happens when I used emoji plugin with editor.
So I think emoji plugin is converting it to Camera emoji when It sees link inside the state.

## Reproducible Demo

Here is the example which you can [try](https://codesandbox.io/s/elated-bell-bkkyx?fontsize=14&hidenavigation=1&theme=dark).

**Comment by fxOne** [comment]
It looks like the camera emoji comes from draft-js itself:
```js
const sampleMarkup =
      "<b>Bold text</b>, <i>Italic text</i><br/ ><br />" +
      '<a href="https://www.facebook.com">Example link</a><br /><br/ >' +
      '<img src="https://raw.githubusercontent.com/facebook/draft-js/master/examples/draft-0-10-0/convertFromHTML/image.png">';
const blocksFromHTML = convertFromHTML(sampleMarkup);

const state = ContentState.createFromBlockArray(
  blocksFromHTML.contentBlocks,
  blocksFromHTML.entityMap
);
const editorState = EditorState.createWithContent(state, decorator);
console.log(editorState.getCurrentContent().getPlainText());
```
will output:
```
"Bold text, Italic text

Example link

📷"
```

I guess the emoji plugin runs before your decorator and handles it so that you only see the emoji. I have currently no idea whats the best to handle this case. I will look deeper into it after we have done the 4.0.0 release.

**Comment by malavshah9** [comment]
@fxOne , Yes that Is understood what is causing the problem.

Thanks for the reply!!! @fxOne 

For the temporary fix, I have fixed it with following code snippets. where I have converted 📷 with '' in the constructor of component itself.

I know comparing the 📷 is not good idea, but for the sake of project ongoing, we need to do this.

```
import React from "react";
import {
  CompositeDecorator,
  ContentState,
  EditorState,
  convertFromHTML,
  convertToRaw,
  convertFromRaw
  // Editor
} from "draft-js";
import Editor from "draft-js-plugins-editor";
import createEmoji from "draft-js-emoji-plugin";
import "./styles.css";
function findImageEntities(contentBlock, callback, contentState) {
  contentBlock.findEntityRanges((character) => {
    const entityKey = character.getEntity();
    return (
      entityKey !== null &&
      contentState.getEntity(entityKey).getType() === "IMAGE"
    );
  }, callback);
}
const Image = (props) => {
  const { src } = props.contentState.getEntity(props.entityKey).getData();

  return (
    <img
      src={src}
      alt={"please_dont_convert_to_camera"}
      title={"adf"}
      height={100}
      width={200}
    />
  );
};
export default class App extends React.Component {
  constructor(props) {
    super(props);
    const decorator = new CompositeDecorator([
      {
        strategy: findImageEntities,
        component: Image
      }
    ]);
    this.emojiPlugin = createEmoji();
    const sampleMarkup =
      "<b>Bold text</b>, <i>Italic text</i><br/ ><br />" +
      '<a href="https://www.facebook.com">Example link</a><br /><br/ >' +
      '<img src="https://raw.githubusercontent.com/facebook/draft-js/master/examples/draft-0-10-0/convertFromHTML/image.png">';
    const blocksFromHTML = convertFromHTML(sampleMarkup);
    const state = ContentState.createFromBlockArray(
      blocksFromHTML.contentBlocks,
      blocksFromHTML.entityMap
    );
    const raw=convertToRaw(state);
    raw.blocks = raw.blocks.map((block) => {
      let newText = block.text.replace("📷", " ");
      return {
        ...block,
        text: newText,
      };
    });
    const anotherNewState = convertFromRaw(raw);
    this.state = {
      editorState: EditorState.createWithContent(anotherNewState, decorator)
    };
    this.onChange = (editorState) => {
      this.setState({ editorState });
    };
  }

  render() {
    return (
      <div>
        <div style={{ marginBottom: 10 }}>
          Sample HTML converted into Draft content state
        </div>
        <div style={styles.editor} onClick={this.focus}>
          <Editor
            editorState={this.state.editorState}
            onChange={this.onChange}
            ref="editor"
            plugins={[this.emojiPlugin]}
            decorators={[
              {
                strategy: findImageEntities,
                component: Image
              }
            ]}
          />
        </div>
      </div>
    );
  }
}
const styles = {
  root: {
    fontFamily: "'Helvetica', sans-serif",
    padding: 20,
    width: 600
  },
  editor: {
    border: "1px solid #ccc",
    cursor: "text",
    minHeight: 80,
    padding: 10
  },
  button: {
    marginTop: 10,
    textAlign: "center"
  }
};

```

**Comment by mosshead1995** [comment]
Any updates on this?

**Comment by malavshah9** [comment]
@mosshead1995  Not yet, unfortunately

**Comment by fxOne** [comment]
@malavshah9 as far as I can see it works with the latest version: https://codesandbox.io/s/suspicious-ellis-t8krv?file=/src/App.js

**Comment by fxOne** [comment]
The sample should work now, looks like it didn't saved my last change

**Comment by aquelehugo** [comment]
@fxOne your implementation is not enough, the image cannot be deleted :(

**Comment by fxOne** [comment]
@aquelehugo the image can be deleted, the issue is that it is a little bit hard to get the cursor behind the image.

**Comment by aquelehugo** [comment]
@fxOne true. But if you try to select all and delete, the image is kept. I found out if there is some content after the image, the problem doesn't occur.
Seems like a bug in DraftJS itself anyway. Any idea on how to deal with this?

**Comment by fxOne** [comment]
@aquelehugo I have tried to reproduce it with the [image examples](https://www.draft-js-plugins.com/plugin/image) but I couldn't reproduce it there as there were always a new line. Maybe it is an issue from `convertFromHTML`.

**Comment by aquelehugo** [comment]
@fxOne yeah, the problem is with `convertFromHTML`. I'm using [html-to-draftjs](github.com/jpuri/html-to-draftjs) now and it's working fine. Thanks :)
