### ISSUE TITLE
[draft-js-alignment-plugin] You cannot adjust alignment when text is on the same line

### ISSUE THREAD

**Issue by jonescr3** [draft-js-plugins/draft-js-plugins#1605]
## Environment

- @draft-js-plugins/editor version: "draft-js-alignment-plugin": "2.0.6",
- plugin name and version: "draft-js-alignment-plugin": "2.0.6",

## Description

On any row where text exists, you can not select the image/item that you'd otherwise click on to trigger alignment options. Instead, the cursor will always go to the text that is on the same row/lin of your mouse. This is a fairly fatal bug for alignment as it makes changing the alignment of an object impossible if the user has a floating paragraph of text that completely wraps around the image. This is because the large paragraph floating to the right or left of an image will have a row of text at every available location, so clicking the item to change alignment is impossible.

## Reproducible Demo

This is completely reproducible in the "draft-js-alignment-plugin": "2.0.6", demo found at https://www.draft-js-plugins.com/plugin/alignment. 1. Make sure you are aligning with text to the right or left of your object. 2)Try to click on the object on the same horizontal line where text is floating to the side. Notice you can not click on the object, it will instead attempt to select the text.

**Comment by jonescr3** [comment]
does anyone use this plugin? i cant see how to use It with this bug

**Comment by fxOne** [comment]
The issue is that the `<div class="" data-block="true" data-editor="SimpleAlignmentEditor" data-offset-key="e23a8-0-0">` is over `figure` color block. You can currently select the color block if you try to select it below the text line.
![image](https://user-images.githubusercontent.com/5929640/110180314-da777780-7e09-11eb-98d1-146b04a351eb.png)
I'll think about how to fix it for the demo.

**Comment by jonescr3** [comment]
Thanks! This solved the issue! Any sense when fixes like this are built into a new version of the plugin?

**Comment by fxOne** [comment]
There were no issues with the alignment plugin. There was a `position: relative: z-index: 1;` for the color block missing
