### ISSUE TITLE
Table Editor

### ISSUE THREAD

**Issue by abeq** [draft-js-plugins/draft-js-plugins#164]
Is there plan to make GUI-based Table Editor?

**Comment by nikgraf** [comment]
@bkniffler had something in his original wysiwyg and currently is porting these to the plugins system. He probably can tell more if there are plans to do so https://draft-wysiwyg.herokuapp.com/

**Comment by bkniffler** [comment]
Yes, there are different approaches for that. https://github.com/facebook/draft-js/issues/220 suggests using a html/markdown syntax to store the data, but I think its a better approach to use nested draft editors, as it will allow consistency with the rest of the editor (drag/drop, toolbars, mentions, etc). This is a bit tricky to implement, but it works and it is part of what I want to migrate.

I could initiate a table plugin as soon as thats done!

**Comment by bkniffler** [comment]
Just to let everyone who needs this feature know, I've had some success developing a table-plugin using the above mentioned nested draft editors.

![mai-16-2016 16-29-47](https://cloud.githubusercontent.com/assets/4349324/15292467/8109eba8-1b83-11e6-9348-88c0a6f95d66.gif)

Along with other cool new plugins, this is currently being developed in the wysiwyg branch, you can find the code here: https://github.com/draft-js-plugins/draft-js-plugins/tree/wysiwyg/draft-js-table-plugin/src

I'm still taking care of a few more issues, but you can expect this to be polished, usable and hopefully properly documented very soon!

**Comment by gbbr** [comment]
So what happened to the above? I can see it's now in the `legacy` folder

**Comment by z-ax** [comment]
Pretty important feature to me, would love to see that for sure.
Any publishing tool requires tables. Used not so often, but still can't be replaced with anything else in my opinion.

**Comment by xiaopow** [comment]
Any update on this?

**Comment by nikgraf** [comment]
This is not going to be implemented by me. Too much effort and I don't feel comfortable maintaining the approach @bkniffler took here.

@xiaopow @z-ax @gbbr any of you want to the it, clean it up and publish it as an independent plugin? Happy to add it to the community section :)
