### ISSUE TITLE
Focus plugin breaks on keyboard enter

### ISSUE THREAD

**Issue by alexpuertasr** [draft-js-plugins/draft-js-plugins#1644]
## Environment

- @draft-js-plugins/editor => 4.0.0-beta4
- @draft-js-plugins/focus => 4.0.0-beta2

## Description

Once the plugin is added in the editor the creation of new blocks pressing enter is not working anymore

## Reproducible Demo

https://codesandbox.io/s/focus-issue-7w5he?file=/src/App.js

**Comment by fxOne** [comment]
I just released `@draft-js-plugins/editor@4.0.0-beta3` which should solve the problem as I forgot to create a new release for this package on the last changes. Can you please try out?

**Comment by alexpuertasr** [comment]
@fxOne In this new version it's working well, thank you 👍
