### ISSUE TITLE
Displayed Key combinations for emojis do not lead to emoji display in text

### ISSUE THREAD

**Issue by vanLSpring** [draft-js-plugins/draft-js-plugins#1645]
## Environment

- @draft-js-plugins/editor version: 4.0.0-beta4
- plugin name and version: @draft-js-plugins/emoji@4.0.0-beta5

- @draft-js-plugins/editor version:
- plugin name and version:

## Description

- go to https://www.draft-js-plugins.com/plugin/emoji
- scroll to first example (Simple Emoji Example)
- mouse over emoiji
- see key combinations for emojis
- type displayed key combination, e.g. `:smile:` 

This does not lead to the display of the mentioned smiley emoji. The key combination `:smile` does.

**Comment by fxOne** [comment]
fixed via #1649
