### ISSUE TITLE
CreateWithContent function with decorators gets me stuck in a loop

### ISSUE THREAD

**Issue by supasus** [draft-js-plugins/draft-js-plugins#1665]
Hey Guys,

I am saving Editor states to a server after converting them to markdown. When I retrieve them I convert them back back to EditorState, but my Decorators appear to be missing. Issue seems simple enough, new state - no decorators. 

The decorators work just fine whenever a new instance is created from blank - 

```
  const [editorState, setEditorState] = useState(EditorState.createEmpty())

 <Editor
          editorState={editorState}
          onChange={onEditorStateChange}
          plugins={plugins}
          ref={(editor) => (editorRef.current = editor)}
          decorators={[typograph]}
  />
```

But whenever I introduce a state to retrieve the data from I seem to get into a loop which just ends up freezing my page. Leaving out the Typograph decorator fixes it, but I don't see any other way of introducing the decorators back to the new state. 
```
const TextContent = ({state, update, id, stopWords = []}) => {

   const [{ plugins, InlineToolbar, linkPlugin, typograph}] = useState(() => {
    const linkPlugin = createLinkPlugin({placeholder: ""})
    const inlineToolbarPlugin = createInlineToolbarPlugin({})
    const { InlineToolbar } = inlineToolbarPlugin;
   
    const typograph  = new CompositeDecorator([
      {
        strategy: handleStopWords,
        component: HandleSpan
      },
  
    ]);
    
    const plugins = [inlineToolbarPlugin, linkPlugin];
    return {
      plugins,
      InlineToolbar,
      linkPlugin,
      typograph,
    };
  });
   React.useEffect(() => {           
       if(state.data){
          const rawData = markdownToDraft(state.data);
          const contentState = convertFromRaw(rawData);
          const newEditorState = EditorState.createWithContent(contentState, typograph);
          setEditorState(newEditorState)
        }
  }, [])
}
```

**Comment by supasus** [comment]
I've tried using the push method as shown below, but that still leaves out the decorators. My original state doesn't have the decorator in it, but when I try to put it in there once again I encounter the same issue.
```
 const [editorState, setEditorState] = useState(EditorState.createEmpty())

const newEditorState = EditorState.push(editorState, contentState)
setEditorState(newEditorState)
```

**Comment by supasus** [comment]
I fixed it. The decorator must be left outside of the function, otherwise you'll end up dealing with this mess.

**Comment by SajedHassan** [comment]
I faced a similar issue and fixed it by wrapping the `CompositeDecorator` into the `MultiDecorator` causes the `onChange` method to keep getting called causing a StackOverflow issue
as explained [here](https://github.com/draft-js-plugins/draft-js-plugins/issues/401#issuecomment-437633755)
