### ISSUE TITLE
4.0.0-beta3 Linkify Plugin not Working

### ISSUE THREAD

**Issue by HuppeJ** [draft-js-plugins/draft-js-plugins#1670]
## Environment

```
"@draft-js-plugins/editor": "^4.0.0-beta4",
"@draft-js-plugins/linkify": "^4.0.0-beta3",
"draft-js": "^0.11.7",
"react": "^16.14.0",
"react-dom": "^16.14.0",
```

## Description

New "@draft-js-plugins/linkify" doesn't work with new "@draft-js-plugins/editor".

I read all the documentation I could find and explored the code. I don't know if I'm missing something, but it seems to be a regression. 

## Reproducible Demo

Here is a reproducible demo: 

https://codesandbox.io/s/serene-spence-h51um?file=/src/App.js:325-338

**Comment by fxOne** [comment]
Looks like a race condition in draft-js: https://github.com/facebook/draft-js/issues/1507
If you remove the useEffect or change `focusEditor()` to `setTimeout(focusEditor, 0)` it works.
