### ISSUE TITLE
[draft-js-mention-plugin] When AutoCorrect turned ON in Android; plugin doesn't work

### ISSUE THREAD

**Issue by harshmaisheri** [draft-js-plugins/draft-js-plugins#1673]
## Environment
@draft-js-plugins-editor : "^3.0.0",
@draft-js-mention-plugin  : "^3.1.5",

## Description

When AutoCorrect / Smart Prediction is turn ON in Android Phones the mention plugin just doesn't works as it is in WebBrowser / IOS devices. 
Mention suggestion wont trigger unless space is given after every word but when Autocorrect is turned OFF its working perfectly fine.

## Reproducible Demo

Reproducible in Android 10 & above. 
Here's an [example that uses the mentions plugin](https://cutt.ly/dh5b7Io) - this will help get you started

**Comment by fxOne** [comment]
Draft-js does not support mobile devices: https://draftjs.org/docs/advanced-topics-issues-and-pitfalls#mobile-not-yet-supported
If the issue is located in draft-js-plugins it would be nice if you could provide a PR as I don't have an Android device to reproduce it.

**Comment by harshmaisheri** [comment]
Is there any chance of getting it fixed?

**Comment by bitbasher-dev** [comment]
@harshmaisheri did you get solution?

**Comment by harshmaisheri** [comment]
The issue still persist. As the docs itself says they don't support for mobile device.
