### ISSUE TITLE
Custom decorators are overwritten when using the draft-js-plugins-editor

### ISSUE THREAD

**Issue by adrianmc** [draft-js-plugins/draft-js-plugins#168]
It seems that whatever custom decorators I'm using will get over-written when the draft-js-plugins-editor mounts in `componentWillMount()`. 

Below is the code I am using, which is supposed to turn the text red when it is detected that it begins with a `#` symbol. If I take out the plugins prop and use the official draft-js Editor component, it works as expected, but with the draft-js-plugins-editor, it does not run my decorators at all (I've tried putting a console log inside my `hastagStrategy`).

```jsx
import React from 'react';
import {
  // Editor,
  EditorState,
  RichUtils,
  CompositeDecorator,
  convertToRaw,
} from 'draft-js';

import {hashtagStrategy, HashtagSpan} from './hashtag';

import Editor from 'draft-js-plugins-editor';
import createLinkifyPlugin from 'draft-js-linkify-plugin';
const linkifyPlugin = createLinkifyPlugin();
const plugins = [
  linkifyPlugin,
];

export default class App extends React.Component {
  constructor(props) {
    super(props);

    const decorator = new CompositeDecorator([
      {
        strategy: hashtagStrategy,
        component: HashtagSpan,
      }
    ]);

    this.state = {editorState: EditorState.createEmpty(decorator)};
    this.onChange = (editorState) => this.setState({editorState});
    this.handleKeyCommand = (command) => this._handleKeyCommand(command);
  }

  _handleKeyCommand(command) {
    const newState = RichUtils.handleKeyCommand(this.state.editorState, command);
    if (newState) {
      this.onChange(newState);
      return true;
    }
    return false;
  }

  _onBoldClick() {
    this.onChange(RichUtils.toggleInlineStyle(this.state.editorState, 'BOLD'));
  }

  _logState() {
    const content = this.state.editorState.getCurrentContent();
    console.log(convertToRaw(content));
  }

  render() {
    const {editorState} = this.state;
    return (
      <div id="content">
        <h1>Draft Editor</h1>
        <button onClick={this._onBoldClick.bind(this)}>Bold</button>
        <div className="editor">
          <Editor
            editorState={editorState}
            onChange={this.onChange}
            handleKeyCommand={this.handleKeyCommand}
            plugins={plugins}
          />
        </div>
        <button onClick={this._logState.bind(this)}>Log State</button>
      </div>
    );
  }
}
```

Here's the other file if you want to test it yourself:

```jsx
import React from 'react';

export function hashtagStrategy(contentBlock, callback) {
  const text = contentBlock.getText();
  const regex = /\#[\w\u0590-\u05ff]+/g;
  let matchArr, start;
  while ((matchArr = regex.exec(text)) !== null) {
    start = matchArr.index;
    callback(start, start + matchArr[0].length);
  }
}

export const HashtagSpan = (props) => {
  return <span {...props} style={{color: 'red'}}>{props.children}</span>;
}
```

**Comment by nikgraf** [comment]
Hey @adrianmc, thanks for letting us know! That's something we didn't do in the first version.

I'm currently working on improving the editor to allow people passing in custom decorators. I keep you posted once we have finished this and cut a new release. For now I recommend to create your own plugin which allows you do provide a decorator as well.

**Comment by adrianmc** [comment]
@nikgraf awesome. Great work btw, I'm looking to get more involved on this repo once I get a better hold of draft-js and the draft-js-plugins API. I'm excited to contribute.

**Comment by nikgraf** [comment]
Looking forward to it. Feel free to ask questions anytime :smiley:

**Comment by nikgraf** [comment]
This was solved with release of the 1.0 version.

**Comment by jgrisafe** [comment]
Hi @nikgraf this does not appear to be functioning in 2.0 beta

**Comment by gauravsoti1** [comment]
Got the same issue, my composite decorator is getting overridden because of plugins

**Comment by bbb324** [comment]
Is there have any solutions?

**Comment by rejvban** [comment]
+1 For way for custom decorators solution that does not get blown up by plugins.

**Comment by fxOne** [comment]
@rejvban can you please create an example to reproduce the issue?

**Comment by gauravsoti1** [comment]
@rejvban @bbb324 I solved the problem for myself and then wrote this article to come back to when required. See if this solves your problem: https://gauravsobti1.medium.com/draft-js-decorator-not-working-with-plugins-47c02763442a

**Comment by fxOne** [comment]
@gauravsoti1 does this solution from the FAQ does not work? https://github.com/draft-js-plugins/draft-js-plugins/blob/master/FAQ.md#how-can-i-use-custom-decorators-with-the-plugin-editor
