### ISSUE TITLE
Typing error on drag and drop uploading plugin

### ISSUE THREAD

**Issue by Silvercast** [draft-js-plugins/draft-js-plugins#1680]
## Environment

- @draft-js-plugins/editor version: latest 4.0.0-beta5
- plugin name and version: @draft-js-plugins/drag-n-drop-upload  , latest version 4.0.0-beta2

## Description

I have problem when trying to follow instructions of drag-n-drop-upload plugin in Typescript. TS compiler says incompatible typing (please check the codesandbox below). It is also nice to have a sample of mockUpload in Typescript too because the javascript example takes different inputs.

<img width="690" alt="Screenshot 2021-01-05 at 10 23 24" src="https://user-images.githubusercontent.com/998048/103631360-2a89a900-4f43-11eb-98af-219c9d8932f4.png">

## Reproducible Demo

https://codesandbox.io/s/intelligent-fog-k5nh3

**Comment by fxOne** [comment]
Yeah, I see the issue. As far as I can see the [Alignment + Resize + Focus + Drag'n'Drop + Drag'n'Drop Upload Example](https://www.draft-js-plugins.com/plugin/image) also does not work as expected. 

The types for placeholderSrc looks correct for me: https://github.com/draft-js-plugins/draft-js-plugins/blob/938fa73d902995af615485833e11fda8cf95a4da/packages/drag-n-drop-upload/src/handleDroppedFiles.ts#L51

Can you provide a fix?

**Comment by Silvercast** [comment]
I wish I could but it's hard for me at this point as I happened to find the great draft-js-plugins repo two days ago 😭
