### ISSUE TITLE
Mention keybindings not attached if initial suggestions is empty

### ISSUE THREAD

**Issue by felippepuhle** [draft-js-plugins/draft-js-plugins#1696]
## Environment

- @draft-js-plugins/editor version: 4.0.0
- @draft-js-plugins/mention version: 4.0.0

## Description

I found a bug where the workflow kinda makes sense for our project:

- Suggestion list starts as an empty array
- As soon as the user types `@` we open the suggestion list (we want to show a loading state, for example)
- Key bindings are not working (navigating using the keyboard), unless you move the cursor through the editor and open the suggestions again

Probably related to this line (I think we should remove it): https://github.com/draft-js-plugins/draft-js-plugins/blob/master/packages/mention/src/MentionSuggestions/MentionSuggestions.tsx#L216

## Reproducible Demo

https://codesandbox.io/s/draft-js-pluginsmention-dynamic-suggestion-keybindings-e6rhs

**Comment by fxOne** [comment]
I don't think that removing [`this.props.suggestions.length > 0`](https://github.com/draft-js-plugins/draft-js-plugins/blob/master/packages/mention/src/MentionSuggestions/MentionSuggestions.tsx#L216) is the right solution. Why should the dropdown be in an open state even if there are no suggestions to show? I think a better solution would be to reevaluate the dropdown open state when `this.props.suggestions` is changing.

**Comment by felippepuhle** [comment]
Yeah, but in our case, we're opening the dropdown before having the suggestions (show a loading spinner, or an empty message if no results found - that lead us into another ticket where we'd need to support a custom renderer or something like that)... 

The case is, props are kinda inconsistent... why do we need to control an open state if we're evaluating the suggestions length (it doesn't make sense too)? 

I could solve it on our side for now by doing something like `suggestions={[{ id: 'loading' }]}` or `suggestions={[{ id: 'empty' }]}`, but it's not the ideal IMO.

**Comment by fxOne** [comment]
I understand your issues. I think most of the application uses `open` and `onOpenChange` as a simple state without any logic. 

I would guess that changing suggestion to an `MentionData[] | Promise<MentionData[]>` would be to much work or didn't work?

**Comment by felippepuhle** [comment]
Yeah I agree that `open` and `onOpenChange` is better and simple, that's the reason I suggested to remove the `suggestions.length > 0` verification.

I think `Promise<MentionData[]>` wouldn't work well too, we're using Apollo and it doesn't returns a promise for us (as well as several other data fetching libs).
