### ISSUE TITLE
Linkify demo not working

### ISSUE THREAD

**Issue by 1derwood** [draft-js-plugins/draft-js-plugins#1707]
## Environment

Demo environment
Chrome 87 on Windows

## Description

None of the examples of the linkify plugin are working on the demo page. Nothing happens when entering the editor or selecting text.

## Reproducible Demo

https://www.draft-js-plugins.com/plugin/linkify

**Comment by oldtinroof** [comment]
Not sure if it's connected, but the inline-toolbar demo isn't working either: https://www.draft-js-plugins.com/plugin/inline-toolbar

**Comment by fxOne** [comment]
The `linkify` plugin is working for me. There should nothing happen if you select the text.

The issue with the `inline-toolbar` only occurs if I directly load the page. If I switch between the pages the `inline-toolbar` works fine. Looks like there is an issue with the prerendered version from next.js.
