### ISSUE TITLE
[Mention Plugin] Does not work with react-hook-form

### ISSUE THREAD

**Issue by killerbytes** [draft-js-plugins/draft-js-plugins#1728]
## Environment

- @draft-js-plugins/editor version:
- plugin name and version:

## Description
The mention plugin does not work with the [Controller](https://react-hook-form.com/api/#Controller) implementation of react-hook-form when initialized with `reset(async)` 
Probably other draft-js-plugins dont work too.

Edit: I have updated the code and added comments

## Reproducible Demo
https://codesandbox.io/s/draft-js-mention-forked-peiei?file=/src/App.js:0-2294

**Comment by fxOne** [comment]
This example worked for me: https://codesandbox.io/s/draft-js-mention-forked-44byt?file=/src/TestEditor.js
Can you please describe what does not work?

**Comment by killerbytes** [comment]
@fxOne I have updated the code. Mention does not popup when typing `@`

**Comment by fxOne** [comment]
@killerbytes what is with version I posted wrong? I have never used react-hook-form, so can please explain the issue a little bit deeper for me?

**Comment by killerbytes** [comment]
Sorry, I chose a different route
