### ISSUE TITLE
Mention plugin `entryComponent` prop is ignored 

### ISSUE THREAD

**Issue by killerbytes** [draft-js-plugins/draft-js-plugins#1736]
## Environment

- @draft-js-plugins/editor version: 4.1.0
- plugin name and version: 4.1.0

## Description

`entryComponent` prop is ignored
```
 <MentionSuggestions
    ...
    entryComponent={Entry}
  />
```
But works on the `config`
```
const mentionPlugin = createMentionPlugin({
  ...
  entryComponent: Entry
});
```
## Reproducible Demo

`entryComponent` as props:
https://codesandbox.io/s/brave-haze-qkx6c?file=/src/App.js

`entryComponent` as config:
https://codesandbox.io/s/fervent-williams-05tui?file=/src/App.js:1451-1637

**Comment by fxOne** [comment]
Fixed in [@draft-js-plugins/mentions@4.2.0](https://www.npmjs.com/package/@draft-js-plugins/mention)
