### ISSUE TITLE
Extending Linkify with prefix and target config settings

### ISSUE THREAD

**Issue by adrianmc** [draft-js-plugins/draft-js-plugins#174]
I wanted to get a better idea of how to contribute to a plugin so I decided to try to implement prefixes and target attributes to the Linkify plugin. Users will call the plugin like this:

```js
const linkifyPlugin = createLinkifyPlugin({
  prefix: 'http://',
  target: '_blank',
});
```

And the plugin will check to see if the href already begins with the prefix. If it does not, it will be added onto the front. Also, the target is set to whatever the user has chosen, otherwise it is null.

This is my rough first attempt. I know I'll need to clean it all up before submitting it for a pull request. I guess I'm just posting here to get some feedback on how I should refactor this since there doesn't yet seem to be a "dev conventions" guide written out.

Have a look at my commit here: https://github.com/adrianmc/draft-js-plugins/commit/2ea2413958c0d414ef34059b3c74d9173b145c54

Thanks!

**Comment by nikgraf** [comment]
You changes look really good! I didn't even notice that http was missing before …

Two suggestions:

- by default the config for target should be '_self' (I thought about _blank, but matching the default behaviour of links is probably better to avoid confusion!
- by default the config for prefix should be 'http://'

both defaults can be set here: https://github.com/adrianmc/draft-js-plugins/commit/2ea2413958c0d414ef34059b3c74d9173b145c54#diff-2cd4a092a2a5a7cc5222f02ac1d3612fR19

This will get a good version out of the box, but will be able to configure it by themselves.

Definitely open a PR …

P.S: How should a dev conventions guide look like? What would you expect in there?

**Comment by adrianmc** [comment]
@nikgraf

Great!

Regarding dev conventions, I just wasn't sure if some of the stuff I was doing was "kosher". For example, I wasn't sure that I could piggyback onto the config object since it originally only carried the theme information. I also re-wrote the eslint disabling comments as well as reformatted the props destructuring vertically. All of this stuff, I wasn't sure if I'd upset the original intent of the author.

I guess I'm pretty new to making major contributions (i.e. not simple bug fixes/typos/version bumps) to open sourced projects.

**Comment by adrianmc** [comment]
Uh oh, it seems that the Travis build has failed in my PR #175 because I used the ES2015 `startsWith()` function.

https://developer.mozilla.org/en/docs/Web/JavaScript/Reference/Global_Objects/String/startsWith

I thought that Babel will compile down automatically?

**Comment by nikgraf** [comment]
Ok, good to know. Usually extending with new configuration is not an issue. Especially when it adds value like in your case. Taking something away or renaming it is a bit tricker as it should result in a new major release. Nevertheless anytime you have an idea for improvements I think you should bring it up. The earlier breaking changes happen the better. Often it makes sense to accumulate the and release them together with a new major version.
