### ISSUE TITLE
DraftJS Emoji/Mention Plugin - double-space on Mac ("Add full stop with double-space")

### ISSUE THREAD

**Issue by lukasMega** [draft-js-plugins/draft-js-plugins#1740]
## Environment

OS: Mac OS (I'm using Mac OS Catalina 10.15.7)
Plugin: https://www.draft-js-plugins.com/plugin/emoji

## Description

> The default keyboard settings on modern Mac OS versions include a shortcut for typing periods quickly. This means that hitting the spacebar twice will insert a period automatically at the end of a sentence or word.

<img width="780" alt="Screen 2021-01-29 at 08 04 57" src="https://user-images.githubusercontent.com/2448004/106242983-d784d800-6208-11eb-8f99-697c99a655d0.png">

## Reproducible Demo

**Steps to reproduce:**

- open https://www.draft-js-plugins.com/plugin/emoji and navigate to **Simple Emoji Example**
- make textarea empty, insert emoji
- make sure cursor is immediately after emoji (no space between emoji and cursor)
- press space 2x quickly (now cursor may disappear)
  - press ENTER or some characters... 💥 ERROR!
  - expected state of textarea: "\<emoji\>. \<cursor\>"

https://user-images.githubusercontent.com/2448004/106242498-11a1aa00-6208-11eb-97dd-92a1d9dcf43d.mov

NOTE: it's not reproducible on https://draftjs.org/
It's without problems here:

https://user-images.githubusercontent.com/2448004/106243182-35b1bb00-6209-11eb-94bf-a967098475fe.mov

**Comment by fxOne** [comment]
Looks like the as in https://github.com/draft-js-plugins/draft-js-plugins/issues/1697

**Comment by lukasMega** [comment]
Also reproducible with mention plugin:


https://user-images.githubusercontent.com/2448004/106245882-89be9e80-620d-11eb-9d05-0db7511769cc.mov

**Comment by fxOne** [comment]
As I have just updated the homepage and no access to a Mac can you please check if the issues are still there?

**Comment by lukasMega** [comment]
yes, unfortunately the issue is still here

**Comment by fxOne** [comment]
As I don't have access to a Mac can you provide a PR or explain me how I can reproduce it on Windows?

**Comment by lukasMega** [comment]
Sure, I will try.

**Comment by lukasMega** [comment]
Unfortunately I can not reproduce it on Windows

**Comment by lukasMega** [comment]
Unfortunately I can still reproduce this issue.

**Comment by fxOne** [comment]
@lukasMega as I already said, it would be nice if you can have a look at it as I have no access to Mac to reproduce this issue.

**Comment by fxOne** [comment]
It looks like it is a `draft-js` issue so the fix need to be done there: https://github.com/facebook/draft-js/issues/2422
