### ISSUE TITLE
Cannot clone on windows

### ISSUE THREAD

**Issue by vas85** [draft-js-plugins/draft-js-plugins#1743]
## Environment
Windows development environment

## Description
Within this path in the repo: https://github.com/draft-js-plugins/draft-js-plugins/tree/master/packages/mention/src

There is a folder that contains a forward slash: 'Mention/__test__'

Windows does not allow folders to contain slashes this way.

The simplest fix is to just create an extra folder 'Mention' and nest '__test__' under it

## Reproducible Demo
1. Use windows as your OS using standard platform specific git binaries
2. clone draft-js-plugs
`git clone https://github.com/draft-js-plugins/draft-js-plugins.git`

*Expected*
Clone to succeed.

*Actual*
Clone fails with the following error:
`error: Invalid path 'packages/mention/src/Mention/__test__/Mention.test.tsx\'`

**Comment by vas85** [comment]
@fxOne can you please take a look?

@fancykingstar and I are both running into this

**Comment by fxOne** [comment]
@vas85 can you check if it now works?

**Comment by vas85** [comment]
Works now. Thanks @fxOne
