### ISSUE TITLE
Link plugin (anchor) decorators not working

### ISSUE THREAD

**Issue by supasus** [draft-js-plugins/draft-js-plugins#1768]
Hi,

I'm using custom decorators with draft.js and now my links don't have any styles on them. They stop working when I am using EditorState.createWithContent(content, myCustomDecorator)

How would I go about fixing this while still keeping my decorators?

**Comment by fxOne** [comment]
Please have a look at the FAQ: https://github.com/draft-js-plugins/draft-js-plugins/blob/master/FAQ.md#how-can-i-use-custom-decorators-with-the-plugin-editor

**Comment by supasus** [comment]
I don't have any problems with my decorators. It's just that the Anchor plugin's decorators stop working once I create a state with content and my decorators in it. I tried using the push method to no avail.

**Comment by fxOne** [comment]
Maybe you can give a https://codesandbox.io example?

**Comment by chrisrobbins** [comment]
@supasus Did you figure this out? I am currently having the same issue. I am applying the decorators via custom decorator object and passing it to the draft-js-plugins-editor prop `decorators` and I have the plugins all configured. My strategy is being called, but the decorator component is never being called.  

**Decorator Strategy and Component**
`import { ContentBlock, ContentState } from 'draft-js';

type Decorator = {
  contentState: ContentState;
  entityKey: string;
  children: string;
};

export default function strategy(
  block: ContentBlock,
  callback: (start: number, end: number) => void,
  contentState: ContentState,
) {
  block.findEntityRanges(character => {
    const entityKey = character.getEntity();
    return (
      entityKey !== null &&
      contentState.getEntity(entityKey).getType() === 'LINK'
    );
  }, callback);
}

export const LinkDecorator = ({
  contentState,
  entityKey,
  children,
  ...props
}: Decorator) => {
  const { url } = contentState.getEntity(entityKey).getData();
  console.log('This is not being called', { url });

  return (
    <a href={url} className="nav-link" {...props}>
      {children}
    </a>
  );
};
`
**Link Plugin**
`import { EditorPlugin } from '@draft-js-plugins/editor';
import { ComponentType } from 'react';

import LinkButton, { HyperlinkButtonProps } from './components/HyperlinkButton';

export type AnchorPlugin = EditorPlugin & {
  LinkButton: ComponentType<HyperlinkButtonProps>;
};

export default (): AnchorPlugin => {
  return {
    LinkButton,
  };
};
`
**Link Button for toolbar**
`import { Dispatch, MouseEvent, SetStateAction } from 'react';

export type HyperlinkButtonProps = {
  setIsLinkModalVisible: Dispatch<SetStateAction<boolean>>;
};

const HyperlinkButton = ({ setIsLinkModalVisible }: HyperlinkButtonProps) => {
  return (
    <button
      type="button"
      aria-label="Hyperlink"
      tabIndex={-1}
      onMouseDown={(event: MouseEvent) => {
        event.preventDefault();
        setIsLinkModalVisible(true);
      }}
    >
      <i className="fa fa-link" aria-hidden="true" />
    </button>
  );
};

export default HyperlinkButton;
`
**Editor**
`const RichTextField = ({
  value,
  id,
  isFocused,
  setIsFocused,
  placeholder,
  onSave,
  onChange,
  showEmojiButton,
}: Props) => {
  const [editorState, setEditorState] = useState(() =>
    createEditorStateWithText(value),
  );
  
   const customDecorators = [
    {
      strategy: linkStrategy,
      component: LinkDecorator,
    },
  ];
  
  const staticToolbarPlugin = useMemo(
    () =>
      createToolbarPlugin({
        theme: {
          buttonStyles: {
            buttonWrapper: 'u-mr-4',
            button: editorStyles.editorToolbarButton,
            active: editorStyles.editorToolbarButton_active,
          },
          toolbarStyles: {
            toolbar: 'd-flex border border-top-0 rounded-bottom u-p-8',
          },
        },
      }),
    [],
  );

  const { Toolbar } = staticToolbarPlugin;
  // const AttachmentPlugin = createAttachmentPlugin();
  // const { AttachmentButton } = AttachmentPlugin;
  const linkPlugin = createLinkPlugin();
  const { LinkButton } = linkPlugin;
  const plugins = [
    staticToolbarPlugin,
    linkPlugin,
    { decorators: customDecorators },
  ];
  
  function onAddLink(link: string) {
    const contentState = editorState
      .getCurrentContent()
      .createEntity('LINK', 'MUTABLE', { link });
    const entityKey = contentState.getLastCreatedEntityKey();
    const withLink = RichUtils.toggleLink(
      editorState,
      editorState.getSelection(),
      entityKey,
    );
    return handleChange(
      EditorState.forceSelection(withLink, editorState.getSelection()),
    );
  }
  
  <Editor
          onFocus={() => setIsFocused(true)}
          placeholder={placeholder}
          ref={editor}
          onBlur={() => {
            const markdownString = draftToMarkdownWrapper(editorState);
            onSave(markdownString);

            return setIsFocused(false);
          }}
          editorState={editorState}
          onChange={handleChange}
          plugins={plugins}
          decorators={customDecorators}
        />
  `

**Comment by supasus** [comment]
> @supasus Did you figure this out? I am currently having the same issue. I am applying the decorators via custom decorator object and passing it to the draft-js-plugins-editor prop `decorators` and I have the plugins all configured. My strategy is being called, but the decorator component is never being called.
> 
> **Decorator Strategy and Component**
> 
> ```
> import { ContentBlock, ContentState } from 'draft-js';
> 
> type Decorator = {
>   contentState: ContentState;
>   entityKey: string;
>   children: string;
> };
> 
> export default function strategy(
>   block: ContentBlock,
>   callback: (start: number, end: number) => void,
>   contentState: ContentState,
> ) {
>   block.findEntityRanges(character => {
>     const entityKey = character.getEntity();
>     return (
>       entityKey !== null &&
>       contentState.getEntity(entityKey).getType() === 'LINK'
>     );
>   }, callback);
> }
> 
> export const LinkDecorator = ({
>   contentState,
>   entityKey,
>   children,
>   ...props
> }: Decorator) => {
>   const { url } = contentState.getEntity(entityKey).getData();
>   console.log('This is not being called', { url });
> 
>   return (
>     <a href={url} className="nav-link" {...props}>
>       {children}
>     </a>
>   );
> };
> ```
> 
> **Link Plugin**
> 
> ```
> import { EditorPlugin } from '@draft-js-plugins/editor';
> import { ComponentType } from 'react';
> 
> import LinkButton, { HyperlinkButtonProps } from './components/HyperlinkButton';
> 
> export type AnchorPlugin = EditorPlugin & {
>   LinkButton: ComponentType<HyperlinkButtonProps>;
> };
> 
> export default (): AnchorPlugin => {
>   return {
>     LinkButton,
>   };
> };
> ```
> 
> **Link Button for toolbar**
> 
> ```
> import { Dispatch, MouseEvent, SetStateAction } from 'react';
> 
> export type HyperlinkButtonProps = {
>   setIsLinkModalVisible: Dispatch<SetStateAction<boolean>>;
> };
> 
> const HyperlinkButton = ({ setIsLinkModalVisible }: HyperlinkButtonProps) => {
>   return (
>     <button
>       type="button"
>       aria-label="Hyperlink"
>       tabIndex={-1}
>       onMouseDown={(event: MouseEvent) => {
>         event.preventDefault();
>         setIsLinkModalVisible(true);
>       }}
>     >
>       <i className="fa fa-link" aria-hidden="true" />
>     </button>
>   );
> };
> 
> export default HyperlinkButton;
> ```
> 
> **Editor**
> 
> ```
> const RichTextField = ({
>   value,
>   id,
>   isFocused,
>   setIsFocused,
>   placeholder,
>   onSave,
>   onChange,
>   showEmojiButton,
> }: Props) => {
>   const [editorState, setEditorState] = useState(() =>
>     createEditorStateWithText(value),
>   );
>   
>    const customDecorators = [
>     {
>       strategy: linkStrategy,
>       component: LinkDecorator,
>     },
>   ];
>   
>   const staticToolbarPlugin = useMemo(
>     () =>
>       createToolbarPlugin({
>         theme: {
>           buttonStyles: {
>             buttonWrapper: 'u-mr-4',
>             button: editorStyles.editorToolbarButton,
>             active: editorStyles.editorToolbarButton_active,
>           },
>           toolbarStyles: {
>             toolbar: 'd-flex border border-top-0 rounded-bottom u-p-8',
>           },
>         },
>       }),
>     [],
>   );
> 
>   const { Toolbar } = staticToolbarPlugin;
>   // const AttachmentPlugin = createAttachmentPlugin();
>   // const { AttachmentButton } = AttachmentPlugin;
>   const linkPlugin = createLinkPlugin();
>   const { LinkButton } = linkPlugin;
>   const plugins = [
>     staticToolbarPlugin,
>     linkPlugin,
>     { decorators: customDecorators },
>   ];
>   
>   function onAddLink(link: string) {
>     const contentState = editorState
>       .getCurrentContent()
>       .createEntity('LINK', 'MUTABLE', { link });
>     const entityKey = contentState.getLastCreatedEntityKey();
>     const withLink = RichUtils.toggleLink(
>       editorState,
>       editorState.getSelection(),
>       entityKey,
>     );
>     return handleChange(
>       EditorState.forceSelection(withLink, editorState.getSelection()),
>     );
>   }
>   
>   <Editor
>           onFocus={() => setIsFocused(true)}
>           placeholder={placeholder}
>           ref={editor}
>           onBlur={() => {
>             const markdownString = draftToMarkdownWrapper(editorState);
>             onSave(markdownString);
> 
>             return setIsFocused(false);
>           }}
>           editorState={editorState}
>           onChange={handleChange}
>           plugins={plugins}
>           decorators={customDecorators}
>         />
> ```

```
const getMarkdownState = (currentState, string, decorator) => {
  const rawData = markdownToDraft(string, {
    preserveNewlines: true,
    blockStyles: {
      ins_open: "UNDERLINE",
    },
    remarkableOptions: {
      enable: {
        inline: "ins",
      },
    },
  });
  const contentState = convertFromRaw(rawData);
  const newEditorState = EditorState.push(currentState, contentState);
  return newEditorState;
};

const TextContent = ({
  state = { data: "" },
  update,
  type = "/default",
  id,
  typographDecorator,
  splitBlock,
  canSplit = false,
  containerStyles = {},
  className,
}) => {
  const [editorState, setEditorState] = useState(
    getMarkdownState(
      typographDecorator
        ? EditorState.createEmpty(typographDecorator)
        : EditorState.createEmpty(),
      state.data
    )
  );
  const [markDownState, setmarkDownState] = useState(state.data);

  const [{ plugins, InlineToolbar, linkPlugin }] = useState(() => {
    const linkPlugin = createLinkPlugin({
      placeholder: "Начните писать ссылку и нажмите ENTER",
    });
    const inlineToolbarPlugin = createInlineToolbarPlugin({});
    const { InlineToolbar } = inlineToolbarPlugin;
    const plugins = [inlineToolbarPlugin, linkPlugin];
    return {
      plugins,
      InlineToolbar,
      linkPlugin,
    };
  });
  
  const editorRef = useRef(null);

  const onEditorStateChange = (newEditorState) => {
    setEditorState(newEditorState);
  };

 
  return (
    <div style={containerStyles} className={className}>
      <div
        className="editor"
        id={`${type}-block`}
        onClick={() => editorRef.current && editorRef.current.focus()}
      >
        <Editor
          editorState={editorState}
          onChange={onEditorStateChange}
          plugins={plugins}
          ref={(editor) => (editorRef.current = editor)}
          decorators={typographDecorator ? [typographDecorator] : null}
          blockStyleFn={customBlockStyles}
          handleKeyCommand={handleSplitCommand}
          handlePastedText={handlePastedText}
          keyBindingFn={splitBindingFn}
          handleReturn={handleReturn}
        />
        <InlineToolbar>
          {(externalProps) => (
            <div>
              <BoldButton {...externalProps} />
              <ItalicButton {...externalProps} />
              <UnderlineButton {...externalProps} />
              <linkPlugin.LinkButton {...externalProps} />
              <HeadlineOneButton {...externalProps} />
              <HeadlineTwoButton {...externalProps} />
              <HeadlineThreeButton {...externalProps} />
              <HeadlineFourButton {...externalProps} />
              <UnorderedListButton {...externalProps} />
              <OrderedListButton {...externalProps} />
              {/* <DraftBubbleButton {...externalProps} /> */}
            </div>
          )}
        </InlineToolbar>
      </div>
    </div>
  );
};


```


Hi, i did manage to get find a fix. The code's a bit rough, but you could get some ideas out of it. Looking at your code I would guess you have to insert a decorator as follows: ```createEditorStateWithText(value, decorator) ```. Are you using only one instance of the editor on your page?

**Comment by chrisrobbins** [comment]
@supasus Not quite. I built a custom decorator array and passed that into `compositeDecorator`, then initialised the state with `EditorState.createWithContent`  which takes the decorator as an argument. That did the trick.

**Comment by supasus** [comment]
> @supasus Not quite. I built a custom decorator array and passed that into `compositeDecorator`, then initialised the state with `EditorState.createWithContent` which takes the decorator as an argument. That did the trick.

You should probably share your solution here. What regex did you use?

**Comment by kseikyo** [comment]
Any updates on this bug?

I was using the [linkify plugin](https://www.draft-js-plugins.com/plugin/linkify) without any trouble.

But after having to update the state of the `EditorState` as I'm fetching data from the backend, the links no longer get detected.

Here's a [codesandbox](https://codesandbox.io/s/draft-js-plugins-linkify-bug-3xk7z) reproducing the bug.

**Comment by fxOne** [comment]
@kseikyo thats because you are overriding the `EditorState` from the plugins with a new one in the `useEffect`. It should work fine if you move it into a function to create the `EditorState` in `useState`.

**Comment by kseikyo** [comment]
> fine if you move it into a function to create t



> @kseikyo thats because you are overriding the `EditorState` from the plugins with a new one in the `useEffect`. It should work fine if you move it into a function to create the `EditorState` in `useState`.

I'm not sure what you mean by _move it into a function to create the `EditorState` in `useState`_.

Are you saying to use the `state` created in the `useEffect` inside the `setState` and push to it. Or is it creating a function that will set the state with the `EditorState`, e.g.,
```js
const updateState = (newState) => {
    setState(EditorState.push(state, newState);
}
```

**Comment by fxOne** [comment]
I mean for example:
```js
const [state, setState] = useState(() => {
 //create editor state with content here
});
```

**Comment by kouohhashi** [comment]
Hi, I have similar issue.
Have you found how to re-apply linkify plugin manually?
