### ISSUE TITLE
Mention plugin is missing input value in CompositionEnd

### ISSUE THREAD

**Issue by yongningfu** [draft-js-plugins/draft-js-plugins#1769]
## Environment

- @draft-js-plugins/editor version: 4.1.0
- plugin name and version:  @draft-js-plugins/mention 4.2.0

## Reproducible Demo
https://user-images.githubusercontent.com/9846613/106443738-d1685300-64b7-11eb-87c0-dd552d6271d3.mov

**Comment by yongningfu** [comment]
#1752

**Comment by fxOne** [comment]
Can you please explain how I can test it? I have only a normal keyboard.

**Comment by yongningfu** [comment]
> Can you please explain how I can test it? I have only a normal keyboard.

https://developer.mozilla.org/en-US/docs/Web/API/Element/compositionend_event

The compositionend event needs to be triggered to reproduce


![image](https://user-images.githubusercontent.com/9846613/106982356-e9cdbb80-679e-11eb-8174-036479aea866.png)




https://user-images.githubusercontent.com/9846613/106982850-d2430280-679f-11eb-8c7e-4a46503aa280.mov

**Comment by fxOne** [comment]
Do you have a solution for non MacOS users?

**Comment by yongningfu** [comment]
> Do you have a solution for non MacOS users?

This bug is related to the compositionend event and has nothing to do with the operating system

**Comment by fxOne** [comment]
> > Do you have a solution for non MacOS users?
> 
> This bug is related to the compositionend event and has nothing to do with the operating system

I asked you to show me a way to reproduce the issue and your link gives me only a solution MacOS. So I still need a way to reproduce this issue on my Windows PC with my german keyboard layout.

**Comment by yongningfu** [comment]
> > > Do you have a solution for non MacOS users?
> > 
> > 
> > This bug is related to the compositionend event and has nothing to do with the operating system
> 
> I asked you to show me a way to reproduce the issue and your link gives me only a solution MacOS. So I still need a way to reproduce this issue on my Windows PC with my german keyboard layout.

got it , i did not find the solution to reproduce on window, You can refer to this issue [ https://github.com/facebook/draft-js/issues/2788](url)

**Comment by yongningfu** [comment]
Has there been any progress on this issue?

**Comment by fxOne** [comment]
I'm waiting for feedback from someone with a mac. I may take a few more days as he has a lot to do.
