### ISSUE TITLE
[Mention Plugin] Moving text cursor before trigger causes it to use preceding characters for search

### ISSUE THREAD

**Issue by soandrew** [draft-js-plugins/draft-js-plugins#1772]
## Environment
- @draft-js-plugins/editor@4.1.0
- @draft-js-plugins/mention@4.2.0

## Description

Bug: After triggering the mentions popup, moving the text cursor (using arrow keys or mouse) before the trigger character causes the search value to be everything before the trigger character. This can be seen in the live demo where the popup does not close if the preceding text just so happens to match a mention name.

Expected behaviour: If the text cursor is moved to before the trigger character I would expect the new search value to be empty string and the new open value to be false (i.e. from `onSearchChange` and `onOpenChange`)

## Reproducible Demo
![2021-02-07-20-36-14](https://user-images.githubusercontent.com/15936962/107168691-feba7280-6989-11eb-859c-3bf649974bc4.gif)
Note that the search value becomes `'matthew '` which is why it matches the mention with name `'Matthew Russell'`

**Comment by fxOne** [comment]
I can reproduce the error if the cursor is just before the trigger as the RegExp also machtes the [whitespace](https://github.com/draft-js-plugins/draft-js-plugins/blob/ea06a64634580423f09c168788fde7ba6886aa34/packages/mention/src/mentionSuggestionsStrategy.ts#L48).
I cannot reproduce the issue that the MentionSuggestions are still visible if your cursor is inside `matthew`. What browser are you using?

**Comment by soandrew** [comment]
Thanks for replying so quick! I'm using Chrome v87.0.4280.141 on a Windows 10 64-bit OS if that helps.
