### ISSUE TITLE
 Unknown DraftEntity key: null when I focus the image and click space bar

### ISSUE THREAD

**Issue by ricardomalagon** [draft-js-plugins/draft-js-plugins#1779]
At the moment of insert an image when you click the image and the image is focused if I click the space bar it returns **Unknown DraftEntity key: null.**

<img width="993" alt="Screen Shot 2021-02-09 at 11 42 51 AM" src="https://user-images.githubusercontent.com/19271573/107388208-f66a5080-6acb-11eb-9213-70e95bbffed3.png">

**This is the function I have to insert the image**

```
function addImage(url: string) {
    const contentState = editorState.getCurrentContent();
    const contentStateWithEntity = contentState.createEntity(
      "image",
      "IMMUTABLE",
      { src: url },
    );

    const entityKey = contentStateWithEntity.getLastCreatedEntityKey();

    const newEditorState = EditorState.set(editorState, {
      currentContent: contentStateWithEntity,
    });

    setEditorState &&
      setEditorState(
        AtomicBlockUtils.insertAtomicBlock(newEditorState, entityKey, " "),
      );
  }
```

**any help?**

**Comment by fxOne** [comment]
Can you please add a https://codesandbox.io example so that i can see the whole code. In the callstack is also the draft-js-video-plugin where I have no idea what it have to do with the issue as you are talking about images.

**Comment by ricardomalagon** [comment]
@fxOne I already found the solution, thanks anyway for taking the help into consideration.

**Comment by chuahyimei** [comment]
Hi @ricardomalagon, I'm facing the same issue. I tried to fix it by removing the <figure> tag but it seems like not working. Can you share me with the solution? Thank you.
