### ISSUE TITLE
Use https://github.com/okonet/lint-staged to lint before committing

### ISSUE THREAD

**Issue by okonet** [draft-js-plugins/draft-js-plugins#178]
Consider using https://github.com/okonet/lint-staged before committing changes

**Comment by nikgraf** [comment]
@okonet sure, can you set up stylelint in a separate PR + fixes and afterwards introduce it with stylelint + eslint + jscs + flow.

**Comment by okonet** [comment]
Sure, I'll try to do it this week. I'm in pre-launch ATM 😅

**Comment by okonet** [comment]
BTW we are you using JSCS along with ESLint? I found the ESLint can handle all the code style checks as well.

**Comment by nikgraf** [comment]
did that change recently? Even 2 weeks ago I still run into things that are not covered by ESLint. Can't remember which one though :crying_cat_face:

**Comment by okonet** [comment]
I switched a long time ago (tired fighting with babel and JSCS inconsistencies) and never regret it. There are a few very minor features missing in ESLint, but having less dependencies and faster linting time was more important for me.

**Comment by nikgraf** [comment]
Airbnb luckily support both at the same time :smile:

**Comment by nikgraf** [comment]
@okonet does lint-staged support jscs & flow?

**Comment by okonet** [comment]
No, but it is rather easy to add. I'll give it a try and do a PR.

**Comment by nikgraf** [comment]
super cool, thx @okonet
