### ISSUE TITLE
Getting issue while using the updating the plugin from @draft-js-plugin-editor to @draft-js-plugin/editor

### ISSUE THREAD

**Issue by manish-upadhyay-ucc** [draft-js-plugins/draft-js-plugins#1782]
<img width="1304" alt="Screenshot 2021-02-11 at 1 35 07 PM" src="https://user-images.githubusercontent.com/72435174/107613513-77f9e400-6c6e-11eb-8769-ee8133e58e35.png">
## Environment

- @draft-js-plugins/editor version:4.1.0

## Not able to build and getting above issue as mentioned.

I am getting above mentioned issue plus and not able to pass in below props to plugin editor
placeholder= 'some text'
          readOnly={this.props.readonly} 
          handleReturn={this.returnHandler}
          handleKeyCommand={this.handlePartialDeleteOfNotes}
          blockStyleFn={this.addNoteStyle}
          blockRendererFn={myBlockRenderer}
          handlePastedText={this.handlePastedTextHandler}
          customStyleMap={customStyleMap}

**Comment by fxOne** [comment]
Can you add an example or try to find the field which causes the issue? Looks like TypeScripts error message is in this case a bit wired. The `PluginEditorProps` are simply extending the `draft-js EditorProps`: https://github.com/draft-js-plugins/draft-js-plugins/blob/f2a0ee49e0ae223524e63024733c52dc8140d9ce/packages/editor/src/Editor/index.tsx#L23

**Comment by manish-upadhyay-ucc** [comment]
> Can you add an example or try to find the field which causes the issue? Looks like TypeScripts error message is in this case a bit wired. The `PluginEditorProps` are simply extending the `draft-js EditorProps`:
> 
> https://github.com/draft-js-plugins/draft-js-plugins/blob/f2a0ee49e0ae223524e63024733c52dc8140d9ce/packages/editor/src/Editor/index.tsx#L23
**The `PluginEditorProps` are simply extending the `draft-js EditorProps`**:  This is what i checked and couldn't get it why such issue is appearing. Which i will check later but main issue is with below pointers

@draft-js-plugins/editor/lib/index.d.ts(8,1):  **Declaration or statement expected.**
@draft-js-plugins/editor/lib/index.d.ts(8,13):  **Declaration or statement expected.**
@draft-js-plugins/editor/lib/index.d.ts(8,40):  **Declaration or statement expected.**

**Comment by fxOne** [comment]
What TypeScript Version do you use?

**Comment by manish-upadhyay-ucc** [comment]
> What TypeScript Version do you use?

There was old typescript version present under project 3.4.1 and when i updated to 4.0.0 things started working.
Thank you!

**Comment by fxOne** [comment]
`export type` was added with TypeScript 3.8: https://www.typescriptlang.org/docs/handbook/release-notes/typescript-3-8.html

**Comment by fxOne** [comment]
@manish-upadhyay-ucc is this issue now solved for you?
