### ISSUE TITLE
REOPEN: Support click for 'hashtag' and 'mention' plugin

### ISSUE THREAD

**Issue by DevAngsy** [draft-js-plugins/draft-js-plugins#1811]
refer to https://github.com/draft-js-plugins/draft-js-plugins/issues/1592

**Comment by fxOne** [comment]
I have added a `hashtagComponent` parameter to the hashtag plugin config. AS you are mentioning the mention plugin here do you want something else, too?

**Comment by DevAngsy** [comment]
The mention plugin has "mentionComponent".
The hashtag plugin has "hashtagComponent".

Thanks for your contribution.
