### ISSUE TITLE
[draft-js-focus-plugin] Simultaneous focus on images in two active text editors

### ISSUE THREAD

**Issue by ShanhinPavel** [draft-js-plugins/draft-js-plugins#1818]
## Environment
 "draft-js": "0.11.7",
 "draft-js-focus-plugin": "2.2.0",
## Description
When switching between two active text editors, the focus on the picture does not disappear.

## Reproducible Demo
###Steps:
1. Add two text editors near each other.
2. Select right text editor 
3. Add picture to it.
4. Select left text editor
5. Add picture to it.
6. Focus on the picture in the editor by mouse.
7. Move to another editor and do step 6.

Actual result: 
Focus on the left picture doesn't disappear.

Expect result: 
The focus on the left image will disappear.

![image](https://user-images.githubusercontent.com/36544060/108695778-be263180-7511-11eb-8fbc-33a902077158.png)

**Comment by Dremuchev** [comment]
We have the same problem.
