### ISSUE TITLE
Module not found: Error: Can't resolve '../../

### ISSUE THREAD

**Issue by Tasarinan** [draft-js-plugins/draft-js-plugins#1821]
## Environment

- @draft-js-plugins/editor version:
- plugin name and version:

## Description
import Editor, { createEditorStateWithText, composeDecorators } from '@draft-js-plugins/editor';

when I use import editor, but after webpack parse, it shows the following error. seem it always parse @ to ../../
how to solve this issue?
Module not found: Error: Can't resolve '../../draft-js-plugins/editor'

**Comment by fxOne** [comment]
Looks like a configuration issue with webpack. Maybe you should ask for help there as I have no idea what the issue could be.
