### ISSUE TITLE
[Mention Plugin] mention search can not input chinese

### ISSUE THREAD

**Issue by guoguo0202** [draft-js-plugins/draft-js-plugins#1841]
## Environment

- @draft-js-plugins/editor version:4.1.0
- @draft-js-plugins/mention:4.2.0

## Description

mention search can not input chinese, and will cause editor can't work

## Reproducible Demo

![屏幕录制2021-02-24 下午6 04 09](https://user-images.githubusercontent.com/24495135/108987274-0e49f300-76ce-11eb-859d-f32a498a8d26.gif)

![image](https://user-images.githubusercontent.com/24495135/108986940-ad221f80-76cd-11eb-9723-cbf29931c7c2.png)

**Comment by fxOne** [comment]
I have released a new version of the website as I think the issue might have been solved in #1697 but wasn't released. Can you please check it again?

If you still get the error can you please provide a PR as I don't have any knowledge of Chinese characters and the keyboard variante?

**Comment by DevAngsy** [comment]
thanks

**Comment by DevAngsy** [comment]
Thanks very much!
