### ISSUE TITLE
Launch Multi Mention Trigger Feature

### ISSUE THREAD

**Issue by fancykingstar** [draft-js-plugins/draft-js-plugins#1856]
Hi @fxOne 
Would you let me know when Multi Mention Trigger Feature is launched?

Thanks.

**Comment by fxOne** [comment]
It was yesterday: https://www.npmjs.com/package/@draft-js-plugins/mention

**Comment by fancykingstar** [comment]
I saw new version was published 19 hours ago.
However, I am not able to find multi mention trigger feature in new
version, even though that feature is github.

Does it take some time to be published?

Thanks. Regards

**Comment by fxOne** [comment]
I checked it locally and can find at least `mentionTrigger?: string | string[];` in the `index.d.ts`. Did you checkt that you have Version `4.3.0`?

**Comment by fancykingstar** [comment]
I can see the updates now.

I think it took some time. :)
Thank  you.
