### ISSUE TITLE
handleReturn / onkeyUp - Get the editor value to submit it?

### ISSUE THREAD

**Issue by tleunen** [draft-js-plugins/draft-js-plugins#186]
How can we register a handleReturn or onKeyUp event to eventually get the text from the editor and submit it?

I tried to use `handleReturn` as described in the draft.js doc, but I don't receive any event.

**Comment by nikgraf** [comment]
Hey @tleunen, can you share an example of your plugin so I can reproduce it? `handleReturn` should work, but you might have discovered a bug

**Comment by tleunen** [comment]
The plugin I use is the mention plugin, and it's basically the same code as the example on the website.

**Comment by nikgraf** [comment]
@tleunen I'm not sure how to help you here. `handleReturn` works for mentions & emojis. I'm currently refactoring the mentions plugin & `handleReturn` works there

**Comment by tleunen** [comment]
Hmmm..
```jsx
<Editor
    editorState={editorState}
    onChange={this.handleChange}
    handleReturn={e => console.log(e)}
    plugins={plugins}
    ref="editor"
/>
```
I don't have any log of my "return" key.

**Comment by nikgraf** [comment]
@tleunen just figured out what's going on

The version currently published didn't implement this yet. see https://github.com/draft-js-plugins/draft-js-plugins/blob/979e9c2a3a0466ebd2abad6955fd1f975e86e688/draft-js-plugins-editor/src/Editor/index.js#L162

We are going to release a new version (1.0.0) next Tuesday or Wednesday that will have a ton of improvements including handleReturn

**Comment by nikgraf** [comment]
@tleunen you now can try 1.0.0-beta1 which has this fix 😄

**Comment by tleunen** [comment]
Thanks ;)
