### ISSUE TITLE
This trick doesnt work on iphone and ipads

### ISSUE THREAD

**Issue by ali-718** [draft-js-plugins/draft-js-plugins#1864]
I was able to find a temporary solution to this problem by using `setTimeout` on the call to `focus`:

```setTimeout(this.editor.focus, 50)```

Strangely enough, this seems to solve the problem even if you set the timeout value to 0.

My original guess on why this works was that there is still something in the mention suggestions that is still in the process of mounting or rendering, but the parent component's `componentDidMount` should't be called until after all this is complete...so really not sure.

_Originally posted by @ryanmcclure4 in https://github.com/draft-js-plugins/draft-js-plugins/issues/800#issuecomment-315950836_

**Comment by fxOne** [comment]
Why are you opening a new issue for this?
