### ISSUE TITLE
[Buttons] props.setAlignment is not a function

### ISSUE THREAD

**Issue by nperichSYKES** [draft-js-plugins/draft-js-plugins#1869]
- @draft-js-plugins/editor version: 4.1.0
- plugin name and version: Buttons and Alignment and Inline Toolbar....newest, like 4.1.2

I noticed that the Buttons plugin now includes options for text alignment. Obviously this has been the big gap in draft plugins (and I hadn't gotten around to just adding my own version yet), so I was excited to try it out! I wasn't able to get it working though. I tried using the buttons as a child of Inline Toolbar. The error was `props.setAlignment is not a function`.

My assumption is that you need to somehow get the Alignment "decorator" to wrap it. But the Inline Toolbar plugin does not take a decorator config ([link](https://github.com/draft-js-plugins/draft-js-plugins/blob/cb421fba50bf431726b2f6b7c147617b2201e446/packages/inline-toolbar/src/index.tsx#L9))
 
This feature is not documented, so I'm probably just missing something in setting it up. If needed I can try to link a reproducible case. Otherwise, consider this issue a request to update the docs to show how to use the new alignment buttons in the Inline Toolbar. 😀

**Comment by fxOne** [comment]
The alignment buttons are designed to be used with the alignment plugin and not directly with the toolbars. Was you plan to use it to align text?

**Comment by nperichSYKES** [comment]
Ok, thanks for your response! Yes, I was hoping to use them to set alignment on text blocks.

**Comment by fxOne** [comment]
You should be able to add you own button to the toolbar with your own logic. You can find `draft-js` documentation for it here: https://draftjs.org/docs/advanced-topics-block-styling

**Comment by fxOne** [comment]
This is also a duplicated ticket of #1016
