### ISSUE TITLE
[draft-js-mention-plugin]the unicode of chinese symbols is wrong! can't mention some users

### ISSUE THREAD

**Issue by yinran100** [draft-js-plugins/draft-js-plugins#1888]
## Environment

- @draft-js-plugins/editor version: 4.3.0
- plugin name and version: draft-js-mention-plugin

## Description
the correct unicode range of chinese symbols is `'\u4e00-\u9fa5`, many common words , like ‘齐’,  is out of range 。
so ,please fix it~  [https://github.com/draft-js-plugins/draft-js-plugins/blob/master/packages/mention/src/defaultRegExp.ts](https://github.com/draft-js-plugins/draft-js-plugins/blob/master/packages/mention/src/defaultRegExp.ts)
thanks~

**Comment by fxOne** [comment]
Can you create a PR for it? Would love to merge it.
