### ISSUE TITLE
draft-js-mention-plugin@0.0.4 version is not properly build

### ISSUE THREAD

**Issue by nadimtuhin** [draft-js-plugins/draft-js-plugins#189]
I am sure that draft-js-mention-plugin@0.0.4 is not properly build. Can you please rebuild and update npm?

**Comment by nadimtuhin** [comment]
https://github.com/draft-js-plugins/draft-js-plugins/blob/master/draft-js-mention-plugin%2Fsrc%2FMentionSearch%2Findex.js#L63 the if(leave) block is not present in the build

**Comment by nikgraf** [comment]
@nadimtuhin the current master does have quite some breaking changes. We plan to release a new version 1.0.0 Tuesday or Wednesday which would include these changes. Would that work for you?

**Comment by nadimtuhin** [comment]
I have updated the built files for myself, so ok :)

**Comment by nadimtuhin** [comment]
btw we should maintain the version numbers otherwise it will confuse others like I was

**Comment by nikgraf** [comment]
@nadimtuhin what would your suggest for maintaining the version number?

**Comment by nadimtuhin** [comment]
https://github.com/draft-js-plugins/draft-js-plugins/blob/master/draft-js-mention-plugin%2Fpackage.json#L3 the version says 0.0.4
if it was 0.0.5 or something up anyone will know the npm version is outdated and can build themselves to have the latest version.

also loving your work :) thanks to you I saved a month

**Comment by nikgraf** [comment]
@nadimtuhin you already can try 1.0.0-beta1 which has this fix 😄
