### ISSUE TITLE
Disable keyboard events on MentionSuggestions mention plugin

### ISSUE THREAD

**Issue by bichotll** [draft-js-plugins/draft-js-plugins#1902]
## Describe the feature

I'd like to have the option to disable on up and down arrow keyboard events.

## Motivation

I have set up a fixed height to the dropdown and when the user moves around using the up and down arrows, the content does not scroll, losing the focus of the selected element.

## Possible implementations

A simple property disableKeyboardEvents or similar.
Either that or set up an auto-scroll feature when the user moves up and down.

**Comment by fxOne** [comment]
Can you give me a https://codesandbox.io example? To disable the key bindings to sounds somehow wrong in your case. I want to check if there are maybe other solutions.
