### ISSUE TITLE
Mention position shifted with parent in position absolute

### ISSUE THREAD

**Issue by ostno** [draft-js-plugins/draft-js-plugins#1933]
## Environment

- @draft-js-plugins/editor version: 4.3.1
- plugin name and version: 4.1.0

## Description

When the editor in the parent is in position absolute (or shifted from initial position with a margin) AND that the position is updated in some way by  ```positionSuggestions```  then the suggestions position is shifted from the same amount of space tahn the parent container is shifted. See below picture.

[https://ibb.co/2sCpDCG](https://ibb.co/2sCpDCG)

It was supposed to be fixed in https://github.com/draft-js-plugins/draft-js-plugins/pull/309 but it seems to be broken.

**Comment by fxOne** [comment]
Thanks for the report. I guess the best would be if we change the overlay to `popper.js`. I'll look at it after the Easter holidays.
