### ISSUE TITLE
Need help integrating @draft-js-plugins/mention with Draftail Editor

### ISSUE THREAD

**Issue by vmc08** [draft-js-plugins/draft-js-plugins#1944]
Hi, thanks for creating this great library but I need help integrating this with [Draftail Editor](https://www.draftail.org/).

### Library versions, if this helps

```
"@draft-js-plugins/editor": "^4.1.0",
"@draft-js-plugins/mention": "^4.3.1",
"draft-js": "^0.10.5",
"draftail": "^1.3.0",
```
have to use 0.10.5 for draft-js so draftail will work as expected (also stated in draftail doc)

### Issue
I just followed the documentation in the mentions plugin but this is the result.

![draftail-issue](https://user-images.githubusercontent.com/12130528/112923924-c6414480-9141-11eb-9dc8-999d5ee0e44c.png)

### Editor Component
```
import React, { useState, useCallback, memo } from 'react'
import { DraftailEditor } from 'draftail'
import { defaultSuggestionsFilter } from '@draft-js-plugins/mention';
import { MentionData } from '@draft-js-plugins/mention/lib';

import usePlugins from './hooks/usePlugins'
import { StyledEditorWrapper } from './styled'

import "draft-js/dist/Draft.css"
import "draftail/dist/draftail.css"
import '@draft-js-plugins/mention/lib/plugin.css'

interface IDraftail {
  mentionSuggestions?: MentionData[]
}

const Draftail: React.FC<IDraftail> = memo(({
  mentionSuggestions = [],
}) => {
  const [openState, setOpenState] = useState(false)
  const [suggestions, setSuggestions] = useState<MentionData[]>(mentionSuggestions)

  const onMentionSearchChange = useCallback(({ value }: { value: string }) => {
    const filteredMentions = defaultSuggestionsFilter(value, mentionSuggestions)
    setSuggestions(filteredMentions);
    // eslint-disable-next-line react-hooks/exhaustive-deps
  }, [mentionSuggestions]);

  const { plugins, MentionSuggestions } = usePlugins()

  return (
    <StyledEditorWrapper id="identifi-editor">
      <DraftailEditor
        plugins={plugins}
      />
      {Boolean(mentionSuggestions.length) && (
        <MentionSuggestions
          open={openState}
          onOpenChange={nextOpenState => setOpenState(nextOpenState)}
          suggestions={suggestions}
          onSearchChange={onMentionSearchChange}
          onAddMention={(_: MentionData) => setOpenState(false)}
        />
      )}
    </StyledEditorWrapper>
  )
})

export default Draftail

```

### Plugins Hook
```
import { useMemo } from 'react'
import createMentionPlugin from '@draft-js-plugins/mention';

export default () => {
  const pluginsObject = useMemo(() => {
    const mentionPlugin = createMentionPlugin()
    const { MentionSuggestions } = mentionPlugin
    const plugins = [
      mentionPlugin,
    ]
    return {
      plugins,
      MentionSuggestions,
    }
  }, [])

  return pluginsObject
}
```

I'm noob at draft-js, I hope you guys can point out what I'm missing or what I did wrong.

**Comment by fxOne** [comment]
Can you setup a [codesandbox.io](https://codesandbox.io/) sample so that I can have a look at this issue?

**Comment by vmc08** [comment]
@fxOne Thank you for your reply. Here's the link:

https://codesandbox.io/s/vigilant-shadow-h7cep?file=/src/App.js


I only have the mentions plugin enabled to avoid confusion

**Comment by fxOne** [comment]
The arrow keys are not working as it looks like `drafttail` does not call the plugins `keyBindingFn`. As I replaces `drafttail` with `@draft-js-plugins/editor` and the mentions plugin works as expected I assume that there might be an issue in `drafttail`? But as I have never done anything with `drafttail` you should ask there.

I will close the issue for now but feel free to come back if there is an issue on our side and I will reopen this issue!
