### ISSUE TITLE
Emojis don't work on paste

### ISSUE THREAD

**Issue by juliankrispel** [draft-js-plugins/draft-js-plugins#196]
Currently, we're not properly parsing unicodes when they're not added manually, but pasted or are already in the text somehow

![emojis](https://cloud.githubusercontent.com/assets/1188186/14565460/781fd7b6-032b-11e6-8e26-a11f4eeaaf30.gif)

I'm working on fixing this now

**Comment by nikgraf** [comment]
fixed here: https://github.com/draft-js-plugins/draft-js-plugins/pull/200
