### ISSUE TITLE
findDOMNode warning when using image and resizeable plugins

### ISSUE THREAD

**Issue by Apporix** [draft-js-plugins/draft-js-plugins#1979]
## Environment

"@draft-js-plugins/editor": "4.1.0",
"@draft-js-plugins/focus": "4.1.1",
"@draft-js-plugins/image": "4.1.1",
"@draft-js-plugins/resizeable": "4.1.0",
"draft-js": "0.11.7",
"react": "17.0.2",
"react-dom": "17.0.2",
"react-scripts": "4.0.0",

## Description
Hello, 
First of all, thank you for your very fast fix for [#1977](https://github.com/draft-js-plugins/draft-js-plugins/issues/1977#issue-855119472).  However, I get the following second/different warning when I try to recreate the second example of the [image docs](https://www.draft-js-plugins.com/plugin/image):

`Warning: findDOMNode is deprecated in StrictMode. findDOMNode was passed an instance of Resizable(Component) which is inside StrictMode. Instead, add a ref directly to the element you want to reference. Learn more about using refs safely here: https://reactjs.org/link/strict-mode-find-node`

The warning gets thrown, when the mouse _hovers_ over the image (e.g. to resize). The focus plugin alone has no warning, but only in combination with the resizeable plugin.

## Reproducible Demo

Here is an example that reproduces the warning: https://codesandbox.io/s/reverent-wilbur-92lm1?fontsize=14&hidenavigation=1&theme=dark

**Comment by fxOne** [comment]
Looks like there are 3 places where `findDOMNode` is used:

- https://github.com/draft-js-plugins/draft-js-plugins/blob/b89a8146e6d697ebd15bf10f8970086862a56b47/packages/resizeable/src/createDecorator.tsx#L96
- https://github.com/draft-js-plugins/draft-js-plugins/blob/b89a8146e6d697ebd15bf10f8970086862a56b47/packages/resizeable/src/createDecorator.tsx#L141
- https://github.com/draft-js-plugins/draft-js-plugins/blob/c74aa41e841602d0d56537b65eb642de026c7250/packages/alignment/src/createDecorator.tsx#L46

As it is only a warning I would fix it with a low priority, maybe when we find the time to change the components to hooks.
