### ISSUE TITLE
forwardRef warning when using drag-n-drop and resizeable plugins

### ISSUE THREAD

**Issue by Apporix** [draft-js-plugins/draft-js-plugins#1992]
## Environment

"@draft-js-plugins/editor": "4.1.0",
"@draft-js-plugins/focus": "4.1.1",
"@draft-js-plugins/image": "4.1.1",
"@draft-js-plugins/drag-n-drop": "4.1.0",
"@draft-js-plugins/resizeable": "4.1.0",
"draft-js": "0.11.7",
"react": "17.0.2",
"react-dom": "17.0.2",
"react-scripts": "4.0.0",

## Description
Hello, 
The same warning in #1977 which was fixed in #1978 occurs also when combining `@draft-js-plugins/resizeable` and `@draft-js-plugins/drag-n-drop`. So I guess that `forwardRef ` also must be added in `@draft-js-plugins/drag-n-drop`.

It is possible that `forwardRef ` is also missing in `@draft-js-plugins/drag-n-drop-upload`, although I have not tested it yet.

## Reproducible Demo

Here is an example that reproduces the warning: https://codesandbox.io/s/awesome-ganguly-y0d2w?fontsize=14&hidenavigation=1&theme=dark

**Comment by fxOne** [comment]
Thank you for your great issue reports!
