### ISSUE TITLE
[Emoji] Emoji suggestions input to wrong editor 

### ISSUE THREAD

**Issue by ricosandyca** [draft-js-plugins/draft-js-plugins#1995]
## Environment

- @draft-js-plugins/editor version: ^4.1.0
- @draft-js-plugins/emoji version: ^4.5.0

## Description

Emoji suggestions input to wrong editor. Let's say I have two editors that have emoji plugin installed. The first editor is rendering asynchronously and the second one is synchronous. Emoji suggestions always input to the asynchronous editor since you re-initialize `getEditorState` on editor initialization.

![Record_select-area_20210422152116](https://user-images.githubusercontent.com/43330562/115681550-d7672500-a37e-11eb-88ed-a2482d071639.gif)

## Reproducible Demo
1. Create two editors, asynchronous and synchronous rendering editors with the same component source.
2. Apply the emoji plugin.
3. Try to select emoji on the synchronous editor one.
4. It should input to the wrong editor.

[Playground](https://codesandbox.io/s/quizzical-bartik-7fr3y?file=/src/MyEditor.js)

**Comment by fxOne** [comment]
That's correct, you should create a new plugin instance for each editor.

e.g. use something like this:
`const { EmojiSelect, EmojiSuggestions, ...emojiPlugin } = useMemo(() => createEmojiPlugin(),[]);`
