### ISSUE TITLE
[Mention Plugin] Add mention on button click

### ISSUE THREAD

**Issue by Sooraj-s-98** [draft-js-plugins/draft-js-plugins#2000]
## addmention by passing mention user ID

when i click on user name mention that user .

**Comment by fxOne** [comment]
Can you please describe your feature request with more details? Maybe an example can help.

**Comment by ozgur-dogan** [comment]
On lick to the user name on the mention popup, it is not doing anything. (on the website it works) => https://www.draft-js-plugins.com/plugin/mention

This could a related with a bug in the newer version.
My editor version is 4.1.0
My mention version is 4.4.0.

**Comment by Sooraj-s-98** [comment]
I don't need show suggestions when user click on a button , directly mention a user on editor. It is like Facebook. When we press reply button in Facebook comment , mention that user directly in editor. I need this feature.

**Comment by Sooraj-s-98** [comment]
@ozgur-dogan @fxOne  it is same like Facebook reply comment feature. When we click on reply button on Facebook directly mention that user in editor and could not show suggestions.

**Comment by ozgur-dogan** [comment]
@Sooraj-s-98 I mean, when you click on the suggestions, it doesn't do anything.

**Comment by ozgur-dogan** [comment]
https://user-images.githubusercontent.com/6137523/115965857-fc949880-a522-11eb-80ff-710f25021b2b.mov

Check this

**Comment by Sooraj-s-98** [comment]
**i need extra feature. when click on button , mention specific user in editor. Any idea ??
it is same like facebook auto mention without click on mention suggestions . when click reply button in facebook comment , automatically mention that user on textarea**   @fxOne , @ozgur-dogan  @makenosound  @okonet

**Comment by fxOne** [comment]
Can you please explain why this should be part of the mention plugin?

**Comment by luokebi** [comment]
@fxOne I was looking for this feature too. I think it's a common use case when using mention feature like @Sooraj-s-98 says. It should be a way to do that.
