### ISSUE TITLE
npm install: unable to resolve dependency tree

### ISSUE THREAD

**Issue by DevAngsy** [draft-js-plugins/draft-js-plugins#2006]
## Environment

- system: Windows 10 20H2
- node version: 14.16.1
- npm version: 7.10.0
- @draft-js-plugins/editor version: 4.1.0
- @draft-js-plugins/emoji version: 4.5.0
- @draft-js-plugins/hashtag version: 4.2.0
- @draft-js-plugins/linkify version: 4.1.0
- @draft-js-plugins/mention version: 4.4.1

## Description
![屏幕截图 2021-04-25 174015](https://user-images.githubusercontent.com/27341089/115988663-5366a480-a5ed-11eb-98e4-9b6eefb8cb35.png)

**Comment by fxOne** [comment]
Can't see any issues there as there is no new version released since 3 years: https://www.npmjs.com/package/find-with-regex
My full installation with yarn works yesterday without any issues.
Maybe a temporary issue?

**Comment by DevAngsy** [comment]
Not a temporary issue.

First run "npm cache clean --force", then "npm install".

npm 7 use new peer dependency algorithm.

I will try it again on ubuntu sys.

**Comment by fxOne** [comment]
Maybe this issue is related to https://github.com/draft-js-plugins/find-with-regex/issues/8

**Comment by DevAngsy** [comment]
How about starting a new lib to replace find-with-regex.

**Comment by fxOne** [comment]
This is a similar question I asked @sibelius. Currently I'm waiting for a response.

**Comment by sibelius** [comment]
let's move find-with-regex here, and release a new scoped version

**Comment by fxOne** [comment]
@DevAngsy I hope npm 7 works with the fixed dependency.

**Comment by DevAngsy** [comment]
Thanks, it works.

My another dependency issue: #2032
