### ISSUE TITLE
Images not working

### ISSUE THREAD

**Issue by jonching** [draft-js-plugins/draft-js-plugins#2012]
## Environment

    "@draft-js-plugins/editor": "^4.1.0",
    "@draft-js-plugins/image": "^4.1.1",
    "draft-js": "^0.11.7"

## Description

I keep getting this error whenever I try to add an image to the editor. I've tried using the imagePlugin.addImage() modifier as well as manually adding the entity to the editor state. Both give the same error.

<img width="1423" alt="Screen Shot 2021-04-27 at 10 32 50 AM" src="https://user-images.githubusercontent.com/3309754/116259638-f7fafa80-a743-11eb-935f-0c034c1b26b6.png">

**Comment by fxOne** [comment]
Can you please add a  https://codesandbox.io/ example so that I can reproduce the issue?
