### ISSUE TITLE
module.css not found

### ISSUE THREAD

**Issue by krisrajzlive** [draft-js-plugins/draft-js-plugins#2015]
Where is the css file located, i can't find it anywhere! 
import editorStyles from './SimpleMentionEditor.module.css';
Refer the website: https://www.draft-js-plugins.com/plugin/mention

Thanks

**Comment by fxOne** [comment]
You can find the file here: https://github.com/draft-js-plugins/draft-js-plugins/blob/master/packages/docs/components/Examples/mention/SimpleMentionEditor/SimpleMentionEditor.module.css

It's the file which is already in the example shown but with a wrong file name there (`editorStyles.css`). I'll fix it soon.
