### ISSUE TITLE
Multi-character triggers no longer work

### ISSUE THREAD

**Issue by emwalker** [draft-js-plugins/draft-js-plugins#2017]
## Environment

- @draft-js-plugins/editor version: v4.1.0
- plugin name and version: @draft-js-plugins/mention v4.4.1

## Description

Multi-character triggers appear to be broken for `@draft-js-plugins/mention`.

With [this PR](https://github.com/draft-js-plugins/draft-js-plugins/pull/1807/files#diff-f5be53e8ae08de0a2489882b1824da7087229abf7a92b29c8d5f3a9522e43690R45), support for multi-character triggers appears to have gone away.  I've verified that a change along the following lines to `@draft-js-plugins/mention` v4.4.1 restores the support for multi-character triggers, although I'm not sure whether there are other unwanted side effects, e.g., related to the new group capture:

```patch
diff --git a/packages/mention/src/mentionSuggestionsStrategy.ts b/packages/mention/src/mentionSuggestionsStrategy.ts
index 3107214a..f7d726a8 100644
--- a/packages/mention/src/mentionSuggestionsStrategy.ts
+++ b/packages/mention/src/mentionSuggestionsStrategy.ts
@@ -67,9 +67,9 @@ export default (
   regExp: string
 ): ((contentBlock: ContentBlock, callback: FindWithRegexCb) => void) => {
   //eslint-disable-line
-  const triggerPattern = `[${triggers
+  const triggerPattern = `(${triggers
     .map((trigger) => escapeRegExp(trigger))
-    .join('')}]`;
+    .join('|')})`;
   const MENTION_REGEX = supportWhiteSpace
     ? new RegExp(`${triggerPattern}(${regExp}|\\s)*`, 'g')
     : new RegExp(`(\\s|^)${triggerPattern}${regExp}*`, 'g');
```

Note that the earlier code in the diff is constructing a regular expression along the lines of `/[trigger](...)/`; i.e., it's collapsing the multi-character trigger into a character class search.

In version v3.1.5 of `draft-js-mention-plugin`, a trigger of "in:" worked for me:

![2021-04-28_13-22](https://user-images.githubusercontent.com/760949/116460888-cefe6680-a824-11eb-8a37-3a1fd6367589.png)

**Comment by fxOne** [comment]
Do you use a custom `mentionRegExp`? In my tests I got an issue with multiple triggers as the text regex also matches the 'in':
![image](https://user-images.githubusercontent.com/5929640/116786821-155ff980-aaa1-11eb-87f6-ca7bf463346c.png)

**Comment by emwalker** [comment]
I'm thinking an anchor at the start of the pattern will solve the issue you're seeing:

![2021-05-01_09-45](https://user-images.githubusercontent.com/760949/116787561-f8f09c80-aa61-11eb-937a-a2912b38a688.png)

I vaguely recall there being an anchor that was in older versions of the code but that went away, but I didn't look into it.

> Do you use a custom mentionRegExp?

I'm not currently using this, although it might provide a workaround (I should check).

**Comment by emwalker** [comment]
I took a look at the `mentionRegExp` option, and since it's used in conjunction with the `triggerPattern` field, I probably won't be able to use it as an override/workaround.
```javascript
var mentionSuggestionsStrategy = (function (triggers, supportWhiteSpace, regExp) {
  //eslint-disable-line
  var triggerPattern = "[" + triggers.map(function (trigger) {
    return escapeRegExp(trigger);
  }).join('') + "]";
  var MENTION_REGEX = supportWhiteSpace ? new RegExp(triggerPattern + "(" + regExp + "|\\s)*", 'g') : new RegExp("(\\s|^)" + triggerPattern + regExp + "*", 'g');
  return function (contentBlock, callback) {
    findWithRegex(MENTION_REGEX, contentBlock, supportWhiteSpace, callback);
  };
});
```
