### ISSUE TITLE
Character counter doesn't count Unicode properly

### ISSUE THREAD

**Issue by nikgraf** [draft-js-plugins/draft-js-plugins#202]
After was watching [Unicode in JavaScript](https://www.youtube.com/watch?v=XD_5xDN7KUA) I was wondering if our counter does manage Unicode properly.

I noticed it doesn't. Here a screenshot of what happens:
![counter](https://cloud.githubusercontent.com/assets/223045/14588554/266229f4-0481-11e6-8835-0d929b21d6f0.gif)
See how the counter jumps from 182 to 193 by just adding one emoji.

anyone interested to pick this up?

/cc @adrianmc @juliankrispel

**Comment by adrianmc** [comment]
@nikgraf I'll take a look at this.

**Comment by adrianmc** [comment]
@nikgraf I've made a fix using the library used in the talk you linked to. It's called [punycode](https://www.npmjs.com/package/punycode).

As much as I'd like to reduce dependencies, this is probably the most robust way to handle unicode characters.
