### ISSUE TITLE
Emoji plugin - Make it possible to disable autocomplete with ":" or set another trigger

### ISSUE THREAD

**Issue by Spoonrad** [draft-js-plugins/draft-js-plugins#2028]
## Describe the feature

The Emoji plugin includes a feature where typing ":" will open the emoji autocomplete box. I haven't found a way to customize this and either disable it and change the trigger key

## Motivation

Some users (like me) may want to disable this feature altogether, or they may want a less obnoxious key (":" is used a lot in editors, and usually not for emojis).
## Possible implementations

As a props passed to the plugin creation function

In the meantime I'm interested in workarounds I may not have thought of. I'd rather not fork the plugin and make my own version just for this.

Thank you for the great package!

**Comment by fxOne** [comment]
I have added the prop `disableInlineEmojis` to disable the inline suggestions. The change of the trigger would have been more difficult as it is part of the emoji one library.
