### ISSUE TITLE
use react-custom-scrollbars-2 replace react-custom-scrollbars

### ISSUE THREAD

**Issue by DevAngsy** [draft-js-plugins/draft-js-plugins#2032]
## Environment

- system: Windows 10 Pro for Workstations 20H2
- node version: 14.16.1
- npm version: 7.11.2
- @draft-js-plugins/editor version: 4.1.0
- @draft-js-plugins/emoji version: 4.5.1
- @draft-js-plugins/hashtag version: 4.2.0
- @draft-js-plugins/linkify version: 4.1.0
- @draft-js-plugins/mention version: 4.4.1

## Description
Related package: 
- @draft-js-plugins/emoji

Awww, react-custom-scrollbars is outdate, it has 140+ issues, 40+ pull requests, and "npm install" of v7 caused error. 
We can use [react-custom-scrollbars-2](https://github.com/RobPethick/react-custom-scrollbars-2), I think this repo is the best replacer.

Other possible solutions:
- https://css-tricks.com/the-current-state-of-styling-scrollbars/
- https://www.w3schools.com/howto/howto_css_custom_scrollbar.asp
- https://github.com/rommguy/react-custom-scroll
- https://github.com/xobotyi/react-scrollbars-custom

![屏幕截图 2021-05-02 180748](https://user-images.githubusercontent.com/27341089/116809593-558ead00-ab71-11eb-9477-aaffbc30c58d.png)

## Reproducible Demo

nothing

**Comment by fxOne** [comment]
Thanks for the hint with react-custom-scrollbars-2. Hope that npm is now happy :)

**Comment by DevAngsy** [comment]
@fxOne I have a question that react-custom-scrollbars-2 has own type define, why write same type define in packages/emoji/src/@types/react-custom-scrollbars-2.d.ts.

**Comment by DevAngsy** [comment]
NPM works normally, thanks.

**Comment by DevAngsy** [comment]
> @fxOne I have a question that react-custom-scrollbars-2 has own type define, why write same type define in packages/emoji/src/@types/react-custom-scrollbars-2.d.ts.

And the class "Scrollbars" of type define of react-custom-scrollbars-2 has a "container" property, but "packages/emoji/src/@types/react-custom-scrollbars-2.d.ts" not have.

**Comment by fxOne** [comment]
I totally missed that they had types, I just saw 100% JavaScript:
![image](https://user-images.githubusercontent.com/5929640/116816514-84515700-ab62-11eb-93bb-1160fda9c2bf.png)
I removed my definition.
