### ISSUE TITLE
static-toolbar is not working

### ISSUE THREAD

**Issue by matiosfree** [draft-js-plugins/draft-js-plugins#2036]
Static-toolbar is not working even on demo page.
https://www.draft-js-plugins.com/plugin/static-toolbar

If I select some text and make it bold nothing happens.
If I sroll down to the 2nd example and click on **CODE icon first** (it's important) and after that make bold text everything is working.

**Comment by fxOne** [comment]
The static-toolbar worked fine. There was only an issue with the SSR rendering implemention.
