### ISSUE TITLE
@mentioning triggers error

### ISSUE THREAD

**Issue by krisrajzlive** [draft-js-plugins/draft-js-plugins#2037]
I get this error message upon typing @ in the editor:
searchValue.toLowerCase is not a function

var defaultSuggestionsFilter$1 = function defaultSuggestionsFilter(searchValue, suggestions, trigger) {
  var value = searchValue.toLowerCase();
  var triggerSuggestions = trigger && !Array.isArray(suggestions) ? suggestions[trigger] : suggestions;
  var filteredSuggestions = triggerSuggestions.filter(function (suggestion) {
    return !value || suggestion.name.toLowerCase().indexOf(value) > -1;
  });
  var length = filteredSuggestions.length < 5 ? filteredSuggestions.length : 5;
  return filteredSuggestions.slice(0, length);
};

I have converted typescript to jsx

**Comment by fxOne** [comment]
Can you create a full sample so that I can reproduce the issue on [codesandbox](codesandbox.io). What do you mean by "I have converted typescript to jsx"?

**Comment by krisrajzlive** [comment]
I am not familiar with that, but I am using react functional component in a javascript project hence can't use typescript.

**Comment by fxOne** [comment]
Sorry, but I can only help you with more information like a full example.

**Comment by krisrajzlive** [comment]
I got fixed myself. Thanks for trying to help me!
