### ISSUE TITLE
Suggestions with scrollbar

### ISSUE THREAD

**Issue by krisrajzlive** [draft-js-plugins/draft-js-plugins#2048]
Can we have suggestions with scrollbars to see all the items?

Thanks

**Comment by fxOne** [comment]
You should be able to change the styles to give the container an overflow or you can create a custom mention component. 
Can you please explain what exactly you are missing?

**Comment by krisrajzlive** [comment]
The number of items in the mentions plugin does not fit in my screen and I can't move it to top of the screen hence users are forced off of the screen at the bottom which does not look good. A scroll bar with fixed number of items without missing all the matching items will be really helpful.

**Comment by fxOne** [comment]
Can you add a screenshot or something like this so that I can get a better feeling why you cannot add a scrollbar yourself via CSS or custom mention component?

**Comment by krisrajzlive** [comment]
Original screen
![image](https://user-images.githubusercontent.com/47850702/117688551-8062ac00-b1d6-11eb-9984-624e91982cfe.png)
After populating suggestions:
![image](https://user-images.githubusercontent.com/47850702/117688471-6aed8200-b1d6-11eb-9bae-851f3b983327.png)

It seems like I have messed up something!

**Comment by krisrajzlive** [comment]
Original Screen:
![image](https://user-images.githubusercontent.com/47850702/117688797-c0c22a00-b1d6-11eb-9e09-862f9a8d7430.png)

After populating suggestions returned by service:
![image](https://user-images.githubusercontent.com/47850702/117688909-de8f8f00-b1d6-11eb-9db0-937be086abf0.png)

Seems like I have messed around something.
`
const editorStyles = {
        editor: {
            boxSizing: 'border - box',
            border: '1px solid #ddd',
            cursor: 'text',
            padding: '16px',
            borderRadius: '2px',
            marginBottom: '2em',
            boxShadow: 'inset 0px 1px 8px - 3px #ABABAB',
            background: '#fefefe',
            minHeight: 80
        },
        root: {
            fontFamily: '\'Helvetica\', sans-serif',
            padding: 20
        }
    }

const renderNotesEditor = () => {
        return (
            <div
                className={editorStyles.editor}
                onClick={() => {
                    if (ref.current != null)
                        ref.current.focus();
                }}
            >
                <Editor
                    editorKey={'editor'}
                    editorState={editorState}
                    onChange={setEditorState}
                    plugins={plugins}
                    ref={ref}
                    placeholder='Enter a note. Type @mention to directly message someone.'
                />
                <MentionSuggestions
                    open={open}
                    onOpenChange={onOpenChange}
                    suggestions={suggestions}
                    onSearchChange={onSearchChange}
                    onAddMention={() => {
                        // get the mention object selected
                    }}
                />
            </div>
        );
    }`

**Comment by fxOne** [comment]
I would guess that you need to set you own CSS for `theme.mentionSuggestions` or `theme.mentionSuggestionsEntry` classes. You can find the documentation here: https://www.draft-js-plugins.com/plugin/mention

**Comment by fxOne** [comment]
Duplicated to #997
