### ISSUE TITLE
Bug in mention plugin - popover/popper.

### ISSUE THREAD

**Issue by DasGMA** [draft-js-plugins/draft-js-plugins#2049]
## Environment

It happens everywhere, even on official website. 

- @draft-js-plugins/editor version: current
- plugin name and version: current

## Description

The issue appears to trigger when have more than one mention. For example of there is Matthew Russel and type @ and mouse is focused on at least one suggestion from suggestions list, deleting @ with backspace leaves empty popper artifact that can be discarded only after the page reload. 

![20210506_085341](https://user-images.githubusercontent.com/39565597/117329561-9cb6bf80-ae49-11eb-86dd-d3aef64cdb84.jpg)
![20210506_085346](https://user-images.githubusercontent.com/39565597/117329586-a3453700-ae49-11eb-8d80-1662ae5f029b.jpg)

**Comment by fxOne** [comment]
This is related to #1696 as the popup is open even if there are no entries to show.
