### ISSUE TITLE
side-toolbar plugin shows twice if there are 2 rendered draft js components in the same page

### ISSUE THREAD

**Issue by ilanskogan** [draft-js-plugins/draft-js-plugins#2053]
Hi, i have a modal which renders 2 draft js components. in both I use side-tool bar plugin.
the problem is that when I focus one of the editors both tool bars show up.
i guess this is related to some dom selector so  I think the solution is to be able to add some class/id prefix to the sideToolBar component 

Here is a screen shot
![Screen Shot 2021-05-09 at 13 14 52](https://user-images.githubusercontent.com/71634959/117568370-8e2a0b80-b0c8-11eb-837e-a37b81b662ac.png)

**Comment by fxOne** [comment]
Can you please show some code or better create an https://codesandbox.io/ example so that I can reproduce this issue? As far as I can see this issue does not occur on our page: https://www.draft-js-plugins.com/plugin/side-toolbar

**Comment by ilanskogan** [comment]
> Can you please show some code or better create an https://codesandbox.io/ example so that I can reproduce this issue? As far as I can see this issue does not occur on our page: https://www.draft-js-plugins.com/plugin/side-toolbar

Yes here it is, I added background color to each editor so you can identify it - https://codesandbox.io/s/autumn-tree-2cgmv

**Comment by fxOne** [comment]
The issue is that you create only one plugin instance for both editors. You should move the creation of the plugin into the component.

**Comment by ilanskogan** [comment]
@fxOne thanks. maybe add this to the docs because you create the plugin instance outside the component there too.
again thanks for the answer :)
