### ISSUE TITLE
max-height and overflow auto breaks the position of the side-tool bar plugin

### ISSUE THREAD

**Issue by ilanskogan** [draft-js-plugins/draft-js-plugins#2054]
Hi i noticed that if you set following css:
`.editor :global(.public-DraftEditor-content) {
  max-height: 450px;
  overflow: auto;
}
`
and press enough enter so it will start to overflow the position of the side-toolbar breaks and it looks like it should be if there was not the overflow: "auto" property.
here is a sandbox - https://codesandbox.io/s/xenodochial-banzai-vmg3b

**Comment by fxOne** [comment]
I would say the best solution would be change the popover to `popper.js`. It would take some time to implement this, but if you need it quicker feel free to send a PR.
