### ISSUE TITLE
Introduce the default value in the Editor tag, I have problems setting the default value when I am using draft-js-plugin

### ISSUE THREAD

**Issue by hiagolincon** [draft-js-plugins/draft-js-plugins#2059]
Hello, I would like to introduce the default value in the Editor tag, I have problems setting the default value when I am using draft-js-plugin / mention, because the mentions do not work when I set the default value in the state with useEffect

**Comment by fxOne** [comment]
Can you please explain what you mean by `default value`?

**Comment by hiagolincon** [comment]
It is the value that I put in the Editor when the page loads, I pass that value by setting a new value in the state with useEffect

**Comment by fxOne** [comment]
Can you add an example?

**Comment by quanlatoi** [comment]
same with problem

**Comment by quanlatoi** [comment]
> Can you add an example?

it's like reply comment, we must mention a user. When I use `EditorState.createWithContent(contentState)` in useEffect hook to set new state for editorState, mention is not woking.

**Comment by fxOne** [comment]
@quanlatoi When you create a new `EditorState` in a `useEffect` you are removing all decorators which are added by the plugins. you should create the `EditorState` in the `useState` function like: 

`useState(() => EditorState.createWithContent(contentState))`
