### ISSUE TITLE
create-react-app -V 4.0.3(latest) throw Warning "UNSAFE_componentWillMount in EmojiSuggestions component

### ISSUE THREAD

**Issue by haw0k** [draft-js-plugins/draft-js-plugins#2069]
## Environment
OS: Ubuntu 18.04
NodeJS 14.17.0

create-react-app 4.0.3

- @draft-js-plugins/editor 4.1.0
- plugin name and version: @draft-js-plugins/emoji 4.5.3

## Description
latest create-react-app with code from example with code
```
createEmojiPlugin({
  useNativeArt: true,
});"useNativeArt: true" throw Warning "UNSAFE_componentWillMount in EmojiSuggestions component
```
Got ERROR warning with text ```
Warning: Using UNSAFE_componentWillMount in strict mode is not recommended and may indicate bugs in your code. See https://reactjs.org/link/unsafe-component-lifecycles for details.

* Move code with side effects to componentDidMount, and set initial state in the constructor.

Please update the following components: EmojiSuggestions

## Reproducible Demo

- npx create-react-app dje-example
- cd djexample
- create component with code from the end of [page](https://www.draft-js-plugins.com/plugin/emoji)
- add created component to App.js
- yarn start
- check browser console for error messages

**Comment by fxOne** [comment]
You can remove the remove the strict mode to prevent this issue.
