### ISSUE TITLE
Don't close emoji suggestion after click on editor

### ISSUE THREAD

**Issue by vrg-success** [draft-js-plugins/draft-js-plugins#2081]
## Describe the feature
I'm working on project which has draftjs with emoji plugin and we are recording users behavior for improve our UX, so many users have problem with emoji suggestions and ediltor, emoji suggestion close after user focus on text editor(draftjs). Would be so good if you will add new prop name closeOnEditorFocus/closeOnEditorClick for <EmojiSelect /> component

https://github.com/draft-js-plugins/draft-js-plugins/blob/44423cee7c/packages/emoji/src/components/EmojiSelect/index.tsx#L70

**Comment by fxOne** [comment]
Can you please explain in detail what you want to achieve? 

As far as I understood you are talking about the button to add emojis and want to prevent it to be closed when the user clicks somewhere else. Is this correct?
