### ISSUE TITLE
No implementation files in sub-projects

### ISSUE THREAD

**Issue by Shlizer** [draft-js-plugins/draft-js-plugins#2085]
Hi,
I'm having truble to use drafj-js-plugins with TypeScript. I'm trying to install packages from npm:

```
{
    "dependencies": {
        "@draft-js-plugins/alignment": "^4.1.0",
        "@draft-js-plugins/buttons": "^4.0.0-beta2",
        "@draft-js-plugins/drag-n-drop": "^4.2.0",
        "@draft-js-plugins/drag-n-drop-upload": "^4.1.0",
        "@draft-js-plugins/focus": "^4.1.1",
        "@draft-js-plugins/resizeable": "^4.1.0",
        "@draft-js-plugins/video": "^4.1.0",
        ...
    }
    ...
}
```

After `npm i` I've got in my `node_modules` TS types, but there are no implementation files (everything is just put into one files and even without exports.

![image](https://user-images.githubusercontent.com/5565301/118951752-a537eb80-b95b-11eb-8372-b882ad45e3cb.png)

**Comment by fxOne** [comment]
All you need is the `index.*.js` and the `index.d.ts`.
