### ISSUE TITLE
onSearchChange not firing after initializing editorState with Plain text : React Hooks

### ISSUE THREAD

**Issue by kartiez360** [draft-js-plugins/draft-js-plugins#2086]
React Hooks

```
const stateWithEntity = editorState.getCurrentContent().createEntity(
                    'mention',
                    'IMMUTABLE',
                    {
                      mention: {id: 'foobar', name: 'foobar', link: 'https://www.facebook.com/foobar'},
                    },
                  )
const entityKey = stateWithEntity.getLastCreatedEntityKey()
const stateWithText = Modifier.insertText(stateWithEntity, editorState.getSelection(), 'foobar', null, entityKey)
const editorStateModified =  EditorState.push(editorState, stateWithText)
setEditorState(editorStateModified)

```

When I type @, it doesn't show any pop-up to search/select mentions. 

- @draft-js-plugins/editor version: "draft-js": "^0.11.6", "draft-js-plugins-editor": "^3.0.0",
- plugin name and version: "draft-js-mention-plugin": "^3.1.5",

## Description

![image](https://user-images.githubusercontent.com/69324878/119208369-e9b4ab80-ba6f-11eb-92f7-0015bb0d8fb6.png)

**NOTE: IT IS WORKING WHEN editorState is initialized as EditorState.createEmpty()**

----Edit----

https://codesandbox.io/s/strange-zhukovsky-osn0i

Check out the code.

**Comment by fxOne** [comment]
Can you please update to the latest versions and create a full reproducible sample on https://codesandbox.io

**Comment by kartiez360** [comment]
> Can you please update to the latest versions and create a full reproducible sample on https://codesandbox.io

Edited the orginal post.

**Comment by fxOne** [comment]
This is happening because you override the `EditorState` which is create by the plugin with an old one in the `useEffect`. Try ou something like this:

```JS
  const [editorState, setEditorState] = useState(() => {
    const e = EditorState.createEmpty();
    const stateWithEntity = e
      .getCurrentContent()
      .createEntity("mention", "IMMUTABLE", {
        mention: {
          id: "foobar",
          name: "foobar",
          link: "https://www.facebook.com/foobar"
        }
      });
    const entityKey = stateWithEntity.getLastCreatedEntityKey();
    const stateWithText = Modifier.insertText(
      stateWithEntity,
      e.getSelection(),
      "foobar",
      null,
      entityKey
    );
    const editorStateModified = EditorState.push(e, stateWithText);
    return editorStateModified;
  });
```
https://codesandbox.io/s/loving-shamir-ioqom?file=/src/CustomInput.js:649-1304

**Comment by kartiez360** [comment]
> This is happening because you override the `EditorState` which is create by the plugin with an old one in the `useEffect`. Try ou something like this:
> 
> ```js
>   const [editorState, setEditorState] = useState(() => {
>     const e = EditorState.createEmpty();
>     const stateWithEntity = e
>       .getCurrentContent()
>       .createEntity("mention", "IMMUTABLE", {
>         mention: {
>           id: "foobar",
>           name: "foobar",
>           link: "https://www.facebook.com/foobar"
>         }
>       });
>     const entityKey = stateWithEntity.getLastCreatedEntityKey();
>     const stateWithText = Modifier.insertText(
>       stateWithEntity,
>       e.getSelection(),
>       "foobar",
>       null,
>       entityKey
>     );
>     const editorStateModified = EditorState.push(e, stateWithText);
>     return editorStateModified;
>   });
> ```
> 
> https://codesandbox.io/s/loving-shamir-ioqom?file=/src/CustomInput.js:649-1304

Thanks! that worked!
