### ISSUE TITLE
Can't filter words with accents

### ISSUE THREAD

**Issue by AlvaroIHS** [draft-js-plugins/draft-js-plugins#209]
Hi, in mention plugin, I can't filter names with accents for example my name Álvaro.

**Comment by nikgraf** [comment]
@AlvaroIHS hey, I'm not sure what you are looking for. Can you elaborate a bit more on how you expect it to work? maybe describing it almost list a test:

(list of Strings, searchString) -> expectedResults

**Comment by AlvaroIHS** [comment]
Of course, sorry @nikgraf. Imagine that I want search a user that has as name Álvaro. If you try search right now, you don't find something because his name start with "Á". 

```
const mentions = fromJS([
  {
    name: 'Álvaro',
    link: 'https://twitter.com/mxstbr',
    avatar: 'https://pbs.twimg.com/profile_images/681114454029942784/PwhopfmU_400x400.jpg',
  },
  {
    name: 'Nik Graf',
    link: 'https://twitter.com/nikgraf',
    avatar: 'https://pbs.twimg.com/profile_images/535634005769457664/Ppl32NaN_400x400.jpeg',
  },
]);
```

```
(mentions, "Ál") ->  expectedResults (object has as name Álvaro)
```

Thanks!

**Comment by nikgraf** [comment]
ohh wow, that's unexpected. I will have a closer look, thx for reporting  in this really nice way 👍

**Comment by ABeloeil** [comment]
Hi,

I am experiencing the same issue.
It appears that the value sent by the method `onSearchChange` stop when encountering an accent.

ex:

typing `@Valérie` only send the value `@Val` and in my case close the suggestions.
