### ISSUE TITLE
Show an optional EmojiOne attribution in the emoji popover

### ISSUE THREAD

**Issue by remyoukaour** [draft-js-plugins/draft-js-plugins#2099]
## Describe the feature

Add an optional attribution notice at the bottom of the emoji popover: "EmojiOne art by [JoyPixels](https://www.joypixels.com/) ([CC-BY-4.0](https://creativecommons.org/licenses/by/4.0/))"

## Motivation

The [emojione v2.2.7](https://github.com/joypixels/emojione/tree/v2.2.7) [license](https://github.com/joypixels/emojione/blob/v2.2.7/LICENSE.md) is [CC-BY-4.0](https://creativecommons.org/licenses/by/4.0/), which requires attribution (a link to the creator and to the license itself). We would like to show this attribution directly in the emoji popover.

## Possible implementations

Add a `showAttribution` boolean property to the `EmojiSelect` component, which would be passed down internally to the `Popover` and show the attribution message. This could also have themable CSS classes for the message and its links.

**Comment by remyoukaour** [comment]
I had already prepared to make a pull request for this: https://github.com/remyoukaour/draft-js-plugins/tree/emojione-attribution However I was not able to fulfill all the contribution requirements: running `npm start` inside `packages/docs` (not `docs` as documented, which doesn't exist) fails, I think since [`next`](https://www.npmjs.com/package/next) was not installed, but attempting to add it gives successive errors like "Failed to install dependencies in workspace: expected workspace package to exist for \"icss-utils\"".

**Comment by fxOne** [comment]
You should use yarn to build the packages. 
Also the latest version of the emoji plugin is using [joypixels/emoji-toolkit](https://github.com/joypixels/emoji-toolkit) as [joypixels/emojione](https://github.com/joypixels/emojione) is archived.
