### ISSUE TITLE
Inline toolbar not showing

### ISSUE THREAD

**Issue by softmarshmallow** [draft-js-plugins/draft-js-plugins#2128]
Use exact same pice of code as provided on the website, with disabling style. (since i don't use .css files)
Tried also applying style manually, but it won't show up.

```jsx
import React, {
  ReactElement,
  useEffect,
  useMemo,
  useRef,
  useState,
} from "react";
import { EditorState } from "draft-js";
import Editor, { createEditorStateWithText } from "@draft-js-plugins/editor";
import createInlineToolbarPlugin from "@draft-js-plugins/inline-toolbar";
//   import editorStyles from './editorStyles.module.css';

const text =
  "In this editor a toolbar shows up once you select part of the text …";

const SimpleInlineToolbarEditor = (): ReactElement => {
  const [plugins, InlineToolbar] = useMemo(() => {
    const inlineToolbarPlugin = createInlineToolbarPlugin();
    return [[inlineToolbarPlugin], inlineToolbarPlugin.InlineToolbar];
  }, []);

  const [editorState, setEditorState] = useState(() =>
    createEditorStateWithText("")
  );

  useEffect(() => {
    // fixing issue with SSR https://github.com/facebook/draft-js/issues/2332#issuecomment-761573306
    setEditorState(createEditorStateWithText(text));
  }, []);

  const editor = useRef<Editor | null>(null);

  const onChange = (value: EditorState): void => {
    setEditorState(value);
  };

  const focus = (): void => {
    editor.current?.focus();
  };

  return (
    <div onClick={focus}>
      <Editor
        editorKey="SimpleInlineToolbarEditor"
        editorState={editorState}
        onChange={onChange}
        plugins={plugins}
        ref={(element) => {
          editor.current = element;
        }}
      />
      <InlineToolbar />
    </div>
  );
};

export default SimpleInlineToolbarEditor;

```

https://user-images.githubusercontent.com/16307013/121288237-01b87600-c91e-11eb-8d16-11e5e4e78172.mov

**Comment by luciapuccini** [comment]
Run into the same behaviour. I solved it by importing the default styles from `node_modules/@draft-js-plugins/inline-toolbar/lib/plugin.css`.  After that you should be able to customize with your own css files (editorStyles). Hope this helps.

For clarification:
```javascript
import '../node_modules/@draft-js-plugins/inline-toolbar/lib/plugin.css'; // --> this is missing 
// import editorStyles from './editorStyles.module.css';

```

**Comment by fxOne** [comment]
If you use your own CSS classes you need to set the `theme` option with the class names you are using.

**Comment by softmarshmallow** [comment]
> If you use your own CSS classes you need to set the `theme` option with the class names you are using.

I don't get it. can you show me an example?

p.s. as mentioned above, i've applied styles with styled-components. Is it normal for this to be not working?
The css content is identical.

**Comment by fxOne** [comment]
From the [Themed Inline Toolbar Example](https://www.draft-js-plugins.com/plugin/inline-toolbar):

```js
import buttonStyles from './buttonStyles.module.css';
import toolbarStyles from './toolbarStyles.module.css';

const inlineToolbarPlugin = createInlineToolbarPlugin({
  theme: { buttonStyles, toolbarStyles },
});
```

**Comment by softmarshmallow** [comment]
> From the [Themed Inline Toolbar Example](https://www.draft-js-plugins.com/plugin/inline-toolbar):
> 
> ```js
> import buttonStyles from './buttonStyles.module.css';
> import toolbarStyles from './toolbarStyles.module.css';
> 
> const inlineToolbarPlugin = createInlineToolbarPlugin({
>   theme: { buttonStyles, toolbarStyles },
> });
> ```
> 
> You can find the full source code here: https://github.com/draft-js-plugins/draft-js-plugins/tree/master/packages/docs/components/Examples/inline-toolbar/ThemedInlineToolbarEditor

Thanks. I'm looking for css independent way of doing this since i'm using nextjs mono repo.

Main proj as nextjs and other monorepo package as draftjs & this plugin. the css will break up lot of things.
Is there no way to do this in current design of this package?

**Comment by fxOne** [comment]
What do you mean by CSS independent way? Can you give me an example and how should a solution look like?

**Comment by softmarshmallow** [comment]
I.e
```
<StyledInlineToolbar width="auto" height="24px">
   <BoldToggle icon={...} color={...} padding={...}/>
</StyledInlineToolbar>
```

some like this i guess?
since it depends on react

**Comment by fxOne** [comment]
Cannot you create a editor wrapper component which takes all the parameters that you want to style from the outside and use it where ever you want?

**Comment by softmarshmallow** [comment]
The problem of the current design is that this plugin forces user to import css. That is a design flaw (IMHO)

Plus, speaking behalf of users independent design will be a lot more intuitive and extensible for future users to use this plugin.

**Comment by fxOne** [comment]
You didn't see anything because you didn't import the CSS or provided classNames which are mapping to a CSS file which somewhere exists.

I'm sorry but this is how this library works.
