### ISSUE TITLE
Fix params styles in the docs for all plugins

### ISSUE THREAD

**Issue by nikgraf** [draft-js-plugins/draft-js-plugins#214]
@adrianmc improved the styles in the counter plugin. We should either port them or even better create a component for it that takes these params as a property.

**Comment by nikgraf** [comment]
@adrianmc do you have time to pick this up?

**Comment by adrianmc** [comment]
Sure, I'll take a look.

**Comment by nikgraf** [comment]
sweet

**Comment by juliankrispel** [comment]
Closing for issue cleanup - If you need this issue and think it should remain open please let us know why, thank you
