### ISSUE TITLE
compositeDecorator is not working 

### ISSUE THREAD

**Issue by DipsC** [draft-js-plugins/draft-js-plugins#2143]
I used draft-js-plugin for social post., so I can create and edit post. For that I used decorator and can change text, image and mention. In mention,I used multimention.
I faced below issues :

- I don't know how to create mention in compositedecorator  strategy.
- When I pass decorator in EditorState.createEmpty() it is going to maximum update.
-When I remove decorator in EditorState.createEmpty()  it works fine and post data. But After posting, when reset editor by EditorState.createEmpty(), mention is not working.

I need create post with mention with decorator and edit post with mention.
please check below link for code

[https://stackblitz.com/edit/react-biyy6h](https://stackblitz.com/edit/react-biyy6h)

Please help me to resolve this issue.

**Comment by fxOne** [comment]
You are using the `compositeDecorator` from `draft-js`, this is `draft-js-plugins`.

If you simply want to use the mention plugin you don't need your own mention decorator as the plugin has an own one. Also if you want to use own decorators you should use the `decorators` property from the editor as mentioned in the [FAQ](https://github.com/draft-js-plugins/draft-js-plugins/blob/master/FAQ.md#how-can-i-use-custom-decorators-with-the-plugin-editor).

**Comment by DipsC** [comment]
@fxOne  okay, So how to maintain decorator of mention when submit post in html and retrieve this html with same decorator in edit mode.
