### ISSUE TITLE
How to maintain mention decorator editorstate to html  and  html to editorstate

### ISSUE THREAD

**Issue by DipsC** [draft-js-plugins/draft-js-plugins#2144]
I used draft-js-plugin for social post., so I can create and edit post. For that I used decorator and can change text, image and mention. In mention,I used multimention.
I faced below issues :

I don't know how to create mention in compositedecorator strategy.
When I pass decorator in EditorState.createEmpty() it is going to maximum update.
-When I remove decorator in EditorState.createEmpty() it works fine and post data.
I need create post with mention decorators .

@fxOne how to maintain mention decorators  when submit post to html and  again retrieve this html with same decorators to editorstate.

please check below link for code

[https://stackblitz.com/edit/react-4qmvzf](https://stackblitz.com/edit/react-4qmvzf)

**Comment by fxOne** [comment]
Can you please explain what you would like to achieve?

**Comment by PalTamasWBA** [comment]
@fxOne maybe it's about restoring the editor state.

I'm facing a similar issue where converting the content state to raw and then back from raw does not work properly, as if the plugins weren't even there. I am basically trying to render the content by using the `readOnly` prop

```jsx
const classes = useStyles()
  const [editorState, setEditorState] = React.useState(EditorState.createEmpty())

  const hashtagPlugin = React.useMemo(() => (
    createHashtagPlugin({
      theme: {
        hashtag: classes.hashtag
      }
    })
  ), [classes.hashtag])

  const linkifyPlugin = React.useMemo(() => (
    createLinkifyPlugin({
      theme: {
        link: classes.link
      }
    })
  ), [classes.hashtag])

  const currentContent = editorState.getCurrentContent()
  const raw = convertToRaw(currentContent)
  const restoredContentState = convertFromRaw(raw)
  const restoredEditorState = EditorState.createWithContent(restoredContentState)

  return (
    <Box>
      <Editor editorState={editorState} onChange={setEditorState} plugins={[linkifyPlugin, hashtagPlugin]} />
      <Editor editorState={restoredEditorState} readOnly={true} onChange={() => {}} plugins={[linkifyPlugin, hashtagPlugin]} />
    </Box>
  );
```

**Comment by fxOne** [comment]
@PalTamasWBA you should find your answer here: https://github.com/draft-js-plugins/draft-js-plugins/issues/982#issuecomment-502690108
