### ISSUE TITLE
Side tool bar plugin menu doesnt open to the right direction

### ISSUE THREAD

**Issue by ilanskogan** [draft-js-plugins/draft-js-plugins#2182]
Hi looks like the menu itself that opens when you hover on the side toolbar plugin always open to bottom even if there is no enough space, I tried to play with the popper options to fix that but i failed.
![Screen Shot 2021-07-05 at 13 37 51](https://user-images.githubusercontent.com/71634959/124458912-3e995080-dd96-11eb-9efa-88135ad9970d.png)
Any suggestions? the expected behavior is that if there is not enough space at the bottom of the page, the menu should open to the top.
because of this, i have to wrap my list of buttons in a pop-menu component we had already that has that functionality but I would like to just use the default menu to show that list.
here is what i mean
![Screen Shot 2021-07-05 at 13 42 47](https://user-images.githubusercontent.com/71634959/124459645-047c7e80-dd97-11eb-9b2f-98d8a8925a0e.png)
![Screen Shot 2021-07-05 at 13 43 18](https://user-images.githubusercontent.com/71634959/124459652-06ded880-dd97-11eb-8e9d-14c0efd85fad.png)

**Comment by fxOne** [comment]
The `popperOptions` are for the 3 dot button popup. Currently the option are only a hover effect from which expands them down. Maybe we should add a 2nd popover there.

**Comment by ilanskogan** [comment]
@fxOne so is there a workaround to do this right now? if so can you guide me please?

**Comment by fxOne** [comment]
Currently there should't be a workaround. Maybe you could try to implement a solution with CSS but it wouldn't be dynamic
