### ISSUE TITLE
mention plugin does not work on Safari

### ISSUE THREAD

**Issue by Epicurean** [draft-js-plugins/draft-js-plugins#2202]
## Environment

Safari - any version

- @draft-js-plugins/editor version:  0.11.7
- plugin name and version: mention version 4.2.0

## Description

Mention plugin produces a syntax error in the Safari browser:
**Invalid regular expression: invalid group specifier name**
This is due to the plugin using  Regex lookbehinds ex. (?<=\/) which are not supported by Safari

## Reproducible Demo

1. Use the plugin on any project
2. Open project on Safari
3. See error in dev tools

**Comment by fxOne** [comment]
Can you update to the latest version as #1846 should have fixed it?

**Comment by Epicurean** [comment]
thank you! I believe that did the trick
