### ISSUE TITLE
[mention-plugin] HTML as a mention

### ISSUE THREAD

**Issue by redaben** [draft-js-plugins/draft-js-plugins#2223]
## Describe the feature

It would be great if the "name" prop of a mention/suggestion can handle HTML. For the moment, the mention can only be a string. 

Is there any workaround ? 🙏

**Comment by fxOne** [comment]
You can use `mentionComponent` to set a custom renderer for the mentions. For an example go to https://www.draft-js-plugins.com/plugin/mention and look for the `Custom Mention Component Example` example.

**Comment by redaben** [comment]
@fxOne If I put some HTML in the name prop and I select the mention, the value (HTML) is added to the EditorState as a text and I don't know if it is possible to convert it to blocks.

**Comment by fxOne** [comment]
React is always escaping the output. You can read more about it here: https://reactjs.org/docs/dom-elements.html#dangerouslysetinnerhtml
If you want to use `dangerouslySetInnerHTML` you need to write your own `mentionComponent` as it is out of scope to support HTML by default.

**Comment by fxOne** [comment]
@RichMatthews You should look at the [Custom Mention Component Example](https://www.draft-js-plugins.com/plugin/mention) example

**Comment by RichMatthews** [comment]
@fxOne I've tried that but it was being odd. it seems to be generating my code as: 
`<p>&lt;p&gt;&lt;strong&gt;some text&lt;/strong&gt;&lt;/p&gt; </p>`and then spitting it out as `<p> some text </p>`

do you know how to convert that to rich text format?

**Comment by fxOne** [comment]
@RichMatthews can you create a https://codesandbox.io example?

**Comment by fxOne** [comment]
You should not add them there. Use a custom mention component to add the `<p>` Tags. 
```js
    const mentionPlugin = createMentionPlugin({
      mentionComponent(mentionProps) {
        return (
          <p>{mentionProps.mention.name}</p>
        );
      },
    });
```
