### ISSUE TITLE
Resizeable plugin has issue with width and height

### ISSUE THREAD

**Issue by ashurbeyli** [draft-js-plugins/draft-js-plugins#2234]
- @draft-js-plugins/editor version: v.4.1.0
- plugin name and version: resizeable@v.5.0.2

## Description

After resizing image entity data has wrong values for `width` and `height`. So the main problem is that `height` is always set as `0` zero, instead of `null` or `undefined`. And when `defaultValue` is generated from entity data it is something like this:

```
<img src="../pic.jpg" width="100" height="0" /> 
```
In addition,  value of `width` attribute has to be with percentage instead. Like, `width="100%"`.

## Reproducible Demo

You can reproduce issue in this codesandbox: [https://codesandbox.io/s/stoic-butterfly-oeifg
](https://codesandbox.io/s/stoic-butterfly-oeifg
)
1. Resize Image
2. Check the console logs
3. Check `entityMap[0].data`

**Comment by fxOne** [comment]
I tried your Demo and the image is displayed as:

```html
<img direction="LTR" src="https://www.draft-js-plugins.com/images/canada-landscape-small.jpg" role="presentation" class="f1vn2c6d" style="position: relative; width: 96%; cursor: default;">
```
Where can I find the `width="100" height="0"` issue there?

In the entityMap I can find the `height: 0` issue:
```
data: {
  height: 0,
  src: "https://www.draft-js-plugins.com/images/canada-landscape-small.jpg" ,
  width: 96,
}
```

**Comment by ashurbeyli** [comment]
@fxOne exactly! Having `height: 0` in entityMap later makes a problem while converting `stateToHtml` in order to create `defaultValue`.

**Comment by ashurbeyli** [comment]
After some investigation I found out that issue is in my code base more than in this plugin. So,

I used `stateToHtml` function from `draft-js-export-html` lib, but forgot to pass options parameter in order to export html from EditorState. So, I just passed entityStyFn like below to fix issues I face:

```
entityStyleFn: (entity) => {
    const entityType = entity.get('type').toLowerCase();
    if (entityType === 'image') {
      const data = entity.getData();

      return {
        element: 'img',
        attributes: {
          src: data.src,
          width: data.width ? `${data.width}%` : undefined,
          height: data.height ? `${data.height}%` : undefined,
        },
        style: {
          float: data.alignment,
        },
      };
    }
  },
```
