### ISSUE TITLE
side-tool-bar plugin latest version, menu not always opens to the right direction

### ISSUE THREAD

**Issue by ilanskogan** [draft-js-plugins/draft-js-plugins#2252]
Hi, few weeks ago i opened [this issue](https://github.com/draft-js-plugins/draft-js-plugins/issues/2182) about the menu that didn't open in the right direction. you guys closed it with a PR that uses popper.js as the menu block and it should have fixed the issue. however, for my scenario in certain screens, it's still not perfect I would like to know if I can do something about it.
you can see here it doesn't open to the top despite it should because there is not enough room for it at the bottom.
<img width="1429" alt="Screen Shot 2021-08-09 at 16 55 01" src="https://user-images.githubusercontent.com/71634959/128717822-69ba9d6b-5f87-462e-97c4-6dbe6974795a.png">
if I go a few rows under it finally opens to the top 
<img width="1417" alt="Screen Shot 2021-08-09 at 16 56 09" src="https://user-images.githubusercontent.com/71634959/128717995-412c43e4-9a65-4ba7-a2d6-deaa3756c1b7.png">

I will add that with a big enough screen I don't have those problems but on my MacBook 13 inch it's buggy

i also considered rendering that list separately not inside the plugin, and then just use a custom button with the plugin so it will dispatch an action on click and I could handle the visibility of the list, but I can't disable the render of the default plugin list and I cant run the onClick callback on my custom button.

**Comment by fxOne** [comment]
As you should be able to configure `popper.js` as you want I don't see any issue here. If we can improve our default settings please let us know how.

You can find the `popper.js` documentation over here: https://popper.js.org/
