### ISSUE TITLE
Inline Toolbar Plugin not opening on text selection

### ISSUE THREAD

**Issue by AlexandreKilian** [draft-js-plugins/draft-js-plugins#2266]
## Environment

- react: 17.0.2
- @draft-js-plugins/editor version: ^4.1.0
- @draft-js-plugins/inline-toolbar: ^4.1.2

## Description

When using Inline Toolbar, the toolbar isn't opened upon selecting text. Code is taken from example (https://www.draft-js-plugins.com/plugin/inline-toolbar)

## Reproducible Demo

https://codesandbox.io/s/draft-js-inline-toolbar-demo-52318

**Comment by fxOne** [comment]
You need to move the `InlineToolbar` outside of the `Editor`:

```jsx
<div className="App">
  <Editor
    editorState={editorState}
    onChange={onChange}
    plugins={plugins}
  />
  <InlineToolbar />
</div>
```

**Comment by AlexandreKilian** [comment]
Oh, my bad 🙈
