### ISSUE TITLE
Website down www.draft-js-plugins.com/

### ISSUE THREAD

**Issue by anubhav-gig** [draft-js-plugins/draft-js-plugins#2271]
## Environment

- @draft-js-plugins/editor version:
- plugin name and version:

**Comment by fxOne** [comment]
https://www.draft-js-plugins.com/ is currently working for me. Can you give me some more information? 
Maybe there are some DNS issues?

**Comment by anubhav-gig** [comment]
Our ISP blocked it . Now able to access it via mobile data.
