### ISSUE TITLE
Cursor issue with the Heart Emoji

### ISSUE THREAD

**Issue by nikgraf** [draft-js-plugins/draft-js-plugins#230]
![out](https://cloud.githubusercontent.com/assets/223045/14689810/bcbba96a-06fd-11e6-9916-ef263dbbb222.gif)

```
rafalp [1:15 PM] 
here you can see that pressing left moves cursor from <heart>a|b right before emoji
I was guessing that emoji's length is the factor, but this seems to happen for heart exclusively
```

**Comment by nikgraf** [comment]
In general we might be able to restructure & optimise the HTML structure by applying data attributes manually.

**Comment by rafalp** [comment]
I can no longer reproduce the bug using emoji demo. Perhaps it was fixed off-chance by something else?

**Comment by nikgraf** [comment]
Yep, we did some fixes in the meantime 👍
