### ISSUE TITLE
[@draft-js-plugins/linkify] Linkify plugin crashes when double space is changed to a full stop.

### ISSUE THREAD

**Issue by MichalJani** [draft-js-plugins/draft-js-plugins#2301]
## Environment

I have replicated this issue on the following env:
MacOS Big Sur 11.5.2 with Keyboard setting 'Add full stop with double-space' checked.
Chrome 92.0.4515.159
![image](https://user-images.githubusercontent.com/33907954/132496035-6fa8b4cc-fb4b-404c-a26b-cda0eb5862fe.png)

- @draft-js-plugins/editor version: 4.1.0
- @draft-js-plugins/linkify version: 4.1.1

## Description

When typing a link eg. 'www.google.com' and pressing space twice (double-space), text editor moves the indicator to the beginning of the link. If there was a text before link, the link spawns at the beginning of the line. If there was no text present, typing in the same line causes crash. The text-that-should-be-a-link cannot be deleted.
This issue does not happen with a regular text.

https://user-images.githubusercontent.com/33907954/132498364-1a46ab93-1038-4ae5-acb0-301ba458cee2.mp4

## Reproducible Demo
[codesandbox](https://codesandbox.io/s/draft-js-plugins-linkify-plugin-crashes-when-double-space-is-changed-to-dot-yze76?file=/src/TextEditor.tsx)

**Comment by fxOne** [comment]
Same issue as in #1740.

Hopefully someone with a Mac can solve it.

**Comment by MichalJani** [comment]
There is currently an issue open for draft's behaviour on double space when invoked after a decorator. 
https://github.com/facebook/draft-js/issues/2422
One of the comments offers a workaround.
This issue can be closed.
