### ISSUE TITLE
Add propTypes for `mentions` list provided to the MentionSuggestions

### ISSUE THREAD

**Issue by nikgraf** [draft-js-plugins/draft-js-plugins#231]
Multiple times people missed that the mentions need to be an Immutable List with entries that are Immutable Maps.

We should have propTypes to warn them about it.

**Comment by tedlin182** [comment]
Yeah it wasn't clear to me either until I started debugging errors. Something in the docs also would be helpful.

**Comment by juliankrispel** [comment]
This isn't an issue anymore, people can now use plain objects as well...
