### ISSUE TITLE
Mention Plugin - Error thrown when displaying mentions in readOnly Editor

### ISSUE THREAD

**Issue by yuenanto** [draft-js-plugins/draft-js-plugins#232]
Mentions are correctly inserted in the Editor in editing mode but do not work in **readOnly** mode.
The thrown error: ```Unhandled promise rejection TypeError: mention.has is not a function(…)```

**Details of the error**
The error comes from [this code](https://github.com/draft-js-plugins/draft-js-plugins/blob/master/draft-js-mention-plugin/src/Mention/index.js#L8) ```if (mention.has('link'))```
As ```Entity.get(entityKey)``` returns an [object](https://github.com/facebook/draft-js/blob/master/src/model/entity/DraftEntityInstance.js#L48), the code tries to use .has() on an Object so it throws an exception.

**Scenario to reproduce this error:**
1. In edit mode : add some mentions
2. Save your rawContent somewhere like in a database so you can reuse it later (My sample below)
3. Display your content in an **readOnly** Editor

If you want to test it quickly, here is my rawContent:
```
{"entityMap": {"0": {"type": "mention", "mutability": "IMMUTABLE", "data": {"mention": {"link": "/user/17", "name": "Maxime Rota", "avatar": "http://1A922.http.par01.cdn.softlayer.net/preprod/line_operator.jpg"}}}}, "blocks": [{"key": "en8l2", "depth": 0, "inlineStyleRanges": [], "type": "unstyled", "entityRanges": [{"key": 0, "length": 11, "offset": 0}], "text": "Maxime Rota "}]}
```

**Comment by sptessier** [comment]
I'm having the same issue. Not sure it's related to the readOnly prop because I'm still having the issue even after removing readOnly from props.

Have you found any workarounds?

**Comment by Stanley** [comment]
Here is the workaround that solved this issue for me:
```js
var fromJS = require('immutable').fromJS

_.forEach(rawContent.entityMap, function(val, key) {
  val.data.mention = fromJS(val.data.mention)
})

var contentState = Draft.convertFromRaw(rawContent)
var editorState = Draft.EditorState.createWithContent(contentState)
```
Hope this helps with finding more permanent solution for this bug.

**Comment by nikgraf** [comment]
@Stanley thanks for these insights, that definitely helps to get a better understanding whats going wrong 😄

**Comment by sptessier** [comment]
@Stanley Thanks your workaround work for me as well. :-)

**Comment by juhaelee** [comment]
@Stanley @sptessier Mind telling me which versions of draftjs & mentions you guys are using? I'm attempting to display mentions in read only mode but I'm getting no styling as well no errors thrown

**Comment by nikgraf** [comment]
@Stanley did it work in readOnly mode then or did you just try in edit mode? I'm wondering if readOnly is an issue or if just the conversion that caused the issue.

btw this issue come up so many times. I start to think it’s a flaw in my original design. It sounded so nice to have all data being Immutable, but it simply isn't coming from the backend over JSON 😄

**Comment by sptessier** [comment]
@juhaelee    
Here's a snapshot from my packages.json:

"draft-js": "^0.7.0",
"draft-js-mention-plugin": "^1.0.1",
"draft-js-plugins-editor": "^1.0.1",

@nikgraf You may be right that the problem could be linked to immuatable structures. Even after using @Stanley workaround to call immutable's fromJS function, 

I'm having issues making the mention link feature work. Let me know if I can help with anything

**Comment by hervejegou** [comment]
@Stanley workaround (FromJS() ) does work to display properly from a saved rawContent...
BUT it seems to add a lot of data to the mention object/map loaded in the editorState and if you do edit/save again and again, the saved rawContent object keeps getting really bigger and bigger? until the browser cannot handle anymore and throws errors...

**Comment by nikgraf** [comment]
This got already fixed in the latest version of the mentions plugin. It not accepts immutable data structures as well as plain JS objects: https://github.com/draft-js-plugins/draft-js-plugins/pull/326
