### ISSUE TITLE
TypeError: Cannot read property 'decorators' of null

### ISSUE THREAD

**Issue by sugarshin** [draft-js-plugins/draft-js-plugins#233]
In [this line](https://github.com/draft-js-plugins/draft-js-plugins/blob/master/draft-js-plugins-editor/src/Editor/index.js#L109) you will receive an error such as the following.

```
TypeError: Cannot read property 'decorators' of null
```

What about a null equivalent judgment?

```js
if (result) {}
```

**Comment by nikgraf** [comment]
@sugarshin sounds good. Wanna do a PR?

What about being more explicit & check for not undefined & not null?

**Comment by nikgraf** [comment]
Just publish 1.0.1 including this fix.
