### ISSUE TITLE
[Editor plugin] Unable to delete/edit the typed message.

### ISSUE THREAD

**Issue by ilyasf** [draft-js-plugins/draft-js-plugins#2334]
When I'm typing message by using Mac suggestions panel I'm not able to delete or edit the typed message.
Sometimes it's working well, but just focus out and focus in to typed message or type 3-4 time and it stops working at all.

onChange in editor returns editorState where ContentState text is not changing (still be typed message, not removed last charcter)

**Comment by fxOne** [comment]
Can you please get a little bit more into detail? 
- Are you using any plugins? If so can you provide a reproducer on [codesandbox](codesandbox.io) or from our website?
- What exactly are you typing? A video might be helpful.
- Can you reproduce the issue on the `draft-js` website?

**Comment by ilyasf** [comment]
The same problem in `draft.js` site. I will record and upload video ASAP.

**Comment by ilyasf** [comment]
https://user-images.githubusercontent.com/3368047/135070396-7022b59f-df02-4bd5-9904-29613a70cc1a.mp4

this is sample example. It happens not always, but focus out and focus in, sometimes, just block editing.

**Comment by fxOne** [comment]
As the issue occurs on https://draftjs.org/ you should make an issue for `draft-js`: https://github.com/facebook/draft-js/issues
