### ISSUE TITLE
Support for formatting options applied to selected text in editor

### ISSUE THREAD

**Issue by ironfroggy** [draft-js-plugins/draft-js-plugins#235]
This is a fantastic looking widget, and the plugins already are a great start to an ecosystem. But if this only can apply to otherwise unformated text, the applicable use cases are really diminished. Is it considered within the scope of this project to support basic text formatting options, either in its core or via plugins? Would the current system support a plugin adding this?

**Comment by nikgraf** [comment]
@bkniffler is currently working on a rich text editing toolbar. you can follow his progress here: https://github.com/draft-js-plugins/draft-js-plugins/tree/wysiwyg/draft-js-toolbar-plugin

**Comment by bkniffler** [comment]
Yes, the inplace text-toolbar works fine and I'm positive it will be merged by the end of next week at latest. Check it out @ironfroggy and tell us if that helps. If not, we are happy about feedback and/or contributions!

**Comment by juliankrispel** [comment]
there's been an inline-toolbar-plugin added to the repo since
