### ISSUE TITLE
Popover with mentions is not working

### ISSUE THREAD

**Issue by AlvaroIHS** [draft-js-plugins/draft-js-plugins#238]
Hi @nikgraf! I have a problem when I try clean the textarea. Right now I added this code for clean it. But after cleaned, when I write "@" the mentions's list not appear. Thanks! 

    componentDidMount() {
        document.addEventListener('clearEditor', this.clearContent)
    }

    componentWillUnmount() {
        document.removeEventListener('clearEditor', ()=> {})
    }

    clearContent() {
        this.setState({editorState:  EditorState.createWithContent(ContentState.createFromText(""))})
    }

**Comment by nikgraf** [comment]
@AlvaroIHS the issue here is that the editorState contains the decorators to trigger the @ mentions. You should not re-create a new editorState from scratch, but rather update it. Make sure to only update the contentState.

**Comment by AlvaroIHS** [comment]
But how I update contenState?. All methods of it are get or create (https://facebook.github.io/draft-js/docs/api-reference-content-state.html#content) The editorState and contentState are immutable, right?. Sorry, maybe I don't understand you.

**Comment by nikgraf** [comment]
@AlvaroIHS described it here:
https://github.com/draft-js-plugins/draft-js-plugins/issues/251#issuecomment-216287520

**Comment by AlvaroIHS** [comment]
Thanks! :smile:
