### ISSUE TITLE
Placeholder

### ISSUE THREAD

**Issue by AlvaroIHS** [draft-js-plugins/draft-js-plugins#239]
Hi! Right now the placeholder it's in black color and you can't write in the same line on textarea. I added this lines to your style. I think that it's better, because the placeholder has appearance as real placeholder. 

```
.public-DraftEditorPlaceholder-inner {
  position: absolute;
  color: #aaaaaa;
}
```

**Comment by nikgraf** [comment]
Can you elaborate a bit more on this? Maybe with screenshots. I'm don't understand the issues …

**Comment by AlvaroIHS** [comment]
The first input is like appear without the code that I put above. I don't know if a issue or not but I think that the second input has appearance as real placeholder. Do you understand me?

![example](https://cloud.githubusercontent.com/assets/10597575/14920265/76197e6e-0e24-11e6-9e63-b09318966619.png)

**Comment by adrianmc** [comment]
@AlvaroIHS I had this problem a while back. I recall it being a CSS issue.

**Comment by AlvaroIHS** [comment]
I only added those lines in plugin.css file and that's all. :smile:

**Comment by nikgraf** [comment]
@AlvaroIHS I would assume this is an issue with the core itself as we don't overwrite the draft editor styles in the plugin system. What happens if you use the draft-js editor without plugins in your codebase?

**Comment by SachaMPS** [comment]
@AlvaroIHS Use the css contained in the draft.js repo as a starting point. Placeholders whould work as expected afterwards:
https://github.com/facebook/draft-js/blob/master/src/component/utils/DraftStyleDefault.css

**Comment by nikgraf** [comment]
thx @SachaMPS, we should add this as well to our planned FAQ site & gettibg started docs

**Comment by zayaisshawn** [comment]
Go to your developer console and find class for placeholder div then add 
`position: absolute; ` 
for the placeholder div in your css.

**Comment by nikgraf** [comment]
Just added this topic to the FAQ 😄 
https://github.com/draft-js-plugins/draft-js-plugins/blob/master/FAQ.md#my-default-styles-are-broken

**Comment by ramisalem** [comment]
> @AlvaroIHS Use the CSS contained in the draft.js repo as a starting point. Placeholders would work as expected afterward:
> https://github.com/facebook/draft-js/blob/master/src/component/utils/DraftStyleDefault.css
where should I add that file?
