### ISSUE TITLE
The document link does not exist.

### ISSUE THREAD

**Issue by hatsu38** [draft-js-plugins/draft-js-plugins#2405]
## Environment

```
"name": "@draft-js-plugins/docs",
"version": "4.0.0",
```

- @draft-js-plugins/editor version: 4.0.0
- plugin name and version: alignment, counter, divider, drag-n-drop, emoji, focus, hashtag, image, inline-toolbar, linkify, mention, side-toolbar, static-toolbar, sticker, undo

#### Current
```js
<ExternalLink href="https://github.com/draft-js-plugins/draft-js-plugins/blob/master/docs/client/components/pages/Mention/index.js">
```
→ 404 not found

```js
<ExternalLink href="https://facebook.github.io/draft-js/docs/advanced-topics-entities.html#mutability">
```
→ 404 not found

#### Correct?

```js
<ExternalLink href="https://github.com/draft-js-plugins/draft-js-plugins/blob/master/packages/docs/pages/plugin/mention/index.tsx">
```
→ 200

```js
<ExternalLink href="https://draftjs.org/docs/advanced-topics-entities/#mutability">
```
→ 200

## Reproducible Demo

https://user-images.githubusercontent.com/16137809/139566947-03f39f51-42ba-4666-9237-1ff2e915d50d.mov

**Comment by fxOne** [comment]
Thanks for the report. I have moved the fixed link to the footer as "Edit on Github" link.

**Comment by hatsu38** [comment]
Thank you very much. I have confirmed that it is fixed. I'm so happy!
