### ISSUE TITLE
Invalid hook call error in MentionSuggestionsPortal component when mentions trigger keyword is entered 

### ISSUE THREAD

**Issue by Karthickbg** [draft-js-plugins/draft-js-plugins#2422]
## Environment

Encountered this error on Windows 10 with "react": "^16.14.0"

- @draft-js-plugins/editor version: "^4.1.0"
- plugin name and version:  "@draft-js-plugins/mention": "^4.5.2"

## Description

When the trigger keyword is entered in editor, the app is breaking with error "Uncaught Error: Invalid hook call"
![image](https://user-images.githubusercontent.com/22284372/141070845-8a3e396a-11ec-4ff5-9f15-3529df464378.png)

## Reproducible Demo

Here's the reproducible code sandbox link - https://codesandbox.io/s/getting-started-with-draft-js-plugins-forked-mrxxm?file=/src/DraftEditor.js

**Comment by fxOne** [comment]
You need at least react 16.8 for hook support.
