### ISSUE TITLE
Linkify Behavior when adjacent to a parenthesis

### ISSUE THREAD

**Issue by thebritican** [draft-js-plugins/draft-js-plugins#244]
### Question

Should Linkify link email addresses or websites when they are placed inside parenthesis?

### Use Case

When people respond and type out links, they may want them inside parenthesis.

![](http://g.recordit.co/cNOSU85Jka.gif)

**Comment by raphaelsaunier** [comment]
In my opinion, yes. Although that's something that would need to be fixed upstream in the [linkify-it](https://github.com/markdown-it/linkify-it.git) module.

**Comment by nikgraf** [comment]
@thebritican good find, fix and published a new release
