### ISSUE TITLE
Cannot use multi character triggers 

### ISSUE THREAD

**Issue by alessio-de-padova** [draft-js-plugins/draft-js-plugins#2451]
I am using Draft JS in my React application. 

  "draft-js": "^0.11.7",
  "draft-js-mention-plugin": "^3.1.5"

I am trying to use multi character mentions as shown in the documentation but it does not seem to work. 

If I configure my mention plugin as shown below all works fine. 
 
`const mentionPlugin = createMentionPlugin({
    mentionTrigger: "@",
    mentionComponent(props) {
        return (<Mention props={props}/>)
    }
});`

But when I try and add another trigger it does not work at all. 

` const mentionPlugin = createMentionPlugin({
    mentionTrigger: ["@", "("],
    mentionComponent(props) {
        return (<Mention props={props}/>)
    }
});`

Why does this happen? The ability to support multi character triggers would be of great help to me (I need different ajax calls depending on the trigger) and would avoid me the struggle of repeating lots and lots of code (e.g. mentionPlugin2, mentionPlugin3 etc.)

I have another problem withthe onSearchChange handler. Whereas I can see the value prop, the trigger always seem to be undefined.

**Comment by fxOne** [comment]
You need to update to latest version of `@draft-js-plugins/mention`: https://www.npmjs.com/package/@draft-js-plugins/mention
The multi mention feature was added with version `4.3.0`

**Comment by alessio-de-padova** [comment]
I am using  "@draft-js-plugins/mention": "^5.1.0",

**Comment by alessio-de-padova** [comment]
Thanks. That fixed the problem!
