### ISSUE TITLE
Hashtag not working well with UTF-8

### ISSUE THREAD

**Issue by thanhtungdp** [draft-js-plugins/draft-js-plugins#247]
DraftJs Plugins is awesome. Thank you your team.
 But i have problem with hashtag. When i type utf-8 character then not working well.
Like this
<img width="698" alt="screen shot 2016-04-30 at 12 37 24 pm" src="https://cloud.githubusercontent.com/assets/4653102/14934102/5fda5f54-0ed0-11e6-9837-05c54d358760.png">

**Comment by nikgraf** [comment]
@thanhtungdp thanks for reporting this bug. We need to improve the logic identifying hashtags and there was some discussion, but I didn't took the time yet to dig deeper and experiment with a possible solution.

More infos here: https://github.com/draft-js-plugins/draft-js-plugins/issues/11

Would you be interested to take care of it?

**Comment by adrianmc** [comment]
Not sure if this is any help, but I couldn't sleep so I googled around and found this: https://github.com/twitter/twitter-text/commit/408c69d73462fea0c4ff08f4ed2084d33ade485b

It's kind of crazy, yet fascinating.

**Comment by nikgraf** [comment]
nice, the diff is actually quite useful … @adrianmc wanna pick this up?

**Comment by adrianmc** [comment]
@nikgraf will do, but as @mxstbr said in the other issue, it'd likely come down to a judgment call for whether or not we want to re-implement the entire implementation that Twitter has settled on.

I'll try to extract the necessary elements from that library first, and then we'll see how huge it is and maybe we'll decide whether or not we want to take all of it.

**Comment by adrianmc** [comment]
Okay, it was kind of tricky but I got it done. Twitter basically has [8.39 KB](https://github.com/adrianmc/twitter-hashtag/blob/master/app/hashtagRegex.js) of special characters that they use to parse hashtags.

I've created a repo here: https://github.com/adrianmc/twitter-hashtag

And a quick demo (based on Brunch 😄 ) here: http://adrianmcli.com/twitter-hashtag/

Question is, how much of this should we integrate into the hashtag plugin? All of it?

@nikgraf @mxstbr Thoughts?

**Comment by thanhtungdp** [comment]
I have use regex, it's simple
const HASHTAG_REGEX = /\S*#(?:\[[^\]]+\]|\S+)/g;
It's work fine
<img width="216" alt="screen shot 2016-05-03 at 10 21 49 am" src="https://cloud.githubusercontent.com/assets/4653102/14973935/e199cc92-1118-11e6-84c3-77e9ed886ca3.png">

**Comment by adrianmc** [comment]
I've added a PR for this issue. It uses Twitter's detection method, so it's _bulletproof_ in that sense, but it may be overkill. It seems that @thanhtungdp's regex above works well enough. So maybe we should consider that first?

**Comment by nikgraf** [comment]
@adrianmc I'm reviewing your PR right now. Fantastic work!

@thanhtungdp might work as well. I'm like the Twitter strategy more, because it's a whitelist approach rather than a blacklist approach. Except some minor things to improve I would merge the PR and consider this issue as resolved. What are your thoughts?

**Comment by nikgraf** [comment]
@thanhtungdp just release 1.1.0 of the Hashtag plugin 😄 let us know if it works well for you
