### ISSUE TITLE
Add FlowType declarations

### ISSUE THREAD

**Issue by ryyppy** [draft-js-plugins/draft-js-plugins#248]
So I have been looking into it and thought about how we could ship flowtype declarations with it's specific draftjs-plugin. 

Just to make this explicit, it turns out that creating something like a `index.js.flow` should simulate the exports of the actual `lib/index.js` file and during the build / publish process, the file should be copied to the `lib` directory.

There are still some points open, especially of how we define dependencies to DraftJS types... right now it is common to put declarations in the global scope and namespace stuff with `$`... e.g.  `React$Component`... for now, until the DraftJS project gets things settled, we could write our own DraftJS libdef file, which drops our stuff we need in the `Draft$` namespace.

@nikgraf we can talk about it on Monday at the meetup

**Comment by nikgraf** [comment]
@ryyppy ideally we would submit a PR to the DraftJS repo to export the types directly and re-used them, but it's also fine to come up with our own for now

a flow file per package sounds good to me - let's discuss tonight 😄

**Comment by juliankrispel** [comment]
Closing for issue cleanup - If you need this issue and think it should remain open please let us know why, thank you
