### ISSUE TITLE
Enter key is not working on inline buttons - Accessibility 

### ISSUE THREAD

**Issue by Tejas-TBF** [draft-js-plugins/draft-js-plugins#2489]
## Environment

- @draft-js-plugins/buttons version: 4.1.1

## Description
When enter key is pressed on any inline buttons such as BoldButton, CodeButton, ItalicButton or UnderlineButton etc, respective inline styles are not applied or removed. Works fine when mouse clicked on the buttons.

This is useful for visually impaired users who cannot use mouse. Users must be able to select any text in the editor and press tab key which focuses the toolbar buttons, and when bold/italic/underline etc button is clicked, inline styles must be applied to the selected text.

Please provide some resolutions.

**Comment by fxOne** [comment]
Can you provide a fix?

**Comment by Tejas-TBF** [comment]
> Can you provide a fix?

I was hoping you guys can provide some solutions for me.

**Comment by fxOne** [comment]
How should a button get the focus so that the enter key should work? You cannot tab out as this would remove the focus from the editor. 
Also the github editor does not support this feature as far I can see.

**Comment by Tejas-TBF** [comment]
> How should a button get the focus so that the enter key should work? You cannot tab out as this would remove the focus from the editor. Also the github editor does not support this feature as far I can see.

Can`t Draftjs editor maintain selection when tab key is pressed (except when the focus in on numbered/unordered list) and move the focus to the toolbar action buttons, given toolbar is placed at the bottom of the editor? 
Azure devops editor has this feature. This will make the editor fully accessible for all users.

**Comment by gargigoyal-ga** [comment]
llll
