### ISSUE TITLE
Double space period breaks mention plugin

### ISSUE THREAD

**Issue by Benrski** [draft-js-plugins/draft-js-plugins#2490]
### Browser

- Chrome
- Firefox
- Safari

### Plugin

- @draft-js-plugins/editor version: 4.1.0
- @draft-js-plugins/mention version: 5.1.0, 5.0.0, 4.6.1

## Description

If there are no characters after a mention and you press double space immediately after it the editor will break.
Sometimes it stops working, other times it crashes.

## Reproducible Demo

[DraftJS Plugins](https://www.draft-js-plugins.com/plugin/mention)
- Simple Example: editor stops working (undo, redo, delete, ...)
- Custom Themed Mention Example: editor crashes

https://user-images.githubusercontent.com/15658144/146905133-86fc0594-082f-4871-b581-e749e1b05b32.mp4

**Comment by fxOne** [comment]
Duplicated to #1740. 

Would be cool if you could look into is as I have no access to a Mac.
