### ISSUE TITLE
Can not add 👍 emoji support with `:+1:` syntax

### ISSUE THREAD

**Issue by vasiastep** [draft-js-plugins/draft-js-plugins#2494]
## Description

I am using `draft-js` with `@draft-js-plugins/emoji` plugin

Wanted to add 👍 inline emoji support not only with `:thumbsup:` syntax but also with `:+1:` syntax

After extending priority list:

```
priorityList: {
  ':+1:': ['1F44D'],
  ':see_no_evil:': ['1f648'],
  ':raised_hands:': ['1f64c'],
  ':100:': ['1f4af'],
  ':joy:': ['1F602'],
  ':ok_hand:': ['1F44C'],
  ':heart:': ['2764'],
  ':smile:': ['1F601'],
  ':tada:': ['1F389'],
},
```

I understood typing inline `:+` just breaks emoji suggestions. I think its because of `+` sign, as `onSearchChange` of `EmojiSuggestions` component stops executing either. 

Is there a way to add 👍  inline emoji with `:+1:` syntax ?

**Comment by fxOne** [comment]
The `priorityList` cannot be used to add new emojis, it can change only the priority of how the entries are shown. It is currently not possible to a `:+1:` syntax
