### ISSUE TITLE
Mentions are not compatible with useEffect

### ISSUE THREAD

**Issue by qhenkart** [draft-js-plugins/draft-js-plugins#2519]
## Environment

normal set up, react hooks, following the docs exactly

- @draft-js-plugins/editor version: 4.1. 
- plugin name and version: mention 5.1

## Reproducible Demo

Here's an [example that uses the mentions plugin](https://codesandbox.io/s/MjG72jX2R) - this will help get you started
**The link to the working example in the template is broken**

If you need a working example, if you wouldn't mind sharing a fixed version of the above link, it would save me a lot of time. Otherwise I think this is a known feature of mentions so I'm not sure if it's necessary. 

The following useEffect logic I am using overwrites the mention plugin is the following.

Each one overwrites the mention plugin. I feel like the incompatibility with useEffect should be a primary focus in the docs, or, even more ideally, the plugin should be compatible with this hook

```
useEffect(() => {
    if(props.focusOnMount){
      // timeout is required otherwise it overwrites the mentions plugin
     editor.current.focus()
    }
  }, [])

// this hook is used to update the editor state from realtime events 
useEffect(() => {
    let es = getEditorStateFromRaw(props.content))

    // timeout is required otherwise it overwrites the mentions plugin
   setEditorState(es)

  }, [props.content])
```

**Comment by fxOne** [comment]
Thanks for reporting the broken link. It looks like codesandbox removes templates after a while.

I will add a note to the FAQ page that if you create a new `EditorState` it will not have the decorators which are added by `draft-js-plugins`.

**Comment by qhenkart** [comment]
@fxOne Is there a workaround? Is it possible to modify the editorstate instead of replace it or reapply the decorators to the new one?

**Comment by fxOne** [comment]
You can find the documentation here: https://draftjs.org/docs/advanced-topics-decorators/#setting-new-decorators

**Comment by qhenkart** [comment]
Thank you. In the end I just updated the editor state instead of replacing it which preserves the decorators. https://draftjs.org/docs/api-reference-editor-state/#push

Closing

**Comment by fxOne** [comment]
I'll reopen this issue as I want to add some notes to the FAQ to make the issue clear and provide some links to the solutions
