### ISSUE TITLE
MentionSuggestions component override

### ISSUE THREAD

**Issue by nadimtuhin** [draft-js-plugins/draft-js-plugins#252]
Need to override MentionSuggestions component as its keying with name 

https://github.com/draft-js-plugins/draft-js-plugins/blob/master/draft-js-mention-plugin%2Fsrc%2FMentionSuggestions%2Findex.js#L261

Also would love to have an api that gives us the opportunity to override other components.

**Comment by nikgraf** [comment]
Sounds good to me. How do you imagine the config to look like for such a case?

**Comment by nadimtuhin** [comment]
Have not thought about it yet. I will :)

**Comment by mjrussell** [comment]
Might be related to making the autocomplete more flexible in https://github.com/draft-js-plugins/draft-js-plugins/issues/78#issuecomment-218204891

**Comment by Zhouzi** [comment]
@nadimtuhin There's a pull request adding an option to provide a custom key getter https://github.com/draft-js-plugins/draft-js-plugins/pull/318 and another one adding an option to use a custom component for each suggestions' entry https://github.com/draft-js-plugins/draft-js-plugins/pull/327

**Comment by nikgraf** [comment]
@Zhouzi I'm believe to use `getMentionKey` properly you need to know a lot about the internals and then you might be better of using `entryComponent` right away.

@nadimtuhin what are your thoughts?

**Comment by Zhouzi** [comment]
Yeah you're right, which makes me wonder if `getMentionKey` is really useful and shouldn't simply be replaced by `entryComponent`. That been said, creating a component to be passed as `entryComponent` requires a deeper knowledge of the internals (especially with the weirdish `{...parentProps}`) while with `getMentionKey` you just have to know how the object returned by your API looks. Let's hear @nadimtuhin's thoughts ^^

**Comment by juliankrispel** [comment]
fixed in #802
