### ISSUE TITLE
Multiple editor mention suggestions do not work 

### ISSUE THREAD

**Issue by nadimtuhin** [draft-js-plugins/draft-js-plugins#253]

**Comment by nikgraf** [comment]
Hey @nadimtuhin, do have a little bit more details? Some code you can share?

**Comment by nadimtuhin** [comment]
I will be in a few hours. Thanks for coming back :)

**Comment by nikgraf** [comment]
ping 😄

**Comment by nikgraf** [comment]
@nadimtuhin any updates here?

**Comment by hervejegou** [comment]
I am trying to use two mention editors suggestions plugins  in the same Editor component: similar to Twitter or Slack , with '@' for mentioning users and with '#' for mentioning channels...

I tried to initialize two mention plugin components :

``` 
const mentionPlugin = createMentionPlugin({ mentionPrefix: '@' });
const { MentionSuggestions } = mentionPlugin;
const mentionPlugin2 = createMentionPlugin({ mentionPrefix: '#' });
const { MentionSuggestions2 } = mentionPlugin2;
const plugins = [mentionPlugin, mentionPlugin2];
```
Also setup onChange2() and suggestions2 state required for the second mention plugin component and initialize properly. 

Then list the two plugins in the render area:
```
<Editor
editorState={this.state.editor}
onChange={this.onChange}
plugins={plugins}
ref="editor"
/>
 <MentionSuggestions
onSearchChange={ this.onSearchChange }
suggestions={ this.state.suggestions }
/>
<MentionSuggestions2
onSearchChange={ this.onSearchChange2 }
suggestions={ this.state.suggestions2 }
/>
```
does not work... it was a long shot anyway... Any advice on whether this is possible??

**Comment by nikgraf** [comment]
@hervejegou the mentionPrefix is just for presentation purposes and not used for matching.

This is the current documentation. Any suggestion on how to improve it? Maybe even create a PR?
```
mentionPrefixBy default it is an empty String. For Twitter or Slack like mention behaviour you can provide an `@`
```

**Comment by yjang1031** [comment]
I've added a trigger option, by adding mentionTrigger to config, passing mentionTrigger to the mentionSuggestionsStrategy, having mentionSuggestionsStrategy return a function instead. (https://github.com/yjang1031/draft-js-plugins/commit/7c8de90cd1522915dce0f2ad102e0cd8c441b533)

But since decorate-component-with-props decorate all Mention components with mentionPrefix of the first mention plugin instance, the code below always prefixes mentions with '@' even when I trigger with '#'. Is there a way I can work around this?

```
const mentionPlugin = createMentionPlugin({ mentionTrigger: '@' , mentionPrefix: '@' });
const { MentionSuggestions } = mentionPlugin;
const mentionPlugin2 = createMentionPlugin({ mentionTrigger: '#', mentionPrefix: '#' });
const { MentionSuggestions2 } = mentionPlugin2;
const plugins = [mentionPlugin, mentionPlugin2];

<Editor
editorState={this.state.editor}
onChange={this.onChange}
plugins={plugins}
ref="editor"
/>
 <MentionSuggestions
onSearchChange={ this.onSearchChange }
suggestions={ this.state.suggestions }
/>
<MentionSuggestions2
onSearchChange={ this.onSearchChange2 }
suggestions={ this.state.suggestions2 }
/>
```

**Comment by yjang1031** [comment]
Update. I found out that it's because the plugin uses mentionStrategy that finds all entities with type 'mention'. I had to modify the plugin such that it creates entity with type "mention-" + mentionTrigger, where default trigger is '@'. For more info, see https://github.com/yjang1031/draft-js-plugins/commit/f37a76321886df4abe1a7def4f1a13a21f967232

**Comment by hervejegou** [comment]
@nikgraf @yjang1031 Thanks for the prompt answers!! really great to see such quick feedback. I hope this can be fixed and released (if that is a good feature to add?). Mentions are really useful and I can think of many use for more than one mention component in a single Editor.

**Comment by nikgraf** [comment]
@yjang1031 interested to create a PR?

**Comment by yjang1031** [comment]
@nikgraf done! :) #320

**Comment by hervejegou** [comment]
@nikgraf : seems like @yjang1031 PR is ready? will wait for plugin update and will try it and confirm. this is  a nice upgrade for mention plugin.

**Comment by nikgraf** [comment]
I will look into it. Thank for your help @yjang1031 👌

**Comment by nikgraf** [comment]
@hervejegou & @yjang1031 what's your use-case. Are you using the @-mentions plugin to search for other things like hashtags or different types of mentions?

**Comment by yjang1031** [comment]
@nikgraf Yes. I had two different types of mentions (not exactly hashtags for my use case), and I needed a way to trigger and decorate the mention plugins separately with different trigger characters.

It's possible that one would choose to use the mention plugin instead of the hashtag plugin for hashtags because of `MentionSuggestions`.

**Comment by nikgraf** [comment]
@yjang1031 ok good to know, yeah I'm currently thinking a lot about how far we should go /w making the plugin flexible. We could also help @mjrussell with his autocomplete creator and recommend this one in case people want other autocompletion: https://github.com/mjrussell/draft-js-autocomplete-plugin-creator

Setting this up is way more flexible, but also harder. Kind of the advanced route. What do you think @yjang1031?

**Comment by oyeanuj** [comment]
> It's possible that one would choose to use the mention plugin instead of the hashtag plugin for hashtags to take advantage of MentionSuggestions.

As an example of the use-case: I would definitely like to do this so as to be able to offer users some in-use hashtags or let them create new ones. StackOverflow, for example, has this behavior.

**Comment by mjrussell** [comment]
I'm in the process of fishing an example of the auto complete plugin which shows how to create a github issue style auto complete. 

Id be happy to accept any help offered on it. I definitely need to work the documentation and I think port a few more recent additions to the mention plugin.

**Comment by hervejegou** [comment]
@nikgraf: I have the same use case as @yjang1031 : I need two mention plugins, one for users (@) and one for channels ( # like slack). with suggestions...

Github uses two also in this comment editor, for users and issues...
 
Regarding Hashtags, I looked at it but it does not have suggestions so the use is more limited (only decorate links for example?)... 

Having an auto complete plugins would be similar and overlap significantly with mention plugins??

**Comment by mjrussell** [comment]
@hervejegou your example is exactly why I wrote the autocomplete plugin creator. It is mostly a more general version of mention, in fact I can create the mention plugin from API of the autocomplete plugin creator! Much of the original code for the autocomplete plugin creator came from the mention plugin.

I don't think that the mention plugin at least in its current state can be flexible enough to work in these type of cases where you want to have greater control over the strategy for showing the suggestions, how each suggestion is rendered, and the editor changes when a suggestion is clicked/onEnter.

I think we are seeing that there is a balance between flexibility and ease of use with these type of plugins. My opinion is that it is better to provide a nice, easy to use API that might be inflexible in some advanced use cases, and also provide a more customizable interface for those who need more advanced features.

**Comment by hervejegou** [comment]
@mjrussell sounds good and yes, mention plugin works well but may be unflexible for different use cases. I will give autocomplete a try this week.. any chance of a brief/draft API documentation?

**Comment by mjrussell** [comment]
@hervejegou now I'll actually have someone pushing me to write the docs 😄 

I just pushed an example that I think does a decent job at explaining the plugin creator interface [here](https://github.com/mjrussell/draft-js-autocomplete-plugin-creator/tree/master/examples/issue).

If you are familiar with the Mention plugin and how it works, it should look somewhat familiar. The quick and dirty bit of it is the following:
```js
const createCompletionPlugin = (
  completionSuggestionsStrategy, // The strategy for displaying the suggestion
  addModifier, // The modifier to invoke when the user selects a suggestion
  SuggestionEntry, // The Component to render for each suggestion entry
  suggestionsThemeKey = 'completionSuggestions', // optional theme key to use with the theme config
  additionalDecorators = [], // optional additional decorators to include in the plugin
)
```

Id be happy to continue this discussion over on the repo as well, I'll make a github issue for creating documentation while Im thinking about it
