### ISSUE TITLE
lodash is not being treeshaken because of version 4.5.0 + of 'mention'

### ISSUE THREAD

**Issue by vithano** [draft-js-plugins/draft-js-plugins#2530]
## Environment
webpack 4

- plugin name and version: mention@latest

## Description

lodash-es is not being treeshaken because of this import
![1D121808-DD34-4107-8EAB-9EBD0DEC4413_4_5005_c](https://user-images.githubusercontent.com/11342649/149024165-1d769cfb-91b9-458f-9ff2-a7d39467ac49.jpeg)

**Comment by fxOne** [comment]
Well it looks like it increase the size by 0.1kb:
before: https://bundlephobia.com/package/@draft-js-plugins/mention@5.1.0
after: https://bundlephobia.com/package/@draft-js-plugins/mention@5.1.1
