### ISSUE TITLE
Ability to specify where the emoticons are referenced.

### ISSUE THREAD

**Issue by stefan1968** [draft-js-plugins/draft-js-plugins#254]
I'm want to be able to specify the location of the svg icons for emoji's, but it seems fixed - here

var imagePathSVG = '//cdn.jsdelivr.net/emojione/assets/svg/';

I'm using Electron/Webpack and it's having difficulty accessing this, due to security reasons.

**Comment by nikgraf** [comment]
@stefan1968 this is now possible with the 1.1.0 release of the Emoji plugin.

see the Changelog here: https://github.com/draft-js-plugins/draft-js-plugins/blob/master/draft-js-emoji-plugin/CHANGELOG.md#110---2016-05-08

**Comment by stefan1968** [comment]
Fantastic, thanks for speedy response!

**Comment by buildog** [comment]
@stefan1968 did you succeed importing the styles with electron/webpack?

**Comment by nikgraf** [comment]
I'm curious too 😄
