### ISSUE TITLE
Mention dropdown not working in Vietnamese keyboard

### ISSUE THREAD

**Issue by phongman** [draft-js-plugins/draft-js-plugins#2543]
## Environment

- @draft-js-plugins/editor version: 4.1.0
- plugin name and version: 4.6.2

## Description

![image](https://user-images.githubusercontent.com/47738751/150065187-ae297322-34f3-4c40-847e-67278303bad8.png)
when i use english keyboard the dropdown still working but when i change to vietnamese keyboard the dropdown doesn't open until i type 'space' or 'backspace', ...
![image](https://user-images.githubusercontent.com/47738751/150065432-f2492d66-43f3-433f-ab7d-07cad3020a5c.png)
I found out that when draftjs in composition mode it doesn't setEditorState so the mention value is still empty. I want to ask there is anyway i can trigger open dropdown in this mode?

## Reproducible Demo

On Win change keyboard to VIE keyboard
On MacOs change keyboard to Telex keyboard
Demo can be reproduce in https://www.draft-js-plugins.com/plugin/mention

**Comment by fxOne** [comment]
As far as I can see Vietnamese characters should be supported: https://github.com/draft-js-plugins/draft-js-plugins/blob/5b73416c47803ab69a639583bf4daa33a736048f/packages/mention/src/defaultRegExp.ts#L29.

You should also be able to set your own RegEx within the `mentionRegExp` plugin option.

If you can find the problem with the RegEx, I would be happy to submit a pull request. I myself have unfortunately no experience with Vietnamese characters.
