### ISSUE TITLE
Inline Toolbar shown only on one instance when multiple editors in page

### ISSUE THREAD

**Issue by valentinvucea** [draft-js-plugins/draft-js-plugins#2552]
## Environment

- react 17 with hooks
- @draft-js-plugins/editor 4.1.1
- @draft-js-plugins/inline-toolbar 4.1.2
- draft-js 0.11.7

## Description

If there are multiple editors in the page the inline toolbar is displayed only on the last editor instance.

## Reproducible Demo
https://codesandbox.io/s/headless-snowflake-8q767

**Comment by fxOne** [comment]
The issue is that you are using the same plugin instance for both editor instances. You need to create a new plugin instance for each editor instance.
