### ISSUE TITLE
Plugins not working after clearing editorState

### ISSUE THREAD

**Issue by vahnag** [draft-js-plugins/draft-js-plugins#256]
There's a button in the app that clears the input. It basically does this:

```javascript
this.setState({
  editorState: EditorState.createEmpty()
});
```
After this the plugins stop working. Anything I do wrong?

**Comment by adrianmc** [comment]
@vahnag check out the answer here: #251 

We get this question maybe once every week, and in all honesty, we probably need to set up an FAQ or a Common Issues section on our website.

**Comment by vahnag** [comment]
Thanks.

**Comment by nikgraf** [comment]
@adrianmc agreed, let's set up more docs next week

**Comment by nikgraf** [comment]
Now part of the FAQ: https://github.com/draft-js-plugins/draft-js-plugins/blob/master/FAQ.md 😄
