### ISSUE TITLE
Ability to test if popover is open or closed.

### ISSUE THREAD

**Issue by stefan1968** [draft-js-plugins/draft-js-plugins#259]
Is there some way of testing if the mention or emoji window is open, some event handler?

Many thanks.

**Comment by nikgraf** [comment]
@stefan1968 not right now, what's your use-case? When would it be useful?

**Comment by stefan1968** [comment]
Ok, for example i'm inputting text and on my handlereturn i need to know weather to invoke the plugins handlereturn (or mine) depending if the popup is open, if i just call mine with the popup open because it resets the editor focus and creates a new state etc, it can cause strange behaviour with the plugin

**Comment by mjrussell** [comment]
👍 for this. I ran into a similar issue when I wanted to handle the enter key in the component that wraps the plugin editor differently depending on if the popover was open or closed. In my case I wanted to submit a comment on enter if the popover is not open.

I found an entirely hacky/temporary solution to this by putting a ref on the suggestion component and doing the following:
```js
this.refs.suggestions._reactInternalInstance._renderedComponent._instance.state.isActive;
```

I think we need to add a `getWrappedInstance` to the `decorate-component-with-props` wrapper which returns the rendered ref (this is common in HOC components like redux's `connect`) and then just expose a public method on the suggestions component for querying if the state is open

**Comment by crossman** [comment]
For what it's worth, I ran into the same thing and this was my temporary, hacky solution (along with a large comment)

```js
if (this.refs.editor.refs.editor.refs.editor.getAttribute("aria-haspopup") == "true")
        return
```

But yeah, I'd love to see a better way to handle this.

**Comment by nikgraf** [comment]
What if we would introduce `onOpen/onClose` on MentionSuggestions itself? Would that solve the issue or did I miss something?

**Comment by crossman** [comment]
That could work. I'd have to listen to those and keep track of the state internally for use in handleReturn, but it would create more opportunity to react to changes in the interface. Anything I can do to help? I haven't looked over the internals much but I really appreciate this project and would be happy to contribute.

**Comment by mjrussell** [comment]
Yeah that should work, should this be a controlled state? 

Like passing the visible flag to it and using the onChange to update the parent state? Or is this just a helper/utility

**Comment by nikgraf** [comment]
@mjrussell I though of it just as a callback and not as controlled state. The state should be controlled by the decorator. To me that's a core-value of the plugin, but I'm curious if there are other case.

@crossman a PR just exposing those in the Emoji & Mentions plugin would be great. Do you know how to do that or should we guide you?

**Comment by crossman** [comment]
@nikgraf I'm on it. One question before I do it, is it worth allowing `onOpen/onClose` to cancel the action?

For example, perhaps the editor is in some state where you don't want the mention plugin to kick in so you could `return false` from `onOpen` and cancel it. I think it would have to be an explicit `false` (meaning `undefined` would be considered the same as `true`) because it seems unnecessarily cumbersome to have to `return true` to get the action to complete.

**Comment by crossman** [comment]
Just thinking about it a little more. Maybe they should be `handleOpen` and `handleClose` and function more like similar `draft-js` methods

**Comment by mjrussell** [comment]
It seems weirder to me to use the onOpen as a handle with true/false rather than making it a controlled state. I agree there might be times when you want to not allow the onOpen/onClose but then you could just not call `setState` in the parent component. I could see this being very useful if you have multiple dropdowns that might interfere with one another.

**Comment by crossman** [comment]
Yeah, I'm really not sure what's right. I mean, opOpen/onClose would suffice for my needs, but I can see the need for more control.

**Comment by nikgraf** [comment]
@mjrussell I'm trying imagine how open/closed could be a controlled state. How would the mention plugin expose this to the outer state and what would the usage API for MentionsSuggestion look like?

@crossman For very specific use-cases it might be worth exploring if a separate plugin might be more useful. I believe there is a point where we have to limits of a plugin. To me this is often when the either Developer or User experience starts to decrease due too much complexity. hmm kind of a very vague process …

**Comment by crossman** [comment]
Fair enough. I guess it'd be getting ahead of things to add that now anyway. I'll put together a PR for onOpen/onClose in the morning.
