### ISSUE TITLE
OnChange executes when Editor created

### ISSUE THREAD

**Issue by developdeez** [draft-js-plugins/draft-js-plugins#2594]
I have used this component to save text onChange. I noticed when I enter the page, it executes the onChange immediately.
My goal was to simply allow saving of the html text.
If this is a bug that's fine. If not, how can I prevent this initial save?

  "@draft-js-plugins/editor": "^4.1.0",
        "@draft-js-plugins/static-toolbar": "^4.1.2",
        "draft-js": "^0.11.7",
        "draft-js-export-html": "^1.4.1",
        "draft-js-import-html": "^1.4.1",

code:
```jsx
 <Editor
            className='settings-my-profile__profile-bio__text pb-3'
            ref={editor}
            editorState={editorState}
            plugins={plugins}
            onChange={e => {
                setSaving(true);
                clearTimeout(typingTimer);
                typingTimer = setTimeout(() => {
                  setSaving(false);
                }, 1500);
                setEditorState(e);
                const text = {
                  target: {
                    value: stateToHTML(e.getCurrentContent()),
                  },
                };
                onChange(text);
            }}
          />
```

**Comment by fxOne** [comment]
I would not recommend to do saving on `onChange` because even a cursor change will trigger this function. You should do it  with a save button or by using the `onBlur` event.

**Comment by developdeez** [comment]
Ok will do thanks

**Comment by developdeez** [comment]
@fxOne I moved it but it errors due to the getCurrentContent not being a function. Do you know where I would be able to get the html to save properly?

`
    onBlur={e => {
              const text = {
                target: {
                  value: stateToHTML(e.getCurrentContent()), //<=Error
                },
              };
              onChange(text);
          }}
          `

**Comment by fxOne** [comment]
`e` is the [mouse event](https://developer.mozilla.org/en-US/docs/Web/API/Element/blur_event). You find the `getCurrentContent` function on the `editorState`.
