### ISSUE TITLE
isomorphic rendering

### ISSUE THREAD

**Issue by jamesjjk** [draft-js-plugins/draft-js-plugins#261]
Hi great set of plugins, just what we were looking! Draft-JS generates a checksum error when rendering isomorphically (using react 14.8). How do I avoid this?

**Comment by nikgraf** [comment]
Hey @jamesjjk, any chance you can upgrade to React 15? The docs are rendered isomorphic and it works fine afaik. In addition you get rid of a couple annoying console.log debug messages regarding contenteditable 😄

**Comment by jamesjjk** [comment]
@nikgraf Thanks for that nik. The problem I'm having looks like it may be with Draft-js editor the math.random function used generates a key. (see https://github.com/facebook/draft-js/issues/385)
Have you resolved this in your version?

**Comment by jamesjjk** [comment]
@nikgraf Updated to react 15 however, getting a lot of NPM errors with draft-js-plugins, the peer dependencies for react could be update to 15 (not RC), and the draft-js dependency to 0.7?

**Comment by nikgraf** [comment]
@jamesjjk can you post the errors or a screenshot?

good find regarding the draftJS issues 👍

**Comment by jamesjjk** [comment]
@nikgraf 
I'm getting a number of errors when specifically using the 'draft-js-plugin-editor' rather then draft-js directly. First of I'm using the editor in a form (react-formal) which is perfectly fine. However the plugin-editor throws the following errors. Note that I'm not using any of the plugins.

Both errors are related to editor accepting a new state which causes the main issue..

```
warning.js?0260:44 Warning: This synthetic event is reused for performance reasons. If you're seeing this, you're accessing the property `isTrusted` on a released/nullified synthetic event. This is set to null. If you must keep the original synthetic event around, use event.persist()
```

The second warning I get is:
```
Form.js?3ad3:65 Uncaught Error: The schema does not contain the path: dispatchConfig.
```

**Comment by jamesjjk** [comment]
My work around is to clear the state: _state.editorState = EditorState.createEmpty(); prior to setting a new one which loses the plugins. https://github.com/draft-js-plugins/draft-js-plugins/issues/262

**Comment by nikgraf** [comment]
Hmmm, this might only be a temporary workaround, but could you try to reset the content like described here: https://github.com/draft-js-plugins/draft-js-plugins/blob/master/FAQ.md#how-to-reset-the-content

@jquense any ideas about these errors? The first warning might be related to the synthetic React events. The second might come from here: https://github.com/jquense/react-formal/blob/master/src/Form.jsx

**Comment by jquense** [comment]
Not sure about draftjs but that you get that warning from a form Field component that has a `name` prop that doesn't correspond to a schema branch on the form. If it's not that, my guess would be that something is injecting a name property into a Field without realizing perhaps?

**Comment by nikgraf** [comment]
@jamesjjk did that help? I haven't worked with react-formal yet

**Comment by thomaslindstrom** [comment]
Still getting this on React 15 with newest `draft-js`. ![screen shot 2016-05-27 at 19 29 53](https://cloud.githubusercontent.com/assets/2833514/15615980/72a80506-2441-11e6-8e23-77d96d9f13bd.png)

**Comment by nikgraf** [comment]
Thanks @thomaslindstrom - now I get the issue. This is an issues that has to be solved in the core first. In there it needs a feature to allow setting an editor ID and probably other IDs for the blocks.

**Comment by thomaslindstrom** [comment]
Definitely. But wouldn't it be better to – instead of having it as a setting – (without me knowing how this actually works) do the same thing as React with their checksums?

**Comment by jamesjjk** [comment]
@nikgraf @thomaslindstrom This issue will not be easy to resolve and likely will not be resolved anytime soon. There are no straight forward patterns to apply here as far as I can see.

**Comment by nikgraf** [comment]
sorry to hear 😞

**Comment by agungsb** [comment]
I'm facing the same problem. Even the editor not displaying at all. Still no solution for this? 😞

**Comment by nikgraf** [comment]
Not that I know off. btw if I'm not mistaken warnings are ignore in production. Your users should never be exposed. Unfortunately still annoying for development.

**Comment by juliankrispel** [comment]
Closing for issue cleanup - If you need this issue and think it should remain open please let us know why, thank you
