### ISSUE TITLE
☺️  relaxed emoji is not show up in the editors emoji picker in Apple emoji set

### ISSUE THREAD

**Issue by punithbm** [draft-js-plugins/draft-js-plugins#2611]
- @draft-js-plugins/editor version: 2.1.3
- plugin name and version: Emoji Plugin

## Description

Is there any specific reason why this relaxed emoji is showing up as text rather than actual emoji.  If any of you have faced this issue earlier or have come across it, Please let me know how can we address this.

![Screenshot 2022-02-16 at 7 28 34 PM](https://user-images.githubusercontent.com/13044958/154280063-c24a5bb0-022f-4d29-baf9-48319f940433.png)

**Comment by fxOne** [comment]
The issue is that the font you are using does not support the Unicode character 0x263A.
