### ISSUE TITLE
Editor Plugin doesn't react to a new editorState

### ISSUE THREAD

**Issue by mjrussell** [draft-js-plugins/draft-js-plugins#262]
when changing the editorState such as re-setting with `EditorState.createEmpty()`, a user would expect the plugin editor to react to the change in state as DraftJS's Editor does. But the plugin editor only binds the decorators in `componentWillMount` so the editor loses the plugins

**Comment by mjrussell** [comment]
Current workaround from the component who renders the PluginEditor:

`this.onChange(EditorState.createEmpty(this.state.editorState.getDecorator())`

**Comment by nikgraf** [comment]
Ideally we could identify if people provided a new EditorState instance.

If yes then we could do either one of those:
- declare it as bad practice (which I think it is) & log a info with a link to a detailed explanation.
- check for an updated editorState in the componentWillReceiveProps and re-assign the decorators like here: https://github.com/draft-js-plugins/draft-js-plugins/blob/master/draft-js-plugins-editor/src/Editor/index.js#L59

Can you figure out if the editorState has some unique identifier?

**Comment by jamesjjk** [comment]
+1

**Comment by mjrussell** [comment]
> declare it as bad practice (which I think it is) & log a info with a link to a detailed explanation.

I think this would be the wrong thing to do, considering that the draft-js regular editor works this way, I think its going to confuse users to not be able to do this. It also seems to violate the API that appears to be a controlled component (i.e. onChange with the editorState as a value).

> check for an updated editorState in the componentWillReceiveProps

I think this is actually pretty easy. Should be able to just compare `this.props.editorState` with `nextProps.editorState` and add the decorators to the new editorState if they differ. Only warning I would add is if the decorator object is already defined

Also Related to #251 and #256

**Comment by mjrussell** [comment]
I can take this on and submit a PR unless someone beats me to it

**Comment by jamesjjk** [comment]
@mjrussell @nikgraf Has this been resolved, does the editor now react like draft-js natively does?

**Comment by nikgraf** [comment]
@jamesjjk currently discussion possible solutions here: https://github.com/draft-js-plugins/draft-js-plugins/issues/359

**Comment by whitef0x0** [comment]
@nikgraf any update on this?
