### ISSUE TITLE
Editor crashes in Safari when set to readOnly=true and then back to false

### ISSUE THREAD

**Issue by AryamnovEugeniy** [draft-js-plugins/draft-js-plugins#2620]
## Environment

- @draft-js-plugins/editor version: 4.11
- browser: Safari 15.0

## Description

Hello!

I have an editor from "@draft-js-plugins/editor" package, which I use with several other plugins (these are irrelevant since the issue can be reproduced without them). When I click "Send" button, I set the editor to "readOnly" mode while waiting for the response from the server. When I have the response, I switch "readOnly" from true to false. And then I try to enter a symbol **without** (that is important) focusing the editor. And get this error:

<img width="621" alt="image" src="https://user-images.githubusercontent.com/51905811/155076663-7ab320d8-7d83-4714-8131-fa631c4d862b.png">

If I focus the editor before typing any character, I do not get the error. Below is a screencast of this behaviour:

https://user-images.githubusercontent.com/51905811/155076944-2f235bbc-5148-48ce-9877-2fe44d93b90e.mov

## Reproducible Demo

https://codesandbox.io/s/draft-editor-example-forked-m7tnit?file=/src/App.js

Steps to reproduce:
1. Open the code-sandbox in Safari
2. Type any text
3. Click on "Send" button
4. Wait 3 seconds
5. Try to type any character. This will result in error

Please tell me, am I doing anything wrong here?

I also found a work-around: we can focus the editor manually through ref when readOnly changes:

```
useEffect(() => {
  !readOnly && editorRef.current.focus()
}, [readOnly])
```

**Comment by fxOne** [comment]
I habe just tested it on an IPad with the latest updates where is worked fine. Can you give mir information like the full error?

**Comment by AryamnovEugeniy** [comment]
It can be reproduced on MacOS Monterey. On IPad you will have to focus the editor to start typing. The problem is when it is not focused after readOnly was switched.
Full error:

[Error] NotFoundError: The object can not be found here.
	removeChild
	removeChild (react-dom.development.js:10301)
	unmountHostComponents (react-dom.development.js:21296)
	commitDeletion (react-dom.development.js:21347)
	commitMutationEffects (react-dom.development.js:23407)
	callCallback (react-dom.development.js:3945)
	dispatchEvent
	invokeGuardedCallbackDev (react-dom.development.js:3994)
	invokeGuardedCallback (react-dom.development.js:4056)
	commitRootImpl (react-dom.development.js:23121)
	commitRootImpl
	unstable_runWithPriority (scheduler.development.js:468)
	commitRoot (react-dom.development.js:22990)
	performSyncWorkOnRoot (react-dom.development.js:22329)
	performSyncWorkOnRoot
	(анонимная функция) (react-dom.development.js:11327)
	unstable_runWithPriority (scheduler.development.js:468)
	flushSyncCallbackQueueImpl (react-dom.development.js:11322)
	flushSyncCallbackQueue (react-dom.development.js:11309)
	discreteUpdates$1 (react-dom.development.js:22420)
	discreteUpdates (react-dom.development.js:3756)
	dispatchDiscreteEvent (react-dom.development.js:5889)
	dispatchDiscreteEvent
	
[Error] The above error occurred in the <br> component:

br
Component@
span
Component@
div
Component@
div
div
Component@
div
div
div
Component@
Component@
div
div
App

Consider adding an error boundary to your tree to customize error handling behavior.
Visit https://reactjs.org/link/error-boundaries to learn more about error boundaries. – "↵    in Unknown"
"
    in Unknown"
	(анонимная функция) (vendors~app~embed~sandbox-startup.6e3433fd3.chunk.js:1:597)
	r (vendors~react-devtools-backend.759c29504.chunk.js:1:267550)
	logCapturedError (react-dom.development.js:20085)
	(анонимная функция) (react-dom.development.js:20118)
	callCallback (react-dom.development.js:12318)
	commitUpdateQueue (react-dom.development.js:12339)
	commitLifeCycles (react-dom.development.js:20736)
	commitLayoutEffects (react-dom.development.js:23426)
	callCallback (react-dom.development.js:3945)
	dispatchEvent
	invokeGuardedCallbackDev (react-dom.development.js:3994)
	invokeGuardedCallback (react-dom.development.js:4056)
	commitRootImpl (react-dom.development.js:23151)
	commitRootImpl
	unstable_runWithPriority (scheduler.development.js:468)
	commitRoot (react-dom.development.js:22990)
	performSyncWorkOnRoot (react-dom.development.js:22329)
	performSyncWorkOnRoot
	(анонимная функция) (react-dom.development.js:11327)
	unstable_runWithPriority (scheduler.development.js:468)
	flushSyncCallbackQueueImpl (react-dom.development.js:11322)
	flushSyncCallbackQueue (react-dom.development.js:11309)
	discreteUpdates$1 (react-dom.development.js:22420)
	discreteUpdates (react-dom.development.js:3756)
	dispatchDiscreteEvent (react-dom.development.js:5889)
	dispatchDiscreteEvent

**Comment by fxOne** [comment]
Can you try if you can reproduce it with the draft-js `Editor` as I have no Mac to reproduce it?

**Comment by AryamnovEugeniy** [comment]
No, I was not able to reproduce this issue with the draft-js Editor. Here is my example: https://codesandbox.io/s/draft-editor-example-forked-fuxwwn?file=/src/App.js
