### ISSUE TITLE
[@draft-js-plugins/mention]Firstly, hovering the third suggestion of popover and using up or down arrows, can auto jump the third suggestion when  scrolling the popover bottom

### ISSUE THREAD

**Issue by tangmuchw** [draft-js-plugins/draft-js-plugins#2625]
## Environment

@draft-js-plugins/editor version: 4.1.1
plugin name and version: @draft-js-plugins/mention: 5.1.1

## Description

Firstly, hovering the third suggestion of popover and using up or down arrows, can auto jump the third suggestion when  scrolling the popover bottom

## Reproducible Demo

https://user-images.githubusercontent.com/28349450/155667190-511f972c-5cbe-40df-a0f5-44c8ecf1d867.mov

try [codesandbox](https://codesandbox.io/s/draft-js-plugin-mention-xloxg?file=/src/App.tsx)

**Comment by fxOne** [comment]
I see the issue. 

If you scroll with the arrow keys the mouse cursor hovers a new entry, which triggers a new focus. Do you have any idea on how to solve this issue?
