### ISSUE TITLE
Line clamp not working in safari 

### ISSUE THREAD

**Issue by akshata456** [draft-js-plugins/draft-js-plugins#2630]
## Environment
Safari browser

- @draft-js-plugins/editor version:
- plugin name and version:
- @draft-js-plugins/editor  4.1.2

## Description
I want  line clamp in the paragraph.
I used this below class for clamping  it's  working in Chrome , Firefox but failed in Safari browser.   
clampledWebkitBox($lines) {
  display: -webkit-box;
  -webkit-line-clamp: $lines;
  -webkit-box-orient: vertical;
  overflow: hidden;
}

let me know what should we do to handle this issue in safari. Thanks.

**Comment by fxOne** [comment]
`draft-js-plugin` is not using `line-clamp` so I don't see any issues here. As far as I can see `line-clam` is supported by Safari since version 5: https://caniuse.com/css-line-clamp
