### ISSUE TITLE
Getting the name from the mention field.

### ISSUE THREAD

**Issue by stefan1968** [draft-js-plugins/draft-js-plugins#264]
I know we now have the ability to add a character via mentionPrefix, however this prefix doesn't actually get sent, it just seems to be a decorator - How can i interpret if the name was produced by the mention plugin?

**Comment by nikgraf** [comment]
@stefan1968 Every block contains a characterlist which can reference an Entity which we create here: https://github.com/draft-js-plugins/draft-js-plugins/blob/master/draft-js-mention-plugin/src/modifiers/addMention.js#L5. This way you can identify mentions. 

Does this help?

**Comment by maktouch** [comment]
Any way to add an option so we can just have the mentionPrefix when we do `this.state.editorState.getCurrentContent().getPlainText()`?

**Comment by maktouch** [comment]
Just to add a bit of context -- 

I'm using the draftjs + mention plugin just for the decorators and user searching. I just need the plain text and my backend server redo the parsing. 

Right now, I'm using this very hacky solution that I literally coded 10 minutes ago and is very untested. 

```javascript
getContent() {
    const raw = convertToRaw(this.state.editorState.getCurrentContent());
    const { blocks, entityMap } = raw;

    let content = ''; 

    Object.keys(blocks).map(i => {
        const { entityRanges, text } = blocks[i];

        const textLength = text.length;

        let startRange = 0;
        entityRanges.map(range => {
            content += text.substr(startRange, range.offset - startRange );
            content += '@';
            content += text.substr(range.offset, range.length);
            startRange = range.offset + range.length;
        });

        content += text.substr(startRange, textLength);
        content += "\r\n";
    });

    return content;
}

```

Would be awesome if `getPlainText` just returns the mentions with the prefix :-)

**Comment by stefan1968** [comment]
I ended up with something very similar, be nice to have a
getMentionsFunction()

**Comment by nikgraf** [comment]
Nice @maktouch 

What I can imagine is that we have a different mode for the whole plugin. In this case it would not add entity data, but just autocomplete. This way `getCurrentContent ` would just use the text and you could parse it without trouble on the server. To have a fancy highlighting another decorator would be useful.

- [ ] add option: `useEntity` which is true by default (if false a `mentionPrefix ` must be defined)
- [ ] create a decorator which leverages the `mentionPrefix ` to identify mentions when `useEntity` is set to false
- [ ] avoid creating and setting Entities when autocompleting a mention when `useEntity` is set to false

**Comment by juliankrispel** [comment]
Closing for issue cleanup - If you need this issue and think it should remain open please let us know why, thank you
