### ISSUE TITLE
[@draft-js-plugins/focus] Example code not working as in plugin showcase page

### ISSUE THREAD

**Issue by elton-okawa** [draft-js-plugins/draft-js-plugins#2642]
## Environment

- react version: `17.0.2`
- draft-js: `0.11.7`
- @draft-js-plugins/editor version: `4.1.2`
- @draft-js-plugins/focus version: `4.1.2`

### Expected Behavior
In [focus plugin showcase page](https://www.draft-js-plugins.com/plugin/focus), when we mouse over the color block the cursor icon change to pointer and the color block has a highlight.

![expected](https://user-images.githubusercontent.com/24387035/156917945-acb85d09-707e-4e79-870e-5d78d398d158.gif)

### Actual Behavior
I copied the example code to a fresh react project and it seems that it's not working, when I mouse over it the cursor icon does not change and the color block does not have a highlight.

![actual](https://user-images.githubusercontent.com/24387035/156918053-9e816837-a5b5-4dd4-81c1-0fa80e88b72d.gif)

## Reproducible Demo

Here's a [demo in codesandbox](https://codesandbox.io/s/draft-js-plugin-focus-example-code-not-working-78ec4p)

**Comment by fxOne** [comment]
You need to include the css file as noted on the page
`import '@draft-js-plugins/focus/lib/plugin.css';`
