### ISSUE TITLE
Hitting enter on unknown mention search throws error

### ISSUE THREAD

**Issue by mjrussell** [draft-js-plugins/draft-js-plugins#265]
Steps to reproduce (on https://www.draft-js-plugins.com/plugin/mention):
* Start typing a mention with @ and then some random string that doesn't match any suggestion (not including spaces or invalid chars)
* Hit enter

![image](https://cloud.githubusercontent.com/assets/1641895/15330095/341df9aa-1c10-11e6-9bba-4d500b17cc30.png)

**Comment by mjrussell** [comment]
The fix seems to be to add the following to the suggestions component:
```js
    componentWillReceiveProps(nextProps) {
      if (nextProps.suggestions.size === 0 && this.state.isActive) {
        this.closeDropdown();
      }
    }
```

**Comment by nikgraf** [comment]
Good find, can you open PR together with a fix?

**Comment by mjrussell** [comment]
Yeah will do

**Comment by nikgraf** [comment]
@mjrussell was this fixed with the last PR you submitted?

**Comment by mjrussell** [comment]
@nikgraf no it wasn't, sorry. I can work this in the next day or so and get a PR in with maybe even a test 😄. The onOpen/onClose will probably make this actually easier to verify in the test

**Comment by mjrussell** [comment]
@nikgraf opened #291
