### ISSUE TITLE
Mention plugin crashes in IE11 due to Immutable List Render

### ISSUE THREAD

**Issue by mjrussell** [draft-js-plugins/draft-js-plugins#266]
Because `this.props.suggestions` is an ImmutableJS list [here](https://github.com/draft-js-plugins/draft-js-plugins/blob/master/draft-js-mention-plugin/src/MentionSuggestions/index.js#L259), IE complains that you are rendering an object not an array for react child elements. 

Need a `.toJS()` on the end for IE compatibility.

**Comment by nikgraf** [comment]
oh, can you create small PR? I'm happy to merge & cut a minor release.
