### ISSUE TITLE
Completely replacing theme is not a solution! Merging plugin configurations is necessary. Guys, come on.

### ISSUE THREAD

**Issue by waveiron** [draft-js-plugins/draft-js-plugins#2667]
All I want is tweaking one css class of a plugin, now I have to find the right styles, copy them, create new .module.css files, pastes them, import them and hope it won't break.
I notice there are already issues for theming problems: #786, but that doesn't help at all, issues won't go away just by closing them.

Why I labeled it a bug? It's a "design level" bug.

**Comment by fxOne** [comment]
There are good solutions in issue #786. I don't see any reason to change the design system for this library.
