### ISSUE TITLE
Delay on active styles

### ISSUE THREAD

**Issue by alexpuertasr** [draft-js-plugins/draft-js-plugins#2670]
## Environment

- @draft-js-plugins/editor version: 4.1.2
- @draft-js-plugins/static-toolbar version: 4.1.2

## Description

As you can see in this gif there is a delay of one tick to detect the correct active styles on the caret:

![ezgif-1-a98841fae9](https://user-images.githubusercontent.com/10731590/159973850-ebee7552-7695-4528-bc60-c58c3302b552.gif)

## Reproducible Demo

You can try by yourself this error on this codesandbox:
https://codesandbox.io/s/draft-js-plugins-delay-rwvmn8?file=/src/App.tsx

**Comment by alexpuertasr** [comment]
I have notice that this issue disappears if the `Toolbar` is rendered below the `Editor`

**Comment by fxOne** [comment]
Yes thats the solution. I remember that I had the same issue a year ago. It has something to do with the art of how react renders the components and the first component gets the old `editorState`. I have no idea of how a solution can look like. Maybe you want to look into it?

**Comment by ab-pm** [comment]
Duplicated by #3320
