### ISSUE TITLE
Not possible to have two editors

### ISSUE THREAD

**Issue by alexpuertasr** [draft-js-plugins/draft-js-plugins#2675]
## Environment

@draft-js-plugins/editor version: 4.1.2
@draft-js-plugins/static-toolbar version: 4.1.2

## Description

When you have two editors rendered, they are sharing the same editorState

![ezgif-1-70ee05be63](https://user-images.githubusercontent.com/10731590/160105359-72b09060-0fb9-454c-a150-0ed9482fdeb8.gif)

## Reproducible Demo

https://codesandbox.io/s/draft-js-plugins-issues-hs3m5f?file=/src/RichTextEditor.tsx

**Comment by fxOne** [comment]
You need to create a separate toolbar instance for each editor like:

```
  const { plugins, Toolbar } = useMemo(() => {
    const staticToolbarPlugin = createToolbarPlugin();
    return {
      plugins: [staticToolbarPlugin],
      Toolbar: staticToolbarPlugin.Toolbar
    };
  }, []);
```
