### ISSUE TITLE
Inline styles

### ISSUE THREAD

**Issue by antoinerey** [draft-js-plugins/draft-js-plugins#269]
I started to use your plugins today, and I'd like to apply some custom inline styles but from what I saw, it seems not possible. Is there any reason why the style overrides can only be made with CSS and not inline styles ? 

I went through some of your code, and it seems that you can use `decorate-component-with-props` to pass down any props from the `config` object.

Some code may be easier to understand :

``` js
const linkPlugin = (config = {}) => {
  // Any other key are considered as props
  let { theme, target, ...props } = config;

  theme = theme ? theme : defaultTheme;
  target = target ? target : '_self';

  return {
    decorators: [
      {
        strategy: linkStrategy,
        // We pass down the props to the Link component.
        component: decorateComponentWithProps(Link, { theme, target, ...props }),
      },
    ],
  };
};
```

This way, one can override styles with inline ones, add some ARIA attributes or whatever.

What are you thoughts about it ? I could make a PR if you want to.

PS: I didn't test my idea with real code, so I could have miss something :)

**Comment by nikgraf** [comment]
@antoinerey it would definitely make sense. I probably makes sense to have the same pattern across all default plugins. A lot of the plugins have multiple internal component. Something like this might work although I'm not sure on the naming:

```
let { theme, props = {} } = config;
const { linkProps = {} } = props;

return {
  decorators: [
    {
      strategy: linkStrategy,
      // We pass down the props to the Link component.
      component: decorateComponentWithProps(Link, { ...linkProps, theme }),
    },
  ],
};
```

Are you interested to experiment with it and open a PR?

**Comment by antoinerey** [comment]
Yep okay. I'll start on this later today.

**Comment by yanivtal** [comment]
Check this project out for a nice standard for solving this common problem https://github.com/markdalgleish/react-themeable
