### ISSUE TITLE
TypeError: (this.props.children || this.renderDefaultButtons) is not a function

### ISSUE THREAD

**Issue by ziedHamdi** [draft-js-plugins/draft-js-plugins#2726]
## Environment

next.js, but doesn't work neither in ssr mode nor in client side rendering

    "@draft-js-plugins/buttons": "^4.3.0",
    "@draft-js-plugins/editor": "^4.1.2",
    "@draft-js-plugins/linkify": "^4.2.0",
    "@draft-js-plugins/static-toolbar": "^4.1.2",
    "draft-js": "^0.11.7",

    "react": "^17.0.2",
    "react-dom": "^17.0.2",

    "next": "12.1.5",

## Description

I'm just trying to display the static toolbar. Here's my code:
```
import {EditorState} from 'draft-js';
import Editor from '@draft-js-plugins/editor';
import createLinkifyPlugin from '@draft-js-plugins/linkify';
import React, {useState} from 'react';

import createStaticToolbarPlugin from '@draft-js-plugins/static-toolbar';
import {
    ItalicButton,
    BoldButton,
    UnderlineButton,
} from '@draft-js-plugins/buttons';

export default function StyledEditor() {
    const [editorState, setEditorState] = useState(() =>
        EditorState.createEmpty(),
    );
    const linkifyPlugin = createLinkifyPlugin();
    const staticToolbarPlugin = createStaticToolbarPlugin();

    const { Toolbar } = staticToolbarPlugin;
    const plugins = [staticToolbarPlugin, linkifyPlugin];

    function onChange(e) {
    }

    return (
        <div>
            <Editor editorState={editorState}
                    onChange={onChange} plugins={plugins}/>
            <Toolbar>
                <ItalicButton/>
                <BoldButton/>
                <UnderlineButton/>
            </Toolbar>
        </div>)

}
```

What I receive is : 
TypeError: (this.props.children || this.renderDefaultButtons) is not a function
```
![Capture d’écran de 2022-04-15 13-27-13](https://user-images.githubusercontent.com/7271508/163565534-a5943ff4-b8ab-49ca-a18b-5b78049ab319.png)
```

**Comment by fxOne** [comment]
You need to use it as it mentioned in the [documentation](https://www.draft-js-plugins.com/plugin/static-toolbar):
```jsx
<Toolbar>
  {
    (externalProps) => (
      <div>
        <BoldButton {...externalProps} />
        <ItalicButton {...externalProps} />
        <UnderlineButton {...externalProps} />                  
      </div>
    )
  }
</Toolbar>
```

**Comment by ziedHamdi** [comment]
Ok,

Actually, that's what I found in some documentation
![Capture d’écran de 2022-04-15 16-06-40](https://user-images.githubusercontent.com/7271508/163580687-2fa6b1f5-64f3-4aa2-b426-25dbbad60cc8.png)

**Comment by ziedHamdi** [comment]
I changed the following snippet and it started working for me thanks.

```
    function onChange(editorState) {
      setEditorState(editorState);
    }
```

But still adding a link in the editor doesn't work, and I don't know how to style the buttons using Mui sx syntax. Should I open a new issue?

**Comment by fxOne** [comment]
You can change the css classes and style the buttons with them as you want. You can can see at in the last example here: https://www.draft-js-plugins.com/plugin/static-toolbar

You can also use you own buttons and implement the logic yourself.

I don't know what you mean by the Mui syntax.

**Comment by ziedHamdi** [comment]
Mui is material-ui new version 5 that introduces a new way of writing styles (through the `[sx property](https://mui.com/system/the-sx-prop/)`). As I need to be SSR ready, I stick to their way of solving styling. This can become challenging sometimes

**Comment by ziedHamdi** [comment]
Thank you for your help, I decided to use Lexical instead : https://codesandbox.io/s/lexical-rich-text-example-5tncvy?file=/src/Editor.js
