### ISSUE TITLE
Support for html <mark> and <kbd> tag

### ISSUE THREAD

**Issue by ashiqdey** [draft-js-plugins/draft-js-plugins#2734]
I want to insert html mark and kdb tag for my blogpost so unfortunately which is not available in code draft.js
I am writing tech blogs so i want to use those tags for writing posts with better markup

**Comment by fxOne** [comment]
You can solve this with a [custom block rederer](https://draftjs.org/docs/advanced-topics-custom-block-render-map). I don't see any need for a plugin here.
