### ISSUE TITLE
Placeholder is not removed when usingunordered/ordered list

### ISSUE THREAD

**Issue by TestCK** [draft-js-plugins/draft-js-plugins#2756]
Screenshot
![issue screenshot](https://user-images.githubusercontent.com/74267332/166574390-e6fe327f-4441-497a-8611-8546fcb553b3.png)

## Environment

- @draft-js-plugins/editor version:4.1.3
- plugin name and version:
  OrderedListButton,
  UnorderedListButton
  
## Description

When we use editor with a placeholder and click the orderedlist/unorderedlist button , we get either or `.` or `1.` but the placeholder is not removed.
Ideally the placeholder should be hidden in this case

## Reproducible Demo
https://codesandbox.io/s/draft-js-plugins-delay-forked-onkvm2?file=/src/App.tsx

**Comment by fxOne** [comment]
This part comes from `draft-js` and is the expected behavior: https://github.com/facebook/draft-js/issues/1205#issuecomment-455823300
`draft-js-plugins` isn't doing anything with the placeholder.
