### ISSUE TITLE
Mentions doesn't work after clearing an editor

### ISSUE THREAD

**Issue by maktouch** [draft-js-plugins/draft-js-plugins#278]
How to reproduce:
- Type something
- Clear it using 

``
this.setState({
    editorState: EditorState.createEmpty(),
}
``

- Try a mention
- Mention doesn't work

Not sure if it's a bug or if I'm clearing the editor wrongly.

**Comment by mjrussell** [comment]
Duplicate of #256 and #251. See https://github.com/draft-js-plugins/draft-js-plugins/blob/master/FAQ.md#how-to-reset-the-content for how to reset the content currently. We are looking into improving this

**Comment by maktouch** [comment]
Thanks. Maybe we should make the FAQ link clearer too! Some useful stuff in there

Cheers

**Comment by nikgraf** [comment]
@maktouch what's a good place to highlight the FAQ?

**Comment by viridia** [comment]
It appears that this was deleted from the FAQ but the underlying problem still exists - clearing the editor state destroys the ability to show the mentions popup.

**Comment by giabao1008** [comment]
i have same problem, i created chat rooms, when user type and no send, then they click to other room. I need clear old text (what user typed), but after clear, cant use mentions

**Comment by fxOne** [comment]
Can you please create https://codesandbox.io example so that I can test it?
