### ISSUE TITLE
Side tool bar work with click instead of hover

### ISSUE THREAD

**Issue by ilanskogan** [draft-js-plugins/draft-js-plugins#2785]
Hi, we are using the side tool bar in production and we get a lot of feedback that it will be much more convenient if the side tool bar could be opened by click and not with hover like in the demo.
I couldn't find a way to make it work.
We will be happy to provide a PR if needed, just need a little guidance

**Comment by fxOne** [comment]
You can finde the hover detection here: https://github.com/draft-js-plugins/draft-js-plugins/blob/0e9c8784d23c81e68397cd2ca8591bdaca7000a2/packages/side-toolbar/src/components/Toolbar/Toolbar.tsx#L121
I guess a simple flag `SideToolbarPluginConfig` would be best to change the behavior. Maybe you find a good name :)

I would love to merge a PR!

**Comment by ilanskogan** [comment]
@fxOne looks like the contributing docs are not up to date.
trying to run the demo from packages/docs. looks like you should run "next build" which is not documented but for some reason it fails
<img width="747" alt="Screen Shot 2022-05-25 at 13 19 39" src="https://user-images.githubusercontent.com/71634959/170240329-8d448b88-0732-4f22-b713-5debe77c9428.png">

**Comment by ilanskogan** [comment]
@fxOne I started playing with it, tell me please, do i need to run yarn build on every change i make in order too see the changes? the build is taking a few minutes its really hard to get going like this.

**Comment by fxOne** [comment]
The easiest way to try stuff out is with `yarn storybook`. If you need to modify a story you can find them here: https://github.com/draft-js-plugins/draft-js-plugins/tree/master/stories
