### ISSUE TITLE
Emoji Plugin

### ISSUE THREAD

**Issue by nikgraf** [draft-js-plugins/draft-js-plugins#28]
I quite like Slack's implementation where you can start with a `:` and type the name like `:heart:` which also autocompletes. Pasting in real emojis also works.

**Comment by mxstbr** [comment]
Will try this one!

**Comment by nikgraf** [comment]
Some resources:

- https://github.com/needim/wdt-emoji-bundle/ (most interesting one)
- https://github.com/banyan/react-emoji
- https://github.com/chadoh/react-emoji-picker

**Comment by jpuri** [comment]
There is a difference in emoji on editor to emoji's in slack/git. For instance in slack editor emoji will appear as `:smile:` and when we post it and read it will be :smile: 

But in this editor test will be in one state.

A possible solution is that as user starts typing `:smi` we show him:

![screen shot 2016-03-08 at 11 28 34 am](https://cloud.githubusercontent.com/assets/2182307/13593413/fafa47bc-e520-11e5-835f-7650e6fb977f.png)

But as he completes it `:smile:` with closing `:` we show him :smile:

**Comment by jpuri** [comment]
We can create mapping from emoji tag (eg `:smile:`) to position here: https://slack.global.ssl.fastly.net/d4bf/img/emoji_2015_2/sheet_apple_64_indexed_256colors.png

We can even think of ways to make it more extensible.

**Comment by nikgraf** [comment]
sweeeet, your suggestion sounds great - btw you can store the emoji data in an entity and then build a component that renders the correct emoji :smile:
