### ISSUE TITLE
The content of the line changes when the line is quickly switched.

### ISSUE THREAD

**Issue by lordenas** [draft-js-plugins/draft-js-plugins#2807]
## Environment
- @draft-js-plugins/editor - 4.1.3
- @draft-js-plugins/emoji - 4.6.1

## Description

1) The content of the line changes when the line is quickly switched.

2) Cursor jumps

This problem is observed in my project. It oftener occurs when decorators are used.

## Reproducible Demo
Try to quickly switch to another line after entering text and continue typing. The content of the line will change.
![ezgif-5-daa04e2fc2](https://user-images.githubusercontent.com/15974195/171837749-57136f8a-b919-4472-a90b-86e8e0b1ed37.gif)

**Comment by fxOne** [comment]
This may be related to to https://github.com/draft-js-plugins/draft-js-plugins/issues/2469

**Comment by lordenas** [comment]
> This may be related to to #2469

Most likely this is another problem. But I'm not sure.
