### ISSUE TITLE
Add support for blockRenderMap

### ISSUE THREAD

**Issue by makenosound** [draft-js-plugins/draft-js-plugins#281]
Just wanted to bring this up for discussion as I started working on new plugin. draft-js has recently added support for passing a custom `Map` through a  `blockRenderMap` prop but its support in the plugin system is as-yet unresolved.

The main to think about here with regard to the plugin system is: how do you reconcile things if multiple plugins provide a `blockRenderMap`?

For example, the plugin I’m working on at the moment overrides the entire block map to ensure that only _one_ type of block is allowed. If the plugin editor merges `blockRenderMap`s then that use case would fail. Could you provide a way for individual plugins to specify some sort of `priority` and/or `merge/replace` property?

Note that the `draft-js-plugins-editor` currently supports a single `blockRenderMap` being passed to it, in that it simply passes that onto the standard draft-js `<Editor>`. Is that actually enough? In which case, good work team 😄

**Comment by makenosound** [comment]
Oh, I should also note that I have almost no idea how `blockRenderMap` works in practice, so please correct me if there’s some fundamental misunderstanding I have.

**Comment by crossman** [comment]
I don't think this is an issue since the plugins editor doesn't use the blockRenderMap at all. It's relying on composite decorators and entities. For what it's worth I'm happily using the plugins editor with a custom blockRenderMap without issue.

**Comment by nikgraf** [comment]
Wow, just looked up how it works. Pretty cool feature `blockRenderMap`. As @crossman pointed out for the existing plugins it is irrelevant, but might indeed interesting for some of the wysiwyg features.

Without having use the feature I feel like merging them like we do for `customStyleMap` https://github.com/draft-js-plugins/draft-js-plugins/blob/master/draft-js-plugins-editor/src/Editor/index.js#L201-L212 would be great. If there are overwrite then the last one wins.  

What do you think?
/cc @bkniffler is this relevant for wysiwyg features?

**Comment by makenosound** [comment]
For reference, [`draft-js-single-line-plugin`](https://github.com/icelab/draft-js-single-line-plugin) is the plugin I mention above and https://github.com/icelab/draft-js-single-line-plugin/blob/master/src/index.js#L42-L46 is the `blockRenderMap` I’m including in it. It’s probably not strictly necessary to have in there given the other manual manipulation I’m doing, but I figure it can’t hurt to restrict the set of blocks as best we can. Anyway, that’s the kind of odd use case can I can imagine!

**Comment by guitardave24** [comment]
FWIW, I have a working prototype on my own editor with code like this:

```js
_resolveBlockRenderMap() {
  return this._plugins
      .filter((plug) => plug.blockRenderMap !== undefined)
      .map((plug) => plug.blockRenderMap)
      .reduce((map, type) => {
        return map.merge(type);
      }, DefaultDraftBlockRenderMap);
}
```

In this implementation, the plugins can return either a Map() or a JS object.

**Comment by richtera** [comment]
I see the blockRenderMap thing there, but it's has a problem because of the map.merge. This causes the immutable to build maps for each blockRenderMap but draft.js expects a plain javascript object. Maybe an additional map using type.toJS() or something.

**Comment by richtera** [comment]
This works for example.
```javascript
_resolveBlockRenderMap() {
  return this._plugins
      .filter((plug) => plug.blockRenderMap !== undefined)
      .map((plug) => plug.blockRenderMap)
      .reduce((map, type) => {
        Object.keys(plug.blockRenderMap).forEach(function(key) {
          maps = maps.set(key, plug.blockRenderMap[key]);
        });
        return maps;
      }, DefaultDraftBlockRenderMap);
}

```
