### ISSUE TITLE
Use Lerna to organize project

### ISSUE THREAD

**Issue by joehua87** [draft-js-plugins/draft-js-plugins#282]
Just my opinion, I think [Lerna](https://lernajs.io) is a good fit for this project 😃

**Comment by nikgraf** [comment]
@joehua87 totally agree! Interested to port it to Lerna in a test branch?

**Comment by joehua87** [comment]
@nikgraf I've created a new branch at https://github.com/joehua87/draft-js-plugins/tree/feature/lerna

It's currently
* [x] Organize into lerna structure
* [x] ```lerna bootstrap``` (just install deps in the root folder & call lerna bootstrap, it will install node_modules into child packages)
* [x] ```lerna run build```, so I think it's not have any problem to run 'lerna publish'

Things need to be done
* [ ] Work with flow. I have disable flow-staged to organize into lerna style. But it's not a big problem to make it work again
* [ ] Clean up some duplicated things

**Comment by nikgraf** [comment]
niiiiice @joehua87 - btw I'm not super opinionated to keep flow-staged, but if you can fix it even better 👍 

let me know if I can be of help regarding the refactoring or in case you have any questions

**Comment by joehua87** [comment]
@nikgraf I've tried to publish to npm by add "-ex" with this branch: https://github.com/joehua87/draft-js-plugins/tree/feature/lerna-publish & things work smoothly
Example: https://www.npmjs.com/package/draft-js-plugins-editor-ex

**Comment by nikgraf** [comment]
@joehua87 sweet, this really good. I'm bit busy the next couple days, but will take a closer look after that and merge! Thanks a lot!

**Comment by nikgraf** [comment]
justed noticed there is a merge conflict (we made some minor changes in the last couple days …) https://github.com/draft-js-plugins/draft-js-plugins/pull/301

**Comment by joehua87** [comment]
@nikgraf Just fixed it

**Comment by adrianmc** [comment]
This is pretty cool.

If I am understanding this correctly, Lerna allows you to keep separate npm packages for different major "modules" while still keeping everything in the same git repo?

**Comment by joehua87** [comment]
@adrianmc Ya, you're right 😃

**Comment by juliankrispel** [comment]
hm, it's kind of a shame that this was never merged :/, sorry about that @joehua87 :/

**Comment by sibelius** [comment]
I think yarn workspaces cover most of lerna benefits
