### ISSUE TITLE
inline-toolbar incorrect positing in modal

### ISSUE THREAD

**Issue by vadim7j7** [draft-js-plugins/draft-js-plugins#2826]
## Environment

- @draft-js-plugins/editor 4.1.3
- @draft-js-plugins/inline-toolbar 4.1.6 
 
## Description

I add the editor to a modal(from MUI) and if I don't do scrolling in the modal the position is correct, when I do scrolling down and select a text the menu appears with offset up. Looks like the offset is getting from scrolling in the modal.

<img width="457" alt="scrolling 0" src="https://user-images.githubusercontent.com/5203561/173536818-cfb20e48-86fb-4c09-a13a-912bc3e57a28.png">

<img width="417" alt="scrolloing down" src="https://user-images.githubusercontent.com/5203561/173536800-2070545f-ff0e-4913-8a5d-40bc30298328.png">

**Comment by fxOne** [comment]
@trevor-davis-dover can you please have a look at this?

**Comment by trevor-davis-dover** [comment]
@fxOne @vadim7j7 sorry for the delay. For now, I'd recommend reverting to @draft-js-plugins/inline-toolbar v 4.1.3, which should not have this issue.

@fxOne , I'm curious to hear your thoughts about how to resolve this. The changes that I made solve the issue of scroll offsets but go too far by not accounting for situations where a non-document element might be our relative root.

One idea I have is to extend the InlineToolbarPluginConfig to take a `rootElementId`, which would be the ID if the modal of this case, and add a clause in the scroll offset logic so we stop considering scroll offsets if/when we hit this node.

**Comment by fxOne** [comment]
@trevor-davis-dover I'm thinking about to if it might be a better solution to put the editor and inline-toolbar into a `position: relative` container and then calculate the position relative to this container. In this case we can ignore the scrolling. A better solution for `rootElementId` should be a `React.ref`.

**Comment by trevor-davis-dover** [comment]
> @trevor-davis-dover I'm thinking about to if it might be a better solution to put the editor and inline-toolbar into a `position: relative` container and then calculate the position relative to this container. In this case we can ignore the scrolling. A better solution for `rootElementId` should be a `React.ref`.

Good idea. That's something I can get to, although it won't be until week after next at the earliest because I'll be away from computer access.

**Comment by jp-albrecht** [comment]
Is this bug planning to be fixed? I as well am having positioning issues when using MUI. In my case when I add the editor to a `<FormControl/>`. It seems that the default `position: relative;` on the root element of `<FormControl/>` causes my issue. If I change it to `position: static;` it fixes the problem (but causes other issues with MUI).

https://mui.com/material-ui/api/form-control/#css

**Comment by jp-albrecht** [comment]
It actually seems if there is any DOM element up the tree that has `position: relative;` the inline-toolbar breaks... I've tried downgrading to `v4.1.3`, but still getting experiencing this bug.

**Comment by Hadermite** [comment]
This is still an issue, and should probably be reopened.

**Comment by trevor-davis-dover** [comment]
> This is still an issue, and should probably be reopened.

Hi! Feel free to reopen it. But I want to note that this library is entirely deprecated and only ever updated by random people these days. If you'd like to investigate the issue and put out a PR, I'm sure that I can help review it :)
