### ISSUE TITLE
Removing mention on mobile browser breaks an application.

### ISSUE THREAD

**Issue by mr-securitas** [draft-js-plugins/draft-js-plugins#2827]
## Environment
Device: POCO F3
OS: Android 11 RKQ1.200826.002
Chrome: 102.0.5005.78
@draft-js-plugins/mention: 5.2.1
@draft-js-plugins/editors: 4.1.3

## Description
Removing mention inside draft-js editor throws following error:
![image](https://user-images.githubusercontent.com/101644562/173584588-7715d7ec-dbbf-473a-91ce-04051adfab2c.png)

## Reproducible Demo
1. Open Google Chrome browser on mobile.
2. Go to https://www.draft-js-plugins.com/plugin/mention
3. Enter "@" to trigger mention suggestion.
4. Delete "@" character. Sometimes has to click delete button twice.
5. Error page with "Application error: a client-side exception has occurred (see the browser console for more information)" shows up.
Video:
https://user-images.githubusercontent.com/101644562/173586515-4275af19-ab39-4c6e-a4c4-9587c7cd0ce1.mp4

**Comment by fxOne** [comment]
Sadly `draft-js` does not support mobile https://draftjs.org/docs/advanced-topics-issues-and-pitfalls#mobile-not-yet-supported
