### ISSUE TITLE
error with fixed parent

### ISSUE THREAD

**Issue by berdof** [draft-js-plugins/draft-js-plugins#283]
First of all I am very excited with this plugin.
But I have found one issue. When you place editor into block with position fixed you ran into emoji modal strange positioning.
You can simply test it on demo site 
![image](https://cloud.githubusercontent.com/assets/1468790/15535469/31848454-2276-11e6-80ef-bd0b526e0c58.png)

**Comment by mjrussell** [comment]
@berdof you can override the position suggestions function that is passed into the mentions plugin.

This FAQ explains how to override that function: https://github.com/draft-js-plugins/draft-js-plugins/blob/master/FAQ.md#why-is-there-no-popover-for-mentionsemoji-plugin

Here is an example position suggestions function that worked for me:
https://github.com/draft-js-plugins/draft-js-plugins/issues/206#issuecomment-219192040

**Comment by nikgraf** [comment]
@berdof glad you like it 😄 
thx @mjrussell 👍

**Comment by brigand** [comment]
I just ran into this, with a position:relative parent. I'm not sure how to solve it without the dom node and walking up the parent tree searching for a non-position:static element. Is the dom node provided to positionSuggestions?

It'd be great if draft-js-plugins handled this case for us.

**Comment by nikgraf** [comment]
fixed with https://github.com/draft-js-plugins/draft-js-plugins/pull/309 & going to be in the next release
