### ISSUE TITLE
Unexpected 'Editor cannot be used as a JSX component'

### ISSUE THREAD

**Issue by kdshah6593** [draft-js-plugins/draft-js-plugins#2833]
## Environment
```
    "@draft-js-plugins/editor": "^4.1.3",
    "@draft-js-plugins/static-toolbar": "^4.1.3",
    "draft-js": "^0.11.7",
    "react": "^17.0.2",
    "react-dom": "^17.0.2",
    "@types/draft-js": "^0.11.4",
    "@types/react": "^17.0.33",
    "@types/react-dom": "^17.0.9",
```
## Description

I am trying to just set up a basic editor with static toolbar. However, whenever I try to import the Editor from the package I receive the following error:
```
JSX element class does not support attributes because it does not have a 'props' property.

'Editor' cannot be used as a JSX component.
  Its instance type 'PluginEditor' is not a valid JSX element.
    Type 'PluginEditor' is missing the following properties from type 'ElementClass': context, setState, forceUpdate, props, refs
```
Basically, it seems to not be recognizing the Editor at all. I haven't seen any other related issues similar to this or found a great solution. The other plugins seem to work fine.

I have tried to following below by casting/type coercion, which seems to work for the most part. However then when I try to use plugins like anchor I am getting `Invalid Hook Call` errors.
```
import { default as _Editor } from '@draft-js-plugins/editor';
import { PluginEditorProps } from '@draft-js-plugins/editor';

const Editor = (_Editor as unknown) as React.FC<PluginEditorProps>;

<Editor editorState ... />
```
![Screenshot from 2022-06-17 18-56-40](https://user-images.githubusercontent.com/64661789/174410997-ad493e30-d844-40df-a112-d443b00eabb2.png)

**Comment by fxOne** [comment]
I can't see any problems with your implementation. However, I use this plugin in my own projects without this problem. Can you create an example on https://codesandbox.io?

**Comment by kdshah6593** [comment]
I tried to create an example but I wasn't able to replicate the error. I've been researching the issue and I'm wondering if the issue could be related to React 18? I found this [StackOverflow question](https://stackoverflow.com/questions/71791347/npm-package-cannot-be-used-as-a-jsx-component-type-errors/71828113#71828113) which seems to be similar. 

I haven't had time yet to test that solution, but just wanted to get your thoughts on that. When I get a chance to test that out and if it works, I'll come back and post the solution here and close the issue.

**Comment by minardimedia** [comment]
Any update on this having the same issue.

**Comment by kdshah6593** [comment]
Update: I tried to use the `resolutions` solution, but it did not seem to work for me; Of note, the `Editor` from `draft-js` directly does not produce the same error. 

Temporary Solution is brute force type casting
```
import { default as _Editor } from '@draft-js-plugins/editor';
import { PluginEditorProps } from '@draft-js-plugins/editor';

const Editor = (_Editor as unknown) as React.FC<React.PropsWithChildren<PluginEditorProps>>;
```

However, I am running into issues with the `Anchor` Plugin, and not sure yet if that is a separate issue or related to this one.

**Comment by kdshah6593** [comment]
The repo I was working in uses workspaces and we had packages that were `nohoist` in `package.json`. Added `**/@draft-js-plugins/**` to `nohoist`, deleted my node_modules and ran `yarn install` again. That got it working

**Comment by jonahcarneskog** [comment]
`const Editor = dynamic<EditorProps>(
  () =>
    import("react-draft-wysiwyg").then(
      (mod) =>
        mod.Editor as unknown as React.FC<
          PropsWithChildren<{
            editorState: any;
            wrapperClassName: string;
            editorClassName: string;
            editorStateChange: any;
          }>
        >
    ),
  { ssr: false }
);`

**Comment by jonahcarneskog** [comment]
`const Editor = dynamic<EditorProps>(
  () =>
    import("react-draft-wysiwyg").then(
      (mod) =>
        mod.Editor as unknown as React.FC<
          PropsWithChildren<{
            editorState: any;
            wrapperClassName: string;
            editorClassName: string;
            editorStateChange: any;
          }>
        >
    ),
  { ssr: false }
);`

**Comment by jonahcarneskog** [comment]
```
const Editor = dynamic<EditorProps>(
  () =>
    import("react-draft-wysiwyg").then(
      (mod) =>
        mod.Editor as unknown as React.FC<
          PropsWithChildren<{
            editorState: any;
            wrapperClassName: string;
            editorClassName: string;
            editorStateChange: any;
          }>
        >
    ),
  { ssr: false }
);
```

**Comment by akshay-aravind** [comment]
I am also facing the same issue.

**Comment by akshay-aravind** [comment]
> Update: I tried to use the `resolutions` solution, but it did not seem to work for me; Of note, the `Editor` from `draft-js` directly does not produce the same error.
> 
> Temporary Solution is brute force type casting
> 
> ```
> import { default as _Editor } from '@draft-js-plugins/editor';
> import { PluginEditorProps } from '@draft-js-plugins/editor';
> 
> const Editor = (_Editor as unknown) as React.FC<React.PropsWithChildren<PluginEditorProps>>;
> ```
> 
> However, I am running into issues with the `Anchor` Plugin, and not sure yet if that is a separate issue or related to this one.

Thanks, was facing the same issue and this fixed it.

**Comment by akshay-aravind** [comment]
> The repo I was working in uses workspaces and we had packages that were `nohoist` in `package.json`. Added `**/@draft-js-plugins/**` to `nohoist`, deleted my node_modules and ran `yarn install` again. That got it working

Thanks, was facing the same issue and this fixed it.
