### ISSUE TITLE
[mention] Suggestions won't show up if the editor is focused on componentDidMount

### ISSUE THREAD

**Issue by tleunen** [draft-js-plugins/draft-js-plugins#285]
If the editor is focused on `componentDidMount` with `this.refs.editor.focus();`, the suggestions will never be displayed after typing `@`.

The same issue will appear if you have hot reload enable in your setup and if the editor is focused when reloading the component.

**Comment by nikgraf** [comment]
Discussed it with @tleunen on the chat.

Preliminary conclusion: Re-initialise the editor fresh on every render probably wipes the decorators.

**Comment by nikgraf** [comment]
Discussed it with @tleunen in the chat.

Preliminary conclusion: Initialising the editor fresh on every render probably also wipes the decorators.

**Comment by tleunen** [comment]
What do you mean by "initializing the editor on every render"?

**Comment by nikgraf** [comment]
Just read through the chat again: I misunderstood this one: `so maybe something doesn't work well when the component is rendered multiple times?`

**Comment by tleunen** [comment]
Yep, that was before discovering that the issue comes from the focused element :)

**Comment by bsapozhnikov** [comment]
Hi, just wanted to bump this as I'm coming across the same issue. Any way to focus on componentDidMount without losing mention functionality?

**Comment by bsapozhnikov** [comment]
Update: Solution is to defer focusing in componentDidMount e.g. setTimeout(focusFunction, 0)

**Comment by nikgraf** [comment]
@bsapozhnikov glad you figured it out although I'm wondering if we can do something in the core to fix this issue …

**Comment by mccord** [comment]
any plans to fix this? i'm really glad i found this bug with a google search, so i could add in the workaround.
