### ISSUE TITLE
Mention Suggestion Shows up in Unrelated Spaced Position

### ISSUE THREAD

**Issue by bekkou68** [draft-js-plugins/draft-js-plugins#289]
I found a mention suggestion shows up in unrelated spaced position.
The problem seems occurred when I type a suggested name directly and type the space key.
And it seems solved when I type the enter key to fix a HTML element.

<image src="https://cloud.githubusercontent.com/assets/322852/15644877/67e67f98-2690-11e6-9c15-a80545843ef3.gif" width="50%" />

**Comment by nikgraf** [comment]
hey @bekkou68 - this might be related to: https://github.com/draft-js-plugins/draft-js-plugins/issues/206#issuecomment-219192040 and https://github.com/draft-js-plugins/draft-js-plugins/blob/master/FAQ.md#why-is-there-no-popover-for-mentionsemoji-plugin

Your editor might be nested inside a styled element which causes the troubles. Can you verify if that's the case?

**Comment by nikgraf** [comment]
fixed with https://github.com/draft-js-plugins/draft-js-plugins/pull/309 & going to be in the next release

**Comment by nikgraf** [comment]
I close this issue for now. Let me know in case it didn't work after the next release.

**Comment by hasnainshafqatmlt** [comment]
Hello guys, 
will you please help me how i can change it's position from bottom to top ?
i want to show mention list on top of the text instead of bottom.

![screen shot 2017-11-06 at 8 19 00 pm](https://user-images.githubusercontent.com/6399158/32448072-c217ad4c-c32f-11e7-8aa7-f349695c9218.png)
