### ISSUE TITLE
Inline toolbar not adjusting its position according to space

### ISSUE THREAD

**Issue by hb1998** [draft-js-plugins/draft-js-plugins#2897]
## Environment

"@draft-js-plugins/inline-toolbar": "^4.1.6",
"@draft-js-plugins/editor": "4.1.3",

## Description

when we try to open the inline toolbar in the right most edge, its not adjusting itself to the left, to view the full toolbar  (Im inside a iframe so the dotted lines u see is the right most edge of `body`) 
![image](https://user-images.githubusercontent.com/33490801/183023576-b3b5e3d1-d01c-49db-bd5b-d1c7ddad8af4.png)

this is the full toolbar 
![image](https://user-images.githubusercontent.com/33490801/183024308-be1b3573-2c08-4822-af96-094286fca733.png)

Are there any APIs to position the toolbar or will this be addressed as an issue ?

**Comment by hb1998** [comment]
@fxOne  even in the example provided in the docs 
![image](https://user-images.githubusercontent.com/33490801/183275568-f56f9f4c-0252-4d47-8c00-91f5b6bc0585.png)

you can see that it doesn't actually position itself to the left rather it changes the width and positions itself at the top
this is also not a foolproof solution, since when we don't have space at the top as well, it crops 
![image](https://user-images.githubusercontent.com/33490801/183275602-2e215d12-f50a-43e6-bce0-52b1c95e0e96.png)

can we do something like this 

https://user-images.githubusercontent.com/33490801/183275679-d1c6f93b-3752-4b21-b209-9b29db122c77.mov

reference : https://github.com/yabwe/medium-editor

**Comment by Flip437** [comment]
> As it looks ok on https://www.draft-js-plugins.com/plugin/inline-toolbar I would guess that this it is a CSS issue. You can set your own CSS as you can see in the `Themed Inline Toolbar Example`.

Hello,

Could you tell why themed toolbar crashes if not initialized with both files buttonStyles.module.css and toolbarStyles.module.css event if toolbarStyles.module.css is an empty file ?

this works:
```
import buttonStyles from "../../components/rich_text_editor/buttonsStyles.module.css";
import toolbarStyles from "../../components/rich_text_editor/toolbarStyles.module.css";
const toolbarPlugin = createToolbarPlugin({
  theme: { buttonStyles, toolbarStyles },
});
```

this raise an Uncaught TypeError: error : 
```
import buttonStyles from "../../components/rich_text_editor/buttonsStyles.module.css";
import toolbarStyles from "../../components/rich_text_editor/toolbarStyles.module.css";
const toolbarPlugin = createToolbarPlugin({
  theme: { buttonStyles, toolbarStyles },
});
![Capture d’écran 2022-09-08 à 11 36 07](https://user-images.githubusercontent.com/55752474/189088998-082655f3-17ca-4d31-846a-16dc1b26e86f.png)

```

I repeat, toolbarStyles.module.css is completely empty.

Thanks a lot.
flip

**Comment by hb1998** [comment]
@Flip437 
why would you want an empty module.css file, if you don't want to change the styling don't add them to the options if you wont to customize them make sure you add the classes needed.

**Comment by Flip437** [comment]
> @Flip437 why would you want an empty module.css file, if you don't want to change the styling don't add them to the options or if you want to customize them make sure you add the classes needed.

I don't want one, but I need one if I want createToolbarPlugin to work. If files are note passed to this function, it crashes.
