### ISSUE TITLE
Could we expose a ref to the `EmojiSelect`'s button?

### ISSUE THREAD

**Issue by wlewis-formative** [draft-js-plugins/draft-js-plugins#2903]
## Describe the feature

I'd like to expose the `EmojiSelect`'s button ref to consumers.

## Motivation

This would allow consumers to programmatically open the select by calling `ref.current?.click()`. At the moment, there's no way to do so.

## Possible implementations

This should be a simple matter of adding a new prop (e.g. `buttonRef`), and wiring it up to the inner `button` component.

## Notes

If you're interested in this feature, I'd be happy to contribute the changes.

**Comment by fxOne** [comment]
I think to add `forwardRef` to `EmojiSelect` would be the best. I have no idea if it also works with classes but it should be easy to convert it to a functional component. 
I would love to merge a pull request.
