### ISSUE TITLE
[emoji] Emojis won't show up on the demo

### ISSUE THREAD

**Issue by nhtera** [draft-js-plugins/draft-js-plugins#293]
I've tried on Chrome (Mac OSX 10, iPhone 6 Plus, Nexus 5), Safari (iPhone 5, 6 plus) but emoji can't showing.

![emoji-error](https://cloud.githubusercontent.com/assets/2976973/15769998/7c515906-298a-11e6-8f00-b169a25a6129.gif)

#292

**Comment by nikgraf** [comment]
Thx @nhtera for reporting. No idea why this suddenly is happening …

**Comment by nikgraf** [comment]
just release a new version with the fixes 🙌
