### ISSUE TITLE
Plugins are always recreated when special circumflex or diaeresis accents are writed in empty blocks of the editor

### ISSUE THREAD

**Issue by ShakurOo** [draft-js-plugins/draft-js-plugins#2958]
## Environment

- @draft-js-plugins/editor version: `3.0.0`
- plugin name and version: `Custom plugin`
- MacOS Catalina 10.15.7 (I7 2,9GHZ, 16go RAM)
- Chrome version **Version 105.0.5195.125 (Build officiel) (x86_64)**

## Description
For each empty block, when you typing one of the following characters: `ê` or `ë` (combinaison of two keys to being added), **all active plugins are remounted** ! This behavior is not reproductible when these special chars follows any other character.

## Reproducible Demo

Go to : https://codesandbox.io/s/draftjs-plugins-editor-forked-xusi9c?file=/src/Editor.js
1. Open the console, you see one `Test2Plugin mount !`, all's fine.
2. Break the line
4. Now type character `ê` as first character
5. TADAAA, there is a new log `Test2Plugin mount !`, which means that the Plugin is remounted !
6. Break the line
7. Type any other character as first character, there is no problem, even if you write `ê` after

![image](https://user-images.githubusercontent.com/14843759/192156025-69255303-9f51-4958-9f92-0de978bf4b79.png)

**Comment by fxOne** [comment]
I cannot reproduce this issue with the latest Chrome version. Also I would recommend to update draftjs and all plugins to the latest version.

**Comment by ShakurOo** [comment]
Hi @fxOne,

I forgot to give informations about the test environnement. So I updated my first comment. Could you give me your setup environnement ? This problem could be related to global performance. Can you try to throttle your CPU in dev tools ?

**Comment by fxOne** [comment]
I have tested it on Windows 10 with Chrome Version 105.0.5195.127. 
You are not using the latest versions, they package were renamed to `@draft-js-plugins/editor` etc. Can you test it without the plugins and by using `draft-js` alone?

**Comment by ShakurOo** [comment]
Yes I'll.

For information, I've also tested in Windows 11 with Chrome version `105.0.5195.128` and I have no problem, event with CPU throttle. So the problem might be related to OS ? Hmmm...

**Comment by ShakurOo** [comment]
@fxOne I updated the sandbox :
- I removed all useless stuff (components, libs, etc ...)
- I bump packages to their latest version
- I use `draft-js` Editor comp. vs `@draft-js-plugins/editor` => No problem

But it seem's legit because the `console.log` was declared inside the `useEffect` of the plugin itself. and draft-js doesn't recognize the `plugins` prop. 

Could you test the sandbox in Mac OS environment ?

**Comment by fxOne** [comment]
Sadly I have no access to a Mac.
You can test it with the `draft-js` by simply using the decorator prop with your plugin:
```jsx
<Editor editorState={editorState} onChange={onChange} decorators={placeholderPlugin.decorators} />
```

Mac is doing some wired stuff as you can see in this issue: https://github.com/draft-js-plugins/draft-js-plugins/issues/1740 Maybe this is something similar.
