### ISSUE TITLE
[EDITOR] - I'm getting an error when using the editor

### ISSUE THREAD

**Issue by EwanValentine** [draft-js-plugins/draft-js-plugins#296]
I've included the editor with plugins, with the hashtag plugin. 

```
render() {
  const hashtagPlugin = createHashtagPlugin  
  return(
    <Editor editorState={editorState} 
                 tabIndex="1"
                 plugins={[hashtagPlugin]}
                 onChange={this.onChange}
                 ref="content" />
  )
}
```

But I get...

```
bundle.js:2981 Uncaught (in promise) Error: findComponentRoot(..., .0.0.0.0.0:1.1.0.0.1.0.0.1.0.$i): Unable to find element. This probably means the DOM was unexpectedly mutated (e.g., by the browser), usually due to forgetting a <tbody> when using tables, nesting tags like <form>, <p>, or <a>, or using non-SVG elements in an <svg> parent. Try inspecting the child nodes of the element with React ID ``.
```

Whereas if I use the standard Editor component, I don't get any errors.

**Comment by nikgraf** [comment]
@EwanValentine first thing I see: you need to invoke `createHashtagPlugin` -> `createHashtagPlugin()`

In case this still leads to an error: can you publish a small repo that I can run with `npm install` & `npm start`? That would be ideal so we can help you out 👍

**Comment by juliankrispel** [comment]
I'm closing this issue, if you think this issue is still relevant please let us know why and we'll consider reopening it. Thank you for contributing ✌️
