### ISSUE TITLE
Autocomplete for mentions misbehaves when wrapped with StrictMode

### ISSUE THREAD

**Issue by lcmen** [draft-js-plugins/draft-js-plugins#2966]
## Environment

- @draft-js-plugins/editor version: 4.1.3
- @draft-js-plugins/mention: 5.2.1
- draft-js: 0.11.7
- react: 18.2.0
- react-dom: 18.2.0

## Description

When `draft-js` editor and mention suggestions are within `<StrictMode>` component, autocomplete pop-up appears after at least 1-2 letters are typed (after `mentionTrigger`). I've briefly debugged it and I've found out that normally this line: https://github.com/draft-js-plugins/draft-js-plugins/blob/f38fd3ac0ab3cae3e836baae41708d2796d25952/packages/mention/src/MentionSuggestionsPortal.tsx#L31 is called before https://github.com/draft-js-plugins/draft-js-plugins/blob/f38fd3ac0ab3cae3e836baae41708d2796d25952/packages/mention/src/index.tsx#L139 (so setter is called first, then the getter). With strict mode though, the setter is called **after** the getter, and because of it, there is no reference for popper after the triggered.

## Reproducible Demo

https://codesandbox.io/s/draft-js-mention-plugin-plain-text-mention-forked-r1x393 (You can type `@ab` then hit backspace twice).

**Comment by hatsu38** [comment]
I had the same problem. Is there a good solution?
I would like to create a pull request to solve this problem.

**Comment by holdenmatt** [comment]
Also running into this. Would love to know if anyone finds a workaround or fix for it.

**Comment by niikkiin** [comment]
also having this issue right now, does anyone of you found a solution? thanks

**Comment by TheSizkarn** [comment]
I'm also in the same situation!

**Comment by lcmen** [comment]
Thank you! The latest version fixes it.
