### ISSUE TITLE
Editor in "EditorPreview" state doesn't accept text-align inline styles

### ISSUE THREAD

**Issue by Yehorchik** [draft-js-plugins/draft-js-plugins#2967]
## Describe the feature

Currently Editor  in "EditorPreview" state accepts styles like "BOLD", "ITALIC", but not "center", "right", "left". It would be nice to add these styles as well. I can adjust text-alignment on regular editor but not in preview mode

**Comment by fxOne** [comment]
What do you mean by `EditorPreview`?

**Comment by Yehorchik** [comment]
@fxOne Sorry , I explained it wrong, here is the example of my code 
```
const DraftJsPreview: React.FC<{
  block: ContentBlock;
}> = ({ block }) => {
  const decorator = new CompositeDecorator([
    {
      strategy: findLinkEntities,
      component: Link,
    },
  ]);

  const content = !block.content.data
    ? EditorState.createEmpty()
    : EditorState.createWithContent(convertFromRaw(block.content.data), decorator);

  if (!block.content.data) {
    return null;
  }

  const blockStyleFn = (bl: DraftJsContentBlock) => {
    let alignment = "left";
    bl.findStyleRanges(
      (e) => {
        if (e.hasStyle("center")) {
          alignment = "center";
        }
        if (e.hasStyle("right")) {
          alignment = "right";
        }
        return true;
      },
      () => {},
    );
    return `editor-alignment-${alignment}`;
  };

  return (
    <DraftJsContainer>
      <Editor
        blockStyleFn={blockStyleFn}
        editorKey="EditorPreview"
        editorState={content}
        readOnly
        onChange={() => {}}
      />
    </DraftJsContainer>
  );
```
In `readOnly` mode Editor doesn't read alignment styles, instead I need manually assign specific class to each container to make it work. I don't need to use the same approach with "BOLD" and "ITALIC" styles. Is there any way to make Editor assign alignment styles automatically , without calling `blockStyleFn` ?

**Comment by fxOne** [comment]
Currently I cannot see there anything related to `draft-js-plugins`. Also, you should memorize the `editorState` and the `decorator` because they are recreated after a rerendering, which can break the editor.
