### ISSUE TITLE
After click on mention suggestion and format text after mention then text doubles

### ISSUE THREAD

**Issue by aXenDeveloper** [draft-js-plugins/draft-js-plugins#2977]
## Environment
    "@draft-js-plugins/editor": "4.1.3",
    "@draft-js-plugins/mention": "5.2.1",
    "draft-js": "0.11.7",
    "react": "18.2.0",
    "react-dom": "18.2.0",
    "react-scripts": "4.0.0"

## Description

After click on mention suggestion and format text _(bold text by shortcut)_ after mention then text doubles.

Before bold:
<img width="652" alt="Screenshot 2022-10-16 at 9 39 53 PM" src="https://user-images.githubusercontent.com/58148176/196054776-7450d813-2bf6-41c8-a6a2-d3fa84d9bc16.png">

After bold:
<img width="652" alt="Screenshot 2022-10-16 at 9 40 08 PM" src="https://user-images.githubusercontent.com/58148176/196054797-083875dc-7b99-4f68-828a-b6573b95343a.png">

## Reproducible Demo

Demo: https://codesandbox.io/s/vigilant-ioana-v9i20l?file=/src/App.js

1. Type "matt",
2. Click on "Matthew Russell",
3. Type something else for example "test 123",
4. Select text "test 123",
5. Click shortcut for bold text,
6. Now text is "@Matthew Russell test 123test 123", but should be still "@Matthew Russell test 123".

**Comment by fxOne** [comment]
What is the shortcut for bold text?

**Comment by aXenDeveloper** [comment]
CRTL + B on Windows
Command + B on MacOS
