### ISSUE TITLE
How to update Mention Name?

### ISSUE THREAD

**Issue by bhaveshdaswani93** [draft-js-plugins/draft-js-plugins#2981]
## Environment

- @draft-js-plugins/editor version:
 "draft-js": "^0.11.7",
 "draft-js-emoji-plugin": "^2.1.3",
 "draft-js-linkify-plugin": "^2.0.2",
 "draft-js-mention-plugin": "^3.1.5",
 "draft-js-plugins-editor": "^3.0.0",
"react": "^16.13.1",
"react-dom": "^16.13.1",

## Description
How to update mention text when tag user changes his name?
For example when the user was tagged his name was John Doe, after some day the user change his name in the site to John D, I need to change the mention Name from John Doe to John D, at all the mention in the post. 

Is there some way or option provided by Mention plugin to do this?

**Comment by fxOne** [comment]
This is not supported by this plugin. You need to through the rawState and do it manually which should't be that hard.

**Comment by bhaveshdaswani93** [comment]
Are you referring to the below state we get from draft-js-plugins-editor

`{"blocks": [{"key": "9htle", "data": {}, "text": "Bha  #drone is good", "type": "unstyled", "depth": 0, "entityRanges": [{"key": 0, "length": 5, "offset": 0}, {"key": 1, "length": 6, "offset": 17}], "inlineStyleRanges": []}], "entityMap": {"0": {"data": {"mention": {"id": 101, "link": "/users/bhaveshchat1", "name": "bhavdaswani", "avatar": "/images/placeholders/profile_icon.png", "username": "bhaveshchat1"}}, "type": "mention", "mutability": "SEGMENTED"}, "1": {"data": {"id": 1, "name": "drone", "user_id": 101, "is_hidden": 0, "created_at": "2022-06-19 05:21:37", "created_by": "USER", "flag_count": 0, "image_path": null, "is_deleted": 0, "interestImage": null, "is_admin_approved": 0, "post_connection_count": 8, "interestActivityRating": 8, "comment_connection_count": 0, "unsplash_recommend_image_url": null, "unsplash_recommend_image_status": null}, "type": "interest", "mutability": "IMMUTABLE"}}}`

**Comment by fxOne** [comment]
Yes, this is one option

**Comment by bhaveshdaswani93** [comment]
Okay, @fxOne. Thanks for pointing it out and providing the direction.
