### ISSUE TITLE
Avoid issuing UNSAFE_componentWillMount when using InlineToolbar in StrictMode

### ISSUE THREAD

**Issue by hatsu38** [draft-js-plugins/draft-js-plugins#2983]
## Describe the feature

UNSAFE_componentWillMount error when using InlineToolbar in StrictMode.
I would like to avoid this error.

## Motivation

I want to use InlineToolbar in StrictMode.

## Possible implementations

You may want to change the code around here.
It may be good to rewrite from ClassComponent to FunctionComponent.
https://github.com/draft-js-plugins/draft-js-plugins/blob/8b4d9115ba42a22fb7d42548774873674a7351d0/packages/inline-toolbar/src/components/Toolbar/index.tsx#L64-L66

**Comment by fxOne** [comment]
Can you create a pull request with your suggested fix?
