### ISSUE TITLE
Repacing text with entity block 

### ISSUE THREAD

**Issue by Antherkiv** [draft-js-plugins/draft-js-plugins#299]
Hello I want to make a plugin and I need to replace text (only replace the text) with a entity block, I have an strategy an pass as decorated text to react component, but in the state it's actually text, then I understand I need a decorator and an strategy, bun then, what I need to do?

Thanks for your time and best regards.

**Comment by nikgraf** [comment]
What do you mean by entity block? Draft.js allows you to attach an Entity to a text-range. Of course you could have block which just contains one or zero character and attach an entity to it.

To get to the point: if the text you want to replace has a certain pattern you can write a decorator that attaches an Entity to the text-range. To avoid an endless loop of updates you make sure that it won't attach an entity if there is already an entity attached to that range.

Do you have some examples of what the input is and what the output should be? I believe this would allow me to help you way better than what I just described above 😄

**Comment by Antherkiv** [comment]
I did yet, I'm using a react component like proxy (I only use the componentWillMount and in the render I return null), it's because I don't want to decorate a text, I'm want to replace enterily with a non text component, I used a modifier remove the text and add a block, that's fine I can see my block in the newState, but, when I pass by the blockRendererFn, I got a "Got unexpected null or undefined", but it's strange, if I used a diferent component, like image plugin make for draft-wysiwyg, I didn't get that, I got the component, Obviously my entity data ara different.

I'm looking for a solution now, thanks.

**Comment by nikgraf** [comment]
@Antherkiv if you want to have a custom block you need to set a block type and then apply a custom `blockRenderFn` to be used to provide a custom component

see https://facebook.github.io/draft-js/docs/advanced-topics-block-components.html#custom-block-components

**Comment by Radivarig** [comment]
@nikgraf how would you attach an entity to the text range _over a decorator_? From tweet example in component props the entity key is null. Along the decorator, I could use the same regex to get ranges and if no entity there apply one. Was that what you meant?

**Comment by nikgraf** [comment]
@Radivarig whenever the decorator matches you can update the editorState from within the component. As you can see here the components get the props `getEditorState` & `setEditorState` as well: https://github.com/draft-js-plugins/draft-js-plugins/blob/master/draft-js-plugins-editor/src/Editor/createCompositeDecorator.js#L13

**Comment by Radivarig** [comment]
@nikgraf What I mean is to apply an entity to the matched ranges, so that I can identify it based on the current selection.
Is it a correct approach to do it from the decorator `strategy`? By binding get/set functions and creating selectionState with ranges from `callback`.

**Comment by grichmond-mdsol** [comment]
On my decorator function I don't seem to have the full set of props being passed through as per in the link example: 
```
const Link = (props) => {
        const {url} = props.contentState.getEntity(props.entityKey).getData();
        return (
          <a href={url} style={styles.link}>
            {props.children}
          </a>
        );
      };
```
 I am missing contentState which I need to get the entity. The only props being passed in are "decoratedText", "dir", "entityKey", "offsetKey" and "children".

I'm on 0.9.1

Happy to create a separate issue for this if you think it's the right thing to do.

**Comment by valorize** [comment]
@Radivarig could you show an example of your onChange? On https://github.com/facebook/draft-js/issues/161 it is advised not to alter the editorState in onChange. Therefore I wonder which is the right solution to the described problem

**Comment by Radivarig** [comment]
@valorize Uh, managed to dig this up from stash, but instead replacing over regex I ended up using Mentions plugin as mutating editorState had weird behavior in this case. It did replace but I wasn't able to input anything or it had inserted twice or something like that. My plan was to get all ranges that match some regex and if they weren't entities replace them with an entity of a specific type. Here's the code that was called from onChange:

```jsx
function applyEntitiesByRegex(getEditorState, setEditorState, data) {
  const AT_REGEX = /\B\@[\w]+/g
  var editorState = getEditorState()

  editorState
  .getCurrentContent()
  .getBlockMap()
  .map ((block, i) => {
    const blockKey = block.getKey()
    var ranges = findRangesWithRegex(AT_REGEX, block)
    ranges.map ((range, i) => {
      const start = range.start
      const end = range.end

      var selection = new SelectionState({
        anchorKey: blockKey,  anchorOffset: start,
        focusKey: blockKey,   focusOffset: end,
      })

      const entityKey = block.getEntityAt(start)
      if (entityKey === null)
        editorState = getStateWithEntity(editorState, selection, data)
    })
    if (editorState !== getEditorState())
        setEditorState(editorState)
  })
}
```

**Comment by Radivarig** [comment]
For the original question, here is the code I use for replacing selected text with an entity:
```jsx
getStateWithEntity (editorState, data) {
  const entityKey = Entity.create (type, mutability, data)

  var selection = editorState.getSelection()
  var start = selection.getStartOffset()
  var end = selection.getEndOffset()

  // empty selection hack
  if (start == end) {
    const zws = String.fromCharCode(8203)
    var modifiedContent = Modifier.insertText(
      editorState.getCurrentContent(),
      selection,
      zws,
      null,
      entityKey
    )
    return EditorState.push(editorState, modifiedContent, editorState.getLastChangeType())
  }
  else {
    const editorStateWithEntity = Modifier.applyEntity(
      editorState.getCurrentContent(),
      editorState.getSelection(),
      entityKey
    )
    return EditorState.push(editorState, editorStateWithEntity, 'apply-entity')
  }

}
...
this.onChange(this.getStateWithEntity(editorState, data))
```

**Comment by schabluk** [comment]
> if the text you want to replace has a certain pattern you can write a decorator that attaches an Entity to the text-range.

Hi @nikgraf, could you please elaborate more on this or show some examples?

I have a decorator with regex strategy to recognize a text pattern. Let's say I would like to add button next to my decorated text.
```javascript
class MyDecorator extends React.Component {
  render () {
    return <span data-offset-key={this.props.offsetKey}>
      <button contentEditable={false} onClick={this.props.handleClick)>+</button>
      {this.props.children}
    </span>
  }
}
```
The button should call a click handler function passed from class that wraps my Editor. However, there is no way to pass props to decorator. So, I was thinking to create Entity that will handle the click event. I can create this entity in my custom block component, using the same regex strategy, but it feels a bit redundant, so I was looking for better way. Any support much appreciated.

**Comment by Radivarig** [comment]
@schabluk you can use:
```jsx
import { List } from 'immutable'
import { CompositeDecorator } from 'draft-js'
import decorateComponentWithProps from 'decorate-component-with-props'

function MyCompositeDecorator (decorators, prop1, prop2 /*...*/) {
  
  const convertedDecorators = List(decorators)
    .map((decorator) => ({
      ...decorator,
      component: decorateComponentWithProps(
        decorator.component,
        { prop1, prop2 /*...*/ }
      ),
    }))
    .toJS()

  return new CompositeDecorator(convertedDecorators)
}
module.exports = MyCompositeDecorator
```
and then:
```jsx
import MyCompositeDecorator from 'MyCompositeDecorator'
import MultiDecorator from 'draft-js-multidecorators'

  createDecorator() {
    return new MultiDecorator([
      new MyCompositeDecorator(
        [
          { strategy: yourStuff.findEntities, component: yourStuff.getComponent },
          // ...
        ],
        // props
        prop1,
        prop2,
        // ...
        ),
        // other decorators
      ]
    )
  },

```
and your component will get the props.

**Comment by schabluk** [comment]
@Radivarig thank you very much. I owe you a beer!

**Comment by zhongkai** [comment]
@nikgraf , could you help me to take a look at this closed [issue](https://github.com/facebook/draft-js/issues/161)? I posted a question about the cursor jumping after replacing text of whole block.

That issue is linked to this issue and has been closed. But I can not find any clue about my problem according to your discussions above...

**Comment by Kiwka** [comment]
@Radivarig actually I think your example can be simplified, as the selectionState has method isCollapsed(), so no need to calculate start & end, the condition can look like selection.isCollapsed()

**Comment by juliankrispel** [comment]
I'm closing this issue, if you think this issue is still relevant please let us know why and we'll consider reopening it. Thank you for contributing ✌️
