### ISSUE TITLE
Plugins only work for first instance of editor when there are multiple editor instance

### ISSUE THREAD

**Issue by Abhishek2250** [draft-js-plugins/draft-js-plugins#3015]
## Environment
   System:
    OS: macOS 12.6
    CPU: (8) arm64 Apple M1 Pro
    Memory: 580.13 MB / 16.00 GB
    Shell: 5.8.1 - /bin/zsh
  Binaries:
    Node: 18.11.0 - /usr/local/bin/node
    Yarn: 1.22.19 - /usr/local/bin/yarn
    npm: 8.19.2 - /usr/local/bin/npm
    Watchman: Not Found
  Managers:
    CocoaPods: 1.11.3 - /Users/abhi/.rvm/rubies/ruby-2.7.5/bin/pod
  SDKs:
    iOS SDK:
      Platforms: DriverKit 21.4, iOS 16.0, macOS 12.3, tvOS 16.0, watchOS 9.0
    Android SDK: Not Found
  IDEs:
    Android Studio: 2021.3 AI-213.7172.25.2113.9123335
    Xcode: 14.0.1/14A400 - /usr/bin/xcodebuild
  Languages:
    Java: 11.0.16.1 - /usr/bin/javac
  npmPackages:
    @react-native-community/cli: Not Found
    react: ^17.0.2 => 17.0.2 
    react-native: ^0.68.1 => 0.68.5 
    react-native-macos: Not Found
  npmGlobalPackages:
    *react-native*: Not Found

- @draft-js-plugins/editor version: 4.1.3
- plugin name and version:
- "@draft-js-plugins/hashtag": "^4.2.2",
    "@draft-js-plugins/linkify": "^4.2.1",
    "@draft-js-plugins/mention": "^5.2.1",

## Description

I have made a generic component having the editor and plugins and used that component more than 2 times on a same parent component. Plugins are only working for 1st one editor comp.

Generic comp code:
	const [editorInState, setEditorInState] = useState(() => EditorState.createEmpty());
	const [suggestions, setSuggestions] = useState(mentionData);
	const [isSuggestionOpen, setIsSuggestionOpen] = useState(false);
	const [, setTagName] = useState("");

	const mentionEditorRef = useRef<Editor>(null);

	const { MentionSuggestions, plugins } = useMemo(() => {
		const mentionPlugin = createMentionPlugin({
			entityMutability: "IMMUTABLE",
			theme: commentMentionsStyles,
			mentionPrefix: "@",
			mentionTrigger: "@",
			supportWhitespace: true,
			mentionComponent: (mentionProps) => {
				const item = mentionProps.mention;
				return (
					<span className={mentionProps.className} contentEditable={false}>
						{`@${item.title ?? item.name}`}
					</span>
				);
			},
		});
		const { MentionSuggestions } = mentionPlugin;
		const hashtagPlugin = createHashtagPlugin({ theme: commentMentionsStyles });
		const linkifyPlugin = createLinkifyPlugin({ theme: commentMentionsStyles });
		const plugins = [mentionPlugin, hashtagPlugin, linkifyPlugin];
		return { plugins, MentionSuggestions };
	}, []);

	useEffect(() => {
		setSuggestions(mentionData);
	}, [mentionData]);

	useEffect(() => {
		if (isFocused && !disabled) {
			mentionEditorRef.current?.focus();
		}
	}, [isFocused]);

	const onChangeEditorText = (editorState: any) => {
		const contentState = editorState.getCurrentContent();
		const oldContent = editorInState.getCurrentContent();
		if (contentState === oldContent || contentState.getPlainText().length <= 1500) {
			setEditorInState(editorState);
		} else {
			const updatedEditorState = EditorState.moveFocusToEnd(
				EditorState.push(
					editorInState,
					ContentState.createFromText(oldContent.getPlainText()),
					"undo",
				),
			);
			setEditorInState(updatedEditorState);
		}
		if (contentState !== oldContent) {
			const text = editorState.getCurrentContent().getPlainText();
			if (onChangeText) {
				onChangeText(text);
			}
		}
	};

	const onSuggestionOpenChange = useCallback((open: boolean) => {
		if (!open) {
			setSuggestions(mentionData);
		}
		setIsSuggestionOpen(open);
	}, []);

	const onSearchChange = ({ value }: { value: string }) => {
		if (value && value.trim()) {
			const searchTag = value.trim();
			setTagName(searchTag);
			const msgData = {
				//req obj
			};
			if (getSuggesionsFromServer) getSuggesionsFromServer(msgData);
		} else {
			setTagName("");
			setSuggestions(mentionData);
			if (getSuggesionsFromServer) getSuggesionsFromServer(null);
		}
	};

	const onSearchChangeDebounce = useDebouncedCallback(({ value }: { value: string }) => {
		onSearchChange({ value });
	}, 500);

	const addMention = (item: any) => {
		setTagName("");
	};

	const resetEditorState = useDebouncedCallback(() => {
		const newEditorState = EditorState.moveFocusToEnd(
			EditorState.push(
				editorInState,
				ContentState.createFromText(""),
				"undo",
			),
		);
		setEditorInState(newEditorState);
	}, 500);

	const showBoldText = (props: any) => (<span className="font-bold">{props.children}</span>);

	const renderSuggestions = ({
		mention,
		theme,
		searchValue,
		isFocused,
		...parentProps
	}: any) => (
		//render suggestion here
	);

	const onFocus = () => {
		// focus logic here
	};

	return (
		<div>
			<div
				onClick={onFocus}
				aria-hidden
			>
				<div style={{ flex: 1 }}>
					<Editor
						placeholder={placeHolder}
						editorKey="editor"
						editorState={editorInState}
						onChange={onChangeEditorText}
						plugins={plugins}
						ref={mentionEditorRef}
					/>
				</div>
				<MentionSuggestions
					open={isSuggestionOpen}
					onOpenChange={onSuggestionOpenChange}
					onSearchChange={onSearchChangeDebounce}
					suggestions={suggestions}
					onAddMention={addMention}
					entryComponent={renderSuggestions}
				/>
			</div>
		</div>
	);

##Demo:
https://codesandbox.io/s/adoring-johnson-j8m5u9?file=/src/MentionInput.tsx
Note: styling is not applying in demo. Hashtag and link text should be in blue

Thanks!

**Comment by fxOne** [comment]
Can you create a reproducer on [codesandbox.io](https://codesandbox.io/)?

**Comment by Abhishek2250** [comment]
@fxOne tried to add my code on sandbox: https://codesandbox.io/s/adoring-johnson-j8m5u9?file=/src/MentionInput.tsx
Styling is not applying in demo. Hashtag and link text should be in blue.

**Comment by fxOne** [comment]
You can fix the issue with:

```js
  useEffect(() => {
    if (isFocused && !disabled) {
      setTimeout(()=> mentionEditorRef.current?.focus(),0);
    }
  }, [isFocused, disabled]);
```
You can find more information here: https://github.com/draft-js-plugins/draft-js-plugins/issues/800

**Comment by Abhishek2250** [comment]
Wow! A bit strange soln but it's working.
Thanks
