### ISSUE TITLE
Decorator component start index is different from callback strategy start index with Formik enableReinitialize

### ISSUE THREAD

**Issue by pauldmps** [draft-js-plugins/draft-js-plugins#3016]
## Environment
 "react": "^17.0.2"
 "react-dom": "^17.0.2"

- @draft-js-plugins/editor version:
"@draft-js-plugins/editor": "^4.1.3"
"@draft-js-plugins/mention": "^5.2.1"
"draft-js": "^0.11.7"

## Description
My use case is to show any text which is wrapped in parenthesis {} in a different color and bold font in the editor. I am using a Composite decorator for that purpose. This decorator works as expected with draft-js Editor instance but misbehaves with the @draft-js-plugins/editor.

The output component from composite decorator selects incorrect text. On console.log, I can see that the component props has incorrect start index. This happens only when the Wrapping Formik component has "enableReinitialize" prop set as true.

![image](https://user-images.githubusercontent.com/6829986/201724881-bbef0ae2-108e-49eb-8266-d1722daef061.png)

## Reproducible Demo
https://codesandbox.io/s/hungry-bassi-52eysu

**Comment by pauldmps** [comment]
Any updates?

**Comment by fxOne** [comment]
Can you provide a fix?
