### ISSUE TITLE
EditorState does not contain link data

### ISSUE THREAD

**Issue by jarsbe** [draft-js-plugins/draft-js-plugins#302]
Using the linkify plugin correctly decorates links by wrapping them in an anchor tag, however the editor state, when converted to raw or JS, is missing the link entity data. I'm assuming the plugin is only rendering the link and not updating the editorState - is this the case?

**Comment by nikgraf** [comment]
@jarsbe you are correct, based on the decorator the links are identified on demand.

What's your use-case? When would the link as an entity be interesting to you?

**Comment by jarsbe** [comment]
@nikgraf Oh cool - I want to convert the editorState into HTML with links included. I suppose I could re-implement the 'link grepping' but it returning an editorState with link data seems more like an expected behaviour?

**Comment by jarsbe** [comment]
Happy to dig into this btw if you can point me in the right direction

**Comment by nikgraf** [comment]
@jarsbe this should help you on how to attach entities: https://facebook.github.io/draft-js/docs/advanced-topics-entities.html#creating-and-retrieving-entities

Here you can see an example of how we use it to attach Emojis: https://github.com/draft-js-plugins/draft-js-plugins/blob/master/draft-js-emoji-plugin/src/modifiers/addEmoji.js

In general what you would need to do is hook into onChange, parse the links and then attach an entity. I not sure if this should be part of the linkify-plugin as it would increase complexity and I'm not sure how many people would use that feature.

What about you take the plugin and you or we publish it as `draft-js-entity-linkify-plugin`

Does that help?

**Comment by jarsbe** [comment]
@nikgraf great, thank you so much for the tips. A separate plugin looks like a good idea. I'll be able to dive into this next week 👍

**Comment by jarsbe** [comment]
Totally on the money, much easier to let the plugin editor present the links and then linkify the editor state after the fact.

https://gist.github.com/jarsbe/af55f3705add9d9ec34fd0cb25ef2f67

**Comment by oyeanuj** [comment]
@jarsbe Looks good! Do you also plan to publish it as a separate plugin or enhance the current linkify plugin?

**Comment by nikgraf** [comment]
Well done @jarsbe! I case you plan to publish this on npm let me know. Happy to add a link to the Readme or docs.

**Comment by jarsbe** [comment]
Sure thing, will pop this up on the interwebs. Just on holiday atm... ☀️

**Comment by nikgraf** [comment]
enjoy @jarsbe 😃

**Comment by adrianca** [comment]
@nikgraf @jarsbe 
Wouldn't this be more performant if it was included with the linkify-plugin?
I mean, linkify already does all that work, and duplicating that logic every time content changes means grepping the text twice to parse out the links.

**Comment by tarjei** [comment]
I have to agree with @adrianca here. I was very surprised that the plugin didn't actually modify the output of the editor - this reduces the value of the plugin quite a lot(IMHO). 

Would it change the code a lot to include the editorstate changes into the plugin?

**Comment by nikgraf** [comment]
@adrianca it sounds like it would be more performant in case you do some changes. So far I haven't had any issues since regex & component rendering is quite fast.

@tarjei to me it's not about code, but rather about the behavior. I think there are two valid use-cases and therefor I suggest we create  two separate plugins. Would love to see @jarsbe's version published to npm and added to the readme as community plugin.

**Comment by danii1** [comment]
I think this plugin should create/update link entities, I've thought it does what's needed until I stumbled upon export to html bug. Another issue, if you paste some text with links into editor from the browser page, entities will be in editor state, however when you modify link, link entity in entityMap remain unchanged, so after export you'll get the link pointing to the old location with the new text.

**Comment by anders0l** [comment]
It's too outdated, but it can help somebody https://gist.github.com/anders0l/7a2c2b9a59b1c66a85089c597984d916

**Comment by fedorovsky** [comment]
https://github.com/fedorovsky/draft-js-link-detection-plugin

**Comment by sibelius** [comment]
what is the best way to solve this?

**Comment by glcheetham** [comment]
@fedorovsky saved my life
