### ISSUE TITLE
linkify: apply LINK entities to draft-js ContentState for found links

### ISSUE THREAD

**Issue by Nic0S** [draft-js-plugins/draft-js-plugins#3022]
## Describe the feature

I have this basic working example of the editor with linkify that prints out the draft ContentState on each render: https://codesandbox.io/s/infallible-pond-2k58hk?file=/src/Editor.tsx

I notice that despite the links being correctly recognized when typed into the editor, the draft-js ContentState does not reflect them. It seems like ideally a LINK entity to be applied to the URL text in the ContentState to enable other code to take advantage of the linkification.

## Motivation

When the user submits text from the editor, we do processing on the raw ContentState based on the entities applied to the text (specifically we convert to markdown). Having the LINK entities applied in ContentState would enable easy conversion to markdown links. I can imagine this could be useful for many applications that are converting the ContentState to another format.

## Possible implementations

I'm not sure if it's possible for the plugins to modify the EditorState directly to add the LINK entities, but perhaps there could be a callback triggered when a link is detected so that the parent component could add a LINK entity to the text range?

**Comment by fxOne** [comment]
You can use the `extractLinks` function exported from the plugin to get all detected links from the text.

Changing the behavior of the plugin to use entities would be a breaking change, as it would not work with older versions. Since `draft-js` is no longer being developed, it would not make much sense to make such changes.
