### ISSUE TITLE
Mention plugin in not working properly in mobile

### ISSUE THREAD

**Issue by abinashpanda** [draft-js-plugins/draft-js-plugins#303]
**Steps to reproduce the bugs**
1. Visit https://www.draft-js-plugins.com/plugin/mention from mobile.
2. In the _Simple Example_, add a mention.
3. Completely delete the mention
4. Try to add a new mention.

**Expected Behaviour**
It should show all the mentions available.

**Behaviour**
It doesn't show anything. Even typing @ doesn't work for few times.

**Platform** 
_Browser_: Chrome 51.0.2704.81
_Operating System_: Android 6.01, Nexus 5 Build/MOB30H

**Comment by nikgraf** [comment]
thx for reporting, I don't have an Android phone at hand right now. Works in iOS, but will try this probably tomorrow.

**Comment by abinashpanda** [comment]
@nikgraf Any update on this issue? Are you able to reproduce the bug?

**Comment by Zhouzi** [comment]
Hey @abinashpanda I just gave it a try on an Android 5.0.1 with Chrome 51.0.2704.81 but while I faced other issues, I can't reproduce the one you mentioned. It may be due to my Android version not being up to date but can you confirm that you're still facing the issue? Meanwhile, I'll dig deeper and test with an Android 6.

**Comment by nikgraf** [comment]
@abinashpanda can you maybe do a recording and eventually even debug?

thx for the effort @Zhouzi - I'm curious what issues you encountered 😄

**Comment by khankuan** [comment]
Just to add, found a couple of bugs:
Device: Nexus 5x
Android: 6.0.1
Browser: Chrome 51.0.2704.81
Keyboard: Swiftkey 6.3.6.46

1) Sticker: After inserting sticker, backspace closes the keyboard and does not remove the sticker
2) Hashtag: Typing "#test" ends up with #test#test as plain text. Typing after that became totally bugged
3) Emoji: Erasing a emoji needs 2 backspace. After that, typing a colon would create the same emoji even though i have not typed anything letter (Dropdown does not appear also).

**Comment by nikgraf** [comment]
thx for reporting, there are some tricky edge cases. Some may even be related to draft.js itself. Can you create separate issue for each of them?

**Comment by abinashpanda** [comment]
@nikgraf Sorry for the delay.  I have attached the screencast of the bug that I am facing. Please have a look and let me know if I missed something.


![mentions-screencast](https://cloud.githubusercontent.com/assets/2332955/17084077/6d42a454-51d2-11e6-82ab-43796dc987bb.gif)

**Comment by mzbac** [comment]
Hi @abinashpanda,
I have tried three issues you mentioned, I couldn't reproduce it on my Samsung s5. Since we redeploy the demo website with latest version of draftjs plugin. Could you try on your mobile see if problem solves

**Comment by mattRobinsonOakton** [comment]
We are seeing this problem - I can easily reproduce this on my Google Pixel. 

Using https://www.draft-js-plugins.com/plugin/mention (the Simple Example) :

Type @ and select a user, 
then type a couple of letters, 
then delete everything in the editor with the backspace key, 
type @ and the keyboard closes.

Attached is the console errors being generated

![image](https://cloud.githubusercontent.com/assets/25337957/22277974/f7386388-e313-11e6-95ae-f773f2681af1.png)

Maybe that can help pinpoint the issue?

cheers,

Matt

**Comment by mattRobinsonOakton** [comment]
This problem only happens when the @mention element is starting to be deleted from the draft editor.  We also see this with the Link and Tags plugins...

Once the error has happened, then none of these plugin types will work unless the page is reloaded.

**Comment by Mair** [comment]
This seems to also happen on windows mobile 8.0 and iPhone 5 (seems OK on 5S and later)

**Comment by AndrewSouthpaw** [comment]
Repro'ed on a Nexus 7, Android 6.0.1, Chrome 53, using the steps described above. Same ol' `Failed to execute 'removeChild' on 'Node'`...

**Comment by mattRobinsonOakton** [comment]
Bump

**Comment by ruby97** [comment]
in chrome, i need to type "backward" two times to remove a emoji character.
and i fix the problem as follows 


```
/**
 function to remove a range of text in a block
*/
const removeCharacterByRange: (editorState: EditorState, blockKey: string, startOffset, endOffset) => EditorState = (editorState, blockKey, startOffset, endOffset) => {
    let content = editorState.getCurrentContent();
    let targetRange = new SelectionState({
        anchorKey: blockKey,
        anchorOffset: startOffset,
        focusKey: blockKey,
        focusOffset: endOffset,
    });

    let removeResult = Modifier.removeRange(content, targetRange, 'backward');
    let resetBlock = Modifier.setBlockType(
        removeResult,
        removeResult.getSelectionAfter(),
        'unstyled',
    );

    let newState = EditorState.push(editorState, resetBlock, 'remove-range');
    return EditorState.forceSelection(newState, resetBlock.getSelectionAfter());
}

/**
callback function of editor, to handle key command
*/
handleKeyCommand(command) {
        const {editorState} = this.state;
        let selectionState = editorState.getSelection();
        let anchorKey = selectionState.getAnchorKey();
        let currentContent = editorState.getCurrentContent();
        let currentContentBlock = currentContent.getBlockForKey(anchorKey);

        if (command == "backspace") {
            let length = currentContentBlock.getLength();
                try {
                   // import emojiRegex from 'emoji-regex';
                    const regex = emojiRegex();
                    let text = currentContentBlock.getText();
                    let match;
                    let lastEmoji;
                    let textLength = currentContentBlock.getLength();
                    let lastEmojiIndex = null;

                    while (match = regex.exec(text)) {
                        lastEmoji = match[0];
                        lastEmojiIndex = match.index;
                    }

                    if (lastEmojiIndex !== null) {
                        if (lastEmojiIndex + 3 == textLength) {
                            setTimeout(() => {
                                let newState = removeCharacterByRange(editorState, anchorKey, lastEmojiIndex, textLength);
                                this.setState({editorState: newState});
                            }, 0);
                        }
                    }
                } catch (e) {
                    console.log(e);
                }
            }
        } else {
           // handle other key commands
        }
    }


```

**Comment by jianfenkezhan** [comment]
This problem can be fixed as follows:
https://github.com/facebook/draft-js/issues/1320#issuecomment-476509968

But also bring a new problem, the onChange doesn't fire in some plugins, so how to fix?
