### ISSUE TITLE
Emoji plugin on latest version is not loading all emojis

### ISSUE THREAD

**Issue by marcoburrometo** [draft-js-plugins/draft-js-plugins#3045]
## Environment

- @draft-js-plugins/editor version: 4.1.3
- @draft-js-plugins/emoji version: 4.6.3

## Description

Hello,
I upgraded to the latest version of emoji plugin to solve the slow startup and now it's superfast.

The problem that now I have is that in the suggestions list I don't see all the emojis.

![image](https://user-images.githubusercontent.com/10879009/207806891-e2ae61e5-3362-4f00-8c02-33dac059cbf7.png)

I'm using it like this:

```
const emojiPlugin = createEmojiPlugin({
      useNativeArt: true,
  });
```

If I add 
```
      emojiImage: (p) => {
           return <span>{p.unicode}</span>;
        },
```
and log `p` for some emojis I see it as undefined.

![image](https://user-images.githubusercontent.com/10879009/207807838-dc154129-292e-418a-ba6b-a87e3dfc697a.png)

**Comment by akshayhp2298** [comment]
Facing the same issue...

**Comment by marcoburrometo** [comment]
this is solved by https://github.com/draft-js-plugins/draft-js-plugins/pull/3054


would be great to have it merged :)

**Comment by marcoburrometo** [comment]
Can you reopen this? I'm fully solving this with https://github.com/draft-js-plugins/draft-js-plugins/pull/3056
