### ISSUE TITLE
Create collapse-able suggestion menu of all available emojis

### ISSUE THREAD

**Issue by ledzeppelin** [draft-js-plugins/draft-js-plugins#306]
Would it be possible to create a collapse-able suggestion menu of all available emojis at the top right corner of the textarea?  

Here's an example of how emoji picker does it: https://github.com/OneSignal/emoji-picker

![emoji picker](https://camo.githubusercontent.com/89c2a61b4a70cb9bec8e6e8ccdcb06bd7d83763a/687474703a2f2f6f6e657369676e616c2e6769746875622e696f2f656d6f6a692d7069636b65722f73637265656e73686f742e706e67)

Additionally, when hovering your cursor over an emoji in the selection menu, would it be possible to display the emoji code, **:emojicode:**?

Here's an a screenshot of how slack implements it
![slack emoji selection menu](http://i.imgur.com/DzQOndY.png)

This enhancement could help users discover the breadth of available emojis and the code invoke them.

**Comment by nikgraf** [comment]
Great suggestions & definitely possible!

Would you be interested to create a PR? I'm bit busy right now focusing on a 2.0 beta.

**Comment by ledzeppelin** [comment]
Ah - I probably can't volunteer to do it now :frowning:

**Comment by nikgraf** [comment]
no worries 😊

**Comment by ranaharoni** [comment]
Yep, it would be a nice thing. I would also suggest to offer some way to trigger it with the colon sign, as it is more agile when using a keyboard. It could also reuse the same suggestion feature implemented in the dropdown.

Can't wait to start using this:
`<EmojiSuggestions type="menu"/>`
😃

**Comment by nikgraf** [comment]
@ranaharoni just replied to you on the chat … interested to submit a PR?
