### ISSUE TITLE
[Mention] Suggestion popup not showing on trigger

### ISSUE THREAD

**Issue by vbatsan** [draft-js-plugins/draft-js-plugins#3075]
## Environment

- @draft-js-plugins/editor version: last
- plugin name and version: last
## Description
Trying to use the mentions plugin from [example](https://www.draft-js-plugins.com/plugin/mention). The popup does not calculate the position from the trigger and search. Only after removing (backspace) characters from the search, suggestions appear. Has anyone encountered a problem? [Codesandbox](https://codesandbox.io/s/tender-leaf-ze70ow?file=/src/App.tsx)

**Comment by vbatsan** [comment]
It's goes form @draft-js-plugins/editor 4.51

**Comment by fxOne** [comment]
This looks like the same issue as in #2966
