### ISSUE TITLE
Suggestions with the same name shows a warning and drops "duplicates"

### ISSUE THREAD

**Issue by Zhouzi** [draft-js-plugins/draft-js-plugins#308]
Hey there!

I am using the mention plugin with an api that returns users with different ids but sometimes the same name. So I may end up with: `{ id: 'john-doe', name: 'John Doe' }, { id: 'john-doe-1', name: 'John Doe' }` which leads to:

> Warning: flattenChildren(...): Encountered two children with the same key, `John Doe`. Child keys must be unique; when two children share a key, only the first child will be used.

It'd be great if we could provide a custom "keyGetter".

The current implementation is there: https://github.com/draft-js-plugins/draft-js-plugins/blob/master/draft-js-mention-plugin/src/MentionSuggestions/index.js#L275

**Comment by nikgraf** [comment]
hmmm, I'm pretty confident this is a mistake and should be something like `key={this.key}`

Interested to create a PR @Zhouzi?

**Comment by Zhouzi** [comment]
Sure, I'll submit one in the days to come.

**Comment by davidcalhoun** [comment]
For more context, see #318.  In summary, you need to explicitly add an "id" key to your mention object:

```js
const suggestions = [
  {
    id: 'foo@example.com',
    name: 'Foo Bar'
  },
  {
    id: 'foo2@example.com',
    name: 'Foo Bar'
  }
];
```
