### ISSUE TITLE
DOM takes too long to load when using @draft-js-plugins/emoji

### ISSUE THREAD

**Issue by kalemi19** [draft-js-plugins/draft-js-plugins#3090]
I recently replaced the deprecated draft-js-emoji-plugin with @draft-js-plugins/emoji 4.6.5, but for some reason, the page takes longer to load.

The setup is exactly the same, using native art, but the difference in loading time is significant (milliseconds vs seconds).

This is using @draft-js-plugins/emoji 4.6.5
<img width="1440" alt="Screen Shot 2023-01-30 at 21 02 19" src="https://user-images.githubusercontent.com/1066392/215583591-0389ee4e-ac50-4355-b062-923cc1527d4a.png">

This is using the old draft-js-emoji-plugin
<img width="1440" alt="Screen Shot 2023-01-30 at 21 02 09" src="https://user-images.githubusercontent.com/1066392/215583612-7be798bc-28e6-46c4-9095-e941fe0a2ab5.png">

If I had the time, I would have gladly investigated this further, but for now, I'm reverting back to the old plugin.

These are all the plugins being used:

```
const plugins = [
      this.linkifyPlugin,
      this.shortcodePlugin,
      this.mentionPlugin,
      this.hashtagPlugin,
      this.emojiPlugin,
    ];

```
Thank you

**Comment by fxOne** [comment]
This is an old know issue: https://github.com/draft-js-plugins/draft-js-plugins/issues/855
