### ISSUE TITLE
Draft js

### ISSUE THREAD

**Issue by andelkocvjetkovic** [draft-js-plugins/draft-js-plugins#3093]
## Describe the feature

Hello, is it possible to make with draft.js and plugins something like this. 

https://user-images.githubusercontent.com/56834937/217003383-1dace268-f9d1-48fe-bc9b-14a00366a96e.mov

**Comment by fxOne** [comment]
Sure you can do something like this with `draft-js` and some work. There are no plugins that cover the requirements.

**Comment by andelkocvjetkovic** [comment]
yes, I made it. I wish there is a better documentation. I used your source code for [mention](https://github.com/draft-js-plugins/draft-js-plugins/tree/master/packages/mention). 
It was really hard.
