### ISSUE TITLE
Emoji is not getting selected on pressing enter

### ISSUE THREAD

**Issue by bhaveshdaswani93** [draft-js-plugins/draft-js-plugins#3097]
## Environment

- @draft-js-plugins/editor version:
- draft-js-plugins-editor: 3.0.0
- draft-js-emoji-plugin: 2.1.3

## Description

Emoji is not getting selected on pressing enter, while same works when tab is pressed
Video Demo: https://drive.google.com/file/d/1-Hbn-obQoT2V-6MGThxxE-SNO9_rWnBN/view?usp=sharing

**Comment by bhaveshdaswani93** [comment]
It was related to my code and the enter is working as expected when I created standalone demo. So I am closing the issue

**Comment by fukouda** [comment]
what was your fix for this?
