### ISSUE TITLE
Trying to add new routes to docs, Flow error

### ISSUE THREAD

**Issue by thebritican** [draft-js-plugins/draft-js-plugins#310]
If I simply copy the "Home" page and make another route, to work on another example editor, I get this error on commit:
```
Running eslint on git staged files: **/*.@(js|jsx)
Running flow on git staged files: **/*.@(js|jsx)
flow: unexpected argument 'docs/client/components/pages/SomePage/ANewEditor/initialState.js'.
```

Any ideas what I should be doing differently? Can't find a configuration file for where I need to add a new path

**Comment by nikgraf** [comment]
Seems to be an issue with lint-staged. There was 1.0 release most recently. Let me upgrade the packages and see if that works.

**Comment by nikgraf** [comment]
@thebritican this should be resolved, let me know if it works for you
