### ISSUE TITLE
Plugin-supplied components cannot be placed above editor

### ISSUE THREAD

**Issue by jasonphillips** [draft-js-plugins/draft-js-plugins#311]
As currently written, the plugins-editor only initializes plugins (attaching them to get/setEditorState functions) when the Editor component is first rendered. This means that any components supplied by plugins (like the CharCounter, WordCounter, etc of the counter plugin) cannot be placed above the Editor in a rendering method, since their first render will then be uninitialized and will crash on looking for non-existent methods (`store.getEditorState is not a function`). 

To me, it seems limiting to require that all controls be placed below the Editor.

There are at least a couple of workarounds. For the counter plugin (to take one exampe), the components could simply check for initialization before attempting to access the bound methods:

So [this line:](https://github.com/draft-js-plugins/draft-js-plugins/blob/master/draft-js-counter-plugin/src/CharCounter/index.js#L28)

``` js
  const count = this.getCharCount(store.getEditorState());
```

could become 

``` js
    let count = 0;
    if (store.getEditorState) {
      count = this.getCharCount(store.getEditorState());
    }
```

This kind of fix allows the components to be placed above the Editor, but still leaves an unusual difficulty with the components not remaining fully synced to the Editor's state in all cases. Specifically, it seems that the controls (like the character count) can end up lagging behind by a single rendering cycle when something else updates the editor.

In [my plugin](https://jasonphillips.github.io/draft-js-richbuttons-plugin/), I needed to ensure that formatting buttons (particularly the inline ones like Bold) always correctly reflect an active / inactive state based on the current cursor position, and placing them above the editor with only the above fix left repeated issues with lagging behind a render. 

I ended up solving it by having all my plugin's components internally subscribed to re-render whenever a changed EditorState arrives, but this approach still requires the additional step, when using the plugin, of adding its callback into your onChange function. 

``` js
//  in your component using the richButtons plugin
 onChange(editorState) {
  this.setState({content: editorState}, () => {
    richButtonsPlugin.onEditorChange(editorState); // re-renders the buttons as needed
  });
}
```

It seems that the plugin-editor itself should perhaps have another way of connecting a plugin to subscribe directly to EditorState changes, making the relative position of Editor and buttons truly irrelevant and all changes easily propagable to any plugin-supplied components and controls. Thoughts?

**Comment by nikgraf** [comment]
This in indeed is a problem & I didn't anticipate it.

Possible solutions I can think of right now:

1. Some plugins don't actually need to plugins. For example the counters e.g. WordCounter could simply be Components receiving the editorState as a prop. /cc @adrianmc 

```js
import Editor from 'draft-js-plugins-editor';
import WordCounter from 'draft-js-counter/WordCounter';

<WordCounter editorState={this.state.editorState} />
<Editor editorState={this.state.editorState} />
```

Still some plugins like the Mention plugin also need other things than the editorState e.g. boundingRect https://github.com/draft-js-plugins/draft-js-plugins/blob/master/draft-js-mention-plugin/src/MentionSuggestionsPortal/index.js#L22 and passing all of that might becomes annoying.

2. The second solution is the one where a re-render is forced or update internal state like you did in your plugin. This makes plugin development inherently harder.

Does your plugin actually need to be a plugin or would it work well with the first approach?

I don't see a magic bullet solution right now 😞 Any other ideas? /cc @adrianmc @mjrussell @bkniffler

**Comment by adrianmc** [comment]
We really need a standardized way for components external to the Editor to communicate with the main Editor instance. From what I understand, there are two major issues here:

1. `store.getEditorState()` may not exist yet when it is called.
2. The component can lag behind a render cycle since the latest EditorState change happens downstream.

@jasonphillips I like the workaround that you've created, but to ask every plugin developer to write the same might be a bit much.

@nikgraf Is it possible to add that functionality into draft-js-plugins-editor? 

Ultimately, the current issue stems from an asynchronicity of states across components that may be at different parts of the render tree. If async is the issue, I wonder if we can leverage some RxJS-inspired solutions.

**Comment by oyeanuj** [comment]
+1 to atleast allow for the plugins to subscribe (on initialization) to state changes managed by the editor. That seems the cleanest without a developer needing to reinvent the wheel everytime.

**Comment by nikgraf** [comment]
You can subscribe to state changes already … that's the purpose of `onChange`. It's not ideal, because a plugin later in the cycle might change the editorState. So we could introduce something like `onChangeAfterAllPlugins` (ignore the name for now) that doesn't allow to update the editorState anymore. This would still face the same issues with re-rendering.

What we could do is provide tooling like a higher order component that would take care of the force-rendering.

```JS
// in the plugin
import Editor, { createStore, decorateWithStore } from 'draft-js-plugins-editor';
const store = createStore();
const DecoratedMentionSuggestions = decorateComponentWithProps(MentionSuggestions, mentionSearchProps);

// when exporting from the plugin
MentionSuggestions: decorateWithStore(DecoratedMentionSuggestions, store)
```

Another option would be a plugin store (mini redux) which plugins can leverage and it must be passed to all exported components.

```JS
// passing the store managed by the user
import Editor, { createPluginStore } from 'draft-js-plugins-editor';
import WordCounter from 'draft-js-counter/WordCounter';

setState({pluginStore: createPluginStore()});

<WordCounter
  editorState={this.state.editorState}
  pluginStore={this.state.pluginStore}
/>
<Editor
  editorState={this.state.editorState}
  onChange={this.onChange}
  pluginStore={this.state.pluginStore}
  onChange={this.onChangePluginState}
/>
```

**Comment by jasonphillips** [comment]
@nikgraf That discussion is very helpful.

I realized on further inspection that I wasn't fully leveraging onChange when I first tried that route, because I was still using `getEditorState` after the onChange fired, and that callback technically gets the last state, not the one most recently mutated as the plugins being invoked in sequence.  So I attempted to refactor slightly (not yet committed) and the onChange was sufficient to keep the buttons in sync without needing an explicit invocation in the user's onChange / state method, providing that I still subscribe the plugin's components internally and force re-render whenever onChange is called with a new state.

But as you noted, the onChange alone could still cause out-of-sync rendering of controls if a later plugin in the sequence makes another change to the state. That's why I was thinking of something very similar to what you said above: 

> So we could introduce something like onChangeAfterAllPlugins (ignore the name for now) that doesn't allow to update the editorState anymore. This would still face the same issues with re-rendering.

The idea of having an onChange that is called _after_ all the plugin changes to state, and used merely for updating any rendering (_onChangeComplete_ ?), makes a lot of sense to me. In fact, I feel like the ideal standard might be for plugins to do all state mutations in one loop (where the plugins-editor chains all the onChange functions and passes the new state into each successive one) and then, when all mutations are complete from all plugins, restrict any re-rendering purposes (of controls, etc) to a second loop that is inherently immutable. I like the idea of data flow being one process, and strictly separating any UI changes into a later step, perhaps even enforcing that separation.

> What we could do is provide tooling like a higher order component that would take care of the force-rendering.

This looks great, and would allow a way for plugin authors to create controls that are subscribed to changes without a lot of complication on the development end. I personally prefer this to your second option, since I aesthetically like the idea of controls being simple to invoke (`<WordCounter/><LineCounter/>` instead of having `editorState` repeated everywhere).

**Comment by bryanph** [comment]
Maybe an API such as the following would help:

```

import createEditor from 'draft-js-plugins-editor';

const createLinkPlugin = (config = {}) => (
  const theme = config.theme || styles;
  const initialState = config.state

    ({getEditorState, setEditorState, registerOnChange, registerDecorator}) => {

        registerOnChange((editorState) => {
            // some global onChange
        })

        registerDecorator(/* Some decorator */)

        return {
            (props) => (
                <LinkButton 
                    theme={theme}
                    initialState={initialState} 
                    getEditorState={getEditorState} 
                    registerOnChange={registerOnChange} 
                />,
            )
        }
    }
);

const editor = createEditor(globalConfig)
const { LinkButton } = editor.registerPlugin(createLinkPlugin(config))
editor.registerPlugins([rest1, rest2]) // plugins that don't expose any components or such

const Editor = editor.Component

// now render Editor

```

i.e. the plugin just returns a function which the draft-js-plugins-editor will call with the appropriate methods. Then this method can return components if there are any. In this way there is no need for a store-like object since the components themselves would be responsible for setting up bindings with the editor state and such.

The one annoying thing would be that the user needs to call registerPlugin, since it needs the result of the call. Also, there would be some internal plugin state in the editor which can be mutated from the outside.

**Comment by nikgraf** [comment]
Hmm, let me point out the whole store concept is more of a workaround and not something very crucial to the plugin system, but I can see how people want to as general tooling to build more complex plugins.

@bryanph I like your idea. This would indeed simplify things, but on the other hand it takes a couple steps back from the React concept where we pass in data as props. This is also how the default Draft.js is used. Maybe there is a solution that keeps the paradigm and simplifies the whole store mess …

**Comment by bryanph** [comment]
@nikgraf, I agree with you, we shouldn't try to work around React.

The main issue right now is that Editor is rendered at the same "level" as all the button components etc, right? So maybe we should make draft-js-editor-plugin a higher order component instead which just injects the desired props, like all the current methods like getEditorState(), setEditorState(), etc.

In this way, methods performed by the Editor HOC are always propagated to all components the same way because the state is in the parent.

Something like the following:
```

import createEditor from 'draft-js-plugins-editor';
import createLinkPlugin from 'draft-js-link-plugin';
import createBlockPlugin from 'draft-js-block-plugin';

const linkPlugin = createLinkPlugin({ ...options })
const blockPlugin = createBlockPlugin({ ...options })

const plugins = [ linkPlugin, blockPlugin ]
const withEditor = createEditor(plugins)

const { LinkButton } = linkPlugin
const { H1Button, H2Button, UlButton, OlButton } = blockPlugin

class Editor extends React.Component {

    render() {
        const { Editor, editorState, setEditorState, onChange } = this.props

        return (
            <div>
                <LinkButton editorState={editorState} setEditorState={setEditorState}/>
                <H1Button editorState={editorState} setEditorState={setEditorState}/>
                <H2Button editorState={editorState} setEditorState={setEditorState}/>
                <UlButton editorState={editorState} setEditorState={setEditorState}/>
                <OlButton editorState={editorState} setEditorState={setEditorState}/>
                <Editor
                    readOnly={false}
                    editorState={editorState}
                    onChange={onChange}
                />
            </div>
            
        )
    }
}

/*
 * here withEditor injects the initial editor state along with multiple helper methods
*/
export default withEditor(Editor)

```


In this way there is no "magic" with binding methods and stuff in createPlugin(), you would just pass whatever methods the component needs to it and everything is explicit.

**Comment by derfloscher** [comment]
I think the second API proposed by @bryanph is the way to go. Minimal API, React-ish and little mental overhead. If this is something agreeable, I would be willing to give it a shot.

This is a really awesome project by the way. Thank you @nikgraf for making me feel welcome :+1:

**Comment by bkniffler** [comment]
I'm not too sure about @bryanph suggestion, but I'm not convinced this would work well for most people and with plugins in mind. First of all, the state always needs to be passed from an outer component, so with your solution in a realistic scenario we will have 3 stages involved: the outer app-specific container binding editorState and onChange, the withEditor container and the app-specific editor component that implements withEditor and renders Editor.

Also, where does the plugin definition happen? It can't be happening from the innermost component, except if it happens in a static way as arguments for the decorator, which would disallow dynamically adding, removing or changing plugins. So I hope we agree that this should happen in the outer container just like state handling. 

Therefor I don't see any real advantage of your solution for a broad audience. Though if you still want to use it like you mentioned (which might work better in a few cases), why don't you just create an additional library that makes use of pluginEditor to create the decorator?

ps. I feel like button definition should mostly happen in the context of a toolbar, which defines the positioning and appearance of buttons it contains. Floating toolbar? Above editor? Fixed on top of viewport? And Buttons should always be defined as objects first which will allow us more flexibility. Exporting renderable button-components can easily happen through another library.

**Comment by jplorandi** [comment]
I have solved some of this on my [base plugin](https://github.com/jplorandi/draft-js-plugins-base-plugin) by using react-decorate. It sends the plugin as a prop to any bound components, without wrapping around in a closure. Maybe that helps?

**Comment by juliankrispel** [comment]
Imo - we should remove state management and leave it up to userland - too many opinions about state management...

**Comment by reynacortez2** [comment]
```
console.log(comment);
console.log(comment);
```

**Comment by Murtuza5246** [comment]
[**### cvh jjg @derfloscher what is this ?jhguj uhigh uiohuio ho iouh** ](setState({pluginStore: createPluginStore()});)
