### ISSUE TITLE
No documention for usage of popperjs with mentions plugin

### ISSUE THREAD

**Issue by 17bcs1837** [draft-js-plugins/draft-js-plugins#3110]
Can anybody provide any examples on how to integrate popperjs v2 or v1 with mentions plugin. thanks!
This link returns 404 error:
https://www.draft-js-plugins.com/popper.js.org/docs/v2/

**Comment by 17bcs1837** [comment]
Can anybody provide any examples on how to integrate popperjs v2 or v1 with mentions plugin. thanks!

**Comment by fxOne** [comment]
Where did you found the link? The correct Link is https://popper.js.org/docs/v2/

**Comment by 17bcs1837** [comment]
this link is mentioned here: https://www.draft-js-plugins.com/plugin/mention -> Configuration Parameters -> popperOptions
The link https://www.draft-js-plugins.com/popper.js.org/docs/v2/ is supposed to provide details on how to configure popperjs with draftjs mentions plugin. that documentation is missing

**Comment by fxOne** [comment]
I fixed the link in the documentation.

You should use it like this:
```js
 const mentionPlugin = createMentionPlugin({
      popperOptions: {
        placement: 'right',
      }
    });
```

If you want to add an example feel free to send a PR with on.
