### ISSUE TITLE
how to set mentionRegExp value to only show suggestions popup after a letter has been typed after the trigger

### ISSUE THREAD

**Issue by 17bcs1837** [draft-js-plugins/draft-js-plugins#3111]
I want the suggestion box to only show up when a character or number has been entered after the trigger. I don't want the suggestion box to open as soon as the trigger is entered.

Triggers: ['@', '#']

I am not able to come up with the value for mentionRegExp for the above task. Can someone help me out?

**Comment by fxOne** [comment]
Have you tried something like this?

```ts
 const onSearchChange = useCallback(({ value }: { value: string }) => {
    if(value.length > 0) {
      setSuggestions(defaultSuggestionsFilter(value, mentions));
    } else {
      setSuggestions([]);
    } 
  }, []);
```
