### ISSUE TITLE
Implementation of onRemoveMention ? And deletion of multi word mentions in single go

### ISSUE THREAD

**Issue by 17bcs1837** [draft-js-plugins/draft-js-plugins#3116]
Hi, Just like we have onAddMention callback whenever a mention is added,  I want to know how we can execute a function whenever a mention is removed from the editor.

Also, for multiword mentions, say, two words, I want to delete it in single go, how do I achieve it. Currently, only one word is being delete per backspace by default.

**Comment by 17bcs1837** [comment]
Hi @fxOne, any suggestions on this? Thanks

**Comment by fxOne** [comment]
As far as I know there is no event in `draftjs` if an entity is removed. Maybe you can simply compare the entities before and after saving?

For your multi word use case you can set `entityMutability: 'IMMUTABLE'`.
