### ISSUE TITLE
[Mentioning] typing a char before trigger, triggers popover

### ISSUE THREAD

**Issue by datsteves** [draft-js-plugins/draft-js-plugins#3125]
## Environment

- @draft-js-plugins/editor `4.1.3`
- @draft-js-plugins/mention `5.2.1`
- react / react-dom `18.2.0`

## Description

When Typing `@` then pressing the left arrow key and type a letter (that should at least match one mention) then the popover will still trigger being active. if you first type a letter and then the `@` then its fine.

So I guess as soon as a trigger matches, it is in this state of "I'm using the mentioning now", but does not go out of that state when moving the select before the trigger. Or something along those lines.

![image](https://user-images.githubusercontent.com/31381383/225395812-6ddc8fa6-e8e7-4611-81c5-076e43aa6bff.png)

## Reproducible Demo

https://codesandbox.io/s/cranky-breeze-4b92z9

or use the storyboard page that is named `Editor with custom themed Mention Plugin`

**Comment by fxOne** [comment]
There are some issues with react 18. You should try it with react 16.

**Comment by TheSizkarn** [comment]
> There are some issues with react 18. You should try it with react 16.

Yes but if we are on version 13 of Next.js and that requires version 18 of React?

**Comment by fxOne** [comment]
Feel free to create a PR to fix the issue, I'd be happy to merge it. But if the issue is in draft-js, and there are many, they will never be fixed as Facebook has discontinued the project.

I would recommend moving to another project like [slate](https://www.slatejs.org/) or [lexical](https://lexical.dev/).
