### ISSUE TITLE
Bug Report: onChange event not triggered on mobile devices

### ISSUE THREAD

**Issue by ambaliyadhruv1112** [draft-js-plugins/draft-js-plugins#3151]
Issue Summary
I am using the draft-js-plugins/editor library in my React project and have noticed that the onChange event is not triggered when editing the content on a mobile device.

Steps to Reproduce
Open the project on a mobile device (e.g. iPhone or Android device).
Edit the content inside the editor component.
The onChange event is not triggered, and the editor content does not update.
Expected Results
The onChange event should be triggered whenever the content of the editor is updated, regardless of the device being used.

Actual Results
The onChange event is not triggered on mobile devices, making it difficult to detect changes to the editor content.

Workaround
As a workaround, I have tried using the onKeyDown event to detect changes to the editor content. While this works to some extent, it is not as reliable as the onChange event.

Environment
Operating System: [e.g. iOS 14.5, Android 11]
Browser: [e.g. Safari, Chrome]
Library version: [e.g. draft-js-plugins/editor v4.0.0]
Additional Information
I have tested this issue on multiple mobile devices and browsers, and the issue persists across all of them. Please let me know if you need any additional information to help diagnose this issue.

**Comment by fxOne** [comment]
[draft-js](https://draftjs.org/docs/advanced-topics-issues-and-pitfalls#mobile-not-yet-supported) does not support mobile devices
