### ISSUE TITLE
Mention plugin to allow white spaces

### ISSUE THREAD

**Issue by Zhouzi** [draft-js-plugins/draft-js-plugins#316]
I am dealing with an API that returns a lots of results so mentioning someone from their first name can be tricky. I'd like to be able to type `John Do` so `John Doe` pops out but right now the popover disappear after a white space is inserted.

I'm unsure how tricky that would be to implement, I've been looking at https://github.com/draft-js-plugins/draft-js-plugins/blob/9f94e5c94d4b08605d9ab227218f141d8bee2cf3/draft-js-mention-plugin/src/MentionSuggestions/index.js#L102 and will probably dig deeper but feel free to let me know if you have already worked on it.

**Comment by nikgraf** [comment]
I think this would require a couple of changes. Right now the MentionSuggestions popover is triggered initially after this decorator matches: https://github.com/draft-js-plugins/draft-js-plugins/blob/9f94e5c94d4b08605d9ab227218f141d8bee2cf3/draft-js-mention-plugin/src/mentionSuggestionsStrategy.js#L5

If you would include white space in general into the regex I believe it will be quite hard to manage. You could update the regex to allow one space, but then also word search in the MentionSuggestions has probably other code parts have to change to work with one space.

**Comment by batmandarkside** [comment]
var MENTION_REGEX = /(\s|^)@[\w|\s|\W]*/g;

**Comment by Zhouzi** [comment]
@batmandarkside thanks for sharing, sadly this regexp won't make it partly because of the `\W`. I am currently working on this feature through #319 and the current expression approximatively looks like: `(\s|^)@((\w+\s?){0,})?`. It's configurable though so the real code is a little more complex.

**Comment by juliankrispel** [comment]
I'm closing this issue, if you think this issue is still relevant please let us know why and we'll consider reopening it. Thank you for contributing ✌️

**Comment by kurenov** [comment]
@juliankrispel what's the status of support of white spaces? Are you guys planning to include it soon? Or should we fork this repo and do it our self?

**Comment by fahd** [comment]
I read a couple of other issues about this and it looks like this feature was omitted because the maintainers have too much to deal with at the moment. I read about another pull request that was denied from 2 years ago, so I copied that person's code and created a fork [here](https://github.com/fahd/draft-js-plugins) if anyone wants to see a working example, just go into docs, npm start, and use **Custom Mentions** to test. i agree it's a very important feature!

**Comment by juliankrispel** [comment]
I think we should absolutely support it. I have some opinions about the
implementation however. If anyone fancies working on a pr for this - please
get in touch I’ll gladly help getting it ready to merge 🙏

**Comment by fahd** [comment]
I would include #402 as well - which includes @nishp1 and the code he wrote, which works for me

**Comment by juliankrispel** [comment]
@fahd if you like we can start from there and I can start reviewing that to
give some guidance. How does that sound?

**Comment by fahd** [comment]
sure! when i get a chance i can include that code on top of the latest version
