### ISSUE TITLE
[Mention] Suggestion position on top of text ( or with different parent )

### ISSUE THREAD

**Issue by jarindr** [draft-js-plugins/draft-js-plugins#317]
Is there anyway we could move the position of the suggestion box to top of the text? I think many people will have issue on textEditor that is at the bottom of the page.
or even with customizable position on different parent?

**Comment by nikgraf** [comment]
@jarindr not yet, I think someone suggested she/he wants to submit a PR, I can't remember right now who it was.

**Comment by jarindr** [comment]
@nikgraf the reason I close this PR is because we can hack it with positioning.

**Comment by nikgraf** [comment]
@jarindr sounds good 🙌
