### ISSUE TITLE
plugin.css not found

### ISSUE THREAD

**Issue by ArtemLapys** [draft-js-plugins/draft-js-plugins#3188]
## Environment

- prismjs
- draft-js-prism-plugin
- @draft-js-plugins/inline-toolbar
- @draft-js-plugins/buttons
- draft-js-code

## Description

После установки библиотек:
@draft-js-plugins/buttons
@draft-js-plugins/drag-n-drop-upload

через nmp install <название библиотек >, отсутствует у представленных библиотек plugin.css. Я не делаю никаких лишних шагов.

 К стандартным библиотекам REACT я использую еще:
npm install react-scripts
npm install react-router-domain
npm i react-draft-wysiwyg
npm install draft-js-prism-plugin
npm install draft-js-inline-toolbar-plugin
npm i style-loader css-loader 

При этом стоит отметить, что   при установки draft-js-inline-toolbar-plugin была аналогичная проблема, но при переустановки plugin.css появился. Какими способами еще можно получить plugin.css к указанным выше(первый список) библиотекам? 

p.s. аналогичная проблема имеется и у  "draft-js-code"
## Reproducible Demo

](https://imgur.com/a/yd1BlvD)

**Comment by fxOne** [comment]
Please write you issues in english!
