### ISSUE TITLE
plugin.css not found

### ISSUE THREAD

**Issue by ArtemLapys** [draft-js-plugins/draft-js-plugins#3191]
## Environment

- PrismJS
- draft-js-prism-plugin
- @draft-js-plugins/inline-toolbar
- @draft-js-plugins/buttons
- draft-js-code

## Description

After installing the libraries:
@draft-js-plugins/buttons
@draft-js-plugins/drag-n-drop-upload

via nmp install <library name>, the plugin.css libraries provided are missing. I'm not taking any extra steps.

To the standard REACT libraries I use more:
npm install react-scripts
npm install react-router-domain
npm i react-draft-wysiwyg
npm install grunt-js-prism-plugin npm install grunt-js-inline-toolbar-plugin

npm i style-loader css-loader

It is worth noting that when installing draft-js-inline-toolbar-plugin, there was a similar problem, but when reinstalling plugin.css appeared. What other ways can I get plugin.css to the libraries listed above (the first list)?

P.S. "draft-js-code" has a similar problem

## Reproducible Demo

[Error plugin.css(imgur.com)](https://i.imgur.com/TELGFrN.png)

**Comment by fxOne** [comment]
`@draft-js-plugins/buttons` does not have any css. It is a utility library for other `@draft-js-plugins` libraries. 
Why are you trying to include this file?

**Comment by ArtemLapys** [comment]
In one of the instructions on the Internet. But today I came across your official documentation, where it says that you need to use another file. **Sorry for misleading you**

**Comment by fxOne** [comment]
So everything is fine and we can close this issue?

**Comment by ArtemLapys** [comment]
Yes, of course, thank you and I'm sorry that I stepped like that
