### ISSUE TITLE
Mention's popover shows up when typing before a @

### ISSUE THREAD

**Issue by Zhouzi** [draft-js-plugins/draft-js-plugins#323]
**Steps to reproduce**

1. Go to the [simple example](https://www.draft-js-plugins.com/plugin/mention)
2. Type `@ma`
3. Then move the cursor before the `@` and insert two line breaks
4. Start typing `ma` and the suggestions will appear

![screenshot](http://i.imgur.com/2HTiPW1.png)

*The cursor is on the first line, right after `ma`.*

This is due to the regular expression matching `\s`.

**Comment by nikgraf** [comment]
ouch definitely a bug, any suggestion how to fix it?

**Comment by Zhouzi** [comment]
It could be to replace `\s` by a white space but I have yet to make the proper tests.

**Comment by nishp1** [comment]
@Zhouzi @nikgraf PR is up at https://github.com/draft-js-plugins/draft-js-plugins/pull/340. 

`onEditorStateChange` was iterating over all of the searches in the editor and comparing their start and end dates. I updated it only look at searches on current line using anchor key.

**Comment by nikgraf** [comment]
nice one @nishp1 👌

**Comment by dex1t** [comment]
@nikgraf When are you going to publish this? I expect to fix this issue (https://github.com/draft-js-plugins/draft-js-plugins/issues/289).

**Comment by nikgraf** [comment]
Sometime later today 😃 Currently going through all the issues & PRs to see what should be in the next release. Sorry for the delay.

**Comment by dex1t** [comment]
thanks ✨

**Comment by nikgraf** [comment]
@dex1t sorry, didn't get to it yesterday. hopefully today :)

**Comment by dex1t** [comment]
@nikgraf never mind! thanks 😄
