### ISSUE TITLE
Emoji plugin keyboard navigability issues

### ISSUE THREAD

**Issue by LBPeterson** [draft-js-plugins/draft-js-plugins#3233]
## Environment
- OS: MacOS 12.6
- Browser: Chrome 107
- @draft-js-plugins/emoji version: `^4.6.5`
- draft-js version: `^0.11.7`

## Description
When using the emoji plugin, keyboard navigation is not supported. This manifests itself in several ways:
- The EmojiSelect menu cannot be opened via keyboard when the EmojiSelect button has focus
- When the EmojiSelect menu is open, there is no visual indication of which emoji has focus when navigating via the tab key
- When the EmojiSelect menu is open and an emoji has focus, that emoji cannot be selected with the keyboard `Enter` or `space (' ')` keys

## Reproducible Demo
https://www.draft-js-plugins.com/plugin/emoji

**Comment by LBPeterson** [comment]
I have created a PR to address this problem at https://github.com/draft-js-plugins/draft-js-plugins/pull/3234

**Comment by fxOne** [comment]
Closed by #3234
