### ISSUE TITLE
Emojis missing or style unexpectedly changed

### ISSUE THREAD

**Issue by markostojanovic087** [draft-js-plugins/draft-js-plugins#3244]
## Environment

Chrome - Version 114.0.5735.199
Chromium - Version 107.0.5304.88 (Official Build, ungoogled-chromium) (64-bit)

- @draft-js-plugins/editor version: 4.1.3 in my app AND the version from [official page](https://www.draft-js-plugins.com/plugin/emoji)
- plugin name and version: @draft-js-plugins/emoji 4.6.5 in my app AND the version from [official page](https://www.draft-js-plugins.com/plugin/emoji)

## Description

Emojis are missing or style unexpectedly and randomly changes.

## Reproducible Demo

Reproduced also on the [official page](https://www.draft-js-plugins.com/plugin/emoji):
![image](https://github.com/draft-js-plugins/draft-js-plugins/assets/19815352/b38f07b4-1d10-4769-9204-9ca06f0f3858)
![image](https://github.com/draft-js-plugins/draft-js-plugins/assets/19815352/ed2d8f97-bf32-4d7f-abdc-388ddcd80086)

It happens randomly, I could not obtain a clear repro. It is more likely to occur after first time opening the emoji popup or after page refresh.

**Comment by fxOne** [comment]
It is because the used font does not support all unicode characters. The plugin uses all emojis supported by joypixel.

**Comment by markostojanovic087** [comment]
@fxOne How would you explain the fact that it happens randomly? Most of the time is good.

**Comment by fxOne** [comment]
I can't see any coincidences there. The same ones are always missing after reloading the page or opening the pop-up several times.

**Comment by fxOne** [comment]
As far as I can see it is always the same

**Comment by markostojanovic087** [comment]
Yes, you are right, it always the same for native variant. In that case, I guess the issue can be closed.
