### ISSUE TITLE
Using Hashtag and Mention plugin causes browser hang

### ISSUE THREAD

**Issue by nmt1994** [draft-js-plugins/draft-js-plugins#325]
Hello, 

So I was trying to add an Editor with by using both plugins Mention and Hashtag:

```javascript
const mentionPlugin = createMentionPlugin({
    mentionPrefix: '@',
    entityMutability: 'IMMUTABLE'
});
const hashtagPlugin = createHashtagPlugin();
const { MentionSuggestions } = mentionPlugin;
const plugins = [hashtagPlugin,mentionPlugin];
```

```javascript
<Editor
     editorState={ this.state.editorState }
     onChange={this.onChange}
     plugins={plugins}
      ref="editor"
/>
 <MentionSuggestions
       onSearchChange={ this.onSearchChange }
         suggestions={ this.state.suggestions }
/>
```

- Normal behavior if you don't write hashtag at the beginning of line :

![Normal](https://media.giphy.com/media/l46C6n2wWLa5RODpS/giphy.gif)

- Browser will hang if you try to write hashtag at the beginning of line/text

![Error](https://media.giphy.com/media/26BRx2aMtUMvsHcSQ/giphy.gif)

I also has same issues with #168  as well.

**Comment by nikgraf** [comment]
@nmt1994 thx for reporting. I just tried, but unfortunately I can't reproduce the issue. Do you have time to create repo that I can simply checkout run `npm install` and `npm start`? Or do you have a deployed example?

**Comment by nikgraf** [comment]
@nmt1994 regarding #168: this should be fix, ideally you can highlight the same issue in a repo. Sorry right now I got a lot to do and it takes ages to investigate if I can't reproduce the issue. 😃

**Comment by nmt1994** [comment]
@nikgraf : Working on it :smile:

**Comment by nmt1994** [comment]
@nikgraf : Hello , seems that I found the error which is mainly my fault from modifying the regular expression.
Further explanation :
- I was trying to change how mention can be detected
 ```javascript
var MENTION_REGEX = /(\s|^)[\w]*/g;
```
To
```javascript
var MENTION_REGEX = ([A-Za-zÀ-ÿ0-9_ '.+-]*)$|(?:^|\s)([^\x00-\xff]*)$;
```
Seems that my new regex caused an infinite loop :smiling_imp: .
Sorry for mis-information

**Comment by nikgraf** [comment]
no worries @nmt1994 - glad you found the issue 👍
