### ISSUE TITLE
Allow external custom CSS to style Mentions menu and suggestion entries NOT via webpack and loader modules

### ISSUE THREAD

**Issue by tedlin182** [draft-js-plugins/draft-js-plugins#328]
It seems like the only way to custom style the mentions suggestion list is to follow the steps and import the CSS into the component itself. It would be great if there were just general classes we could just target and style in our external CSS vs. having to load them up via webpack and import them into the module.

Some flexibility around this would be great as that would the easiest way to customize the styling of this.

Thanks!

**Comment by nikgraf** [comment]
@tedlin182 Each plugin takes a list of CSS classes in a `theme` property as described in the documentation. It's an interesting idea. We could even achive this with CSS modules.

On the other hand I strongly believe global CSS classes cause more trouble help in larger application & I wanted to discourage people from doing so right away from the beginning.

Does that make sense?
