### ISSUE TITLE
Editor - Placeholder bug

### ISSUE THREAD

**Issue by SomeBrujah** [draft-js-plugins/draft-js-plugins#3313]
When the editor has a long placeholder, the placeholder extends beyond the editor.
<img width="566" alt="screenshot-1" src="https://github.com/draft-js-plugins/draft-js-plugins/assets/47982319/2fb53f76-8eef-46d5-99e9-ee03e6ca55b1">
I fix thix with styles
```
.public-DraftEditorPlaceholder-inner {
  white-space: nowrap !important;
  text-overflow: ellipsis;
  overflow: hidden;
}
```
![image](https://github.com/draft-js-plugins/draft-js-plugins/assets/47982319/14258315-43b4-49ed-b17d-86d2bc283cc6)

**Comment by fxOne** [comment]
This is part of `draft-js` and not `draft-js-plugins`.
