### ISSUE TITLE
toolbarPlugin onChange() 2nd arg

### ISSUE THREAD

**Issue by bryanph** [draft-js-plugins/draft-js-plugins#332]
When I use the toolbar plugin following the draft-wysiwyg example, the 2nd argument which is used in many plugins in the onChange() is undefined.

Hence, i get
    
    Cannot read property 'setEditorState' of undefined(…)

Is there anywhere I can read up on how this works? Or some material on the plugin architecture.

**Comment by nikgraf** [comment]
@bryanph thx for reporting, so far there is no docs as this is right in the making. Can you post your code in an example that I can run with `npm install` & `npm start`. That's the best way for me to help out …

**Comment by bryanph** [comment]
I didn't notice the wysiwyg example uses a separate repo for the draft-js-plugins code: https://www.npmjs.com/package/draft-js-plugins-editor-wysiwyg

Using that it works.. would prefer to use the draft-js-plugins npm release though.

**Comment by nikgraf** [comment]
@bryanph this was a pre-release @bkniffler used for development, sorry we should have better synced to avoid confusion …

**Comment by poltak** [comment]
@nikgraf What is the recommended way of running the toolbar plugin with custom action buttons now? 

At the moment, the plugin's `onChange` still expects the second arg (as seen [here](https://github.com/draft-js-plugins/draft-js-plugins/blob/master/draft-js-toolbar-plugin/src/index.js#L13)), passing it down to the `getToolbarActions` function which handles creating all the toolbar actions. 

Hence creating custom action buttons (via the `textActions` key in the config object passed to the default import create plugin function from `draft-js-toolbar-plugin` - same way as in the `draft-wysiwyg` example) throws a TypeError null ref thingy.

Doesn't seem to change anything by trying the `2.0.0-beta{1..5}` versions of both `draft-js-plugins-editor` and `draft-js-toolbar-plugin`.

Any pointers getting this running would be appreciated, as there doesn't seem to be any docs at the moment and I can't find any other examples apart from the `draft-wysiwyg` stuff.

**Comment by poltak** [comment]
@bryanph Even using the `Editor` from `draft-js-plugins-editor-wysiwyg` still throws the null ref here. Where did you end up getting with this?

**Comment by poltak** [comment]
No, after reading more into the code of how the plugins are loaded, it's both doc'd [here](https://github.com/draft-js-plugins/draft-js-plugins/blob/master/HOW_TO_CREATE_A_PLUGIN.md#supported-objects--webhooks) and coded [here](https://github.com/draft-js-plugins/draft-js-plugins/blob/master/draft-js-plugins-editor/src/Editor/index.js#L78) that the `setEditorState` function is passed via an object to the plugin's `onChange`. 

So I was wrong there; the error I'm getting is not related to this issue.

**Comment by nikgraf** [comment]
👍
