### ISSUE TITLE
Pressing enter at the bottom of scrolled editor does not move you down

### ISSUE THREAD

**Issue by Sebastian-Nielsen** [draft-js-plugins/draft-js-plugins#3329]
Go to the demo page: https://jpuri.github.io/react-draft-wysiwyg/#/demo 

Type as I do in this video: https://i.gyazo.com/fbe80ceafe4bb8317175f99246d4f3a8.mp4 

As you can see, when you are about to overflow after you press the enter key, the enter key is registered, but you aren't being pulled down to view the down-most content (which is empty space in this case). 

After you then type some characters, it pulls you down to your characters, which depending on how many linebreaks you entered, can be very disorienting. 

For reference, if you add `max-height: 200px` and `overflow: auto` to the editor on the bottom of this page, it won't behave like that. That is how I expect yours to behave as well. website: https://draftjs.org/

**Comment by fxOne** [comment]
This is `draft-js-plugins` and not `react-draft-wysiwyg`.
