### ISSUE TITLE
May not be an issue, but is there a way to render the mentions as links in readOnly mode?

### ISSUE THREAD

**Issue by tedlin182** [draft-js-plugins/draft-js-plugins#334]
I thought maybe I'm missing something, but I'm creating the new mentions just fine and saving it to the DB just fine.

But when I try and render the content, the mentions just show up as straight text. Am I missing a step?

**Comment by tedlin182** [comment]
@nikgraf - Is this related to https://github.com/draft-js-plugins/draft-js-plugins/issues/232 actually?

**Comment by nikgraf** [comment]
@tedlin182 actually this should be already the case … you need to make sure the mention contains a key `link` e.g. https://github.com/draft-js-plugins/draft-js-plugins/blob/master/docs/client/components/pages/Mention/SimpleMentionEditor/mentions.js#L6

**Comment by tedlin182** [comment]
Hey @nikgraf - Yeah I do have a `link` key with the URL and the structure is just like you have it in the example you posted, and once I select a suggestion from the autocomplete list, it renders in the editor as a link fine in **edit mode**.

But once I save the comment into the DB and then render that comment, it just shows up as text. We are using the `Editor` in readOnly mode to display our comments. 

Is there maybe I'm missing?

**Comment by nikgraf** [comment]
no worries, happy to help 😃
