### ISSUE TITLE
Linkify plugin - Link is disabled inside editor

### ISSUE THREAD

**Issue by changeweb** [draft-js-plugins/draft-js-plugins#335]
I guess Link is disabled (not working when clicked) inside editor by default in Draft.js. But how to make it clickable using linkify plugin? I think we can add something like this in the anchor tag:

     `<a onClick={onClick} href={link}>`

where `onClick` event will redirect to the url location. I've edited the index.js file in Link folder with something like this:

    var openWindow = function(){
        window.open(href, target);
      };
      return _react2.default.createElement('a', _extends({}, props, {
        href: href,
        className: combinedClassName,
        target: target,
        onClick: openWindow
      }));

One more thing, Should I use the saved raw content to display in editor as rich text content?

**Comment by nikgraf** [comment]
The idea is that in edit mode you don't follow links. In read mode the links work. Twitter, Slack & Facebook have the same behaviour. Does that make sense?

Still I'm curious about your use-case. Why would you want that?

**Comment by changeweb** [comment]
Oh, it's my fault. I mistakenly used `readonly` instead of `readOnly`. That's why the editor was in edit mode and I thought link was not working. But Hashtag is not clickable in either edit or read only mode. How to fix that?

I'm facing another issue of `ToolbarPlugin` beta. It throws `Uncaught TypeError: Cannot read property 'setEditorState' of undefined` which is generated from

    // Re-Render the text-toolbar onChange (on selection change)
     onChange: function onChange(editorState, _ref) {
      var setEditorState = _ref.setEditorState; // <--- from this line

My editor code is something like this. Code only for toolbar plugin:

    import createToolbarPlugin from 'draft-js-toolbar-plugin';
    const toolbarPlugin = createToolbarPlugin();

    const plugins = [
       hashtagPlugin,
       linkifyPlugin,
       //emojiPlugin,
       toolbarPlugin,
     ];

     export default class MyEditor extends Component {
       constructor(props) {
         super(props);
         this.state = {
             editorState: EditorState.createEmpty(),
         };

        this.onChange = (editorState) => {
            this.setState({
              editorState
            });
        };
      }

**Comment by nikgraf** [comment]
Webpack or Browserify shouldn't make a difference. It might be this actually isn't an issue of the Toolbar. It's still beta 😄 

Regarding the Hashtag plugin: you need to fork it and build that into that Plugin. It simply doesn't have the feature yet. Happy to accept a PR. If you plan to do this let me know we can come up with plan how this can be implemented.

**Comment by changeweb** [comment]
I'm interested to add this feature. With my little knowledge I guess, this can be done by doing something like this:

    const {
       decoratedText = '', <-- add this
       theme = {},
       target = '_self', <-- add this
       className,
       ...props,
      } = this.props;

     const href = "/hashtag/" + decoratedText; <-- this url style & decoratedText should be filtered to get desired url format.

     return (
       <a {...props} href={href} target={target}>
         <span {...props} className={combinedClassName} />
       </a>
     );

This is almost similar to linkify plugin I guess.

**Comment by changeweb** [comment]
@nikgraf the emoji plugin is not working in my case. It gives me `Uncaught TypeError: Cannot read property 'size' of undefined` error. The error is producing from here:

    if (state.isActive) {
	    if (props.suggestions.size > 0) { <-- error here
	      transform = 'scale(1)';

My code looks like something like this:

    import React, { Component } from 'react';
    import Editor from 'draft-js-plugins-editor';
    import createEmojiPlugin from 'draft-js-emoji-plugin';

    const emojiPlugin = createEmojiPlugin();
    const { EmojiSuggestions } = emojiPlugin;

    const plugins = [
      hashtagPlugin,
      linkifyPlugin,
      emojiPlugin,
      //toolbarPlugin,
     ];
    ......

    render() {
      return (
        <div>
          <Editor
            editorState={this.state.editorState}
            onChange={this.onChange}
            plugins={plugins}
            ref="editor"
          />
          <EmojiSuggestions />
        </div>
       );
      }

**Comment by changeweb** [comment]
@nikgraf I've created a repo. [draft-js-emoji-plugin-issue repo](https://github.com/changeweb/draft-js-emoji-plugin-issue). See these images before checking out the repo.
![screenshot from 2016-07-07 11 03 08](https://cloud.githubusercontent.com/assets/9896315/16644808/713b3b46-4441-11e6-8b5e-9788d07d6b22.png)
![screenshot from 2016-07-07 11 03 32](https://cloud.githubusercontent.com/assets/9896315/16644902/fdff8b04-4441-11e6-9196-f3603a28e44a.png)

**Comment by nikgraf** [comment]
@changeweb this should be fixed with the 1.2.3 version of the plugin. I cut a new release earlier this week …

**Comment by changeweb** [comment]
Yes, 1.2.3 version of the plugin fixed the issue.

**Comment by nikgraf** [comment]
I think all issues here are resolved, correct? Feel free to open another issue at anytime 👍

**Comment by 6174** [comment]
@nikgraf   the latest version of  draft-js-emoji-plugin  (2.0.0-beta1) has the same issue  ` Uncaught TypeError: Cannot read property 'size' of undefined`

**Comment by nikgraf** [comment]
@6174 beta1 is outdate. we are already at beta.4, but npm thinks beta1 is later. Will fix that by publishing a beta5 tomorrow morning. sorry for the trouble

**Comment by oliverw** [comment]
@nikgraf I have a similar problem as the original poster. You wrote:

> The idea is that in edit mode you don't follow links. In read mode the links work. Twitter, Slack & Facebook have the same behaviour. Does that make sense?
> 
> Still I'm curious about your use-case. Why would you want that?

My use-case is that the editor is always in edit mode (think Evernote for example). I would like to enable the user to Ctrl+Click a link to open it. Could you recommend a strategy to implement this?

**Comment by avk** [comment]
@nikgraf I have the same use case as @oliverw — the editor is always in edit mode. Why shouldn't links be clickable in that case, like Gmail?

Also would love to see how to implement this.

**Comment by bjhytrek** [comment]
@laszlokiraly  Could you give a little more context to your code snippet? I also have the use case where the editor is always in **edit** mode but links need to be clickable.

I'm currently bringing the plugin in on the same level as my Editor component like so.
`
import createLinkifyPlugin from 'draft-js-linkify-plugin';
import React from "react";

const linkifyPlugin = createLinkifyPlugin();

export default class Texteditor extends React.Component {
...
}
`
I'm a bit confused as to how you're using it.

**Comment by bjhytrek** [comment]
@laszlokiraly  I figured out my issue. I was running version 2.0.0-beta1, 2.0.0-beta10 is required to use a custom handler like you mention is this thread:
https://github.com/draft-js-plugins/draft-js-plugins/issues/398

Thanks!
