### ISSUE TITLE
Invariant Violation Error when using draft-js-plugins-editor

### ISSUE THREAD

**Issue by tbohlen** [draft-js-plugins/draft-js-plugins#342]
I've been trying to switch out the normal draft-js editor with the draft-js-plugins-editor, but am running into an "Uncaught Invariant Violation: Stateless function components cannot have refs." when I do so.

Here's my code. The same code, without plugins and with the draft-js Editor, does not throw any errors. Any idea what might be causing this?

```javascript
import React, {PropTypes, Component} from 'react'
import { EditorState } from 'draft-js'
import Editor from 'draft-js-plugins-editor'
import createLinkifyPlugin from 'draft-js-linkify-plugin'

const linkify = createLinkifyPlugin()
const plugins = [ linkify ]

class MyEditor extends Component {
    constructor(props) {
        super(props)
        this.handleChange = this.handleChange.bind(this)
    }
    
    render() {
        return (
            <div>
                <Editor onChange={ this.handleChange }
                    editorState={this.props.editorState}
                    plugins={ plugins }
                    readOnly={ this.props.readOnly }
                    ref='editor' />
            </div>
        )
    }
    
    handleChange(newState) {
        // fake an event to let this use the same state structure as the rest of
        // the form
        let ev = {
            target: {
                name: this.props.editorId || '',
                value: newState
            }
        }
        this.props.handleChange(ev)
    }
}

MyEditor.propTypes = {
    editorState: PropTypes.object.isRequired,
    handleChange: PropTypes.func.isRequired,
    editorId: PropTypes.string,
    readOnly: PropTypes.bool
}

export default MyEditor
```

**Comment by Zhouzi** [comment]
Hmm seems correct to me but I may be missing something. That been said, my guess is that the error `Uncaught Invariant Violation: Stateless function components cannot have refs.` comes from something else that should look like:

```javascript
import React from 'react';

export default function SomeComponent () {
  return (
    <div ref="someRef"></div>
  );
};
```

Are there any other errors in the console? Would it be possible to add a reproduction scenario on jsfiddle (or somewhere else)?

**Comment by nikgraf** [comment]
hmmm, yeah this should work fine … which React version are you using? Create a small repo with the code to test would help a great deal so we can easily debug.

**Comment by tbohlen** [comment]
React is version 15.0.1

No other errors in the console. I'll set up a smaller test repo and see if I can reproduce this.

**Comment by nikgraf** [comment]
great, thx @tbohlen

**Comment by tbohlen** [comment]
OK, I've created a smaller project and have no issues there - everything works perfectly.

Still trying to narrow down what is going on in my main project, but here's one hint that might mean more to you all than to me. If I provide no plugins (leave the prop out, or give an empty list) I get a different error - "TypeError: cannot read property 'textContent' of null" in draftEditorLeaf.react.js. It appears it is looking for the ref "this.refs.leaf" and failing to find it. Logging out this.refs, the object is empty.

Note that if I have the editor in readOnly mode I have no issue.

Will keep digging, but if you have any thoughts I would appreciate it!

**Comment by tbohlen** [comment]
OK, this appears to be a react bug fixed here: https://github.com/facebook/react/pull/6650

Sorry to pollute your issues with this! Thanks for the help.

**Comment by nikgraf** [comment]
no worries, glad you found a fix 👍
