### ISSUE TITLE
nextjs14 strict mode will cause mention disappear

### ISSUE THREAD

**Issue by chenyingkeai** [draft-js-plugins/draft-js-plugins#3517]
I am using draft-js-plugins/mention in a Next-js 14 project. However, when I type @ in the editor, the mention popover doesn't appear.

Through debugging the code in mention plugins, I found that this particular code runs twice in Nextjs14 strict mode
i found that those code will run twice in nextjs14 strict mode

For now, I've disabled this mode. I'm wondering if there are any possible improvements to this. Or perhaps, this could be helpful to someone else who encounters the same issue.

Here is the chunk of code in question:

```
var useIsomorphicLayoutEffect = typeof window !== "undefined" ? useLayoutEffect : useEffect;
  useIsomorphicLayoutEffect(function () {
    props.store.register(props.offsetKey);
    props.store.setIsOpened(true);
    updatePortalClientRect(props);
    // trigger a re-render so the MentionSuggestions becomes active
    props.store.setEditorState(props.store.getEditorState());
    return function () {
      props.store.unregister(props.offsetKey);
      props.store.setIsOpened(false);
      props.store.setReferenceElement(null);
    };
  }, []);
```

**Comment by fxOne** [comment]
Duplicated to https://github.com/draft-js-plugins/draft-js-plugins/issues/2966
