### ISSUE TITLE
Add a note about babel-polyfill requirement in the documentation

### ISSUE THREAD

**Issue by Zhouzi** [draft-js-plugins/draft-js-plugins#352]
There are usage of features that requires `babel-polyfill` (e.g `for...of` in `Editor/index.js`), it may be worth adding a note about that.

**Comment by nikgraf** [comment]
This shouldn't be necessary as we compile the code /w Babel before putting it up to npm. Did I miss something?

**Comment by Zhouzi** [comment]
There are a few things that are not transpiled/polyfilled at build time, e.g `for...of` uses `Symbol` which needs a run time polyfill such as `babel-polyfill`.

**Comment by nikgraf** [comment]
good catch, what if we add this to the readme & the docs as a not at every install example?

**Comment by Zhouzi** [comment]
yes, let's do that👌

**Comment by smeijer** [comment]
The counter plugin also depends on `punnycode 2.0`, which is incompatible with IE11. Isn't it possible to use punnycode v1.4.1. ?

See this related issue: https://github.com/bestiejs/punycode.js/issues/56

**Comment by juliankrispel** [comment]
Closing this issue as part of a clean out. If you think this should remain open please let me know. Cheers
