### ISSUE TITLE
Focusing on ComponentDidMount.

### ISSUE THREAD

**Issue by stefan1968** [draft-js-plugins/draft-js-plugins#357]
When i do this:

``` javascript
componentDidMount() {
  this.refs.editor.focus();
}
```

To put the cursor inside the box, the plugins no longer work. Any ideas?

**Comment by Zhouzi** [comment]
Hey @stefan1968! Could you elaborate on what you mean by "the plugins no longer work"? And are there any errors in the console?

**Comment by prabodh** [comment]
It happens in my setup too..to be precise, when i call focus in componentDidMount , mention plugin does not work..there are no errors in the console..i dont have a public reproduce setup for this bug..but will try to get one and post if it helps

**Comment by stefan1968** [comment]
I fixed this by doing a setTimeout call to focus with a zero delay.

**Comment by prabodh** [comment]
@stefan1968 thanks...yes..actually it did work for me....any thoughts on why this works...
i will give it a shot to fix it in the plugin

**Comment by stefan1968** [comment]
I have no idea, but figure its because the plugins haven't had time to setup yet, and this call would wait till the next frame. I'm guessing here.

**Comment by sam-jay** [comment]
Having this issue even with a setTimeout. Causing mentions to not be rendered.

**Comment by nikgraf** [comment]
very strange, need to look into it a some point. Do you have an example repo I can install and try?

**Comment by tommoor** [comment]
Note if you put this in a `setTimeout` don't forget to check that the editor ref still exists before calling focus

**Comment by nikgraf** [comment]
Does this bug still exist?

**Comment by misterioss** [comment]
yes

**Comment by thomastvedt** [comment]
setTimeout worked as a workaround for mentionsPlugin
