### ISSUE TITLE
Inconsistency with decorators and EditorState

### ISSUE THREAD

**Issue by Schniz** [draft-js-plugins/draft-js-plugins#359]
Using version `1.1.0`.

lets say we have this function:

```js
function createState(text) {
  return EditorState.createWithContent(
    ContentState.createFromText(text)
  );
}
```

each time we create a new `EditorState`, we need to manually set the decorators. Yet, the first state we send gets the decorators from the plugins.

**Comment by nikgraf** [comment]
The issue here is that the decorators are part of the editorState. Every time you create a new EditorState the decorators are not applied anymore.

There are other ways to update the EditorState. There is a FAQ document we compiled with a proposal https://github.com/draft-js-plugins/draft-js-plugins/blob/master/FAQ.md#how-to-reset-the-content

**Comment by nikgraf** [comment]
I hope this helps. I close the issue for now, but feel free to open more if you have more questions 😄

**Comment by Schniz** [comment]
:+1: but isn't `EditorState#push` creates an `undo` action?

**Comment by nikgraf** [comment]
@Schniz that's true, what's the use-case where you want to clean the undo stack?

**Comment by Schniz** [comment]
Writing a text editor - choosing a file should replace the entire contents
of the editor and create a new EditorState (without preserving undos)

**Comment by nikgraf** [comment]
makes sense

We could set the decorators in ever `componentWillReceiveProps`, but we should check & make sure that it doesn't have bad impact on the performance …

**Comment by Zhouzi** [comment]
I personally have the feeling that the intention here is really to "re-build" the editor with a new blank state so it makes sense to re-instantiate the editor (and thus the decorators). The solution could be to just abstract that part in a function that returns the editor's initial editorState to avoid the repetition.

**Comment by Schniz** [comment]
Or at least expose a (curried?) `attachDecorators(plugins, state)` function 😄

**Comment by Zhouzi** [comment]
Do you mean something like:

```javascript
const attachDecorators = (plugins) => (state) => /* attach decorators */;
```

That could be great!

**Comment by nikgraf** [comment]
Sounds reasonable, happy to merge a PR (please add some tests as well as the editor itself is & should be well tested)

**Comment by nikgraf** [comment]
@Zhouzi @Schniz what do you guys think about a utility function to retrieve a combined decorator from an Array of plugins? This way developers can apply the manually whenever they want to create a new EditorState.

```js
import { createCombinedDecorator } from 'draft-js-plugins-editor';

const plugins = [mentionPlugin, hashtagPlugin];
const combinedDecorator = createCombinedDecorator([mentionPlugin, hashtagPlugin]);

function createState(text) {
  return EditorState.createWithContent(ContentState.createFromText(text), combinedDecorator);
}
```

**Comment by Zhouzi** [comment]
I'd say that's the way to go 👍

**Comment by Schniz** [comment]
Sweet!

**Comment by nikgraf** [comment]
hehe, ok

anyone wanna take this up? I will spend the next hour reviewing PRs 😄

**Comment by whitef0x0** [comment]
@nikgraf was this ever completed?

**Comment by pioul** [comment]
Just had a quick go at this, and it doesn't seem possible (at least easily) anymore: to create a new set of combined decorators, [`createCompositeDecorator`](https://github.com/draft-js-plugins/draft-js-plugins/blob/0cc196646de85472b138d7898c8c7e343b45a6c1/draft-js-plugins-editor/src/Editor/createCompositeDecorator.js) needs to be passed `getEditorState` and `setEditorState`, which are only available within the component itself once instantiated.

I'm not familiar enough with the codebase to know if it could be refactored in a way that makes this easier.

The only way I currently see of making such a util work would be to create it as a prototype method, and have people retrieve the Editor instance using a `ref` attribute, from which they'd be able to access the util. Doable but really not the best api.

My use-case (forcing the re-rendering of decorators) doesn't require this solution specifically, I'll implement another simple one instead, but the idea in this thread is great and would make a larger number of use-cases possible 👍
