### ISSUE TITLE
Gesture/Swipe support

### ISSUE THREAD

**Issue by hadynz** [draft-js-plugins/draft-js-plugins#360]
I'm keen to create DraftJS plugin that supports swiping on elements to style them. Very similar to the experience that [Paper](http://blog.fiftythree.com/posts/swipe-to-style) provides.

![](http://static1.squarespace.com/static/5565e32ce4b0dcba1f63442d/t/55f1c1bae4b0e3b621990078/1441907206466/fiftythree-paper-swipe-to-style?format=1500w)

Any tips from people more familiar with the DraftJS model on the building blocks to create such a plugin? In particular... I would love to get some guidance on how to wrap every DraftJS "block" with a high order component that would have touch start/end listeners on them.

Any thoughts on this would be great! Let's make a great plugin for this awesome editor.

**Comment by nikgraf** [comment]
Using hammer.js and a higher order component sounds reasonable. The resizable or focus plugin can provide some guidance, but they are mostly built by Ben and yet I didn't have time to take a closer look.

**Comment by juliankrispel** [comment]
Seems like it'd be a great plugin.

In an effort to clean up issues, I'm closing all issues that aren't relevant and should be closed, if you think this shouldn't be closed please let us know why and we'll reopen. Cheers
