### ISSUE TITLE
Mobile bug: Sticker backspace

### ISSUE THREAD

**Issue by khankuan** [draft-js-plugins/draft-js-plugins#361]
Device: Nexus 5x
Android: 6.0.1
Browser: Chrome 51.0.2704.81
Keyboard: Swiftkey 6.3.6.46

After inserting sticker, backspace closes the keyboard and does not remove the sticker

**Comment by nikgraf** [comment]
I feel like we should convert Stickers to use atomic blocks. This way we get all the atomic block support out of the box and if it's also an issue it should be fixed in the core. It's already in the 2.0 roadmap: https://github.com/draft-js-plugins/draft-js-plugins/issues/329

**Comment by mingzhaov** [comment]
Hey, do we have some solutions to make stickers stay with the text in a line? just like the way the emoji does @nikgraf
