### ISSUE TITLE
Mobile bug: Emoji backspace

### ISSUE THREAD

**Issue by khankuan** [draft-js-plugins/draft-js-plugins#363]
Device: Nexus 5x
Android: 6.0.1
Browser: Chrome 51.0.2704.81
Keyboard: Swiftkey 6.3.6.46

Erasing a emoji needs 2 backspace. After that, typing a colon would create the same emoji even though i have not typed anything letter (Dropdown does not appear as well).

**Comment by freedomlang** [comment]
@khankuan Is it still happen on the latest version ?

**Comment by khankuan** [comment]
I have not used the lib since then. You can probably close the bug :P

**Comment by freedomlang** [comment]
@khankuan we'll close this issue for now, if you still facing this issue or something similar, please feel free to open a new issue, we will pick it from there
