### ISSUE TITLE
Unknown Prop Warning from draft-js-mention-plugin in react@ 15.2.0

### ISSUE THREAD

**Issue by mzbac** [draft-js-plugins/draft-js-plugins#364]
React 15.2 added a check for unknown props being passed to a component.  when using React@15.2.0 
draft-js-mention-plugin got the waning message as below:

VM813 bundle.js:1226 Warning: Unknown props `onSearchChange`, `suggestions`, `ariaProps`, `callbacks`, `theme`, `store`, `entityMutability`, `positionSuggestions` on <div> tag. Remove these props from the element. For details, see https://fb.me/react-unknown-prop
    in div (created by MentionSuggestions)
    in MentionSuggestions (created by Decorated(MentionSuggestions))
    in Decorated(MentionSuggestions) (created by CustomMentionEditor)
    in div (created by CustomMentionEditor)
    in CustomMentionEditor

**Comment by nikgraf** [comment]
thx for reporting and especially for creating a PR!

**Comment by MykolaGolubyev** [comment]
It now complains on isFocused property.
