### ISSUE TITLE
Custom theme error for styles

### ISSUE THREAD

**Issue by zacksiri** [draft-js-plugins/draft-js-plugins#372]
I'm trying the demo code from the site, and I am getting this error with webpack compile.

` composition is only allowed when selector is single :local class name not in ".mentionSuggestionsEntryFocused", ".mentionSuggestionsEntryFocused" is weird`

**Comment by Zhouzi** [comment]
The snippets from the site are using a few webpack plugins to import the css so it may not work out of the box. How familiar are you with webpack's loaders? You can whether try to install the required plugins or use a regular css file.

**Comment by nikgraf** [comment]
@zacksiri did you run this repo or tried to copy the code in your setup?
I will close the issue for now, but feel free to continue the conversation. I have more time again and will try to help.

**Comment by krsnaa** [comment]
FWIW, the line causing this is: `composes: mentionSuggestionsEntry;` from the code block below:

```
.mentionSuggestionsEntryFocused {
    composes: mentionSuggestionsEntry;
    background-color: #e6f3ff;
}
```

It is found in the mentionsStyles.css file.
