### ISSUE TITLE
Sticker drag and drop on Website

### ISSUE THREAD

**Issue by signalwerk** [draft-js-plugins/draft-js-plugins#374]
I'm not familiar with the project yet. Therefore just the description from a users point of view. On https://www.draft-js-plugins.com/ there is an example with stickers. If I drag a unicorn (:heart_eyes:) to the text area I get a correct cursor indicator and even a green plus sign but if I let it drop it won't insert the unicorn. Click works perfect.

**Comment by Zhouzi** [comment]
Hey @signalwerk I am afraid that drag and dropping unicorns is not a feature the sticker plugin supports 😃. The plus sign is added by the browser and I think it would take a fair amount of work to implement that. I'm unsure so it'd be great to have @nikgraf's thoughts on this.

**Comment by signalwerk** [comment]
Pardon. I didn't know that dragging is not supported. I modified the stylesheet so people can't drag the images at first place. See #384

**Comment by nikgraf** [comment]
@signalwerk thx for helping out here!

**Comment by nikgraf** [comment]
@Zhouzi I think it should be not too hard with the drag & drop plugin, but haven't tried to combine them yet
