### ISSUE TITLE
[Linkify] Are new URLs introduced notified?

### ISSUE THREAD

**Issue by jorgemanso** [draft-js-plugins/draft-js-plugins#376]
Hi! Only started with drafjs recently and I am trying to use the _linkify_ plugin and all works fine but I am not able find how to get notified immediately after the user inputs the URL and the presses the space bar. I would need that info to display a preview of the URL right below the editor. Thanks! :)

**Comment by jorgemanso** [comment]
Closing as I managed to do this by listening to the events on the editor and when space bar is pressed I check if the previous content was a link.

**Comment by Zhouzi** [comment]
Hey @jorgemanso, sorry for not getting back but I'm not yet really familiar with how the linkify plugin works. You're probably good to go by looking for links after the space bar is pressed, there are two things to note though:

1. You may already be doing it that way, but just so you know there's a `keyBinding` exposed by DraftJS that comes handy to add behavior to certain key press: [Key Bindings](https://facebook.github.io/draft-js/docs/advanced-topics-key-bindings.html)
2. You'll probably want to look for links after a paste event too, have a look at [handlePastedText](https://facebook.github.io/draft-js/docs/api-reference-editor.html#handlepastedtext)

Hope that helps and let us know if you're facing any issues ;)

**Comment by adrianmc** [comment]
One thing you can do is attempt to keep track of the number of links in a counter. And basically, each time onChange is called, you compare the new number of links with the old number of links. If it is different, you just call a handler.

**Comment by jorgemanso** [comment]
Thanks @Zhouzi ! I haven't used key bindings a lot but I will defo have a look :)

**Comment by nikgraf** [comment]
@jorgemanso since today you can provide your on Link component with this PR https://github.com/draft-js-plugins/draft-js-plugins/pull/415. You could leverage the React life-cycle `componenDidMount` to be notified when a link is used.
