### ISSUE TITLE
Prefix not sent.

### ISSUE THREAD

**Issue by stefan1968** [draft-js-plugins/draft-js-plugins#380]
How can i make it send the selected prefix when i use content.getPlainText(); the names are there, but not the actual prefix that has appeared in the input bar?

**Comment by Zhouzi** [comment]
Are you referring to the mention plugin? Looks like you already submitted a similar issue, please see #264.

**Comment by Zhouzi** [comment]
@stefan1968 I am closing as duplicate of #264 but let us know if the issues are not related.

**Comment by nikgraf** [comment]
thx @zhouzi
