### ISSUE TITLE
draft-js-mention-plugin defaultSuggestionsFilter parametrizable number of rows

### ISSUE THREAD

**Issue by jmaguirrei** [draft-js-plugins/draft-js-plugins#381]
Hi, is it possible to modify this function to allow maxRows parameter?
In some cases you want less rows for, a more 'inline' suggestion.

This could be the implementation:

```javascript
// /node_modules/drafts-js-mention-plugin/lib/utils/defaultSuggestionsFilter.js

'use strict';

Object.defineProperty(exports, "__esModule", {
  value: true
});
// Get the first 5 suggestions that match
var defaultSuggestionsFilter = function defaultSuggestionsFilter(searchValue, suggestions, maxRows = 5) {
  var value = searchValue.toLowerCase();
  var filteredSuggestions = suggestions.filter(function (suggestion) {
    return !value || suggestion.get('name').toLowerCase().indexOf(value) > -1;
  });
  var size = filteredSuggestions.size < maxRows ? filteredSuggestions.size : maxRows;
  return filteredSuggestions.setSize(size);
};

exports.default = defaultSuggestionsFilter;
```

This way, you can consume the filter for example like this:

```javascript
    this.setState({
      suggestions: defaultSuggestionsFilter(value, mentions, 1),
    });
```

Or as the default way:

```javascript
    this.setState({
      suggestions: defaultSuggestionsFilter(value, mentions),
    });
```

Thanks very much,

**Comment by Zhouzi** [comment]
Hey @jmaguirrei! Actually you can already do it by simply returning the max number of suggestions you want from the function that actually return them. It's great to decouple the suggestions from the plugin itself as there are lots of case where you'll want to manage it precisely. For example to add/remove properties, filter them, or add a maximum limit. So regarding the limit, you could have something like this:

```javascript
fetch('/suggestions', { method: 'GET' })
  .then((res) => res.json())
  .then((suggestions) => {
    const maxRows = 5;
    this.setState({
      suggestions: suggestions.slice(0, maxRows)
    });
  })
```

You might also want to consider adding a parameter to the web service so it returns just 5 items. In certain cases it could lead to some performant improvements.

**Comment by jmaguirrei** [comment]
@Zhouzi I havent use **immutable.js** untill now, but seems that the plugin needs it to work.

For example, this code:

```javascript

    this.setState({
      suggestions: _.filter(
        mentions, obj => _.includes(obj.name.toLowerCase(), value.toLowerCase())
      ).slice(0, 3)
    });

```

Being mentions a regular array of objects (6 elements).

![screenshot from 2016-08-03 16 27 04](https://cloud.githubusercontent.com/assets/11958637/17380896/4bc8b1de-5997-11e6-82b5-c7c5abaa30c3.png)

What could be wrong?

**Comment by Zhouzi** [comment]
The suggestions have to be an ImmutableJS list so you'll need to:

```javascript
import { fromJS } from 'immutable';

this.setState({
  suggestions: fromJS(_.filter(
      mentions, obj => _.includes(obj.name.toLowerCase(), value.toLowerCase())
  ).slice(0, 3))
});
```

**Comment by jmaguirrei** [comment]
Thanks, it works now.

One thing though is the console is showing an error. I look into this
https://github.com/draft-js-plugins/draft-js-plugins/pull/365

But seems there is still an issue?

![screenshot from 2016-08-03 18 52 26](https://cloud.githubusercontent.com/assets/11958637/17385183/05deba3e-59af-11e6-8e23-5b2b28417dc3.png)

**Comment by Zhouzi** [comment]
Glad your could figure it out 👍 

What version are you using?

**Comment by jmaguirrei** [comment]
Yes, this are the versions I have:

```
├─┬ draft-js@0.7.0
│ ├─┬ fbjs@0.8.3
│ │ ├── core-js@1.2.6
│ │ ├─┬ isomorphic-fetch@2.2.1
│ │ │ ├─┬ node-fetch@1.5.3
│ │ │ │ ├── encoding@0.1.12
│ │ │ │ └── is-stream@1.1.0
│ │ │ └── whatwg-fetch@1.0.0
│ │ ├─┬ promise@7.1.1
│ │ │ └── asap@2.0.4
│ │ └── ua-parser-js@0.7.10
│ └── immutable@3.8.1
├─┬ draft-js-mention-plugin@2.0.0-beta.2
│ ├── decorate-component-with-props@1.0.2
│ ├── find-with-regex@1.0.2
│ └── union-class-names@1.0.0
├── draft-js-plugins-editor@1.1.0
```

**Comment by nikgraf** [comment]
@jmaguirrei This is an warning when using it combined with new React version. Working on a fix at the moment.
