### ISSUE TITLE
Cannot find module 'lodash/escapeRegExp'

### ISSUE THREAD

**Issue by Inucoder** [draft-js-plugins/draft-js-plugins#386]
After installing current version from NPM it says it can't find lodash/escapeRegExp module. It seems like it is imported from mentionSuggestionsStrategy.js. I can't see any reference to Lodash in the package.json, is it missing?

**Comment by Zhouzi** [comment]
You are absolutely right @Inucoder, `lodash` is missing from the `package.json`'s dependencies. I'll push a fix.

**Comment by DerekHung** [comment]
It should be loadash/string/escapeRegExp

**Comment by Zhouzi** [comment]
@DerekHung lodash no more splits its methods into type-related sub directories. The issue comes from the missing entry in the `package.json`.

**Comment by Inucoder** [comment]
Awesome!, thanks @Zhouzi

**Comment by nikgraf** [comment]
awesome, thanks for all the investigation!
