### ISSUE TITLE
current npm package1.1.0 version doesn't work with toolbar plugins

### ISSUE THREAD

**Issue by mzbac** [draft-js-plugins/draft-js-plugins#387]
1.1.0 version using 
`     if (plugin.onChange) {
        newEditorState = plugin.onChange(newEditorState);
      }
    });`
instead of 
`if (plugin.onChange) {
        newEditorState = plugin.onChange(newEditorState, this.getPluginMethods());
      }
    });`
it breaks toolbar plugin's onChange function

**Comment by nikgraf** [comment]
@mzbac the the toolbar plugin didn't exist in 1.x

I'm closing the issues, but let me know in case you still have question here.
