### ISSUE TITLE
Mentions: Uncaught TypeError: clientRectFunctions.get(...) is not a function

### ISSUE THREAD

**Issue by jameslk** [draft-js-plugins/draft-js-plugins#388]
When I try to use a mentionTrigger longer than 1 character, I start to get this error:

```
index.js:106 Uncaught TypeError: clientRectFunctions.get(...) is not a function
getPortalClientRect @ index.js:106
(anonymous function) @ index.js:77
MentionSuggestions._this.componentDidUpdate @ index.js:89
invokeComponentDidUpdateWithTimer @ ReactCompositeComponent.js:66
...
```

Steps to reproduce:

Set up a mentionTrigger of _test_,

``` javascript
    const mentionsPlugin = createMentionsPlugin({
        mentionTrigger: 'test'
    });
```

Then in the editor, type "test" and press backspace, which triggers the error.

This appears to be caused by the code in `MentionSuggestions` `componentDidUpdate`:

``` javascript
const decoratorRect = this.props.store.getPortalClientRect(this.activeOffsetKey);
```

It fails because `this.activeOffsetKey` is no longer in the store `searches` map. It was taken out from a prior call to the store's `unregister` function when I hit backspace.

**Comment by gfx** [comment]
I have the same errors on my application.

Fortunately I can reproduce this issue on the demo site: https://www.draft-js-plugins.com/plugin/mention

1. Start a mention selection by typing `@`
2. Select the first one
3. Delete it by typing three backspaces
4. Type `@foo` and `<enter>`

Then you will see this error.

**Comment by nikgraf** [comment]
Thanks for reporting @jameslk & @gfx. I'm quite busy right now. Does one of you have time to investigate & fix the issue? A Pull Request would be very welcome.

**Comment by mzbac** [comment]
just quickly went through source code, it seems mention plugin only allow to  set single character to be mentionTrigger. no sure if needs a RP to modify it to support mulit-characters mentionTrigger.

**Comment by paulyoung** [comment]
@mzbac I did something related to that in https://github.com/mjrussell/draft-js-autocomplete-plugin-creator/pull/7.

IMHO, it would be great if that project could be brought into this repo and the mentions plugin be implemented in terms of that.

cc @mjrussell

**Comment by paulyoung** [comment]
@mzbac I also just proposed these changes: https://github.com/mjrussell/draft-js-autocomplete-plugin-creator/pull/11

**Comment by mzbac** [comment]
@paulyoung  thanks for your proposal, I don't know the reason why mention trigger was set to single character, have to confirm with Nick. 
@nikgraf  could you please review this? I can't remember why mention trigger was restricted to single character.

**Comment by jameslk** [comment]
While this is being looked at, I'd like to propose allowing the trigger to to be 0 characters if possible. For example, on Facebook, I can mention someone just by typing out a few characters of their name. This is actually how I originally discovered this bug, as I was trying to do something similar.

**Comment by ZeeStorm** [comment]
Any update on this issue? Just started seeing it in my own app, and it looks like this issue has been abandoned for over a year now :(

**Comment by freedomlang** [comment]
@ZeeStorm Ah, looks like #416 should fixed this issue, would you please offer a codesandbox ? It would help us to check this error

**Comment by ZeeStorm** [comment]
@freedomlang if that's the case I'm probably going to ignore it. I haven't touched that code in months, and out of thousands of users, it just randomly happened to 1 yesterday and was alerted via sentry. I tried to reproduce using the steps above, but couldn't get it to break and stepping through the code didn't seem to alert any red flags that would cause it an issue. If it starts showing up more, I'll write up my use case. For now, I may add more debugging to sentry for this specific issue in case it does occur again. Thanks!
