### ISSUE TITLE
Support for adding iframes

### ISSUE THREAD

**Issue by sauravskumar** [draft-js-plugins/draft-js-plugins#390]
Can we please have support for adding iframes to the text editor Please. Thank You

**Comment by Zhouzi** [comment]
Hey @sauravskumar! Could you elaborate on the use case? Why would you add an iframe in a text editor?

**Comment by sauravskumar** [comment]
@Zhouzi i want to add jsfiddle to my website and to do so we require iframes... Iframes could be an awesome idea for draft.js ... Can we please add support for iframes... Thank You

**Comment by Zhouzi** [comment]
Ok so the intention here is to add support for embeds which could be a great plugin. It'd require some work though as we need to think about the user interface and the security issues it could involve. Would you be interested in implementing it?

**Comment by sauravskumar** [comment]
I would be very happy to contribute... I am unfamiliar to this codebase... is there any helpful resource to get up and running with this repo in not much time?

**Comment by Zhouzi** [comment]
You can start by having a look at the DraftJS documentation. Then, choose an existing plugin that's close to what you want to do and play around with it. Make changes, see what happens and hopefully you'll have a better understanding of how it works. You don't need to understand all the concepts and read all the code.

Feel free to create a pull request if you need some help 😉

**Comment by albertomr86** [comment]
Does this helps? https://github.com/jimmycodesocial/draft-js-iframely-plugin

**Comment by sibelius** [comment]
please use https://github.com/jimmycodesocial/draft-js-iframely-plugin

we need to include other plugins from other repositories in the code
