### ISSUE TITLE
 Link decorator not work with plugin

### ISSUE THREAD

**Issue by DerekHung** [draft-js-plugins/draft-js-plugins#395]
Hello 
When I use <Editor> from draft-js-plugins
I found that the DraftJS example : link didn't work with plugin's <Editor>
It looks like decorator didn't has any effect 

`const decorator = new CompositeDecorator([
					{
						strategy: findLinkEntities,
						component: Link,
					},
				]);`

I have a sample code in this repo : https://github.com/DerekHung/link-draft-plugin-example

Would you help to solve this problem?

Thanks~

**Comment by adrianmc** [comment]
So let me clarify here. You're not trying to use the Link plugin? You are trying to use the draft-js-plugins editor, but it seems to be breaking the official draft-js link example?

**Comment by DerekHung** [comment]
Yes,
I only use the draft-js-plugins <Editor> component

**Comment by DerekHung** [comment]
@adrianmc  do you have any idea about this bug?

**Comment by mzbac** [comment]
currently plugin editor will use the decorators from plugins. so the decorator you passed as props of plugin editor has been ignored.. as a work around you can write you own plugin which wrap your custom decorator and pass it to plugin editor.
```javascript

const yourPlugin = (config = {}) => {
  return {
    decorators: [{
      strategy: linkStrategy,
      component: Link,
    }]
  }
}

```
the details you can see the gist below:
https://gist.github.com/mzbac/acbb79146ba875954bebb8d539dc382c

**Comment by nazarposhta** [comment]
@DerekHung did you resolve that problem?
