### ISSUE TITLE
[2.0] dnd plugin should set the url after upload

### ISSUE THREAD

**Issue by kiliwalk** [draft-js-plugins/draft-js-plugins#399]
Currently, after upload, the content state still has a null url property in the entity data, only src(data-url) there. Then I can't get the img url when exporting.
Is there anything I missed?
If it's a bug, I can create a pull request.

**Comment by nikgraf** [comment]
@bkniffler is this a bug?

**Comment by bkniffler** [comment]
Must be some kind of old relic. The dnd plugin should not dictate the url prop / initiate it with null. I've removed it here https://github.com/draft-js-plugins/draft-js-plugins/commit/c3b37744a1f5e902d3e7558086f8a9695b60dc54

Thanks for the report, feel free to reopen or comment if theres something else related!

**Comment by Antherkiv** [comment]
Hello, I want to ask if the url going to be completely removed in replaceBlock and delegate the work to the handleBlock:

 newEditorState = replaceBlock(
                modifyBlockData(
                  newEditorState,
                  blocks.first().get('key'),
                  retainSrc ? { progress: undefined } : { progress: undefined, src: undefined }
                ),
                blocks.first().get('key'),
                newEditorStateOrBlockType
);

If you set retainSrc to true, you got nothing, I want to understand if it´s ok and then how you plan to handle that.

Best regards.
