### ISSUE TITLE
Linkify Plugin not showing links in readonly mode

### ISSUE THREAD

**Issue by tbohlen** [draft-js-plugins/draft-js-plugins#401]
Hi all -

I'm having trouble getting draft-js-plugins working. The linkify plugin works wonderfully in edit mode, but as soon as I transition the editor to readOnly mode, my links do not show up. I've figured out that the decorator strategy is working just fine and still triggering correctly in readOnly mode, but that the decorator component is never being rendered.

Any ideas on what might be going on here? I saw a number of other issues relating to readOnly mode but none seemed to be showing quite the same symptoms.

Note that I've tried this with both the version 2 beta and the version 1 code.

Thanks so much for any help!

**Comment by tbohlen** [comment]
After some more digging, I discovered this was because I was using EditorState.createWithContent without passing a decorator. Going to see about making that documentation clearer for future users on the draft-js project.

Thanks!

**Comment by nikgraf** [comment]
glad you figured it out 👍

**Comment by meteorplus** [comment]
can you be more clear plz what you did there?

**Comment by tbohlen** [comment]
Yes, sure.

When I rendered an editor in read-only mode, I was parsing a raw content state saved in a database using

```
let contentState = convertFromRaw(savedContentState)
let editorState = EditorState.createWithContent(contentState)
// render editor in readonly mode
```

What I _should_ have been doing is this:

```
let contentState = convertFromRaw(savedContentState)
let decorator = myFunctionForGrabbingAllPluginDecorators();
let editorState = EditorState.createWithContent(contentState, decorator)
// render editor in readonly mode
```

My understanding (someone else might be able to shed more light) is that then the editor state constructor runs it needs the decorators to do the initial pass of the content and render appropriate parts of the content using those decorators. If you don't provide the link plugin decorator at this stage, Draft.js doesn't know to hunt for and render links when it first renders your content.

@meteorplus let me know if that helped!

**Comment by Rafi993** [comment]
@tbohlen could you give a sample of how **myFunctionForGrabbingAllPluginDecorators** will look

**Comment by Rafi993** [comment]
and it would be awesome to include in the docs too

**Comment by meteorplus** [comment]
@tbohlen thanks dude but I am against grabbing all things! it's might be considered something else these days hhh

**Comment by meteorplus** [comment]
Salam Rafi9

this might help you

**Comment by meteorplus** [comment]
check that repo too

**Comment by tbohlen** [comment]
@Rafi993 Phew getting my head back into this bit of the code! In case you haven't already solved this, and for people who run into this in future, I've included some generalized code for `myFunctionForGrabbingAllPluginDecorators` below.

```
import MultiDecorator from "draft-js-plugins-editor/lib/Editor/MultiDecorator";
import { CompositeDecorator } from "draft-js";

function getPluginDecoratorArray() {
    let decorators = [];
    let plugin;
    // check each plugin that will be used in the editor for decorators
    // (retrieve listOfPlugins however makes sense in your code)
    for (plugin of listOfPlugins) {
        if (plugin.decorators !== null && plugin.decorators !== undefined) {
            // if the plugin has any decorators, add them to a list of all decorators from all plugins
            decorators = decorators.concat(plugin.decorators);
        }
    }
    return decorators;
}

function myFunctionForGrabbingAllPluginDecorators() {
    // I can't quite remember why I had to wrap things in this exact way, but found that I ran into
    // errors if I did not both have a MultiDecorator and a CompositeDecorator wrapping
    // This MultiDecorator can now be used as shown in my previous post.
    return new MultiDecorator(
        [new CompositeDecorator(getPluginDecoratorArray())]
    );
}
```

**Comment by SajedHassan** [comment]
> @Rafi993 Phew getting my head back into this bit of the code! In case you haven't already solved this, and for people who run into this in future, I've included some generalized code for `myFunctionForGrabbingAllPluginDecorators` below.
> 
> ```
> import MultiDecorator from "draft-js-plugins-editor/lib/Editor/MultiDecorator";
> import { CompositeDecorator } from "draft-js";
> 
> function getPluginDecoratorArray() {
>     let decorators = [];
>     let plugin;
>     // check each plugin that will be used in the editor for decorators
>     // (retrieve listOfPlugins however makes sense in your code)
>     for (plugin of listOfPlugins) {
>         if (plugin.decorators !== null && plugin.decorators !== undefined) {
>             // if the plugin has any decorators, add them to a list of all decorators from all plugins
>             decorators = decorators.concat(plugin.decorators);
>         }
>     }
>     return decorators;
> }
> 
> function myFunctionForGrabbingAllPluginDecorators() {
>     // I can't quite remember why I had to wrap things in this exact way, but found that I ran into
>     // errors if I did not both have a MultiDecorator and a CompositeDecorator wrapping
>     // This MultiDecorator can now be used as shown in my previous post.
>     return new MultiDecorator(
>         [new CompositeDecorator(getPluginDecoratorArray())]
>     );
> }
> ```

For anyone who is facing a similar issue:
Not wrapping the `CompositeDecorator` into the `MultiDecorator` causes the `onChange` method to keep getting called causing a StackOverflow issue
