### ISSUE TITLE
draft-js-mention-plugin throwing errors after selecting the trigger and typing

### ISSUE THREAD

**Issue by ksmth** [draft-js-plugins/draft-js-plugins#403]
Steps to reproduce:
 - type "@"
 - select "@" via "Shift <-" or with the mouse
 - type anything
 - observe the error in the console

From what I understand, `this.props.store.getPortalClientRect(...)` breaks in this case, but I don't know enough about this plugin yet to fix it.

**Comment by nikgraf** [comment]
Should be solved with this PR and a release today: https://github.com/draft-js-plugins/draft-js-plugins/issues/403

Can you try again?
