### ISSUE TITLE
Best Approach to Convert to HTML

### ISSUE THREAD

**Issue by agungsb** [draft-js-plugins/draft-js-plugins#404]
Hi, this is a really nice work.

I'm using draft-js-mention-plugin and draft-js-linkify-plugin. I'm curious what is the best approach to convert them to HTML? I use https://github.com/sstur/draft-js-export-html , but it export either the mention and the linkify as a plain text instead of ```<a>``` element. Any thoughts?

**Comment by nikgraf** [comment]
@agungsb right now I would recommend to use the editor in readOnly mode. I thought about creating a patch to support plugins or writing a patch, but considering all the other work with higher priority that might take a couple months.

If you have time and are happy to help let me know 😃
