### ISSUE TITLE
Mention plugin to handle some special characters like _ - .

### ISSUE THREAD

**Issue by jssisodiyaPG** [draft-js-plugins/draft-js-plugins#406]
Usernames might have some special characters. Mention plugin regex should handle those as well.
Somthing like this - `/(\s|^)@[\w_\-.]*/g`

**Comment by nikgraf** [comment]
Makes sense. Can you create a PR?

**Comment by jssisodiyaPG** [comment]
Sure, here is the PR
https://github.com/draft-js-plugins/draft-js-plugins/pull/435
