### ISSUE TITLE
Pasting links into the editor doesn't work

### ISSUE THREAD

**Issue by zthomas** [draft-js-plugins/draft-js-plugins#407]
When you paste html links into the demos, none of the links will show up. For my project, I can only get links to render on pasted content. If I remove draftjs plugins editor and use draftjs Editor directly with a compositeDecorator. 

This is probably related to #395

**Comment by mzbac** [comment]
hi zhtomas,

I have commented on https://github.com/draft-js-plugins/draft-js-plugins/issues/395 with a work around of this issue.

**Comment by zthomas** [comment]
Yup, that works now. I guess this is more of an missing documentation issue then. That decorator prop should be added to the props list https://github.com/draft-js-plugins/draft-js-plugins#documentation

here's a PR  https://github.com/draft-js-plugins/draft-js-plugins/pull/408

**Comment by nikgraf** [comment]
thx for helping out here @mzbac & @zthomas ✨
