### ISSUE TITLE
How can I use editor plugin coupled with mention plugin?

### ISSUE THREAD

**Issue by topgun743** [draft-js-plugins/draft-js-plugins#412]
Hi Guys, 
I m trying to use your editor plugin in order to make use of mentions.
Problem is, if I include draftjs via require in my source code and then require editor plugin, 
it gives me console error saying something like 
`....Muliple copies of React bla bla bla........`

I then tried including draftjs using CDN and then required your editor plugin but again it states the same kinda error.

How can I make use of your editor + mention plugins in my existing project, which already includes lots of React/ES6 code? 
Also there must be an examples folder under your repo that makes us to run the plugins at our browser locally. Thanks

**Comment by mzbac** [comment]
Hi topgun,
you can go to docs folder.. it's the code for draft-js-plugins demo site. you will find out how to use draft-js-plugins by reading those codes.

**Comment by nikgraf** [comment]
@topgun743 what version of npm do you use? I assume you have pre-compiled some code and then mixed in other React code?

**Comment by topgun743** [comment]
I use npm 3+
Used static files of React.js and ReactDOM.js in my web page. Added DraftJS js file also on web page. However compiled my other application specific jsx/ES6 code using webpack/gulp and in that I referred these plugins of yours. But it did not work.
