### ISSUE TITLE
Invariant Violation: Invalid DraftEditorContents structure.

### ISSUE THREAD

**Issue by andzuck** [draft-js-plugins/draft-js-plugins#418]
Hi. Not really sure when/why this error is called, but occasionally, I get this error while using a draftjs plugin editor along with two mention plugins. I'm not 100% sure what triggers it, but I believe it has something to do with pressing the shift key while using the editor and/or clicking another button or pressing mouse down. Here is the error that takes place:

Error: Invalid DraftEditorContents structure.
Invariant Violation: Invalid DraftEditorContents structure.
    at invariant (...)
    at getPointForNonTextNode (...)
    at getDraftEditorSelectionWithNodes (...)
    at getDraftEditorSelection (...)
    at DraftEditor.editOnSelect (...)

Following that, I get this error:

Error: Cannot read property 'getIn' of undefined
TypeError: Cannot read property 'getIn' of undefined
    at getUpdatedSelectionState (...)
    at getDraftEditorSelectionWithNodes (...)
    at getDraftEditorSelection (...)
    at DraftEditor.editOnSelect (...)

Some unusual behavior that follows after this error include: clicking backspace doesn't visibly erase text, and after clicking backspace enough times, the placeholder text of the draft editor as well as the typed text are both visible as seen here:

![screen shot 2016-09-07 at 3 52 18 pm](https://cloud.githubusercontent.com/assets/3750712/18326366/6560af38-7513-11e6-9e4f-148946d1ecdb.png)

Any ideas as to how to resolve this infrequent but annoying error? Any help would be greatly appreciated.

Also, if this is important at all, I am rendering multiple editor components on the same page.

Some of my code for the editor is as follows:

export class reactInput extends React.Component {
  constructor() {
    super();

    this.assigneePlugin = createMentionPlugin({ mentionPrefix: '@' });
    this.labelPlugin = createMentionPlugin({ mentionTrigger: '#', mentionPrefix: '#' });

    this.state = {
      editorState: EditorState.createEmpty(),
      // start with blank lists of assignees/labels
      assigneeSuggestions: fromJS([{}]),
      assigneeMentionsArray: [],
      labelSuggestions: fromJS([{}]),
      labelMentionsArray: [],
    };

    this.onChange = (editorState) => {
      this.setState({editorState}, () => {
        this.props.onDateFound(this.getDate());
        this.props.onMentionsFound(this.getMentions());
        this.props.onInputChange(this.getText());
      });
    };

    ...

    render() {
        return (
          <div onClick={this.focus}>
              <Editor
                editorState={this.state.editorState}
                onChange={this.onChange}
                placeholder={this.props.placeholder}
                plugins={plugins}
                ref="editor"
              />
                <this.AssigneeSuggestions
                  onSearchChange={({value}) => this.onSearchChange({value}, PluginType.ASSIGNEE)}
                  suggestions={this.state.assigneeSuggestions}
                  onOpen={() => this.onOpen(PluginType.ASSIGNEE)}
                  onClose={this.onClose}
                />
                <this.LabelSuggestions
                  onSearchChange={({value}) => this.onSearchChange({value}, PluginType.LABEL)}
                  suggestions={this.state.labelSuggestions}
                  onOpen={() => this.onOpen(PluginType.LABEL)}
                  onClose={this.onClose}
                />
          </div>
        );
      }
   }
}

**Comment by nikgraf** [comment]
hehe, what was this about?

**Comment by andzuck** [comment]
Hey @nikgraf totally unrelated to the plugin don't worry haha. I realized afterwards, but I was trying to blur/focus on an old div that I though the plugin was still attached to.
