### ISSUE TITLE
Allow to update the plugins and set new decorators

### ISSUE THREAD

**Issue by nikgraf** [draft-js-plugins/draft-js-plugins#42]
This issue needs to be fixed first:

```
hellendag [12:06 PM] 
:simple_smile:

[12:07] 
The only thing to be careful of with setting a new decorator right now is that `beforeInput` allows native character insertion, so that's causing some problems

[12:07] 
I need to come up with a good solution for that

[12:07] 
So right now, if you set a new decorator in `onChange` and the new state is coming from a `beforeInput`, there can be some rendering bugs

nikgraf [12:08 PM] 
I think I had this issue

hellendag [12:08 PM] 
Double character rendering, mostly

nikgraf [12:08 PM] 
I type in character `a`and it results in 2 a `aa`

[12:08] 
exactly

hellendag [12:08 PM] 
Yeah

[12:08] 
So right now, the way around that is to propagate the new state with a `setTimeout`, to allow the native insertion

[12:08] 
It works, but it's not pretty

[12:09] 
And I need to come up with something better
```

**Comment by MarkNijhof** [comment]
I would really like to see this happen :) and I would like to try out something myself:
`
componentWillMount() {
  this.loadPluginsAndDecorators();
}
componentWillReceiveProps(nextProps) {
  if (!Immutable.is(this.props.plugins, nextProps.plugins) { //make plugins an Immutable.List
    this.unloadPluginsAndDecorators(); // logic from the componentWillUnmount
    this.loadPluginsAndDecorators(); // logic from the constructor + componentWillMount
  }
}
componentWillUnmount() {
  this.unloadPluginsAndDecorators();
}
`
How does this look?

Btw I am not following why you do this in the constructor `const plugins = [this.props, ...this.resolvePlugins()];` why add this.props to the array?

**Comment by juliankrispel** [comment]
Closing for issue cleanup - If you need this issue and think it should remain open please let us know why, thank you
