### ISSUE TITLE
DraftJs Mentions throws an error upon the following behaviour

### ISSUE THREAD

**Issue by andzuck** [draft-js-plugins/draft-js-plugins#421]
Type an @, hit left arrow key to position yourself to the left of the @, type a letter.

After these events, a type error is thrown:

Error: clientRectFunctions.get(...) is not a function
TypeError: clientRectFunctions.get(...) is not a function
    at Object.getPortalClientRect (index.js:106)
    at index.js:77
    at MentionSuggestions._this.componentDidUpdate (index.js:89)
    at ReactCompositeComponentWrapper.invokeComponentDidUpdateWithTimer (ReactCompositeComponent.js:71)
    at ...

**Comment by nikgraf** [comment]
Will be solved with this PR: https://github.com/draft-js-plugins/draft-js-plugins/pull/416

**Comment by andzuck** [comment]
Hey @nikgraf,
Sorry to bother you!
I think this error actually still persists even after this PR. The only difference is that now the error is: 
Error: p.get(...) is not a function

**Comment by nikgraf** [comment]
@andzuck no worries, thx for reporting

**Comment by mzbac** [comment]
@nikgraf I think the bug because the code below  didn't get merge into master branch from PR #416 

```js

if (!this.props.store.getAllSearches().has(this.activeOffsetKey)) {
    return;
 }
```

**Comment by mzbac** [comment]
Hi @andzuck, I can't reproduce the error by your instructions. I have tried on our live demo website and current master branch. can you re-try it on latest version?
@nikgraf  I guess maybe that PR didn't go to npm package..could you please check that?

**Comment by nikgraf** [comment]
@mzbac you worried that it's not published?

**Comment by mzbac** [comment]
@nikgraf, yes, I can't reproduce the error on our live demo website..

**Comment by andzuck** [comment]
Can't reproduce it either on the website @mzbac , but the day I submitted this issue it definitely did occur on the live demo website. It's also still occurring in my implementation of the plugin when the @ is the first character entered into the editor. Do you think it has anything to do with npm and the version being sent to me?

**Comment by nikgraf** [comment]
@andzuck did you upgrade to the latest beta?

**Comment by juliankrispel** [comment]
not reproducable anymore :+1:
