### ISSUE TITLE
Mobile Safari - tapping on mention item in list doesn't add mention to editor

### ISSUE THREAD

**Issue by tedlin182** [draft-js-plugins/draft-js-plugins#423]
Hi,

I upgraded to 1.1.2 recently and for some reason I can't add mentions after tapping on them. It seems to only be in mobile Safari.

I can type and show the mentions list menu fine and when I tap on an item, it just closes the menu and the mention doesn't populate in the editor. There are no errors as far as I can see and it works in Android, Safari desktop, etc.

In the `MentionsSuggestions/Entry/.index.js` it looks like you're only using onMouseDown and onMouseUp which don't fire in Mobile Safari (added console.log lines). 

I added `onTouchStart/End` to have it trigger the this.onMouseDown/Up methods and it seemed to fix the issue.

Is there a better workaround to help resolve this issue in the meantime?

**Comment by nikgraf** [comment]
Wow, that's unexpected. I thought mouseDown is supported as well … could you create a PR with onTouchStart/End?
