### ISSUE TITLE
Mentions suggestion up arrow does not loop

### ISSUE THREAD

**Issue by stevensacks** [draft-js-plugins/draft-js-plugins#437]
When the mentions suggestion panel opens, you can hit the down arrow to cycle through them and when you hit the bottom, it will loop back around to the top.

However, if you hit the up arrow to cycle through them, it stops at the top and does not cycle to the bottom like it should.

Both down and up arrow should cycle both directions infinitely.

**Comment by nikgraf** [comment]
Good point: Can you create a PR with a fix?

**Comment by stevensacks** [comment]
Done! Please merge. :)
