### ISSUE TITLE
Problems with installing beta via npm

### ISSUE THREAD

**Issue by DerKobe** [draft-js-plugins/draft-js-plugins#442]
I've locked the versions in my `package.json` to `2.0.0-beta.4` but I always end up with `beta1`. I had the same Problem with `beta.2`. Any ideas?

**Comment by DerKobe** [comment]
It was just to the fact that npm thinks `beta1` is newer than `beta.2` because of the lexical order.

**Comment by nikgraf** [comment]
argh, just noticed, will cut a new release soon, sorry for the mess
