### ISSUE TITLE
Graphical builder, drag-drop premade 'blocks'

### ISSUE THREAD

**Issue by dbx834** [draft-js-plugins/draft-js-plugins#447]
I've been following this project for some time now and I think it is coming along very well. With WYSIWYG editor and uploading plugins being added, the project will attain a mature status. Congratulations on the good work.

I've been wondering if it is possible to implement a graphical builder where one can drag-drop premade blocks, and each block can be configured.

Something like this - [Variant Builder](http://www.mediumra.re/pangaea/variant/builder.html)

Is it possible with draftjs? How?

**Comment by nikgraf** [comment]
It is certainly possible since you can handle drag & drop of blocks. I haven't worked with drag & drop at all so I can't tell you how so far 😄

**Comment by dbx834** [comment]
Okay, many thanks. Does your project have some kind of a forum or irc or something? I think these simple questions would be much better for forums.

Also, can the image upload plugin directly upload to S3?

**Comment by nikgraf** [comment]
Yep, there is a Slack channel in the official Draft.js Slack organisation. See more info here: https://github.com/draft-js-plugins/draft-js-plugins#discussion-and-support

Yes, I don't see any reason why it should not be possible …
