### ISSUE TITLE
Open Graph metadata snippets

### ISSUE THREAD

**Issue by MichaelSavin** [draft-js-plugins/draft-js-plugins#452]
I propose to add support for open graph snippets in draft-js-linkify-plugin

**Comment by sugarshin** [comment]
+1

**Comment by nikgraf** [comment]
@MichaelSavin what are Open Graph metadata snippets?

**Comment by MichaelSavin** [comment]
@nikgraf 
![image](https://cloud.githubusercontent.com/assets/1640229/19408563/d644c958-92d9-11e6-980f-68c5254dfd41.png)

**Comment by MichaelSavin** [comment]
It's snippet for links

**Comment by nikgraf** [comment]
@MichaelSavin how can you support them?

**Comment by MichaelSavin** [comment]
This should be a block component that can display links with a description, based on opengraph tags. I think we can make fetch request, parse and store the results. Although it is not a very nice solution.

**Comment by nikgraf** [comment]
ahh ok, does it make sense as a separate plugin? If yes, interested to contribute it? I'm bit too busy to build more

**Comment by MichaelSavin** [comment]
Ok, I'll try

**Comment by GromNaN** [comment]
Hi!
Are you sure this is possible without a server-side service to fetch the page ? (like [Iframely](http://iframely.com/) of [Embedly](http://embed.ly/)).
To my knowledge, CORS requests are very restricted.

**Comment by juliankrispel** [comment]
Closing this issue as part of a clean out. If you think this should remain open please let me know. Cheers
