### ISSUE TITLE
Paste into editor (cmd+v), delete..... shows very weird behavior

### ISSUE THREAD

**Issue by andzuck** [draft-js-plugins/draft-js-plugins#453]

**Comment by mzbac** [comment]
@andzuck could you please give us more details of this issue? what's the weird behaviour?

**Comment by andzuck** [comment]
Sure @mzbac ,

Go to https://www.draft-js-plugins.com/plugin/mention and paste "The quick brown fox jumps over the lazy dog" into the first simple editor.

After the sixth or seventh backspace, the cursor jumps back many places instead of just one. Let me know if you can reproduce this!

**Comment by mzbac** [comment]
@andzuck which browser you are using..I can't reproduce it on my chrome browser.

**Comment by andzuck** [comment]
I'm using Chrome as well on OSX. But today, after the same steps as above, it's actually perfectly fine. Quite strange!

Will let you know if this behavior comes up at all again.

**Comment by nikgraf** [comment]
@andzuck might have been fixer after a re-deploy of the docs in between
