### ISSUE TITLE
Issues with mentions on IE

### ISSUE THREAD

**Issue by davidlenthall** [draft-js-plugins/draft-js-plugins#456]
I'm having a few issues with using mentions on IE 11. When I've selected a mention from the suggestions list and it is added to my text, I can't use the arrow keys to navigate into it. If I then click directly into the name of the mention, I get this error:
"Could not complete the operation due to error 800a025e" at line 61 of "setDraftEditorSelection.js".

I've noticed that the examples page for mentions won't open in IE 11 due to it using ES6 code. (Fixed this for my build using babel-polyfill).

**Comment by andzuck** [comment]
Yep, also having problems with the plugin editor in IE11... any ideas?

**Comment by davidlenthall** [comment]
Managed to solve the issue. The "display: inline-block" style on the "draftJsMentionPlugin__mention__29BEd" was causing the issue. The style had to be overriden to remove this.

**Comment by mzbac** [comment]
@davidbyttow I think you can pass theme from config of mentionPlugin to override the default styles..
```js

const {
    mentionPrefix = '',
    theme = defaultTheme,
    positionSuggestions = defaultPositionSuggestions,
    mentionComponent,
    mentionTrigger = '@',
  } = config;
```

**Comment by davidlenthall** [comment]
Yeah, that's what I did to get round that.
