### ISSUE TITLE
Mentions: not work with Cyrillic

### ISSUE THREAD

**Issue by kortv** [draft-js-plugins/draft-js-plugins#457]
onSearchChange event does not occur when typing Cyrillic character after @

**Comment by ZozuliaDV** [comment]
in defaultRegExp.js add \u0400-\u0500
`exports.default = '[\\w\u4E00-\u9EFF\u3040-\u309F\u30A0-\u30FF\uAC00-\uD7A3\u3130-\u318F\u0400-\u0500]*';`

**Comment by nikgraf** [comment]
@kortv we just merged a PR and going to release a new version today 😄
