### ISSUE TITLE
linkify: Emit event with the link entity in order to fetch data from the url.

### ISSUE THREAD

**Issue by albertomr86** [draft-js-plugins/draft-js-plugins#458]
Hello.
Is there an event that trigger when a link entity is created?
I want to be aware of link in the component that include the editor, this is to fetch data from the link. (e.g. like Facebook does when share a link)
Thanks.

**Comment by adrianmc** [comment]
You could do something in the onChange function and check to see if the number of link entities have changed?

**Comment by albertomr86** [comment]
@adrianmc Thanks. I just can't figure out how to accomplish that, how to iterate over the link entities? Can you please provide me a quick example, at least pseudo-code?

**Comment by albertomr86** [comment]
`import linkifyIt from 'linkify-it';
import tlds from 'tlds';

const linkify = linkifyIt();
linkify.tlds(tlds);`

`_onChange = (editorState) => {
   editorState.getCurrentContent().getBlockMap().forEach((block) => {
      const links = linkify.match(block.get('text'));

      if (typeof links !== 'undefined' && links !== null) {
        for (let i = 0; i < links.length; i++) {
          THIS_IS_THE_LINK(links[i].url);  // could be more than one
        }
      }
    });

    this.setState({editorState});
  };`

**Comment by digital-flowers** [comment]
sorry but the most simple thing in any editor is setting and getting data and i think these should be mentioned in the documentation with samples but over all amazing plugin keep it up :)
