### ISSUE TITLE
draft-js-plugins.com website down in IE11

### ISSUE THREAD

**Issue by andzuck** [draft-js-plugins/draft-js-plugins#459]
If you go to https://www.draft-js-plugins.com/ in Internet Explorer 11, it simply says 
"Page not Found :("

An error that's thrown is "Object doesn't support property or method 'startsWith'"

What's interesting is that if you go to the website on Google Chrome (mac), that error doesn't appear, but the following error does: "Cannot read property 'replaceChild' of null"

**Comment by Grsmto** [comment]
There is no polyfill for the `startsWith` method of `String`.
They need to add `core-js/shim` for example https://github.com/zloirock/core-js#basic
Or Babel polyfill.

**Comment by mzbac** [comment]
@Grsmto thanks for your solution, could you create RP for this?

**Comment by Grsmto** [comment]
@mzbac done!
