### ISSUE TITLE
Giphy Plugin

### ISSUE THREAD

**Issue by nikgraf** [draft-js-plugins/draft-js-plugins#46]
A plugin which allows to add a gif block.

**Comment by bashkos** [comment]
hmmm... Recently i created `react-giphy-select` package. Maybe we can use it?
https://github.com/WEACOMRU/react-giphy-select

**Comment by nikgraf** [comment]
Would be cool, I just started to close outdated issues 😄

**Comment by albertomr86** [comment]
Hi guys. 
Sorry to interrupt in a closed issue. 
Recently I created a similar plugin, for a project that I will be launching soon: https://github.com/jimmycodesocial/draft-js-giphy-plugin
