### ISSUE TITLE
[draft-js-plugins-editor] Doesn't work on IE10

### ISSUE THREAD

**Issue by Grsmto** [draft-js-plugins/draft-js-plugins#460]
Hi! First, thanks for the good work!

Error reported:
`SCRIPT5007: Unable to get property 'plugins' of undefined or null reference `
This error reference this line: https://github.com/draft-js-plugins/draft-js-plugins/blob/c867cf8c606f5cc16b0cb7e512b21fc40e935683/draft-js-plugins-editor/src/Editor/index.js#L202

After digging into this, I figured out it was probably coming from the Babel version used to transpile the plugin (I use the latest version): https://github.com/babel/babel/pull/3527

I'll keep going on debugging and submit a PR if I find. But if you have an idea..go ahead!

Thanks.

**Comment by Grsmto** [comment]
Realised this issue was fixed in v2 beta. Closing then!

**Comment by nikgraf** [comment]
cool, thx for investigating
