### ISSUE TITLE
Is there a way to show the toolbar plugin only sometimes?

### ISSUE THREAD

**Issue by terencechow** [draft-js-plugins/draft-js-plugins#464]
I have multiple fields on my page. They all render a draft js editor because I am doing word count validations, etc on them.

However some of my fields require the draft-js-toolbar-plugin and some do not. (Think some are rich text, and others just need the validation benefits mentioned above).

My problem is I don't know how to show the toolbar-plugin only on some fields and not on others. 

I tried using `<Editor plugins=[createToolbarPlugin()]/>` on some and leaving plugins to be blank on others but this doesn't work. 

Is what I'm requiring possible?

**Comment by terencechow** [comment]
Nevermind. I was using the same plugin across editors.

For more info:
https://github.com/draft-js-plugins/draft-js-plugins/blob/master/FAQ.md#can-i-use-the-same-plugin-for-multiple-plugin-editors

**Comment by nikgraf** [comment]
Glad you figured it out 😊
