### ISSUE TITLE
The position of the suggestions popup on small screens

### ISSUE THREAD

**Issue by tomkelsey** [draft-js-plugins/draft-js-plugins#465]
Hi,

Great job with this plugin - I'm using it on a live site atm and people love the ease of adding in emojis and @mentioning people 👍 

I noticed that on small screens or mobiles it looks like the suggestions popup doesn't factor in whether or not it'll overflow off the screen.

![screen shot 2016-09-29 at 11 37 14](https://cloud.githubusercontent.com/assets/14311327/18950743/45b909d2-8639-11e6-9e86-20d8d786442f.png)

I looked through some previous issues and it seemed like maybe fixing something else removed functionality that would have automatically repositioned the popup?

I was just wondering if there were any plans to add this back in?

Thanks :)

**Comment by mzbac** [comment]
Hi @tomkelsey I think you can write your own positionSuggestions and pass it as part of config to mention plugin.. something likes below code example.. 

```js
const positionSuggestions = ({ state, props }) => {
  let transform;
  let transition;

  if (state.isActive & props.suggestions.size > 0) {
    transform = 'scaleY(1)';
    transition = 'all 0.25s cubic-bezier(.3,1.2,.2,1)';
  } else if (state.isActive) {
    transform = 'scaleY(0)';
    transition = 'all 0.25s cubic-bezier(.3,1,.2,1)';
  }

  return {
    transform,
    transition,
  };
};

const mentionPlugin = createMentionPlugin({
  theme: mentionsStyles,
  positionSuggestions,
  mentionPrefix: '@',
});
```

**Comment by nikgraf** [comment]
@tomkelsey Let me know if this solved the issue for you.
