### ISSUE TITLE
Mentions: update to 'suggestions' prop while dropdown is closed and suggestions is empty doesn't trigger dropdown reopen

### ISSUE THREAD

**Issue by maxhr** [draft-js-plugins/draft-js-plugins#469]
This can be reproduced in the Remote Data Mention Example:
https://www.draft-js-plugins.com/plugin/mention

Type `@m` fast, before remote fetch returns.
`setState` is called, `suggestions` prop is updated, but the dropdown opens only after `editorState` changes somehow.

This happens because `componentWillReceiveProps`of `MentionSuggestions` checks for empty suggestions and closes the dropdown:
https://github.com/draft-js-plugins/draft-js-plugins/blob/master/draft-js-mention-plugin/src/MentionSuggestions/index.js#L40

However triggering openDropdown happens only inside `onEditorStateChange` 
https://github.com/draft-js-plugins/draft-js-plugins/blob/master/draft-js-mention-plugin/src/MentionSuggestions/index.js#L84
which doesn't get called until some change happens inside the editor.

**Comment by nikgraf** [comment]
Thanks for the detailed bug report. Would you be interested to submit a fix? I'm quite busy with other plugins right now.

**Comment by tal-moshayov** [comment]
+1 any remedy?

**Comment by jameskraus** [comment]
Is there any particular reason why the MentionSuggestions class closes itself if there are no suggestions? Can that just be disabled?

**Comment by nikgraf** [comment]
Just merged this PR which should fix the issue: https://github.com/draft-js-plugins/draft-js-plugins/pull/659
