### ISSUE TITLE
Mentions: Cannot break out of mentions entity using spacebar while editing it

### ISSUE THREAD

**Issue by tarun-dugar** [draft-js-plugins/draft-js-plugins#475]
I set 'entityMutability' to 'MUTABLE' and tried editing a selected mentions entity by deleting some characters. However, after deleting some characters I am unable to move the cursor/caret outside the mentions entity using a spacebar.

Example:
1. I selected 'Matthew Russell' from the mentions dropdown
2. Deleted characters 'ell'
3. Now, pressing spacebar doesn't help in moving caret out of the entity

![image](https://cloud.githubusercontent.com/assets/8099609/19218247/c3d2bf26-8e12-11e6-9e93-c5a297c0e87d.png)

**Comment by nikgraf** [comment]
@tarun-dugar ouch, that's a bug then. Interested to find the issue and submit a fix?

**Comment by tarun-dugar** [comment]
@nikgraf of course! give me some time I'll submit a PR.

**Comment by tarun-dugar** [comment]
@nikgraf I had a doubt: In `MUTABLE` mode is adding new characters to the mentions entity allowed? Or only deletion is allowed?

**Comment by freedomlang** [comment]
@tarun-dugar I'll close this, cause can not reproduce it at the latest version. Please let us know if you still have this issue at the latest version, fell free to reopen it or create an new issue
