### ISSUE TITLE
Sidebar plugin WIP

### ISSUE THREAD

**Issue by Nihaux** [draft-js-plugins/draft-js-plugins#484]
Hello I am working on a sidebar plugin to insert atomic blocks like embeds, images and others.
It is a work in progress. (a la medium).
You can find the branch here: https://github.com/Nihaux/draft-js-plugins/tree/sidebar-plugin/draft-js-sidebar-plugin
You can test it by building the doc and go to http://localhost:3000/plugin/sidebar
Attached a screenshot of the doc (for the lazy ones ;) )
Don't hesitate to give me your thoughts, how to make it better, etc..
[sidebar.pdf](https://github.com/draft-js-plugins/draft-js-plugins/files/527639/sidebar.pdf)

**Comment by mzbac** [comment]
@Nihaux that's cool idea for have sidebar plugin to insert custom component. but beware of the way you creating entity data is about to change on draftjs new release..https://github.com/facebook/draft-js/pull/376

**Comment by nikgraf** [comment]
@mzbac good point, I guess we need to migrate a couple plugins then …
