### ISSUE TITLE
Do we have any option for show all emoji

### ISSUE THREAD

**Issue by haunguyen90** [draft-js-plugins/draft-js-plugins#485]
I need a button to show all emoji same as iMessage
![image](https://cloud.githubusercontent.com/assets/8245883/19364802/e6f97120-91b9-11e6-9034-9babbbfe2151.png)

Do we have any option for show all emoji like that ?

**Comment by mzbac** [comment]
@haunguyen90, emoji list came from emojione lib..

**Comment by nikgraf** [comment]
@haunguyen90 yep, if you build a drop down that has some kind of dropdown like this I would be happy to merge it into the plugin 😄

**Comment by maratgaip** [comment]
@haunguyen90 @EllisShen @nikgraf i built something like that customizing sticker plugin. i can do for emoji too and pull request... 
<img width="556" alt="screen shot 2016-11-01 at 3 28 10 pm" src="https://cloud.githubusercontent.com/assets/3010387/19910068/06f6efec-a048-11e6-9907-5f84ea916243.png">

**Comment by haunguyen90** [comment]
@maratgaip Really nice

**Comment by jrock17** [comment]
@maratgaip did you ever make a PR for this? Thanks!
