### ISSUE TITLE
[draft-js-mention-plugin] error using mentionComponent without props.children

### ISSUE THREAD

**Issue by YoonjiJang** [draft-js-plugins/draft-js-plugins#487]
There's a bug using the `mentionComponent` prop. See https://drive.google.com/open?id=0B3Ftrnd9yXx-QzlrcExxaGlCMzg (added two mentions and backspaced on current draft-js-plugins website custom component example).

This seems to happen whenever `mentionComponent`'s descendants aren't a draft editor node. For example, everything works fine if I have `props.children` (which is a `DraftEditorLeaf` component) as the only child of `mentionComponent`.

Is there a way to go around this problem while still allowing the mention component to be replaced?

**Comment by nikgraf** [comment]
hmmmm, that's an interesting bug. Unfortunately I don't have an answer for you. 😞 

Do you have time to investigate a bit? If not we probably should drop the `mentionComponent`.

**Comment by ismyrnow** [comment]
I'm encountering the same issue. In my case, I just need to add a custom class to the mention component so I could override styling of it. I did by passing a theme object to the plugin options, and changing the mention class to just 'mention', instead of the compiled class name I was seeing.

**Comment by dotansimha** [comment]
Same issue here. Backspace breaks the custom `mentionComponent`
