### ISSUE TITLE
Allow for refreshing editorState

### ISSUE THREAD

**Issue by MarkNijhof** [draft-js-plugins/draft-js-plugins#488]
In order to load new editorState after the pluginEditor has mounted we need a way to decorate the new editorState with the plugins loaded in the editor. If you just change the editorState in the props of the pluginEditor then it is not decorated atm and will load the editorState without the plugins applied. 

I have experimented with redecorating it in the componentWillRecieveProps but because of the cycle state.editorState -> pluginEditor.props.editorState -> onChange(editorState) -> this.setState(editorState) it becomes an unending loop.

My solution is to change:

```
  componentWillMount() {
    const compositeDecorator = createCompositeDecorator(
      this.resolveDecorators(),
      this.getEditorState,
      this.onChange);
    const editorState = EditorState.set(this.props.editorState, { decorator: compositeDecorator });
    this.onChange(moveSelectionToEnd(editorState));
  }
```

into:

```
    componentWillMount() {
        const editorState = this.decorateEditorState(this.props.editorState);
        this.onChange(moveSelectionToEnd(editorState));
    }
    decorateEditorState(editorState) {
        const compositeDecorator = createCompositeDecorator(
            this.resolveDecorators(),
            this.getEditorState,
            this.onChange);
        return EditorState.set(editorState, { decorator: compositeDecorator });
    }
```

So that in the component using the pluginEditor I can create/load a new editorState then decorate it with the plugins from the pluginEditor and put it in the props. For example like this:

```
    loadAst(ast) {
        const contentState = importer(ast);
        const editorState = EditorState.createWithContent(contentState);
        const decoratedEditorState = this.refs.pluginEditor.decorateEditorState(editorState);

        this.setState({
            editorState: decoratedEditorState
        });
    }
```

The downside of this is that you need a reference to the pluginEditor, but I don't see only one way how this can be prevented and that is if we can "discover" what plugins the editorState is decorated with and if that doesn't match the loaded plugins in the pluginEditor to re-decorate the editorState with the missing plugins.

If we can achieve that then this will also enable the loading of new plugins relatively easily as on each componentWillReceiveProps you would check if all needed plugins are loaded and load the missing ones. Maybe we can even unload plugins not loaded in the pluginEditor anymore. completely solving both this issue and #42 

I can see in the editorState that "decorator" is null so it should be easy to actually solve this in the componentWillReceiveProps the first time, but if we can add some meta-data that shows what plugins are loaded then we can do the loading and unloading automatically based on that list.

This also works (but doesn't feel right to peak inside editorState like this):

```
    componentWillReceiveProps(nextProps) {
        const decorator = nextProps.editorState._immutable.get("decorator");
        if (typeof decorator !== "undefined" && decorator === null) {
            const editorState = this.decorateEditorState(nextProps.editorState);
            this.onChange(moveSelectionToEnd(editorState));
        }
    }
```

**Comment by MarkNijhof** [comment]
Actually decorators are exposed using editorState.getDecorator()
```
    componentWillReceiveProps(nextProps) {
        const decorator = nextProps.editorState.getDecorator();
        if (typeof decorator !== "undefined" && decorator === null) {
            const editorState = this.decorateEditorState(nextProps.editorState);
            this.onChange(moveSelectionToEnd(editorState));
        }
    }
```

**Comment by MarkNijhof** [comment]
Actually this is working: Biggest pain is how to compare the plugins in the componentWillReceiveProps as now I am just doing a count which is not good enough
```
    constructor(props) {
        super(props);

        // attach proxy methods like `focus` or `blur`
        for (const method of proxies) {
            this[method] = (...args) => (
                this.editor[method](...args)
            );
        }

        this.state = {};
    }

    componentWillMount() {
        this.initPlugins();
        this.decorateEditorState(this.props.editorState);
    }

    componentWillReceiveProps(nextProps) {
        const decorator = nextProps.editorState.getDecorator();
        if (this.props.plugins.length !== nextProps.plugins.length) {
            setTimeout(function() {
                this.unloadPlugins();
                this.initPlugins();
                this.decorateEditorState(nextProps.editorState);
            }.bind(this), 10);
            return;
        }

        if (typeof decorator !== "undefined" && decorator === null) {
            this.decorateEditorState(nextProps.editorState);
            return;
        }
    }

    componentWillUnmount() {
        this.unloadPlugins();
    }

    decorateEditorState(editorState) {
        const compositeDecorator = createCompositeDecorator(
            this.resolveDecorators(),
            this.getEditorState,
            this.onChange);
        const decoratedEditorState = EditorState.set(editorState, { decorator: compositeDecorator });
        this.onChange(moveSelectionToEnd(decoratedEditorState));
    }

    initPlugins() {
        const plugins = [this.props, ...this.resolvePlugins()];

        for (const plugin of plugins) {
            if (typeof plugin.initialize !== 'function') continue;
            plugin.initialize(this.getPluginMethods());
        }
    }

    unloadPlugins() {
        this.resolvePlugins().forEach((plugin) => {
            if (plugin.willUnmount) {
                plugin.willUnmount({
                    getEditorState: this.getEditorState,
                    setEditorState: this.onChange
                });
            }
        });
    }
```

**Comment by mzbac** [comment]
@MarkNijhof  can you try to use
```js
EditorState.push(
  editorState: EditorState,
  contentState: ContentState,
  changeType: EditorChangeType
): EditorState
``` 
I think that method will keep the decorators..

**Comment by juliankrispel** [comment]
@MarkNijhof did the rejig of that pr get anywhere? If you like I'm happy to chat over slack :-)

For now, closing this issue as part of a clean out. If you think this should remain open please let me know. Cheers
