### ISSUE TITLE
RichText Editing Plugin

### ISSUE THREAD

**Issue by nikgraf** [draft-js-plugins/draft-js-plugins#49]
@bkniffler did a great job @ https://github.com/bkniffler/draft-wysiwyg

Something similar to this or Medium would be great. Double click (ideally also double tap) triggers a rich text editing tool. I suggest to visually separate text transformation from block transformation so people can get a feeling of the editing scope.

**Comment by jasonphillips** [comment]
The medium-style bar is something I look forward to using for some cases, but I've just completed a different approach that I find convenient for rendering formatting buttons on demand with very little complexity.

https://github.com/jasonphillips/draft-js-richbuttons-plugin

As you'll see in the README, this plugin attaches the `RichUtils` capabilities to your editor instance (and key bindings) then provides a set of named components in a manner similar to the Counter plugin. So after instantiating it you can grab the ones you need:

```js
const { ItalicButton, BoldButton, OLButton } = richButtonsPlugin;
```

And then you may render these wherever desired.

```html
<div className="myBar">
  <ItalicButton/> <BoldButton/> <OLButton/>
</div>
```

It also will pass the needed props down to any direct child of these components, allowing you to define your own stateless way of rendering the buttons:

```js
// for a style button with a font-awesome icon
const MyIconButton = ({iconName, toggleInlineStyle, isActive, label, inlineStyle }) =>
  <a onClick={toggleInlineStyle}>
    <span
      className={`fa fa-${iconName}`}
      toolTip={label}
      style={{ color: isActive ? '#000' : '#777' }}
    />
  </a>;
```

Which would be used this way:

```js
<BoldButton>
  <MyIconButton iconName="bold"/>
</BoldButton>
<ItalicButton>
  <MyIconButton iconName="italic"/>
</ItalicButton>
```

Feedback welcome.

**Comment by jasonphillips** [comment]
(my plugin not yet published to npm though I'll be pushing it there in next day or so unless feedback prompts immediate changes  )

**Comment by jasonphillips** [comment]
Live demo now here: https://jasonphillips.github.io/draft-js-richbuttons-plugin/

**Comment by nikgraf** [comment]
@jasonphillips this is really really good stuff! 👌

Interested to add it here https://github.com/draft-js-plugins/draft-js-plugins/blob/master/README.md#built-by-the-community and https://github.com/nikgraf/awesome-draft-js#projects-on-top-of-draftjs?

I just went a bit through the code. The tests are nice & help a lot to get a better understanding. Right now the only feedback that comes to my mind is to make the demo page a bit fancier. I believe it will have impact on people's decision to use your plugin 😊

**Comment by jasonphillips** [comment]
Thanks! I'm all in favor of adding it to the community plugin lists (if you'd prefer me to initiate the PRs for that, let me know). And on the demo page, agreed that it could be improved. One thing that really stands out about `draft-js-plugins` itself is the excellent demo / documentation site; mine won't be up to that level but I intend to circle back and improve its presentation soon.

**Comment by nikgraf** [comment]
Thanks @jasonphillips 🙌 

Yeah, PRs to both repos would be great 😄
You just triggered a new idea: What would be really cool is a boilerplate for draft-js-plugins with nice docs out of the box …

**Comment by bkniffler** [comment]
Hey, this is really cool @jasonphillips! A fixed toolbar mode would be very nice to have for the toolbar plugin, and shouldn't be to hard to implement, as the toolbar plugin is more of a toolbar manager that could be decoupled from the way how a toolbar looks. It is necessary though to react to what kind of element/block is currently active, think about the MS Word ribbon toolbar which adds options if you select the table.

So ideally we'd have the toolbar-manager that manages active actions (text actions like bold, h1, etc. as well as individual block actions for focused blocks that are defined via the toolbar decorator) and a fixed-toolbar / air-toolbar plugin that stupidly renders actions that it gets from the manager. 

This would allow users to swap toolbar modes whenever they like or use different modes simultaneously.

**Comment by nikgraf** [comment]
We have this now with the two different toolbar plugins!
