### ISSUE TITLE
Cannot render stickers from raw content state 

### ISSUE THREAD

**Issue by timschambers** [draft-js-plugins/draft-js-plugins#491]
Howdy,

First, thank you all for the great work on these set of plugins. They're really helping to reduce my pain points with draft-js.

Second,  I'm running into a problem where ContentStates that are "convertFromRaw" and stored as JS strings, can't render their stickers. Instead, any sticker blockType throws an 'Invariant' exception and does not show up in the editor. 

I am using draft-js-plugins-v2.0.0@beta5, draft-js-0.9.1, and React@15.3.2.

All stickers run into this problem, while other block types, like text, render perfectly fine.

I have attached screenshots of the debug output, particularly the line where it fails:

<img width="514" alt="screen shot 2016-10-17 at 9 29 20 am" src="https://cloud.githubusercontent.com/assets/1759595/19439630/d6756472-944c-11e6-8c19-57d2012b1e07.png">

The getEntityAt(0) returns a `null` that is passed into Entity.get, causing the error shown below.

<img width="1157" alt="screen shot 2016-10-17 at 9 34 34 am" src="https://cloud.githubusercontent.com/assets/1759595/19439684/077c1aca-944d-11e6-9d79-548edb5ced2f.png">

And this is JSON of a sample ContentState being loaded, which throws the 'Invariant' exceptions:

``` js
{
    "entityMap": {
        "0": {
            "type": "sticker",
            "mutability": "IMMUTABLE",
            "data": {
                "id": "/static/media/images.97b53447.jpeg"
            }
        },
        "1": {
            "type": "sticker",
            "mutability": "IMMUTABLE",
            "data": {
                "id": "/static/media/plague.2d0a9da3.gif"
            }
        }
    },
    "blocks": [{
        "key": "7m54a",
        "text": "",
        "type": "sticker",
        "depth": 0,
        "inlineStyleRanges": [],
        "entityRanges": [{
            "offset": 0,
            "length": 0,
            "key": 0
        }],
        "data": {}
    }, {
        "key": "fa7d4",
        "text": "",
        "type": "sticker",
        "depth": 0,
        "inlineStyleRanges": [],
        "entityRanges": [{
            "offset": 0,
            "length": 0,
            "key": 1
        }],
        "data": {}
    }, {
        "key": "f6o38",
        "text": "",
        "type": "unstyled",
        "depth": 0,
        "inlineStyleRanges": [],
        "entityRanges": [],
        "data": {}
    }]
}
```

Would anyone have an idea of what I'm doing wrong here?

**Comment by mzbac** [comment]
Feels like  convert from raw is from different draft js instance than your plugin editor instance...

**Comment by timschambers** [comment]
Oh that's interesting. 

```js
import Editor from 'draft-js-plugins-editor';
import { EditorState, convertFromRaw, convertToRaw, Entity } from 'draft-js';
import createStickerPlugin from 'draft-js-sticker-plugin'; 
```

Is what I'm doing; am I mistaken?

**Comment by mzbac** [comment]
@timschambers  can you show me the codes of your conversion from rawContentState to editorState?

**Comment by timschambers** [comment]
Of course!

```js
this.setState({
                editorState: EditorState.createWithContent(
                    convertFromRaw(json)
                ),
            });
```

**Comment by mzbac** [comment]
@timschambers  the code looks fine, no sure what's the cause.  but I suspect that getRaw function.  maybe you can try pass on change callback from parent component then in you child editor component pass the converted contentstate through onchange call back..
```js
onChange(editorState) {
    this.setState({ editorState }, () => this.props.onChange(convertToRaw(editorState.getCurrentContent())));
  }

```

**Comment by timschambers** [comment]
Hey, I tried both methods, got rid of getRaw, to no avail. Still getting draftkey entity invariant errors.

If the content that's going is not malformed, should I fork the plugin and fix the underlying bug?

**Comment by mzbac** [comment]
@timschambers sure, if there is a bug of plugin, we are PR welcome.. but still feel somehow in your code base you have multiple copies of 'draft-js'

**Comment by matthiasn** [comment]
Hi, I had the same issue and I was able to fix it by using a non-empty string as the block content for the sticker, see the PR. Without this change, I would always get the `Uncaught Invariant Violation: Unknown DraftEntity key.` error message.

**Comment by nikgraf** [comment]
Thanks to @matthiasn who fixed the issue here: https://github.com/draft-js-plugins/draft-js-plugins/pull/721

**Comment by nikgraf** [comment]
Let me know if this issue still occurs …
