### ISSUE TITLE
Having multiple Editor instances on the same page with mention plugin results in weird behaviour

### ISSUE THREAD

**Issue by GaborLeskoFlach** [draft-js-plugins/draft-js-plugins#492]
Great plugins for Draft, thanks for all the good work you guys put in!
I'm having an issue with putting multiple instances of Draft Editor on the same page. In my case the same component is being used and injected into the page multiple times. (it's like a Social wall feature when users can comment on stuff, then reply and comment more, you get the idea) When typing something in the Draft Editor on the top of the page the Mention plugin appears on the bottom for the last placed Editor.

The only way to get around this at the moment is to have separate components to be injected into the page like you do here: https://www.draft-js-plugins.com/plugin/mention
Unfortunately this is not a solution for me because there can be X number of Draft Editor components on the page. Hope this makes sense. Any idea why this is happening?

Environment : Visual Studio Code Editor
Typescript with React.

**Comment by GaborLeskoFlach** [comment]
Has been fixed in here. I've just missed it
https://github.com/draft-js-plugins/draft-js-plugins/issues/298

**Comment by nikgraf** [comment]
Glad you got it to work!
