### ISSUE TITLE
Mentions to get data from external API

### ISSUE THREAD

**Issue by GaborLeskoFlach** [draft-js-plugins/draft-js-plugins#493]
Hi!
I have a requirement to provide the Mentions Plugin with data being fetch from and External API. I was trying to implement this based on the Remote Data Mention example you guys have provided and run into an issue which is causing me a headache and I can't figure out for the love of god why it's happening and how to resolve it. I'm happy to provide further info if required. I'm just wondering if you've seen anything like this. This doesn't happen when using the static mention.json file as data source. It's probably something to do with the fact that when the user typing after each char a remove service call is initiated...or something along this line..not sure. Any help would be appreciated.

This is the error I'm getting:
![image](https://cloud.githubusercontent.com/assets/20980950/19464563/15738fbc-9549-11e6-89c4-a2b1f7774e57.png)

and this is roughly how I've implemented the MentionSearch

![image](https://cloud.githubusercontent.com/assets/20980950/19464578/34cb0066-9549-11e6-86ed-58dabc11ba91.png)

Environment: Visual Studio Code Editor
Typescript and React
For State management I'm using MobX
Getting the data from the external WebAPI I use fetch.

**Comment by Zhouzi** [comment]
The error in the console suggests that there are two suggestions with the same key. Could you have a look at the web api's response to make sure that there are no duplicates?

**Comment by GaborLeskoFlach** [comment]
Yes, you are correct @Zhouzi , it's my bad, the getMentions method kept pushing the results into the same array hence I got the duplicates. Solution was to clean this array as per below screenshot.
![image](https://cloud.githubusercontent.com/assets/20980950/19629834/24d854c2-99c9-11e6-8add-8149187cb6a8.png)

Thanks for the help

**Comment by nikgraf** [comment]
@GaborLeskoFlach glad you figured it out :)
