### ISSUE TITLE
Release new version of the draft-js-pllugin-editor

### ISSUE THREAD

**Issue by Hirurg103** [draft-js-plugins/draft-js-plugins#498]
In IE <= 10 we get error

```Unable to get value of the property 'plugins': object is null or undefined```

The old compiled code uses `Object.getPrototypeOf` which doesn't work correctly in IE. See [babel issue](https://github.com/babel/babel/issues/3041)

When I build the master version of the plugin I can see that the compiled code handles inheritance normally: `PluginEditor.__proto__ || Object.getPrototypeOf(PluginEditor)`

We had to add code which overrides Object.getPrototypeOf to get the plugin working in IE.

Could you release the new version please? Thanks

**Comment by nikgraf** [comment]
@Hirurg103 which version of the editor do you use?

**Comment by Hirurg103** [comment]
@nikgraf ^2.0.0-beta1

**Comment by nikgraf** [comment]
@Hirurg103 can you upgrade to `2.0.0-beta5`. Might be fixed there.

**Comment by Hirurg103** [comment]
Hello @nikgraf. It fixed the issue. Thanks a lot!

**Comment by tedlin182** [comment]
So I upgraded to `beta5` which did resolve the IE 10 issue above for me, but when I click into the editor and hit "Enter" for a carriage return, it gives me this error in all browsers:

`Uncaught Error: Cannot set unknown key "data" on ContentBlock(…)`

Thoughts?

**Comment by nikgraf** [comment]
@tedlin182 not really, what kind of plugins do you use?
