### ISSUE TITLE
When deleting an Emoji I get: Invariant Violation: Unknown DraftEntity key

### ISSUE THREAD

**Issue by cristiandan** [draft-js-plugins/draft-js-plugins#500]
When I press **backspace** to delete an emoji I always get: Invariant Violation: Unknown DraftEntity key. I'm using v. beta5
![pasted image at 2016_10_21 04_39 pm](https://cloud.githubusercontent.com/assets/7952216/19604869/d27bda2e-97bf-11e6-85cd-10455c9840b4.png)

I found [this](https://github.com/facebook/draft-js/issues/250) issue on draft-js

I've tried other versions and it seems that v. beta1 is working well.

**Comment by nikgraf** [comment]
@cristiandan I'm currently working on preparing 2.0. If you have time to investigate and submit a PR that would be awesome. Somewhere in the most recent betas we updated the EmojiPlugins to use the emojione package instead of copying code from there. We might have missed something on the way …

**Comment by Arinteck** [comment]
Look [this](https://github.com/draft-js-plugins/draft-js-plugins/issues/110) link, seems it can help you.

**Comment by smeijer** [comment]
Same issue here; but beta1 was throwing some other issues. Probably because of breaking changes between the beta9 and beta1 though. Is the 2.0 release making any progress?

**Comment by beeant** [comment]
the same thing happens for me on image plugin.
The solution, for now, seems to be wrapping the `<img />` with `<div />`, as it is mentioned here: https://github.com/facebook/draft-js/issues/1191#event-1125944192

**Comment by Shadowman4205** [comment]
@beeant 
How wrapp img with div? i tried this 

> <div style={{width:100+"px"}}><img src={props.src} style={{width:"100%"}} /></div>

but still the same, gettin error on Enter press

**Comment by MarksCode** [comment]
@Shadowman4205 ever figure it out?

**Comment by andpor** [comment]
I get this error with Mention plugin and I am not even adding a mention when it happens. This is not stable or production ready...
