### ISSUE TITLE
Server rendering question

### ISSUE THREAD

**Issue by Antherkiv** [draft-js-plugins/draft-js-plugins#508]
Hello, I'm trying in my sparse time several plugins and I'm playing with server rendering (this going to be serious near) I found really hard to dealing  with the plugins that are using css in the server side context and I going to begin to move to js style instead (I'm thinking in aphrodite), I want to ask if you want to get involved or at least you are interesting in a pull request?

Best regards (P.D. sorry I'm not a native speaker).

**Comment by juliankrispel** [comment]
Totally interested in a pr and would be happy to help :) but I'm guessing you'll have lost interest because no one replied at the time :/ - sorry about that

Closing this issue as part of a clean out. If you think this should remain open please let me know. Cheers
