### ISSUE TITLE
[Mentions] Improvements

### ISSUE THREAD

**Issue by nikgraf** [draft-js-plugins/draft-js-plugins#51]
- [x] let the user decide between immutable, segmented or mutable
- [x] animate the popover
- [x] improve colours
- [x] use handle & name
- [x] remote example
- [x] themed example with a static list below the editor
- [x] proper naming 
- [x] marketing for mobile optimization (test on mobile device)
- [x] fix aria tag issue for editor
- [x] fix scrolling issue
- [x] option to keep @
- [x] add initialize callback to editor
- [x] update homepage example
- [x] properly align the box
- [x] make it mobile ready (check touch)
- [x] use flexbox
- [x] switch to non immutable classname list
- [x] allow to take a promise for mentions data as well
- [x] make sure mentions popover stay at the same position
- [x] custom key handling for dropdown (@nikgraf working on it)
- [x] make sure in case no link exists it does not become an Anchor tag
- [x] add profilepics/icons
- [x] only show/use images if all mentions have images
- [x] use unicorn name & unicorn profile pictures for the the dataset
- [x] use an algorithm to filter for name - see [ComboBox algorithm of Belle](https://github.com/nikgraf/belle/blob/master/src/components/ComboBox.js#L122)
- [x] don't add a space at the end if the mention is somewhere in between
- [x] when you type too far ahead so no result shows up and you hit backspace the dropdown should appear again (only happens when somewhere in between text)
- [x] allow to provide an extended config
- [x] close the dropdown when clicking somewhere outside of it and loosing focus
- [x] close dropdown when the selection moves away
- [x] fix onclick on the mention option (doesn't work right now)
- [x] add active state for the mention option

**Comment by mjrussell** [comment]
- [ ] Undoing a mention places the cursor in a weird location

**Comment by nikgraf** [comment]
- [ ] inserting an mention before another mention leads to weird inserting behavior

**Comment by nikgraf** [comment]
- [ ] avoid height changes (right now the text is jumping)

**Comment by jpuri** [comment]
For mentions( and also other plugins) I think would be nicer to have a new block for each mention in the editor.

**Comment by nikgraf** [comment]
Hmmm, the idea here was to allow sentences and include people. Works well like this on Twitter, Facebook and even Github.

"Thanks for your great PR @jpuri " (not a new block)

vs

"Thanks for your great PR
@jpuri " (new block)

:smile:

**Comment by jpuri** [comment]
I think a new block has nothing to do with newline.

**Comment by mjrussell** [comment]
Is the newline issue just because you are typically rendering a div? Would using `display: inline` (or spans) solve the issue?

**Comment by nikgraf** [comment]
good point, yes that probably would work.

What's the benefit of a block over a strategy though?

**Comment by tleunen** [comment]
Would it be possible to have an option to display the mentions below the text, or above the text?
