### ISSUE TITLE
inline-toolbar-plugin npm package name is incorrect

### ISSUE THREAD

**Issue by mkampik** [draft-js-plugins/draft-js-plugins#510]
In the `package.json` and documentation, the inline-toolbar-plugin is referred to as "[draft-js-inline-toolbar-plugin](https://github.com/draft-js-plugins/draft-js-plugins/blob/master/draft-js-inline-toolbar-plugin/package.json#L2)". However, the actual package name is "**react**-draft-js-inline-toolbar-plugin".

See: https://www.npmjs.com/package/react-draft-js-inline-toolbar-plugin

**Comment by Nihaux** [comment]
It seems to be an unofficial release by https://www.npmjs.com/~nomad (while waiting for the official release ?). I guess he didn't want to reserve the official name.
For those who wants to use the latest feature of master, there is always this solution: https://github.com/draft-js-plugins/draft-js-plugins/blob/master/CONTRIBUTING.md#using-your-own-fork-in-your-own-development
