### ISSUE TITLE
[request] Please create release tags

### ISSUE THREAD

**Issue by gfx** [draft-js-plugins/draft-js-plugins#512]
I think release tags are inevitable for OSS.

**Comment by nikgraf** [comment]
Good suggestion, I need to think about how do manage this, but probably split up all plugins into different repos and then can do release tags. Btw all plugins have an internal CHANGELOG.md where you can follow the changes from each release.

**Comment by MarkNijhof** [comment]
Yeah CHANGELOG is great for people, tags are great for computers. 

Personally I use a TAG file with the content v0.0.1 and have the following script to update the version:

```
#!/bin/bash
new_tag="v`perl -pe 's/^v((\d+\.)*)(\d+)(.*)$/$1.($3+1).$4/e' < $1`"
echo "$new_tag" > $1

git add $1
git commit -m "New tag $new_tag"
git push
git tag $new_tag
git push --tags

echo "New tag created $new_tag"
```
Usage: `./increase_version.sh TAG`

**Comment by MarkNijhof** [comment]
Btw this only updates the minor version, you want to increase the major you just fix the TAG file manually :)

**Comment by gfx** [comment]
> split up all plugins into different repos

Seems really great; I can't wait it 👍

**Comment by f0rr0** [comment]
Might want to check out https://github.com/lerna/lerna
