### ISSUE TITLE
Editor slows down as text length increases

### ISSUE THREAD

**Issue by spherop** [draft-js-plugins/draft-js-plugins#517]
With long blocks of text, upwards of several thousand words, the editor becomes very slow. This does not happen with the base version of draft-js.

We're having this issue in our product using draft-js-plugins editor.  I tested the problem indeed exists on the home page example here. If you paste in a long text, let's say 10,000 words. The editor becomes noticeably slow. 

Try typing into the middle of body of this long text and you should see that the text only appears in sporadic chunks. I also can sense, but this is more subtle, that the plugins version of the editor feels generally slower even with small word counts than the core draft-js and other text editors.

Perhaps it is one specific plugin that's the cause? Love to find a fix so we can still use.

**Comment by avk** [comment]
Also seeing this issue on https://www.draft-js-plugins.com/

**Comment by sbhargava** [comment]
Really would love to find a way to resolve this issue as well.

**Comment by icstunna** [comment]
I too am experiencing lag with the plugin however lag varies between browsers with it being greatest with Chrome then Firefox and least of all with Safari (almost negligible with Safari).

**Comment by nikgraf** [comment]
Any chance one of you can pin down the issue e.g. does it happen with the plugin editor when there is not plugin or is a specific plugin.

**Comment by spherop** [comment]
As it turns out in my case the extremity of it was due to a render function inside the custom editor toolbar that was too aggressively checking for content changed/dirty.

**Comment by nikgraf** [comment]
@avk @sbhargava @icstunna what about you guys?

**Comment by avk** [comment]
@nikgraf hm, actually I was also storing the `editorState` and comparing it to past states... thanks for the lead @spherop! Much better now with a boolean flag!

**Comment by juliankrispel** [comment]
Closing this issue as part of a clean out. If you think this should remain open please let me know. Cheers
