### ISSUE TITLE
Make State Preview a plugin

### ISSUE THREAD

**Issue by mxstbr** [draft-js-plugins/draft-js-plugins#52]

**Comment by nikgraf** [comment]
:+1:

**Comment by adrianmc** [comment]
What's the description here? State preview sounds useful, but I'm unsure what it is.

**Comment by nikgraf** [comment]
@bkniffler had a nice `See JSON` button here: https://draft-wysiwyg.herokuapp.com/

I'm not sure if we really need it. We had something like this and eventually removed it again as console.log & debugger was way more useful.

**Comment by nikgraf** [comment]
If you have a great idea feel free to give it a try. If not I'm happy to close this issues 😄

**Comment by adrianmc** [comment]
Hey that's pretty cool. I can see how it could be super useful for debugging, but yeah I agree that console.log probably makes more sense.
