### ISSUE TITLE
how to use sticker-plugins to make sticker stay with font in a line

### ISSUE THREAD

**Issue by mingzhaov** [draft-js-plugins/draft-js-plugins#522]
hey,@nikgrf ,sorry to interrupt you! when I use draft-js-sticker-plugins, I just want to know how to  use the sticker-plugin to make the sticker stay with text in a line.

**Comment by juliankrispel** [comment]
@mingzhaov the sticker plugin works with blocks only right now. Stickers would need to be entities in this case. I'd recommend using the image plugin instead :)
