### ISSUE TITLE
How to use the draft-js-focus-plugin.

### ISSUE THREAD

**Issue by MarinusDR** [draft-js-plugins/draft-js-plugins#523]
What does the draft-js-focus-plugin do?
And how to use it?
Do you have some codelines as example?

**Comment by MarinusDR** [comment]
Hello..?

**Comment by mzbac** [comment]
@MarinusDR It provide a props of block to tell you if that block is focused or not. then you can add your own logic to do some highlight or onSelect. 
https://github.com/draft-js-plugins/draft-js-plugins/blob/master/draft-js-focus-plugin/src/index.js#L56
https://github.com/draft-js-plugins/draft-js-plugins/blob/master/draft-js-focus-plugin/src/createDecorator.js#L77

**Comment by nikgraf** [comment]
@MarinusDR sorry for the late reply. I kind of stopped looking at issues to actually focus on code and finish up 2.0

I rewrote the focus plugin. It now has docs and I'm 99% sure this is the final API for 2.0
https://www.draft-js-plugins.com/plugin/focus

Let me know if something is unclear. Then we can clarify in the docs right away. 👍

**Comment by GeckoFu** [comment]
hi @nikgraf , in this [example](https://www.draft-js-plugins.com/plugin/focus), focus decorator is applied to `ColorBlock`, what if I want to focus a dynamically inserted image? (with the image-plugin, where i didn't get the image component but just a modified editorState)

I tried to pass the decorator to editorState, but it doesn't look like a Draft.js decorator
