### ISSUE TITLE
draft-js-dnd-plugin - replaceBlock url question.

### ISSUE THREAD

**Issue by Antherkiv** [draft-js-plugins/draft-js-plugins#524]
Hello, I want to ask if the url going to be completely removed in replaceBlock and delegate the work to the handleBlock:

newEditorState = replaceBlock(
modifyBlockData(
newEditorState,
blocks.first().get('key'),
retainSrc ? { progress: undefined } : { progress: undefined, src: undefined }
),
blocks.first().get('key'),
newEditorStateOrBlockType
);

If you set retainSrc to false, you got nothing, I want to understand if it´s ok and then how you plan to handle that.

Best regards.

**Comment by juliankrispel** [comment]
@Antherkiv hey man. Sorry this reply is a bit late I guess.

I'm not sure I understand the queastion to be honest but if you still need an answer please feel free to reply here with a more detailed description or on the draft js slack.

I'm closing the issue for now assuming that this has been resolved within the last year or so :trollface:  :)
