### ISSUE TITLE
How to render these plugins from raw content state in "readOnly" mode

### ISSUE THREAD

**Issue by kevinleeTCA** [draft-js-plugins/draft-js-plugins#530]
I made the plugins work under the **Editor** tag, and I can type inline block like bold, underline,.. etc.
I also install plugins like **Linkify**, **Mentions** and **Emoji**, it shows correctly in the editing box. 

But it just show a plain text when rendering it in HTML for the links and mentions, and some of the Emoji did not show correctly, for the one shows correctly, the CSS looks very different.

What I did is that converting editor state to raw state 
`let rawState = convertToRaw(this.state.editorState.getCurrentContent()`
then, create a editorState for rendering as follows
`const blocks = convertFromRaw(rawState);`
  `this.state = {editorState: EditorState.createWithContent(blocks)};`
and try to rendering it using `Editor` with `readOnly={true}`, 
Defining the rendering component like

    render(){
        return <div className="RichEditor-root message-display-root">
                <div className="RichEditor-editor message-display-editor">
                    <Editor
                        blockStyleFn={getBlockStyle}
                        customStyleMap={styleMap}
                        editorState = {this.state.editorState}
                        readOnly={true}
                        plugins={plugins}
                        onChange={()=>{}}
                        />
                </div>
        </div>;
    }

All the inline style show correctly (Bold, Underline, Blockquote, UL, OL, ...etc), just these plugins does not show correctly when trying to render it in HTML.
When inspecting the element, some of the class and element shows quite different, like there will be `draftJsMentionPlugin__mention__29BEd` class for the mention shown in editing box, but not shown in the readOnly part of the HTML page.

**Comment by mzbac** [comment]
seems when you replace the editorState from ```this.state = {editorState: EditorState.createWithContent(blocks)};`` you lost all the decorators..
try
```
 `this.state = {editorState: EditorState.push(this.state.editorState, convertFromRaw(this.props.originalContentState), 'update-contentState')}
```

**Comment by kevinleeTCA** [comment]
@mzbac  thanks for the reply.
I tried this, now work as well.

My component to rendering message is 

```
class MessageDisplay extends React.Component{

    constructor(props) {
        super(props);
        const blocks = convertFromRaw(this.props.messageObj);
        this.state = {editorState: EditorState.createWithContent(blocks)};
    }

    render(){
        return <div className="RichEditor-root message-display-root">
                <div className="RichEditor-editor message-display-editor">
                    <Editor
                        blockStyleFn={getBlockStyle}
                        customStyleMap={styleMap}
                        editorState = {this.state.editorState}
                        readOnly={true}
                        plugins={plugins}
                        onChange={()=>{}}
                        />
                </div>
        </div>;
    }
}
```

The `messageObj` is the raw content state.

**Comment by mzbac** [comment]
it may sounds silly, but draftjs-plugin editor is using onchange to mount the decorators to editorState. so I think even your editor is on readOnly you still need to pass onchange ={ (editorState) => this.setState({editorState}}

**Comment by kevinleeTCA** [comment]
@mzbac  It is wired. But it works. Thank you very much 👍

**Comment by varunajmera0** [comment]
https://codeburst.io/web-developer-playbook-rich-text-editor-4c356fb8929d
