### ISSUE TITLE
inline-Toolbar wrong position when using twitter bootstarp.

### ISSUE THREAD

**Issue by navidmesbah** [draft-js-plugins/draft-js-plugins#531]
Position of the inline-toolbar is calculated wrong when using twitter bootstrap as the skeleton of the css...

![screenshot_2016-11-07_22-48-13](https://cloud.githubusercontent.com/assets/10755936/20072085/5344b08e-a53c-11e6-9e7d-7cf8001aeb29.png)

**Comment by Rosey** [comment]
I've noticed this too, not with twitter bootstrap but just in general - it seems to always set the position relative to the window, which could be wrong if it has a relative/absolutely positioned parent. The way emoji/mentions are positioned seems way more reliable, maybe that functionality could be ported over to the inline-toolbar as well?

I do find if you set `position: fixed` on the toolbar the position "works" but in the case of a scrollable parent, it doesn't scroll with its parent anymore, so I think it could still be made better by emulating how emoji and mention suggestions are positioned :)

**Comment by jrock17** [comment]
I'm seeing the same thing (using Zurb Foundation). Any recommended fixes?

![2016-11-15_09-27-06](https://cloud.githubusercontent.com/assets/1270524/20316198/bc4a1f22-ab15-11e6-8361-91b0db4bf544.png)

**Comment by jebarjonet** [comment]
I am facing a similar issue when the draft js input is nested in `div` that have `position: relative`, the toolbar position is messed up and is displayed somewhere else on the screen. When I set those parents `div` in `position: static`, it works perfectly. Unfortunately I need this `position: relative` property on those parents.

**Comment by jrock17** [comment]
I'm still having the same problem after the beta7 update.

![toolbar](https://cloud.githubusercontent.com/assets/1270524/20676561/ffc880de-b544-11e6-8414-a54839b75ca7.png)

**Comment by mkampik** [comment]
I've encountered the same problem. You can fix the inline-toolbar's position by ensuring that **all** of it's parent `divs` have their css `position` property set to its default value: `static`.

Would be nice to be able to position parent `divs` however you like. Not sure what the best implementation would be tho. Perhaps worth exploring in a separate issue?

**Comment by jebarjonet** [comment]
@mkampik this fix works on very simple and lightweight structures, if you work on a bigger project or use frameworks (Bootstrap, Foundation, Semantic, etc.) it is not viable to put every parents in `static`. The plugin should be usable anywhere, independently of ancestors or siblings. I guess it only needs a `div` in `relative, the tooltip inside as `absolute` and make every calculation inside the relative div, without worrying about the rest of the page.

**Comment by jckhang** [comment]
Toolbar gets the selection rectangle position in DOM. So I find using `position: fixed` and `top: 0;` works well.

**Comment by nikgraf** [comment]
any ideas on a better way of determining the position? Should `position: fixed` & `top: 0` be the default behaviour?

**Comment by myyellowshoe** [comment]
I ran into basically the same issue, but with the sidetoolbar plugin, as my parent container element had to be positioned relative. When I applied the position fixed to toolbar, it worked perfectly. From my testing, it looks like position fixed works well regardless of the parent position type.

**Comment by styks1987** [comment]
The above fix, fixed it for me.

**Comment by nikgraf** [comment]
Thanks everyone for your involvement. Just merged the fix and going to cut a release later today or tomorrow 😃

**Comment by 1x-martin** [comment]
The same issue is currently appearing again. Version is `2.0.0-beta6`

**Comment by lednhatkhanh** [comment]
We should reopen this issue, I'm having the same problem...
