### ISSUE TITLE
Unknown props "onOpen", "onClose"

### ISSUE THREAD

**Issue by lookapanda** [draft-js-plugins/draft-js-plugins#533]
> Warning: Unknown props `onOpen`, `onClose` on <div> tag. Remove these props from the element. For details, see https://fb.me/react-unknown-prop
    in div
    in MentionSuggestions (created by Decorated(MentionSuggestions))
    in Decorated(MentionSuggestions) (created by ChatInputComponent)
    in div (created by ChatInputComponent)
    in div (created by ChatInputComponent)
    in div (created by ChatInputComponent)
    in form (created by ChatInputComponent)
    in ChatInputComponent

Is this known? I didn't really modify anything, I just used the examples on the documentation page. It's still working as intended, but it throws this warning.

**Comment by mzbac** [comment]
this is the warning which introduced from react@15, I think somehow the onOpen and onClose are passed down to html standard DIV element in mentionSuggestion.

**Comment by lookapanda** [comment]
Good to know :)

**Comment by nikgraf** [comment]
Thanks @lookapanda for reporting. Will be solved with the next beta-release 👍
