### ISSUE TITLE
how to set a type?

### ISSUE THREAD

**Issue by sanghyunJ** [draft-js-plugins/draft-js-plugins#537]
const PersonMentionPlugin = createMentionPlugin({
    PersonMentions,
    entityMutability: 'IMMUTABLE',
    mentionPrefix: '@',
    mentionTrigger:'@',
    type: "person"
});
it doesn't work..
somebody help me..
thanks.

**Comment by mzbac** [comment]
@sanghyunJ  type of  mention? of entity?

**Comment by sanghyunJ** [comment]
sorry i want to type of entity

**Comment by mzbac** [comment]
from the code, I don't think the entity type can be changed..
https://github.com/draft-js-plugins/draft-js-plugins/blob/master/draft-js-mention-plugin/src/modifiers/addMention.js#L6

**Comment by sanghyunJ** [comment]
@mzbac hu.... then.. how to export to html? 
I'm using draft-js-export-html for show result html .. but all of tag has 'unstyled'
i want to distinguish  mention and other plugin

**Comment by mzbac** [comment]
@sanghyunJ  I don't know much about draft-js-export-html but I am guessing you need to write some custom mapper for that.  for me personally I would just use draft-js-plugin-editor to show the result html by setting readOnly = true.

**Comment by sanghyunJ** [comment]
@mzbac can i show your example source code? thank you very very much
