### ISSUE TITLE
CompositeDecorator strategies are not working when we are using Emoji Plugin.

### ISSUE THREAD

**Issue by ErangaLakmal** [draft-js-plugins/draft-js-plugins#538]
I am using following two strategies coming from tweet example.
``` 
const compositeDecorator = new CompositeDecorator([
    {
        strategy: handleStrategy,
        component: HandleSpan,
    },
    {
         strategy: hashtagStrategy,
         component: HashtagSpan,
    },
]);
```

These two strategies are working fine and we can find them in the console log of editorState.( As same as Tweet example). Then I integrated Emoji Plugin into my editor. After that, only the Emoji Plugin decorator and Emoji Suggestions decorator are coming under the decorators array of editorState. My Hash tag and Handler stategies are gone from the decorators. Any particulate reason to this. My code is as follow. Please refer. ank you in advance.

```
import { CompositeDecorator, EditorState, RichUtils, convertFromRaw, convertToRaw} from 'draft-js';
import Editor, { createEditorStateWithText } from 'draft-js-plugins-editor'; 

import createEmojiPlugin from 'draft-js-emoji-plugin'; 
import editorStyles from './editorStyles.css';

const emojiPlugin = createEmojiPlugin();
const { EmojiSuggestions } = emojiPlugin;
const plugins = [emojiPlugin];

export default class DayView extends Component {
    constructor(props) {
        super(props);
        const compositeDecorator = new CompositeDecorator([
            {
              strategy: handleStrategy,
              component: HandleSpan,
            },
            {
              strategy: hashtagStrategy,
              component: HashtagSpan,
            },
        ]);
       
        this.state = {
            editorState : EditorState.createEmpty(compositeDecorator),
        };

        this.focus = () => this.refs.editor.focus();
        this.onChange = (editorState) => this.setState({editorState});
        this.logState = () => console.log(this.state.editorState.toJS());
    }

    render() {
        return (
            <div>
                <Editor
                    editorState={this.state.editorState}
                    onChange={this.onChange}
                    placeholder="Write a tweet..."
                    ref="editor"
                    spellCheck={true}
                    plugins={plugins}
                />
               <EmojiSuggestions />
           </div>        
        )
    }
}

const HANDLE_REGEX = /\@[\w]+/g;
const HASHTAG_REGEX = /\#[\w\u0590-\u05ff]+/g;

function handleStrategy(contentBlock, callback) {
  findWithRegex(HANDLE_REGEX, contentBlock, callback);
}

function hashtagStrategy(contentBlock, callback) {
  findWithRegex(HASHTAG_REGEX, contentBlock, callback);
}

function findWithRegex(regex, contentBlock, callback) {
  const text = contentBlock.getText();
  let matchArr, start;
  while ((matchArr = regex.exec(text)) !== null) {
    start = matchArr.index;
    callback(start, start + matchArr[0].length);
  }
}

const HandleSpan = (props) => {
  return <span {...props} style={styles.handle}>{props.children}</span>;
};

const HashtagSpan = (props) => {
  return <span {...props} style={styles.hashtag}>{props.children}</span>;
};

const styles = {
  root: {
    fontFamily: '\'Helvetica\', sans-serif',
    padding: 20,
    width: 600,
  },
  editor: {
    border: '1px solid #ddd',
    cursor: 'text',
    fontSize: 16,
    minHeight: 40,
    padding: 10,
  },
  button: {
    marginTop: 10,
    textAlign: 'center',
  },
  handle: {
    color: 'rgba(98, 177, 254, 1.0)',
    direction: 'ltr',
    unicodeBidi: 'bidi-override',
  },
  hashtag: {
    color: 'rgba(95, 184, 138, 1.0)',
  },
};
```

**Comment by nikgraf** [comment]
@ErangaLakmal simply pass the decorators to the draft-js-plugins-editor like this:

```
<Editor
  editorState={this.state.editorState}
  onChange={this.onChange}
  decorators=[compositeDecorator]
  plugins={plugins}
/>
```

This is a limitation of the plugin architecture. Afaik we can't keep the original behaviour and have decorator support in the plugin system.

**Comment by nikgraf** [comment]
Let me know if that solves your problem. If that wasn't clearly communicated I would be happy about a PR to the FAQ or README explaining it.

**Comment by erangakapukotuwa** [comment]
I have two question.
01. We can not use square bracket here.
02. Where do we declare the `compositeDecorator` . In the constructor or render function. Tried several ways. It did not worked.

**Comment by ErangaLakmal** [comment]
I have two question.
01. We can not use square bracket here.
02. Where do we declare the compositeDecorator . In the constructor or render function. Tried several ways. It did not worked.

**Comment by mzbac** [comment]
1.you have to wrap attribute by {}
2.you don't need to declare conpositeDecorator. editor will do it for you. you just need to pass it as an array in decorators attributes.

**Comment by ErangaLakmal** [comment]
@mzbac Thank you for commenting. What I mean is. I should have a place to define the strategies. I mean the following part. Can you please explain bit more.

```
    {
        strategy: handleStrategy,
        component: HandleSpan,
    },
    {
         strategy: hashtagStrategy,
         component: HashtagSpan,
    },
```

**Comment by mzbac** [comment]
something like:
```
<Editor
  editorState={this.state.editorState}
  onChange={this.onChange}
  decorators={[
 {
        strategy: handleStrategy,
        component: HandleSpan,
    },
    {
         strategy: hashtagStrategy,
         component: HashtagSpan,
    },
]}
  plugins={plugins}
/>

**Comment by mzbac** [comment]
```
<Editor
  editorState={this.state.editorState}
  onChange={this.onChange}
  decorators={ [{
        strategy: handleStrategy,
        component: HandleSpan,
    },
    {
         strategy: hashtagStrategy,
         component: HashtagSpan,
    },]}
  plugins={plugins}
/>
```

**Comment by ErangaLakmal** [comment]
Correct. I tried this method. The contentBlock variable which is in the following line is not properly set. 
```
      function findWithRegex(regex, contentBlock, callback) {
           const text = contentBlock.getText();
```
Becase of that, it indicates the following error. 

`EditorField.js:145 Uncaught TypeError: contentBlock.getText is not a function`

Then I logged the contentBlock by putting a `consol.log()` there. This is what it indicated.

```
( /*number*/start, /*number*/end) {
        // Find out if any of our matching range is already occupied
        // by another decorator. If so, discard the match. Otherwise, store
        //…
```


What I understood is, This message prompts because I am using "#" and "@" tags which are already taken by my `mentions plugin`. Is this possible. Based on that assumption I changed my regex to `const HANDLE_REGEX = /\$[\w]+/g;`. Unfortunately the issue continues.

**Comment by mzbac** [comment]
@ErangaLakmal  yes mention plugin used the '@' by default. if you really want to use '@', '#' on your own decorator you can change the mention plugin's config.
https://github.com/draft-js-plugins/draft-js-plugins/blob/master/draft-js-mention-plugin/src/index.js#L89

**Comment by ErangaLakmal** [comment]
Correct. I have done that thing too. I am using "#" tag as the mention trigger. Forget about all. And lets assume I am using "$" as the decorator. `HANDLE_REGEX = /\$[\w]+/g;`. The issue is exist even now.

Anyway I notice that my costume strategy repeats inside the decorators array.(after log the editorState I notice this.) Please check the screen shot. I have five decorators which are, 
01. My custom decorator(timeStrategy)
02. mentions decorator
03. mentions Suggestion decorator
04. Emoji decorator 
05. Emoji decorator
![screenshot from 2016-11-16 12-51-55](https://cloud.githubusercontent.com/assets/22886170/20338215/ac2083c0-abfb-11e6-9572-e92cab4c53bb.png)

After expanding 1st decorator(my custom decorator ). You can see same strategy repeats at the bottom of expanded object. And also it repeats infinitely  & nestedly.  Please see the attachment. Is there any possibility regarding this to prompt above issue.

![screenshot from 2016-11-16 12-55-10](https://cloud.githubusercontent.com/assets/22886170/20338416/0140f7a8-abfd-11e6-84a7-ab7d67d33d97.png)

**Comment by ErangaLakmal** [comment]
Here I added my code to a sample git repo.

https://github.com/erangakapukotuwa/draft-js-sample/blob/master/EditorField.js

Please check.

**Comment by mzbac** [comment]
@ErangaLakmal  I could not figure out why you are getting duplicated decorators. can you debug in your local draft-js-plugin-editor's code.
the decorators related logic you can checking the following .
https://github.com/draft-js-plugins/draft-js-plugins/blob/master/draft-js-plugins-editor/src/Editor/index.js#L58

**Comment by ErangaLakmal** [comment]
Thank You very much for your patient @mzbac . I'll check.
