### ISSUE TITLE
how to set a entity(block) type?

### ISSUE THREAD

**Issue by sanghyunJ** [draft-js-plugins/draft-js-plugins#539]
I'm using draft-js-export-html for show result html .. but all of block has 'unstyled'
i want to distinguish mention and other plugin

**Comment by scf4** [comment]
Well what was the solution? When I run convertToRaw my hashtags are unstyled...

**Comment by nikgraf** [comment]
@sanghyunJ sorry the draft-js-export-html and plugins are not compatible at this point
