### ISSUE TITLE
Moving to yarn ?

### ISSUE THREAD

**Issue by nihaux** [draft-js-plugins/draft-js-plugins#545]
I am not familiar with shrinkwrap but using yarn makes a breath to lock dependencies
Switching in other projects has been effortless. I wasn't publishing on npm though.

**Comment by nikgraf** [comment]
@Nihaux yarn will not help with publishing packages, but certainly docs and devDependencies for building would benefit from it.

I would absolutely merge this 😄

**Comment by juliankrispel** [comment]
Closing this issue as part of a clean out. If you think this should remain open please let me know. Cheers
