### ISSUE TITLE
Multiple plugins / multiple editors

### ISSUE THREAD

**Issue by stevewillard** [draft-js-plugins/draft-js-plugins#548]
I'm trying to render multiple Components/Editors onto the page, each with their own decorators and plugins. I followed the advice in the FAQ (https://github.com/draft-js-plugins/draft-js-plugins/blob/master/FAQ.md) but for some reason, the emoji plugin (or mentions, etc.) isn't being applied to each Editor.

This is roughly what my code looks like:
```javascript
import { Component, PropTypes } from 'react';

import 'draft-js/dist/Draft.css';

// Editor
import Editor from 'draft-js-plugins-editor';

// Emoji
import createEmojiPlugin from 'draft-js-emoji-plugin';
import 'draft-js-emoji-plugin/lib/plugin.css';

export default class Test extends Component {
  constructor(props) {
    super(props);

    const emojiPlugin = createEmojiPlugin();
    const { EmojiSuggestions } = emojiPlugin;

    this.editorPlugins = [
      mentionPlugin
    ];

    this.components = {
      EmojiSuggestions
    };
  }

  render() {
    const {
      onChange,
      editorState,
      readOnly
    } = this.props;

    const {
      EmojiSuggestions
    } = this.components;

    return (
      <div className={styles.editor}>
        <Editor
          editorState={editorState}
          onChange={onChange}
          plugins={this.editorPlugins}
          ref={(element) => { this.editor = element; }}
          readOnly={readOnly}
        />
        <EmojiSuggestions />
      </div>
    );
  }
}
```

Any help would be greatly appreciated! Thanks for putting these plugins together.

**Comment by sam-jay** [comment]
@stevewillard I'm assuming that you meant `emojiPlugin` and not `mentionPlugin` in `this.editorPlugins`. I was able to get multiple editors working with almost the same code you have. Does your onChange function set local state somewhere which then gets passed as the editorState prop?

I have it working with something like this:

```js
export default class MyEditor extends Component {
  constructor(props) {
    super(props);
    const mentionPlugin = createMentionPlugin();
    const { MentionSuggestions } = mentionPlugin;
    this.plugins = [mentionPlugin];
    this.components = { MentionSuggestions };
    this.state = {
      editorState: props.editorState
    };
  }

  onChange = (editorState) => {
    this.setState({ editorState });
    if (this.props.onChange) {
      this.props.onChange(editorState);
    }
  };

  render() {
    <div>
      <Editor
          editorState={this.state.editorState}
          onChange={this.onChange}
          plugins={this.plugins}
          ref={(element) => { this.editor = element; }}
       />
    </div>
  }
}
```

**Comment by stevewillard** [comment]
Yeah -- I meant the emoji plugin. Something is definitely up with my code. In one part of my app, I can render multiple Editors, using code very similar to what you posted, and things work fine. In another area the decorators don't seem to work.

The onChange updates an editorState value in a redux store, which then gets passed down to this component.

I'll keep digging and post back here if I figure it out. Maybe it'll help others who have the same issue.

**Comment by lakesare** [comment]
I'm having the same issue, my decorators don't work when multiple editors are present. It does disappear when I'm setting editor's state in the same component instead of passing `onChange` and `editorState` as props.

**Comment by NikolasStelmah** [comment]
For futher searchers: if you getting `editorState` from `this.props` then your decorator got broken and plugin will not work. To fix this, you need to do smth like this in somewhere parent container to `<Editor/>` component where is defined your `onChange` function: 
`onInputTextChanged(editorState) {
    if (editorState.getDecorator()) {
      this.setState({ decorator: editorState.getDecorator(), editorState });
    } else if (this.state.decorator) {
      const { decorator } = this.state;
      this.setState({
        editorState: EditorState.set(editorState, { decorator }),
      });
    } else this.setState({ editorState });
  }`
Then u should pass `editorState` and `onChange` function as a props like u probably did.

Another situation is like in current issue above. You must be shure that you did it in your editor component constructor: 
`
constructor(props) {
    super(props);
   const emojiPlugin = createEmojiPlugin();
   const { EmojiSelect } = emojiPlugin;
   his.plugins = [emojiPlugin];
   this.components = { EmojiSelect };
...
`
Plugin can by any whatever you are using and you must be shure, that you rendering the right plugin from `this.components`

**Comment by tariqporter** [comment]
I didn't understand any of the above. Is this a bug?
I have 2 draftjs components, both with `draft-js-emoji-plugin` and `draft-js-inline-toolbar-plugin`. You'll see that only the second one works properly

https://stackblitz.com/edit/react-hecgf4

Type `:smile` to test first plugin, and then type `test` and try and highlight it in both textboxes. Neither plugin works correctly in the first field
