### ISSUE TITLE
Moving React dependency to peerDependencies

### ISSUE THREAD

**Issue by chrisui** [draft-js-plugins/draft-js-plugins#549]
Hey,

Just installed draft-js-plugins and noticed it pulls in the *latest* version of `react`. Typically I would've expected this to be a peer dependency since the consumer is in the charge of managing the versioning there.

Two questions:

1. Can we move `react` and `react-dom` to `peerDependencies` in `package.json` (perhaps there are other deps which should live there too?)
2. Does draft-js-plugins support previous versions of React? (.14 in my case)

Thanks!

**Comment by nikgraf** [comment]
@chrisui sorry for the late reply. I kind of stopped looking at issues for the last month to actually focus on code and finish up 2.0

1. Didn't peerDependencies become obsolete with npm3?
2. Nope, we don't support 0.14.x

**Comment by nikgraf** [comment]
ohhh, didn't know that. Sounds good to me. Interested to open up a PR?

**Comment by sugarshin** [comment]
+1

**Comment by bj00rn** [comment]
close?
