### ISSUE TITLE
how to add a clolor-picker plugin

### ISSUE THREAD

**Issue by zwhu** [draft-js-plugins/draft-js-plugins#550]
Hi, i want to add a clolor-picker plugin , but I don't know how to add, can you give a suggest?

I have saw the drafts's example, that must set customStyleMap, but I have many many colors ,so I don't know how to add color-picker function.

thanks.

**Comment by mzbac** [comment]
1.apply custom style.
2.set custom style map
3.add css accordingly

**Comment by nikgraf** [comment]
@zwhu checkout this one here: https://github.com/jpuri/react-draft-wysiwyg/blob/master/js/src/components/ColorPicker/index.js

**Comment by zwhu** [comment]
ok,thanks a lot.
