### ISSUE TITLE
Resetting the content does not work in beta6 anymore

### ISSUE THREAD

**Issue by DerKobe** [draft-js-plugins/draft-js-plugins#552]
Resetting the content as described in the FAQ does not work in beta6 anymore. When I switch back to beta5 it works again.

**Comment by jrock17** [comment]
I'm on beta6 and clearing the input box is working ok for me. Might want to check your code or post here.

**Comment by nikgraf** [comment]
@DerKobe I released beta9 today. Is it still not working for you?

**Comment by DerKobe** [comment]
Ok with beta9 it clears the input again, but I get weird behaviour for the input after that (e.g. cursor jumps after deleting a character). I use another method (I found somewhere) for clearing the input and it works much better for me (with any beta version).

    resetChatInput() {
      const contentState = this.state.editorState.getCurrentContent()
      const firstBlock = contentState.getFirstBlock()
      const lastBlock = contentState.getLastBlock()

      const selectionState = this.state.editorState.getSelection().merge({
        anchorKey: firstBlock.getKey(),
        anchorOffset: 0,
        focusKey: lastBlock.getKey(),
        focusOffset: lastBlock.getLength(),
        hasFocus: true
      })

      const editorState = EditorState.push(
        this.state.editorState,
        Modifier.removeRange(contentState, selectionState, "backward")
      )

      this.onChange(editorState)
    }

**Comment by nikgraf** [comment]
@DerKobe you try to use EditorState.forceSelection (which returns a new editorState) before you pass the editorState to onChange

**Comment by DerKobe** [comment]
@nikgraf just to clear things up, I get the weird cursor behaviour with the clearing-method from the FAQ and because of that I use the method mentioned above. Do you see a problem with the above version?
