### ISSUE TITLE
MentionSuggestions mentionTrigger as prop enhancement

### ISSUE THREAD

**Issue by Revln9** [draft-js-plugins/draft-js-plugins#554]
Hi , the mentionSuggestions plugin is not reading correctly some props , the only way to get the mentiontrigger replaced is by passing a config object  like this 

`createMentionPlugin({mentionTrigger:'/'});`

i have not invistigated much on the props  issue but i will surely do 
How do you think i can solve this ?

thanks for these awesome plugins !

**Comment by Revln9** [comment]
just rechecked the code and the readme again last night , and this prop was a bump 🐰  of my imagination lol sorry about that , but it will be cool to have this enhancement don't you think?

**Comment by Radivarig** [comment]
I'd like to make a dropdown that triggers on "#" like on github to mention an issue.

**Comment by Radivarig** [comment]
This is working for me

```js
const mentionPlugin = createMentionPlugin({
  mentionTrigger: '#',
})

**Comment by Radivarig** [comment]
This is working for me

```js
const mentionPlugin = createMentionPlugin({
  mentionTrigger: '/',
})
```

using `"draft-js-mention-plugin": "^2.0.0-beta5"`
