### ISSUE TITLE
How to rerender mention component [Mentions]

### ISSUE THREAD

**Issue by Radivarig** [draft-js-plugins/draft-js-plugins#557]
I'd like to force render of existing mention component when something in store changes

```jsx
const mentionComponent = (props) => {
  // if (getReduxStore().something)
  //   return <span>different render output</span>

  return (
    <span className={props.className}>
      {props.mentionPrefix}
      {props.decoratedText}
    </span>
  )
}
```
Edit:
I noticed that deleting from the same line where component entity is triggers rerender.

**Comment by mzbac** [comment]
you can give a key of your span and when store changes then change the key.. I guess

**Comment by Revln9** [comment]
Use this.state to store the 'thing' that changes in your store and mapStateToProps will do the job for you , you just have to call setState after changes occurs , this  will rerender your component .

**Comment by Radivarig** [comment]
@mzbac `key` change forces a remount, I just need to render again.

Also key doesn't matter because the component needs to know when to update anyway, for example setState would trigger it, but something has to trigger setState, and I'm not looking for async solution like listening for an event.

This is how custom mention component is passed in config on plugin creation
```jsx
import createMentionPlugin from 'draft-js-mention-plugin'

const mentionComponent = ...

createMentionPlugin({
  mentionComponent,
  ...
```
so since plugin handles rendering of the component I can't choose the `key` of the mention component.

**Comment by Radivarig** [comment]
@Revln9 if I mapStateToProps and add a `<Provider>` wrapper I'd loose props passed by the mention plugin. Or am I missing something?

**Comment by techhysahil** [comment]
Have you got solution for "How to rerender this component"? I need any help i can get on this one.

**Comment by techhysahil** [comment]
In "[Custom Mention Component Example](https://www.draft-js-plugins.com/plugin/mention)" example , instead of just triggering alert, i want to trigger component reRender.

**Comment by Radivarig** [comment]
@techhysahil if you don't need to depend on external events to have to connect the component with redux and spread props from the provider wrapper like described above, but can depend only on the internal events like onClick, you can use a stateful react component instead of the stateless lambda in the example and update its state based on those events.

**Comment by techhysahil** [comment]
@Radivarig thanks for suggestion. I was able to do it other way.

**Comment by baquiax** [comment]
Hi @techhysahil! 

It's 2021 and I'm facing the same issue! Is there a chance to know how do you solve it?

Thanks in advance!
