### ISSUE TITLE
MentionSuggestions whitespace Regex filter issue

### ISSUE THREAD

**Issue by Revln9** [draft-js-plugins/draft-js-plugins#558]
suppose you have  a suggestion list like that 
```
[
{ name: 'call 1' , value:1 },
{ name: 'call 2' , value:2 },
{ name: 'call 3' , value:3 }
]
```

if you type '@call 3' at the editor it will not narrow the search to item call 3 , because the whitespace breaks it . instead it will give you all of them.

i've noticed also a sorting issue with suggestions when you search for something that contains A for example the suggestions that begins with A needs to be at the top of the list which is not the case. instead it gives you the the natural order of your current suggestions list.

now how i can modify the regex and the mentionSuggestionsStrategy to do so ?

**Comment by mzbac** [comment]
@Revln9  I think current mentions suggestion regex doesn't support withe space..

**Comment by Revln9** [comment]
Found a solution or a hack (your call).

 the regex `/\S+$/` that is used as a word delimiter in `getWordAt.js` is weak , it will not skip whitespaces , even worse it will use it as a word boundary .

I  wrote my own (took me some headaches...) that takes the mentionTrigger key as the first delimiter and a new line or a return carriage as the second . It will read all the line after the mentionTrigger key.

Another important point to mention is that your mentionTrigger key must not be a character or a digit .

`/[^\s][\s?\w+]*(?=$)/
`

if anyone has some experience in the regex 'Science' feel free to comment 

WARNING 🔴 
I AM NOT A REGEX EXPERT USE IT AT YOUR OWN RISK :dagger: 

Hope this helps!

Ps: even github mention doesn't have this mention with space awarness feature , so i guess it's for a good reason , i don't have facebook if anyone could try this and post the result it will be cool.

**Comment by nikgraf** [comment]
@Revln9 there even was a PR for whitespace support at some point. Unfortunately it's even more complicated as you need to limit the amount of spaces for the decorators. Even then you need to make sure there are no overlapping decorators.

In the end I decided to not accept it and recommend to publish it as a separate plugin. The only way to get this in properly would be a re-write of the plugin without leveraging decorators.

**Comment by Revln9** [comment]
Yep nick , you're right for overlapping , i know these things can get quite nasty... ,

I have 3 cascaded mentionSuggestion plugins in the same Editor , and they  show up in series (1 after the other) when i trigger the first one. 
For overlapping issues , all of the mentionTriggers must not be a character `A-z 0-9`  because the regex that i posted before  considers all the non character keys as delmiters and if it didn't find one it will use a new line or a return carriage as the last delimiter. 

It will be tricky to merge this but more documentation about this should help us all.

**Comment by luisrudge** [comment]
😭

**Comment by nikgraf** [comment]
@Revln9 @luisrudge To tackle this issue, I believe the plugin has to be fundamentally different. Instead of using decorators you could run a regex on every selection change and then show an autocomplete dropdown. The code would be way easier and I believe this could eventually even replace the mention plugin.

If any of you would write autocomplete plugin, that would be awesome …
