### ISSUE TITLE
404 errors when npm install plugins

### ISSUE THREAD

**Issue by LucasBerbesson** [draft-js-plugins/draft-js-plugins#559]
Hello,
I don't understand why I get 404 errors when trying to install your plugins. 
<img width="671" alt="capture d ecran 2016-11-21 a 11 27 38" src="https://cloud.githubusercontent.com/assets/8393585/20479188/914a8c2c-afdd-11e6-819a-398b6c66ef66.png">

I get : 
'draft-js-inlineToolbar-plugin' is not in the npm registry.
Registry returned 404 for GET on https://registry.npmjs.org/draft-js-inlineToolbar-plugin

**Comment by mzbac** [comment]
try npm install <plugin>@2.0.0-beta6 --sav

**Comment by LucasBerbesson** [comment]
It worked with 
npm install draft-js-inline-toolbar-plugin
instead of : 
npm install draft-js-inlineToolbar-plugin

**Comment by nikgraf** [comment]
sorry, that was my fault, but should be fixed now 😄
