### ISSUE TITLE
Decorators are getting null after reset the editor

### ISSUE THREAD

**Issue by ErangaLakmal** [draft-js-plugins/draft-js-plugins#562]
Assume that we have an editor, which has integrated several plugins( mentions, emojis ). These plugins are coming under the decorators of the editor. Let assume we reset the editor using the following code. 

`    
const editorState = EditorState.push(this.state.editorState, ContentState.createFromText(''));
this.setState({ editorState });
`

After doing that, the decorators dismiss from the editor. Those plugins( mentions, emojis ) no longer available on the editor. After work around this issue, I got to know that the decorators array, which is coming from a console.log() of editorState is `null`.

**Comment by nikgraf** [comment]
@ErangaLakmal In general we recommend reseting editorState like this for now: https://github.com/draft-js-plugins/draft-js-plugins/blob/master/FAQ.md#how-to-reset-the-content

 This is currently in the making: https://github.com/draft-js-plugins/draft-js-plugins/pull/526, but in case you have better idea let me know 😄

**Comment by ErangaLakmal** [comment]
Cool. This is worked for me. Thank you for commenting.

**Comment by nikgraf** [comment]
Glad it worked out well …

**Comment by davidtran** [comment]
it doesn't work for me.
