### ISSUE TITLE
Latest versions have not been released

### ISSUE THREAD

**Issue by jeremyblalock** [draft-js-plugins/draft-js-plugins#570]
Hi,

The latest release on [npmjs.org](https://www.npmjs.com/package/draft-js-mention-plugin) is **2.0.0-beta1**, but the latest version on the master branch is **beta7**. Is there a reason the most recent beta versions have not been released on [npmjs.org](https://www.npmjs.com/package/draft-js-mention-plugin)?

I just ask, because it is much more difficult to get the development environment setup (not to mention any other deployed environment) if it's not officially released.

Please let me know!

**Comment by StorytellerCZ** [comment]
I don't know why npm lists it as beta1, but when I actually install I get beta7.

**Comment by jeremyblalock** [comment]
@StorytellerCZ, thanks for the tip. When I install @beta or just manually change the version, everything works fine.
