### ISSUE TITLE
onRemoveMention event - mentions

### ISSUE THREAD

**Issue by itzikyacobi** [draft-js-plugins/draft-js-plugins#574]
how can i listen to this event ? or can you give me direction where to start to implement this ?

thanks!

**Comment by nikgraf** [comment]
@itzikyacobi did you find it out?

**Comment by albertomr86** [comment]
Hi @nikgraf I have the same requirement. I need to know when a mention is removed from the editor in order to sync my list of mentions.
Any thoughts?
Thanks.

**Comment by grahamtallen** [comment]
I also have the same requirement. Any word on how to implement this?

**Comment by Pardeep94** [comment]
I also have the same requirement. Any word on how to implement this?

**Comment by vujevits** [comment]
I'd need this feature too.
