### ISSUE TITLE
onChange not triggering [undo]

### ISSUE THREAD

**Issue by Radivarig** [draft-js-plugins/draft-js-plugins#575]
Readme for undo-plugin says this is how button components should be used:
```jsx
<UndoButton onChange={ this.onChange } editorState={ this.state.editorState } />
<RedoButton onChange={ this.onChange } editorState={ this.state.editorState } />
```
However `onChange` is not triggered for me, and the buttons work without props:
```jsx
<UndoButton />
<RedoButton />
```
Also I couldn't find where `createUndoPlugin` or any other `create{$name}Plugin` is exported. Where is it created?

Using beta7.

**Comment by nikgraf** [comment]
Sorry, this is outdated. Here the correct docs: https://www.draft-js-plugins.com/plugin/undo

Interested in submitting a PR to fix the docs?

**Comment by Radivarig** [comment]
Sure, #597. So it's not related to `create{$name}Plugin`. But where is it generated? I couldn't trace it and would like to understand, [`src/__test__/index`](https://github.com/draft-js-plugins/draft-js-plugins/blob/master/draft-js-undo-plugin/src/__test__/index.js#L5) points to [src/index](https://github.com/draft-js-plugins/draft-js-plugins/blob/master/draft-js-undo-plugin/src/index.js#L36) which exports only `historyPlugin`.

**Comment by nikgraf** [comment]
`historyPlugin` should actually be renamed to `createUndoPlugin`. For the execution it doesn't really matter as you define the name when importing it, but would be nice for consistency.

Wanna create another PR for this?

**Comment by Radivarig** [comment]
Ah.. yes. So it could be any variable name from both sides.
I usually use `export const explicitVarName = <expression>` and then `import {explicitVarName}`, but that would be a breaking change from `import varName` to `import {varName}` . Would exporting directly `export default <expression>` be ok?

**Comment by nikgraf** [comment]
@Radivarig jep, `export default <expression>` is even better. Creates less confusion …
