### ISSUE TITLE
Identify and convert mentions on pasting.

### ISSUE THREAD

**Issue by prashantagarwal** [draft-js-plugins/draft-js-plugins#578]
If you copy and paste a text string with some mentions, it should style the mentions accordingly.

**Comment by prashantagarwal** [comment]
@nikgraf any idea how this can be achieved in current version ?

**Comment by prashantagarwal** [comment]
Closing this. It has got nothing to do with mention plugin. I handled it in handlePastedText of Draft-js.

**Comment by nikgraf** [comment]
@prashantagarwal 👍

**Comment by olee** [comment]
Could you tell how you managed to do this?
