### ISSUE TITLE
Fancy animations for the plugins

### ISSUE THREAD

**Issue by nikgraf** [draft-js-plugins/draft-js-plugins#58]
- focused option in the mentions list could be a quick fadeIn/fadeOut of the background
- adding mentions should be smooth animation after the replace
- [ ] fade in for stickers
- [ ] emoji gets same animations as mentions

**Comment by juliankrispel** [comment]
In an effort to clean out issues and only keep those open which we need I'm closing this one. If you disagree, please lmk and I'll reopen.

✌️
