### ISSUE TITLE
Image drag and drop doesn't update editor content with image url from response

### ISSUE THREAD

**Issue by royshouvik** [draft-js-plugins/draft-js-plugins#581]
On image drag and drop, `handleUpload` is called, which uploads the image to server correctly. However, `editorContent` is not updated with the image url from response and data url is still present in src.

**Image uploaded correctly**
![image](https://cloud.githubusercontent.com/assets/5521768/20847259/5241c5d0-b8f3-11e6-8b98-7a8676c12e4f.png)

**Editor Content still contains the data url in src atribute and doesn't use the url returned in response**
![image](https://cloud.githubusercontent.com/assets/5521768/20847329/989e9e40-b8f3-11e6-8dfe-23646607ae12.png)

**Comment by nikgraf** [comment]
Upload management is not ready yet in the 2.0 beta

**Comment by erykpiast** [comment]
@nikgraf, what is the state of work here? I'd like to help.

**Comment by erykpiast** [comment]
I just want to note, I did a great progress with uploading files here: https://github.com/prezly-forks/draft-js-plugins/blob/master/draft-js-drag-n-drop-upload-plugin/src/handleDroppedFiles.js. It works in real application at least. I'd like to merge this to upstream after review and discussion, I still see a field for improvement.

**Comment by royshouvik** [comment]
@erykpiast I am trying to reach out to @nikgraf on [DraftJS Slack](https://draftjs.slack.com/messages/draft-js-plugins/). You can join there too or I will let you know if I get any updates.

**Comment by alfonsoperez** [comment]
@erykpiast could you post an example usage of your plugin?, like how would `addPlaceholder` look like?. Thanks

**Comment by erykpiast** [comment]
Hi @alfonsoperez, it may look like this:

```TypeScript
function addPlaceholder(
    editorState: EditorState,
    file: {
        name: string;
        id: string;
        src: string;
    },
): EditorState {
    return insertBlock(editorState, createPlaceholder({
        ...file,
        caption: removeFileExtension(file.name || getFilenameFromUrl(file.src)),
    }));
}
```

Where `createPlaceholder` produces some custom block of type `image-placeholder`. It's inserted in place of selected text then. That's a code extracted from real application, sorry if it's too obscure.

**Comment by alfonsoperez** [comment]
Thanks!, I have hacking some solution and I _almost_ have it working :D. Could I ask you a probably noob question?.

When I create an `image-placeholder` block, I have it to something like this:

```
function createImagePlaceholder({ caption }: { caption: string }) {
  return new ContentBlock({
    key: genKey(),
    type: "image-placeholder",
    data: new Map({
      caption,
    }),
  });
}
```

If this would be implemented this way?, how would I retrieve the block afterwards in `getPlaceholderBlock` based on the `file` object?.

**Comment by erykpiast** [comment]
I'm doing something very similar, more or less. I just have unique ID assigned to each image, not a file name. But mechanism of getting placeholder block is basically the same.

In my case functions like `createPlaceholderBlock` and `getPlaceholderBlock` are used with two other plugins - one for uploading images by button, another for uploading pasted images (ex. from Word or external web page). But it's more about separation of concerns. In my opinion plugin for uploading images by dropping them shouldn't care about how image (or image placeholder) block looks like, how to find relation between placeholder and final image etc. It just let you do more complex stuff if you need. If you don't, very simple boilerplate code is enough.

**Comment by alfonsoperez** [comment]
Makes total sense, thanks so much!

**Comment by nikgraf** [comment]
Sorry for the late response. @erykpiast can you create a PR? would love to see this plugin in soon :)

**Comment by alfonsoperez** [comment]
@nikgraf That would be amazing, if I can help with anything @erykpiast let me know

**Comment by esteem8** [comment]
Does anyone would have a full example of external required function?
It seem to work in production with @erykpiast solution I just don't exactly know how to handle external function required by the plugin.

Also a PR would be greatly appreciated.
