### ISSUE TITLE
Image resize incorrect behavior when resized from the left edge

### ISSUE THREAD

**Issue by royshouvik** [draft-js-plugins/draft-js-plugins#582]
**Please see attached screenshot**
![image](https://cloud.githubusercontent.com/assets/5521768/20847863/ca47e10c-b8f5-11e6-977b-3464208f762d.png)

Image becomes smaller on dragging outward and becomes larger on dragging inward. This happens only on resizing from the left edge. Resizing from the right edge works fine.

**Comment by nikgraf** [comment]
@royshouvik what version are you using? can you upgrade to the latest beta?

**Comment by royshouvik** [comment]
@nikgraf  Thanks, I was using version `1.0.8`. On updating to `2.0.0-beta7` I get the following error.

`draftJsResizeablePlugin.ResizeableDecorator is not a function`

The new version doesn't export a `ResizeableDecorator`. How should I instantiate the new plugin for resizing `block-image`?

**Comment by nikgraf** [comment]
@royshouvik we changed how it works, but now offer a documentation since today: https://www.draft-js-plugins.com/plugin/resizeable

**Comment by royshouvik** [comment]
@nikgraf Thanks for the docs. I checked with the latest beta release, and the issue still exists. This is reproducible on the [docs](https://www.draft-js-plugins.com/plugin/resizeable) as well. Please let me know if you need more information.

**Comment by juliankrispel** [comment]
fixed in #1071
