### ISSUE TITLE
How to customize styles in draft-js-plugins side-toolbar and inline-toolbar

### ISSUE THREAD

**Issue by StevenIseki** [draft-js-plugins/draft-js-plugins#586]
I am using draft-js-plugins in a project and want to customize the styles. For instanct in the [draft-js-side-toolbar-plugin](https://github.com/draft-js-plugins/draft-js-plugins/blob/master/draft-js-side-toolbar-plugin/src/buttonStyles.css) I want to update the colors, etc...

What is the standard approach for this? I don't imagine we just update the styles in our node_modules folder.

**Comment by mzbac** [comment]
@StevenIseki  standard way to customize styles is pass theme object from config object, however draft-js-side-toolbar-plugin seems doesn't follow the pattern right now.  maybe it will fix in the future or if you are interested you could make a PR for this as well..

**Comment by StevenIseki** [comment]
Thanks @mzbac I just added a pr to fix it https://github.com/draft-js-plugins/draft-js-plugins/pull/588

**Comment by nikgraf** [comment]
Thanks for your PR @StevenIseki - I added 2 more examples, releases your work with beta8 and re-published the website.

**Comment by liSong5713** [comment]
How can I set the toolbar is fixed at the top ?   thanks

**Comment by saeedafroozi** [comment]
@nikgraf :Excuse me sir where is your examples that you added

**Comment by efjacobson** [comment]
@saeedafroozi the final examples on the toolbar plugin pages show custom styling. Inline toolbar: https://www.draft-js-plugins.com/plugin/inline-toolbar

**Comment by arsalankhalid** [comment]
But how exactly are you rendering the sidebar and the inline bar? It looks like just inline is being rendered in the above example.

**Comment by efjacobson** [comment]
@arsalankhalid yeah my example is the inline toolbar but you should be able to do the same with the sidebar. see https://www.draft-js-plugins.com/plugin/side-toolbar and https://github.com/draft-js-plugins/draft-js-plugins/pull/588/files#diff-689858c84b168596419ab718bafe32c8
