### ISSUE TITLE
webpack bundle has two copies of immutable

### ISSUE THREAD

**Issue by lonelyclick** [draft-js-plugins/draft-js-plugins#593]
I used source-map-explorer look at the webpack bundle, found that there are two copies of the immutable. One from draft-js to ~3.7.1, the other from the ^3.8.1 in the draft-js-plugins, so we can make the two library unified version of it?

**Comment by nikgraf** [comment]
good point, interested to open a PR to change the dependencies to 3.8.1

**Comment by lonelyclick** [comment]
#598

**Comment by J22Melody** [comment]
Cool, same issue. Wonder when and which npm version will this commit be published so I can use it via npm?

**Comment by danii1** [comment]
Still different versions of immutable.js....

**Comment by AleksandrZhukov** [comment]
via Webpack you can do:
```
  resolve: {
    alias: {
      ...
      immutable: path.join(__dirname, '../node_modules/immutable')
    }
  }
```

**Comment by danii1** [comment]
I'm using Yarn, so I ended up adding 
```javascript
"resolutions": {
    "draft-js/immutable": "^3.8",
    "draft-js-plugins-editor/immutable": "^3.8",
    "draft-js-export-html/immutable": "^3.8"
}
```
to package.json
