### ISSUE TITLE
Mentions: Suggestions only return upon second letter

### ISSUE THREAD

**Issue by myyellowshoe** [draft-js-plugins/draft-js-plugins#599]
I return an empty array to the mentions plugin when there is no text to search my database on. When I disable this, all works fine.

What I'm seeing:
- First Search on a letter like: **'@j'**  properly returns valid data, but doesn't show popup.
- Second letter **'@ju'** returns data and shows popup.
- Backspacing to 1 letter now searches properly shows popup.

Heres my function:

```
  findUsers = ({value}) => {

    //Can't search on empty
    if(value.length < 1){
      this.setState({
        suggestions:fromJS([])
      });
      return;
    }
...
```

**Comment by nikgraf** [comment]
@myyellowshoe that sounds like there is a delay in the rendering cycle … can you share a reproducible example where I can run `npm install` and `npm start` to figure out what's going on
