### ISSUE TITLE
emoji-plugin ImageType property not getting through to Emoji

### ISSUE THREAD

**Issue by Hapet95** [draft-js-plugins/draft-js-plugins#602]
This is the original code on github:
https://github.com/draft-js-plugins/draft-js-plugins/blob/master/draft-js-emoji-plugin/src/index.js

![image](https://cloud.githubusercontent.com/assets/20340782/21072288/8044b83c-bed6-11e6-8314-943088a4ab2f.png)

And this is the bundled module's same file:

![image](https://cloud.githubusercontent.com/assets/20340782/21072331/dd0d8548-bed7-11e6-9d40-da54a4314c11.png)

**Comment by nikgraf** [comment]
@Hapet95 yes, that was a bug in beta8. We fixed it and released beta9 the day after 😄 can you verify it's working with beta9?

**Comment by Hapet95** [comment]
now it's okay! thanks! :)
