### ISSUE TITLE
Video Plugin + Block Decorators

### ISSUE THREAD

**Issue by nikgraf** [draft-js-plugins/draft-js-plugins#608]
There are a few issues with the video plugin. For example

- the focus outline is not shown if focused (you can focus the block by clicking next to it)
- resizing a video with the resizeable plugin is not working

@mzbac do you have time to look into these issues?

**Comment by mzbac** [comment]
@nikgraf I think those two decorators need to discuss, currently the video component is taking full size of its atomic block.. and it has user interaction such as play, pulse. do you think we need apply outline of the default video component.. if we need to do so then video player will has the padding around the component . feels break the video player's styles..
