### ISSUE TITLE
Entry and positionSuggestions components should be in the Mention Plugin

### ISSUE THREAD

**Issue by svnm** [draft-js-plugins/draft-js-plugins#611]
For the mentions-plugin I don't understand why `Entry` and `positionSuggestions` components are not included in the plugin. Then we could simply import `Entry` to use and `positionSuggestions` would just be internal.

```
import { Entry, positionSuggestions} from './components/Mention/mentions'
const mentionPlugin = createMentionPlugin({
  mentions,
  positionSuggestions,
  theme: mentionsStyles
})
```

Would become: 

```
const mentionPlugin = createMentionPlugin({
  mentions,
  theme: mentionsStyles
})
const { Entry } = mentionPlugin
```

I could probably setup a PR for this if it sounds good.

**Comment by simsim0709** [comment]
Maintainers are working on mention version 3.0 and its api will be different (#1074)

I will close this for now, if it's still relevant you can reopen it.

Thank you 👍

**Comment by juliankrispel** [comment]
this is actually a good point

**Comment by juliankrispel** [comment]
I'll reopen this because I think it should go into the mentions plugin

**Comment by sibelius** [comment]
what is the use case to expose Entry?

**Comment by svnm** [comment]
I just thought this was a more consistent way of doing it. Not a big deal, so happy for the issue to be closed as I don't think anyone minds the current approach of using the positionSuggestions function. Also the API has changed a little in the current version so looks like this is not as relevant.
