### ISSUE TITLE
Inline Toolbar Plugin Release?

### ISSUE THREAD

**Issue by baldwmic** [draft-js-plugins/draft-js-plugins#613]
I'm using the [official npm package](https://www.npmjs.com/package/draft-js-inline-toolbar-plugin) for the `draft-js-inline-toolbar-plugin` and the version is `2.0.0-beta6`. When can we expect a release for latest changes (especially #555)?

**Comment by stevewillard** [comment]
The latest version is
`"draft-js-inline-toolbar-plugin": "2.0.0-beta9"`

you should be able to install that version, which has that fix.

**Comment by inv8der** [comment]
Just fyi, the latest version according to npm is still `2.0.0-beta6`, so running `npm install draft-js-inline-toolbar-plugin` will install that version. You'll have to specify the version number until the latest tag is fixed... unless that's intentional

**Comment by baldwmic** [comment]
thank you @stevewillard and @inv8der. gonna close this
