### ISSUE TITLE
Module not found: Error: Can't resolve 'draft-js-drag-n-drop-plugin'

### ISSUE THREAD

**Issue by TheGent** [draft-js-plugins/draft-js-plugins#614]
How can I use the draft-js-drag-n-drop-plugin

**Comment by Alex-ray** [comment]
Seriously wtf

**Comment by nikgraf** [comment]
@TheGent sorry for getting back to so late. I recently added documentation for the drag & drop plugin here: https://www.draft-js-plugins.com/plugin/drag-n-drop

@Alex-ray Are you referring to? The issue, the comment or because it wasn't documented? In any case your comment doesn't seem appropriate in any case. Can you explain?

**Comment by Alex-ray** [comment]
My apologies @nikgraf , the comment was uncalled for and came from pure frustration. 

Thank you for updating the documentation. The frustration came from trying to use the advanced image  example on the website only to find out that the `draft-js-drag-n-drop-upload-plugin` wasn't  even on npm. 

I ended up forking the (draft-js-drag-n-drop-upload-plugin)[https://github.com/draft-js-plugins/draft-js-plugins/tree/master/draft-js-drag-n-drop-upload-plugin] and implementing it myself. 

I might suggest removing that example from the documentation until its fixed.

Thanks for what you all do and I am happy to help here if you need it 🙂

**Comment by nikgraf** [comment]
all good, thanks for the apologising!

There is an open PR https://github.com/draft-js-plugins/draft-js-plugins/pull/733, but I didn't have time to look at it. If you have time and motivation to contribute would be interesting to open another PR for the upload plugin or contribute to the existing one. Don't feel pushed to work on it, but help would be very much appreciated :)

**Comment by nikgraf** [comment]
Yeah, removing it from the docs until it's ready makes a lot of sense! Will do that
