### ISSUE TITLE
Undo forces page reloading

### ISSUE THREAD

**Issue by lednhatkhanh** [draft-js-plugins/draft-js-plugins#616]
I notice that when there is just blank text, everything is fine, but with emoji or hashtag or link, the undo button will force the page to reload.

**Update**: I also notice that there is a question mark at the end of the page url (react-router)

**Comment by simsim0709** [comment]
Hi, @lednhatkhanh 

Is this issue still existing? Then, can you provide a reproduction link(codesandbox) so I can look into it?

Thank you
