### ISSUE TITLE
Mentioned seems to have a bug, which leads to the mentioned list cannot disappear

### ISSUE THREAD

**Issue by hjyue1** [draft-js-plugins/draft-js-plugins#619]
First of all to say sorry, English is not my native language, expression is not very good
I am in my project and website https://www.draft-js-plugins.com/plugin/mentionFound the same bug。When draft-js-plugins.com trigger mentioned：
Steps:
1. A space character + @ (trigger mentioned list)
2. Remove the @ character
3. mentioned List cannot disappear
Hope to get help

**Comment by mzbac** [comment]
@hjyue1  can you tell more details of the bug? for example, which browser you are using, how did you remove @ character. and can you open the dev console see if any errors when mention list didn't disappear.

**Comment by hjyue1** [comment]
@mzbac  Thank you very much for your help。
Browser is chrome version number: 55.0.2883.95 (64 - bit)
I turned on the console, there is no any error message
I in this website of https://www.draft-js-plugins.com/plugin/mention, a Simple Example
Steps:
1. First character is a space, the second character is @，(Mentioned  list appears at this time)
2. Press the keyboard brcksprce  Delete the second character Spaces (Editor only a space inside, but Mention list has not disappeared)
I think the correct logic is remove @ after mentioned list should disappear

**Comment by hjyue1** [comment]
Recorded a GIF don't know if you can open:http://7xt3ii.com1.z0.glb.clouddn.com/img.gif

**Comment by hjyue1** [comment]
And have this case, the performance of weird 
url:http://7xt3ii.com1.z0.glb.clouddn.com/img3.gif

**Comment by hjyue1** [comment]
[gif](http://7xt3ii.com1.z0.glb.clouddn.com/img.gif)

**Comment by hjyue1** [comment]
`<img style="-webkit-user-select: none" src="http://7xt3ii.com1.z0.glb.clouddn.com/img.gif">`

**Comment by mzbac** [comment]
@hjyue1 
Thanks for those details, there definitely is bug. are you interested to make PR to fix it?

**Comment by Revln9** [comment]
yes  it's a bug , i've noticed this too when i was tweaking the regex's , and i came up with a fix , problem is i don't really remember what i did... , so i'll post it when i find it.

**Comment by hjyue1** [comment]
@mzbac Very grateful for your invitation, I feel very honored
I found the problem here draft-js-mention-plugin/src/MentionSuggestions/index.js;
In line 130, When the first character is a space, @ is the second character,  anchorOffset = 1 , Return true  result in mentioned List cannot disappear 

code:
127    const selectionIsInsideWord = leaves
128      .filter((leave) => leave !== undefined)
129      .map(({ start, end }) => (
130        (start === 0 && anchorOffset === 1 && anchorOffset <= end) || // @ is the first character
131        (anchorOffset > start + 1 && anchorOffset <= end) // @ is in the text or at the end
132      ));


My solution is：Because this situation is special so I add two judgment
129      .map(({ start, end }) => (
130       const plainText = editorState.getCurrentContent().getPlainText();
131        (start === 0 && anchorOffset === 1 && plainText.charAt(anchorOffset) !== '@' && /\@/g.test(plainText)  && anchorOffset <= end) || // @ is the first character

Maybe I am this way are stupid, but for the moment can be solved the bug, looking forward to have a better solution

**Comment by hjyue1** [comment]
@Revln9 Thank you for your answer

**Comment by nikgraf** [comment]
Just merged a fix by @hjyue1 https://github.com/draft-js-plugins/draft-js-plugins/pull/621
