### ISSUE TITLE
Load saved mentions in editor

### ISSUE THREAD

**Issue by suhair** [draft-js-plugins/draft-js-plugins#622]
I am saving draftjs content and deserializing it using convertFromRaw and convertToRaw methods. It works expected but when I am dipslaying the deserialized content, formatting styling of mentioned content is lost. Following is the snippet I used to display the saved content.

```
var converted = convertFromRaw(this.beat.editorContent);
return <Editor  plugins={plugins} editorState={ EditorState.createWithContent(converted)  }> </Editor>
```

I have loaded the plugin and styles using 

```
import createMentionPlugin, { defaultSuggestionsFilter } from 'draft-js-mention-plugin'; 
import 'draft-js-mention-plugin/lib/plugin.css';
import { fromJS } from 'immutable';

const mentionPlugin = createMentionPlugin();
const { MentionSuggestions } = mentionPlugin;
const plugins = [mentionPlugin];
```

Have I missed anything?

**Comment by mzbac** [comment]
@suhair draft-js-plugin-editor is using onChange method to mount decorators.. therefore you need to pass onChange method to editor even you just want to display the content..

**Comment by suhair** [comment]
Thanls @mzbac . I have now placed onChange and converted mention data as suggested in https://github.com/draft-js-plugins/draft-js-plugins/blob/master/FAQ.md#why-are-mentions-broken-after-using-convertfromraw-and-throwing-an-error. Now its working fine.

**Comment by abelski21** [comment]
@suhair I'm trying to do the opposite, I want to get the deserialized value of editorState with the mentions formatted content. So for example, I have a button when on click, it will display the html value of editor. How could I get the <span> wrapper of the mention component with its style from the editorState?

Thanks in advance.

**Comment by mchaledg19** [comment]
Hi I need your help I have same issue. 
I am trying to save data in html format but when I save the data with "mention" Like @Juan Dela Cruz I will only save as plain text. I want to format it with a popover like this

![image](https://user-images.githubusercontent.com/46014163/60175209-6ec3c580-9845-11e9-9db6-cec8d584049f.png)
