### ISSUE TITLE
A about Mention plugin Very weird bug

### ISSUE THREAD

**Issue by hjyue1** [draft-js-plugins/draft-js-plugins#623]
![img4](https://cloud.githubusercontent.com/assets/14873240/21473937/6168a55c-cb53-11e6-9450-dc97923ed072.gif)
The above figure can observe GIF
steps：
1.According to the first keyboard key: the blank space （Here for a single character）
2.According to the second keyboard key: the blank space （Here for a single character）
3.According to the third keyboard keys: @ （Here for a single character)
4.The cursor move back one character at a time
Bugs are: there is three blanks in the editor and a @ (a total of four characters)
In the fourth step, it is weird to copy one more characters

**Comment by hjyue1** [comment]
Hope to get help

**Comment by paulyoung** [comment]
I'm experiencing similar issues in https://github.com/mjrussell/draft-js-autocomplete-plugin-creator/issues/9#issuecomment-271358041

@hjyue1, did you every figure anything out?

**Comment by freedomlang** [comment]
@hjyue1 Don't quite understand what you want to description, and if you still having this issue, please let us know.
