### ISSUE TITLE
Mentions - Doesn't popup when swapping EditorState

### ISSUE THREAD

**Issue by homerlex** [draft-js-plugins/draft-js-plugins#624]
We have an app the shows a list of documents down the left side of the page and has an edit component on the right.

When the user selects a document we populate the editor with its contents.

We keep the EditorState for each document in our redux store.  This all works great except for the fact that mentions only work for the first document that is selected.

After the user selects a second document the mention popup doesn't appear.  In the debugger I can see that register is never called in draft-js-mention-plugin/lib/index.js.

NOTE: if the user goes back and re-selects the first document the mentions work again.

Here is the meat of our component:

```
// Defines the plugin
const mentionPlugin = createMentionPlugin();
const { MentionSuggestions } = mentionPlugin;
const plugins = [mentionPlugin]; 

    onChange = (currentEditorState) => {
        // dispatches an action that updates the docuemnt's editorState in redxx
    };
    
    onAddMention = (data) => {
        ...
    };

    onSearchChange = ({ value }) => {
        ...
    };
  
  
  render () {
  	...
    <Editor
        editorState={this.props.document.editorState} // this comes from redux
        onChange={this.onChange}
        plugins={plugins}        
    />
    <MentionSuggestions
        onSearchChange={this.onSearchChange}
        suggestions={this.state.suggestions}
        onAddMention={this.onAddMention}
    />
    ...
```
    
Any suggestions on how to get this to work?  I even tried storing separate instances of mentionPlugin for each instance of editorState in redux and doing something like the following in the render but it had the same result.  

```
	// Each doc in redux has its own mention plugin that is instanciated something like:
	mentionPlugin  : createMentionPlugin()
	
	// Our component renders like:

  render () {
      ...
  
      const { MentionSuggestions } = this.props.document.mentionPlugin;
      
      return (
          <div className='editor' onClick={this.focus}>
              <Editor
                  editorState={this.props.document.editorState} // this comes from redux
                  onChange={this.onChange}
                  plugins={[this.props.document.mentionPlugin]}    // this comes from redux              
              />
              <MentionSuggestions
                  onSearchChange={this.onSearchChange}
                  suggestions={this.state.suggestions}
                  onAddMention={this.onAddMention}
              />
          </div>
      )
```
        
I'm obviously missing something here.  Any help is greatly appreciated.

**Comment by mzbac** [comment]
@homerlex I used to have the same issue, when I accidentally shared the mention plugin instance to multiply editor. as far as I know, suggestions position is stored in mention plugin.  can you make check if your individual editor has their own mention plugin instance?

**Comment by homerlex** [comment]
Below is an 'impractical' sample that show the behavior.  To keep things simple I took redux out of the picture but the behavior is the same.  When the page is first rendered the mention popup works.  After I hit the 'Update Editor State' button it stops working.  You can see that `updateEditorState()` puts a new EditorState and mentionPlugin instance on the state.

Is there any way to put a new EditorState on this.state and still have mentions work?

```
class MyEdit extends React.Component {

    constructor(props) {
        super(props);
        this.onAddMention = this.onAddMention.bind(this);
        this.updateEditorState = this.updateEditorState.bind(this);

        this.state = {
            editorState: EditorState.createEmpty(),
            suggestions: fromJS([]),
            mentionPlugin: createMentionPlugin()
        };
    };
    
    onAddMention = (data) => {
        console.log("add mention...");
    };

    onSearchChange = ({ value }) => {
        this.setState({
            suggestions: fromJS([{name: 'Name 1'}, {name: 'Name 2'}])
        });
    };

    onChange = (editorState) => {
        this.setState({
            editorState: editorState
        });
        console.log('onChange');
    };
    
    updateEditorState() {
        const contentState = ContentState.createFromText('editor state set');
        this.setState({
            editorState: EditorState.createWithContent(contentState),
            mentionPlugin: createMentionPlugin()
        })
        console.log('updated Editor State')
    }
    
    render () {
        const { MentionSuggestions } = this.state.mentionPlugin;
       
        return (
            <div>
                <div className='editor' onClick={this.focus}>
                    <Editor
                        editorState={this.state.editorState}
                        onChange={this.onChange}
                        plugins={[this.state.mentionPlugin]}
                    />
                    <MentionSuggestions
                        onSearchChange={this.onSearchChange}
                        suggestions={this.state.suggestions}
                        onAddMention={this.onAddMention}
                    />
                    
                </div>
                <button type="button"
                        className="btn-primary btn"
                        onClick={ this.updateEditorState }>
                    Update Editor State
                </button>
            </div>
        )
    }
}
```

**Comment by mzbac** [comment]
@homerlex  when you use  EditorState.createWithContent(contentState) in your updateEditorState function, you lost all the decorators of previous editorState.  you can try to use editorState push method to update your editorState
https://facebook.github.io/draft-js/docs/api-reference-editor-state.html#push

**Comment by mzbac** [comment]
@homerlex currently all plugin's decorators are set on plugin-editor's componentWillMount method you can see from source code below:
https://github.com/draft-js-plugins/draft-js-plugins/blob/master/draft-js-plugins-editor/src/Editor/index.js#L74

we are working on add a reloadDecorators function which will solve the issue. but I don't know when it will merge into master and release on npm.. but you can refer the PR below to implement a custom  plugin-editor as workaround at the moment.
 
https://github.com/draft-js-plugins/draft-js-plugins/pull/526

**Comment by homerlex** [comment]
Thanks @mzbac.  That explains why were are currently forced to remount our component when changing editorState.

**Comment by homerlex** [comment]
I played a bit with reloadDecorators.  It doesn't work if I do something like 

```
updateEditorState() {
        const contentState = ContentState.createFromText('editor state set');
        this.setState({
            editorState: EditorState.createWithContent(contentState),           
        })        
        this.editor.reloadDecorators();
    }
```

If I put `reloadDecorators()` after `this.setState` the new content doesn't appear.  If I put `reloadDecorators()` before `this.setState` the content changes but the mentions don't work.

If I add another button and move the reloadDecorators call into that action:
```
reloadDecorators() {
        this.editor.reloadDecorators();
}

<button type="button"
  className="btn-primary btn"
  onClick={ this.reloadDecorators }>
  Reload decorators
</button>
```

... and hit that after I hit the "Reload decorators" button it works.

So, the question is, where/how would I have to call `reloadDecorators()` after changing `this.state.editorState`?

**Comment by mzbac** [comment]
@homerlex  can you try 
```
this.setState({
            editorState: EditorState.createWithContent(contentState),           
        },() =>  this.editor.reloadDecorators()) ;
```
if it still doesn't work, you have to copy resolveDecorators logic to get all the decorators and put it in your new editorState on your updateEditorState function.

**Comment by homerlex** [comment]
@mzbac - putting the reloadDecorators() call on the setState callback does indeed do the trick.  I'll let you know if I stumble upon any other issues.

**Comment by homerlex** [comment]
@mzbac - I'm having some other issues with mentions and editorState reloading.  

If I change my code to set focus on the editor right after I call `reloadDecorators` (as shown below) the mention popup stops working.   This issue is easy to duplicate by having a button that calls the following code:

```
    updateEditorState() {
        const contentState = ContentState.createFromText('editor state set');
        this.setState({
            editorState: EditorState.createWithContent(contentState),
        },() => {
            this.editor.reloadDecorators();
            this.editor.focus();
        }) ;
    }
```

Any idea why this would be?

The issue we are having in our actual application is also related to calling `.focus` after `.reloadDecorators` but the behavior is a bit different than the issue above.  Its also difficult for me to create a simple bit of code to post here that reproduces the issue (though its consistent in our app).  We have a condition where if the current text in the editor contains a "@" (its not a mention) and we do a `.reloadDecorators`  followed by `.focus` not only does the mention popup not appear but also when you  type "@" the cursor gets messed up and strange behavior occurs when typing.   The following video shows the behavior in we are seeing in our app.  You can't see it in the video but I hit a button after typing @nonmention that triggers the problem.  You can see the after I trigger it when I type "@" some text disappears and then some other odd stuff happens:  https://www.screencast.com/t/I4kaphrpDK

Let me know if you have any thoughts on this.

**Comment by iEchoic** [comment]
Anyone find a solution to this yet? Sounds like my issue is the same - on a single page, I have multiple editors. The last editor loaded seems to "claim" the MentionSuggestions component, so the mentions always work on the last-rendered editor and are broken on all others.

**Comment by chenyuejie** [comment]
Works fine by using EditorState.push to change the content of editor, but the editor's old state(like redo, undo) is persist.

```
this.setState({ 
  editorState: EditorState.push(this.state.editorState, 
  ContentState.createFromText(newContent))
})
```

@iEchoic  for multiple editors, you should create mentionPlugin for each instance.

**Comment by nikgraf** [comment]
@iEchoic exactly as @chenyuejie mentioned.
@homerlex still having an open issue or is it resolved?

**Comment by homerlex** [comment]
@nikgraf  - The behavior mentioned in my last comment is still an issue.

**Comment by nikgraf** [comment]
@homerlex ok, not sure when I get to this. Ideally in the next 2 weeks, but can't promise anything

**Comment by inchr** [comment]
@chenyuejie @nikgraf I've the same problem of @iEchoic ... I've 2 editors in the same page, 1 with the mentions/emoji plugin and another is on readOnly. When I write a mention on the first editor, the popover of the mentions/emojis is opened in the second editor (that in theory doesn't load the plugins either)

Any suggestions ?

**Comment by nikgraf** [comment]
@iEchoic @inchr you need to multiple MentionSuggestions. One for each editor! Please let me know if that helps? Here a longer explanation in the FAQ https://github.com/draft-js-plugins/draft-js-plugins/blob/master/FAQ.md#can-i-use-the-same-plugin-for-multiple-plugin-editors

**Comment by terencechow** [comment]
Note another issue with `EditorState.push` is that it maintains the undo stack.

if I have a page with 1 editor, that is populated with data from taskId 1, and I have a button for 'next task' which just updates the state to use data from taskId 2, I don't want the undo stack to be maintained between different tasks. Hence `EditorState.push` is not a complete solution. We need a way to set the EditorState and reload the decorators that already exist

**Comment by igorlesnenko** [comment]
Any progress on this?

**Comment by fran-cadenas** [comment]
Hello, any solution for this ? I'm still having problems to load the mention-plugin when loading state form db with convertFromRaw.

**Comment by sibelius** [comment]
try this

 ```jsx
const plugins = useMemo(() => {
    const mentionPlugin = createMentionPlugin({
      mentionPrefix: '@',
      mentionComponent: Mention,
    });
    const linkifyPlugin = createLinkifyPlugin();

    return [linkifyPlugin, mentionPlugin];
  }, []);

const decorators = plugins.reduce((acc, p) => [...acc, ...p.decorators], []);

const decorator = new CompositeDecorator(decorators);

      const editorState = EditorState.createWithContent(
        convertFromRaw(contentState),
        decorator,
      );

return (<Editor editorState={editorState} />
```

**Comment by fran-cadenas** [comment]
@sibelius Thanks, it seems to work and load the plugin correctly. The problem now is that when I enter the mentions trigger ('$' in my case) it crashes:

```
index.js:54 Uncaught TypeError: this.props.getEditorState is not a function
    at MentionSuggestionsPortal.componentDidMount (index.js:54)
    at commitLifeCycles (react-dom.development.js:16864)
    at commitAllLifeCycles (react-dom.development.js:18219)
    at HTMLUnknownElement.callCallback (react-dom.development.js:149)
    at Object.invokeGuardedCallbackDev (react-dom.development.js:199)
    at invokeGuardedCallback (react-dom.development.js:256)
    at commitRoot (react-dom.development.js:18427)
    at completeRoot (react-dom.development.js:19884)
    at performWorkOnRoot (react-dom.development.js:19813)
    at performWork (react-dom.development.js:19721)
```

**Comment by sibelius** [comment]
from where are you getting the `MentionSuggestionsPortal`?

try

```jsx
const { plugins, MentionSuggestions } = useMemo(() => {
      const mentionPlugin = createMentionPlugin({
        mentionPrefix: '@',
        mentionComponent: Mention,
      });
      const linkifyPlugin = createLinkifyPlugin();

      return {
        plugins: [linkifyPlugin, mentionPlugin],
        MentionSuggestions: mentionPlugin.MentionSuggestions,
      };
    }, []);

   return (<MentionSuggestions
            open={isOpen}
            onOpenChange={(newOpen) => setIsOpen(newOpen)}
            onSearchChange={onSearchChange}
            suggestions={suggestions}
          />)
```

**Comment by fran-cadenas** [comment]
@sibelius I'm currently using state to manage the plugins:

```javascript
const [bodyMentionsPlugin] = useState(createMentionPlugin({
  entityMutability: 'IMMUTABLE',
  theme: mentionStyles,
  mentionPrefix: '$',
  mentionTrigger: '$',
  supportWhitespace: false,
}));

const _bodyPlugins = useMemo(() => [ ...bodyPlugins, bodyMentionsPlugin ]);

const getDecoratorFormPlugins = (plugins) => {
  const _decorators = plugins.reduce((decoratorArray, { decorators = [] }) => [
    ...decoratorArray,
    ...decorators,
  ], []);

  return new CompositeDecorator(_decorators);
};
const loadBodyFromContent = (rawContent) => {
    const content = convertFromRaw(rawContent);
    const decorators = getDecoratorFormPlugins(_bodyPlugins);
    setBodyState(EditorState.createWithContent(content, decorators));
};

 const { MentionSuggestions: BodyVariableSelector } = bodyMentionsPlugin;
```
When I tell the component to load from a rawContent it triggers the solution you told me before. The plugin is actually in state and I get it from there. To me it seems as the `PluginEditor` is not injecting the `getEditorState` prop correctly...

**Comment by sibelius** [comment]
I would rather useMemo instead of useState

can you try with that?

**Comment by fran-cadenas** [comment]
@sibelius Same issue:

```javascript
const bodyMentionsPlugin = useMemo(() => createMentionPlugin({
  entityMutability: 'IMMUTABLE',
  theme: mentionStyles,
  mentionPrefix: '$',
  mentionTrigger: '$',
  supportWhitespace: false,
}), []);

const _bodyPlugins = useMemo(() => [ ...bodyPlugins, bodyMentionsPlugin ]);

const getDecoratorFormPlugins = (plugins) => {
  const _decorators = plugins.reduce((decoratorArray, { decorators = [] }) => [
    ...decoratorArray,
    ...decorators,
  ], []);

  return new CompositeDecorator(_decorators);
};
const loadBodyFromContent = (rawContent) => {
    const content = convertFromRaw(rawContent);
    const decorators = getDecoratorFormPlugins(_bodyPlugins);
    setBodyState(EditorState.createWithContent(content, decorators));
};

 const { MentionSuggestions: BodyVariableSelector } = bodyMentionsPlugin;
```

**Comment by sibelius** [comment]
can you try with master version?

**Comment by fran-cadenas** [comment]
> can you try with master version?

Sorry, either I'm having problems installing such version or don't know how. I'm currently using:

```
    "draft-js-mention-plugin": "^3.1.5",
    "draft-js-plugins-editor": "^3.0.0",
```
