### ISSUE TITLE
Question: Linking via Inline Toolbar Plugin

### ISSUE THREAD

**Issue by JohnONeill** [draft-js-plugins/draft-js-plugins#625]
Is there an "add link" option for the inline toolbar plugin? 

While checking out https://github.com/draft-js-plugins/draft-js-plugins/issues/134 I noticed https://cloud.githubusercontent.com/assets/4349324/14179943/467ef0f0-f761-11e5-9571-c5101792d552.gif, which suggests @bkniffler brought over the ability to add links from his [awesome] wysiwyg repo. It doesn't seem like that's actually an option though, looking at the list of inline toolbar button options at https://github.com/draft-js-plugins/draft-js-plugins/tree/master/draft-js-buttons/src/components – but maybe the option's there / I'm just missing it.

**Comment by divyenduz** [comment]
I think what you are looking for is the [anchor plugin](https://www.draft-js-plugins.com/plugin/anchor). Does this solve your issue?

**Comment by freedomlang** [comment]
@JohnONeill  I'll close this issue, cause there has been no response for more information. If you still got question above, please feel free to reopen or open a new issue. ❤️
