### ISSUE TITLE
Mention suggestion portal get closed when trigger character is also a part of the suggestions.

### ISSUE THREAD

**Issue by prashantagarwal** [draft-js-plugins/draft-js-plugins#626]
So I am facing this issue when mentionTrigger is also a part of the suggestion list and when I try to search for that suggestion and type trigger as a search string, the autosuggestion gets closed.

**Comment by hjyue1** [comment]
I seem to have encountered similar problems, two consecutive @ mentioned list is closed

**Comment by prashantagarwal** [comment]
@nikgraf is this a bug or it is not handled by the plugin ?
