### ISSUE TITLE
About Sticker-plugins Keyboard (window) Ctrl + A Unable to select all

### ISSUE THREAD

**Issue by hjyue1** [draft-js-plugins/draft-js-plugins#627]
I found the window system， Sticker-plugins，Keyboard  Ctrl + A Unable to select all，And the cursor moves to the end

**Comment by freedomlang** [comment]
@hjyue1  Is this issue still exists? can you provide your os, browser, and version of draft-js-plugins. It would be help for us to check the problem you mentioned above
