### ISSUE TITLE
Documentation Pages

### ISSUE THREAD

**Issue by nikgraf** [draft-js-plugins/draft-js-plugins#63]
- [x] add social bar to the bottom of every page before the footer - `I have added this section to bottom of all pages. May be options should better be aligned in a single line - plz suggest @nikgraf.`
- [x] add a section "Team" to the homepage with a picture & links (both twitter) to https://twitter.com/jyopur https://twitter.com/nikgraf https://twitter.com/mxstbr https://twitter.com/juliandoesstuff
- [x] add section "Discussion and Support" to bottom of the homepage & readme with
  Join the channel #plugin-editor after signing into the DraftJS [Slack organisation](https://draftjs.herokuapp.com)!
- [x] allow Code component to be collapsed or expanded. the initial state can be passed in via props, but it should be uncontrolled - `this is done but atm, code clocks expand / collapse on mouse clicks this can be improved @nikgraf  suggestions plz`.

**Comment by nikgraf** [comment]
- [ ] the link should wrap the images as well on team members

**Comment by nikgraf** [comment]
- [ ] add https://github.com/mjrussell to the team

**Comment by jpuri** [comment]
[ ] - on emoji page replace existing use of hashtag plugin by new emoji plugin

**Comment by juliankrispel** [comment]
Closing for issue cleanup - If you need this issue and think it should remain open please let us know why, thank you
