### ISSUE TITLE
Clearificaition linkify plugin

### ISSUE THREAD

**Issue by aight8** [draft-js-plugins/draft-js-plugins#630]
What's the exact use case for the linkify plugin in the current form?
Links are not usable in draft js (make no sense), decorators are not supported by draft.js renderers.
So it mark links very good but it's either in the content state nor it can be reused by renderers.

So currently it's only usable when the Editor is in read only mode - this should be better documented.

Thanks for clarification 👍

**Comment by jebarjonet** [comment]
The plugin currently does nothing except showing links in the Draft JS editor as links. You have to catch links in a `convertToHTML` to convert links to real `<a>` tags when you export your content state into HTML content.

**Comment by bufordtaylor** [comment]
I'm confused as to the point of the linkify plugin if it doesn't actually create an anchor entity.

**Comment by mattgreenfield** [comment]
Is this a bug that is worth looking to fix or is it a deliberate decision?

**Comment by tzerchyuan** [comment]
Is this still the case? That Linkify does not create link entities in the Content State for the links that it detects?

What is the best way to insert a Link entity along with the linkified text?
