### ISSUE TITLE
Mentions plugin doesn't trigger when a decorator uses the same regex

### ISSUE THREAD

**Issue by athomann** [draft-js-plugins/draft-js-plugins#631]
I've been using a decorator to style mentions from createWithContent && createFromText but this blocks the ability to trigger the mentions plugin.

**Comment by THook** [comment]
Have you found any workaround? I have a use case where user mentions existing tags or creates one if it doesn't exist already. Mention plugin actually gets triggered on 2.0.0-rc5 but overrides decorators starting with the same prefix ('#' in my case).

Any idea?
