### ISSUE TITLE
Issues with unwanted forced selection

### ISSUE THREAD

**Issue by paulyoung** [draft-js-plugins/draft-js-plugins#637]
This has been described in detail in https://github.com/mjrussell/draft-js-autocomplete-plugin-creator/issues/9 including animated gifs and a demo branch – https://github.com/mjrussell/draft-js-autocomplete-plugin-creator/issues/9#issuecomment-271561909

As explained in https://github.com/mjrussell/draft-js-autocomplete-plugin-creator/issues/9#issuecomment-271861506, I stopped using `draft-js-plugins-editor` and updated my own `Editor` wrapper component with parts of `PluginEditor` to make the plugin work, and things work fine.

If I manage to narrow down the cause of the issues, I'll report back here.

**Comment by paulyoung** [comment]
I've tracked this down to this line: https://github.com/draft-js-plugins/draft-js-plugins/blob/3d81349c9f0c606a0924d183ca318aa96b54872b/draft-js-plugins-editor/src/Editor/index.js#L75

If I make the following change, everything works as expected:

```diff
-    this.onChange(moveSelectionToEnd(editorState));
+    this.onChange(editorState);
```

**Comment by paulyoung** [comment]
The only difference appears to be that after `componentDidMount`, in the selection state when using `moveSelectionToEnd`, `hasFocus` is `false`.

Without `moveSelectionToEnd`, `hasFocus` is `true`.

**Comment by paulyoung** [comment]
I'm trying to work around this by setting the focus in my wrapper component, but running into https://github.com/draft-js-plugins/draft-js-plugins/issues/628.

**Comment by paulyoung** [comment]
As explained in https://github.com/draft-js-plugins/draft-js-plugins/issues/628#issuecomment-271920682, I'm doing this in my component and everything now works as expected:

```javascript
componentDidMount() {
  window.requestAnimationFrame(() => {
    this.refs.editor.focus();
  });
}
```

**Comment by bengotow** [comment]
Hey folks—just wanted to chime in here, I think `moveSelectionToEnd` should be made into a boolean option on the component. In my case, the editorState I'm assigning to the editor already has a selection state that has been determined via more advanced logic. (Maybe it could detect whether selection appears to be the default and only force it in that case?)
