### ISSUE TITLE
Pasting is losing some new lines?

### ISSUE THREAD

**Issue by terencechow** [draft-js-plugins/draft-js-plugins#638]
Steps to recreate:
1. Create a Google Doc.
2. Type text as such:

One line
Two line
Three line

3. Copy the whole text you have written in Google Doc and paste it into the Draft Js website here: https://facebook.github.io/draft-js/
4. Do the same thing at the Draft Js Plugins website here: https://www.draft-js-plugins.com/

Notice that at the Draft Js Plugins website the text is shown as:

One lineTwo lineThree line 

instead of showing it properly on 3 lines. Is there something draft-js-plugins is doing that is changing the behaviour of the pasting? Note that this occurs from pasting from Google Doc but not from other webpages... If you want to direct me to where this might be caused I can investigate, but at the moment I'm having trouble determine where the problem is arising from

**Comment by bummzack** [comment]
I'd like to know how to fix that as well. It's really important for me that pasted text gets inserted as separate blocks for each line.

Any pointers how to fix, or what might be causing this would be greatly appreciated.

**Comment by bummzack** [comment]
As an update, here's a simple test case:

```jsx
import { Editor, EditorState, Modifier, ContentState } from 'draft-js';
import React from 'react';

class TestEditor extends React.Component
{
  constructor(props) {
    super(props);
    this.state = {
      editorState: EditorState.createEmpty()
    };
    this.handleEditorChange = this.handleEditorChange.bind(this);
    this.handlePastedText = this.handlePastedText.bind(this);
  }

  handleEditorChange(editorState) {
    this.setState({ editorState });
  }

  handlePastedText(text) {
    const { editorState } = this.state;
    const pastedBlocks = ContentState.createFromText(text).blockMap;
    const newState = Modifier.replaceWithFragment(
      editorState.getCurrentContent(),
      editorState.getSelection(),
      pastedBlocks
    );
    this.handleEditorChange(EditorState.push(editorState, newState, 'insert-fragment'));
    return true;
  }

  render() {
    return (
      <Editor
        editorState={this.state.editorState}
        onChange={this.handleEditorChange}
        handlePastedText={this.handlePastedText}
      />
    );
  }
}

export default TestEditor;
```
The above works as expected when pasting text with multiple lines (eg. from Plaintext). It creates a new block for each line.

When replacing `import { Editor, EditorState, Modifier, ContentState } from 'draft-js';`  with:

```
import Editor from 'draft-js-plugins-editor';
import { EditorState, Modifier, ContentState } from 'draft-js';
```
It inserts the text as single block instead.
I'm using the `2.0.0-beta10` version.

**Comment by nikgraf** [comment]
@bashkos any chance you can investigate why that's the case?

**Comment by bashkos** [comment]
I'll try. On this holidays too =)

**Comment by bradbirnbaum** [comment]
I am also observing the same thing.   Any chance for a fix?

**Comment by freedomlang** [comment]
@bashkos @bradbirnbaum @bummzack @terencechow guys, is it still happen on the latest version ?

**Comment by terencechow** [comment]
Why don’t you just follow the steps in my original post to see if it’s still happening? My steps take like 5 minutes.

**Comment by simpleshadow** [comment]
Had the same issue. See facebook/draft-js#231. I'm now using HubSpot/draft-convert to resolve.

**Comment by Dremuchev** [comment]
I have the same problem! Ordered list with empty line pasted as ordered list without empty line. And my custom block pasted as unstyled block with '\n' after each block.
