### ISSUE TITLE
AlignmentToolbar is not hidden when focused item is deleted

### ISSUE THREAD

**Issue by kentmclean** [draft-js-plugins/draft-js-plugins#639]
The issue can be observed in the `Alignment + Resize + Focus + Drag&Drop Example` sample on the `Image` plugin page (https://www.draft-js-plugins.com/plugin/image).

1. Click on the image to provide it focus. The alignment toolbar will appear.
2. Press the `Backspace` or `Delete` key on the keyboard. The image will be deleted, but the AlignmentToolbar element will remain.

The AlignmentToolbar will remain visible until another image (or other element that supports the AlignmentToolbar) is focused and unfocused.

**Comment by kentmclean** [comment]
potential solution: provide the `src/createDecorator.js` with a `componentWillUnmount` lifecycle method that sets the `visibleBlock` value within the `store` to `null`:

`  componentWillUnmount = () => {
      store.updateItem('visibleBlock', null);
  }`

**Comment by andpor** [comment]
issue still there...and it is not even marked as defect on github...weird...

**Comment by ramrami** [comment]
I just created a PR #804 to fix this issue, hopefully it will be merged soon 😄
