### ISSUE TITLE
Video Plugin is not working

### ISSUE THREAD

**Issue by kuatro** [draft-js-plugins/draft-js-plugins#641]
`draft-js 0.9.1 + draft-js-plugins-editor 2.0.0-beta6 + draft-js-video-plugin 2.0.0-beta.5`

Plugin is detecting video source and video url, but not inserting a video component. Below you can see content state after I pasted a link to Youtube. Thus the link appears as plain unstyled text.
Could you please give an advice how to fix it?

```
{  
  "entityMap":{  },
  "blocks":[  
    {  
      "key":"5loer",
      "text":"Pasting video:",
      "type":"unstyled",
      "depth":0,
      "inlineStyleRanges":[  ],
      "entityRanges":[  ],
      "data":{  }
    },
    {  
      "key":"f2eoc",
      "text":"https://www.youtube.com/watch?v=JCZJ05ygPk0",
      "type":"unstyled",
      "depth":0,
      "inlineStyleRanges":[  ],
      "entityRanges":[  ],
      "data":{  }
    },
    {  
      "key":"707o1",
      "text":"",
      "type":"unstyled",
      "depth":0,
      "inlineStyleRanges":[  ],
      "entityRanges":[  ],
      "data":{  }
    }
  ]
}
```

**Comment by mzbac** [comment]
I think that auto insert video is changed,  now you have to manually insert video component- https://github.com/draft-js-plugins/draft-js-plugins/blob/master/docs/client/components/pages/Video/CustomAddVideoVideoEditor/index.js#L1

or you can put your custom login into handlePastedText for something like:

```
 handlePastedText: (text, html, { getEditorState, setEditorState }) => {
      if (!autoHandlePastedText) return false;
      if (isVideo(text)) {
        setEditorState(addVideo(getEditorState(), getVideoSrc(text)));
        return true;
      }
      if (utils.isYoutube(text)) {
       setEditorState(addVideo(getEditorState(), utils.getYoutubeSrc(text)));
       return true;
      }
      if (utils.isVimeo(text)) {
        setEditorState(addVideo(getEditorState(), utils.getVimeoSrc(text)));
       return true;
      }
      return false;
    }
```

**Comment by kuatro** [comment]
@mzbac For some reason `handlePastedText` is not executing:
```
const videoPlugin = createVideoPlugin({
  handlePastedText: () => {
    console.log('Hello, world!')
  }
});

**Comment by mzbac** [comment]
@kuatro  you shouldn't pass handlePastedText to video plugin, you need pass the handlePastedText to plugin editor..

**Comment by kuatro** [comment]
@mzbac I think the problem isn't in pasting videos only. This example is not working too: [SimpleVideoEditor](https://github.com/draft-js-plugins/draft-js-plugins/blob/master/docs/client/components/pages/Video/SimpleVideoEditor/index.js)

Is the documentation outdated now?

**Comment by lucidlive** [comment]
@kuatro I'm experiencing the same issue - did you resolve the problem?

**Comment by mzbac** [comment]
@kuatro @lucidlive sorry for the delay,  I think the new video-plugin isn't release on npm. can you try use it from master branch's code

**Comment by lucidlive** [comment]
Thanks for the reply @mzbac . It's the strangest thing because I had the draft-js-video-plugin working with no issues at all. Then, just recently I noticed that it was not working. Like @kuatro , I examined the contentState and editorState and video links are not being picked up by the plugin... no errors or anything, just nothing. I tried installing different versions of draft-js-plugins-editor to no avail. The other plugins I'm using (mention, emoji, image) are all working fine. 

I'm using the video plugin in its simplest form:
```
import createVideoPlugin from 'draft-js-video-plugin';
const videoPlugin = createVideoPlugin({ autoHandlePastedText: true });
```

I would love to help nail down the issue so if there's anything I can do to help, let me know!

**Comment by kuatro** [comment]
@lucidlive It also ignoring existing video entities. Another strange thing is the only available version at npmjs.org is `2.0.0-beta.5 `, when here, at master branch, `2.0.0-beta.4`.

**Comment by mzbac** [comment]
@lucidlive the old video plugin was auto-phrasing video url from copyPastedText to video entities. but new video-plugin changed the behaviors. so it's not longer auto-phrasing the video url to video entity from copyPastedText.  you have to manual insert the video entity by yourself.. that means you need to write your own handlePastedText on your plugin-editor. 

```
const videoPlugin = createVideoPlugin();

const plugins = [videoPlugin];

const handlePastedText = (text, html) => {
if (isVideo(text)) {
    videoPlugin.addVideo(this.editorState, { src: videoURL }))
     return true;
  }
}

render() {
    return (
      <div className={editorStyles.editor} onClick={this.focus} >
        <Editor
          editorState={this.state.editorState}
          onChange={this.onChange}
          handlePastedText={handlePastedText}
          plugins={plugins}
          ref={(element) => {
            this.editor = element;
          }}
        />
      </div>
    );
  }
```

**Comment by lucidlive** [comment]
Hey @mzbac - Thanks again for the reply. Your solution didn't work for me but it got me on track. I believe there is something about the "readOnly" property that is preventing insertAtomicBlock. If I set readOnly to true, I'm able to add custom blocks. When false, however, inserting seems to do nothing.

**Comment by RoeeEidan** [comment]
The issue is in the getSrc function (in DefaultVideoCompoent.js).

it's looking for a match with youtube or Vimeo and if it doesn't find it, it returns `undefined`.

It should do a URL validation and return the src if it's valid.

 `
const getSrc = ({ src }) => {
  const { isYoutube, getYoutubeSrc, isVimeo, getVimeoSrc } = utils;
  if (isYoutube(src)) {
    const { srcID } = getYoutubeSrc(src);
    return `${YOUTUBE_PREFIX}${srcID}`;
  }
  if (isVimeo(src)) {
    const { srcID } = getVimeoSrc(src);
    return `${VIMEO_PREFIX}${srcID}`;
  }
  return undefine
};
`
