### ISSUE TITLE
Bug deleting mentions with custom Component.

### ISSUE THREAD

**Issue by GreGGus** [draft-js-plugins/draft-js-plugins#644]
Hey. I'm implementing Mentions on my DraftJS. It's working nice, but I'm facing a bug in order to delete mentions.

There's no problem to "call" mentions and to add them inside our Editor. But when I want to delete the mentions, I see somes bugs.
I can reproduce this bugs on Documentation examples.

=> https://www.draft-js-plugins.com/plugin/mention

I use Custom Mention Component Example, and when i tried to delete, my cursor loose focus and go to the line's begin, and nothing is delet. You can try inside the example. Type : "Hey guys, my name is matthew  and i want to delete properly julian . Thanks"  then try to delete the mentions ... see ? 

Thanks again for your help.

Edit : If you type like 5 chars before the mentions, it's impossible to delete it without bugging.

**Comment by maybeShuo** [comment]
#674 the same problem?

**Comment by reemtariqq** [comment]
any fix for this issue ?

**Comment by freedomlang** [comment]
can not reproduce this bug

![2018-03-28 15 45 08](https://user-images.githubusercontent.com/11409069/38015737-511bce0e-329f-11e8-9326-adc009080c77.gif)

**Comment by reemtariqq** [comment]
@freedomlang it happens when the mention in two words not one word

**Comment by freedomlang** [comment]
@reemtariqq still can not reproduce this bug

![2018-03-28 17 22 35](https://user-images.githubusercontent.com/11409069/38020540-193189a8-32ad-11e8-85e9-0949ee4a8d13.gif)

![2018-03-28 17 23 23](https://user-images.githubusercontent.com/11409069/38020632-57d32fd6-32ad-11e8-9a0b-4a32e3436c9e.gif)

**Comment by reemtariqq** [comment]
@freedomlang change any mention value to be two words 
like mathew : mathew mathew for an example

**Comment by reemtariqq** [comment]
@freedomlang i want to delete the whole block when backspace clicked to delete the whole mention even if it's two words

**Comment by freedomlang** [comment]
that's another bug, right ? I suggest you open a issue.

By the way, the bug you describe is on my todos, will figure it out and try to solve it

**Comment by freedomlang** [comment]
@maybeShuo seems like not the same bug

**Comment by maybeShuo** [comment]
@freedomlang if i change the custom mentionComponent like this:
```
mentionComponent: (mentionProps) => (
  <span
    className={mentionProps.className}          
  >
    {mentionProps.mention.get('name')}
  </span>
)
```
replace  the "mentionProps.children" in the customMention demo with ''mentionProps.mention.get('name')"

![mention](https://user-images.githubusercontent.com/18511169/38025062-96e35028-32b9-11e8-9fec-9b0ef11e7900.gif)
when i try to delete, the cursor go to the line's begin

**Comment by JoeCase** [comment]
I am still having the same problem with this. Anyone find a fix?

**Comment by XieAn2016** [comment]
I am still having the same problem with this. Anyone find a fix?

**Comment by rohit-khanna** [comment]
@JoeCase @XieAn2016 
My issue was pertaining to use a CustomComponent for `mentionComponent` property for this plugin.

My Backspace was behaving weirdly . This post helped me solve the issue: https://github.com/facebook/draft-js/issues/1558
