### ISSUE TITLE
unable to find plugins

### ISSUE THREAD

**Issue by yagneshmodh** [draft-js-plugins/draft-js-plugins#646]
I am unable to find following modules on npm

draft-js-drag-n-drop-plugin
draft-js-drag-n-drop-upload-plugin

Please let me know by when it will be available?

**Comment by hhertogh** [comment]
Hey, I have the same issue. Were you able to fix this?

**Comment by DominikGuzei** [comment]
`draft-js-drag-n-drop-upload-plugin` is still not available on npm

**Comment by marekolszewski** [comment]
I also couldn't find draft-js-drag-n-drop-upload-plugin. I built v2.0.0-beta10 and put it at the following github repo:

https://github.com/marekolszewski/draft-js-drag-n-drop-upload-plugin

Feel free to npm install from this repo while you wait for the package to be created.

**Comment by liperuf** [comment]
thank you @marekolszewski

**Comment by juliankrispel** [comment]
[I can find it on npm o_O](https://www.npmjs.com/package/draft-js-drag-n-drop-plugin)

**Comment by DominikGuzei** [comment]
@juliankrispel we meant the `draft-js-drag-n-drop-UPLOAD-plugin` which is still not available 😉
