### ISSUE TITLE
Needs plugin/editor for displaying content

### ISSUE THREAD

**Issue by elfey** [draft-js-plugins/draft-js-plugins#648]
It's in the title.

I'd like to be able to import data into my editor and display the styled content to my user (highlighted usernames, links, formatting, emojis, etc.), while disabling the possibility of editing for the user.

There aren't really any plug-and-play options out there for this right now. It'd be great if there was.

**Comment by ElegantSudo** [comment]
Bump. It'd be great to have a clean and easy way of displaying the content that's generated with this plugin!
