### ISSUE TITLE
Demos/Tutorials not working

### ISSUE THREAD

**Issue by dpkshrma** [draft-js-plugins/draft-js-plugins#650]
The demos seem to be outdated. I am trying to make focus plugin work, but the [focus demo](https://www.draft-js-plugins.com/plugin/focus) probably contains a lot of code which probably does not pertain to the beta version.

So, I tried to make few adjustments to get it working:
- I copied the `composeDecorators` util directly from the codebase ,since, it is no longer available from [draft-js-plugins-editor](https://github.com/draft-js-plugins/draft-js-plugins/tree/master/draft-js-plugins-editor).
- I used the newly exported `FocusDecorator`.

But, I am using the same `colorBlockPlugin` mentioned in the demo. So, currently, I got stuck at this error:

![selection_018](https://cloud.githubusercontent.com/assets/7024976/22388777/51a92992-e508-11e6-82db-47994601775c.png)

Does anyone know of any up-to-date documentation for the plugins?

**Comment by dpkshrma** [comment]
Ok, so, this time I tried it without `yarn add <pluginName>`.

After directly cloning, from the git repo, I was able to get the plugins working just by following the tutorial w/ minor issues. So, it means that the code in repo is updated but possibly, the version of npm modules was bumped up w/o pointing to updated repo branch. I am just speculating here, since, I haven't used any previous versions of draft js plugins.

Either way, the npm module should be updated, or the code.., if the problem is other way round :P

**Comment by tomconroy** [comment]
Seems like the latest version for the focus plugin is `2.0.0-beta1`. Would be great to get the latest pushed out.

**Comment by kristajg** [comment]
I have plugins-editor & respective plugins all at 2.0.0-beta9 & I can't seem to get nearly any of the tutorials up and running.

 Specifically, the 'Alignment + Resize + Focus + Drag&Drop Example' under Image is throwing this error currently:
![screen shot 2017-03-10 at 12 03 22 pm](https://cloud.githubusercontent.com/assets/2675535/23807044/c0e3a2fa-0589-11e7-829c-9791810a5f75.png)

**Comment by nikgraf** [comment]
Interesting, I'm looking into it!

**Comment by nikgraf** [comment]
I just ran the demos locally after merging some PRs and fixing the demos afterwards. Can you let me know if it works for you now? (I will deploy in a couple minutes)

I'm going to close the issue, but in case you run into troubles please open another issue or reply here again.
