### ISSUE TITLE
Track removing of mentions

### ISSUE THREAD

**Issue by valorize** [draft-js-plugins/draft-js-plugins#654]
Hi @nikgraf do you know if it is possible in draftjs to trigger a method when an entity gets removed from the editor? I would like to create mentions and list them in a sidebar. Furthermore I want synchronize this sidebar when the a mention gets deleted.

**Comment by valorize** [comment]
Ok I found a way how it can be done. It's the same approach taken within the MentionSuggestionsPortal. The componentDidMount method registers the mention with the key and on componentWillUnmount it will unregister it again.

**Comment by pypetey** [comment]
@valorize - how did you get access to mentioned objects? I would like to create a separate list of mentions like you did but I have no idea how to access it.

**Comment by valorize** [comment]
I'm still on it but the following should get you going:
within the constructor of myEditor i have 
```
const myEditor = this;

class Mention extends React.Component<any, any> {
	componentDidMount() {
		myEditor.setState({models: myEditor.state.models.set(this.props.entityKey, this.props.mention)});
	}

	componentWillUnmount() {
		myEditor.setState({models: myEditor.state.models.delete(this.props.entityKey)});
	}

	render() {
		return (
			<span
				className={this.props.className}
				contentEditable={false}
			>
	{this.props.mention.get('value')}
	</span>
		);
	}
}

const mentionPlugin = createMentionPlugin({
...
			mentionComponent: Mention,
		});
this.MentionSuggestions = mentionPlugin.MentionSuggestions;
this.plugins = [mentionPlugin];
```

**Comment by valorize** [comment]
Hmm unfortunately this it seems it does not work reliabely when you do a selection and remove multiple mentions at once.

**Comment by valorize** [comment]
Another way but with I guess worse performance is:
```
const contentState = convertToRaw(this.state.editorState.getCurrentContent());
const models = Map(contentState.entityMap).toList().filter(v => v.type === entityType).map(v => v.data.mention);
```

**Comment by nikgraf** [comment]
@valorize I think this is such an edge case. At this point I recommend to fork the plugin and add this handler by yourself.

**Comment by yhoiseth** [comment]
Thanks a lot for sharing `draft-js-plugins`, especially the Mention plugin 🙂 

I thought I'd share my (simple and imperfect) solution to this issue in case it helps anyone:

Users are emailed if they are mentioned. In order to not email users who are mentioned and then removed, I filter on whether the content contains the given user's first or last name. Then, the remaining users are posted to the backend API.

```js
usersMentioned
  .filter(
    user =>
      content.includes(user.firstName) ||
      content.includes(user.lastName)
)
```

There are some edge cases where this can fail, such as when several users have the same first name, but it's sufficient for our needs at the moment.

**Comment by Vannevelj** [comment]
I don't fully understand why this is considered an edge case. If it's important enough to know when someone is mentioned, surely the opposite is true as well? Looking at @valoricDe their code sample I'm not seeing mention data on the block so I can't inspect that. I also can't make the trade-off made by @yhoiseth. 

What is the recommended approach for knowing which people are mentioned, taking into account deletions?

**Comment by danieloi** [comment]
you can get mentions by checking the entity map property on the editorState object instead of using the onAddMention method.

**Comment by OdysseyJ** [comment]
> you can get mentions by checking the entity map property on the editorState object instead of using the onAddMention method.

it works. thank you.

const contentState = convertToRaw(editorState.getCurrentContent());
const models = contentState.entityMap;
console.log(models);

this is result 
![image](https://user-images.githubusercontent.com/23691933/100953221-749ef980-3555-11eb-8f57-bf21f658643f.png)
