### ISSUE TITLE
Multiple instances of mentions plugin for 1 instance of editor

### ISSUE THREAD

**Issue by cutbko** [draft-js-plugins/draft-js-plugins#657]
Hi

Is it possible to have mentions plugin setup like mentions here, in github. I mean if I type '@' I get users to mention, if I type '#' I get issues to mention. 

If it is possible - do you have a sample of how to setup it?
If it is not possible - please explain why, maybe I could help implementing what is missing to have this possible.

**Comment by lorenjohnson** [comment]
I have the same question, I do think this open issue may be relevent: draft-js-plugins/draft-js-plugins: Issue #253

**Comment by lindskogen** [comment]
I have got this working on the `@2.0.0-rc2` version.

Very straight-forward:

```js
  const mentionPlugin = createMentionPlugin({
    mentionPrefix: "@"
  });

  const hashtagMentionPlugin = createMentionPlugin({
    mentionPrefix: "#",
    mentionTrigger: "#"
  });

this.plugins = [mentionPlugin, hashtagMentionPlugin]
```

```js
render() {
    const [mentionPlugin, hashtagMentionPlugin] = this.plugins;
    const { MentionSuggestions } = mentionPlugin;
    const { MentionSuggestions: HashtagSuggestions } = hashtagMentionPlugin;
    return (
      <div onClick={this.focus}>
        <Editor plugins={this.plugins} />
        <MentionSuggestions
          onSearchChange={this.onMentionSearchChange}
          suggestions={mentionSuggestions}
        />
        <HashtagSuggestions
          onSearchChange={this.onHashtagSearchChange}
          suggestions={hashtagSuggestions}
        />
      </div>
    )
}
```

**Comment by davidpelayo** [comment]
I, personally, haven't been able to make this work together with the `draft-js-hashtag-plugin`. But first let me explain why I'm saying this.

If I'm combining the suggestion above, @lindskogen's one, with the usage of the `draft-js-hashtag-plugin` to allow showing-while-writing that the user is writing a hashtag (this way they can select from the dropdown suggestion + create a new one), I'm getting an error when dismissing the suggestions dropdown (by pressing ESC, for instance), which is the following:

![Screen Shot 2019-04-03 at 10 41 22 AM](https://user-images.githubusercontent.com/84540/55465383-51dc7500-55fd-11e9-8f84-90142d95be8c.png)

![hashtags](https://user-images.githubusercontent.com/84540/55465712-feb6f200-55fd-11e9-81f7-34ebe129fbd7.gif)


Here's my snippet:

```js
const staticHashtagsPlugin = createHashtagPlugin();
const mentionPlugin = createMentionPlugin({
  mentionPrefix: '@',
  mentionPrefix: '@',
  entityMutability: 'IMMUTABLE'
});

const hashtagMentionPlugin = createMentionPlugin({
  mentionPrefix: '#',
  mentionTrigger: '#',
  entityMutability: 'IMMUTABLE'
});
this.plugins = [staticHashtagsPlugin, mentionPlugin, hashtagMentionPlugin]

/** ... **/

<div className={classnames(editorStyles.editor, className)} onClick={this.focus}>
  <Editor
          editorState={editorState}
          onChange={this.handleOnChange}
          plugins={plugins}
          ref={this.editor}
  />
  <MentionSuggestions
          onSearchChange={this.onSearchChange}
          suggestions={suggestions}
          onAddMention={this.onAddMention}
  />
  <HashtagSuggestions
          onSearchChange={this.onSearchChange}
          suggestions={hashtags}
          onAddMention={this.onAddHashtag}
  />
</div>
```

And even though simply without the hashtag plugins, on pressing ESC, I'm getting the error:

![inconsistent_anyways](https://user-images.githubusercontent.com/84540/55465902-63724c80-55fe-11e9-8c4a-b2ffa755a12d.gif)

**Comment by stevequinn** [comment]
Did you manage to sort this one out @davidpelayo ? I'm running across the exact same issue.

**Comment by davidpelayo** [comment]
I'm sorry to tell you I didn't manage to solve it, @stevequinn; I now live confined with the covid-19 issue and this one too

**Comment by jk-bd** [comment]
> I'm sorry to tell you I didn't manage to solve it, @stevequinn; I now live confined with the covid-19 issue and this one too

im in a similar situation.. was this ever doable?

**Comment by fxOne** [comment]
@jk-bd you can set multi mention triggers. You can find an example on then end of this page: https://www.draft-js-plugins.com/plugin/mention
