### ISSUE TITLE
Draft JS Plugin Editor and IE11: Expected Object error

### ISSUE THREAD

**Issue by tomkelsey** [draft-js-plugins/draft-js-plugins#660]
Hi,

Using the Draft JS Plugin Editor I was getting an "Expected Object" error in IE11.

I fixed this by replacing every instance of a `(for x of y)` loop with a `forEach` loop in `/Editor/index.js`

As per: https://github.com/tomkelsey/draft-js-plugins-editor/blob/master/src/Editor/index.js

Due to how the project is structured I haven't had time to shape this into a PR but hopefully it's useful for anyone else that comes across this issue.

**Comment by amannn** [comment]
I had the same problem. I'm using polyfill.io for polyfills but apparently the babel transpiled version of `for of` needs at least these two polyfills:

```
import 'core-js/es6/map';
import 'core-js/fn/symbol';
```

Using them instead of the ones from polyfill.io solved the problem for me.

**Comment by nikgraf** [comment]
That's a pity!

@amannn would you mind opening a PR? We could add core-js as dependency. Correct?

**Comment by amannn** [comment]
So you'd bundle those polyfills with the editor? Not sure if that's the best way. I could also add a note about this particular problem to the [FAQ](https://github.com/draft-js-plugins/draft-js-plugins/blob/master/FAQ.md#the-editor-throws-errors-in-internet-explorer-11). Maybe there are other polyfills for Map and Symbol that work and if people use those, we'd unnecessarily increase their bundle size with additional polyfills. It could also be that the polyfill.io polyfills will be updated in the near future and will work properly. So personally I'd leave the polyfills out and try to solve the problem with documentation.

What do you think?

**Comment by nikgraf** [comment]
Sound good to me, an update to the FAQ or even very early in the Readme sounds like a good approach …

**Comment by tomkelsey** [comment]
Hi guys,

Just jumping back in and noticed the linting config extends airbnb's - I'm not entirely sure as to their rationale but they seem to recommend not using for-of loops:

https://github.com/airbnb/javascript#iterators-and-generators

I don't know how extensively they're used in the codebase but it could be worth removing them rather than adding a caveat. Either way, great job with these plugins @nikgraf 👍

**Comment by nikgraf** [comment]
@tomkelsey we using them as a way to make the plugin system as performance as possible and bail out asap. Maybe that was over engineered …

**Comment by amannn** [comment]
Do you mean these ones here? https://github.com/draft-js-plugins/draft-js-plugins/blob/master/draft-js-plugins-editor/src/Editor/index.js#L43

The fork from @tomkelsey also has those: https://github.com/tomkelsey/draft-js-plugins-editor/blob/master/src/Editor/index.js#L43.

Or are you talking about something else?

**Comment by nikgraf** [comment]
exactly, but it's not the same - once breaks out of the for each the other still does the check for every other plugin

**Comment by amannn** [comment]
Hmm, not sure if I'm missing something. I guess they do the same, no? https://jsfiddle.net/uu24w0jb/

**Comment by nikgraf** [comment]
you are right, sorry - had another concept in mind

wanna open a PR? sounds good to me to refactor it to for each

**Comment by amannn** [comment]
Ah, alright :). Well @tomkelsey would you like to open the PR since your fork already contains the necessary changes? Otherwise I can take care of it.

**Comment by nikgraf** [comment]
@tomkelsey what do you think?
