### ISSUE TITLE
Mention removed

### ISSUE THREAD

**Issue by timrnz** [draft-js-plugins/draft-js-plugins#664]
I might be going blind but I can't seem to find the documentation that is the exact opposite to `onAddMention`. Is there a `onRemovedMention` equivalent?

I need to keep a track of mentions and send them with some payload information.

**Comment by ismyrnow** [comment]
The API doesn't have a function like that, since there are many ways to remove content that might include a mention (delete block, highlight + replace text, delete part of mention text if mutable, etc.).

Some folks over at #654 are discussing how to do it.

**Comment by nikgraf** [comment]
👍
