### ISSUE TITLE
If you're at the bottom of the page the mention should go up

### ISSUE THREAD

**Issue by johndavedecano** [draft-js-plugins/draft-js-plugins#665]
![offscreen](https://cloud.githubusercontent.com/assets/1860038/23119818/b073e5d6-f794-11e6-85e3-c810ce22209a.png)

The mention plugin is no longer visible when you are at the bottom

**Comment by sohini-roy** [comment]
Hello I would love to work on this issue.
Please guide me through :)

**Comment by nikgraf** [comment]
@johndavedecano that's a tricky problem. How would you solve that?
@sohini-roy I'm curious about a solution too. It could be placed above, but then we should come up with a clear ruleset.

**Comment by johndavedecano** [comment]
@nikgraf Do you guys already have a fix for this. Apparently its working on facebook

**Comment by johndavedecano** [comment]
```
    positionSuggestions: ({state, props}) => {
        
        let styles = {};

        const mentionSuggestions = document.getElementsByClassName(props.theme.mentionSuggestions)[0];

        const clientRect = mentionSuggestions.getBoundingClientRect();
        const bottomDistance = window.innerHeight - (clientRect.top + mentionSuggestions.offsetHeight);

        if (state.isActive & props.suggestions.size > 0) {
            
            styles.transform = 'scaleY(1)';
            styles.transition = 'all 0.25s cubic-bezier(.3,1.2,.2,1)';

            if (bottomDistance < 25) {
                styles.top = (mentionSuggestions.style.top - mentionSuggestions.offsetHeight - 18) + 'px';
            }

        } else if (state.isActive) {
            styles.transform = 'scaleY(0)';
            styles.transition = 'all 0.25s cubic-bezier(.3,1,.2,1)';
        }

        return styles;
    }
```

**Comment by johndavedecano** [comment]
@nikgraf here is my solution using react portal

```
    positionSuggestions: ({state, props}) => {

        document
            .getElementsByClassName(props.theme.mentionSuggestions)[0]
            .removeAttribute('style');

        const activeElement = document.getSelection().focusNode.parentNode;
        const {top, left} = activeElement.getBoundingClientRect();

        let styles = {
            top: top + 'px',
            left:  left + 'px'
        };

        const mentionSuggestions = document.getElementsByClassName(props.theme.mentionSuggestions)[0];
        const innerHeight = window.innerHeight || document.body.clientHeight;

        const bottomDistance = innerHeight - (top + mentionSuggestions.offsetHeight);

        if (state.isActive & props.suggestions.size > 0) {
            styles.transform = 'scaleY(1)';
            styles.transition = 'all 0.25s cubic-bezier(.3,1.2,.2,1)';
            if (bottomDistance < 31) {
                styles.top = (top - mentionSuggestions.offsetHeight - 31) + 'px';
            } else {
                styles.top = top + 'px';
            }
        } else if (state.isActive) {
            styles.transform = 'scaleY(0)';
            styles.transition = 'all 0.25s cubic-bezier(.3,1,.2,1)';
        }

        return styles;
    }
```

```
import Portal from 'react-portal';

            <Portal isOpened={true}>
                <this.MentionSuggestions
                    ref="suggestions"
                    onSearchChange={this.onSearchChange}
                    suggestions={this.state.suggestions}
                    onOpen={this.onMentionOpen}
                    onClose={this.onMentionClose}
                />
            </Portal>
```

**Comment by LawJolla** [comment]
@johndavedecano I like your fix.  While you're at it :), it experiences the same problem when the text box is too close to the right side of the screen.  

It looks like you can modify your code to solve that case too.

I like that you're using a portal!

**Comment by johndavedecano** [comment]
@LawJolla You might wanna check its distance from the right browser

**Comment by agarrharr** [comment]
@johndavedecano Thank you, your code works great!

Now, I wish there was an option to reverse the order of the suggestions. If you have the suggestions on top, it would be nice if you could make the suggestions start from the bottom of the list.

**Comment by agarrharr** [comment]
@johndavedecano That actually doesn't work for me. I thought it was because when it first opens, it will be above the cursor, then then after I move my mouse over the menu, or if I type another character, the menu moves back down below.

**Comment by johndavedecano** [comment]
@agarrharr I think we can use popper.js for this case then. I created a textarea with mention library https://github.com/johndavedecano/react-mention-plugin/blob/master/src/mentions/Suggestions.js

What i did is i track the coordinates of the caret then use it to position a span tag. I use that span tag as a reference for my popper element.

I think draftJS can also implement popperJS for managing mention position. @nikgraf any thoughts?

**Comment by digitalstaub** [comment]
#1125

**Comment by sibelius** [comment]
I think using popper.js would simplify a lot of code
