### ISSUE TITLE
Mention - Cannot read property 'getBoundingClientRect' of null

### ISSUE THREAD

**Issue by ismyrnow** [draft-js-plugins/draft-js-plugins#666]
When updating search suggestions, MentionSuggstionPortal loses its reference to `this.searchPortal`, which is a ref for the element.

<img width="740" alt="draft-js-mention-plugin-bug" src="https://cloud.githubusercontent.com/assets/1127410/23185694/4cf3631a-f852-11e6-90e1-52891d4e5f02.png">

The problem seems to have arose when switching from string refs (`ref='searchPortal'`) back in beta2. I have a fix for this and will open a PR shortly.

**Comment by ismyrnow** [comment]
Could I have gotten a worse issue number?

**Comment by ismyrnow** [comment]
The emoji plugin has code almost identical to this plugin which could be broken as well. I'm not using that plugin at the moment, so I don't know for sure if it's an issue there.

**Comment by nikgraf** [comment]
hehe, bad luck with the number 😄

**Comment by nikgraf** [comment]
Solved with #667
