### ISSUE TITLE
Everything is unstyled when I convertToRaw?

### ISSUE THREAD

**Issue by scf4** [draft-js-plugins/draft-js-plugins#670]
I'm using the hashtag plugin, things look fine in the editor but when I convert to raw all of the blocks are unstyled. e.g,

```
{"entityMap":{},"blocks":[{"key":"9bno","text":"blah blah #hashtag blah","type":"unstyled","depth":0,"inlineStyleRanges":[],"entityRanges":[],"data":{}}]}
```

**Comment by scf4** [comment]
Here is a sample of code:

```
import { createEditorStateWithText, EditorState, ContentState } from 'draft-js-plugins-editor';
import { convertToRaw } from 'draft-js';

class NewReply extends React.Component { 
  constructor() {
    super();
    this.state = { editorState:  createEditorStateWithText('') };
  }
  resetState = () => {
    const editorState = EditorState.push(
      this.state.editorState,
      createEditorStateWithText(''),
    );
    this.setState({ editorState });
  }
  handleChange = (editorState) => {
    this.setState({ editorState });
  }
  handleReturn = (e) => {
    e.preventDefault();
    this.handleSubmit();
    return true;
  }
  handleSubmit = () => {
    const content = this.state.editorState.getCurrentContent();
    const raw = JSON.stringify(convertToRaw(content));
    this.props.createPostMutation({ content: raw });
    this.resetState();
  }
  render () {
    return (
        <Editor 
          editorState={this.state.editorState}
          onChange={this.handleChange}
          placeholder="Write a reply..."
          handleReturn={this.handleReturn}
        />
    );
  };
}```

**Comment by nikgraf** [comment]
This is by design as the hashtag plugin doesn't attach any entities. It simply styles hashtags in the editor. If you want hashtags you could extract them on the backend using this strategy: https://github.com/draft-js-plugins/draft-js-plugins/blob/master/draft-js-hashtag-plugin/src/utils/index.js#L4

**Comment by scf4** [comment]
Thank you @nikgraf. What's the recommended way to store and retrieve content to the client for rendering? E.g. for a list of comments written with this component?

Should my API _not_ send a raw entityMap to the client for rendering? That's what I'm planning to do ATM.

**Comment by nikgraf** [comment]
@scf4 not that's actually the recommended way. If you apply the hashtag plugin it will do the highlights at the same place.
