### ISSUE TITLE
Docs: JavaScript errors and onFocus bug

### ISSUE THREAD

**Issue by wyqydsyq** [draft-js-plugins/draft-js-plugins#672]
Viewing the docs home page on Chrome Version 55.0.2883.75 (64-bit), I get the following errors in my console:
![image](https://cloud.githubusercontent.com/assets/621277/23598640/80a931d2-0287-11e7-931f-d73268bc4fb8.png)

Additionally, whenever I click on (focus) any of the editors in the page, my browser is for some reason scrolled to the top of the page.

**Comment by nikgraf** [comment]
This is an issue with the Github button. If you have a fix please let me know. Would be happy to accept a PR
