### ISSUE TITLE
[draft-js-mention-plugin] "Press and hold for accents" fails only during mentioning.

### ISSUE THREAD

**Issue by theuniverse** [draft-js-plugins/draft-js-plugins#673]
**OS:** macOS 10.12.2, 
**Browser:** Chrome, Safari

**How to reproduce:**
1. Open https://www.draft-js-plugins.com/plugin/mention and find any example.
1. Input `@J` and then press and hold u for `ü`.

**Expected result:** See `@Jü` in the editor.
**Actual result:** See `@Juü` in the editor, while the focus in after `u`; press delete will remove `ü` instead of `u`.

![2017-03-06 17_13_56](https://cloud.githubusercontent.com/assets/348304/23604267/41555f86-0293-11e7-9ffc-0e68f290e7ec.gif)

**Comment by theuniverse** [comment]
@nikgraf Please feel free to let me know if you have any idea. I will also try to find a solution and create a PR.

**Comment by nikgraf** [comment]
@theuniverse can you try again after the latest release today? that could be related to Draft.js itself and I upgraded to the latest version …

**Comment by theuniverse** [comment]
@nikgraf Tried but the problem still occurs. And it doesn't occur when I don't type in a mention typeahead. 😿

**Comment by nikgraf** [comment]
@theuniverse sorry, didn't do a release yet since I needed to fix the docs (took me half a day). Can you try later today?

**Comment by theuniverse** [comment]
@nikgraf Tried with 2.0.0-beta10, the problem is not fixed. But I think the problem is that in the default mention suggestion regex, `\w` doesn't accept accents. I think it's not a problem which must be fixed inside the plugin. After some other trial, I will close this ticket.

**Comment by nikgraf** [comment]
Thanks for looking into it! If you could investigate, that would be awesome. Maybe it is even a Draft.js or even React issue …
