### ISSUE TITLE
Mention - Backspace behaviors unexpected in Custom Mention Component Example

### ISSUE THREAD

**Issue by chenyuejie** [draft-js-plugins/draft-js-plugins#674]
https://www.draft-js-plugins.com/plugin/mention

Add two mentions in the Custom Mention Component Example editor, then press backspace key, will remove the first one.

**Comment by chenyuejie** [comment]
Works fine insert children in custom component instead of decoratedText.
```
mentionComponent: (props) => (
    <span
      className={props.className}
      // eslint-disable-next-line no-alert
      onClick={() => alert('Clicked on the Mention!')}
    >
      {props.children} // the example code is: {props.decoratedText}
    </span>
  ) 
```

**Comment by nikgraf** [comment]
@chenyuejie yes, you are right! Interested to submit a bugfix?

**Comment by chenyuejie** [comment]
@nikgraf PR created.

**Comment by nikgraf** [comment]
Thanks @chenyuejie! Very much appreciated ✨
