### ISSUE TITLE
alignment plugin example not working

### ISSUE THREAD

**Issue by andpor** [draft-js-plugins/draft-js-plugins#675]
Hi there,

I am running bare bones alignment example based on your instructions from https://www.draft-js-plugins.com/plugin/alignment.

I get the project to compile and run however I do not get the focus border around the rectangular area nor do I get any toolbar after I click the rectangular area ????? I am using the latest beta plugin versions.

Any idea where to start troubleshooting this?

I would be great to have a set of fully working sample projects...

**Comment by nikgraf** [comment]
What browser are you using? The docs are a set of fully working samples (in case there are no bugs) 🙂. Does it work for you on the website?

**Comment by andpor** [comment]
Chrome 55.0.2883.95 (64-bit) on Mac. Yes the example is working for me on the website. After I included the example code from the page it runs however the mouse over border is not showing and the toolbar does not appear when I click in the highlighted area. I have copied the code in entirety and npm installed pulled all beta version of the plugins...

**Comment by DavidBradbury** [comment]
I'm getting the same issue, app.js isn't loading - Chrome on Mac, Chrome on Windows, IE11 on Windows, and Chrome on Android - This seems to be happening for multiple demos.

**Comment by nikgraf** [comment]
Can you make a screenshot? I can't reproduce the issue …

**Comment by andpor** [comment]
That is because demo started working 2 days ago ...
