### ISSUE TITLE
selecting suggestion via return key not working

### ISSUE THREAD

**Issue by JayMc** [draft-js-plugins/draft-js-plugins#677]
this commit fdc158ef606b5257539d6d661cad4bee328aa977 seems to break selecting a suggestion from the list using the return key.
If I change the return from 'handled' to true inside `commitSelection()` in `MentionSessugestions/index.js` it works.

**Comment by nikgraf** [comment]
@JayMc what version of Draftjs are you using?

**Comment by JayMc** [comment]
was using `0.9.1` tried again on `0.10.0` and it's working.

**Comment by JayMc** [comment]
Ok maybe I should have updated draft-js-plugins-editor to be same version. The enter select seems to be working after also updating draft-js-plugins-editor to `2.0.0-beta9`

* draft-js-mention-plugin 2.0.0-beta9
* draft-js-plugins-editor 2.0.0-beta9
* draft-js 0.9.1

**Comment by Grammos** [comment]
Hi! I kind of have the same issue, but in my case, return key 'catches' just the '@' tag, and not that chosen item listed below.  

Plus, it keeps producing the: 

_"Warning: React does not recognize the isFocused prop on a DOM element. If you intentionally want it to appear in the DOM as a custom attribute, spell it as lowercase isfocused instead. If you accidentally passed it from a parent component, remove it from the DOM element. " - Please, find below the PrtSc attached, according to this problem._    Please, check detailed issue that I opened: https://github.com/draft-js-plugins/draft-js-plugins/issues/969

I'm using: 
- draft-js-plugins-editor: ^2.0.2
- draft-js-mention-plugin: ^2.0.1 
- draft-js: ^0.10.4

p.s. I'm trying to figure out what's going on?! Thanks in advance!

**Comment by weasteam** [comment]
Mine is similar:

```
Warning: Unknown prop `isFocused` on <div> tag. Remove this prop from the element. For details, see https://fb.me/react-unknown-prop
```

* draft-js-plugins-editor: ^2.0.3
* draft-js-mention-plugin: ^2.0.1
* draft-js: ^0.10.4
