### ISSUE TITLE
mention plugin person list trigger not working when using Korean

### ISSUE THREAD

**Issue by sanghyunJ** [draft-js-plugins/draft-js-plugins#685]
mention plugin person list trigger not working when using Korean
how to fix them?
<img width="593" alt="screen shot 2017-03-15 at 2 19 19 pm" src="https://cloud.githubusercontent.com/assets/15775881/23934699/72d65166-098a-11e7-83ba-4f06a9d144f9.png">
<img width="576" alt="screen shot 2017-03-15 at 2 19 31 pm" src="https://cloud.githubusercontent.com/assets/15775881/23934701/7413ab46-098a-11e7-8aba-d3fb38051017.png">
<img width="559" alt="screen shot 2017-03-15 at 2 19 10 pm" src="https://cloud.githubusercontent.com/assets/15775881/23934703/761f4166-098a-11e7-9a27-2dafa7d27869.png">

**Comment by nikgraf** [comment]
we need to extend the unicode range for the regular expression. do you know the unicode range for korean symbols?

**Comment by sanghyunJ** [comment]
I know that.. but current Korean unicode range is correct

I think that draft-js has some error.  not mention-plugin!

when typing Korean, beforehandleinput() can't catch key input event
