### ISSUE TITLE
Performance issue -- calling onChange in componentWillMount

### ISSUE THREAD

**Issue by gavinwahl** [draft-js-plugins/draft-js-plugins#686]
The PluginEditor manipulates the editor state and calls onChange in componentWillMount. This means the editor renders, its state changes, then it immediately rerenders. This causes a huge slowdown on a page with many editors (1000ms vs 1500ms).

Is it possible to make it work without causing an immediate, useless, rerender?

**Comment by nikgraf** [comment]
@gavinwahl what would you propose for the API in terms of the decorators?

**Comment by Benmiller313** [comment]
I'm also having issues with this. I want to be able to mount the editor during an Alt dispatch, and I also want my onChange function to fire an Alt action. Calling the onChange during the initial mount then fails when it tries to fire the alt action while its dispatching the original action.

**Comment by jjalonso** [comment]
Having problems too with this auto onchange. 

My specific case is that Im setting the field as dirty when onChange is triggered, to show validation, then at the start, no field show error but Draft because he triggered an onChange making itself dirty....

**Comment by elbakerino** [comment]
This now also resolves to an error in the console!

Since React 12.13. it popped up, also noted here: https://github.com/facebook/react/issues/18147

**Comment by sibelius** [comment]
I think we should let user apply decorators themselves or use something like

`getCompositeDecoratorFromPlugins(plugins)`

**Comment by ab-pm** [comment]
Related: #3375
