### ISSUE TITLE
Cannot use videoPlugin in my app 

### ISSUE THREAD

**Issue by jackmatrix** [draft-js-plugins/draft-js-plugins#688]
I am using the video plugin version 2.0.0 beta5

I am also using the imagePlugin.addImage in the same way. No problem i can insert my image. 

What wrong with the video plugin .

`this.onChange(videoPlugin.addVideo(editorState, {src: this.state.url}))`

doesn't working 

`Uncaught TypeError: videoPlugin.addVideo is not a function`

Thanks for helping

**Comment by nikgraf** [comment]
Please upgrade to beta10 and try again. Also would be great if you post the code how you instantiated the plugin.

**Comment by jackmatrix** [comment]
Thanks for replying. I already upgraded to beta10 of plugin editor but npm just propose me beta5 of video plugin editor. i spent almost 5 days to try get it works. I don't think i instantiated wrong since imagePlugin works fine and this is this the same process i guess.

Finally i could get it works . I had to "clone" the plugins. That means i had to completely rewrite it manually based on code available on github repo, then re-integrate in my app. I definely never could get the native addVideo() to work, So i rebuilt that stuff. Now I can embed video. That was a long and painful process.

**Comment by nikgraf** [comment]
@jackmatrix would you be willing to contribute a PR with a fixed version? In this case others don't run into the issue

**Comment by echenley** [comment]
@nikgraf looks like videoPlugin hasn't been published since beta5. Maybe it's missing in your deploy scripts?

```
$ npm view draft-js-video-plugin versions
-> [ '0.0.1', '0.0.2', '0.0.3', '0.0.4', '2.0.0-beta.5' ]
```

**Comment by nikgraf** [comment]
@echenley just deployed it a couple days back with rc1

**Comment by echenley** [comment]
Great thanks!
