### ISSUE TITLE
onAddMention not firing

### ISSUE THREAD

**Issue by jgrisafe** [draft-js-plugins/draft-js-plugins#689]
Cannot figure out how to get this callback firing:

```
<MentionSuggestions
          ref={component => (this.MentionSuggestions = component)}
          onSearchChange={this.onSearchChange}
          suggestions={this.state.suggestions}
          onOpen={() => this.setState({ popoverOpen: true })}
          onClose={() => this.setState({ popoverOpen: false })}
          onAddMention={this.onAddMention}
        />

onAddMention = (mention) => {
    console.log(mention) // eslint-disable-line no-console
  }
```

**Comment by nikgraf** [comment]
Might be a bug?

**Comment by hasnainshafqatmlt** [comment]
@nikgraf same issue i'm getting, it's not firing the function.
i'm not getting any error but the warnings i'm getting on mention select is this one.

![screen shot 2017-11-09 at 12 35 35 am](https://user-images.githubusercontent.com/6399158/32570489-10916b04-c4e6-11e7-9ac6-7f4cde75c535.png)

**Comment by jgrisafe** [comment]
The was fixed after upgrading to the newest version.
