### ISSUE TITLE
Options for mention identifier

### ISSUE THREAD

**Issue by Aleksion** [draft-js-plugins/draft-js-plugins#69]
I think the work you're doing is great! I really hope that the plugin system you're building can become the standard way of building plugins for draftjs.

The application I'm working on is persisting data entered through Draftjs as HTML The way the mention plugin is currently working, it's removing the '@' from the content, meaning that when the content is rendered as html, there's no way of recognizing the string as a mention afterwards.

A quick fix for me would be to persist the '@' character either visible or invisibly so that I have a way of knowing that the given string is a mention

**Comment by nikgraf** [comment]
Hey @Aleksion, thanks for the kind words :smile: 

I was thinking to split between `handle` & `name` so it's also possible to have @mentions like in Slack. I guess that would help.

I haven't gave exporting much of a thought yet, but when looking at it from a bigger picture and having rendering for all sorts of things like Stickers, custom Emojis or @mentions you basically would need to understand the block type & entities. That's also how internally a mention is detected.

What about you build your exporter in a way that it has a plugin system as well and it accepts `blockrenderFn` as well as `decorators`. If we agree on a structure of the plugin that works for both of us we could use the exact same plugin for the editing as well as your export. Could this be a path you want to investigate more?

**Comment by Aleksion** [comment]
@nikgraf - I think that would be great. Github does it like slack as well: it simply prepends the name to the "@" character behind it. The reason I need it, is because I'm using draftjs and react in an existing angular app (DraftJs solved so many problems that it was worth pulling in react - I cannot even begin to describe the hatred I feel toward other RTE's).

Highlighting users without having a handle to scan for is a problem then.

I went down the path you suggested: I forked https://github.com/sstur/draft-js-export-html.
As with most early draftjs libraries it lacks quite a bit in extensibility - but the way I handled it was by enabling the MarkupGenerator to take an object containing EntityConverters (Personally I would like to change it to an array, but I wan't to do a complete cleanup on sstur's code before I make a pull request)

In order to output the name preprended with the '@' character, you simply have to do the following:

```javascript

let mentionConverter = (entity, content) => {
 return `@${content}`;
}
let markupGenerator({mention: mentionConverter});

```

The mentionPlugin could provide a default mentionConverter, that takes into account the handle, whether or not to prefix and potentially create a custom html tag for mentions (which would make it easier to convert back the other way - but I haven't had time to dive into sstur's html importer yet).

with an array instead of an object it would be done as such:

```javascript
let mentionConverter = {
  key: 'mention',
  converter: (entity, content) => {
    return `@${content}`;
  }
}
let markupGenerator([mentionConverter]);
```

Are you planning on moving your plugins into seperate repositories? (I think it would make sense to do so).

If you do I propose you move the project to an organization and publish both the core (the editor) and all the plugins under that organization name. It will also make it easier for you to get new contributors (I'm going to stick with you anways)

A repository I go started has really picked up after we moved it from my account - and is now living it's own life without me :D (because I've been too busy in JS world): https://github.com/ReSwift/ReSwift

**Comment by nikgraf** [comment]
sorry, have been a bit busy, but I try to get back to you tomorrow

**Comment by nikgraf** [comment]
hey @Aleksion, sorry for the delay. We now implemented a `mentionPrefix` option for the config. After we merged this you can check it out in the documentation. It also will be available at the 1.0.0 of the mentions plugin.

https://github.com/draft-js-plugins/draft-js-plugins/pull/220

**Comment by agungsb** [comment]
Hi @Aleksion ,

I'm curious in how you manage to solve your problem using with  [ https://github.com/sstur/draft-js-export-html.](https://github.com/sstur/draft-js-export-html) in more detail way. I need to export the content to html using that plugin, but the 'mention' is not exported as ```<a>``` element.

Thanks.

**Comment by MykolaGolubyev** [comment]
You can define entityStyleFn and play around data that can be extracted from passed entity.
https://github.com/sstur/draft-js-utils/tree/master/packages/draft-js-export-html#entitystylefn
