### ISSUE TITLE
Add some European characters to the Mention regex please

### ISSUE THREAD

**Issue by fredriksundstrom** [draft-js-plugins/draft-js-plugins#692]
Hey! The Mention plugin is really useful in English, but with i.e. Swedish characters it doesn’t work so good.

I found the regex and was trying to add it as a pull request but couldn’t get the dev setup going.

I hacked in åäöÅÄÖáÁéÉíÍóÓëËúÚàÀèÈìÌùÙ into the Regex I currently have in the plugin and it works much better, so maybe you could add these characters – or at least åäöÅÄÖ to the regex. :)

I’ve summed up some european characters and some other foreign stuff as \u00C0-\u00D6\u00D8-\u00F6\u00F8-\u00FF, which suits your current Regex a little bit better, if you’d like to use that combination.

The regex I’ve got going right now that is also working is: [\\w\u00C0-\u00D6\u00D8-\u00F6\u00F8-\u00FF\u4E00-\u9EFF\u3040-\u309F\u30A0-\u30FF\uAC00-\uD7A3\u3130-\u318F]*

**Comment by thomas88** [comment]
Fixed by https://github.com/draft-js-plugins/draft-js-plugins/pull/870

**Comment by freedomlang** [comment]
@fredriksundstrom Looks like the problem you mentioned above has been solved; if you still facing the same problem at the latest version, please leave a comment or open a new issue , we will pick it from there.
