### ISSUE TITLE
Mentions example not working within draft-js-plugins live demo

### ISSUE THREAD

**Issue by arsanjea** [draft-js-plugins/draft-js-plugins#695]
I tried the live demo on the official website. I am expecting that typing Michael Russell would give me a list of names.
Am I missing something?
![draft-plugin-problem](https://cloud.githubusercontent.com/assets/9323128/24262169/a44be9a4-0fcf-11e7-8ee4-e79455c1d36f.gif)

**Comment by mattiasewers** [comment]
You need to type "@" before entering the name

**Comment by arsanjea** [comment]
Got it. Thanks.

**Comment by haydenbleasel** [comment]
I've got a strange issue with the demo version where hitting `Return` continuously triggers the first suggested user to be added automatically.

![5p9o2roku1](https://cloud.githubusercontent.com/assets/4142719/24341061/b6a788f2-1302-11e7-863b-0ac497c0b157.gif)

**Comment by theuniverse** [comment]
@haydenbleasel This is what #687 is discussing about.

**Comment by haydenbleasel** [comment]
@theuniverse Ahh okay, sorry about that mate. I'll head there.
