### ISSUE TITLE
[draft-js-emoji-plugin] Copy / paste emoji from other sources

### ISSUE THREAD

**Issue by bashkos** [draft-js-plugins/draft-js-plugins#698]
When copying emoji from the page like
`<img class="emojione" alt="😝" title=":stuck_out_tongue_closed_eyes:" src=" ... ">`, from twitter or from vkontakte and pasting into the editor, instead of emoji an image link is inserted. In this case, twitter and vkontakte are inserted emoji.

**Comment by bashkos** [comment]
![Gif](https://s8.hostingkartinok.com/uploads/images/2017/04/31b325e65ba1fc0c6330886279975e2e.gif)

**Comment by allankikkas** [comment]
Are you actually copying an image from the comments section below or is this an actual unicode emoji character with image background?

**Comment by bashkos** [comment]
Yes, I copy the image obtained by the method [`emojione.unicodeToImage()`](https://demos.emojione.com/latest/jsunicodetoimage.html). This image have actual unicode emoji character in `alt` property. When I copy this image and paste in `textarea` element or my IDE, I get plain unicode character. When I copy this image and paste to Twitter message field, I get emoji in twitter-style.

**Comment by nikgraf** [comment]
hmmm, I would say this is more of an issue from Twitter and vKontakte. Doing emoji's like that seems like a bad strategy :(

In any case if anyone is interested to create a PR to even cover that case. Happy to accept it.
