### ISSUE TITLE
image-plugin not loading decorators on init

### ISSUE THREAD

**Issue by arcifius** [draft-js-plugins/draft-js-plugins#700]
Well i'm new with DraftJS so this can even not be a problem at all...

First of all i'm creating the imagePlugin
`const imagePlugin = createImagePlugin({
    theme: imageTheme,
    decorators: [
        resizeablePlugin.decorator,
        alignmentPlugin.decorator,
        focusPlugin.decorator,
        blockDndPlugin.decorator
    ]
});`

my initial state is the same defined in https://www.draft-js-plugins.com/plugin/image

in my render i got the following
`render() {
    return (
        <div>
            <div className="text-editor-root" onClick={this.focus}>
                <Editor
                    editorState={this.state.editorState}
                    onChange={this.onChange}
                    plugins={plugins}
                    ref={(element) => { this.editor = element; }}
                />
                <AlignmentTool/>
            </div>
        </div>
    );
  }
}`

When mount the editor i got an image but it can't be resized nor moved, if I insist in move it I end up with two images the new one can be resized and moved... Each new move clones the image, i'm totally lost here...

**Comment by arcifius** [comment]
To reproduce it: go to https://www.draft-js-plugins.com/plugin/image

Scroll to **Add Image Button Example** example and then add some image mine was "https://www.w3schools.com/css/img_fjords.jpg", you'll see that it isnt resizable/alignment missed but then if you drag'n'drop it on the beginning of the text it will be cloned and the new one is at least resizable but align tools still disabled... Hope it has a fix...

**Comment by StevenIseki** [comment]
That is because the add image example does not include the alignment plugin. 
`const plugins = [imagePlugin];` 

You would just need to add the alignment-plugin in your example for this to work correctly:

```
const focusPlugin = createFocusPlugin();
const resizeablePlugin = createResizeablePlugin();
const blockDndPlugin = createBlockDndPlugin();
const alignmentPlugin = createAlignmentPlugin();
const { AlignmentTool } = alignmentPlugin;

const decorator = composeDecorators(
  resizeablePlugin.decorator,
  alignmentPlugin.decorator,
  focusPlugin.decorator,
  blockDndPlugin.decorator
);
const imagePlugin = createImagePlugin({ decorator });

const plugins = [
  dragNDropFileUploadPlugin,
  blockDndPlugin,
  focusPlugin,
  alignmentPlugin,
  resizeablePlugin,
  imagePlugin
];
```
