### ISSUE TITLE
Cursor issue when i removing the space div under image block

### ISSUE THREAD

**Issue by jackmatrix** [draft-js-plugins/draft-js-plugins#701]
There is a cursor issue when we trying to remove the image block.

Go to the plugin [page](https://www.draft-js-plugins.com/plugin/image) and try by yourself.

The cursor behavior become weird and float right. Then you have no choice than remove the image if you want to keep using the editor normally. We can focus the editor below the image block. This is like if the part of the editor located below the image has been disabled. very weird. 

Any suggestions to solve this probleme

**Comment by simsim0709** [comment]
Hello, @jackmatrix 

Is this problem still existing? I can reproduce the issue.

I will just close for now. If it still exists, you can reopen it!

Thank you.
