### ISSUE TITLE
Draft-Js dependency incorrect?

### ISSUE THREAD

**Issue by marekolszewski** [draft-js-plugins/draft-js-plugins#702]
Since 3ba2d3, I believe the draft-js dependency in each plugins' package.json file should have been bumped to v0.10.0. I just ran into a bunch of issues because the resizable plugin was pulling in an older version of draft js but calling the new getEntity function.

Related to this, it may make sense to move the draft-js dependency into peerDependencies in each of the plugins.

**Comment by melbourne2991** [comment]
+1 for making it a peer dependency if possible.

**Comment by nikgraf** [comment]
Sounds good to me. Interested to create a PR?
