### ISSUE TITLE
draft-js-video-plugin and draft-js-drag-n-drop-upload-plugin npm problem

### ISSUE THREAD

**Issue by sanghyunJ** [draft-js-plugins/draft-js-plugins#705]
plz upgrade draft-js-video-plugin to 2.0.0-beta10 version...
current npm proposal only 0.0.1, 0.0.2, 0.0.3, 0.0.4, 2.0.0-beta.5 version
and draft-js-drag-n-drop-upload-plugin is not found on npm...

**Comment by andromedarabbit** [comment]
Any progress?

**Comment by SevenZark** [comment]
I'm having a similar issue, leaving my project dead in the water for now. No progress on it since April has me worried. I hope somebody cares, at some point! :)

To provide a bit of context, I'm trying to do one of the examples shown in the official documentation for the image plugin. But when I try to install the drag-and-drop upload package I get this:

```
npm ERR! code ENOVERSIONS
npm ERR! No valid versions available for draft-js-drag-n-drop-upload-plugin

```

**Comment by jtbonhomme** [comment]
The same for me ...

**Comment by tarjei** [comment]
@SevenZark  did you try yarn add  draft-js-drag-n-drop-upload-plugin@2.0.0-rc8 ?

**Comment by SevenZark** [comment]
I don't use yarn. I didn't think it was a requirement for this package?

**Comment by jtbonhomme** [comment]
Doesn't work neither:

% yarn add draft-js-drag-n-drop-upload-plugin@2.0.0-rc8
...
error Received malformed response from registry for
"draft-js-drag-n-drop-upload-plugin". The registry may be down.

2017-09-26 9:30 GMT+02:00 Tarjei Huse <notifications@github.com>:

**Comment by kingmatusevich** [comment]
Please fix this

**Comment by Hongbo-Miao** [comment]
Tried to follow the guide in image [Alignment + Resize + Focus + Drag'n'Drop + Drag'n'Drop Upload Example](https://www.draft-js-plugins.com/plugin/image), also failed to install **draft-js-drag-n-drop-upload-plugin**.

**Comment by Hongbo-Miao** [comment]
Also failed to install **draft-js-drag-n-drop-upload-plugin** when I tried to follow the guide in image [Alignment + Resize + Focus + Drag'n'Drop + Drag'n'Drop Upload Example](https://www.draft-js-plugins.com/plugin/image).

**Comment by Hongbo-Miao** [comment]
Also failed to install **draft-js-drag-n-drop-upload-plugin** when I tried to follow the guide in image [Alignment + Resize + Focus + Drag'n'Drop + Drag'n'Drop Upload Example](https://www.draft-js-plugins.com/plugin/image).

Can someone help publish **draft-js-drag-n-drop-upload-plugin** to the npm again? Thanks

**Comment by galileomd** [comment]
+1 for publishing draft-js-drag-n-drop-upload-plugin

**Comment by kalekseev** [comment]
Guys I think it was removed from npm because it was never implemented as stated in the docs.
If you look at the code https://github.com/draft-js-plugins/draft-js-plugins/blob/master/draft-js-drag-n-drop-upload-plugin/src/handleDroppedFiles.js#L46 then you will find that handleUpload callback is commented out and the only thing that it does is show image thumbnail after upload. If that functionality is what you want then you can just copy that plugin source code into your project.

**Comment by abhishek541** [comment]
npm still says no valid versions available. Any updates ?

**Comment by bufordtaylor** [comment]
This appears to be a dead plugin

**Comment by gorjan-mishevski** [comment]
2018 still nothing. This is just Unbelievable.

**Comment by rauleite** [comment]
I have been installing via _@mikeljames_

`yarn add @mikeljames/draft-js-drag-n-drop-upload-plugin`

and...

`import createDragNDropUploadPlugin from '@mikeljames/draft-js-drag-n-drop-upload-plugin'`

**Comment by rauleite** [comment]
I have been installing with [@mikeljames](https://www.npmjs.com/package/@mikeljames/draft-js-drag-n-drop-upload-plugin) prefix.

`yarn add @mikeljames/draft-js-drag-n-drop-upload-plugin`

and...

`import createDragNDropUploadPlugin from '@mikeljames/draft-js-drag-n-drop-upload-plugin'`

**Comment by rauleite** [comment]
Can anyone make resize + video work?

It doesn't ever work on ["Advanced Video Example"](https://www.draft-js-plugins.com/plugin/video)

**Comment by bodguy** [comment]
this is still not work 2019!

**Comment by 0fisher** [comment]
use this for my publish on npmjs instead
draft-js-dragndrop-upload-plugin
