### ISSUE TITLE
Emoji plugin makes editor very slow on Safari

### ISSUE THREAD

**Issue by martynasjocius** [draft-js-plugins/draft-js-plugins#709]
How to reproduce:

1. Open Safari (10.1) or Safari Technology Preview (Release 27).
2. Go to https://www.draft-js-plugins.com/plugin/emoji.
3. Enter more content into the editor (5-20 paragraphs).
4. Try typing some new text.
5. Editor is responding very very slowly and cannot be used.

This issue appears only on Safari browser and only when using Emoji plugin (other plugins work fine).

Have you also noticed that bug? Is there a quick way to avoid it? Thanks for the feedback!

**Comment by eugenijusr** [comment]
I found the culprit. It's because `attachImmutableEntitiesToEmojis` is iterating through all the blocks on each key stroke. When there's a lot of text it gets super slow.

Why is this needed, can't we just take the last block?

Instead of:
```
block.forEach((block) => {
```

Do this:

```
let block = null
if (blocks.length > 0) {
  block = blocks[blocks.length - 1]
}

if (block != null) {
```

This fixes the sluggish performance on Safari for us without any apparent effect on the functionality. Or am I missing something?

**Comment by nikgraf** [comment]
@eugenijusr this would cause issues if someone pastes a whole block of emojis

**Comment by eugenijusr** [comment]
@nikgraf Would it be possible to select only the new blocks instead of going through all of them?

Anyways since performance was an big issue for us we hard-forked this with the following fix for now:

```javascript
const currentSelection = editorState.getSelection()
const startKey = currentSelection.getAnchorKey()
const block = contentState.getBlockForKey(startKey)
if (block != null) {
```

**Comment by nikgraf** [comment]
@eugenijusr maybe based on the und/redo list we could figure out which blocks changed and make it more efficient.

@eugenijusr so what happens in your solution if I copy paste a full text with emojis?

**Comment by bengotow** [comment]
Hey folks—just stumbled across this one as well. Would it be possible to catch paste using the `handlePastedText` handler and only do the expensive computation in the following update?

**Comment by simpleshadow** [comment]
Just recently had this issue on Safari. Using @eugenijusr's solution. Still works with paste. Might be missing something somewhere, but resolved a user reported issue.
