### ISSUE TITLE
Exception when using focus plugin

### ISSUE THREAD

**Issue by artur-charcenko** [draft-js-plugins/draft-js-plugins#710]
Steps to reproduce:
- Go to https://www.draft-js-plugins.com/plugin/focus
- Focus block by clicking on it or using arrow keys
- Press `Enter`

You should see this error in the console:
```
Uncaught Error: Unknown DraftEntity key.
```

**Comment by league55** [comment]
Just trying to guess, but 
{code}

  _handleKeyCommand(command) {
    const newState = RichUtils.handleKeyCommand(this.state.editorState, command);
    if (newState) {
      this.onChange(newState);
      return 'handled';
    }
    return 'not-handled';
  }
{code}
may solve it

**Comment by nikgraf** [comment]
Still having this issue with rc1?

**Comment by artur-charcenko** [comment]
@nikgraf Just tried rc2 and it seems that issue is resolved. Thanks!

**Comment by nikgraf** [comment]
thanks for checking @artur-charcenko

**Comment by mhinostroza** [comment]
This fix continues
Steps to reproduce:

Focus image by clicking
Press Enter
