### ISSUE TITLE
Mention bug when pressing return

### ISSUE THREAD

**Issue by tomkelsey** [draft-js-plugins/draft-js-plugins#712]
On the simple example: https://www.draft-js-plugins.com/plugin/mention

If you type `@NikGrif` (select the mention) then type some random text and hit return rather than going to a new line it'll enter "Nik Grif" into the text editor again.

This seemed to be introduced when I upgraded to the latest versions of all the plugins so guessing a recent PR. I haven't had a chance to look into it yet.

**Comment by tomkelsey** [comment]
I believe it was PR #659 that introduced this bug. Commenting out that code appears to fix the issue.

**Comment by johnmpotter** [comment]
I just came across this issue as well. It started occurring after I upgraded from beta9 to beta10. I just went back to beta9 and the issue disappeared.

**Comment by mbseid** [comment]
There is a PR open to fix this issue: https://github.com/draft-js-plugins/draft-js-plugins/pull/706

It has been working for us quite well.

**Comment by Ace139** [comment]
Merge the PR soon. It's really annoying.

**Comment by GRiccarducci** [comment]
Please merge the PR

**Comment by inchr** [comment]
Please merge :( same bug here :( #723

**Comment by nikgraf** [comment]
Merged and released with 2.0.0-beta11!
