### ISSUE TITLE
Can I change the trigger of mention pluggin?

### ISSUE THREAD

**Issue by guidiego** [draft-js-plugins/draft-js-plugins#713]
Hey guys, I want to change my mention plugin to trigger mentions by `#` and not from `@`, Can I do this without fork and change the code ?

**Comment by johnmpotter** [comment]
Yeah, it's super easy! Just set the param 'mentionTrigger' to '#'.

You can find all the configurations here 👉 https://www.draft-js-plugins.com/plugin/mention

**Comment by guidiego** [comment]
@johannesnagl I try this but not work :/ I was using 1.1.2, has some point about this?

**Comment by johnmpotter** [comment]
I might be wrong, but it looks like it was added in version 2.0 #320 

I'm not sure what it take to upgrade from 1.0 to 2.0+, but if you are able to, i'd try that. I'm working on "2.0.0-beta9" and it is working 👍

**Comment by guidiego** [comment]
Thanks!

**Comment by nikgraf** [comment]
Thanks @johnmpotter for helping out here!
