### ISSUE TITLE
Emoji plugin raise exeption when number emoji

### ISSUE THREAD

**Issue by sugarshin** [draft-js-plugins/draft-js-plugins#717]
Hi,

Could you check this. The following emoticons will raise exception.

```
^:(one|two|three|four|five|six|seven|eight|nine|zero):$
```

![image](https://cloud.githubusercontent.com/assets/2001452/25079303/3782c4cc-2376-11e7-841f-d143b0f75f30.png)

I think this is a maybe draft-js issue.

**Comment by nikgraf** [comment]
@bashkos maybe something for you to tackle as you already familiar with the emoji code :)

**Comment by bashkos** [comment]
Ok, I'ill see it on this holidays.

**Comment by nikgraf** [comment]
thanks!

**Comment by bashkos** [comment]
Maybe it's time to update on EmojiOne 3.x, but it can be so long.

**Comment by nikgraf** [comment]
Just read that EmojiOne 3.x had different license terms :( Makes me want to look for alternatives. Maybe the Twitter set?

**Comment by bashkos** [comment]
With new license terms all of need is attribution, as well as for twemoji. But only emojione provide assort by categories

**Comment by gsgilman** [comment]
Any update on the status for this?

**Comment by nikgraf** [comment]
@gsgilman didn't get to work on it. are you interested to contribute a PR?

**Comment by rrjanbiah** [comment]
Bump!

**Comment by rrjanbiah** [comment]
Bump! (Moving away from Draft personally; but it is a good issue)

**Comment by fxOne** [comment]
I just tried it out with the latest version of `@draft-js-plugins/emoji@4.0.0-beta5` and it worked without any errors.
