### ISSUE TITLE
UndoButton/RedoButton cannot be initialized before Editor

### ISSUE THREAD

**Issue by terryoy** [draft-js-plugins/draft-js-plugins#718]
Hi,

I'm writing a toolbar with DraftJS, and it will be rendered before the Editor.

```jsx
<div>
<Toolbar><RedoButton/><UndoButton/></Toolbar>
<Editor .../>
</div>
```

I think it's because the RedoButton/UndoButton didn't consider the situation that the Editor has not been initialized before the buttons are rendered.

```
Uncaught TypeError: this.props.store.getEditorState is not a function
    at UndoButton.render (index.js:59)
    at ReactCompositeComponent.js:796
    at measureLifeCyclePerf (ReactCompositeComponent.js:75)
    at ReactCompositeComponentWrapper._renderValidatedComponentWithoutOwnerOrContext 
```

Exception line: 
https://github.com/draft-js-plugins/draft-js-plugins/blob/master/draft-js-undo-plugin/src/RedoButton/index.js#L21

When the method "getEditorState" is actually initialized:
https://github.com/draft-js-plugins/draft-js-plugins/blob/master/draft-js-undo-plugin/src/index.js#L30

**Comment by AverageZ** [comment]
+1

**Comment by nikgraf** [comment]
> I think it's because the RedoButton/UndoButton didn't consider the situation that the Editor has not been initialized before the buttons are rendered.

You are right, interested to create a PR?

**Comment by terryoy** [comment]
@nikgraf I have moved on to other projects and didn't maintain the work space, so I just added a simple fix without testing it. You can accept it if it's appropriate.

https://github.com/draft-js-plugins/draft-js-plugins/pull/740

**Comment by nikgraf** [comment]
Ouch, just read you added the fix without testing it. Let's hope it works

**Comment by hoppula** [comment]
It doesn't work yet as store always exists: https://github.com/draft-js-plugins/draft-js-plugins/blob/master/draft-js-undo-plugin/src/index.js#L14

I think https://github.com/draft-js-plugins/draft-js-plugins/blob/master/draft-js-undo-plugin/src/RedoButton/index.js#L22 would need another check that ensures `this.props.store.getEditorState` actually exists.

**Comment by terryoy** [comment]
Agree with @hoppula

**Comment by Hongbo-Miao** [comment]
It also happens to LinkButton.

**Comment by Hongbo-Miao** [comment]
This also happens to LinkButton.

**Comment by minhdang241** [comment]
> I think this also happens to LinkButton. Got same error if editor is not ready.

Hi, do you have any solution for it
