### ISSUE TITLE
CreateFromText doesn't take plugins as a parameter

### ISSUE THREAD

**Issue by Aleksion** [draft-js-plugins/draft-js-plugins#72]
One problem i'm running into with the mentionsPlugin is that if I initialize the editor with content - that contains a @ character - it will not trigger the mentions plugin at all. Until I've deleted the character, committed the state and reinitializes it without it.

I figured that was the reason for the built in createFromText function - but it doesn't seem to do anything else than wrap the native functions of DraftJs (and doesn't even take the plugins array as specified in the documentation)

I know the documentation is far from done - I just wanted to know a bit about the thinking behind it :)

**Comment by nikgraf** [comment]
sorry, have been a bit busy, but I try to get back to you tomorrow

**Comment by nikgraf** [comment]
@Aleksion Mentions leverage entity data. It will only be detected as mention once there is an entity for the range of characters covering the mention. This is why it's important to convert the content state to a re-usable datastructure `convertToRaw` as well as initializing the content state with `convertFromRaw`.

More details here: https://facebook.github.io/draft-js/docs/api-reference-data-conversion.html#content
