### ISSUE TITLE
Bug in mention plugin(send key automatically select a mention)

### ISSUE THREAD

**Issue by inchr** [draft-js-plugins/draft-js-plugins#723]
Hi, i'm trying the draft-js-plugins and I've noticed a weird bug when i press the "send key" in the textarea, it automatically mentions someone.

The bug is also in the plugin page: https://www.draft-js-plugins.com/plugin/mention

Is this a bug or I'm missing something ?

**Comment by fdemian** [comment]
Hi, I'm also experiencing a similar case. 
I believe this is similar to #724 (if not the same issue). I've noticed it is in the page too. 

**How to reproduce:** 

Go the mention plugin in the page [https://www.draft-js-plugins.com/plugin/mention](https://www.draft-js-plugins.com/plugin/mention) 
Press "@" and select a user.
Press enter twice.

**Comment by inchr** [comment]
Not sure if is the same issue, but yeah, both bugs sucks.

**Comment by inchr** [comment]
@fdemian My issue(but not yours) is fixed by this PR #706

**Comment by fdemian** [comment]
Ok, I actually experienced both, so this is good news.
