### ISSUE TITLE
[mention] Put empty space after @, it still suggests users

### ISSUE THREAD

**Issue by keioka** [draft-js-plugins/draft-js-plugins#724]
The mention plugin tries to suggest users even when I put empty space after @. It happens on example (https://www.draft-js-plugins.com/plugin/mention) and my code.

**Version** 
```
"draft-js": "^0.10.0",
"draft-js-mention-plugin": "2.0.0-beta10",
"draft-js-plugins-editor": "2.0.0-beta10",
```

https://www.useloom.com/share/10bf567886124f2ea4e93ee04ef7c27f

**Comment by nikgraf** [comment]
@keioka do you still have this issue with rc1 or rc2?

**Comment by dovydaskukalis** [comment]
Same issue on rc5.
