### ISSUE TITLE
IE11 mention focus results in infinite loop.

### ISSUE THREAD

**Issue by 1Jesper1** [draft-js-plugins/draft-js-plugins#735]
Focusing on a mention results in an infinite loop.
Change `display : "inline-block"` to `display: "inline"` for class `.draftJsMentionPlugin__mention__29BEd, .draftJsMentionPlugin__mention__29BEd:visited` for IE11, to prevent this issue.

**Comment by nikgraf** [comment]
@1Jesper1 I don't have a machine with IE11 setup right now. Could you create a PR with a fix?

**Comment by 1Jesper1** [comment]
I suggest to get the userAgent string at document.ready with window.navigator.userAgent and then add a specific class for ie11 to the body. 
Then add the CSS: 
`.(specificClass).draftJsMentionPlugin__mention__29BEd,
.(specificClass).draftJsMentionPlugin__mention__29BEd:visited 
{
  display: inline !important
}`
