### ISSUE TITLE
Method signature has changed in beta 11?

### ISSUE THREAD

**Issue by brijeshb42** [draft-js-plugins/draft-js-plugins#736]
Normally, any function would receive arguments like this,

```js
handleKeyCommand(command, { getEditorState, setEditorState})
```

But in `beta-11` version, the signature is this,

```js
handleKeyCommand(command, editorState, { getEditorState, setEditorState})
```
This is breaking the code.

**Comment by nikgraf** [comment]
ouch, this happened by accident. I will fix and cut a new release soon!

**Comment by nikgraf** [comment]
Unfortunately this actually isn't a bug. With Draft.js 0.10.1 the signature was changed and therefor all the functions in the plugins changed as well.

Here are the changes in the core:
https://github.com/facebook/draft-js/pull/1112/files
https://github.com/facebook/draft-js/pull/1113/files

I'm about to cut a new release where these changes are documented in the changelog and made 0.10.1 mandatory: https://github.com/draft-js-plugins/draft-js-plugins/pull/743
