### ISSUE TITLE
Please consider a changelog

### ISSUE THREAD

**Issue by tarjei** [draft-js-plugins/draft-js-plugins#738]
Hi, you guys are doing a great job and I know you are still in beta mode, but it would be great if you could try to keep a changelog file for your betareleases. It doesn't matter if it is not complete, any info is better than trying to discern what has changed from the commit list.

kind regards,
Tarjei

**Comment by StorytellerCZ** [comment]
With that, tagging releases here would also help.

**Comment by juhaelee** [comment]
Each package has it's own changelog if you go into its directory

**Comment by juliankrispel** [comment]
@StorytellerCZ since we have all the plugins in one repo tagging releases doesn't make much sense. But I think it's up for discussion whether that still makes sense.

**Comment by StorytellerCZ** [comment]
@juliankrispel There are some ways that we could play with it that it would work, but I think that would be more pain than gain. The only way tagging would help would be if all the releases happen at the same time like they have been happening with 2.0 beta.

**Comment by juliankrispel** [comment]
@StorytellerCZ what about splitting up the repo, see -> #812
