### ISSUE TITLE
Ability to define our own emoji list for the emoji autocomplete dropdown?

### ISSUE THREAD

**Issue by Rosey** [draft-js-plugins/draft-js-plugins#744]
Right now the emoji autocomplete uses emojiOne as the source of truth for what emojis are available, but I'm in a situation where I need the emojis listed in the dropdown to match those available in the https://github.com/iamcal/emoji-data repo. Right now there's a handful of emojis that are supported by emojiOne but aren't yet supported in emoji-data.

Would it be OK if I opened a PR that allows you to optionally include your own emojiList and fall back on the emojiOne list if none is provided? I'm not sure if this would be overkill for the plugin but I definitely need this, so I'll likely end up doing it in my own fork regardless :)

**Comment by nikgraf** [comment]
@Rosey do you have a rough idea what you want to change and how it should look like? This would help me to get a better idea if this should go in the main repo.

**Comment by Rosey** [comment]
🤔  Was thinking, possibly similar to how the mentions plugin works, accepting a `suggestions` prop that is an object containing a list of emoji, (object would be formatted in the same way that `emojilList.js` currently formats). The plugin then uses this suggestions prop instead of the `emojiList` generated list. However, if no suggestions are passed in, the plugin falls back to the list generated by `emojiList.js`.

**Comment by nikgraf** [comment]
Oh you mean just the list itself. You already can do that by providing a `priorityList`. It's document here: https://www.draft-js-plugins.com/plugin/emoji

**Comment by nikgraf** [comment]
I'm closing this for now, but happy to re-open it in case I misunderstood you.

**Comment by Rosey** [comment]
Doesn't the priority list only dictate the first emoji to show (eg when it first opens, the "top suggestions") but all other emoji from emojilist are still available if the user types enough to match one of them?

**Comment by nikgraf** [comment]
@Rosey yeah, that's correct. Okay so you want to limit the list of emojis - hmmm this is probably such an edge case that I rather recommend to fork the plugin, because even if you limit the autocompletion people could still paste in the Emoji and that would be weird, because some are replaced than while others aren't.
