### ISSUE TITLE
Apply mention suggestion on spacebar?

### ISSUE THREAD

**Issue by bernardw** [draft-js-plugins/draft-js-plugins#745]
Hi, I am using the mention plugin, I wonder if there is an easy way so `space` behaves the same as `tab` and commit last highlighted suggestion without having to subclass MentionSuggestion?

**Comment by nikgraf** [comment]
@bernardw I guess you mean that it autocomplete to the next result -> not really at this point and I believe this would be cause some UX issues. Think about the case where someone doesn't want it to be autocompleted, but rather have text.

If you still want this feature the best way is to for the mention plugin. I'm closing this for now, but happy to re-open if I misunderstood you.
