### ISSUE TITLE
Can't resolve './emojiSelectStyles.scss' in Emoji Plugin (rc1)

### ISSUE THREAD

**Issue by stevewillard** [draft-js-plugins/draft-js-plugins#748]
I recently updated my plugins to `rc1` and the emoji plugin is referencing a module that doesn't exist:
```
ERROR in ./~/draft-js-emoji-plugin/lib/index.js
Module not found: Error: Can't resolve './emojiSelectStyles.scss' in '/.../node_modules/draft-js-emoji-plugin/lib'
resolve './emojiSelectStyles.scss' in '/.../node_modules/draft-js-emoji-plugin/lib'
  using description file: /.../node_modules/draft-js-emoji-plugin/package.json (relative path: ./lib)
```

**Comment by ryanmcclure4** [comment]
I'm having this same issue. `emojiSelectStyles.scss` does not exist in the folder.

**Comment by stevewillard** [comment]
@bashkos Any idea on this? Looks like you made most of the recent emoji plugin commits.

**Comment by bashkos** [comment]
Thank you for issue. I'm try to resolve it.

**Comment by bashkos** [comment]
I just pushed PR. Sorry for troubles.

**Comment by nikgraf** [comment]
Will release in a bit rc2

**Comment by stevewillard** [comment]
Thanks guys! I really appreciate it.
