### ISSUE TITLE
React.PropTypes is deprecated and throwing a console warning.

### ISSUE THREAD

**Issue by ScottEfird** [draft-js-plugins/draft-js-plugins#751]
As of React 15.5.0 we should pull in the prop-types package and use that for our PropTypes. 
https://facebook.github.io/react/blog/2017/04/07/react-v15.5.0.html

Hopefully it will be an easy fix, thank you.

**Comment by ScottEfird** [comment]
Closed. I suspect I made this ticket too fast. I can't find any examples here where it is used. Sorry about that.

**Comment by nikgraf** [comment]
No worries 😊
