### ISSUE TITLE
Emoji plugin's emoji selector adds 321k to gzipped bundle size

### ISSUE THREAD

**Issue by tomkelsey** [draft-js-plugins/draft-js-plugins#753]
Hey,

I love the new emoji selector, it's great!

However, by including the `react-icons` package it adds an extra 321k (gzipped) to the bundle size as its seemingly including all the font awesome icons rather than just the few that are used.

Perhaps changing:

```
import {
  FaSmileO,
  FaPaw,
  FaCutlery,
  FaFutbolO,
  FaPlane,
  FaBell,
  FaHeart,
  FaFlag,
} from 'react-icons/lib/fa';
```

to

```
import FaSmileO from 'react-icons/lib/fa/smile-o';
import FaPaw from 'react-icons/lib/fa/paw';
import FaCutlery from 'react-icons/lib/fa/cutlery';
import FaFutbolO from 'react-icons/lib/fa/futbol-o';
import FaPlane from 'react-icons/lib/fa/plane';
import FaBell from 'react-icons/lib/fa/bell';
import FaHeart from 'react-icons/lib/fa/heart';
import FaFlag from 'react-icons/lib/fa/flag';
```

Would fix things although I haven't had a chance to try.

FAO @bashkos

**Comment by nikgraf** [comment]
would be awesome to get it down again! 🙌

**Comment by lindskogen** [comment]
Have you tried using rollup for doing this automatically?
