### ISSUE TITLE
Consider new API to avoid overloading the component instance

### ISSUE THREAD

**Issue by mattkrick** [draft-js-plugins/draft-js-plugins#754]
Currently, when making a component we have to create & manage a singleton:
```
class MyEditor extends Component {
  constructor(props) {
    super(props);
    const tagPlugin = createMentionPlugin({
      entityMutability: 'IMMUTABLE',
    });
    this.plugins = [tagPlugin];
    this.MentionSuggestions = tagPlugin.MentionSuggestions;
  }
  
  render() {
    return (
      <div>
        <Editor
          editorState={this.props.textAreaValue}
          onChange={this.props.setValue}
          plugins={this.plugins}
        />
        <this.MentionSuggestions
          onSearchChange={this.onSearchChange}
          suggestions={this.state.suggestions}
          onAddMention={this.onAddMention}
        />
      </div>
    )
  }
}
```

This is a bit confusing for a couple reasons
- You must dump your plugins and your modal onto `this`
- You have to manage the instantiation yourself
- The modal is a peer, not a child, of the Editor
- You have to grab the modal from `this`, which isn't very React-ish

Instead, I propose the following:
```
const MyEditor = (props) => (
  <Editor
    editorState={props.textAreaValue}
    onChange={props.setValue}
  >
    <MentionSuggestions
      entityMutability="IMMUTABLE"
      onSearchChange={props.onSearchChange}
      suggestions={props.suggestions}
      onAddMention={props.onAddMention}
    />
  </Editor>
)
```

Doing it this way allows you
- to use a stateless component when possible, as the instantiation occurs _inside_ the Editor
- less code since instantiation occurs inside the plugin editor (improved DX since there's less to mess up)
- visually, it makes sense that the modal is a child of the editor

Internally, the `Editor` simple iterates over the children when it is instantiated. Basically it does what the developer had to do in the app code.

**Comment by nikgraf** [comment]
I like the idea … for such a big change I would probably even consider higher order components. Since I don't have a ton of time to invest I don't see such big API changes happening soonish … sorry
