### ISSUE TITLE
404 on npm install draft-js-drag-n-drop-upload-plugin

### ISSUE THREAD

**Issue by ar7casper** [draft-js-plugins/draft-js-plugins#755]
![image](https://cloud.githubusercontent.com/assets/5730102/26582614/8762fc3c-454a-11e7-879c-0d475bc03464.png)

**Comment by nikgraf** [comment]
This plugin yet wasn't published

**Comment by antoinerousseau** [comment]
@nikgraf why not?

**Comment by nrfm** [comment]
@nikgraf  
any updates on this?
Where is the best place to get a clear picture of the status/blocks and see if i can help with it?

thanks for the hard work!

**Comment by divyenduz** [comment]
I am still running into a 404 for this one? Is this published to npm now? If no, is there any blocked task that I can pick up to move this :)

Thanks for all the hard work.

**Comment by Arieg419** [comment]
hey, any update on this? @nikgraf

**Comment by sofianeOuafir** [comment]
any update on this?

**Comment by mrfambo** [comment]
What the hell? Where is the team to respond?
