### ISSUE TITLE
Emoji plugin - use host system art

### ISSUE THREAD

**Issue by tumetus** [draft-js-plugins/draft-js-plugins#756]
The emoji plugin now uses EmojiOne art for emojis and this ensures consistent display across all platforms. I would however like to be able to use the default emoji art for the platform that my app is running on.

Is this something that could be implemented? I could try to work on a PR if so.

**Comment by nikgraf** [comment]
@tumetus you could fork the emoji plugin and replace the rendering parts where we show images in the autocompletion & picker.

I'm interested in a PR 🙂

**Comment by tumetus** [comment]
@nikgraf I created a PR for this 🙂  #758

**Comment by tumetus** [comment]
Closing this, PR for this is merged :)
