### ISSUE TITLE
Inline toolbar on mobile - should it be positioned below the text?

### ISSUE THREAD

**Issue by tomkelsey** [draft-js-plugins/draft-js-plugins#757]
I was just wondering what people thought about the inline toolbar on mobiles.

At the moment it ends up behind the iOS/Android formatting toolbar that also appears above the text and so isn't accessible.
[](url)

![screen shot 2017-05-31 at 09 41 01](https://cloud.githubusercontent.com/assets/14311327/26623346/535b2324-45e5-11e7-8a37-c20dc395a0cc.png)

Would it make sense if on mobile/tablet sized devices the toolbar was below the text so that the user had access to both the system menu and the draft-js one?

Or would it make more sense just to hide it on mobile given it is "stuck" behind the system toolbar anyway?

Happy to have a stab at a PR for this but thought I'd see what people thought!

**Comment by StorytellerCZ** [comment]
I've noticed that the common behavior is to have it at the bottom of the screen, in the end being just above the keyboard. So I think that makes sense and would be a nice improvement. Go ahead with the PR, so that we have something more concrete and can test it.

**Comment by sidewayskumara** [comment]
Wondering if there’s been any progress on this. Super keen on the idea!
