### ISSUE TITLE
Improve Tests

### ISSUE THREAD

**Issue by nikgraf** [draft-js-plugins/draft-js-plugins#76]
HashtagPlugin
- [ ] plugin config: theme
- [ ] test hashtag matching (strategy)

Undo Plugin
- [x] RedoButton: button is disabled in case the getRedoStack is empty
- [x] RedoButton: button is not disabled in case the getRedoStack is not empty
- [x] RedoButton: onClick on the button triggers an update with a redo
- [x] UndoButton: button is disabled in case the getRedoStack is empty
- [x] UndoButton: button is not disabled in case the getRedoStack is not empty
- [x] UndoButton: onClick on the button triggers an update with a redo
- [x] plugin config: undoContent
- [x] plugin config: redoContent
- [x] plugin config: theme

Linkify Plugin
- [ ] plugin config: theme
- [ ] link strategy

Sticker Plugin
- [ ] TODO come up with a list

Mention Plugin
- [ ] TODO come up with a list

Emoji Plugin
- [x] TODO come up with a list

**Comment by juliankrispel** [comment]
Closing for issue cleanup - If you need this issue and think it should remain open please let us know why, thank you
