### ISSUE TITLE
Alignment plugin: deleting the picture still shows the toolbar

### ISSUE THREAD

**Issue by peorth80** [draft-js-plugins/draft-js-plugins#763]
If I go to the demo https://www.draft-js-plugins.com/plugin/alignment and delete the image, the toolbar still displays the alignment toolbar, as if the image still exists.

![image](https://cloud.githubusercontent.com/assets/16003799/26803383/61e10362-4a1a-11e7-9116-e2eb871e7e93.png)

How to reproduce:

1. Go to https://www.draft-js-plugins.com/plugin/alignment
2.  Scroll down to the example
3. Delete the image using the backspace key or the delete key
4. The alignment toolbar still exists. It should not, since the image no longer exists.

**Comment by ramrami** [comment]
I just created a PR #804 to fix this issue, hopefully it will be merged soon 😄
