### ISSUE TITLE
Demo code does not work or instructions insufficient.

### ISSUE THREAD

**Issue by andpor** [draft-js-plugins/draft-js-plugins#765]
Hi there,

I have created a project to test out Alignment Plugin demo and followed the instructions on the site. 
When I run the project, I get a page looking similar to demo page except the blue rectangle does not seem to be active. 
1 - it does not get any border when mouse hovering on top of it
2- does not respond to mouse clicks - thus no toolbar/menu

There are no errors in console.

Is there a boiler-plate project I should use to get started with plugins? It is quite frustrating to follow the instructions , whatever is available, and see the app not working as it should...

is there a git repo that has the example code, ready to run?

I am running on Chrome 57.0.2987.133 (64-bit).

**Comment by andpor** [comment]
The instructions for the demo are not correct. First example I try and it is mesed up...

3. Add the below import line to your component to tell Webpack to inject the style to your component.

import 'draft-js-image-plugin/lib/plugin.css'; // eslint-disable-line import/no-unresolved

This is incorrect.

Instead, these ought to be added to SimpleAlignmentEditor.js

import 'draft-js-alignment-plugin/lib/plugin.css'; 
import 'draft-js-focus-plugin/lib/plugin.css';
import 'draft-js-inline-toolbar-plugin/lib/plugin.css';

Once these are in, the focus and clicking (toolbar) all work fine.

The other question is...why do I have to import internal files from plugins into the main component????

**Comment by pencilcheck** [comment]
Yea, I also got it work by including a lot of plugins. I wish there is a much better way to detect dependencies and use of decorators patterns more consistently among plugins...

**Comment by semiromid** [comment]
Not working

**Comment by juliankrispel** [comment]
We need to make this stuff clearer in docs, I'm working on new docs and will consider this
