### ISSUE TITLE
FocusPlugin uses css styles named draftJsEmojiPlugin

### ISSUE THREAD

**Issue by andpor** [draft-js-plugins/draft-js-plugins#767]
These styles should be named draftJsFocusPlugin rather than draftJsEmojiPlugin

lib/plugin.css:

.draftJsEmojiPlugin__unfocused__1Wvrs:hover {
  cursor: default;
  border-radius: 2px;
  box-shadow: 0 0 0 3px #D2E3F7;
}

.draftJsEmojiPlugin__focused__3Mksn {
  cursor: default;
  border-radius: 2px;
  box-shadow: 0 0 0 3px #ACCEF7;
}

**Comment by juliankrispel** [comment]
Great find @andpor thank you! Fix is on the way
