### ISSUE TITLE
Need UMD buiild  Help Required

### ISSUE THREAD

**Issue by gmchaturvedi1** [draft-js-plugins/draft-js-plugins#768]
hello all,

i just build editor with help of draftjsplugin(editor,mathjax,image ) and save to database in row satate. in my web application i just render that row state perfectle. I need help to render the same in react-native webview but their i required UMD build .Jindly guide if any other method is their to render this is react-native.

regards
gmchaturvedi

**Comment by juliankrispel** [comment]
@gmchaturvedi1 you could help us debug this by setting up a little repository for reproducing this. Would be awesome :)
