### ISSUE TITLE
Make keyBindingFn signature consistent with the others

### ISSUE THREAD

**Issue by danneu** [draft-js-plugins/draft-js-plugins#769]
Over a week ago, there was a change that migrated the `(...args, {getEditorStore, ...})` signature of all the Editor prop functions to `(...args, editorStore, pluginFunctions)`.

https://github.com/draft-js-plugins/draft-js-plugins/blob/161e4176a5138dff60188d8c2f4c997273894ea9/draft-js-plugins-editor/CHANGELOG.md#added

However, I noticed that `keyBindingFn` still has the `(e, {getEditorStore})` signature which makes it the only function I use in my plugins that I didn't have to migrate over.

I'm new to draft.js but it seemed like an oversight.

v2.0.0-rc2

**Comment by danneu** [comment]
I also noticed `onTab`'s signature is also `(e, {getEditorState})`. I guess just the props that start with `handler*` get that signature?

I must be missing the distinction, but it seems simplest to just pass `getEditorState` in to the plugin's entrypoint config object than grappling with it per-function.

**Comment by lakesare** [comment]
This broke my production! Did you just remove `"draft-js-plugins-editor": "^2.0.0-beta1"` at some point and created newer backwards-incompatible versions?

**Comment by danneu** [comment]
@lakesare Hey, I closed this issue because I decided I didn't have enough experience with this project to understand how to use the signatures properly much less comment on them.

I think it would be more valuable for you to make an issue coming from your own experience since you're an actual user.
