### ISSUE TITLE
File `videoStyles.css` not getting created on npm build in version 2.0.0-rc2

### ISSUE THREAD

**Issue by NamitYadav** [draft-js-plugins/draft-js-plugins#771]
Hi, I am getting the following error on trying to use the **draft-js-video-plugin**:

`Module not found: Can't resolve './videoStyles.css' in '.../node_modules/draft-js-video-plugin/lib'`

I am using the following version: 
` 
"draft-js-plugins-editor": "^2.0.0-rc2",
"draft-js-video-plugin": "^2.0.0-rc2",
`

**Comment by nikgraf** [comment]
@NamitYadav we published a rc3 recently and going to publish a rc4 today. You can find it under `/lib/plugin.css`
