### ISSUE TITLE
Use the Emojione Sprite

### ISSUE THREAD

**Issue by mkates** [draft-js-plugins/draft-js-plugins#772]
The EmojiSelect works great but it makes an individual call for each SVG emoji, resulting in over a thousand network requests. Is there a way to use the emojisprite instead in the popover?

**Comment by Rosey** [comment]
Sort of related -

I like the idea of a sprite too. I am in a situation where I let the user choose which emoji set they want (twitter, emojione, apple, google) and I'm using emoji-data (https://github.com/iamcal/emoji-data) for this. For me, it would be so super convenient if the plugin switched to use emoji-data & its sprites and supported emoji type as an option - right now I just define the path for the images, which works well, but if we were to switch to sprites I would worry that the mapping in the emoji one sprites wouldn't be 1:1 with the mapping in the emoji data sprites, so would make it harder to simply define a custom path like I do right now.

**Comment by juliankrispel** [comment]
Yea that's fair enough. I think we need to make this plugin more configurable in general.

**Comment by juliankrispel** [comment]
@bashkos were you going to look at this?

**Comment by stevewillard** [comment]
Is anyone working on this? I can try to find some time next week to work on this.

**Comment by creativelikeadog** [comment]
Anyone ?
