### ISSUE TITLE
custom mention component

### ISSUE THREAD

**Issue by matt-erhart** [draft-js-plugins/draft-js-plugins#776]
In the custom mention component example, createMentionPlugin takes an object with the mentionComponent field which is a function that takes props and returns the custom component. Output of createMentionPlugin get passed into the plugins prop on the editor component. 

With a setup like this, how do I pass props into each of my custom mention components from the editor? My short term goal is to just show details of a mention on click, but ideally I'd like as much control over each mention component as I do any other react component.

**Comment by deanshub** [comment]
currently I use suggestions prop and send my own suggestion object but to reach it from the mentionComponent is a nightmare, I use 
```
this.props.mention._root.entries
```

**Comment by haydenbleasel** [comment]
I needed to bind mentions to React Router's `Link` component. Took a bit of digging but here's what I got:

```
import React, { Component } from 'react';
import { Link } from 'react-router-dom';
import { fromJS } from 'immutable';
import _ from 'lodash';

function getMentionLink (arrays) {
    const mention = _.chain(arrays).map((array) => {
        const object = {};
        const key = array[0];
        const value = array[1];

        object[key] = value;

        return object;
    }).flatten().find('link').value();

    return mention.link;
}

const mentionComponent = ({ entityKey, mention, className, decoratedText }) => (
    <Link className={className} to={getMentionLink(mention._root.entries)}>{decoratedText}</Link>
);

function UserSuggestions ({ firstName, lastName, objectId, photo }) {
    const name = `${firstName} ${lastName}`;
    const link = `/profile/${objectId}`;
    const avatar = photo;

    return { name, link, avatar };
}

const mentionSuggestions = fromJS(props.users.map(UserSuggestions));
const mentionPlugin = createMentionPlugin({ mentionComponent });
```

**Comment by haydenbleasel** [comment]
Check out https://github.com/draft-js-plugins/draft-js-plugins/issues/290#issuecomment-318878114
