### ISSUE TITLE
A section of the toolbar is hidden when selected text is too close to the left edge

### ISSUE THREAD

**Issue by edwinmp** [draft-js-plugins/draft-js-plugins#777]
![capture](https://user-images.githubusercontent.com/5672438/27275579-b45060fe-54e0-11e7-8404-a7548eb34f49.PNG)

This is unlike the toolbar behavior when the selected text is too close to right edge, which auto adjusts from a horizontal to a vertical position.

![capture2](https://user-images.githubusercontent.com/5672438/27275636-f183ecb6-54e0-11e7-98ac-80761e4143c9.PNG)

**Comment by juliankrispel** [comment]
Nice find! Thanks for reporting, If anyone wants to open pr for fixing this please do!
