### ISSUE TITLE
Autocomplete Component (to be used by other plugins)

### ISSUE THREAD

**Issue by juliankrispel** [draft-js-plugins/draft-js-plugins#78]
The mention plugin has fairly fleshed out predictive text functionality, instead of redoing this for every plugin with functionality like that it'd be great to keep improving/working on one and making it available for building other plugins.

**Comment by nikgraf** [comment]
Agreed, what I usually do in auch a case is copy the whole thing and build it out. Once it's fairly fleshed out I check where it makes sense to refactor code out into a common module. I would say: whatever works best for you is fine.

There is definitely value in such tooling

**Comment by mjrussell** [comment]
Im actually pretty interested in creating this capability. I'll try to take this on. 

My first goal is to split the Suggestions (autocomplete) from the decorator which displays the Mention/Emoji/etc and then make this part a "plugin creator" i.e. taking parameters to render the suggestion entries.

I think the one downside of this approach I could see is that the mention plugin would need to be 2 separate plugins, i.e. mention suggestions, and mentions and I don't see an easy way to "merge" the result of the plugin-creator and the regular decorator.

**Comment by danielberndt** [comment]
I really would like to see this feature as well. Here's one requirement for my current use case that might be interesting to consider: I would like to be able to offer an autocomplete for hashtags that also allows me to create Tag-Entities if I type a new tag not offered by the autocomplete.

**Comment by nikgraf** [comment]
@danielberndt this actually is done by @mjrussell https://github.com/mjrussell/draft-js-autocomplete-plugin-creator, but could use some documentation … interested to helm him out?
