### ISSUE TITLE
InlineToolbar reuse conflict

### ISSUE THREAD

**Issue by jf423** [draft-js-plugins/draft-js-plugins#784]
**I have an issue when I plan to reuse the inline tool bar.
Here is the situation.**

**First I wrap the InlineToolbar into the component called Draft.**

`import React, { Component } from 'react';`
`import PropTypes from 'prop-types';`
`import { css } from 'glamor';`
`import { EditorState } from 'draft-js';`
`import Editor, { createEditorStateWithText } from 'draft-js-plugins-editor';`
`import createInlineToolbarPlugin, { Separator } from 'draft-js-inline-toolbar-plugin';`

`const inlineToolbarPlugin = createInlineToolbarPlugin();`
`const { InlineToolbar } = inlineToolbarPlugin;`

`class Draft extends Component {`
 &emsp;`static propTypes = {`
        &emsp;`EditorState: PropTypes.func,`
        &emsp;`draftStyle: PropTypes.shape(),`
        &emsp;`style: PropTypes.shape()`
    `}`
   `constructor(props) {`
        &emsp;`super(props);`
&emsp;`const plugins = [inlineToolbarPlugin];`
&emsp;`        const text = 'In this editor a toolbar shows up once you select part of the text …';`
&emsp;  `      this.state = {`
&emsp;&emsp;    `        editorState: createEditorStateWithText(text),`
&emsp;&emsp;      `      plugins: plugins`
&emsp;        `};`
   ` }`
`    onChange = editorState => {`
&emsp;`        this.setState({ editorState });`
`    }`
`    focus = () => {`
&emsp;`        this.editor.focus();`
`    }`
`    render() {`
&emsp;`        const { draftStyle, index } = this.props;`
&emsp;  `      const { plugins } = this.state;`
&emsp;`        return (`
&emsp;&emsp;`            <div className={css(editor, draftStyle)} onClick={this.focus} >`
&emsp;&emsp;         &emsp;` <Editor`
&emsp;    &emsp;        &emsp;   &emsp;   `key={index}`
 &emsp;   &emsp;       &emsp;     &emsp;  `editorState={this.state.editorState}`
 &emsp;       &emsp;     &emsp;  &emsp;   `onChange={this.onChange}`
  &emsp;   &emsp;   &emsp;        &emsp;  `plugins={plugins}`
 &emsp;     &emsp;      &emsp;   &emsp;   `ref={element => { this.editor = element; }}`
  &emsp;     &emsp;     &emsp;    `/>`
  &emsp;    &emsp;   &emsp;      `<InlineToolbar />`
  &emsp;    &emsp;      `</div>`
 &emsp;  &emsp;     `);`
 &emsp;   `}`
`}`

`export default Draft;`

`const editor = {`
`    boxSizing: 'border-box',`
 `   border: '1px solid #ddd',`
   ` cursor: 'text',`
    `padding: '16px',`
    `borderRadius: '2px',`
   ` marginBottom: '2em',`
    `boxShadow: 'inset 0px 1px 8px -3px #ABABAB',`
    `background: '#fefefe'`
`};`

**And I include like this**
`<div>`
&emsp;`<div><Draft /></div>`
&emsp;`<div><Draft /></div>`
`</div>`

**Then, Conflict happened like this, seems like both of tool bar has been triggered.**

![2017-06-29 4 30 39](https://user-images.githubusercontent.com/11975649/27678606-618b012a-5ce8-11e7-92d1-da0ef1bbeaab.png)

**Does I make any mistake or incorrect usage ?? 
Apology, if I ask some stupid question.( I am new to the Draft.js )**

**Comment by juliankrispel** [comment]
@jf423 you need to instantiate one plugin per editor. It's not super obvious but is documented

**Comment by nikgraf** [comment]
@varghesethomase I hope this helps https://github.com/draft-js-plugins/draft-js-plugins/blob/master/FAQ.md#can-i-use-the-same-plugin-for-multiple-plugin-editors

**Comment by nabeelnazirvf** [comment]
@nikgraf @juliankrispel you are saying that if I have 10 editors in one page then I have to instantiate 10 plugins for these 10 editors?
Is there any way to achieve this dynamically? Like for example, I have a dynamic form builder in react JS and requirement is to add `InlineToolbar` with every new dynamic text area. How can we achieve this by using your plugin?

**Comment by juliankrispel** [comment]
that's exactly what we're saying yes. That's how it works right now I'm
afraid. If you want to achieve this dynamically just move the plugin
instantiation into a component lifecycle method

**Comment by nabeelnazirvf** [comment]
@juliankrispel following code works for me. I am pasting it here so that it may help others as well. 

```
import React, { Component } from 'react';
import withStyles from 'isomorphic-style-loader/lib/withStyles';
import Editor from 'draft-js-plugins-editor';
import createLinkPlugin from 'draft-js-anchor-plugin';
import createInlineToolbarPlugin from 'draft-js-inline-toolbar-plugin';
import draftDefaultStyles from './DraftDefault.css';
import editorStyles from './DraftEditor.css';
import buttonStyles from './buttonStyles.css';
import toolbarStyles from './toolbarStyles.css';
import linkStyles from './linkStyles.css';

import ss from 'draft-js-inline-toolbar-plugin/lib/plugin.css';
import { convertToRaw, EditorState } from 'draft-js';
import { stateToHTML } from 'draft-js-export-html';
import { stateFromHTML } from 'draft-js-import-html';
import { UnorderedListButton, OrderedListButton } from 'draft-js-buttons';
import customBranding from '../../../../hoc/customBranding/customBranding';

import { connect } from 'react-redux';
import { compose } from 'redux';
import { withCookies } from 'react-cookie';

const linkPlugin1 = createLinkPlugin({
  theme: linkStyles,
  placeholder: 'Enter a valid URL and press enter.',
  linkTarget: '_blank',
});

@customBranding
class DraftEditorSingle extends Component {
  constructor(props) {
    super(props);
    this.inlineTool = createInlineToolbarPlugin({
      theme: { buttonStyles, toolbarStyles },
    });
    this.linkPlugin = createLinkPlugin({
      theme: linkStyles,
      placeholder: 'Enter a valid URL and press enter.',
      linkTarget: '_blank',
    });
    const contentState = stateFromHTML(props.description);
    this.state = {
      editorState: EditorState.createWithContent(contentState),
    };
    this.onChange = this.onChange.bind(this);
  }

  onChange(editorState) {
    this.setState({
      editorState,
    });
    const content = editorState.getCurrentContent();
    const dataToSaveBackend = convertToRaw(content);
    let options = {
      entityStyleFn: entity => {
        const entityType = entity.get('type').toLowerCase();
        if (entityType === 'link') {
          const data = entity.getData();
          return {
            element: 'a',
            attributes: {
              href: data.url,
              target: '_blank',
            },
            style: {
              // Put styles here...
            },
          };
        }
      },
    };
    this.props.descriptionEditChild({
      target: { value: stateToHTML(content, options) },
    });
  }

  focus = () => {
    this.editor.focus();
  };

  placeholderSwitch = (param, alias_program) => {
    switch (param) {
      case 'description':
        return `${alias_program} intro...`;
      case 'eligibility':
        return `Enter any eligibility requirements for the ${alias_program}...`;
      case 'scholarship':
        return `Enter any scholarship information for the ${alias_program}...`;
      case 'subDescription':
        return `${alias_program} Description...`;
      case 'activities':
        return null;
      default:
        return null;
    }
  };

  cssSwitch = param => {
    switch (param) {
      case 'description':
        return editorStyles.newDescriptionInput;
      case 'eligibility':
        return editorStyles.newEligibility;
      case 'scholarship':
        return editorStyles.newScholarship;
      case 'subDescription':
        return editorStyles.newSubDescriptionInput;
      case 'activities':
        return editorStyles.newActivitiesAndAdmin;
      case 'excursions':
        return editorStyles.newActivitiesAndAdmin;
      case 'addOns':
        return editorStyles.newActivitiesAndAdmin;
      default:
        return editorStyles.newDescriptionInput;
    }
  };

  render() {
    const { status } = this.props;
    const { alias_program } = this.props.alias_program ? this.props : 'Program';
    const plugins = [this.inlineTool, this.linkPlugin];
    const { InlineToolbar } = this.inlineTool;
    const { LinkButton } = this.linkPlugin;
    return (
      <div className={this.cssSwitch(status)} onClick={this.focus}>
        <div>
          <Editor
            editorState={this.state.editorState}
            onChange={this.onChange}
            plugins={plugins}
            ref={element => {
              this.editor = element;
            }}
            placeholder={this.placeholderSwitch(status, alias_program)}
          />
          <InlineToolbar>
            {externalProps => (
              <div>
                <UnorderedListButton {...externalProps} />
                <OrderedListButton {...externalProps} />
                <LinkButton {...externalProps} />
              </div>
            )}
          </InlineToolbar>
        </div>
      </div>
    );
  }
}

const mapStateToProps = state => ({
  customBranding: state.profile.customBranding || {},
});

export default compose(
  withCookies,
  withStyles(
    draftDefaultStyles,
    ss,
    editorStyles,
    buttonStyles,
    toolbarStyles,
    linkStyles,
  ),
  connect(
    mapStateToProps,
    null,
  ),
)(DraftEditorSingle);


```
