### ISSUE TITLE
Cant extend the theme, instead completely overrides the existing theme.

### ISSUE THREAD

**Issue by varghesethomase** [draft-js-plugins/draft-js-plugins#786]
const emojiPlugin = createEmojiPlugin({
  theme: {
    emoji: 'emoji-wrapper',
  },
});

This overrides the whole of the theme and the style for the emojiSelect breaks. 
![screen shot 2017-07-01 at 6 02 48 pm](https://user-images.githubusercontent.com/5429756/27762073-8f6514dc-5e87-11e7-8d4d-c9bc655b2f22.png)
![screen shot 2017-07-01 at 6 02 55 pm](https://user-images.githubusercontent.com/5429756/27762074-92793950-5e87-11e7-9be7-6aba5b0b82cc.png)

**Comment by juliankrispel** [comment]
@varghesethomase you can include the styles from `draft-js-emoji-plugin/lib/plugin.css` and then extend that yourself!

**Comment by nikgraf** [comment]
@varghesethomase I hope this helps https://github.com/draft-js-plugins/draft-js-plugins/blob/master/FAQ.md#can-i-use-the-same-plugin-for-multiple-plugin-editors

**Comment by glenswift** [comment]
Each class in `draft-js-emoji-plugin/lib/plugin.css` has suffixes, how can I reliable overwrite them?

**Comment by icd2k3** [comment]
Same issue here, what's the proper way to extend default themes instead of replacing them? Can't find anything in the docs...

**Comment by Sauloxd** [comment]
I created a gist that mimics all the styling for v2.1.1.
Not the best approach, but it exports all named classes:
https://gist.github.com/Sauloxd/284b1f90b715e962cff8a79f66686a56

**Comment by waveiron** [comment]
Why this issue is closed?
