### ISSUE TITLE
Can't select block with alignment plugin after typing

### ISSUE THREAD

**Issue by juhaelee** [draft-js-plugins/draft-js-plugins#787]
![alignment](https://user-images.githubusercontent.com/606411/27770850-1dfd82b0-5f14-11e7-9688-c391c2d049a6.gif)

After typing you can't select the block unless you remove the text you already inputed

**Comment by juliankrispel** [comment]
aha, will look int o thi

**Comment by juliankrispel** [comment]
thanks for reporting the issue

**Comment by juliankrispel** [comment]
@juhaelee this seems to work fine now. I believe it was fixed by a recent pr to the focus plugin. Here's proof:

![alignment-working](https://user-images.githubusercontent.com/1188186/30835439-ff8b38de-a24f-11e7-8ccb-bdd76747214d.gif)

If you can still somehow reproduce it let me know!
