### ISSUE TITLE
[mentions] Avoid optionally stripping first char of search value?

### ISSUE THREAD

**Issue by FredyC** [draft-js-plugins/draft-js-plugins#789]
The mentions plugin is the closest match I found so far for my use case. Essentially what I want is not usual mention-like behavior, but I have a simple keyword map in the form of `Dictionary<string, string>`. Whenever the user types in 2+ characters, I want to display all suggestions based on the filter of values from this map.

```js
const mentionPlugin = createMentionPlugin({
  mentionTrigger: '',
  mentionRegExp: '[a-zA-Z]{2,}'
});
```

I was almost excited when I did this, and it seemed to work. A few seconds later I've realized there are too many results. After a little digging I found out that first character of entered word is stripped away. Instead of search for "ma", it does search for "a" only.

This behavior is rather [deeply hidden](https://github.com/draft-js-plugins/draft-js-plugins/blob/master/draft-js-mention-plugin/src/MentionSuggestions/index.js#L175). I am wondering what are my options here. Would you consider to have this part configurable? I would be willing to create PR with a possible solution for that. It could be something simple like...

```js
const startIndex = this.props.mentionTrigger.length;
const searchValue = word.substring(startIndex, word.length);
```

**Comment by juliankrispel** [comment]
I'll have a look at this and get back to you!
