### ISSUE TITLE
Not able to delete any letter within DraftJS when I implement Mentions for andrewcoelho/react-text-editor

### ISSUE THREAD

**Issue by suhasmanjunath** [draft-js-plugins/draft-js-plugins#792]
Hello @nikgraf @andrewcoelho ,

I tried implementing draft-js-plugins Mentions plugin for [andrewcoelho/react-text-editor](https://github.com/andrewcoelho/react-text-editor). The Mentions implementation was successful, however the editorState was hanging everytime causing DraftJS text cursor immovable. Neither deleting nor selecting! Requesting you to kindly assist.

I think the editor state onChange event has to do with this:
```
this.onChange = (editorState) => {
      if (!editorState.getSelection().isCollapsed()) {
        const selectionRange = getSelectionRange();
        const selectionCoords = getSelectionCoords(selectionRange);
        this.setState({
          inlineToolbar: {
            show: true,
            position: {
              top: selectionCoords.offsetTop,
              left: selectionCoords.offsetLeft
            }
          }
        });
      } else {
        this.setState({ inlineToolbar: { show: false } });
      }
```

**Comment by juliankrispel** [comment]
@suhasmanjunath for questions and troubleshooting please ask on stackoverflow or on the draft.js slack, I'd be happy to help and so would others!
