### ISSUE TITLE
Is it possible to invoke button actions externally?

### ISSUE THREAD

**Issue by po5i** [draft-js-plugins/draft-js-plugins#795]
Let's say that I have a button somewhere out of the editor (or an Electron app menu), I want to invoke BOLD like I have pressed the bold button from the inline toolbar.

Is it possible?

**Comment by samkelleher** [comment]
Yeh it's possible, the editor is just rendering what's in its state so as long as you can see this you can manipulate it.

Examine the source for the draft-js-buttons project as this contains a hint for detecting when a style is active and toggling it.

https://github.com/draft-js-plugins/draft-js-plugins/blob/master/draft-js-buttons/src/utils/createInlineStyleButton.js

This file should be a good starting point.

**Comment by po5i** [comment]
Thanks, I am getting into it. Could you give me a hint on how to access the Editor state (i.e. from a Store)

**Comment by po5i** [comment]
Hi @samkelleher , any help on this I will appreciate. Thanks.

**Comment by samkelleher** [comment]
Hello @po5i ,

draftjs actually have a example specifically for this, and the buttons plugin that draft-js-plugins provides basically just extends this example.

https://github.com/facebook/draft-js/blob/master/examples/draft-0-10-0/rich/rich.html

This example basically wraps an editor, has access to it's state, and mutates it based on interaction with formatting buttons (like bold). These buttons are thus external to the editor.

The `onChange` passed by the `Editor` is where you can pass that state object further up your component tree, for example, if your buttons are really far away from your editor.

Or they would come from a store, but I'd just recommend you to some good reading on something like redux as that doesn't really have anything todo with draftjs itself (it doesn't care where the value came from).

Have a look at that draftjs example as I think that show you want you need.

**Comment by po5i** [comment]
Awesome! Using an external store worked for me. I will run some tests from now.

Thanks!
