### ISSUE TITLE
🙏  Deleting whole decorated Text

### ISSUE THREAD

**Issue by jonmaciel** [draft-js-plugins/draft-js-plugins#799]
Hello there,
I've used decorator as text variable, and I have a problem when I need to delete any variable.
The way I've found:
-Span used to to decorate (`handleSpan`):
```
handleSpan(props) {
    const componentStartIndex = props.contentState.selectionBefore.anchorOffset
    const componentEndIndex = props.contentState.selectionAfter.anchorOffset

    return (
      <span style={styles.handle} data-offset-key={props.offsetKey} contentEditable={false}>
        <span>
          {this.varName()}
          <a onClick={() => this.removeVar(componentStartIndex, componentEndIndex)}>X</a>
        </span>
        <span style={{display: 'none'}}>{props.children}</span>
      </span>
    )
  }
```
NOTE: I use `props.contentState.selectionBefore.anchorOffset` to use it in `removeVar` callBack
NOTE2: `props.children` contains variable ID and I'm just ignoring it on displayed text

-Function used to delete decorator (it's called in `handleSpan`):
```
 removeVar(start, end) {
    let editorState = this.state.editorState
    let selectionState = editorState.getSelection()

    selectionState = selectionState.merge({anchorOffset: start, focusOffset: end})

    this.setState({
      editorState: EditorState.push(
        editorState,
        Modifier.removeRange(
          editorState.getCurrentContent(),
          selectionState,
          'forward'
        ),
        'remove-text'
      )
    })
  }
```

Is there another *(easier)*  way to do it?
Because, I'd like to delete these "variables" using *delete*/*backspace* key .

🤞

**Comment by juliankrispel** [comment]
@jonmaciel this isn't necessarily draft-js-plugins related. For questions and troubleshooting it's best to get on to the draft-js slack or post a question on stackoverflow
