### ISSUE TITLE
Forcing focus breaks plugins

### ISSUE THREAD

**Issue by ryanmcclure4** [draft-js-plugins/draft-js-plugins#800]
I've noticed that when i call `focus()` on the Editor, the emoji and mention plugins do not work -- that is, they do not respond to `:` or `@` and suggestions do not populate. I'm guessing `focus()` is somehow messing with the selectionState...any ideas on this?

**Comment by arempe93** [comment]
also having this issue, calling `focus()` breaks mention suggestions but inline toolbar works fine. on `v2.0.0-rc2`

**Comment by arempe93** [comment]
tried switching from doing this

```js
// render
<PluginEditor
  ref={el => { this.editor = el }}
  ...
/>

// componentDidMount
this.editor.focus()
```

to calling `focus()` on the DOM element directly like so

```js
// componentDidMount
this.editor.getEditorRef().refs.editor.focus()
```

both focus the editor correctly, but the problems with mentions persisted

**Comment by ryanmcclure4** [comment]
I was able to find a temporary solution to this problem by using `setTimeout` on the call to `focus`:

```setTimeout(this.editor.focus, 50)```

Strangely enough, this seems to solve the problem even if you set the timeout value to 0.

My original guess on why this works would be that there is still something in the mention suggestions that is still in the process of mounting or rendering, but the parent component's `componentDidMount` should't be called until after all this is complete. So really not sure...

**Comment by alixander-stripe** [comment]
Any update on this @juliankrispel ? I ran into this issue as well and it's not obvious that focusing would be a blocking issue to having the mentions plugin work. Maybe it could be noted in docs for now

**Comment by diegohaz** [comment]
I just spent about 4 hours to figure out why my `mention` and `linkify` plugin weren't working. That was so frustrating.

We should give more attention to this issue.

**Comment by Rafi993** [comment]
Any update on this issue ?

**Comment by thaoms** [comment]
+1

**Comment by jack-arms** [comment]
+1, can we please at least add documentation for this?

**Comment by jkhaui** [comment]
This is a major issue, and has barely been acknowledged in 2 years :\ I guess this repo is no longer maintained?

**Comment by katsuomi** [comment]
I also had that problem...

**Comment by orlandodemauro** [comment]
@juliankrispel first off all thanks for the amazing work. is there an update on this issue? thanks

**Comment by Developer-reyna** [comment]
Do you know if there is already a solution to this problem or when the solution will be available?

**Comment by jkhaui** [comment]
> Do you know if there is already a solution to this problem or when the solution will be available?

@ryanmcclure4 's `setTimeout` solution works. Last time I remember using it with 0 seconds and it still worked.

But obviously this isn't a desirable solution. If I knew how to fix the underlying issue I would post a PR.

**Comment by ksjogo** [comment]
The underlying issue is something like this (from memory):
1. A new editor component is created
2. The plugins component takes the initial state and adds all decorators from active plugins and then calls the passed in state updated function from the props (but doesn't update the internal state, as it is expecting the component parent to do that)
3. focus is called in the same render cycle and reads from props.state, changes the focus and then calls update state with that new state (which doesn't include the plugin decorators as the cycle from 2 didn't finish updating)
4. 3 overwrites the new state from 2 kicking out all decorators, breaking mentions, emojis, etc.

**Comment by ynnelson** [comment]
Still having this issue! +1

**Comment by rizalrhmn** [comment]
I'm still having this issue. when forcing focus, the mention plugin is not working anymore.

**Comment by rizalrhmn** [comment]
> I was able to find a temporary solution to this problem by using `setTimeout` on the call to `focus`:
> 
> `setTimeout(this.editor.focus, 50)`
> 
> Strangely enough, this seems to solve the problem even if you set the timeout value to 0.
> 
> My original guess on why this works was that there is still something in the mention suggestions that is still in the process of mounting or rendering, but the parent component's `componentDidMount` should't be called until after all this is complete...so really not sure.

this is weird but after following this, my code is running.

**Comment by ynnelson** [comment]
@rizalrhmn I opened a separate issue on #1511 , it seems to be a race condition. Hence why `setTimeout` helps.

**Comment by rizalrhmn** [comment]
@ynnelson that's make sense. thank you!

**Comment by ali-718** [comment]
focus() avoids the mount of plugins in Editor, you have to wait millisecond to load plugins, have a look at my code. 

```
let editor = useRef();

    useEffect(() => {
        if (isFocused) {
            setTimeout(() => {
                editor?.current?.focus();
            }, 200);
        }
    }, []);

```
```
 <Editor
                                ref={editor}
                                plugins={plugins}
                                onChange={onChange}
                                editorState={text}
                                onBlur={() => setIsFocus(false)}
                            />
```
