### ISSUE TITLE
Handling pasted text with handlePastedText does not work!

### ISSUE THREAD

**Issue by ramrami** [draft-js-plugins/draft-js-plugins#806]
I just want to trim the text when pasting, to avoid undesired whitespace. The DraftJs docs says that I should use `handlePastedText`, that's what I did with the following code : 

```javascript
  handlePastedText(text, html) {
    console.log("handlePastedText executed");
    const {editorState} = this.state;
    const newState = Modifier.replaceText(editorState.getCurrentContent(), editorState.getSelection(), text.trim());
    this.onChange(EditorState.push(editorState, newState, 'insert-fragment'));

    return true;
  }
```

but that didn't work, until I changed `import { Editor } from 'draft-js-plugins-editor';` to `import { Editor } from 'draft-js';`

Here are some gifs :

(With the normal Editor)
![ezgif com-video-to-gif 3](https://user-images.githubusercontent.com/9569590/28675635-5d5819a4-72e0-11e7-8d5c-618c7d0ab123.gif)

(With the Plugins Editor)
![ezgif com-video-to-gif 4](https://user-images.githubusercontent.com/9569590/28675737-99cad58e-72e0-11e7-9521-ad222d51812e.gif)

**Comment by juliankrispel** [comment]
thanks @ramrami  will investigate

**Comment by icd2k3** [comment]
Same issue here - simpler test:

```
import { Editor } from 'draftjs'
<Editor
  handlePastedText={() => true}  // blocks all text from being pasted into editor
  //...
/>
```

```
import Editor from 'draft-js-plugins-editor';
<Editor
  handlePastedText={() => true}  // still allows all text to be pasted into editor
  //...
/>
```

**Comment by icd2k3** [comment]
More details: to be clear, `handlePastedText` IS always called when pasting text, but the return value is ignored in draft-js-plugins-editor

**Comment by icd2k3** [comment]
@ramrami and @juliankrispel we figured this one out. The draft-js docs are confusing for [handlePastedtext](https://draftjs.org/docs/api-reference-editor.html#handlepastedtext) which state: 

> Handle text and html(for rich text) that has been pasted directly into the editor. Returning **true** will prevent the default paste behavior.

This should actually read:

> Handle text and html(for rich text) that has been pasted directly into the editor. Returning 'handled' will prevent the default paste behavior.

So, for my example above, switching to this works:

```
import Editor from 'draft-js-plugins-editor';
<Editor
  handlePastedText={() => 'handled'}  // blocks text from being pasted into editor
  //...
/>
```

**Comment by ramrami** [comment]
Thanks @icd2k3, this is interesting. However, if you look at the `draft-js` source code [here](https://github.com/facebook/draft-js/blob/master/src/component/utils/isEventHandled.js), the function is checking for `value === true`. 

```javascript
/**
 * Utility method for determining whether or not the value returned
 * from a handler indicates that it was handled.
 */
function isEventHandled(value: DraftHandleValue): boolean {
  return value === 'handled' || value === true;
}
```

So both values should work (maybe the docs should be updated with both values). But IMO it's still a problem with `draft-js-plugins` that sould check for both values, or use `isEventHandled` if it's public.

**Comment by icd2k3** [comment]
Thanks @ramrami I'll work on a fix here

**Comment by liangwenzhu** [comment]
I had met the same question.Thanks for your answer,and I had solved my question. Draft-js-plugins is amazing!! @icd2k3

**Comment by reynacortez2** [comment]
```
const {editorState} = this.state;
       console.log(editorState);
       const blockMap = ContentState.createFromText(text.trim()).blockMap;
       console.log(blockMap);
       const newState = Modifier.replaceWithFragment(editorState.getCurrentContent(), editorState.getSelection(), blockMap);
       console.log(newState);
       this.onChange(EditorState.push(editorState, newState, 'insert-fragment'));
       return true;
```

**Comment by ynnelson** [comment]
I came across the same issue. Using `handled` solved it for me, not sure why it still doesn't handle `true` has an answer.

**Comment by holdenmatt** [comment]
This also tripped me up until I found this issue. Using 'handled' instead of true works.

Would be helpful to future users if 'return true' just worked here (or Draft.js docs were updated to suggest using 'handled' instead).

**Comment by fxOne** [comment]
@holdenmatt maybe you want to add it to the [FAQ](https://github.com/draft-js-plugins/draft-js-plugins/blob/master/FAQ.md)? I would love to merge a PR!

**Comment by holdenmatt** [comment]
Ah I see, it seems the real issue here is Draft.js should update a line in their docs. I'll report there instead and can make a PR to update their docs if helpful. Thanks!
