### ISSUE TITLE
Focus plugin breaks on keyboard enter press

### ISSUE THREAD

**Issue by lukephills** [draft-js-plugins/draft-js-plugins#808]
Steps to reproduce:

1. Load 'Simple Focus Example': https://www.draft-js-plugins.com/plugin/focus
2. Focus the coloured box
3. Press enter

It should add a new line after the box, but instead crashes the app.

**Comment by nikgraf** [comment]
just confirmed

good find @lukephills! interested to contribute a fix?

**Comment by juliankrispel** [comment]
Just fixed this!
