### ISSUE TITLE
Does it make sense to have all plugins in one repository

### ISSUE THREAD

**Issue by juliankrispel** [draft-js-plugins/draft-js-plugins#812]
I get it, it's for ease of development, managing all the plugins etc. 

But it's also a little problematic. Because:

- We can't really tag releases in gh
- You can't install plugins from github (In some cases you might want to)
- It brings up the question of how we version plugins. Right now they always all have the same version...

@nikgraf WDYT?!

**Comment by ramsgoli** [comment]
I agree with these points! I'd like to install some of the plugins individually to experiment/make modifications but can't really do that easily. Maybe you can use git submodules?

**Comment by juliankrispel** [comment]
@ramsgoli feel free to chime in, feedback will be taken into account

**Comment by jrock17** [comment]
You can install each of the plugins separately (in fact that's the only way to install them). Once your editor is installed, just install the plugins you want like so:
`npm install draft-js-emoji-plugin@[version] --save`

**Comment by juliankrispel** [comment]
I think what he means is he'd like to fork plugins and get the packages from a git repo which isn't currently possible :/.

**Comment by juliankrispel** [comment]
I think the main thought behind one repository is that the project is easier to manage...

**Comment by juliankrispel** [comment]
Another really annoying thing about this is the confusion about versioning. Right now we version all of the plugins together, even if they don't change...
