### ISSUE TITLE
Resizeable and Alignment changes not saving to server

### ISSUE THREAD

**Issue by CalebGM** [draft-js-plugins/draft-js-plugins#813]
So I've been trying to use draft-js-plugins to form a rich text editor to write up articles. These articles are then saved to a server and brought back to be displayed.

I wanted to use resizeable and alignment plugins to move around images and change size. Then I use convertToRaw to store everything as a JSON in the server. And convertFromRaw to bring it back to an EditorState to display. However, when I do, the changes I made to image alignment and sizes are never saved in the JSON. I'm just wondering how I'm supposed to save the edits I make with these two plugins?

**Comment by juliankrispel** [comment]
@CalebGM the alignment plugin persists the alignment into the entity data like so:

![image](https://user-images.githubusercontent.com/1188186/30835655-35168f20-a251-11e7-9cf2-60256920a586.png)

So it  does persist. If you need more help, please provide a codesandbox or reach out to us on the draft js slack, I'd be happy to help 👍
