### ISSUE TITLE
Get Entity key for added mention in onAddMention

### ISSUE THREAD

**Issue by maniksingh92-xx** [draft-js-plugins/draft-js-plugins#822]
Hi,

I wish to get the `entityKey` of a mention when it is added to the draft editor.

I have a custom `mentionComponent` with an `onClick` event:
```javascript
const customMentionComponent = (props) => {
  return (<div
      onClick={ ()=>{executeSomeFunctionDependentOn(props.entityKey} }>
    {props.children}
  </div>)
};
```
Since a user can add a single mention multiple times within a draftjs editor instance, and I am displaying multiple draftjs editors at the same time, the purpose of my implementation is to manage and distinguish between inserted mentions, whether or not they may be the same.

---

I tried doing something like this with the `entityKey` from the state of the editor:
```javascript
onAddMention = (mention) => {
    let contentState = this.state.editorState.getCurrentContent();
    let entityKey = contentState.getLastCreatedEntityKey();
    contentState.mergeEntityData(entityKey, {"incremental_id": this.incremental_id++});
  }
```
but it throws me the error `Unknown DraftEntity key.` at the line of the `contentState.mergeEntityData()`, because `onAddMention` triggers before the mention is added to the `entityMap`.

UPDATE: The `entityKey` variable value above is the correct value for the mention after it gets added to the `entityMap`. However, the `entityKey` information is lost when using `convertToRaw`. So, maintain an object to map `entityKey` to a mention will be of no use after using `convertToRaw`.

---

Tried doing this:

```javascript
onAddMention = (mention) => {
    mention._root.entries.push(["customId", this.custom_id++]);
  }
```
So that I can manually insert some unique id to each mention before they get added to the `entityMap`.
It does show up in the data of the mention entity in the `contentState`. But it updates all instances of the mention entities.

---

Is there a solution for this problem?

Thanks

**Comment by maniksingh92** [comment]
So I have found a dirty solution for this problem:

```javascript
onAddFunction = (mention) => {
    mention._root.entries.push(["incremental_id", this.incremental_id++]);
  }
```

It does show up in the data of the mention entity in the `contentState`.

Though, I am not sure whether this is the correct way to modify immutable data structures.

**Comment by maniksingh92** [comment]
Figured out another solution,
The `entityKey` provided by `contentState.getLastCreatedEntityKey()` is unique throughout my app, across multiple draftjs instances.

So I am maintaining another object to map my mentions to these `entityKey` values.

```javascript
onAddFunction = (mention) => {
  let contentState = this.state.editorState.getCurrentContent();
  let entityKey = contentState.getLastCreatedEntityKey();
  this.addEntityKeyMentionRelationShip({entityKey: mention});
}
```

And inside my custom `mentionComponent` I do something like this:
```javascript
const customMentionComponent = (props) => {
  return (<div
      onClick={ ()=>{executeSomeFunctionDependentOn(props.entityKey} }>
    {props.children}
  </div>)
};
```

As of now, I will go with this approach, although I would still prefer storing my own `incremental_id` inside the mention data

**Comment by maniksingh92** [comment]
SOLUTION:
This is an ugly solution which modifies the immutable `mention` object. Not sure if this is the right way to go, but it works for me.

```javascript
onAddFunction = (mention) => {
  const uniqueId = Math.random(); // for demonstration purposes, internally i'm using an incremental counter
  mention.uniqueId = uniqueId;
}
```

The key `uniqueId` is preserved in the immutable data of `mention`, even after using `convertToRaw`.
