### ISSUE TITLE
Specify which property of the mention object is used for mention text

### ISSUE THREAD

**Issue by jmbyerly** [draft-js-plugins/draft-js-plugins#832]
I'm using the Mentions plugin and want to specify which property of the mention object is used for the mention text when an item from the suggestions dropdown is selected and a mention entity is created.

Right now, the code that sets the text for the mention entity in the `addMention` function defaults to using the `name` property:

```javascript
`${mentionPrefix}${mention.get('name')}`
```

I'd like the option to add a `mentionTextPropertyName` property to the config object passed to `createMentionPlugin`, and then update that line of the `addMention` function to use that property if it's been passed in, or default to `'name'` otherwise:

```javascript
`${mentionPrefix}${mention.get(mentionTextPropertyName) || mention.get('name')}`
```

Is this something that other people would find useful? If so, I'd be happy to submit a pull request. Otherwise I'll just fork it.

Really enjoying using this library, kudos!

**Comment by thomas88** [comment]
This would also help me. We're having users with a `firstName` and `lastName` property and I'm currently setting a `name` property with `${firstName} ${lastName}` for each mention suggestion.

I think both cases could be handled by allowing to pass in a `mentionText(mention, mentionPrefix)` function that overrides a default function 
```
const defaultMentionText = (mention, mentionPrefix) => `${mentionPrefix}${mention.get('name')}
```
