### ISSUE TITLE
Enable plugin editors to get editorState before Editor renders

### ISSUE THREAD

**Issue by juliankrispel** [draft-js-plugins/draft-js-plugins#834]
Right now any component which needs access to editorState but lives outside the plugin editor needs to be rendered after the PluginEditor so it always has access to the current editorState, this seems a little silly so I'm looking for alternative approaches.

However there may be reasons I don't know about that caused the plugin editor to be designed this way.

Any thoughts anyone?

**Comment by tarjei** [comment]
@nikgraf this seems to me to be an issue wrt to a bug I'm experiencing where the user presses the bold button in a static toolbar but the button does not get marked as bold.

For some reason this bug does not happen in the examples on the page, I don't know why.

**Comment by bjrmatos** [comment]
i just found this behaviour today,

the render of my editor looks like this:

```js
return (
      <div className={styles.contentEditorRoot}>
        <InlineStylesButtons />
        <div className={className} onClick={this.focus}>
          <Editor
            blockStyleFn={getBlockStyle}
            customStyleMap={styleMap}
            editorState={editorState}
            handleKeyCommand={this.handleKeyCommand}
            onChange={this.handleEditorChange}
            onTab={this.handleTab}
            placeholder="Add some content..."
            plugins={plugins}
            ref={this.setEditorRef}
          />
        </div>
      </div>
    )
```

where `InlineStylesButtons` is a component of a plugin (`inlineStylesPlugin.InlineStyleButtons`)

just for the record i had to workaround by passing the last editorState as a prop to `InlineStylesButtons`

final render:

```js
const { editorState } = this.state

return (
      <div className={styles.contentEditorRoot}>
        <InlineStylesButtons editorState={editorState} />
        <div className={className} onClick={this.focus}>
          <Editor
            blockStyleFn={getBlockStyle}
            customStyleMap={styleMap}
            editorState={editorState}
            handleKeyCommand={this.handleKeyCommand}
            onChange={this.handleEditorChange}
            onTab={this.handleTab}
            placeholder="Add some content..."
            plugins={plugins}
            ref={this.setEditorRef}
          />
        </div>
      </div>
    )
```

**Comment by bjrmatos** [comment]
maybe this can be a nice addition to the FAQ, because it is not obvious (and can be a common bug to other people) to find why `getEditorState` returns the previous one in this case.
