### ISSUE TITLE
InlineToolbar/SideToolbar reuse conflict

### ISSUE THREAD

**Issue by grinono** [draft-js-plugins/draft-js-plugins#842]
it's not possible to use the same plugin for multiple plugin Editors.
As can be found in #784 and  [https://github.com/draft-js-plugins/draft-js-plugins/blob/master/FAQ.md#can-i-use-the-same-plugin-for-multiple-plugin-editors](url)

Though i iterate the editors from a datasource array. So creating a new Editor per iteration is not a alternative. 

Is their any other solution to fix having multiple editors on a single page? 
Would be great if the toolbars stay at the location of Editing :-)

**Comment by juliankrispel** [comment]
@grinono you need to instantiate a plugin instance for every editor. It's unfortunate that this isn't obvious and I'm looking for a way to improve the docs to make it more obvious, suggestions welcome.

[Here's a link to the section of the faq that explains this.](https://github.com/draft-js-plugins/draft-js-plugins/blob/master/FAQ.md#can-i-use-the-same-plugin-for-multiple-plugin-editors)

**Comment by grinono** [comment]
I understand that's the case. Tough the number of editors that are on the page is a variable number. Between 1 and 100. I now just show a list of Editors with content in the Editor with readOnly="false"  is then the only option to show the content in HTML for example. And then when clicking Edit a singel Editor instance is loaded.

**Comment by juliankrispel** [comment]
@grinono I'm not sure what the problem is actually is here tbh.

This is probably better talked about over chat rather than a github issue. Feel free to join the [draft-js slack](https://draftjs.herokuapp.com/) I and others would be happy to assist you :+1:
