### ISSUE TITLE
[draft-js-mention-plugin] Dynamically change the theme

### ISSUE THREAD

**Issue by OriR** [draft-js-plugins/draft-js-plugins#845]
Currently I can only pass the `theme` through `createMentionPlugin`, which means that in order to re-theme the mentions I have to invoke `createMentionPlugin` again.
Which I'm doing, but doesn't seem to work, it appears to break the mentions altogether.

The only thing that works is re-mounting (unmount & mount immediately) the editor which feels really hacky.

But, it also makes me think of the bigger scenario here - I can't dynamically create the mention plugin for the editor, which I'm going to need this in the future.
Having the ability to dynamically create different mention plugins (one for every type of prefix trigger), which might change during the life cycle of the component.

**Comment by juliankrispel** [comment]
@OriR what you're trying to achieve should be possible, a few solutions come to mind:

- Rerender the editor and recreate the plugins when your theme changes
- Create nested selectors for the styles you want to adapt and simply change the class of a container component - like `.black-theme .mention { ... }`
