### ISSUE TITLE
Bug: draft-js-emoji-plugin, IE11, and `imagePath`

### ISSUE THREAD

**Issue by icd2k3** [draft-js-plugins/draft-js-plugins#848]
Hey all, thanks for the great work happening here!

I am using the `imagePath` option to point to a directory of emojiOne v. 3.1 svgs like so:

```
createEmojiPlugin({
  imagePath: `${window.location.protocol}//example.com/emojione/`,
}),
```

This looks great on chrome, etc and the emojiOne v3 assets are being displayed correctly in the tooltip menu...

Chrome, Safari, etc:
![emoji-chrome](https://www.dropbox.com/s/avw3ovl3fkp5jvn/Screenshot%202017-08-23%2010.48.55.png?raw=1)

However, in **IE11** the assets are being cut off in the tooltip and, if selected, don't display correctly in the inline text until page refresh...

IE11:
![emoji-ie11](https://www.dropbox.com/s/ddhy5pxtgp6poj6/Screenshot%202017-08-23%2010.49.55.png?raw=1)

Removing the `imagePath` option fixes this problem in IE11, but also means I can not use the emojiOne v. 3 assets that I paid for.

For now, as a workaround, I'll detect if user is on IE and conditionally add the `imagePath` param, but it seems there is a bug here with using it in IE11

draft-js-emoji-plugin: **2.0.0-rc2**
draft-js: **0.10.1**
draft-js-plugins-editor: **2.0.0-rc3**

**Comment by juliankrispel** [comment]
this has been fixed btw :+1:
