### ISSUE TITLE
AnchorPlugin ES6 build error

### ISSUE THREAD

**Issue by aabanaag** [draft-js-plugins/draft-js-plugins#851]
## Description
![image](https://user-images.githubusercontent.com/2245822/29872422-2ac7aef8-8dc2-11e7-8bb6-4d853dd77ac1.png)

(Add images if possible)

## Steps to reproduce
I added a module named draft-js-anchor-plugin which in turn uses url-regex as one of its child module. url-regex is written in ES6(github.com/kevva/url-regex) this has to be transpilled but tried using exclude: /node_modules\/(?!(url-regex))/ but the build error still exist.

(Add link to a demo on https://jsfiddle.net or similar if possible)

# Versions

- React-Boilerplate (see `package.json`): 3.4.0
- Node/NPM:
- Browser:

**Comment by stevewillard** [comment]
I noticed this bug too. If you're using Webpack/Babel, as a work around, you can tell your babel-loader to transpile that library

```
  {
    test: /\.js$/,
    use: ['babel-loader'],
    include: [
      path.resolve(__dirname, 'src'),
      path.resolve(__dirname, 'node_modules', 'url-regex'),
    ],
  },
```

**Comment by aabanaag** [comment]
I think I also tried this, but either way got new error.

```
ERROR in ./app/app.js
Module parse failed: /Users/jongbanaag/Documents/Code/Web/iStack/awc-exhibitor-portal-v2/app/app.js Unexpected token (80:4)
You may need an appropriate loader to handle this file type.
| const render = (messages) => {
|   ReactDOM.render(
|     <Provider store={store}>
|       <LanguageProvider messages={messages}>
|         <Router
 @ multi main
```
initially my loader is something like this

```
test: /\.js$/,
exclude: /node_modules/,
query: options.babelQuery,
```

**Comment by stevewillard** [comment]
That looks like your app code. Instead of using `exclude`, use `include` to include your app code and also `url-regex` which is in the node_modules folder. In my example, my code is under a src directory - it looks like yours is called `app`?

**Comment by aabanaag** [comment]
yes I did changed it to point to app instead or src hence got the error. also removed exclude then inserted the code you posted. I'm using react-boilerplate anyways if it might help narrow the issue.

**Comment by aabanaag** [comment]
Closing this as I managed to fix the issue by simply using uglifyjs-webpack-plugin as this module uses uglify-es which supports ES6.
