### ISSUE TITLE
Emoji plugin seems to have very slow initial load

### ISSUE THREAD

**Issue by tomkis** [draft-js-plugins/draft-js-plugins#855]
Whenever emoji plugin is used, editor boot time is incredibly slow. It takes couple seconds to initialize the emoji.

It might have something to do with:

https://github.com/draft-js-plugins/draft-js-plugins/issues/772

**Comment by sevikon** [comment]
@tomkis yeah, you are right. 
I wasted one day to find out what's the problem with my application. It was totally freezing tab in Google Chrome when it started to load all images. 
I fixed it with this package:
https://github.com/Deveo/emojione-png-sprites
I replaced image and background image with span tag in render method and change a bit css.
And it works like a charm now :) 
I hope it helps you or contributors.

**Comment by romanlex** [comment]
@sevikon can you please add simple how make this with **draft-js-emoji-plugin**

**Comment by jamesfriedal** [comment]
I have also been suffering with the emoji plugin's load time problem. 
@sevikon is there any chance you could share your work?

**Comment by sevikon** [comment]
@romanlex I'm really sorry. I forgot about it and I'm a bit busy recently.
@jamesfriedal  I don't have time right now. I'm working on another project. I will try to share it in the nearest future. 
But I can send you guys zipped directory with plugins. I wrote few others and rewrited a bit some of your plugins like dnd-upload-plugin. I hope it can help.
Plz wrote to me sevikon[at]gmail.com so I will send you files and link to dev version of my project so you can see how it works. 
Best regards!

**Comment by sevikon** [comment]
@romanlex I created fork:
you can check how it works:
https://github.com/sevikon/draft-js-plugins/tree/master/draft-js-emoji-plugin

**Comment by bengotow** [comment]
Hey folks—just ran into this as well. The performance of the EmojiSelectButton is really bad, and it renders the entire emoji selection panel / popover, even when it's closed. (I think this is the source of the problem - there are 1369 emoji, and it spends nearly 80ms rendering them on my machine, only to hide them with CSS)

I think it'd be really easy to fix this - the emoji button shouldn't render the picker subtree unless the picker is visible. Might mean dropping a nice "appear" animation, but it'd be worth it. 

<img width="1462" alt="image" src="https://user-images.githubusercontent.com/1037212/34541648-e37166dc-f08d-11e7-8ae1-0a4c291013ab.png">

**Comment by rustemkk** [comment]
Hello guys, experiencing same problem, any chances that it will be fixed in master soon?

**Comment by grydstedt** [comment]
+1

**Comment by jzaburunov** [comment]
What about not render popup at all, while user not clicks the button ? Did somebody try this?

**Comment by canozgen9** [comment]
Why not just use react-virtualized ? It is very serious performance problem.

**Comment by d3ce1t** [comment]
This continues happening. I have an application where more than one editor are visible on the same page. Load time is very slow, around ~4 seconds. But everything loads pretty fast when I remove the EmojiSelect. Any advice?

**Comment by swkeever** [comment]
I'm also facing this issue. I have no noticeable issues when using `<EmojiSuggestions />` but including `<EmojiSelect />` causes the app to lock up for 5 or so seconds until it loads.

**Comment by adostal** [comment]
> useNativeArt: true

I have better result with use: useNativeArt: true, but still exist slow initial load.
Tested in Chrome/MacOS

**Comment by fxOne** [comment]
@adostal I justed released version 4.3.1 which should fix it. Can you please check it?
