### ISSUE TITLE
Pressing arrow key up/down with mention/emoji plugin should move the cursor

### ISSUE THREAD

**Issue by thomas88** [draft-js-plugins/draft-js-plugins#856]
First of all thank you for the amazing, high quality plugins! Great work 👍 

Currently when pressing arrow key up/down in the mention/emoji plugin examples, the cursor does not move up/down, as you can see in this screen capture:

![mentions](https://user-images.githubusercontent.com/1851359/29960622-b4e730e6-8efc-11e7-893e-c5857010d9c6.gif)

Any hints on what's happening here?

**Comment by leekevinyg** [comment]
@thomas88 were you able to find a workaround for this issue?
