### ISSUE TITLE
Mentions plugin should replace all text between @ and last character of mention

### ISSUE THREAD

**Issue by thomas88** [draft-js-plugins/draft-js-plugins#857]
See this screen capture:
![mentions](https://user-images.githubusercontent.com/1851359/29961998-beccf226-8f01-11e7-88b0-70f630c66b87.gif)

Something seems to be off with the `defaultSuggestionsFilter`, as it probably shouldn't return any suggestions for " i i i i i".

And then the plugin should replace all the text, starting with the @ character to the last character of the mention.

I haven't dug into the internals of the plugin yet, but it seems to me that these two issues might be related.

**Comment by dovydaskukalis** [comment]
Plugin seems to work much better if I comment out [this line](https://github.com/draft-js-plugins/draft-js-plugins/blob/e5ad5da34b6c23e0178d33edc8a1c752398aaab5/draft-js-mention-plugin/src/MentionSuggestions/index.js#L45)
