### ISSUE TITLE
DraftJS Emoji Plugin - Bundle Size

### ISSUE THREAD

**Issue by hamed-farag** [draft-js-plugins/draft-js-plugins#859]
i am using draft emoji plugin, my webpack package analyzer show me that there is a huge package on my bundle 
![image](https://user-images.githubusercontent.com/5382471/29994808-26ca4b6c-8fd9-11e7-9710-677462d930fe.png)

is there any way to reduce bundle size

**Comment by jamesfriedal** [comment]
Hi Hamed, did you ever resolve this?

**Comment by iansinnott** [comment]
Since emojione is one big JS blob your best bet is probably to use [dynamic imports](https://webpack.js.org/guides/code-splitting/#dynamic-imports) so that the user only ever has to request emojione if they actually use your editor component. That way you don't bloat your main bundle.

**Comment by felippepuhle** [comment]
Can we re-open this issue? We're still having a large bundle due to the emoji plugin, and it increased 300kb after migrating to the v4.

**Comment by fxOne** [comment]
The issue should be the list of emojis [`emojibase-data/en/compact.json`](https://github.com/draft-js-plugins/draft-js-plugins/blob/c72e529dac1f6184c80e3310ca84ca6186d8d20f/packages/emoji/src/utils/createEmojisFromStrategy.ts#L2). I already changed to `emojibase-data` as it was smaller than the one from `emoji-toolkit`. Do you have any idea?

**Comment by felippepuhle** [comment]
I'm trying to identify @fxOne, I found this https://bundlephobia.com/result?p=@draft-js-plugins/emoji@4.0.1 but I don't think it's correct (537kb from react-icons)...

**Comment by felippepuhle** [comment]
@fxOne I tried a couple of things but it didn't help, is there a way we can replace `emoji-toolkit`? it doesn't seem to support tree shaking so we're importing the whole library (about 388kb)

**Comment by fxOne** [comment]
@felippepuhle I have marked all plugins as `"sideEffects": false` to enable tree shaking. Can you please check if it resolves in a smaller build?

**Comment by felippepuhle** [comment]
@fxOne it seems to help a lot, thanks!

### before

```
File sizes after gzip:

  598.27 KB  build/static/js/vendor.dac4bd2d.js
  173.4 KB     build/static/js/main.eeae9237.js
  121.81 KB    build/static/css/vendor.f5b73b64.css
  15.31 KB      build/static/css/main.9f1398d2.css
  771 B           build/static/js/manifest.fd6741f5.js
```
<img width="1680" alt="Screen Shot 2021-01-25 at 2 58 48 PM" src="https://user-images.githubusercontent.com/15961929/105746177-e2e0b680-5f1d-11eb-90a7-c003cae201cb.png">


### after

```
File sizes after gzip:

  552.07 KB  build/static/js/vendor.658aaf44.js
  173.4 KB     build/static/js/main.e459fc5d.js
  121.81 KB    build/static/css/vendor.f5b73b64.css
  15.31 KB      build/static/css/main.9f1398d2.css
  771 B           build/static/js/manifest.fd6741f5.js
 ```
 
 
<img width="1680" alt="Screen Shot 2021-01-25 at 2 58 12 PM" src="https://user-images.githubusercontent.com/15961929/105746206-ea07c480-5f1d-11eb-8a23-83d0fc1c0572.png">

-----------

I think that `no-source` is probably the `emojibase-data` JSON

**Comment by qw110946** [comment]
same issue

**Comment by d-ivashchuk** [comment]
Still huge bundle sizes for me, tried to use dynamic imports but still erroneous:

```
  const {
    plugins,
    MentionSuggestions,
    EmojiSuggestions,
    EmojiSelect,
  } = useMemo(() => {
    import('@draft-js-plugins/emoji').then((createEmojiPlugin) => {
      let defaultTheme = createEmojiPlugin.defaultTheme;
      defaultTheme.emojiSuggestions =
        defaultTheme.emojiSuggestions + ' emoji-picker';
      mentionsDefaultTheme.mentionSuggestions =
        mentionsDefaultTheme.mentionSuggestions + ' mentions-suggestions';

      const emojiPlugin = createEmojiPlugin.default({
        useNativeArt: true,
        theme: defaultTheme,
      });
      const resizeablePlugin = createResizeablePlugin();
      const mentionPlugin = createMentionPlugin();
      const { EmojiSuggestions, EmojiSelect } = emojiPlugin;
      const { MentionSuggestions } = mentionPlugin;
      const plugins = [emojiPlugin, mentionPlugin, resizeablePlugin];
      return { plugins, MentionSuggestions, EmojiSuggestions, EmojiSelect };
    });
  }, []);
```

`Cannot destructure property 'plugins' of 'Object(...)(...)' as it is undefined.`

**Comment by yashSangai** [comment]
I am facing a similar kind of issue, tried multiple things but hard luck.
@d-ivashchuk Were you able to resolve it?

**Comment by bharathgedela204** [comment]
can be fixed doing import like this 
`import createEmojiPlugin, { defaultTheme } from `'@draft-js-plugins/emoji';
`

**Comment by bharathgedela204** [comment]
Making import as below bring down the parsed size to 34kb types 
**import createEmojiPlugin from '@draft-js-plugins/emoji';**
<img width="1728" alt="Screenshot 2022-11-18 at 9 33 36 PM" src="https://user-images.githubusercontent.com/97687863/202748608-a1d3a21e-130a-4067-8ed1-65750ca368ea.png">
