### ISSUE TITLE
Use Emoji-Mart in emoji-plugin

### ISSUE THREAD

**Issue by dimaslz** [draft-js-plugins/draft-js-plugins#860]
Hi team!

I need to use the https://github.com/missive/emoji-mart component like emoji render in draft-js-emoji-plugin, In fact I doing the modification to solve that. To release, if I do a PR, is a good point to have in draft-js-plugins or is better to do a 3rd party package directly on npm?

Thanks!! 

cc: @nikgraf

**Comment by juliankrispel** [comment]
this is actually kind of a cool idea because then we wouldn't have to maintain this ourselves, what do you think @nikgraf

**Comment by juliankrispel** [comment]
@dimaslz I'll reach out to nik and will get back to you on that, definitely like the idea!

**Comment by dimaslz** [comment]
@juliankrispel @nikgraf ok, perfect. I will do the PR soon. I did a plugin in local in a project, but I will work in the proper plugin inside draft-js-plugin.

In fact, in this plugin I will use the last version of emojione because emoji-mart is using it.

So, a quick question. Do you want that I do the new parameters inside draft-js-emoji-plugin to use this component or create a new one like draft-js-emoji-mart-plugin? What do you think?

**Comment by juliankrispel** [comment]
I would refactor the emoji plugin. Fel free to reach out to me on the draft js slack if u want to talk more about the how ✌️

**Comment by juliankrispel** [comment]
@dimaslz just talked to @nikgraf. Would be great to refactor the plugin to use emoji mart. 

Do you want to go ahead? Feel free to reach out to me on slack about it!

**Comment by juliankrispel** [comment]
@dimaslz how are you doing with that? If I don't hear from you soon I might attack this myself <3

**Comment by dimaslz** [comment]
Hi!, I had a busy week. I have something done. Let me this week to try finish. I will join the Slack channel and we talk soon ;)

**Comment by jamesfriedal** [comment]
Does this mean there might be an updated emoji plugin released !!!!!

I Appreciate the work on Draft.JS plugins. As they have completed saved my project.

**Comment by juliankrispel** [comment]
@dimaslz feel free to open a pr for a review @jamesfriedal oh yea we're updating stuff all the times!

**Comment by jamesfriedal** [comment]
aweosme, sounds great Julian. When i get a bit better at coding, I hope to contribute.

**Comment by MichalPodeszwa** [comment]
Would this plugin also have the emoticons?

**Comment by gavrichards** [comment]
Any update on this? Would love this for our project we're building at the moment.

**Comment by santryn** [comment]
Would also love to know if there is any update on this. Currently reworking a textbox that already uses emoji mart to utilise DraftJS- this would be a big problem solver for us!

**Comment by gavrichards** [comment]
@juliankrispel @dimaslz Hey guys, I'd really like to use this in my project as the existing emoji plugin doesn't suit our needs - A) we'd like to use Twitter's emoji pack B) resolve the issue with the slow loading #855 . Do you have anything you can share, even if it's a zip? It would be so much appreciated, I've been struggling with this since November and our new product is preparing for launch now, so we'd like to have this in place. Thanks

**Comment by joshfarrant** [comment]
@juliankrispel @dimaslz Any updates/timeframes?

**Comment by gavrichards** [comment]
I gave up and ended up taking the time to modify the existing emoji plugin to meet my needs, including Emoji Mart and using Twemoji to avoid licencing issues.

As a courtesy to the few folk here who are struggling like me, I'm providing my code - I hope it helps you out. Please don't ask me to do a PR and contribute this back to the project - I've got no incentive at all after the complete lack of any helpful response here or in the Slack group, sorry!

To use my code you'll need to import it like you would the regular emoji plugin:

```
import emojiPlugin from './emoji-plugin';

const emojiPluginInst = emojiPlugin();
const { EmojiSelect } = emojiPluginInst;
```

```
<EmojiSelect
  selectedEmoji={() => {
    // If you're showing the component inside a flyout container or something, you might want to hide it when an emoji is selected, e.g...
    this.emojiFlyout.instanceRef.hide();
  }}
/>
```

You'll need to install these packages:
- twemoji
- emoji-mart
- find-with-regex
- decorate-component-with-props

Good luck friends! :)

[emoji-plugin.zip](https://github.com/draft-js-plugins/draft-js-plugins/files/1682288/emoji-plugin.zip)

**Comment by GotSteez** [comment]
Is there any update on this? I am using the above zip from @gavrichards with a few modifications and it's worked well but I'd rather have this as an external library rather than as a part of the application. The above zip also lacks suggestions which would be good to keep when the original emoji plugin gets refactored.

**Comment by dimaslz** [comment]
Sorry!Sorry!Sorry!Sorry!Sorry!Sorry!  guys, I had some problems and I was lose and very focus in other projects and in my new Job. 

I talked with @gavrichards  and he is free to do the PR. I can help on in, but I will try this weekend if I can to finish it.

Thanks very much in advance.!

**Comment by aklishchevskiy** [comment]
@dimaslz @gavrichards, any updates on this topic?

**Comment by eriffat896** [comment]
> I gave up and ended up taking the time to modify the existing emoji plugin to meet my needs, including Emoji Mart and using Twemoji to avoid licencing issues.
> 
> As a courtesy to the few folk here who are struggling like me, I'm sharing my code solution in the attached zip.
> 
> To use my code you'll need to import it like you would the regular emoji plugin:
> 
> ```
> import emojiPlugin from './emoji-plugin';
> 
> const emojiPluginInst = emojiPlugin();
> const { EmojiSelect } = emojiPluginInst;
> ```
> ```
> <EmojiSelect
>   selectedEmoji={() => {
>     // If you're showing the component inside a flyout container or something, you might want to hide it when an emoji is selected, e.g...
>     this.emojiFlyout.instanceRef.hide();
>   }}
> />
> ```
> You'll need to install these packages:
> 
> * twemoji
> * emoji-mart
> * find-with-regex
> * decorate-component-with-props
> 
> Good luck friends! :)
> 
> [emoji-plugin.zip](https://github.com/draft-js-plugins/draft-js-plugins/files/1682288/emoji-plugin.zip)

Hello, @gavrichards, 
Can you explain it more? like how you apply it after installing the above packages.

**Comment by antonazgarovich** [comment]
Is there a chance that an emoji mart plugin will be added?

**Comment by fxOne** [comment]
`Emoji-Mart` uses as licence BSD-3 while `@draft-js-plugins` uses MIT. As far as I can see these 2 licence are not compatible.
