### ISSUE TITLE
Could the Hashtag plugin be adopted for other characters? 

### ISSUE THREAD

**Issue by jamesfriedal** [draft-js-plugins/draft-js-plugins#863]
Hastag plugin is cracking. 

I also want to style the text to be blue after the '@' key is pressed as well as the #key. 
Just like  _#cool_ comes out as blue I would also like _@cool_ to come out as blue.

Perhaps this may work in a similar way to reimertz's implementation in this pull request #854 
Massive thanks for any help.

**Comment by juliankrispel** [comment]
@jamesfriedal fair proposal!

**Comment by juliankrispel** [comment]
@jamesfriedal fancy opening a pr with such a change?

**Comment by jamesfriedal** [comment]
am i right in thinking a PR would require me to actually write the code? 
because unfortunately that would be beyond my ability. apologies
