### ISSUE TITLE
No compatible version found: draft-js-plugins-editor@2.0.0-rc6

### ISSUE THREAD

**Issue by williamli** [draft-js-plugins/draft-js-plugins#867]
`npm install draft-js-plugins-editor@2.0.0-rc6 --save`

No compatible version found: draft-js-plugins-editor@2.0.0-rc6

Valid install targets:
0.0.0, 0.1.0, 0.2.0, 1.0.0-beta1, 1.0.0, 1.0.1, 1.1.0, 2.0.0-beta1, 2.0.0-beta.2, 2.0.0-beta.4, 2.0.0-beta5, 2.0.0-beta6, 2.0.0-beta7, 2.0.0-beta8, 2.0.0-beta9, 2.0.0-beta10, 2.0.0-beta11, 2.0.0-rc1, 2.0.0-rc2, 2.0.0-rc3, 2.0.0-rc4, 2.0.0-rc5

use the following instead will install 2.0.0-rc5

`npm install draft-js-plugins-editor@beta --save`

**Comment by juliankrispel** [comment]
@williamli whoops, try rc-7 :)

**Comment by williamli** [comment]
@juliankrispel will `@beta` automatically maps to rc-7?
