### ISSUE TITLE
[draft-js-linkify-plugin] - Parameter component not working

### ISSUE THREAD

**Issue by davidsonsns** [draft-js-plugins/draft-js-plugins#875]
Parameter `component` not working in Linkify Plugin
In node_modules this is so

```js
var linkPlugin = function linkPlugin() {
  var config = arguments.length <= 0 || arguments[0] === undefined ? {} : arguments[0];

  // Styles are overwritten instead of merged as merging causes a lot of confusion.
  //
  // Why? Because when merging a developer needs to know all of the underlying
  // styles which needs a deep dive into the code. Merging also makes it prone to
  // errors when upgrading as basically every styling change would become a major
  // breaking change. 1px of an increased padding can break a whole layout.
  var theme = config.theme ? config.theme : defaultTheme;
  var target = config.target ? config.target : '_self';
  return {
    decorators: [{
      strategy: _linkStrategy2.default,
      component: (0, _decorateComponentWithProps2.default)(_Link2.default, { theme: theme, target: target })
    }]
  };
};
```

**Comment by thomas88** [comment]
Which version of the plugin are you using? The `component` prop is only available in version 2 upwards (still in beta/rc). See also https://github.com/draft-js-plugins/draft-js-plugins/blob/master/draft-js-linkify-plugin/CHANGELOG.md

**Comment by davidsonsns** [comment]
I'm using the version 2.0.0-beta1, tks

**Comment by juliankrispel** [comment]
@davidsonsns please provide a [codesandbox](codesandbox.io) so we can reproduce and help you

**Comment by davidsonsns** [comment]
I created this project [https://codesandbox.io/s/pyoy0on510](https://codesandbox.io/s/pyoy0on510)

if it is really a bug, I will try to collaborate with the repo, tks

**Comment by juliankrispel** [comment]
@davidsonsns apparently with that version it doesn't work :/ - try `draft-js-linkify-plugin@2.0.0-rc8`

It seems to work in this [forked code sandbox](https://codesandbox.io/s/6zmql4qrmz) with the updated dependency, so I'm closing this issue
