### ISSUE TITLE
create-react-app

### ISSUE THREAD

**Issue by aanchalgera** [draft-js-plugins/draft-js-plugins#879]
The anchor plugin is not working with create-react-app because of the dependency on url-regex as url-regex compiles in es6.

**Comment by juliankrispel** [comment]
@aanchalgera thx I opened a pr here - https://github.com/kevva/url-regex/pull/45 to fix the issue. If I don't get a reply soon from the project owner we'll just copy the module

**Comment by aanchalgera** [comment]
Thank you @juliankrispel for taking up the issue. I am still facing the same issue with ip-regex :(
