### ISSUE TITLE
Mention Plugin - Problem with mentionTrigger

### ISSUE THREAD

**Issue by agarrharr** [draft-js-plugins/draft-js-plugins#881]
When I make the `mentionTrigger` a parenthesis `(` or bracket `[`, like this:

```js
const mentionPlugin = createMentionPlugin({
  mentionTrigger: '(',
});
```

I get this error:

```
Uncaught SyntaxError: Invalid regular expression: /(/: Unterminated group
    at RegExp (<anonymous>)
```

This only happens if the first thing that I type into the editor is `(`. If I type some other characters first, it works fine.

Is there a way to achieve the same thing with `mentionRegExp`?

**Comment by agarrharr** [comment]
This only happens if the first thing that I type into the editor is `(`. If I type some other characters first, it works fine.

**Comment by juliankrispel** [comment]
that should be an easy fix, I'm guessing this is about escaping `(`

**Comment by juliankrispel** [comment]
@agarrharr just opened a pr as fix!

**Comment by agarrharr** [comment]
I'm not sure if this fixed it. This is what I'm seeing now.

![bug](https://user-images.githubusercontent.com/3266363/30887178-7450042e-a2d7-11e7-9553-6a0cfb285a56.gif)

**Comment by juliankrispel** [comment]
@agarrharr ugh - fixed now, that plugin really needs a rewrite and some tests!

The fix will be live shortly as `draft-js-mention-plugin@2.0.0-rc10`

**Comment by agarrharr** [comment]
It works great now!
