### ISSUE TITLE
draft-js-plugin-buttons: Support sub and sup buttons + custom button

### ISSUE THREAD

**Issue by tarjei** [draft-js-plugins/draft-js-plugins#882]
Hi, it would be great if `draft-js-buttons` could have support for sub and sup buttons. Also, it would be nice if there was a function to create custom buttons where one could extend the click event to handle external stuff like file uploads etc.

This is the code I use today to get sub/sup:
```js
import React from 'react'

import createInlineStyleButton from 'draft-js-buttons/lib/utils/createInlineStyleButton'

export default createInlineStyleButton({
  style: 'SUBSCRIPT',
  children: (
    <div className="SubButton-button ToolbarButton-button">
      x<sub>2</sub>
    </div>
  )
})
import React from 'react'

import createInlineStyleButton from 'draft-js-buttons/lib/utils/createInlineStyleButton'

export default createInlineStyleButton({
  style: 'SUPERSCRIPT',
  children: (
    <div className="SupButton-button ToolbarButton-button">
      x<sup>2</sup>
    </div>
  )
})

```

And also in the editor customStyleFn: 
```js
<Editor  ....
              customStyleMap={ {
                SUBSCRIPT: { fontSize: '0.6em', verticalAlign: 'sub' },
                SUPERSCRIPT: { fontSize: '0.6em', verticalAlign: 'super' }
              }} />
```

**Comment by juliankrispel** [comment]
@tarjei wanna make a pr to add those buttons? Would be happy to merge that in :+1:

**Comment by tarjei** [comment]
Np. can you provide icons? Also, which font is used for the icons?

**Comment by juliankrispel** [comment]
@tarjei if you look at draft-js-buttons, they're all svgs I believe...

**Comment by juliankrispel** [comment]
@tarjei example: https://github.com/draft-js-plugins/draft-js-plugins/blob/master/draft-js-buttons/src/components/BlockquoteButton/index.js
