### ISSUE TITLE
draft-js-image-plugin: adding image on blank line adds ContentBlock above & below

### ISSUE THREAD

**Issue by trevtrich** [draft-js-plugins/draft-js-plugins#883]
When using `addImage` with the cursor position on an empty line, the resulting state is three ContentBlocks: 1) empty block, 2) block containing image entity, 3) another empty block. The creation of the empty blocks seems like a side-effect.

If I use `addImage` in the middle of a block of text, I also get three blocks, but all are three have content: 1) block with text before the cursor, 2) block containing image entity, 3) block with text after the cursor. That is, no empty blocks are created. This seems correct.

**Desired state**: using `addImage` in an empty block just replaces that block rather than splitting it into three blocks.

I'm not sure whether this is a draft issue or an image-plugin issue, but hopefully this can get the conversation started.

**Comment by juliankrispel** [comment]
@richardson-trevor which addImage method are you regarding?

**Comment by richardson-trevor** [comment]
It's the reference accessible by:
```JS
const imagePlugin = createImagePlugin();
const THIS_ONE = imagePlugin.addImage
```
I believe the reference in the image plugin api is [on this line](https://github.com/draft-js-plugins/draft-js-plugins/blob/master/draft-js-image-plugin/src/index.js#L35).

**Comment by MykolaGolubyev** [comment]
Not sure if it is related, but if my content starts with an image, then there is an empty line in front of it which I can't delete without deleting the image.

**Comment by juliankrispel** [comment]
I shall have a peek!
