### ISSUE TITLE
Pressing enter on a focussed image

### ISSUE THREAD

**Issue by mxstbr** [draft-js-plugins/draft-js-plugins#885]
When I press ENTER on a focussed image the newline is inserted before the image. (right now it crashes entirely, replicate-able after merging #880 on the website) This makes it impossible to add more text after an image that's at the end of the content.

Recording of the issue: 
![enter-image 1](https://user-images.githubusercontent.com/7525670/30654324-d1550178-9e2d-11e7-9a37-6e4b9a2b0566.gif)

**Comment by juliankrispel** [comment]
@mxstbr wanna submit a pr for this? I'm assuming you guys found a workaround?

**Comment by mxstbr** [comment]
Nope, no fix yet, otherwise you'd long have a PR :wink:

**Comment by kalimantos** [comment]
I found a rough solution but for now is the only one i found

**Comment by juliankrispel** [comment]
@kalimantos thanks man! I looked and reviewed/tested

**Comment by juliankrispel** [comment]
@mxstbr released a fix for this just now - draft-js-focus-plugin@2.0.0-rc9

**Comment by mxstbr** [comment]
Yesss, awesome! Thanks @kalimantos and @juliankrispel!

**Comment by kalimantos** [comment]
sadly i found an issue about that fix! when we use `replaceWithFragment` in https://github.com/draft-js-plugins/draft-js-plugins/pull/890/files#diff-597e058aa9b8b23d0ecfdff3859807d7R30 draft-js writes inside the empty unstyled block a whitespace and links the above entity to them. I think this should not happen. I can make a new pull request to fix this

**Comment by juliankrispel** [comment]
@kalimantos this is fixed, please see above
