### ISSUE TITLE
emoji-plugin useNativeArt breaks deleting emojis

### ISSUE THREAD

**Issue by stevewillard** [draft-js-plugins/draft-js-plugins#886]
If we create an emoji-plugin with the `useNativeArt` option, you can't delete emojis after you have created them. To reproduce:

```
const emojiPlugin = createEmojiPlugin({
    useNativeArt: true
});
```

1. Add an emoji to your editor
2. Delete (the cursor jumps to the beginning of the line)

**Comment by juliankrispel** [comment]
oh crap, I'll look at it soon o_O

**Comment by juliankrispel** [comment]
this makes me so sad :(

**Comment by stevewillard** [comment]
Haha, why? I can try to take a look at this later in the week. I was trying to dig into how `useNativeArt` worked, because I was curious if I could exclude `emojione` entirely to reduce the size of this plugin.

**Comment by juliankrispel** [comment]
@stevewillard I'm exaggerating :-)

**Comment by juliankrispel** [comment]
looking at it right now actually

**Comment by juliankrispel** [comment]
@stevewillard fixed - https://github.com/draft-js-plugins/draft-js-plugins/pull/893
