### ISSUE TITLE
drawing plugin

### ISSUE THREAD

**Issue by ChuckIrvine** [draft-js-plugins/draft-js-plugins#889]
Is there a plugin what would allow draftjs users to embed drawings in documents? On subsequent edits, the user would be able to edit the embedded drawing. Thanks

**Comment by juliankrispel** [comment]
There's a plugin for uploading images in the works - https://github.com/draft-js-plugins/draft-js-plugins/pull/733

**Comment by ChuckIrvine** [comment]
I don't think uploading images works does it? If I upload an image, will I be able to click on it and edit in place?

**Comment by nikgraf** [comment]
@ChuckIrvine you won't be able to manipulate the image. If you want to do that it needs a plugin using canvas or svg. I'm not aware of any plugin out there having support for that.

**Comment by ChuckIrvine** [comment]
That’s what I suspected. I think it would have been better to keep my issue open. What I suggested would be very useful I think.
