### ISSUE TITLE
Mention can only get triggered once each line after recent updates

### ISSUE THREAD

**Issue by aarryy** [draft-js-plugins/draft-js-plugins#895]
Noticed the issue after I updated draft-js-mention-plugin to 2.0.0-rc8 recently. Not sure if this is the desired behavior but I didn't have this issue with my previous installation 2.0.0-rc2. It can be replicated on the [demo page](https://www.draft-js-plugins.com/plugin/mention) too. I wonder if it has anything to do with #865. I did change my suggestions from immutable list to pure array.

**Comment by juliankrispel** [comment]
that bug is fixed now btw :) - please install the latest

**Comment by zigoo** [comment]
My problem is kind of similar - when nesting  mentions inside another component, I can only trigger one Mention per line..

I did install the latest version, tried different versions of dependencies/react etc.. and nothing seem to work :| 
I even copied this (https://codesandbox.io/s/rj2ymv4l7n) into my app and mentions still behave same way.. What could possibly influence this behaviour?
