### ISSUE TITLE
[RFC] Compound components

### ISSUE THREAD

**Issue by mxstbr** [draft-js-plugins/draft-js-plugins#897]
The default plugins are not as customizable as I would like them to be, mainly due to doing too many things.

Take the side toolbar plugin as an example. You use it like this:

```JS
import createSideToolbarPlugin from 'draft-js-side-toolbar-plugin';

const plugin = createSideToolbarPlugin();
const { SideToolbar } = plugin;

<Editor plugins={[plugin]} />
<SideToolbar />
```

Now this magic `SideToolbar` component does a bunch of _stuff_. It handles the position of the sidebar, it's styled, it renders the buttons.

On top of that, to change the buttons that are rendered I have to provide a `structure` option:

```JS
createSideToolbarPlugin({
  // wat
  structure: [Button1, Button2]
})
```

To change the styling, a `theme` option:

```JS
createSideToolbarPlugin({
  theme: { /* wait what do I put here now ugh some random keywords I gotta figure out */ }
})
```

Really, in a real-world use case **the only thing I want from the `<SideToolbar />` is the position**. That's all I need! Ryan Florence recently popularized the concept of compound components, and I think they could be very very powerful here.

This is what I imagine the API for the side toolbar plugin to look like when using the compound components concept:

```JS
import createSideToolbarPlugin from 'draft-js-side-toolbar-plugin';

// This is all the same, minus the options passed to the createSideToolbarPlugin call
const plugin = createSideToolbarPlugin();
const { SideToolbar } = plugin;
<Editor plugins={[plugin]} />

// This is were the magic happens
<SideToolbar>
  // Function as a child, style is just the positioning on the side
  // e.g. style = { top: '262px', left: '539px' }
  {({ style, setEditorState, getEditorState }) => (
    <div style={style}>
      {/* Now I'm free to render whatever the fuck I want inside my toolbar! */}
      <Button1 setEditorState={setEditorState} getEditorState={getEditorState} />
      <Button2 setEditorState={setEditorState} getEditorState={getEditorState} />
      <Heading1>Hello Iam a heading because why the fuck not this is my sidebar now</Heading1>
    </div>
  )}
</SideToolbar>
```

This could then still be enhanced were you'd have a second plugin with some standard buttons that users can render if they're too bored to create their own ones.

There's a couple of fine discussion points here (e.g. function as a child vs. render prop), but overall this kind of API would make the plugin a lot more focussed on a single purpose (position the sidebar and change the editor state from it) and thusly a lot more useful!

**Comment by juliankrispel** [comment]
@mxstbr really love this! Would be awesome to have a conversation with you @mxstbr and @nikgraf on slack <3

**Comment by juliankrispel** [comment]
I've opened a [paper doc](https://paper.dropbox.com/doc/Architecture-changes-3.0-dLkTLrMlDq53VjvesyyxH?_tk=share_copylink) for further discussion, anyone with the link can comment/share the doc...

**Comment by tarjei** [comment]
#834 should be closed as a duplicate of this issue.

**Comment by juliankrispel** [comment]
@tarjei why?

**Comment by tarjei** [comment]
@juliankrispel It seems to me that the best solution to #834 will be implementing Draft-JS-plugins as a compound component instead of a HOC as today. I might be wrong.
