### ISSUE TITLE
Image resize plugin onChange is not fired

### ISSUE THREAD

**Issue by MykolaGolubyev** [draft-js-plugins/draft-js-plugins#898]
## Use-case/Problem

I use  `draft-js-resizeable-plugin` plugin. My system reacts on real time changes inside DraftJS editor. 
Need to react on size change of an image.

```
createResizeablePlugin({onChange: (args) => {
            console.log('image change', args)
        }});
```
That didn't produce any console output. 
I checked the source and didn't find ant mention of `onChange`.

Not sure if I am using it wrong or misunderstood the docs.
Let me know if this is something on a roadmap and if I could help.

**Comment by Hongbo-Miao** [comment]
Have same question, not sure where it hold the image size states.

**Comment by juliankrispel** [comment]
@MykolaGolubyev @Hongbo-Miao the size is held in the entity metadata, [see here](https://github.com/draft-js-plugins/draft-js-plugins/blob/master/draft-js-image-plugin/src/modifiers/addImage.js#L9)

you can't pass an `onChange` handler to the plugin creator, however the editors `onChange` callback should be fired when you resize an image

**Comment by juliankrispel** [comment]
above I linked an example of how an image and it's entity gets added, here's how the resize plugin [modifies that entity](https://github.com/draft-js-plugins/draft-js-plugins/blob/master/draft-js-image-plugin/src/modifiers/addImage.js#L9)
