### ISSUE TITLE
plugins not working if called refs.editor.focus() in componentDidMount

### ISSUE THREAD

**Issue by baoziv587** [draft-js-plugins/draft-js-plugins#900]
# Minimal reproduce
![image](https://user-images.githubusercontent.com/7347513/31021367-414cdb44-a4fb-11e7-80e1-df0cafd8ae7c.png)

https://codesandbox.io/s/r743k3022q

**Comment by pfftdammitchris** [comment]
Hmm that is odd. Will try to work around a fix for this

**Comment by asokani** [comment]
this issue is a duplicate of #800

**Comment by jrock17** [comment]
I also lost 3 life hours on this one. Fixed it with setTimeout, although it feels a bit hacky. Oh well, time for a beer.

```
  componentDidMount() {
    this.focusTextInput();
  }

  focusTextInput = () => {
    // Focuses editor window on a slight delay to fix emoji & mentions loading bug
    setTimeout(() => { this.editorWindow.current.focus(); }, 10);
  };
```

Should be fixed properly inside the plugins at some point.
