### ISSUE TITLE
Mention plugin only pops up when '@' is the first character in a line after updating

### ISSUE THREAD

**Issue by iEchoic** [draft-js-plugins/draft-js-plugins#901]
Hello,

I'm using draft-mention-plugin in production, and after updating to Draft 0.10 and mentions plugin 2.0.0-rc9, I'm finding that the suggestions only pop-down if the '@' character is the *first* character in any row. So:

`@name` works, but

`hi @name` will not pop the suggestions component.

I've been debugging through the code and am at a loss as to why this is happening. It appears that on editor state change, the function in `MentionSuggestions` component that determines if it should be shown is returning early because there are no search portals, so it's not looking at the raw content and looking for content that ends with a `@`.

Any idea where to look here? Thank you.

**Comment by iEchoic** [comment]
I just downgraded to rc8 and it seemed to have fixed the issue. Possible issue in rc9?

**Comment by juliankrispel** [comment]
@iEchoic rc8 has other issues, did you try rc10?

**Comment by thenanyu** [comment]
I just repro'd in rc10

**Comment by juliankrispel** [comment]
Can you provide a codesandbox please?

**Comment by jgrisafe** [comment]
+1 on this issue, we will have to lock our app at rc8 until this is fixed.

**Comment by juliankrispel** [comment]
@jgrisafe @thenanyu @iEchoic I have tested this with `draft-js-mention-plugin@2.0.0-rc10` and can't reproduce the error, here's [some proof](https://codesandbox.io/s/rj2ymv4l7n) - You can inspect the version number in the sandbox! Please let me know if you can still reproduce it and provide proof and I'll happily reopen this again <3

**Comment by diegohaz** [comment]
I'm also having this problem (with rc10). Trying to investigate it, but without success so far.
