### ISSUE TITLE
React v16 Support

### ISSUE THREAD

**Issue by alexlatchford** [draft-js-plugins/draft-js-plugins#906]
## Use-case/Problem

Looks like there are a couple of uses of deprecated features that have now been removed, ie. `React.PropTypes` -> `prop-types` module.

We migrated our app pretty quickly to get the speed boost it comes with and didn't have too many hiccups.

**Comment by stevewillard** [comment]
React 16 is already supported. Do you see any issues after upgrading?

**Comment by alexlatchford** [comment]
Hi @stevewillard apologies for the delay.

I'm using: `"draft-js-plugins-editor": "^2.0.0-beta1",`. Here's the problem:

![screencapture-local-hugoai-3001-1507235571007](https://user-images.githubusercontent.com/628146/31251096-b4417274-a9d1-11e7-85cc-a3bb7450aa6f.png)

```
TypeError: Cannot read property 'object' of undefined
./node_modules/draft-js-plugins-editor/lib/Editor/index.js
node_modules/draft-js-plugins-editor/lib/Editor/index.js:177
  174 | }(_react.Component);
  175 | 
  176 | PluginEditor.propTypes = {
> 177 |   editorState: _react2.default.PropTypes.object.isRequired,
  178 |   onChange: _react2.default.PropTypes.func.isRequired,
  179 |   plugins: _react2.default.PropTypes.array,
  180 |   defaultKeyBindings: _react2.default.PropTypes.bool,
```

**Comment by alexlatchford** [comment]
Haha, I just checked I'm on the latest version and looks like there is a `draft-js-plugins-editor@2.0.0-rc8` out! That works with React v16 it looks like.

Closing, apologies...
