### ISSUE TITLE
Linkify underline problem

### ISSUE THREAD

**Issue by ArthurStam** [draft-js-plugins/draft-js-plugins#910]
I am trying to use draft-js-linkify-plugin and I have a problems with underlining of whole text after pasting link. I think, this is bug, because after link paste I would to continue writing normal text, but I can't, because it's underlined) 
![screen shot 2017-10-09 at 19 04 28](https://user-images.githubusercontent.com/5061840/31349755-d30d61d0-ad24-11e7-92b6-d236e47a4344.png)

**Comment by freedomlang** [comment]
@ArthurStam can not reproduce on the latest version, please upgrade to latest version and have a try
