### ISSUE TITLE
mention plugin npm published version is old and out of sync with documentation

### ISSUE THREAD

**Issue by andpor** [draft-js-plugins/draft-js-plugins#911]
Please publish new version of mention plugin. npm version is dated, completely out of sync with current documentation and buggy. 

I would like to use the latest codebase but cannot get it is distributed flavor.

**Comment by jrock17** [comment]
Just run this to get the latest version:
`npm install draft-js-mention-plugin@2.0.0-rc8 --save`

**Comment by simsim0709** [comment]
Hello, @andpor 

Did you update the latest version?

It seems like it's resolved. I will close this.
