### ISSUE TITLE
draft-js-image-plugin adds image caption

### ISSUE THREAD

**Issue by janjon** [draft-js-plugins/draft-js-plugins#912]
`blockRendererFn
`
Adds the input input box in ThemedImage, but regardless of how can't select, but [http://lastdraft.xyz/](url) the mentality also added input to update data to implement. It indeed may select

Thanks your response

**Comment by janjon** [comment]
input need setReadOnly Can use, Has looked for a long time

**Comment by freedomlang** [comment]
@janjon what do you mean?
