### ISSUE TITLE
Webpack dependency doubled on package.json

### ISSUE THREAD

**Issue by Kornil** [draft-js-plugins/draft-js-plugins#913]
https://github.com/draft-js-plugins/draft-js-plugins/commit/1f71cf2c68970118ae8489b2e89a3560c5691762 this commit over one year ago introduced `webpack` as normal dependency of the project (it was already there as devDep), I could not find a reason for it.

Is it needed? I tried to play around removing it and it does not look like it's doing anything at all, let me know if it can be removed. I'll gladly make a PR for it.

**Comment by freedomlang** [comment]
it is unneeded, PR is welcome!
