### ISSUE TITLE
Publish new version using the prop-types package

### ISSUE THREAD

**Issue by nbarrera** [draft-js-plugins/draft-js-plugins#914]
I faced an issue while using the latest npm package (2.0.0-beta8).

My project react version was bumped up to 16.0.0 where the use of React.PropTypes is no longer supported and only the use of the new prop-types package is supported.

I 've found that the code at master already supports using prop-types package:

https://github.com/draft-js-plugins/draft-js-plugins/blob/e332b78552d3000b4fa91e665cd35d7151107670/draft-js-plugins-editor/src/Editor/index.js#L3

since 5 months ago, but the latest published package at npm is a year old now.

If you published a new version of the library with that change only I would be able to use your library and the latest react version.

**Comment by stevewillard** [comment]
The latest version is `2.0.0-rc8`, use that version instead.

**Comment by nbarrera** [comment]
Thanks for your response.

Is there a way to reach that `2.0.0-rc8` through `npm`?

From https://www.npmjs.com/package/draft-js-plugins-editor I just can see the latest as `2.0.0-beta1`

**Comment by stevewillard** [comment]
Yup. Honestly, I'm not sure why npm still reports that version. You can do:
```
npm i draft-js-plugins-editor@2.0.0-rc8
```

**Comment by nbarrera** [comment]
Great! I could install that version, thank you!
