### ISSUE TITLE
Serialize/Deserialize Draft

### ISSUE THREAD

**Issue by tim-soft** [draft-js-plugins/draft-js-plugins#916]
Is there a recommended way to save the editor State in a way that the drafts plugin side effects aren't lost? Converting the editor State to html results in links from linkify not being links for example.

Ideally, id like to save the editor state in a way that can be displayed later (as comments) but then be able to edit those comments, keeping the plugin effects. Any advice would be extremely helpful as I've grown really fond of draft plugins!

**Comment by dobesv** [comment]
It may depend on the particular plugin whether it supports this, but draft-js has APIs to save and restore the editor contents, e.g. https://draftjs.org/docs/api-reference-content-state.html#content

You can save the editor contents as JSON.  I don't think it works for editor state.  But, in any case, you should bring this up with draft-js for the more "general" concept of saving out the state, if their existing API doesn't work.

If there are particular plugins that aren't conforming to the existing way to store things into the draft-js content state, then you can file a bug for those plugins.  I suspect that most or all of them do support the existing draft-js content load / save system.
