### ISSUE TITLE
addMention callback provided to MentionSuggestions is not getting invoked

### ISSUE THREAD

**Issue by andpor** [draft-js-plugins/draft-js-plugins#917]
I provided a callback method to MentionSuggestion element per documentation onAddMention but this callback is not getting invoked when mention is selected. In fact, there is no code in MentionPlugin that looks at props.onAddMention property at all.

I should be invoked in onMentionSelect before the mention is added and ideally if the value returned from this callback is empty, code should abort adding the mention into draft model.

I have this code written if PR is welcome...

**Comment by sibelius** [comment]
please send the PR
