### ISSUE TITLE
How does the table plugin use?

### ISSUE THREAD

**Issue by zjj131415** [draft-js-plugins/draft-js-plugins#921]
How does the table plugin use?

**Comment by export-mike** [comment]
@zjj131415 FYI I have a table plugin you can use here: @mikeljames/draft-js-table-plugin

**Comment by IzaGz** [comment]
@export-mike where can i find the github repo of this?

**Comment by space11** [comment]
@export-mike do You provide source code and or documentation for Your table plugin ?

**Comment by export-mike** [comment]
@space11 its available at: https://github.com/export-mike/draft-js-plugins/tree/master/draft-js-table-plugin

We are no longer using this, so i will not be providing any further support.

but it has been used in production for awhile. its a pretty basic table it doesn't allow formatting or nested cells or images. 

feel free to ask me questions on the issues of the repo I'd be happy to point you in the right direction if you need it.

**Comment by space11** [comment]
@export-mike thanks.
Do you have a example how to use it?
I'm new to draft ecosystem. I'm not sure should I use through draft plugins or other way?

**Comment by export-mike** [comment]
@space11 see the stories: https://github.com/export-mike/draft-js-plugins/tree/master/stories/ExampleEditor

**Comment by export-mike** [comment]
```npm run storybook```
