### ISSUE TITLE
[Bug] Heart emoji ":heart:"

### ISSUE THREAD

**Issue by F3LENYR** [draft-js-plugins/draft-js-plugins#925]
Hey,

Thank you for this great emoji plugin.

Package : "draft-js-emoji-plugin"

I've found a bug with the emoji "heart", when I type ": heart :", when I press enter or click on it, the emoticon is not displayed :  
https://gyazo.com/72f4e6dad0da098b9a14d58f69a73cbf

(Sorry for my bad english because I'm french)

Thank you in advance.

**Comment by steven-qi** [comment]
I have opened a PR #938 for this.

**Comment by juliankrispel** [comment]
Hi @steven-qi. Thanks for opening the issue and contributing. However I'm struggling to reproduce this, it's working for me in the sandbox:

![heart-emoji](https://user-images.githubusercontent.com/1188186/32490693-f55bbf64-c3ab-11e7-8908-ccb6a6e74d17.gif)

@steven-qi can you reproduce this in a [codesandbox](codesandbox.io) please?

**Comment by steven-qi** [comment]
@juliankrispel Please check out the comments of the updated PR. I can reproduce it directly on demo page here with Windows 10 + Chrome 62.

https://www.draft-js-plugins.com/plugin/emoji

BTW, I am not the one who opened the issue, but I do encounter the same issue few days ago when I was trying to incorporate this to my own project..

**Comment by juliankrispel** [comment]
fixed
