### ISSUE TITLE
Mention Suggestion only gets triggered once

### ISSUE THREAD

**Issue by johndavedecano** [draft-js-plugins/draft-js-plugins#927]
Hi Nik and the team,

I am using mention suggestion plugin. When i initially type @ mention plugin works and shows the dropdown. However when there is already a content in the text box and type @ it no longer works.

```
  onChange = nextEditorState => {
    this.setState({
      editorState: nextEditorState,
    });
  };
```

**Comment by stevewillard** [comment]
I'm experiencing the same issue.

**Comment by thomasvidas** [comment]
Happening to me on 2.0.0-rc10 as well with both the default "@" and custom triggers. It's not happening on 2.0.0-rc8 though, so it must've been a change in the last few release candidates.

Also if you newline, you can trigger another mention

**Comment by stevewillard** [comment]
@thomasvidas thanks for the tip on downgrading to rc8 - that seems to have fixed the issue for me.

**Comment by sciyoshi** [comment]
It works only at the beginning of the line, but nowhere else. Looks like this change may have broken it https://github.com/draft-js-plugins/draft-js-plugins/commit/ddbb566f44c8a70a385f4fb3864c3c9aa4c3c08e#diff-c8ba337a5e28941ea2e2ac378060ef6b cc @juliankrispel
