### ISSUE TITLE
How to make all plugins use one store?

### ISSUE THREAD

**Issue by IronLu233** [draft-js-plugins/draft-js-plugins#934]
## Use-case/Problem
I want try to use draft-plugin-editor with several plugins.
The [static-toolbar-plugin](https://www.draft-js-plugins.com/plugin/static-toolbar)  and [markdown-shortcut-plugin](https://github.com/ngs/draft-js-markdown-shortcuts-plugin/)  use their own store. So when I change inline style by shortcut. The style of button which is in inline toolbar is not changed(It should be has an `.active` class name).
Is there any way to make all plugins use one store?

**Comment by simsim0709** [comment]
Hello, @IronLu233 

Do you still have the problem? It's working as expected.

You want to try newest version of the plugin. 

If you still have a problem, please give me reproduction link so I can look into it.

I will close for this now. You can reopen if you want.

Thank you.
