### ISSUE TITLE
Start versioning between releases

### ISSUE THREAD

**Issue by Aleksion** [draft-js-plugins/draft-js-plugins#94]
It seems package.json is still on 0.0.0 and npm haven't been bumped in quite a while. Is this intentional?

**Comment by nikgraf** [comment]
@Aleksion we did our first release yesterday with 0.0.0 - we will do a few improvements during the day and release 1.0.0 later :smile:

**Comment by Aleksion** [comment]
Sounds great! :+1:

**Comment by nikgraf** [comment]
@Aleksion I will wait with 1.0.0 a bit longer. There are a couple more ideas floating around how to improve the plugins before releasing
