### ISSUE TITLE
Static toolbar example is missing stylesheets in documentation

### ISSUE THREAD

**Issue by wildlifehexagon** [draft-js-plugins/draft-js-plugins#940]
I was following along on the static-toolbar documentation as seen here:

https://www.draft-js-plugins.com/plugin/static-toolbar

And I noticed the Themed Static Toolbar Example does not show two of the three stylesheets that it uses. Both buttonStyles and toolbarStyles are missing from the landing page content. It's easy to imply what the styling might be, but it seems both should be embedded like the way editorStyles.css is.

**Comment by easychen** [comment]
```
import 'draft-js-inline-toolbar-plugin/lib/plugin.css';
```
should be

```
import 'draft-js-static-toolbar-plugin/lib/plugin.css';
```
maybe .

**Comment by freedomlang** [comment]
it's now fixed
