### ISSUE TITLE
image show error

### ISSUE THREAD

**Issue by TonyGGC** [draft-js-plugins/draft-js-plugins#942]
add two picture into the Editor,  than delete one picture,  show me two pictures' info from 
"console.log(convertToRaw(editorState.getCurrentContent()));"

.................................................

 onChange(editorState) {
        this.setState({
            editorState,
        });

        console.log(convertToRaw(editorState.getCurrentContent()));
    };

...........................
<Editor
                            placeholder="通过拖拽向编辑框插入图片...."
                            editorState={this.state.editorState}
                            onChange={this.onChange}
                            plugins={plugins}
                            ref={(element) => {
                                this.editor = element;
                            }}
                        />
............................

How to update the  image info when have changed??     thank you so much!

**Comment by vikeen** [comment]
this looks like it may be the same issue as https://github.com/draft-js-plugins/draft-js-plugins/issues/952.
