### ISSUE TITLE
[side-toolbar-plugin] Positioning of sidebar toolbar

### ISSUE THREAD

**Issue by troelskn** [draft-js-plugins/draft-js-plugins#946]
Currently the SidebarToolbar is hardcoded to position on the left side. For my use case, I would like to move it to the right side instead. There is no obvious way to achieve this that I can figure out.

I would suggest either giving a config option `position` w values `left | right` or perhaps better -
 allow to hook in to the positioning code, that is currently locked inside `Toolbar.onEditorStateChange`. Perhaps one could pass a callback in config, that will be used to calculate the position?

**Comment by troelskn** [comment]
Somewhat related - I tried to hook in to `onEditorStateChange`, but can't, since it's hidden behind `decorateComponentWithProps`. It would be most helpful if this weren't the case. I would suggest changing this line:

    SideToolbar: decorateComponentWithProps(Toolbar, toolbarProps),

To something like:

    makeSideToolbar: function(DefaultToolbar) {
        return decorateComponentWithProps(DefaultToolbar || Toolbar, toolbarProps)
    },

That would allow me to extend `Toolbar` from the outside and pass it in.

**Comment by freedomlang** [comment]
@troelskn We've added a config option named `position` in the latest version. Cheers 🎉
