### ISSUE TITLE
How to refresh the physical content of the editor wthe it changed?

### ISSUE THREAD

**Issue by TonyGGC** [draft-js-plugins/draft-js-plugins#950]
My case：
1.  add two pictures into editor
2.  delete one of them

My problem：
I get two pitures‘ info from log  when I do the step one and step two?

please give me a help, thank you!!!

**Comment by pfftdammitchris** [comment]
What do you mean? I am confused

**Comment by TonyGGC** [comment]
@pfftdammitchris 

Insert two pictures in the editor, than delete one of them again, obtain two picture information from the log information.

console.log(convertToRaw(editorState.getCurrentContent()));

**Comment by freedomlang** [comment]
Looks like it's similar to #952
