### ISSUE TITLE
Image delete keep entity into state 

### ISSUE THREAD

**Issue by kalimantos** [draft-js-plugins/draft-js-plugins#952]
When deleting an image, the entity remains binded to the block above into the entityRanges and the entity is not removed from the entityMap.
https://codesandbox.io/s/4ql8746pl7
Step to reproduce:
- delete the image
- log the state in console with the proper button

state before:
```json
{
  "entityMap": {
    "0": {
      "type": "image",
      "mutability": "IMMUTABLE",
      "data": {
        "src": "https://www.draft-js-plugins.com/images/canada-landscape-small.jpg"
      }
    }
  },
  "blocks": [
    {
      "key": "9gm3s",
      "text": "You can have images in your text field. This is a very rudimentary example, but you can enhance the image plugin with resizing, focus or alignment plugins.",
      "type": "unstyled",
      "depth": 0,
      "inlineStyleRanges": [],
      "entityRanges": [],
      "data": {}
    },
    {
      "key": "ov7r",
      "text": " ",
      "type": "atomic",
      "depth": 0,
      "inlineStyleRanges": [],
      "entityRanges": [
        {
          "offset": 0,
          "length": 1,
          "key": 0
        }
      ],
      "data": {}
    },
    {
      "key": "e23a8",
      "text": "See advanced examples further down …",
      "type": "unstyled",
      "depth": 0,
      "inlineStyleRanges": [],
      "entityRanges": [],
      "data": {}
    }
  ]
}
```
state after:
```json
{
  "entityMap": {
    "0": {
      "type": "image",
      "mutability": "IMMUTABLE",
      "data": {
        "src": "https://www.draft-js-plugins.com/images/canada-landscape-small.jpg"
      }
    }
  },
  "blocks": [
    {
      "key": "9gm3s",
      "text": "You can have images in your text field. This is a very rudimentary example, but you can enhance the image plugin with resizing, focus or alignment plugins. See advanced examples further down …",
      "type": "unstyled",
      "depth": 0,
      "inlineStyleRanges": [],
      "entityRanges": [
        {
          "offset": 155,
          "length": 1,
          "key": 0
        }
      ],
      "data": {}
    }
  ]
}
```
i noticed that in the [draft-js media example](https://github.com/facebook/draft-js/blob/master/examples/draft-0-10-0/media/media.html) this didn't happen, but for now I've not been able to solve the problem

**Comment by kalimantos** [comment]
I found a solution but it doesn't solve the problem at all.
Adding
```
handleKeyCommand: (command, _, { getEditorState, setEditorState }) => {
  const newState = RichUtils.handleKeyCommand(getEditorState(), command);
  if (newState) {
    setEditorState(newState);
    return 'handled';
  }
  return 'not-handled';
},
```
to the returned object of image plugin it solves the problem. But i think this happens with all the atomic blocks, so putting this code in image-plugin could not be the better solution. The same problem also happen when using the focus plugin and deleting the image when is focused and this "quick fix" doesn't solve that.

Anyone have some idea where is the best place to fix them? And how fix the problem also for the focus plugin without having some conflicts between the 2 fix?

**Comment by vikeen** [comment]
I'm having this same issue. I've got a lot of documentation to read still, but not even sure where to start yet on debugging this issue.

I have noticed that you can remove the image, but you have to delete the empty space it takes on to the previous line.

**Comment by khsily** [comment]
It's not a real bug-fix but i fixed it like this as a tricky hack.

```
onChange = (editorState) => {
        let newEditorState = editorState;

        const content = editorState.getCurrentContent();
        const key = editorState.getSelection().getFocusKey();
        const type = content.getBlockForKey(key).getType();

        if (type === 'atomic') {
            const keyAfter = content.getKeyAfter(key);
            const newSelection = SelectionState.createEmpty(keyAfter);
            newEditorState = EditorState.forceSelection(editorState, newSelection);
        }

        this.setState({ editorState: newEditorState });
};

handleKeyCommand(command, editorState) {
        const newContent = RichUtils.handleKeyCommand(editorState, command);
        if (newContent) {
            this.onChange(newContent);
            return 'handled';
        } else {
            return 'not-handled';
        }
}
```

I just tried to move cursor after the atomic block so that I can delete images without the bug.

**Comment by freedomlang** [comment]
found a [smimilar issue](https://github.com/facebook/draft-js/issues/1510) in draft-js

**Comment by MattyBalaam** [comment]
OK, glad I’m not the only one seeing this. I think it might be related to this issue I have opened: https://github.com/draft-js-plugins/draft-js-plugins/issues/1122

**Comment by rrt2850** [comment]
Was this issue fixed? I'm still running into it in draft-js version 0.11.7
