### ISSUE TITLE
Use Popper.js for tooltip positioning

### ISSUE THREAD

**Issue by FezVrasta** [draft-js-plugins/draft-js-plugins#963]
Hi! I think the text-selection positioned tooltips would benefit if you used Popper.js to position them.

Here you find a little demo to show how easy is it to position elements with it:
https://codepen.io/FezVrasta/pen/vWXQdq

As you can see, you will get automatic flip to make the tooltip stay in the viewport and lot of advanced features that you can read in the popper.js.org website

**Comment by k-zakhariy** [comment]
How to implement this into DraftJS ?

**Comment by elalienx** [comment]
Hi @FezVrasta , nice code implementation. I just found a little bug. When you select a big paragraph like the third one in your example. The tooltip jumps way to much to the bottom on scroll. 
<img width="1280" alt="screen shot 2018-02-01 at 14 00 23" src="https://user-images.githubusercontent.com/6117977/35697590-9d1d9336-0758-11e8-9e4a-542e68ae19b5.png">

**Comment by FezVrasta** [comment]
Don't close this issue. This is an automatic message by [Fresh](https://github.com/c-hive/fresh) - a bot against stale bots.

**Comment by FezVrasta** [comment]
Don't close this issue. This is an automatic message by [Fresh](https://github.com/c-hive/fresh) - a bot against stale bots.
