### ISSUE TITLE
Inline Toolbar position off within modal

### ISSUE THREAD

**Issue by jrock17** [draft-js-plugins/draft-js-plugins#965]
My editor lives within a modal. It looks like the inline toolbar positioning is slightly off in this case (see screenshot).

If I change this line (line 78) in Toolbar/index.js:
`top: selectionRect.top - relativeRect.top - toolbarHeight`

... and subtract 10 pixels, it lines up perfectly:
`top: selectionRect.top - relativeRect.top - toolbarHeight - 10`

But that's a hack. Any ideas for a permanent fix?

![inlinetoolbar](https://user-images.githubusercontent.com/1270524/32707903-f3a652a4-c7db-11e7-972e-45b49f9bb567.jpg)

**Comment by dobesv** [comment]
Have you tried adding position:relative to some parent element of the editor ?

**Comment by juliankrispel** [comment]
fixed in #1031
