### ISSUE TITLE
Expose BlockTypeSelect through draft-js-side-toolbar-plugin

### ISSUE THREAD

**Issue by divyenduz** [draft-js-plugins/draft-js-plugins#974]
## Use-case/Problem

I might be missing something but I feel customizing `draft-js-side-toolbar-plugin` is not as straightforward as `draft-js-inline-toolbar-plugin`. 

For, `draft-js-inline-toolbar-plugin` I was able to provide the `structure` option as suggested by the documentation. 

When I try the same with `draft-js-side-toolbar-plugin`, the CSS breaks as shown in the image below. 
<img width="224" alt="screen shot 2017-11-19 at 5 07 54 pm" src="https://user-images.githubusercontent.com/746482/32990246-3b6fdb80-cd4c-11e7-9da8-ff9315eec414.png">

A quick dive into the code suggests that the plugin uses `DefaultBlockTypeSelect` that in turn uses `BlockTypeSelect` to fill the default set of buttons but I could not find an API to change the structure wrapped with BlockTypeSelect. Is this the case, and if yes, is this intentional? 

A solution can be to expose `BlockTypeSelect` through the `draft-js-side-toolbar-plugin`, so, it can be imported like 

`import createSideToolbarPlugin, { BlockTypeSelect } from "draft-js-side-toolbar-plugin";`

Then, we can use it to change the underlying structure and retain the default CSS of `draft-js-side-toolbar-plugin`. 

What do you think of this suggestion? If I am missing something, please let me know. If we agree on this or some other way to get around this, I can work on a PR :)

Please let me know. 

Lastly, thanks for putting all the hard work in the plugins, they are amazing.

**Comment by divyenduz** [comment]
I think I found an [example of](https://github.com/simsim0709/draft-js-plugins/tree/master/draft-js-divider-plugin) editing the side-toolbar. Is this the right approach to get the BlockTypeSelect? 

Like this
```
import BlockTypeSelect from 'draft-js-side-toolbar-plugin/lib/components/BlockTypeSelect';
```

**Comment by simsim0709** [comment]
Hello, @divyenduz 

Do you still want this feature? If so, could you make a pr? It would be very appreciated.

**Comment by divyenduz** [comment]
@simsim0709 : Sure! I came up with a PR to start the discussion. Please let me know if any changes are needed. Thanks!
