### ISSUE TITLE
Side toolbar not placed correctly when parent(s) is positioned relative

### ISSUE THREAD

**Issue by robgietema** [draft-js-plugins/draft-js-plugins#976]
When the editor is inside a parent (or multiple parents) with position relative the side toolbar is not placed correctly. It will be place absolute inside the relative parent but should be absolute to the document. Could be the same issue as the inline toolbar #531

**Comment by lednhatkhanh** [comment]
+1 for this problem, I am facing the same thing....

**Comment by juliankrispel** [comment]
this was fixed in #1029
