### ISSUE TITLE
Contributing Workflow

### ISSUE THREAD

**Issue by export-mike** [draft-js-plugins/draft-js-plugins#984]
Hey,

I'm in the middle of creating a plugin, and notice the project has some repetitive changes regarding local requires within the repo, publishing and building the project.

Just a thought has anyone tried using lerna with this project? If so were there issues? 

Otherwise I'm keen to contribute a PR with updated config. let me know if you think this will be useful.

Cheers,

**Comment by freedomlang** [comment]
Duplicate of #282

**Comment by juliankrispel** [comment]
@export-mike I have been thinking about lerna, would be nice to have a nicer workflow for managing the project, if you'd still like to discuss feel free to reach me on the draft js slack ♥️
