### ISSUE TITLE
Pressing enter twice in a ordered or unordered list should fallback to normal paragraph

### ISSUE THREAD

**Issue by robgietema** [draft-js-plugins/draft-js-plugins#985]
When you have selected the ordered or unordered list style you can add list items by pressing enter. When you press enter twice it should fall back to paragraph style.

**Comment by simsim0709** [comment]
Hi, @robgietema 

I think it's not related with draft-js-plugins itself, but draft-js.

But, you might check this plugin: https://github.com/icelab/draft-js-block-breakout-plugin
It has the feature you request.

Thank you.
