### ISSUE TITLE
draft-js-mentions-plugin: Viewarea detection is not present

### ISSUE THREAD

**Issue by comatory** [draft-js-plugins/draft-js-plugins#986]
## Steps to reproduce

1. Go to [https://www.draft-js-plugins.com/plugin/mention](https://www.draft-js-plugins.com/plugin/mention) to the section with "Simple example" text area
2. Resize window to approximately 640px.
3. Write enough text so that when you add a mention you're at the end of the line in editor

Result:

![](https://i.imgur.com/bAZE2QZ.png)

I don't know if this is a bug or if it's intentionally left out, however when the pop-over for mentions is displayed and the editor is right at  the edge of view area, the pop-over is not repositioned.

I somehow assumed that this would be taken care of or maybe I'm missing something.

**Comment by THook** [comment]
Hello @comatory, this behaviour comes from an `overflow` CSS attribute being set to `hidden` or at least, not `visible` as it should. It may come from parent component or the Mention plugin CSS class itself, which you can override to match the expected behaviour.

Hope it helps

**Comment by comatory** [comment]
Yes I get that, it's just a bit _emabarassing_ I think, I'd expect it to work out of the box, I think the use-case is so apparent in real life that lot of people are bound to run into it.

I managed to follow documentation and create repositioning callback for `positionSuggestions` options that looks like this:

```
  _positionSuggestions = ({ decoratorRect, popover, state, props }) => {
    const popoverPosition = (decoratorRect.x || decoratorRect.left) + popover.offsetWidth
    const {
      left,
      ...restProps
     } = positionSuggestions({ decoratorRect, popover, state, props })

    let adjustedLeft = null
    if (popoverPosition > window.innerWidth) {
      adjustedLeft = `${parseFloat(left) - (popoverPosition % window.innerWidth)}px`
    }

    return {
      left: adjustedLeft || left,
      ...restProps,
    }
  }
```

so my plugin configuration looks like this:

```
  _mentionPlugin = createMentionPlugin({
    entityMutability: 'IMMUTABLE',
    positionSuggestions: this._positionSuggestions,
  })
```

**Comment by THook** [comment]
That's really nice! I ended up doing something pretty similar with CSS only but was struggling with Instagram-like positioning of mentions. This will help!

**Comment by amcdnl** [comment]
It would be great if we could leverage [popper.js](https://popper.js.org/popper-documentation.html) to handle this. This is what most libraries like material ui use internally.

**Comment by jack-arms** [comment]
These solutions work for when the popover is opened initially, but `positionSuggestions` doesn't seem to get called when the window resizes so the popover will still get cut off if you shrink the window after opening. Has anyone found a workaround to this?

**Comment by comatory** [comment]
> These solutions work for when the popover is opened initially, but `positionSuggestions` doesn't seem to get called when the window resizes so the popover will still get cut off if you shrink the window after opening. Has anyone found a workaround to this?

Yes the workaround for this is to listen to window `onresize` event. Perhaps try using [react-window-resize-listener`](https://github.com/cesarandreu/react-window-resize-listener) and when this happens, recalculate the position (you have to pass callback to the `positionSuggestions` function to do this). I think that should work.

Closing for now since this does not seem to move forward anyway.

**Comment by gfigueras-sage** [comment]
> It would be great if we could leverage [popper.js](https://popper.js.org/popper-documentation.html) to handle this. This is what most libraries like material ui use internally.

It seems popper is now supported for mentions through popperOptions parameter, but there's no examples on the docs... Any idea on how to implement it?

**Comment by fxOne** [comment]
@gfigueras-sage you can find the documentation for `popper.js` on there homepage. What are you missing?

**Comment by gfigueras-sage** [comment]
> @gfigueras-sage you can find the documentation for `popper.js` on there homepage. What are you missing?

Not sure if I'm using popper correctly, but for instance, this is what I have but nothing happens:

```
createMentionPlugin({
      entityMutability: 'IMMUTABLE',
      popperOptions: {
        placement: 'left',
        modifiers: [
          {
            name: 'offset',
            options: {
              offset: [10, 20],
            },
          },
        ],
      },
      mentionComponent: MentionText })
```

**Comment by fxOne** [comment]
I just tried it with
```
const mentionPlugin = createMentionPlugin({
  popperOptions: {
    placement: 'left',
    modifiers: [
      {
        name: 'offset',
        options: {
          offset: [0, 100],
        },
      },
    ],
  },
});
```
which worked well.
![image](https://user-images.githubusercontent.com/5929640/120936522-7f0a9d80-c708-11eb-9152-fca8173a9c13.png)

**Comment by gfigueras-sage** [comment]
> I just tried it with
> 
> ```
> const mentionPlugin = createMentionPlugin({
>   popperOptions: {
>     placement: 'left',
>     modifiers: [
>       {
>         name: 'offset',
>         options: {
>           offset: [0, 100],
>         },
>       },
>     ],
>   },
> });
> ```
> 
> which worked well.
> ![image](https://user-images.githubusercontent.com/5929640/120936522-7f0a9d80-c708-11eb-9152-fca8173a9c13.png)

I updated mentions plugin from 4.4.1 to 4.5.1 and now it seems it works ;)

Thanks for the example.
