### ISSUE TITLE
list-type invalid。。。

### ISSUE THREAD

**Issue by zzlw** [draft-js-plugins/draft-js-plugins#989]
click list 'list-type' invalid
<img width="688" alt="wx20171207-101256 2x" src="https://user-images.githubusercontent.com/29618863/33695258-4bc4a2f6-db37-11e7-876d-c7fd640d2ce7.png">

**Comment by juliankrispel** [comment]
Sry there’s insufficient info in here.

I don’t know whether this is a bug report or a feature request :/

If you’d like to submit either - please open a new issue and fill out the template.

Thanks so much!

Cheers
