### ISSUE TITLE
onSearchChange not firing when typing dot (.)

### ISSUE THREAD

**Issue by flyingpath** [draft-js-plugins/draft-js-plugins#996]
Problem

The onSearchChange not firing when typing dot (.).

And my mention list have mention begin with . (ex.   ".load")
Do you have any suggestion?

Thanks

Tao

**Comment by andriystabryn** [comment]
@flyingpath have you resolved the problem?

**Comment by kalemi19** [comment]
@flyingpath just ran into this issue as well. How did you fix it? Monkey patching it seems a little complicated.

**Comment by fxOne** [comment]
@kalemi19 have you tried to set your own `mentionRegExp`?
