### ISSUE TITLE
[draft-js-mention-plugin] Feature request: Have a div with scroll bar to deal with long mentions

### ISSUE THREAD

**Issue by flyingpath** [draft-js-plugins/draft-js-plugins#997]
Hi:

When mention list is too long, the div get long too.
I tried to add style max-height: 200px and overflow-y: auto.
But I can't move the scroll bar by press "down button".

![default](https://user-images.githubusercontent.com/21292793/34195947-d1cd0a60-e59a-11e7-8cfb-ce62db3cd360.png)

( the picture shows that no on-focus div with blue background, it in the bottom overflow)

Do you have any suggestion?

Thanks very much!

Tao

**Comment by freedomlang** [comment]
@flyingpath overflow-y and max-height should did the trick, don't know why it didn't work! btw, a codesandbox would be nice !

**Comment by tcosentino** [comment]
@freedomlang I am actually looking to do the same thing. I was able to get it working for the most part via overflow and max-height. I wrapped `MentionSuggestions` in a `div.mention-suggestions` and then set the css like so:

```
.mention-suggestions > div {
  max-height: 250px;
  overflow: scroll;
}
```

I then made a new suggestions filter that doesn't limit to 5 so that all of my suggestions are presented. The only issue I still have is that as I change my selection with up and down arrows the div does not scroll to keep them visible. I've done this with a list before but not sure where I should be handling this with the mentions plugin. Any recommendations before I start digging too far?

**Comment by juliankrispel** [comment]
@tcosentino you could either open a pull request to fix this behaviour or implement your own `MentionSuggestions` component.

**Comment by flyingpath** [comment]
Yes, my issue is as @tcosentino say. 
And I finally added callback function to control the scroll bar at down arrow events.

Thanks guys!

**Comment by safonoi** [comment]
@flyingpath Please tell me how did you add callback function to control the scroll bar at up and down arrow events? thanks a lot

**Comment by flyingpath** [comment]
I write up and down separately..
Something like below.

       
      if (e.which == 38) {
             let MentionDiv = document.querySelector('.draftjsWithMention>div:nth-child(2)')
             if(MentionDiv){
                 const oriScrollTop = MentionDiv.scrollTop
                 if (oriScrollTop-35< 0){
                     MentionDiv.scrollTop = 0
                 }else{
                     MentionDiv.scrollTop -= 35
                 }
             }
        }


               <div
                    id={id}
                    className = 'draftjsWithMention' 
                    onClick={this.focus}
                    ref={div=>this.draftBody=div}
                >
                    <Editor
                        editorState={this.state.editorState}
                        onChange={this.onChange}
                        plugins={plugins}
                        ref={(element) => { this.editor = element }}
                        onTab={this.onTab}
                        spellCheck={true}
                        handlePastedText={this.handlePaste} 
                        customStyleMap={this.StyleMap}
                    />
                    <MentionSuggestions
                        onSearchChange={this.onSearchChange}
                        suggestions={suggestions}
                        entryComponent={Entry}
                        onAddMention={this.onAddMention}
                    />
                </div>

**Comment by f0rdream** [comment]
> I wrote up and down separately without focus.
> Something like below.. more stupid XD
> 
> ```
>   if (e.which == 38) {
>          let MentionDiv = document.querySelector('.draftjsWithMention>div:nth-child(2)')
>          if(MentionDiv){
>              const oriScrollTop = MentionDiv.scrollTop
>              if (oriScrollTop-35< 0){
>                  MentionDiv.scrollTop = 0
>              }else{
>                  MentionDiv.scrollTop -= 35
>              }
>          }
>     }
> 
> 
>            <div
>                 id={id}
>                 className = 'draftjsWithMention' 
>                 onClick={this.focus}
>                 ref={div=>this.draftBody=div}
>             >
>                 <Editor
>                     editorState={this.state.editorState}
>                     onChange={this.onChange}
>                     plugins={plugins}
>                     ref={(element) => { this.editor = element }}
>                     onTab={this.onTab}
>                     spellCheck={true}
>                     handlePastedText={this.handlePaste} 
>                     customStyleMap={this.StyleMap}
>                 />
>                 <MentionSuggestions
>                     onSearchChange={this.onSearchChange}
>                     suggestions={suggestions}
>                     entryComponent={Entry}
>                     onAddMention={this.onAddMention}
>                 />
>             </div>
> ```

Actually you could do this by implementing your own `mentionSuggestionsComponent`, it's may be better to listen to the dom directly.

**Comment by hashina** [comment]
> I wrote up and down separately without focus.
> Something like below.. more stupid XD
> 
> ```
>   if (e.which == 38) {
>          let MentionDiv = document.querySelector('.draftjsWithMention>div:nth-child(2)')
>          if(MentionDiv){
>              const oriScrollTop = MentionDiv.scrollTop
>              if (oriScrollTop-35< 0){
>                  MentionDiv.scrollTop = 0
>              }else{
>                  MentionDiv.scrollTop -= 35
>              }
>          }
>     }
> 
> 
>            <div
>                 id={id}
>                 className = 'draftjsWithMention' 
>                 onClick={this.focus}
>                 ref={div=>this.draftBody=div}
>             >
>                 <Editor
>                     editorState={this.state.editorState}
>                     onChange={this.onChange}
>                     plugins={plugins}
>                     ref={(element) => { this.editor = element }}
>                     onTab={this.onTab}
>                     spellCheck={true}
>                     handlePastedText={this.handlePaste} 
>                     customStyleMap={this.StyleMap}
>                 />
>                 <MentionSuggestions
>                     onSearchChange={this.onSearchChange}
>                     suggestions={suggestions}
>                     entryComponent={Entry}
>                     onAddMention={this.onAddMention}
>                 />
>             </div>
> ```

Could you provide your full code please ? thanks a lot

**Comment by eschaefer** [comment]
If you set your `theme.mentionSuggestionsEntryFocused` to `.mentionSuggestionsEntryFocused`, then just do something like this:


```jsx

handleKeyUp = () => {
    const el = window.document.querySelector('.mentionSuggestionsEntryFocused');
	if (el) el.scrollIntoView();
};

componentDidMount() {
    window.document.addEventListener('keyup', this.handleKeyUp);
}

componentWillUnmount() {
	window.document.removeEventListener('keyup', this.handleKeyUp);
}


```

**Comment by sibelius** [comment]
is this fixed?

should we add this to FAQ?

**Comment by TheTedAdams** [comment]
I think a max-height suggestions popup with scrollbar and a good keyboard nav experience would be a pretty common scenario people will want to handle.

`max-height` and `overflow-y: auto;` on whatever class you put in `theme.mentionSuggestions` gets you scrollable pretty quick. The only thing that's lame is that if you keep hitting down arrow you end up focusing suggestions that are not visible.

I've been playing with this a bit and have found this is a pretty easy way to handle it:

```ts
export const Entry = ({
  mention,
  theme,
  searchValue,
  isFocused,
  ...parentProps
}) => {
  const ref = useRef<HTMLDivElement>(null);
  useEffect(() => {
    if (isFocused) {
      ref.current?.scrollIntoView({ behavior: 'smooth', block: 'nearest' });
    }
  }, [isFocused]);

  return (
    <div {...parentProps} key={mention.key} ref={ref}>
		{/* The rest of my custom entry code */}
    </div>
  );
};
```

This has the questionable effect of scrolling on mouse highlight of an entry that is off partially visible at top or bottom... but I can't decide if I dislike that or not.

**Comment by fxOne** [comment]
@TheTedAdams Thanks for you sample code. I used your solution to fix this issue as I don't think that the mouse over might be an issue.
