### ISSUE TITLE
How can you use this without CSS modules?

### ISSUE THREAD

**Issue by cmmartin** [draft-js-plugins/draft-js-plugins#999]
I'm working on a project that can't use CSS modules. I assumed I could copy and paste the CSS into my own stylesheets, but CSS modules generate unique hashes for the class names. Is there any way to use this without CSS modules?

**Comment by eltiare** [comment]
Well, this would explain why I've been having issues trying to incorporate this into my SASS stylesheets. >:(

**Comment by juliankrispel** [comment]
You can absolutely just use css classnames instead - with the plugin config!

**Comment by apoorvans** [comment]
@juliankrispel can you please share an example of this? I made local copies of button and toolbar styles and tried to customize them. But nothing seems to happen.
`
import buttonStyles from './buttonStyles.css';

import toolbarStyles from './toolbarStyles.css';

const staticToolbarPlugin = createToolbarPlugin({theme: { toolbarStyles, buttonStyles }});
`
